### PR TITLE
Changed cmd+w with no open tabs to close window

### LINKED ISSUE #5322: `Cmd+W` with no open tabs doesn't close the window
**Is your feature request related to a problem? Please describe.**

Just a tiny nit (feel free to say if these tiny bugs aren't helpful), but when the window is empty, I would have expected `Cmd+W` to act like `Cmd+Shift+W`, but it currently does nothing.

(See: behaviour in Atom, VS Code)

### PR DESCRIPTION
**Pull request by williamviktorsson**
Fixes https://github.com/zed-industries/zed/issues/5322

Release Notes:

- Changed cmd+w with no open tabs to close window [#5322](https://github.com/zed-industries/zed/issues/5322)

https://github.com/zed-industries/zed/assets/22855292/113b1635-ae30-4718-a3d3-758a4bf53714

### CODE REVIEW

**Comment by williamviktorsson** [comment]
@cla-bot check

**Review by mikayla-maki — APPROVED** [review]
Looks great! Once the merge conflict is fixed, I'd love to merge this :)

**Comment by williamviktorsson** [comment]
Two thoughts:

- While this fixes the issue, and is similar to default behaviour of other apps, one might want to be able to configure the behaviour.

- I noticed that if you cmd+w with focus on terminals, it closes terminals first, then editor windows, then application window. However, if you focus editor windows and start cmd+w, it will close the editors then the application window, and focus does not go to terminals first. This is consistent with how VSCode does it, just thought I'd mention it cause I was expecting terminals to count as active windows.

**Comment by williamviktorsson** [comment]
I really would also like to know how if it would be possible to return to the previous project after closing the window with "CloseWindow", in the same way you return to the previous project after closing with "Quit" ?

**Comment by mikayla-maki** [comment]
Thank you!

**Comment by mikayla-maki** [comment]
> I really would also like to know how if it would be possible to return to the previous project after closing the window with "CloseWindow", in the same way you return to the previous project after closing with "Quit" ?

I don't think there would be a way. We save the orientation of your tabs every time you open or close one.

**Comment by williamviktorsson** [comment]
> > I really would also like to know how if it would be possible to return to the previous project after closing the window with "CloseWindow", in the same way you return to the previous project after closing with "Quit" ?
> 
> I don't think there would be a way. We save the orientation of your tabs every time you open or close one.

I feel like this is a good feature and I'll make an issue out of it explaining why, along with a PR to fix it.

**Comment by baldwindavid** [comment]
Darn, this got reverted. @williamviktorsson , are you interested in working on a modified version of this feature (i.e. with a setting defaulted to `false` as noted in #10986)?

**Comment by williamviktorsson** [comment]
> Darn, this got reverted. @williamviktorsson , are you interested in working on a modified version of this feature (i.e. with a setting defaulted to `false` as noted in #10986)?

I could but I’m occupied for a few weeks. The changes in my reverted pr really was few lines of code so it should be easy to include and wrap in a setting check :-)

**Pull request merged**
