### PR TITLE
Handle first click on Zed window

### LINKED ISSUE #4336: Focus editor component under cursor instead of last active component
### Check for existing issues

- [X] Completed

### Describe the feature

Please propagate the initial click that brings focus to the editor so that the clicked element inside the editor gets focus. Tried vscode, it focuses on click. Also in chrome browser, clicking on a different tab will switch to it immediately.

### If applicable, add mockups / screenshots to help present your vision of the feature

Problem:

Since switching from vs code to zed I have been sometimes typing into the wrong panel in the zed editor. It happens when you want to swith to Zed from another application by clicking (e.g. I click on the terminal panel), but Zed does not switch focus to it, opting to keep the focus the same as when you left the editor. 

Current process: 
1) Zed main panel active
2) switch to another application, keeping Zed visible
3) click on Zed terminal panel
4) start typing -> source code in the main panel is being changed (or whichever panel was focused when leaving zed)

Changed flow:
1) Zed main panel active
2) swith to another application, keeping Zed visible
3) click on Zed terminal panel
4) (CHANGE) start typing -> terminal has become focused as the user clicked on it. User is successfully typing commands in the terminal.

### PR DESCRIPTION
**Pull request by xyzqm**
Fixes #4336

### CODE REVIEW

**Comment by mikayla-maki** [comment]
I wonder if we should always do this 🤔

**Comment by mikayla-maki** [comment]
I think that commit should be rolled back. This seems like it could be a macOS specific API, and I’d rather not have that in the general-purpose abstraction.

**Comment by danielzsh** [comment]
Makes sense, where do you suggest putting the logic instead?

**Comment by mikayla-maki** [comment]
Hmm, did a little experimenting and I don't think we're setup to handle this well yet. Some apps (Firefox) don't have this behavior, while VSCode integrates this behavior with the application: generally it uses accept_first_mouse (e.g. clicking on status bar buttons) except the file explorer specifically doesn't react to the first mouse, beyond focusing the panel. 

In Zed, we don't have this distinction, so setting `accept_first_mouse` to `YES` (like in this PR), makes clicking into the project panel feel very bad.

**Comment by mikayla-maki** [comment]
If we wanted to solve this problem, I think we should unconditionally return `YES` to `accepts_first_mouse` and then refactor the project panel, channels panel, and etc. to have similar activating-click-focus logic (like VSCode's explorer).

**Comment by danielzsh** [comment]
Looking at the code, am I correct in understanding that each Zed window consists of exactly one `NSView`? The documentation [here](https://developer.apple.com/documentation/appkit/views_and_controls?language=objc) mentions that `NSView`s are often nested within each other (and having each pane being a separate NSView would certainly greatly simplify implementation of this feature) but that doesn't appear to be the case for Zed.

**Comment by mikayla-maki** [comment]
Yep! We use a single NSView, grab all of the interactions we care about from it, and then do our own dispatching.

**Comment by mikayla-maki** [comment]
We’re making a UI framework.

**Comment by danielzsh** [comment]
Maybe my understanding is a bit skewed b/c of webdev; is `NSView` analogous to `div`? If yes, why would a web UI framework abstain from using native `div` nesting in favor of internally re-implementing the same functionality?

**Comment by mikayla-maki** [comment]
Because we're _creating_ the `<div>`, NSView is just the way you have to do everything on macOS.

**Comment by danielzsh** [comment]
Would it be possible to embed the info into `gpui::ClickEvent` like:
```rust
pub struct ClickEvent {
    /// The mouse event when the button was pressed.
    pub down: MouseDownEvent,

    /// The mouse event when the button was released.
    pub up: MouseUpEvent,

    pub first_mouse: bool,
}
```
Or does that still suffer from this issue:
> This seems like it could be a macOS specific API, and I’d rather not have that in the general-purpose abstraction.

**Comment by mikayla-maki** [comment]
Perhaps? It might also work to check the windows activation state before processing clicks in the ProjectPanel code directly. Either way, I think I'll close this PR for now and we can revisit with that other approach.

**Pull request closed without merging**
