### PR TITLE
Add separate JSONC language

### LINKED ISSUE #860: JSONC Support
### Check for existing issues

- [X] Completed

### Describe the feature

Following this issue (https://github.com/biomejs/biome-zed/issues/11), it would be great to differentiate JSON and JSONC, this way we could disable Biome for JSON for example and still work with JSONC without the need or additional plugins config files, etc. 

### If applicable, add mockups / screenshots to help present your vision of the feature

Screenshot 2024-06-02 at 15 37 38

### PR DESCRIPTION
**Pull request by luckydye**
Resolves https://github.com/zed-industries/extensions/issues/860 and https://github.com/zed-industries/zed/issues/10921, also https://github.com/biomejs/biome-zed/issues/11.

### Problem:
When opening .json files, zed allows comments by default in the JSON language, which can cause some problems.
For example, language-servers also get "json" as the language, which may show errors for those comments.

image

### Solution:

This PR adds a JSONC language. 

image

This allows for more specific configuration for language servers. 
Also any json file can be set explicitly to be JSONC using the file_types setting:

```jsonc
{
  "file_types": {
    // set all .json files to be seen as JSONC
    "JSONC": ["*.json"]
  }
}
```

Release Notes:

- N/A

### CODE REVIEW

**Comment by luckydye** [comment]
@Angelk90 I would rather not include it in this PR :) 
And I'd argue an extension may be better suited for json5.

**Comment by osiewicz** [comment]
Hey, we should also associate Zed's .json config files as jsonc by default. As you've remarked, this can be done by changing  the default values for`file_types` in `assets/settings/default.json`.

**Comment by luckydye** [comment]
Is there a way to more specifically target zed config files other then:
```json
  "file_types": {
    "JSONC": ["settings.json", "tasks.json", "keymap.json"]
  }
```
Since this will turn any file named that way into JSONC, which may cause confusion(?).

**Comment by osiewicz** [comment]
I believe you could filter on the files being in `.zed/` or `zed/` subdirectory, since that would match both global and worktree-local files.

**Comment by luckydye** [comment]
If I understand it correctly, file_types is only matched with filename+extension, not the full path.
https://github.com/zed-industries/zed/blob/e829a8c3b0564bc902cc0d0a530099be7f0f036e/crates/language/src/language_registry.rs#L512
Not sure yes how else im going to do this.

**Comment by osiewicz** [comment]
> Maybe file_type should match on the path too?

Yeah, I think that'd make sense.

**Comment by luckydye** [comment]
I got it working now I think. 

The `file_types` in `defaults.json` were being ignored, so I had to merge the defaults with the user settings.

**Comment by ClearedFram3** [comment]
Can someone explain the issue with renaming `settings.json` to `settings.jsonc`?

**Comment by osiewicz** [comment]
> The file_types in defaults.json were being ignored, so I had to merge the defaults with the user settings.

Did you have an override in your settings? I believe user settings override the defaults (they don't get merged), so the user would have to respecify it in their settings.

> Can someone explain the issue with renaming settings.json to settings.jsonc?
On one hand we could do that, but on the other it feels bad to break backwards compatibility if there's a way for us to handle it gracefully.

**Comment by luckydye** [comment]
> Did you have an override in your settings? I believe user settings override the defaults (they don't get merged), so the user would have to respecify it in their settings.

I tested it with, and without user overrides in user settings and project settings (.zed/settings.json). The defaults were *never* applied to file_types.

My understanding might be incorrect here. I was thinking, when someone overrides the file_types for "JSONC" in user or project settings, it would be weird if zed settings files are suddenly not JSONC anymore.
I can take out the merging part tho.

**Comment by osiewicz** [comment]
No, I think you're right. Let's keep it as is.

**Pull request merged**
