### PR TITLE
Add simple support for wrapscan

### PR DESCRIPTION
**Pull request by Kalmaegi**
For: #13417 

This is a simple version, I'm not sure if we just need to limit this feature to vim mode, or maybe in normal editor mode, which involves other logic like the location of the setting

Release Notes:

- N/A

### CODE REVIEW

**Comment by weartist** [comment]
Because it affects some of the previous behaviors, the example test will not pass for the time being. If the solution is feasible, I will adjust it together.

**Comment by ConradIrwin** [comment]
@weartist This makes sense to me (and making it a setting at the Zed level not the vim level seems correct). Vim calls it `wrapscan`, VSCode calls it `editor.find.loop`; not sure the best Zed name, but probably something like `"search_wrap"`? that defaults to true.

**Comment by weartist** [comment]
I am not sure how to modify the current global configuration in the test. If you could let me know how to do it, I can add a test case. Thanks :D

**Comment by ConradIrwin** [comment]
You should be able to do something like:

```
        cx.update_global(|store: &mut SettingsStore, cx| {
            store.update_user_settings::<EditorSettings>(cx, |s| {
                s.search_wrap = Some(false)
            });
        });
```

I think we should probably go with the neovim approach, because it means that if you do `d /x` you can be sure that your cursor will only delete forward (or not at all). That said we may need to show a toast when you hit the end in that case.

I'll play with it a bit later.

**Comment by weartist** [comment]
> You should be able to do something like:
> 
> ```
>         cx.update_global(|store: &mut SettingsStore, cx| {
>             store.update_user_settings::<EditorSettings>(cx, |s| {
>                 s.search_wrap = Some(false)
>             });
>         });
> ```
> 
> I think we should probably go with the neovim approach, because it means that if you do `d /x` you can be sure that your cursor will only delete forward (or not at all). That said we may need to show a toast when you hit the end in that case.
> 
> I'll play with it a bit later.

I didn't notice operations like d/x, so the current code is only limited to the editor's search, maybe we should expand it

**Comment by ConradIrwin** [comment]
@weartist I pushed up an vim-style version. Does that work for you?

Things like `d/` already work because they use the same code-path to find the next match.

**Comment by weartist** [comment]
> @weartist I pushed up an vim-style version. Does that work for you?
> 
> Things like `d/` already work because they use the same code-path to find the next match.

It works great, I've added a test case and tested the health in a couple of cases and it looks good

**Comment by weartist** [comment]
> @weartist I pushed up an vim-style version. Does that work for you?
> 
> Things like `d/` already work because they use the same code-path to find the next match.

There are still some issues with the "d/" command, I'll look for where the problems are later and add tests

> @weartist I pushed up an vim-style version. Does that work for you?
> 
> Things like `d/` already work because they use the same code-path to find the next match.

I've tested it and added test cases, and it looks like it's working just fine so far!

**Comment by ConradIrwin** [comment]
Thanks for the tests too!

**Pull request merged**
