### PR TITLE
Add macOS native window tabs

### PR DESCRIPTION
**Pull request by gaauwe**
Closes #14722, #4948, #7136

Adds support for native window tabs on macOS, allowing users to open multiple instances of Zed in the same window. Works similar to how vscode handles native tabs (https://code.visualstudio.com/updates/v1_12#_macos-sierra-tabs). Added a default setting and updated the docs with information about the new setting.

image

It is my first time contributing to Zed, let me know if anything is missing (:

Release Notes:

- Added support for macOS native window tabs

### CODE REVIEW

**Comment by gaauwe** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
Thanks for this!

We are not planning to ship macOS tabs right now as it makes an already complicated navigational hierarchy even harder to parse.

Currently if you want to open multiple projects in Zed you can use the "add folder to project" command (also available in the right click menu on the project panel).

**Comment by felixroos** [comment]
I'm sad that this PR got rejected in this way (without any discussion). with a hidden file tab bar (tab_bar.show=false), the navigation is very easy to parse imo:

image

vs

image

as @ahetzm said, it's a different workflow to add folders to a project. for example, a typical workflow includes having a terminal task running for each project. when you have multiple projects in one workspace, you also need one terminal tab per project, which is very disorienting. when having multiple window tabs, each project workspace remains in the exact state it has been since you last left it (including terminal + open files, etc). 
having this as opt-in wouldn't hurt i suppose.

**Comment by gaauwe** [comment]
I've been using this daily without any issue, since I originally opened the PR. About once a week I pull in new changes locally from master to stay up-to-date, but at this point I can't imagine using Zed without this feature.

As a few people already mentioned, it's quite different than "add folder to project". I'm often working on multiple projects that have both a backend and a frontend. While adding both the backend and frontend to 1 project works amazingly, having multiple projects in 1 window isn't manageable for me. With these native tabs, things like terminals and global search are nicely separated. The feature has been opt-in / configurable from the start. If there are certain things that need to be changed for this to be acceptable, I'll gladly work together with the Zed team to refine it 😄

Recently I also got the 'plus button to open a new tab' working:

image

**Comment by stefvanhouten** [comment]
Can we please add this feature? It seems really nice and would enhance my workflow greatly

**Comment by remorses** [comment]
This is one of the most important features for me, please reconsider reopening this PR.

Having 10 Zed windows makes it much more difficult to navigate compared to one window with 10 native tabs.

**Comment by remorses** [comment]
I will donate $100 to whoever merges this PR

**Comment by gordongrech** [comment]
Just started using Zed and it's an amazing product. Having this feature would truly make Zed complete for us.

**Comment by irakliasatiani** [comment]
Aren't you going to make it? community needs this

**Comment by ConradIrwin** [comment]
See  #33334. It's happening!

**Comment by irakliasatiani** [comment]
> See #33334. It's happening!

Great job! wish you luck

**Pull request closed without merging**
