### PR TITLE
notification panel: rework time formatting

### PR DESCRIPTION
**Pull request by bennetbo**
Follow up of #7994 to rework the notification panel timestamps.
This PR also includes some of the changes @evrsen proposed in #8996 
Here is what it looks like now:

https://github.com/zed-industries/zed/assets/53836821/d85450e7-eab6-4fe7-bd11-1d76c0e87258

Release Notes:
- Reworked date time formatting in the chat and the notification panel
- Added hover style to notifications and hovering tooltip on timestamps

### CODE REVIEW

**Comment by bennetbo** [comment]
> Just came to my mind, @bennetbo, maybe the way we're using the absolute timestamp when hovering over the relative timestamps in notifications doesn't make much sense, the relative timestamp already indicates whether the date was today or yesterday so having those indications on the absolute timestamp maybe is redundant, could we replace the indicators with an actual date?
> 
> What I'd expect hovering over `46 minutes ago` is to be prompted `2024/03/07 12:37` and not `Today at 12:37`. This is, of course, without affecting the absolute timestamps in the chat panel.
> 
> What do you think?

Yeah sounds like a good idea.
I also didn't like the name `TimestampFormat::Absolute`, as the formatting is not really absolute. I added a new Variant to `TimestampFormat::EnhancedAbsolute` which inserts "Today" or "Yesterday" if necessary.
Still not too happy with the naming, suggestions welcome!

**Comment by bennetbo** [comment]
Not sure why `extension_store_test::test_extension_store_with_gleam_extension` is failing. Working locally for me and seems unrelated to the changes.

**Comment by SomeoneToIgnore** [comment]
Also fails on `main` and does seem unrelated indeed.

**Comment by JosephTLyons** [comment]
Total side note, but I wonder if chat timestamps could benefit from the same sort of improvement - seems nice to be able to hover and get the specific time.

**Comment by bennetbo** [comment]
> Total side note, but I wonder if chat timestamps could benefit from the same sort of improvement - seems nice to be able to hover and get the specific time.

Should have probably made this clearer, we changed up the timestamps in the chat a little bit as well. The timestamps that are not from today or yesterday also include the time (previously only the date was included)

Before:
image


After:
image

**Comment by ConradIrwin** [comment]
Thanks for this!

**Pull request merged**
