### PR TITLE
Add language-agnostic snippets

### LINKED ISSUE #4611: Language server agnostic snippets
### Check for existing issues

- [X] Completed

### Describe the feature

Other editors have the ability to define snippet without setting up in the LSP. For example, one can still define snippets for editing plain text files and that does not require user to setup initialization options of a LSP. (And we don't generally have a LSP for plain text files.)

Also some snippets might shared across different file types/LSPs.

### If applicable, add mockups / screenshots to help present your vision of the feature

output

### PR DESCRIPTION
**Pull request by osiewicz**
Note that right now we can't attach a language server to arbitrary buffer, which is why I've listed a bunch of languages verbatim. 
See https://github.com/zed-industries/simple-completion-language-server/tree/main for docs on how to define your snippets. They should be placed in ~/.config/zed/snippets ; `snippets.(toml|json)` file can be used to define language-agnostic snippets, and any other name (e.g. `python.toml`) will apply only to buffers of that particular type.

There's https://github.com/rafamadriz/friendly-snippets you can use as a repository of snippets, for your convenience.

Fixes https://github.com/zed-industries/zed/issues/4611

Release Notes:
- Added support for snippets via simple-completion-language-server

### CODE REVIEW

**Comment by d1y** [comment]
The official support now is really great.
I also made this extension before
And I would like to offer some suggestions and ideas:

1.  wonder if it's possible to change its service name to `scls`, which would be much easier to remember?
2. How about adding a command to obtain [rafamadriz/friendly](https://github.com/rafamadriz/friendly-snippets)? like `Zed:: FetchFriendlySnippets`?(https://github.com/d1y/scls/commit/d0d1daf075d44d8cf9749754bf031073f7b2615e)
3. The completion sorting of `scls` should be able to sort (#12028)
4. Always highlight code blocks ([d1y/scls/8](https://github.com/d1y/scls/pull/8))

**Comment by osiewicz** [comment]
Hey @d1y,
Oh, I didn't know that we've had an extension based on scls already. 
On one hand yeah, scls is easier to remember, but on the other how are you supposed to know what it means? I think it makes sense to spell out `snippets` explicitly in the name to make it a bit easier on the users.
For the other ideas, I'd just wait for users feedback to make a call. I'm a bit skeptical of adding a zed action that's specific to an extension. 
As for sorting, that sounds like a good idea; though we can probably implement in on the side of language server (setting it's sortText to something low-ish). 
As for code highlighting, can we reliably assume that the snippet description contains just code?

**Comment by osiewicz** [comment]
Nevermind, you're right about highlighting; since we're using the body as doc, it should be valid code. It may contain unsubstituted variables tho, which is a bit of a bummer.

**Comment by osiewicz** [comment]
@eproxus I think that's because Erlang is not in a list of languages for which this language server is enabled (see [this line](https://github.com/zed-industries/zed/pull/13253/files#diff-4a4040983d1956db42718bdbc429ad466f5799ce955b38c094fb737ac53849dfR11)). That can be fixed. You should see completion from `snippets.json` in any other file (I think we don't do plain text right now); can you try it in e.g. go file?

**Comment by eproxus** [comment]
@osiewicz Yes, please support more languages! ❤️ 

I tried in a file with `Shell` syntax but the snippet above from `snippets.json` still doesn't show up...

**Comment by osiewicz** [comment]
Oh, it looks like there's a typo in languages list; "Shell" should be a "Shell Script" syntax. TL;dr: try other file. I'll fix the shell association in a sec.

**Comment by eproxus** [comment]
Alright, it works in a Python file. However I noticed it does not work in any supported syntax if the file is not saved. Is that supposed to work?

**Comment by osiewicz** [comment]
No, it's not supposed to work (unrelated to this PR); we don't support LSPs in unsaved files right now.

**Comment by eproxus** [comment]
Do you want a PR to add more languages?

**Comment by osiewicz** [comment]
I'm on it. =)

**Comment by danremollino** [comment]
You mention that you should be able to use a snippets.toml file. Have not been able to get this to work. Do I have something formatted wrong?

```
[snippet]
prefix = "log"
body = ["console.log(\"$1\")"]
description = "Expand `log` to `console.log()`"
```

**Comment by osiewicz** [comment]
@danremollino yeah, I think the first line should be `[[snippets]]` and not `[snippet]`.

**Comment by osiewicz** [comment]
@eproxus I guess it might be added at some point, yeah - it's [in the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax), so I don't see why not; [our snippet support](https://github.com/zed-industries/zed/tree/main/crates/snippet) is relatively scarce right now, so please create a new issue for it.

**Comment by eproxus** [comment]
@osiewicz Great! I'll file an issue. Do you know if those variables are supported already, like `TM_FILENAME_BASE`?

**Comment by osiewicz** [comment]
Hehe, nope: https://github.com/zed-industries/zed/issues/13255

**Comment by tepavcevic** [comment]
@osiewicz I have an issue with starting snippets language server on Ubuntu.
My installation process went as follows:
- installed the extention
- added a sample `console.log` snippet to `~./config/zed/snippets/snippets.json`
- no snippets show up

In my zed logs I've found errors related to starting the snippets server:
`[ERROR] failed to start language server "snippet-completion-server": no asset found matching "simple-completion-language-server-x86_64-unknown-linux-musl.tar.gz"`

Can you please help me decode the issue here, since my best guess was that the extention is not installed correctly and I've tried reinstalling multiple times with no result?

**Comment by osiewicz** [comment]
@tepavcevic Thankfully this is relatively straightforward - I've screwed up the name of a platform for Linux. None of this is your fault and I'm sorry for it being so confusing.
I'll release a new version which should fix it shortly.

**Comment by osiewicz** [comment]
@tepavcevic Can you give 0.0.5 a try?

**Comment by tepavcevic** [comment]
> @tepavcevic Can you give 0.0.5 snippets extension a try?

Just tried out 0.0.5, working as intended. Thanks

**Pull request merged**
