### PR TITLE
Respect `eslint.nodePath` setting

### PR DESCRIPTION
**Pull request by Yanguk**
I'm using Yarn Plug'n'Play.
In this case, by default, eslint cannot find the path, so configuration like `"eslint.nodePath": ".yarn/sdks"` is required.
So, I want to add this!

Release Notes:

- Added eslint config nodePath

### CODE REVIEW

**Comment by Yanguk** [comment]
@cla-bot check

**Comment by Yanguk** [comment]
is not working

i will re Pull requeset after test and Fix

**Comment by Yanguk** [comment]
I wanted to confirm if format_on_save was working properly, but it didn't seem to be functioning as expected.

However, I noticed that despite this, the option was applied, as I no longer encountered the `eslint/noLibrary` error.

**Review by mrnugget — APPROVED** [review]
Looks good, yep!

**Pull request merged**
