### PR TITLE
Add emacs keymap

### PR DESCRIPTION
**Pull request by vextorspace**
Release Notes:

-added default emacs keybindings. They are not complete but a good start. I have not tested the mac bindings as I don't have a mac so might be a good idea to test them first.

### CODE REVIEW

**Comment by notpeter** [comment]
Thanks for taking a crack at this.

I don't think macos emacs key bindings should be `cmd-` prefixed.  I'm an emacs user and I've always used them as `ctrl-` on all platforms (mac, windows, linux).

I'd also like to signal to users that this is an incomplete emacs mode, perhaps the `Display` should show "Emacs (beta)" or some such.

**Comment by opsnull** [comment]
I'm also an emacs user, I have tweak zed default keymap a lots with the help of zed assistant AI, and following is my current used version. 
https://gist.github.com/opsnull/5da3e4545aa36fb057e4f5df4f9b510c

**Comment by vextorspace** [comment]
I've switched the cmd to ctrl in the emacs bindings as suggested @notpeter. I also had to bring the branch up to date with zed main. If you would rather the clean commit, I could cherry pick the commits on top of main so there wasn't a merge commit.

**Comment by notpeter** [comment]
I know this is by no means a full emacs keymap but it's a start.
Thanks and congrats on your first contribution!

**Comment by maaand** [comment]
How do we use this emacs keymap??

**Comment by notpeter** [comment]
@maaand You are running Zed Stable 0.161.2 and if you look at the release notes, this shipped in [Zed Preview v0.162.0-pre](https://github.com/zed-industries/zed/releases/tag/v0.162.0-pre).

Zed Stable will get 0.162.x on Wednesday.

**Comment by maaand** [comment]
> @maaand You are running Zed Stable 0.161.2 and if you look at the release notes, this shipped in [Zed Preview v0.162.0-pre](https://github.com/zed-industries/zed/releases/tag/v0.162.0-pre).

Oh boy, my bad. Thanks for the update!

**Pull request merged**
