### PR TITLE
bump tree-sitter-nu to latest

### PR DESCRIPTION
**Pull request by fdncred**
This PR bumps the tree-sitter-nu commit to the latest supported by the nushell team. It also includes the latest highlights.scm

Release Notes:

Bumped `nu` tree sitter dependency and highlights.scm

### CODE REVIEW

**Comment by fdncred** [comment]
@cla-bot check

**Comment by JosephTLyons** [comment]
Hey @fdncredl, this looks good, so I'm going to merge the PR. As a heads up, we are moving `nu` support, and support for a bunch of other languages, over to a plugins. `nu` actually already has a plugin. The plugin source code is here:

- https://github.com/zed-extensions/nu

And the plugin is registered to our plugin store here:

- https://github.com/zed-industries/extensions/tree/main/extensions

We haven't removed any languages out of Zed since the plugins don't support language servers yet, but I think the nu language server has not worked inside of Zed since the day it was added, so we are probably fine to actually remove nu from Zed, then work to keep the plugin up to date, and add the nu language server to the plugin once our extensions have language server support.

**Comment by JosephTLyons** [comment]
> @JosephTLyons Sounds good. I'll look at those links. I was thinking the nu --lsp functionality was working because I could get completions with `str <tab>`. Maybe something else is providing those completions?

Huh, its possible that its just broken for a subset of users. So, maybe `nu` needs to be treated like the other languages and left in Zed until extensions support language servers.

**Comment by fdncred** [comment]
I can submit a PR to https://github.com/zed-extensions/nu if you need me to. I noticed it's out of date too.

**Pull request merged**
