### PR TITLE
Move "Sign in" button to user menu

### PR DESCRIPTION
**Pull request by mintyleaf**
Release Notes:

- Moved "Sign In" button to user menu (as mentioned in #11800)

### CODE REVIEW

**Comment by mintyleaf** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
It seems unlikely that we'll do this. Collaboration is a core Zed feature, so it doesn't make sense to hide the sign-in button away in a menu.

Additionally, we display connection status indicator in the same spot, and hiding that under the user menu will make those errors less readily available.

I'll let @iamnbutler weigh in.

**Comment by maxdeviant** [comment]
> It seems unlikely that we'll do this. Collaboration is a core Zed feature, so it doesn't make sense to hide the sign-in button away in a menu.
> 
> Additionally, we display connection status indicator in the same spot, and hiding that under the user menu will make those errors less readily available.
> 
> I'll let @iamnbutler weigh in.

After talking with @iamnbutler, we won't be moving forward with this.

**Comment by mintyleaf** [comment]
> > It seems unlikely that we'll do this. Collaboration is a core Zed feature, so it doesn't make sense to hide the sign-in button away in a menu.
> > Additionally, we display connection status indicator in the same spot, and hiding that under the user menu will make those errors less readily available.
> > I'll let @iamnbutler weigh in.
> 
> After talking with @iamnbutler, we won't be moving forward with this.

okay, no problem, i hope linux user keychain storage will be fixed anyways, maybe i'll got some time to investigate  

after looking more into the code i can say that the whole collab_ui thing is kinda unclear  

we can hide various statusbar buttons and still have access to them through command palette, so there are intention to let user decide which (core) parts can be seen and accessed quickly if really needed  
we have an existing option to hide collab panel button from statusbar, yet, titlebar button is still there which is not related to panel, yet inheriting the idea that something can be hidden - it most likely should be hideable too  
i tried to do that, but seems like the whole titlebar, including project name, git status, user menu is hard tied only to collab_titlebar_item logic, and rendered there as well, making the whole titlebar logic unmodular and cumbersome

**Pull request closed without merging**
