### PR TITLE
Add `musl`  package for Arch Linux

### PR DESCRIPTION
**Pull request by connortsui20**
It seems like `musl` is required to build on Arch Linux, but it is not included in the dependencies list. I think adding it here will fix this?

<details>

```
+ [[ x86_64-unknown-linux-musl == \x\8\6\_\6\4\-\u\n\k\n\o\w\n\-\l\i\n\u\x\-\m\u\s\l ]]
+ export 'RUSTFLAGS= -C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib -C target-feature=+crt-static'
+ RUSTFLAGS=' -C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib -C target-feature=+crt-static'
+ cargo build --release --target x86_64-unknown-linux-musl --package remote_server

<-- snip -->

The following warnings were emitted during compilation:

warning: ring@0.17.8: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?
warning: ring@0.17.8: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?

error: failed to run custom build command for `ring v0.17.8`

Caused by:
  process didn't exit successfully: `???/zed/target/release/build/ring-e6a4c8b1838d35d7/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_8_
  OPT_LEVEL = Some(3)
  OUT_DIR = Some(???/zed/target/x86_64-unknown-linux-musl/release/build/ring-98c5093b40c533c3/out)
  TARGET = Some(x86_64-unknown-linux-musl)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-musl
  CC_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_musl
  CC_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(crt-static,fxsr,sse,sse2)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-musl
  CFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_musl
  CFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?

  --- stderr


  error occurred: Failed to find tool. Is `musl-gcc` installed?


warning: build failed, waiting for other jobs to finish...
```

</details>

Release Notes:

- Fixed missing `musl` dependency required to build from source on ArchLinux

### CODE REVIEW

**Comment by connortsui20** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Hi @connortsui20,

Zed requires a libc of some sort (e.g. the [unofficial Zed ArchLinux package](https://archlinux.org/packages/extra/x86_64/zed/) uses `glibc`) but doesn't explicitly require `musl` or `glibc` specifically and I believe either will work.  

Not sure how to best handle supporting this is the `script/linux` bootstrap script. I would assume most users with either `glibc` or `musl` installed would expect to not be forced to install the other, but I'm not sure what the best default behavior is if don't have either: maybe immediately quit if neither is available and force the end user to manually install `glibc` or `musl` and rerun? Not sure.

**Comment by connortsui20** [comment]
It might be good to have a warning in the `script/linux` script _before_ compilation starts? On my laptop it took several minutes to compile everything before hitting the above error message, which wasted a lot of battery and time. I'm not a scripting person though so I'm not exactly qualified to implement that...

**Comment by notpeter** [comment]
I've made the changes to your branch which will check for glibc or musl packages and bail if neither is installed.  Could you test and see if it works for you?

**Comment by connortsui20** [comment]
> I've made the changes to your branch which will check for glibc or musl packages and bail if neither is installed. Could you test and see if it works for you?

I don't think it worked, when I remove `musl` from my system and run `install/linux` it passes just fine...

**Comment by notpeter** [comment]
I was incorrect. I totally forgot we require musl to build the a statically compiled zed-remote-server without a glibc dependency. You're original change is correct.

Thanks for testing.

**Comment by connortsui20** [comment]
It might be a good idea to add that requirement for other platforms? Though I only run Arch so I have no way to test it. Maybe we open a new issue for adding that requirement for all distros?

**Comment by notpeter** [comment]
> It might be a good idea to add that requirement for other platforms? Though I only run Arch so I have no way to test it. Maybe we open a new issue for adding that requirement for all distros?

Looks like we get on Ubuntu/Debian
https://github.com/zed-industries/zed/blob/c2f2f6c873116ad3a29aad9bdecd25092962082a/script/linux#L46-L47
And RHEL/Fedora/etc:
https://github.com/zed-industries/zed/blob/c2f2f6c873116ad3a29aad9bdecd25092962082a/script/linux#L71

But not on Arch/OpenSuse/Void/Gentoo

I'm going to go ahead and merge this as-is, we can improve it for other distros as required.

**Comment by notpeter** [comment]
Thanks! And congrats on your first Zed contribution!

**Pull request merged**
