### PR TITLE
windows: Use exact scale factor

### PR DESCRIPTION
**Pull request by kazatsuyu**
Maybe several problem in this will be solved by #9438, I wait it.

Also below is remained task.

- [x] Positions that be stored in database should be multiplyed by scale_factor

Release Notes:

- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
I think it's not the right time to introduce the scale factor now, the scale factor is pretty buggy, see #9438 #8809

**Comment by JunkuiZhang** [comment]
Edit: Sorry, I misread that.

**Comment by kazatsuyu** [comment]
Probably `blade` requires the number of physical pixels, so in HiDpi mode, we should just use the value notified by Windows.

There seems to be differences between macOS and Windows in the effect of the scale factor on the size of the window, so there needs to be some changes.

**Comment by kazatsuyu** [comment]
In second thought, the values to be stored in the database can remain the same. And apply display scale factor on create window.
So I have to wait #9360 too

**Comment by kazatsuyu** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor#remarks
Apparently it is better to use `GetDpiForWindow` instead of checking the dpi of the monitor, so it would be better to create the window and then use `SetWindowPos` to move it.

**Comment by kazatsuyu** [comment]
Close because of #9449 #9456 is merged

**Pull request closed without merging**
