### PR TITLE
Inline git blame

### PR DESCRIPTION
**Pull request by mrnugget**
This adds so-called "inline git blame" to the editor that, when turned on, shows `git blame` information about the current line inline:

screenshot-2024-04-15-11 29 35@2x

When the inline information is hovered, a new tooltip appears that contains more information on the current commit:

screenshot-2024-04-15-11 28 24@2x

The commit message in this tooltip is rendered as Markdown, is scrollable and clickable.

The tooltip is now also the tooltip used in the gutter:

screenshot-2024-04-15-11 28 51@2x

## Settings

1. The inline git blame information can be turned on and off via settings:
```json
{
  "git": {
    "inline_blame": {
      "enabled": true
    }
  }
}
```
2. Optionally, a delay can be configured. When a delay is set, the inline blame information will only show up `x milliseconds` after a cursor movement:
```json
{
  "git": {
    "inline_blame": {
      "enabled": true,
      "delay_ms": 600
    }
  }
}
```
3. It can also be turned on/off for the current buffer with `editor: toggle git blame inline`.

## To be done in follow-up PRs

- [ ] Add link to pull request in tooltip
- [ ] Add avatars of users if possible

## Release notes

Release Notes:

- Added inline `git blame` information the editor. It's enabled by default. It can be turned off in the settings with `{"git": { "inline_blame": {"enabled": false } } }` for every buffer. It can be turned on/off temporarily for the current buffer, with `editor: toggle git blame inline` ([#4793](https://github.com/zed-industries/zed/issues/4793)).

(These release notes include https://github.com/zed-industries/zed/pull/10632)

### CODE REVIEW

**Comment by baldwindavid** [comment]
Great stuff. I don't want to disrupt anything you have going on here, but just posting a couple things I wonder about for the future:
- I really like inline blame, but don't tend to want to see it when moving throughout the code. I see a mention of "enable/disable", but assume that means a global on/off switch. I wonder if it would be possible to have a command allowing a keybinding to be assigned to display the tooltip similar to `g h` for `editor::Hover`.
- "Add link to PR to tooltip" - This would be amazing to have at some point. As an aside, this is wayyyy outside the scope of this PR, but would generally like to be able to visit links in tooltips via keyboard.

**Comment by mrnugget** [comment]
Thanks, David!

> * I wonder if it would be possible to have a command allowing a keybinding to be assigned to display the tooltip similar to `g h` for `editor::Hover`.

Yeah, that's a great idea, and we talked about it before: a push-to-talk kinda thing where you hold a key combination down and while it's down it shows the inline blame or something like that.

But before we do that,  maybe we need global setting and a toggle keybinding, yeah.

**Comment by Tenkir** [comment]
This is cool, but is there a way to display it in the bottom toolbar (like VSCode). I pretty much never want to see it in the code itself.

**Comment by Tenkir** [comment]
All good, just wondering. I'd also be happy with the toggle hotkey [baldwindavid](https://github.com/baldwindavid) mentioned above, so I'll throw a +1 behind that. As it is, it's too distracting so I just have it disabled.

**Comment by baldwindavid** [comment]
@Tenkir you're probably aware but, if not, a bit of a workaround is to use the `editor: toggle git blame` command to pop open the blame only as needed rather than using "inline" blame at all. I have a keybinding to open/close that quickly.

```json
  {
    "context": "Editor && VimControl && !VimWaiting && !menu",
    "bindings": {
      "space g l": "editor::ToggleGitBlame"
    }
}
```

**Comment by jay-herrera** [comment]
Hey! what is the relevant styling config for this feature? In my editor it shows up as super white, but I can't narrow down which config would change it

**Comment by mrnugget** [comment]
@jay-herrera it's using `hint`. You can override it like this:

```json
{
  "experimental.theme_overrides": {
    "hint": "#fb4a35ff"
  }
}
```

**Comment by pavles6** [comment]
@mrnugget, is there a keymap action that can be mapped to display the tooltip that appears when an inline blame message is hovered? I want to be able to see the pop-up without having to move my mouse cursor.

**Pull request merged**
