### PR TITLE
[WIP] Introduce keyboard layout independent shortcuts

### PR DESCRIPTION
**Pull request by JunkuiZhang**
### Description

To address the issue of shortcuts becoming unusable due to different keyboard layouts, this PR introduces layout-independent shortcut settings. Currently, all shortcuts in Zed are based on the standard US English keyboard layout. For example, the shortcut `cmd-shift-[` doesn't work on the Czech layout because that layout lacks the `[` key. While it's true that the `[` character can be typed using `AltGr-F` on the Czech layout, it's important to clarify the concept of a "key." For instance, the `a` inside shortcut `ctrl-shift-a` is a key, but `A` inside `ctrl-A` is not, even though both output the `A` character, since there is no `A` key on keyboard, just the `a` key. The Czech layout simply doesn't have a `[` key.

### Solution

The solution proposed in this PR is to map the `[` key from the standard English layout to the corresponding key in the Czech layout, which would be `ú`. This approach creates layout-independent shortcuts, giving users the option to enable this feature or, more granularly, to enable it for specific keys only.

### Implementation

The ideal implementation would involve mapping `[` to its scancode in the standard English layout, and then mapping that scancode to the corresponding key in the user's layout, such as `ú` in the Czech layout. On Windows, this can be easily achieved with the `MapVirtualKey` function, and there are similar functions available on Linux. However, I couldn't find an equivalent function on macOS after some google.

Therefore, this PR adopts a manual approach to translating the standard English layout to other layouts. This method is simple, understandable, and works across all platforms. It requires minimal maintenance, though users will need to specify their keyboard layout. I believe this is acceptable, since some key mappings in nvim also require the user to specify the keyboard layout.

### Showcase

As shown in the video, I installed the Czech keyboard layout on my Mac, and the video displays the current key presses in the bottom left corner. In the video, I use the `cmd-/` shortcut (from the standard English layout) to comment out a line of code. However, as you can see, I actually pressed `cmd--` because, on the Czech layout, the `-` key is in the same position as the `/` key in the English layout.

https://github.com/user-attachments/assets/92dba9ec-c144-484f-890c-42d959585bb0

One issue with the current `gpui` shortcut system is that it doesn't distinguish the concept of a `Key` within `Keystroke`. In `keymap.json` and `vim.json`, for example, `cmd-{` should actually be represented as `cmd-shift-[`, and the `:` shortcut should be represented as `shift-;`. Changing `{` to `shift-[` not only clarifies the key mappings but also reduces maintenance overhead. This way, we only need to maintain the mapping from `Key` to `Key`, dont have to maintain mappings from `shift-Key` to `shift-Key` which will cut half of the efforts of maintaining.

Any suggestions or feedback on this are welcome.

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this. There's a lot to think about here!

Reading through https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layouts shows one way we could make this work; though Zed works quite differently to that today. How does VSCode do the virtual key mapping automatically on macOS? In #16278 we toyed with the idea of using `NSEvent#charactersWithModifier(.command)` but that didn't seem to solve everything.

On macOS a concrete bug that we'd like to try and fix with changes to how keypresses are interpreted is:
* On non-Latin keyboards the builtin alphabetic shortcuts that don't use command can't be typed. (e.g. ctrl-a or vim mode normal commands).

It's worth noting that shortcuts that do include command already just work because macOS keyboard layouts are typically built to send qwerty keys when command is held down.

Vim (unlike VSCode) uses the input as typed. Its solution is to set a `langmap` in your settings that maps between keys you type and vim normal-mode shortcuts to trigger. I'm not sure that's exactly the model we want to follow, but it is at least easy to explain.

If we do switch to a more "virtual" interpretation of our keymap, it's probably worth thinking about how to ensure we show the right thing to users in the UI. I'd also like to keep the ability to write `"cmd-ф"` in the mappings file and have it work as you expect.

**Comment by JunkuiZhang** [comment]
> Thanks for this. There's a lot to think about here!
> 
> Reading through https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layouts shows one way we could make this work; though Zed works quite differently to that today. How does VSCode do the virtual key mapping automatically on macOS? In #16278 we toyed with the idea of using `NSEvent#charactersWithModifier(.command)` but that didn't seem to solve everything.
> 
> On macOS a concrete bug that we'd like to try and fix with changes to how keypresses are interpreted is:
> 
> * On non-Latin keyboards the builtin alphabetic shortcuts that don't use command can't be typed. (e.g. ctrl-a or vim mode normal commands).
> 
> It's worth noting that shortcuts that do include command already just work because macOS keyboard layouts are typically built to send qwerty keys when command is held down.
> 
> Vim (unlike VSCode) uses the input as typed. Its solution is to set a `langmap` in your settings that maps between keys you type and vim normal-mode shortcuts to trigger. I'm not sure that's exactly the model we want to follow, but it is at least easy to explain.

I've reviewed the macOS code, and the issue lies in the lack of a clear distinction between the concept of a "Key" and a "Char" that I mentioned earlier.

Say an example:

Shortcut: `cmd-q`. Here, it's important to note that `q` refers to the `key`, not the `character`. On a non-Latin keyboard layout (let's take Russian as an example), pressing the `q` key actually produces the character `й`, see [here](https://en.wikipedia.org/wiki/File:KB_Russian.svg). In the Windows implementation, this is handled correctly because we distinguish between the key and the character, as shown in the video below:


https://github.com/user-attachments/assets/0761d42c-f400-449f-9232-4ebeaed3e764



However, in the macOS implementation, this distinction is not made, resulting in the following representation:

```rust
KeyStroke {
    cmd: true,
    key: "й",
    ...
}
```

In contrast, the Windows implementation correctly represents it as:

```rust
KeyStroke {
    cmd: true,
    key: "q",
    ...
}
```

So, the non-Latin keyboard short-cut issue you mentioned does not exist on Windows.

I'll submit a draft PR to address this on macOS. My question is: considering that the `Key` in the current `KeyStroke` is of type `String`, which makes it difficult to clearly distinguish the concept of a Key, should we consider changing its type from `String` to `VirtualKeyCode(u32)`?

> If we do switch to a more "virtual" interpretation of our keymap, it's probably worth thinking about how to ensure we show the right thing to users in the UI. I'd also like to keep the ability to write `"cmd-ф"` in the mappings file and have it work as you expect.

In the VSCode link you provided, there are images that suggest VSCode applies some special handling for these cases:

Different keyboard layouts usually reposition the above virtual keys or change the characters produced when they are pressed. When using a different keyboard layout than the standard US, Visual Studio Code does the following:

All the key bindings are rendered in the UI using the current system's keyboard layout. For example, `Split Editor` when using a French (France) keyboard layout is now rendered as `Ctrl+*`:

https://code.visualstudio.com/assets/docs/getstarted/keybinding/render-key-binding.png

When editing `keybindings.json`, VS Code highlights misleading key bindings, those that are represented in the file with the character produced under the standard US keyboard layout, but that need pressing keys with different labels under the current system's keyboard layout. For example, here is how the `Default Keyboard Shortcuts` rules look like when using a French (France) keyboard layout:

https://code.visualstudio.com/assets/docs/getstarted/keybinding/keybindings-json.png

**Comment by JunkuiZhang** [comment]
@ConradIrwin I created a draft PR #17015 


https://github.com/user-attachments/assets/0b3716bf-1632-4b82-b8ff-1fd2264cee32

**Comment by JunkuiZhang** [comment]
Vim mode shortcuts with Russian keyboard layout:

https://github.com/user-attachments/assets/ee094fe5-a352-4b95-8cc0-2a3f593c7258

**Comment by mikayla-maki** [comment]
Further discussion: https://github.com/zed-industries/zed/discussions/17031

**Comment by ConradIrwin** [comment]
@JunkuiZhang based on some more research and discussion, we want to copy the macOS key equivalents more directly. This is a bit of a change from what you have here, but not too much.

* For keyboards that generate the full ascii range with command (and optionally shift) modifiers, like Russian, Japanese, etc. then we will use that key as the key equivalent we match against for all bindings.
* For keyboards that don't we will do the same mapping that macOS does (as described here: https://developer.apple.com/documentation/swiftui/keyequivalent#overview). Unfortunately they provide no way to query this data, but we can somewhat automate it with a small macOS app (I can take that on). This is not based on key code but on character. For example zoom-in (cmd-+) requires a shift on a US keyboard, but no shift on an AZERTZ keyboard. As you said, the number keys and their shifted characters stay the same, so this only matters for `~_-+=[{]}\|;:'",<.>/?`. These keys are when possible mapped to either the key that generates the character, or the same position on a qwerty keyboard, or if not possible it seems a bit arbitrary.
* By default we'll hardcode mappings for known keyboard layouts, and I think we should add the ability for people to configure this mapping in their config. e.g. `"ö":"[", "Ö":"{"`. When we load keyboard bindings we run it through the current mapping so that the shortcut we load for `cmd-[` is `cmd-ö`. This lets us render tooltips etc. without having to query the key system at all.

There is one further change I think we need for vim mode to continue working which is to allow people to type the real character (when it is specified with no modifier key). So, if you're on an AZERTZ keyboard option-5 could match a binding to either `option-5` OR `[` (Similar how how we do ime_key today).

Beyond this change, a nice thing to do would let you configure what your option keys do so you can configure left-option-5 to do one thing and right-option-5 to do the other (in the case that they conflict).

**Comment by JunkuiZhang** [comment]
> * For keyboards that generate the full ascii range with command (and optionally shift) modifiers, like Russian, Japanese, etc. then we will use that key as the key equivalent we match against for all bindings.

On russian layout `ctrl-й` would be `ctrl-q`, and `й` would be `q`, just like how it behaves on Windows, right ?

> * For keyboards that don't we will do the same mapping that macOS does (as described here: https://developer.apple.com/documentation/swiftui/keyequivalent#overview). Unfortunately they provide no way to query this data, but we can somewhat automate it with a small macOS app (I can take that on). This is not based on key code but on character. For example zoom-in (cmd-+) requires a shift on a US keyboard, but no shift on an AZERTZ keyboard. As you said, the number keys and their shifted characters stay the same, so this only matters for `~_-+=[{]}\|;:'",<.>/?`. These keys are when possible mapped to either the key that generates the character, or the same position on a qwerty keyboard or if not possible it seems a bit arbitrary.

I didn't expect handling key events on macOS to be this complex and challenging. I think we might need further discussion here, as I’ve noticed that even in Xcode, keybindings don't seem to be purely char-based. For example, the shortcut for `Editor->Font Size->Increase` is marked as `cmd-+` in the US layout. Based on char-based matching, I should press `cmd-shift-=`, but in reality, pressing `cmd-=` triggers the shortcut.

> * By default we'll hardcode mappings for known keyboard layouts, and I think we should add the ability for people to configure this mapping in their config. e.g. `"ö":"[", "Ö":"{"`. When we load keyboard bindings we run it through the current mapping so that the shortcut we load for `cmd-[` is `cmd-ö`. This lets us render tooltips etc. without having to query the key system at all.

Makes sense.

> There is one further change I think we need for vim mode to continue working which is to allow people to type the real character (when it is specified with no modifier key). So, if you're on an AZERTZ keyboard option-5 could match a binding to either `option-5` OR `[` (Similar how how we do ime_key today).

So, char-based and key-based matching here?

> Beyond this change, a nice thing to do would let you configure what your option keys do so you can configure left-option-5 to do one thing and right-option-5 to do the other (in the case that they conflict).

If using VirtualKeyCode, like on Windows, it can be done with `VK_LEFTALT` and `VK_RIGHTALT`, on macOS, scan code can achieve this. So, I guess on macOS, `KeyStroke` could be something like:
```rust
struct KeyStroke {
    scan_code: u16,
    ime_key: String,    // key_char on VSCode
}
```

And I think the issue raised in this PR will largely be addressed by #17015. Should I go ahead and close this draft PR?

**Comment by ConradIrwin** [comment]
Sounds good, let's keep working on https://github.com/zed-industries/zed/pull/17015.

> I didn't expect handling key events on macOS to be this complex and challenging. 

Me neither! It seems fairly typical for `cmd-=` to also zoom in on a QWERTY keyboard, even though the primary shortcut is `cmd-+`.

In terms of struct I am not sure about using a virtual key code instead of a String for the key. We will be storing the bindings with the character so that we can render them in the user-interface, and it seems simpler to me if we match against Strings instead of trying to convert a string like `ö` we get from the keyboard into a virtual key code and back again at match time.

**Pull request closed without merging**
