### PR TITLE
Resolve documentation for visible completions

### PR DESCRIPTION
**Pull request by mgsloan**
Release Notes:

- Improved LSP resolution of documentation for completions. It now queries documentation for visible completions and avoids doing too many redundant queries.

---

In #21286, documentation resolution was made more efficient by only
resolving the current completion. However, this meant that single line
documentation shown inline in the menu was missing until scrolled
to. This also meant that it would wait for navigation to resolve
completion docs, leading to lag for displaying documentation.

This change resolves this by attempting to fetch all the completions
that will be shown. It also mostly avoids re-resolving completions. It
intentionally re-resolves the current selection on navigation, as some
language servers will respond with more information later on.

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Not sure on this one, given that we have https://github.com/zed-industries/zed/pull/21716 

1. Is the resolve speed that much of a concern when we start doing it without a debounce?

2.  One odd caveat we have is `vtsls` and https://github.com/zed-industries/zed/pull/21521 : that language server will send us updated `detail` on each resolve, so technically there not a situation possible, where `documentation` will be present for a certain item, but its label details won't (not the case for `vtsls` I think though).

Also, resolving neighbors in this case will enable rich labels for more items in the list, but not in the entire list.
That might look even more odd than just a single, selected item having a rich label and raise questions like "why not resolve the whole visible list".

-----------

So, I personally do not like this change, but feel free to merge if you insist.

**Comment by mgsloan** [comment]
@SomeoneToIgnore Thanks for taking a look! I've updated this to resolve all visible items, so that should address the issue with labels and single line docs.  I also made it always resolve the current selection,to attempt to handle cases where resolving later has more information.

I think the motivation for the debounce was just to avoid visual jank due to documentation appearing and disappearing, which is no longer a concern.  I suppose there could be a motivation to reduce the work done by the language server.

**Comment by SomeoneToIgnore** [comment]
> I suppose there could be a motivation to reduce the work done by the language server.

There was in the original issue (https://github.com/zed-industries/zed/issues/21205), and VSCode indeed is able to resolve only one (selected) completion item in certain cases, so it's not bad to try and match our resolve quantity given that it's only the documentation we want, in the ideal world where LSP is not violated.
Our remote connections will also benefit from that, as it's less bytes sent over the wire this way.

Given that now we don't have a debounce, maybe it's not that bad to try fixing the flicker some other ways, but I think it's also fine to do the visible range resolve — in fact, VSCode seem to do that if any of the returned items do not have `details` in it (which VSCode declares capable of resolving, so does not require to be present in the initial completion list).

So, I see both ways as feasible and having their pros and cons and cannot insist on either.

**Comment by mgsloan** [comment]
Cool, thanks for taking a look Kirill!  I'm going to merge this as I think it's definitely an improvement for the common case, then we can refine from here with feedback.  I can certainly imagine value in not fetching as many completions in some cases, such as when there is no single-line documentation or logic similar to VS Code w.r.t the details field (I don't quite follow how that works)

**Pull request merged**
