### PR TITLE
LSP: Allow for an LSP extension match on any suffix, not just filename and ext

### PR DESCRIPTION
**Pull request by nathansbradshaw**
Angular shares file extensions with `html` and `ts`. It is conventional for an angular file to follow the format `*.component.html` or `*.component.ts`. This PR allows LSP to add an optional Language detection field called `path_regex` that can be used to sort out duplicate Languages, such as in the case of angular files. 

Release Notes:
- Added `Path_Regex` option for LSP configs

### CODE REVIEW

**Comment by nb-midwestern** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I think we may just want to extend `path_suffixes` to handle these cases.

Adding a separate configuration option feels weird.

**Comment by maxbrunsfeld** [comment]
I agree, it seems like a `path_suffixes` need to not just match against the extension and the filename, but rather split the filename on a `.`, and check if *any* suffix of that split list matches the entry.

**Comment by ConradIrwin** [comment]
Sorry for the slow response here. 

I am going to close this for now. I think we need to consolidate our file ending handling so we can fix this in just one place.

**Pull request closed without merging**
