### PR TITLE
Avoid hang when starting work with rust-analyzer

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Release Notes:

- N/A

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
This change does not seem correct.

If we never notify then the Zed UI isn't going to update the displayed progress indicators.

This seems like it's just papering over the problem, which is undesirable.

**Comment by maxbrunsfeld** [comment]
We used to have some kind of throttle around this, which may have gotten accidentally removed at some point.

I think that it is ok to drop *some* of these messages, because ultimately we will get a `lsp::WorkDoneProgress::End` method that removes the token completely.

There is already a `last_update_at` Instant stored on the `LanguageServerProgress` associated with each progress token. We could probably just ignore progress updates unless a certain fairly short duration (maybe 50ms) has elapsed since the token was updated.

**Comment by CharlesChen0823** [comment]
> If we never notify then the Zed UI isn't going to update the displayed progress indicators.
If you mean, when remove `cx.notify`, the activity_indicator will not update the progress? But in my test, the progress indicators will always refresh when rust-analyzer is work progress. There might have other issue?

**Comment by maxdeviant** [comment]
Closing this, as the fix is not the one we want.

If anyone is looking to improve things in this area, see Max's suggestion https://github.com/zed-industries/zed/pull/12481#issuecomment-2140242197 as a starting point.

**Pull request closed without merging**
