### PR TITLE
Highlight some buttons in the extensions interface

### PR DESCRIPTION
**Pull request by bestgopher**
Release Notes:
- N/A

### Before:
image
### After:
image

### CODE REVIEW

**Comment by bestgopher** [comment]
I don't know how to clean up the warning.

**Comment by bajrangCoder** [comment]
try adding the release notes stuff at the end of your pr message
> ```
> Release Notes:
>
> - N/A
> ```

**Comment by maxdeviant** [comment]
Thanks for taking the time to put together this PR.

However, this change doesn't align with our current design direction.

**Comment by bestgopher** [comment]
> Thanks for taking the time to put together this PR.
> 
> However, this change doesn't align with our current design direction.

Ok. Thanks for your reply.

**Pull request closed without merging**
