### PR TITLE
emmet: Support more languages

### LINKED ISSUE #10654: Emmet support in xhtml, tsx, jsx, vue, & svelte
### Check for existing issues

- [X] Completed

### Describe the feature

Add optional configuration to the emmet extension to enable support for HTML/XML embedded languages, most web developers are writing inside of one of these so having the zed emmet extension limited to just explicitly HTML files is restrictive, implement a system similar to

https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types

with whichever system was chosen for settings for extensions haven't checked in on that in a few weeks.

*also xhtml can be ignored but is likely the easiest as it can just work identically to the default html setup*

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by olrtg**
Hey guys! `emmet-language-server` author here. Thank you so much for the amazing editor!

This PR adds more languages to the list for the `emmet-language-server` to attach to.

I have a question though, I saw that you guys don't differentiate yet between `JavaScript` and `JSX` files. I know that the tree-sitter parser for `js` comes with the ability to parse both but we still need to make that difference. Is that part of the plan? or do you have a reason for doing that?

Aside from that, I've still added support for `JavaScript` files since is important to have emmet completions in `JSX` files, but I would like to know what are your thoughts on that since doing this may pollute the completions in `.js` files.

And one last thing, the emmet language server accepts more filetypes such as `pug`, `sass`, `scss` and `less` files, which are not currently supported by zed. Should I create some extensions to add grammar support to those files later? Should those extensions be part of the zed repo? I'm just thinking that those are sort of core languages.

Aside from that, let me know if there's anything left to do on my side. Greetings!

Fixes #10654.

Release Notes:

- N/A

### CODE REVIEW

**Comment by olrtg** [comment]
@cla-bot check

**Comment by JosephTLyons** [comment]
cc @osiewicz

**Comment by olrtg** [comment]
@cla-bot check

**Comment by osiewicz** [comment]
Hey, thanks for your work on `emmet-language-server`! :)

> Aside from that, I've still added support for JavaScript files since is important to have emmet completions in JSX files, but I would like to know what are your thoughts on that since doing this may pollute the completions in .js files.

I think we have an option to enable language servers only in parts of the source file (e.g. for javascript we do so for tailwind: https://github.com/zed-industries/zed/blob/main/crates/languages/src/javascript/config.toml#L28). I'm not sure how that's gonna interact with a language server that comes from an extension though.

> And one last thing, the emmet language server accepts more filetypes such as pug, sass, scss and less files, which are not currently supported by zed. Should I create some extensions to add grammar support to those files later? Should those extensions be part of the zed repo? I'm just thinking that those are sort of core languages.

Well, that's totally up to you. If we don't yet have extension for these file types I think it doesn't make sense to enable Emmet support for them in this PR, but it's fine to revisit that decision down the line when we do eventually get them.

> I have a question though, I saw that you guys don't differentiate yet between JavaScript and JSX files. I know that the tree-sitter parser for js comes with the ability to parse both but we still need to make that difference. Is that part of the plan? or do you have a reason for doing that?

I'm not aware of any plans on our front to split JS support into JS/JSX (but honestly I wasn't there when that decision was made, so I don't have a feel for how much we want JS/JSX to stay under a single language).

**Comment by olrtg** [comment]
Update: Nope, I don't know how attaching the language server to a certain part of the buffer works. As you mentioned, for extensions at least it doesn't seem allowed for now.

Let me know if there's anything else I can do on my side!

**Comment by osiewicz** [comment]
Hey, it seems to almost work fine to me; the only caveat is that it only works inside of another element, so e.g.
`return (div>li*2` won't give you any completions; if it's within:
```
return (
  <nav>
  div>li*2
```
it does.

Here's a patch I used to enable Emmet within TSX files conditionally:
[emmet-tsx.patch](https://github.com/zed-industries/zed/files/15108964/emmet-tsx.patch)

> Ok! so, would you like me to keep JavaScript in the list or should I remove it until we have a separation between JS/JSX?

Given the above, I'd stick with enabling support in JS for now.

**Comment by olrtg** [comment]
Amazing @osiewicz! I have applied your patch, tested for both in jsx/tsx files and it's working.

**Comment by osiewicz** [comment]
Thanks!

**Comment by ZayRTun** [comment]
Hi, can you please add support for `Blade` files.

**Comment by olrtg** [comment]
@ZayRTun maybe open a new issue.

**Pull request merged**
