### PR TITLE
Add vim::MoveTo{Next,Prev} flags for regex and case sensitive search

### PR DESCRIPTION
**Pull request by osa1**
This makes the hard-coded regex and case-sensitive search flags in `vim::MoveToNext` and `vim::MoveToPrev` commands configurable in key bindings.

Example:

```json
{
  "context": "VimControl && !menu",
  "bindings": {
    "*": ["vim::MoveToNext", { "regex": false, "caseSensitive": false }],
    "#": ["vim::MoveToPrev", { "regex": false, "caseSensitive": false }]
  }
}
```

Closes #15837.

Release Notes:

- Added `regex` and `caseSensitive` arguments to `vim::MoveToNext` and `vim ::MoveToPrev` commands, for toggling regex and case sensitive search.

### CODE REVIEW

**Comment by osa1** [comment]
`Vim::move_to_internal` doesn't need to be `pub`. Lmk if you want me to fix it.

**Comment by osa1** [comment]
Is it possible to update the keymap in tests? I see a bunch of setting types like `EditorSettings` for updating user settings in tests. Is there a similar type for updating the keymap?

**Comment by mrnugget** [comment]
> Is it possible to update the keymap in tests? I see a bunch of setting types like `EditorSettings` for updating user settings in tests. Is there a similar type for updating the keymap?

Do you want to update the whole keymap? Because I don't think we do that in tests. It happens here though:

https://github.com/zed-industries/zed/blob/3fafdeb1a8280c5313f235a45af41d30e1314cc7/crates/vim/src/test/vim_test_context.rs#L62-L66

That ends up calling this here:

https://github.com/zed-industries/zed/blob/3fafdeb1a8280c5313f235a45af41d30e1314cc7/crates/settings/src/keymap_file.rs#L113

Which then creates the binding, which you can also do directly and which *is* something we do in tests:

https://github.com/zed-industries/zed/blob/3fafdeb1a8280c5313f235a45af41d30e1314cc7/crates/vim/src/test.rs#L802-L807

So I guess that's what I would do to test this.

**Review by mrnugget — APPROVED** [review]
Change looks good to me, so approving, but it sounds like you want to add a test, which I think would be great.

**Comment by osa1** [comment]
> Change looks good to me, so approving, but it sounds like you want to add a test, which I think would be great.

Yes, I'd like to test this. I couldn't figure out how to update keymaps in tests before so couldn't add the test. I'll try to do it today.

**Comment by osa1** [comment]
@mrnugget any ideas on what I'm doing wrong in this test?

```rust
    #[gpui::test]
    async fn test_regex_flag(cx: &mut gpui::TestAppContext) {
        use super::MoveToNext;
        use gpui::KeyBinding;

        let mut cx = VimTestContext::new(cx, true).await;

        cx.update(|cx| {
            cx.bind_keys([KeyBinding::new(
                "*",
                MoveToNext {
                    case_sensitive: false,
                    partial_word: false,
                    regex: false,
                },
                None,
            )])
        });

        cx.set_state("ˇ***Hi***", Mode::Normal);
        cx.simulate_keystrokes("*/*Hi*");
        cx.run_until_parked();
        cx.assert_state("**ˇ*Hi***", Mode::Normal);
    }
```

The idea is that `*` will enable search but the search term will be empty. `/` will then start editing the search term, then we type `*Hi*`, which if the flags are correct should select `*Hi*` in the buffer.

However it doesn't seem to move the cursor right now. Is there a way to check the selected text? Maybe the cursor doesn't move as the search highlights the matches?

**Comment by osa1** [comment]
I can't figure out how to test this with the limited time I have. @mrnugget please feel free to merge.

**Comment by mrnugget** [comment]
Thanks! Sorry, I was/am super busy with the SSH remoting stuff and didn't get to reply.

**Pull request merged**
