### PR TITLE
Add Zig support

### PR DESCRIPTION
**Pull request by allancalix**
This PR adds support for Zig with the official LSP (ZLS) and the treesitter grammar listed on the [website](https://tree-sitter.github.io/tree-sitter/). I've tested this on a few large codebases and go to definition, completion, and hover overlays all seem to work fine with no error logs.

Screenshot 2024-01-24 at 20 17 18

The highlights are adapted from the tree sitter repository which target neovim I think, I've fixed a handful of issues and the highlighting is looking pretty good but need to do more testing.

Release Notes:
- Added Zig support with zls [#5300](https://github.com/zed-industries/zed/issues/5300).

### CODE REVIEW

**Comment by mrnugget** [comment]
Hey @allancalix! Thanks so much for this — can't wait to write Zig with Zed too 😄 We'd love to merge this.

There's two things, as far as @as-cii and I can tell, that we'd need:

1. Can you sign the CLA?
2. Can you also go over the `highlights.scm` (and possibly the other tree-sitter query files) and make sure that the captures (the things using `@`) match what we use in Zed? Example: I noticed that `if`/`switch`/`else` aren't highlighted as keywords. Turns out that we need to change the capture from `@conditional` to `@keyword`:

```diff
diff --git a/crates/zed/src/languages/zig/highlights.scm b/crates/zed/src/languages/zig/highlights.scm
index 189d6aa46..a00036709 100644
--- a/crates/zed/src/languages/zig/highlights.scm
+++ b/crates/zed/src/languages/zig/highlights.scm
@@ -135,7 +135,7 @@ field_constant: (IDENTIFIER) @constant
   "if"
   "else"
   "switch"
-] @conditional
+] @keyword

 [
   "for"
```

What do you think?

**Comment by gabydd** [comment]
neovim  recently switched to being closer to the way  upstream and helix use them https://github.com/nvim-treesitter/nvim-treesitter/issues/4799

I dont think everything is the same now but they are probably closer: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/zig

**Comment by allancalix** [comment]
I went over a bunch of examples from the zig language tour and all the highlight seems to be working now. There's a bit of weirdness common to implementations of highlighting based on treesitter around highlighting for functions, here are some examples:

##  Neovim
Screenshot 2024-01-25 at 18 56 00


## Helix
Screenshot 2024-01-25 at 18 56 06

Neovim just highlights functions and variables all the same colors, helix tries to adhere to the official zig style guide but some big repos (like tigerbeetle) seem to favor using snake case function names so it's inconsistent.

Notably, vscode does this pretty much exactly as you'd hope but AFAICT doesn't use treesitter and depends on regex lookaheads to be able to do this. Notices how `bytes` is not highlighted in this example where in neovim it is. I don't know if this is currently possible to do put if someone wants to point me where to look I can give it a try or we can iterate after it's merged.

Another thing to note is `print` is captured to a variable but is a function call and is highlighted to match functions.

Screenshot 2024-01-25 at 19 00 24

Happy to merge as is though!

**Comment by gabydd** [comment]
depending on if you want to capture all function call syntax you can use:
```scheme
(
  (_
    variable_type_function: (IDENTIFIER) @function
    (FnCallArguments)) 
  (#match? @function "^[a-z]+([A-Z][a-z0-9]*)*$")
)
``` 
to match all camelCase even one word ones
or use
```scheme
(
  (_
    variable_type_function: (IDENTIFIER) @function
    (FnCallArguments)) 
)
``` 
to match all camel case and snake case

imo the grammar should probably tell if is a function or a variable but this seems like an ok way to check

**Comment by allancalix** [comment]
Wow! This. looks. great. Thanks for scheme-fu, updated the PR. Here's the result.

Screenshot 2024-01-25 at 20 26 41

**Comment by nathansobo** [comment]
Kicking off a build. Intrigued by Zig and we definitely want to support it.

**Comment by nathansobo** [comment]
I didn't realize builds needed approval. Maybe we need a bigger build farm so we don't require that.

**Comment by nathansobo** [comment]
Thanks very much! What else would be good to do for Zig?

**Comment by JosephTLyons** [comment]
Very cool!

**Comment by diocletiann** [comment]
> Thanks very much! What else would be good to do for Zig?

Breadcrumbs bar doesn't update as the cursor moves on my build.

**Comment by JosephTLyons** [comment]
Just to note - I think the outline view is also not working.

**Comment by matklad** [comment]
>I didn't realize builds needed approval. Maybe we need a bigger build farm so we don't require that.

https://matklad.github.io/2022/10/24/actions-permissions.html

**Comment by SomeoneToIgnore** [comment]
Latest stable release was a hotfix for certain channel-related issues, and the regular release is coming tomorrow only.

**Comment by StringNick** [comment]
Hi, is inlay hints working for zig?

**Comment by woshiwuja** [comment]
autocomplete fails for imported packages. Works in vscode and for std. works also in neovim. Any clue on how to implement that? havent seen anyone with this problem, maybe its just me?

**Pull request merged**
