### PR TITLE
telemetry: Abstract telemetry handling with trait

### PR DESCRIPTION
**Pull request by wolffiex**
Added a trait to telemetry so that downstream forks can configure alternate telemetry clients with minimal invasiveness

Release Notes:

- N/A

### CODE REVIEW

**Comment by wolffiex** [comment]
Is it possible that the test failure is spurious? Hard to see how this PR could have broken that. This works
`cargo nextest run --package client --lib telemetry::tests`

**Review by maxdeviant — CHANGES_REQUESTED** [review]
This seems like a lot of indirection to be adding for something that we're not going to make use of in Zed itself.

Could you state what the problem is you're trying to solve?

Would it suffice to have an easier way to set the URL used for telemetry events without needing to change the base Zed API URL? Or is there additional customization of the request that needs to happen (e.g., adding an `Authorization` header, etc.)?

**Comment by wolffiex** [comment]
Oh nope, not enough to just supply the URL I'm afraid. Here's what my code needs to do:
* Construct URL from environment and fail telemetry requests if expected info is missing
* Set headers
* Wrap EventRequestBody in expected message format

Happy to do this how you like. Would you prefer to see this refactored into a method that I replace in the fork?

**Comment by maxdeviant** [comment]
Closing in favor of https://github.com/zed-industries/zed/pull/18890.

**Pull request closed without merging**
