### PR TITLE
Use "enter" to ask for assistance

### PR DESCRIPTION
**Pull request by ConradIrwin**
This confused me, and a few other people in feedback; as although we
present this UI as a chat, it doesn't work like a chat.

Release Notes:

- Breaking change: Use `"enter"` to send a message to the AI. `"shift-enter"` can be used to extend the prompt.

### CODE REVIEW

**Comment by maxdeviant** [comment]
It does make it work less like an editor, though 🤔

**Comment by maxdeviant** [comment]
I do agree that the hotkey to submit the chat isn't entirely obvious, but I don't know that using "enter" and breaking the normal buffer behavior is the right solution.

I know at least for me this will make composing complex asks in the conversation editor more painful.

**Comment by JosephTLyons** [comment]
Though I recognize that this is inconsistent with how a typical chat behaves, I quite like the behavior. I do a lot of `enter`ing in that bad boy.

**Comment by iamnbutler** [comment]
Not a fan of this change at all – 

I use the assistant hours a day often, and specifically enjoy the way it works due to it just working like a regular buffer. I think it is one of the strengths of Zed's approach over any other I've worked with so far. I could see this being a setting, but not a default change.

**Comment by ConradIrwin** [comment]
👍 I talked this through with Marshall and came to the same conclusion. We do seem some UX improvements there, we've had several pieces of user-submitted feedback in the last 24 hours on the theme of "The "New Conversation" tab with gpt-4-turbo is unclear. I can type messages there for myself. But what is it used for? How does gpt-4 respond?". Marshall's idea was to add a "send" button with a cmd-enter tooltip, which I think would fix it.

(We also need to add error handling, as one reason for feedback like this is currently we can fail and show the user nothing).

**Pull request closed without merging**
