### PR TITLE
Support MSbuild row-column format in PathWithPosition

### PR DESCRIPTION
**Pull request by sndels**
This implements #15412.  Row-column parsing is changed into a regex to support more complex patterns like the MSBuild diagnostics. Terminal `word_regex` is also relaxed to match those suffixes.

Release Notes:

- N/A

### CODE REVIEW

**Comment by sndels** [comment]
The `url_regex` may still need tightening as I think `,` is a reserved character in urls?

@SomeoneToIgnore raised to consideration exposing the suffix regex in configs. The init cost of `Regex` means that we might have to take it as a parameter into `PathWithPosition::parse_str` in that case. We'd also need error reporting to the user when the custom regex isn't valid for what the parser expects, potentially falling back to the default one. `Captures::extract()` assumptions can be validated at runtime before calling it, avoiding the panic. Terminal `word_regex` and `url_regex` might need to be changed too depending on the custom regex, which is another gotcha to handle in user-facing documentation.

**Comment by sndels** [comment]
The `filename:.*` was a specific test case before. I’m not sure if some tools have non-row-col suffixes that it’s designed to drop. It does feel a little weird given the intent of the object and  the doc saying it parses whole `s` as a path if suffix parsing fails.

On Windows, `:` is not allowed in filenames but I guess sanitation that doesn’t involve file positions should be a separate thing that gets called later if necessary?

**Comment by mrnugget** [comment]
Hey @JunkuiZhang could you review this?

**Comment by JunkuiZhang** [comment]
These changes look good to me. However, my concern is whether this is the best approach to implement (However, at this point, the current implementation seems to be the best we can achieve). I mean, do we have to change the codes here every time when there is a new pattern needs to be matched? Maybe some form of extension would be better? We can only implement the most basic pattern matching here, the other stuff like MSbuild path matching can go with an extension or something similar. For example, Windows Terminal, only matches the most basic patterns, `"file://D:\some\path\"` wouldn't be matched.

Screenshot 2024-08-06 221553

And, I don't insist on my opinion.

**Comment by sndels** [comment]
I agree that a more easily customizable solution would be nice to have in the long run if more of these suffixes crop up, especially if they become a hindrance for maintenance or perf. My intuition is that `:row:column` and `(row,column)` cover a lot of ground already based on Zed's current language support and the languages/toolchains I regularly use, so I might err on the side of simplicity until more suffixes or some other issue manifests. However, I'll trust your judgement as a maintainer.

`PathWithPosition` feels like the logical place to do the parsing even if it were extendable since its one job is to parse out the file position suffix. A runtime extendable solution based on this implementation would likely have to handle
- Validating the suffix regex for use with `Captures::extract()`
  - Clear errors when it's not valid, fallback to avoid panic
- Support changing `TerminalBuilder`'s `word_regex` and `url_regex` too when needed
  - `word_regex` might filter out suffixes that the user regex would parse
  - `url_regex` might let through malformed urls when `word_regex` changes (like `,` with the proposed changes?)
  - Needs clear documentation for the interactions/requirements between the three regexes and the components that depend on them
- Hardening against user regexes if they could break critical behavior by filtering out/letting through the wrong things
  - Fallbacks/UI errors?
- Cache the suffix regex to avoid its init cost on every parse like the static `LazyLock` does now
  - The current one already takes >.2ms to init with or without wrapping in `LazyLock` and I'm not sure how bad it could get with user input

 I don't know if there is another way to implement this without some of those needs.

**Comment by thorbenk** [comment]
Python will output `"file.py", line 3` for runtime errors. Zed does not currently recognize the line number, either. I've opened https://github.com/zed-industries/zed/issues/16004 for this.

**Comment by sndels** [comment]
Oh, right. Python feels like something that should work out of the box.

It would be really nice if the location parsing was brought by the language extension. I guess it could be expensive to go through all extensions’ parse results until one matches, though. Languages are frequently mixed in projects and build tooling.

**Comment by mrnugget** [comment]
Thanks for this!

**Comment by SomeoneToIgnore** [comment]
Funny, but turned out the regex was not working until today and https://github.com/zed-industries/zed/pull/19004
Luckily now we have tests for future cases.

Also thanks to https://github.com/zed-industries/zed/pull/18425 I've realized that this broke Zed's ability to open file patterns like `new file (2).txt`.
This is easy to fix though, so no big issues, just more context on where things should move, in case someone is interested.

**Comment by sndels** [comment]
> Funny, but turned out the regex was not working until today and #19004
> Luckily now we have tests for future cases.
Huh, weird 😄 I've been happily running a locally compiled v0.419.0 so I guess this just happened to work with how the parsing was structured back then. Seems like there has been some recent changes to parsing/path handling outside `PathWithPosition` as I did run into this issue too on a newer version tag https://github.com/zed-industries/zed/issues/18550

**Pull request merged**
