### PR TITLE
Add a way to explicitly specify RC toolkit path

### LINKED ISSUE #18393: Cannot build on Windows (invalid RC path from `winres` dependency)
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I get the following error when building zed:

```
error: failed to run custom build command for `zed v0.154.2 (C:\Users\USER\src\zed\crates\zed)`

Caused by:
  process didn't exit successfully: `C:\Users\USER\src\zed\target\debug\build\zed-b24f1e9300107efc\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=../../.git/logs/HEAD
  cargo:rustc-env=ZED_COMMIT_SHA=25e2e9c6727ba9b77415588cfa11fd969612adb7
  cargo:rustc-link-arg=/stack:8388608
  cargo:rerun-if-changed=resources/windows/app-icon.ico
  package.metadata.winresource does not exist
  Selected RC path: 'bin\x64\rc.exe'

  --- stderr
  The system cannot find the path specified. (os error 3)
warning: build failed, waiting for other jobs to finish...
```

Here are the commands to reproduce the bug:

```
rustup update
git clone https://github.com/zed-industries/zed
cd zed
git checkout tags/v0.154.2
cargo run
```

**Investigation**:

I believe this is the same error as the one described [here](https://github.com/tauri-apps/tauri/issues/2871#issuecomment-969191116).
Building zed from my personal laptop works fine but building it on my work laptop doesn't. This is probably due to the IT security rules, as in the comment I've posted above.

Is it possible to bypass that problem? Maybe providing manually the RC path through the command line instead of letting it be deduced from registry values?

### Environment

**Device specifications:**

Device name	USER
Full device name	USER.MYCOMPANY.com
Processor	AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics     3.30 GHz
Installed RAM	32,0 GB (31,3 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

**Windows specifications:**

Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎28/‎05/‎2024
OS build	22621.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by 0hDEADBEAF**
Closes #18393 

Release Notes:

- Added a `ZED_RC_TOOLKIT_PATH` env variable so `winresource` crate can fetch the RC executable path correctly on some configurations

### CODE REVIEW

**Comment by 0hDEADBEAF** [comment]
@cla-bot check

**Comment by 0hDEADBEAF** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, can we document it somewhere in the Windows development document?
 https://github.com/zed-industries/zed/blob/250f2e76eb6f97fe097ee39863c621335762c102/docs/src/development/windows.md?plain=1#L1

Ideally, we could add a couple related documentation links there on top.

**Comment by 0hDEADBEAF** [comment]
Yes, I can add documentation in that Markdown file :)

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks!

**Pull request merged**
