### PR TITLE
docs: Split vim mode documentation into two pages, edit for clarity

### LINKED ISSUE #17215: Vim docs could be more structured and approachable for new users (proposal)
### Check for existing issues

- [X] Completed

### Describe the feature

This issue is a little proposal for a contribution I'd like to make to the docs for vim mode.

Currently, the [Vim mode docs page](https://zed.dev/docs/vim) provides valuable information, but it could use a little more structure (it bounces back and forth between configuration and explaining differences in Zed's emulation layer), and it sometimes assumes some understanding of Zed and non-basic nvim ecosystem details.

I'd like to make it more approachable for new users and clearly separate the parts about configuring vs using the vim mode.

For that, besides editing, I would split the vim docs into two pages:

1. Under the **Configuring** section, a page only about configuring the vim mode: toggling vim mode, settings, keymap, and using the context in custom keymap entries.
1. Under **Using Zed**, a page about using the vim mode and all the provided key bindings and features. It would talk about toggling vim mode, vim mode design philosophy, provided features and commands, using the command palette, using Zed-specific additions, outline optional Vim mode features (surround, camelCase word navigation, etc.).

The two pages would cross-link.

In terms of edits, I'd like to format keybindings presented as code blocks in tables, similarly to other pages, and flesh out the text to improve precision and accessibility.

I started with a small set of edits in #17214 so you can tell me if you'd like any changes to the writing style. I'd gladly continue from there. Please let me know if you'd like this approached differently.

~~I'd also tackle #15591 as part of this work, in a single or multiple PRs, whichever works best for you.~~

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by NathanLovato**
Closes #17215

Release Notes:

- N/A

---

This PR builds upon the vim mode documentation page and aims bring the following improvements:

- Separate vim mode-specific configuration from introducing vim mode.
- Reformat some lists of provided commands and keymaps from code blocks to sub-sections containing tables.
- Flesh out the text a little bit to make it more explicit in some parts.
- Generally format notes and a couple of other things closer to some other docs pages.

Checking the diff doesn't give a good idea of the changes, so here are some before after images for quick examples of the kinds of changes brought by this PR.

**Introducing the key differences of Zed's vim mode**

Before

After

---

**Zed-specific vim key bindings**

Before

After

### CODE REVIEW

**Comment by NathanLovato** [comment]
I didn't have time to complete all I wanted to edit this afternoon, so leaving as draft for now. I'll complete it as soon as possible.

**Comment by ConradIrwin** [comment]
Thanks for this! let me know when it's ready to go

**Comment by NathanLovato** [comment]
@ConradIrwin this should be good to go! Please feel free to change anything directly, and of course request any changes. The two new pages feature cross-links in the introduction and generally a handful more links.

**Comment by NathanLovato** [comment]
@ConradIrwin this should be good to go! Please feel free to change anything directly, and of course request any changes. The two new pages feature cross-links in the introduction and generally a handful more links.

**Comment by ConradIrwin** [comment]
Thanks for this, and sorry for the slow reply.

I'm struggling a bit with the introductions to the two pages, as there's a lot of repetitive stuff and it's not clear which document you should read first if you're new.

Although we talked about splitting them, now I see the result, I think we should re-merge the two pages; but keep the new formatting and prose, and have the introduction link further down for people who want to jump to a specific section.

Do you want to take a pass of that, or should I?

**Comment by ConradIrwin** [comment]
That sounds great, thank you!

**Comment by NathanLovato** [comment]
@ConradIrwin It's merged! I removed cross links, proofread, and tried to find an OK order for covering things. It's summarized in the bullet list in the intro. Let me know if this needs any changes, and also feel free to change anything directly too if it's easier for you.

**Comment by ConradIrwin** [comment]
Awesome, thank you!

**Pull request merged**
