### PR TITLE
Translate notify::Event to fsevent::Event on linux

### PR DESCRIPTION
**Pull request by gmorenz**
This isn't exactly a great solution, but it's a step in the right direction, and it's simple allowing us to quickly unblock linux. Without this (or an equivalent) PR linux builds are broken.

I spent a bunch of time investigating using notify on macos, and have a branch with that working and FakeFs updated to use notify events. unfortunately I think this would come with some drawbacks. Primarily that files that don't yet exist yet aren't handled as well as with using events directly leading to some less than ideal tradeoffs.

This PR is very much a placeholder for a better cross platform solution. Most problematically, it only fills in the portion of fsevent::Event that is currently used, despite there being a lot more information in the ones collected from macos. At the very least a followup PR should hide those implementation details behind a cross platform Event type so that if people try and access data that hasn't been translated, they find out about it.

Release Notes:

- N/A

### CODE REVIEW

**Comment by gmorenz** [comment]
Just for clarity, the mac_impl module is just a copy and paste of all the code that use to be in fsevent.rs and now isn't. Nothing was actually changed in that crate except for moving code around so we can get access to the fsevent::Event type on linux.

**Comment by maxdeviant** [comment]
Should we also move the Linux (or, non-macOS, I suppose) implementation into a separate module to make it clearer what belongs to each platform?

Maybe `notify_impl.rs`?

**Comment by gmorenz** [comment]
Yes, but as part of a larger refactoring that I didn't want to block the other linux work on. Long explanation:

Right now the common interface for filesystem notifications is `fs::Fs::watch`, which gives notifications in terms of `fsnotify::Event` and `fsnotify::StreamFlags`, which are structs that expose internals of the mac fsnotify api. `fsnotify` is a mac-os crate, and the only reason there's an `mac_impl` file in the first place is so that we can expose the mac-os type definitions to our non-macos implementation for translation.

All the notify specific code is currently in the `notify` crate, or a thin translation layer in the non-macos implementation of `fs::Fs::watch` (trait method) for `RealFs`(struct) - which takes about a dozen lines of code.

What should probably happen in refactoring is that the `RealFs` implementation of `fs::Fs::watch` becomes a thin wrapper around a `our_notify_crate::watch` method with different implementations on different platforms returning types defined in `our_notify_crate` that hide platform details we don't care about. The `RealFs` implementation itself should then be platform independent.

But the paragraph above implies design decisions and simply more work (discussed below), so to unblock being able to build zed on linux I think we should merge this first. Since a change like this is required to make linux build at all, and this change doesn't change anything at all on macos (except for the file some code is in), it seems like a very safe interim solution.

---

I really would have liked to make the `our_notify_crate` I referenced above just the `notify` crate, ditching the custom `fsnotify` crate entirely. It does exactly what I'm proposing to do after all, create a cross platform abstraction around filesystem notifications. That's what I tried to do [in this branch](https://github.com/gmorenz/zed/tree/notify).

Unfortunately it seems to me that the api notify currently exposes would result in regressions in macos. Either we would have to accept not watching for the creation of files when they don't exist, we'd have to handle *every* file notification below the top level folder that exists in their path, or we'd have to implement some overly complex logic to handle files not existing (like watching the first existing ancestor directory non-recursively, and then re-starting the watcher every time a new level in the directory tree is created).

Those regressions are also problems for linux of course. Right now when zed tries to listen for a settings file that doesn't exist on linux we emit an error log message and don't watch for its creation. We need to figure out the best way to do this for linux - and we should probably figure that out before we create/select our cross platform API for file watching and refactor to using it.

**Comment by mikayla-maki** [comment]
Thanks for the explanation @gmorenz, since this is a bandaid to get linux building I think we can go for it and fix the deeper issue in a dedicated way.

**Pull request merged**
