### PR TITLE
Add Solidity syntax support

### PR DESCRIPTION
**Pull request by meetmangukiya**
Release Notes:

- Added solidity syntax support [#4872](https://github.com/zed-industries/extensions/issues/160).

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@cla-bot check

**Comment by meetmangukiya** [comment]
Is there any specification on indents.scm queries and how they are used? I couldn't get `struct` declaration to indent properly. Others seem alright.

**Comment by ThatXliner** [comment]
the recently merged Zig support PR could be of some help:

https://github.com/zed-industries/zed/pull/6690

**Comment by alvgaona** [comment]
Here's another [Solidity tree-sitter repo](https://github.com/JoranHonig/tree-sitter-solidity) that might help you build the queries.

**Comment by alvgaona** [comment]
> Here's another [Solidity tree-sitter repo](https://github.com/JoranHonig/tree-sitter-solidity) that might help you build the queries. Look in the `queries/` dir.

I see the repo you added in the TOML file is a fork from the one I suggested here. Why are you using a fork and not the original?

**Comment by meetmangukiya** [comment]
Yeah it doesn't have indents query.

I had to fork it because [tree-sitter version was incompatible](https://github.com/parmanuxyz/tree-sitter-solidity/commit/ae2d0d99322a8e83a30a0ac6a2ccce326e07d411) and I didn't that PRing that upstream just for zed made sense. I believe many of them in Cargo.toml are already forks for similar reasons.

**Comment by SomeoneToIgnore** [comment]
Hello, and sorry for coming up with a slightly delayed response: there's a lot of going on and we needed to push on a PR to make this more justified.

We seem to be close to provide a generic way to add a tree-sitter grammar support: https://github.com/zed-industries/zed/pull/7105

We want to avoid collecting support for all possible languages in the Zed source tree, since neither we're able to properly check if the support is good or not, nor the compile times and other things will be convenient.
So, now we try to close syntax-related language support PRs, and even some "rare" LSP support PRs too:
https://github.com/zed-industries/zed/pull/7094#issuecomment-1917805704
https://github.com/zed-industries/zed/pull/7010#issuecomment-1917570899

This one falls into the category of the language highlight, so we'll close that, but hopefully will be able to provide a better, more generic way to add Solidity highlights in Zed.

**Pull request closed without merging**
