### PR TITLE
Fix TSX highlighting on Windows

### LINKED ISSUE #13110: TSX files not showing correctly on Windows, on the bottom bar it says "Unknown" on the language type
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open a .tsx file the highlights don't show up, and in the bottom it says Unknown language. 
Edit: Its also happenning with .ts files, if I add the tsx file in the settings to file_types

### Environment

Zed: v0.141.0 (Zed Dev 15d3e54ae3ac0e0e9256cdebfd41d9e38e6cb7eb)
OS: Windows 10.0.22631
Memory: 23.9 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-06-16T16:51:33+02:00 [INFO] Took 9.2899ms to receive response to "notifyRejected" id 25
2024-06-16T16:51:33+02:00 [INFO] Took 18.0356ms to receive response to "getCompletions" id 26
2024-06-16T16:51:33+02:00 [ERROR] failed to load language TSX:
Error loading brackets query

Caused by:
    Query error at 1:1. Invalid syntax:
    ../typescript/brackets.scm
    ^
2024-06-16T16:51:33+02:00 [INFO] Took 3.4581ms to receive response to "notifyRejected" id 27
2024-06-16T16:51:33+02:00 [INFO] Took 4.6366ms to receive response to "notifyRejected" id 28
2024-06-16T16:51:37+02:00 [ERROR] crates\assistant\src\assistant_panel.rs:954: Az elem nem található. (0x80070490)
2024-06-16T16:51:37+02:00 [ERROR] crates\assistant\src\assistant_panel.rs:954: Az elem nem található. (0x80070490)
2024-06-16T16:51:39+02:00 [INFO] Took 4.1897ms to receive response to "notifyRejected" id 29
2024-06-16T16:51:39+02:00 [INFO] Took 4.0737ms to receive response to "notifyRejected" id 30
2024-06-16T16:51:48+02:00 [INFO] Took 5.1133ms to receive response to "notifyRejected" id 31
2024-06-16T16:51:48+02:00 [INFO] Took 3.5609ms to receive response to "notifyRejected" id 32
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }
2024-06-16T16:52:01+02:00 [ERROR] crates\gpui\src\elements\img.rs:345: BadStatus { status: 404, body: "Not Found" }

### PR DESCRIPTION
**Pull request by Huliiiiii**
fix #13110

Release Notes:

- N/A

### CODE REVIEW

**Comment by Huliiiiii** [comment]
@cla-bot check

**Comment by Huliiiiii** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
`inherits:` is a Neovim directive, and as such does not work in Zed.

**Comment by Huliiiiii** [comment]
@maxdeviant it works for me :)

**Comment by Huliiiiii** [comment]
@maxdeviant 
Does zed find and replace content based on paths in scm files? If so can you tell me where Zed parses the paths? Because it doesn't work on windows.
```
Caused by:
Query error at 1:1. Invalid syntax:
../typescript/brackets.scm
^
```
I'll try to fix it.

**Comment by maxdeviant** [comment]
> @maxdeviant Does zed find and replace content based on paths in scm files? If so can you tell me where Zed parses the paths? Because it doesn't work on windows.
> 
> ```
> Caused by:
> Query error at 1:1. Invalid syntax:
> ../typescript/brackets.scm
> ^
> ```
> 
> I'll try to fix it.

Right now we're relying on symlinks, which I presume is why it isn't working on Windows.

Not sure what the best way to handle it would be. I think it needs further discussion in #13110.

**Pull request closed without merging**
