### PR TITLE
Scrollbar perfomance improvements

### PR DESCRIPTION
**Pull request by alygin**
This PR addresses performance issues with drawing large numbers of scrollbar markers in large files. Discussions that started this work:
- https://github.com/zed-industries/zed/issues/9055#issuecomment-1999318878
- https://github.com/zed-industries/zed/pull/9080#issuecomment-2004521464

This is still work in progress, not intended to be merged.

What's done so far:
- When possible, markers are now combined into contiguous hunks which are painted as a single quad.
- Number of rendered marker hunks is limited to 5000.
- Marked row ranges for search results and symbols are cached
- Removed duplication of markers for search results
- Markers rendering unified, specifics moved to `markers.rs`

Open questions:
- Is caching in `Editor` a right thing to do?
- Cache invalidation on folding, inlays toggling, wrapping, and other things that affect marker positions. I'm not sure it's completely and efficiently covered.

cc @mrnugget, @osiewicz

### CODE REVIEW

**Comment by alygin** [comment]
@mrnugget, with caching, the scrollbar works very well even on large files with thousands of markers.

Though I'm a bit hesitant about this approach because of necessity of cache invalidation. I've added it for some common usecases &mdash; folding/unfolding and soft wrapping/unwrapping.

What do you think? Is such implementation viable?

**Comment by as-cii** [comment]
Hey @alygin, thanks so much for attacking this performance issue!

I share your concerns about cache invalidation, I would really love to not even have caching at all, so I am wondering about an alternative approach…

It seems like when we don't have a long file things are pretty smooth. As the file gets longer, the scrollbar will naturally tend to lose resolution, and yet it seems like we're trying to display a lossless representation of what's in the buffer, even though we most likely can't even paint it (e.g., some markers won't even be 1px tall on screen). Therefore, I wonder: could we apply some quantization mechanism when we _query_ information to insert into the scrollbar?

Put another way, the scrollbar's height is only gonna occupy a finite amount of pixels (e.g., on my screen it's ~1000px). So, in my specific case, it seems like we should query at most 1000 "markers" from the underlying data structures, because we can't literally display more information than that anyway. 

A strategy for doing so would be: divide the number of actual rows by the scrollbar's height. This should give us how many rows each pixel represents. In the example above, assuming I have a file that has 3000 rows, each pixel corresponds to 3 rows. Then, when we query the structure, we should be able to start at the beginning, e.g. row 0, query all the information we have for that row, and advance to the next _marker_ that starts at a row greater than 3.

Then I think it also makes sense to draw just one quad for consecutive markers of the same kind, e.g. if we have a marker at row 0, row 3, row 6 and row 9, we should just draw one quad that encompasses all the rows (4px tall, continuing the example).

Does this make sense? You've already dived into an implementation so there might something I'm missing here. I would be curious to explore how fast rendering would get if we applied this quantization scheme without caching. What do you think?

**Comment by as-cii** [comment]
One more thought on this is: if we can't provide the answer synchronously within a reasonable amount of time, maybe we can query this information in the background and then notify once we have it?

**Comment by alygin** [comment]
@as-cii, thanks for sharing your thoughts on this!

Just to be on the same page regarding the implementation in this PR: the highlights go through the following pipeline:
1. They are extracted from the editor's `background_highlights`, thransformed into buffer row numbers, and grouped into contiguous row ranges. For instance, if we have highligts in rows 5, 6, 7, 9, 10, we'll end up with two ranges: 5..7 and 9..10 on this step.
2. We cache the resulting row ranges.
3. When we need to draw markers, we retrieve those cached ranges.
4. We apply all the folidng-, wrapping-, inlaying- etc. transformations.
5. We apply scaling to the scrollbar.
6. We merge resulting quads to draw as few of them as possible.

So, it's very close to your idea, if I understood it correctly. We now have both optimization of the initial data and optimized markers drawing. The only difference I see is the optimization approach on step 1. We can improve it (reduce the number of resulting ranges in some cases) with the algorithm you described.

But, I think, it won't be enough to make scrollbar smooth. Here's why: In the case that started this work, we have 68K highlights. They come in large contiguous ranges with large gaps between them (see the screenshot below). It's good for the range-optimization because of those contiguous ranges, but it won't produce better results from the algorighm you described, because of the large gaps. Thus, in this case, I assume the results will be very close in what we have in this PR.

On step 1 we reduce 68K highlights to only 200 ranges, which seems good. Even withoug caching, the resulting scrollbar performance is much better than in the `main`, yet it's still not very smooth.

Do you think it's correct to assert that the current implementation is close enough to your ideas? Or do I miss something?

large-file-markers

**Comment by alygin** [comment]
@as-cii , @mrnugget , I've removed caching so you can check how it works. The implementation now is very close to what @as-cii described, without caching and async-things. Just reducing the number of initial ranges and number of painted quads.

**Comment by as-cii** [comment]
@mrnugget and I reviewed the code, and we think the implementation doesn't quite achieve what I was trying to describe in the above comment. Maybe we're missing something but here's another stab at describing what I meant.

The changes in this pull request seem to group contiguous ranges together, which is great for minimizing the amount of quads that we paint. I think we should keep doing that. 

However, it seems like we're still performing a lot of conversions from anchors to rows and visiting all the background highlights. What I had in mind instead was to flip it around. Instead of looking at all the rows, coalescing them, and then drawing highlights, we should instead:

1. Calculate how many rows a pixel corresponds to (`rows_per_pixel = rows / height_in_pixels`) (e.g. if we have a height of 1000px and 3000 rows, one pixel corresponds to 3 rows)
2. Set `start_row = 0`, `start_index = 0`
3. Binary search the whole set of highlights (e.g. `highlights[start_index..]`) to find the first highlight greater than or equal to `start_row`
4. This will give us an index into `highlights` and a row where the highlight starts
5. Store that marker into a pending quad, because the next marker might be coalesced with this one if they are contiguous
6. Set `start_row = highlight_end_row + rows_per_pixel` and `start_index = highlight_index`
7. Go to 3

Maybe we are missing something but it seems like this should achieve a significant speedup because this will perform a constant amount of queries independently of how many highlights we have. Thoughts? 💭

**Comment by alygin** [comment]
> @mrnugget and I reviewed the code, and we think the implementation doesn't quite achieve what I was trying to describe in the above comment. Maybe we're missing something but here's another stab at describing what I meant.

Sorry, that's my fault. I understand the approach you suggest. And I understand that it differs from my implementation. But my first reaction was that _in the particualr case that we look at_ it will be the same performance-wise.

But now I see that there really may be a significant difference. I'll get back with the implementation tomorrow.

**Comment by alygin** [comment]
@as-cii, your idea works well. The scrolling is smooth on that large file with 68K search results that result in 200 marker quads. I'll extend this solution to other marker types.

**Comment by mrnugget** [comment]
@alygin hey! just to keep you up to date: after checking out this branch and playing around with it a bit, @as-cii and I noticed that it's still a bit bumpy when there's lots of search results. So we started working on an approach that moves the computation to a background thread. That seems _very_ promising and we plan to continue on that: https://github.com/zed-industries/zed/pull/10080.

**Comment by alygin** [comment]
Hi @mrnugget! Thanks for the info! I wonder if you noticed performance problems in the initial case (that 68K-results searching), or was it something different?

As for the async-approach, are you planing to combine it with the optimization from this branch? Or we can close this one?

**Comment by as-cii** [comment]
@alygin I think we're not going to apply this optimization in that branch as it feels orthogonal, but I'd still like to do it as it's more efficient. It would be great if you could apply the same optimization on top of #10080 once we land it!

**Comment by alygin** [comment]
@as-cii, sure! Then I'll close this one, and reopen it when #10080 is merged.

**Pull request closed without merging**
