### PR TITLE
project_search: Add ability to search only for opened files

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Any suggestion?

Release Notes:
  - add ability for project search only in opened files.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this, it would be great to support this in Zed!

I think we should do this more explicitly by adding an `buffer_ids: Vec<BufferId>` to `SearchInput`. Then in project we can just iterate over open buffers instead of doing a local or a remote search.

This will allow us to respect the include filter in addition to the exclude filter; and avoid collisions where if you have "/README.md" open, "/foo/README.md" will match.

On the UI side, let's make it so that:
* The button is at the end so it is [include filter] [exclude filter] [icon] [icon]
* If you enable "search excluded files" we should disable "search only open" and vice-versa to make it clear that it only makes sense to have one of these options selected.

For the icon we should probably use the Markdown icon, or the Open Folder icon instead of the closed Book icon. Unless @danilo-leal has a better idea.
Screenshot 2024-08-22 at 19 28 52
Screenshot 2024-08-22 at 19 28 54

Let me know if you'd like to pair on this: https://calendly.com/conradirwin/pairing

**Comment by CharlesChen0823** [comment]
> I think we should do this more explicitly by adding an buffer_ids: Vec<BufferId> to SearchInput. Then in project we can just iterate over open buffers instead of doing a local or a remote search.

Do you mean `SearchQuery` not `SearchInput` ? Original, I use `project::opend_buffers` for get all opened buffer paths, but there has an edge case, when user hit search/project_search, all of these opened buffer will also respect, I don't know if this is accept?

> Let me know if you'd like to pair on this: https://calendly.com/conradirwin/pairing

I'm not good at english, so I think comment is fine.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 It could be on SearchQuery or SearchInput. I think SearchInput is better because that contains the `include/exclude` filters already.

As you say we can't just use the Project's open buffers, so we do need to get the Buffer ids in the way you currently do from the workspace (but return `buffer.read(cx).remote_id()` instead of the file path).

In the `Project::search` function I think we should notice `if query.is_opened_only() { self.search_open(query) } else if self.is_local() ...`. The `search_open` function can be a simplified version of the existing `search_local` that only handles open files and does not scan over the worktrees.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 In #16782 I made a bigger change to how search is factored. Once that's landed it should be much a bit easier to only look at the open buffers.

**Comment by CharlesChen0823** [comment]
@ConradIrwin I temp modify some code, want to known if this is your expected?

And I will wait until #16782 landed, then work remain.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 Yes, that was exactly what I meant. 

That said @maxbrunsfeld and I changed the API again today for #16915 - I've merged your branch into that and made the toggle work.

Please let me know if you have time to make the UI changes I suggested above.

**Comment by CharlesChen0823** [comment]
I will do remain.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 Sorry for all the back and forth here, we've been making a lot of changes to project search this week :D.

I've updated the branch to a state I think is good. Does it work as you expect?

I also reverted the change I asked for about filtering. Before #16923 we used to include open ignored files in the search results, but we decided that was a bug; so now it does make sense to be able to toggle ignored files independently of open buffers. Sorry for making more work for you there.

**Comment by CharlesChen0823** [comment]
@ConradIrwin yes, this work as i expect.

**Comment by gianpaj** [comment]
Is there a way, in the settings, for example, to search opened files in addition to the project files? Not exclusively, as at the moment
image


Use case: I modified files in the `.venv` python folder (currently ignored), and I have them opened.

I would like to search for a string as I manually extended some functionality in a module I've installed. Thanks 🙌 

I am happy to open an issue if this needs to be considered separately

**Pull request merged**
