### PR TITLE
Use standard captures in injection queries

### PR DESCRIPTION
**Pull request by michaelfortunato**
Before this commit, zed was using captures and properties for injection queries that did not match the tree sitter [documentation][1] This was breaking the Java extension when it came to its injections.scm, and would likely break other tree-sitter extensions as authors are instructed in the tree-sitter docs to use the standard captures and properties for injection queries.

## Changed
The following properties and captures used for injections have changed to be the standard ones. In particular

- @language to @injection.language
- @content to @injection.content
- combined to injection.combined
- language to injection.language

## Testing
Unit tests have been updated with the standard captures as well. In particular,  `cd crates/language && cargo test --lib` and `cd crates/editor && cargo test --lib` both have been updated and pass on my machine.

[1]: https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection

Release Notes:

- Use standard captures in injection queries ([#9656](https://github.com/zed-industries/zed/issues/9656)).

### CODE REVIEW

**Comment by michaelfortunato** [comment]
@cla-bot check

**Comment by michaelfortunato** [comment]
@cla-bot check

**Comment by maxbrunsfeld** [comment]
Yeah, good point @michaelfortunato - no reason to do it differently from the other tree-sitter stuff.

**Review by maxbrunsfeld — APPROVED** [review]

**Comment by michaelfortunato** [comment]
Sounds good. I had to resolve a conflict, I think it'll be able to merge now with your approval @maxbrunsfeld. Also https://github.com/zed-extensions/svelte/blob/main/languages/svelte/injections.scm will have to be updated as well.

**Comment by maxbrunsfeld** [comment]
@michaelfortunato Sorry for the delay. We now have extensions, so there are fewer languages to update in this repo, but we need to make the change in a backwards compatible way (accepting both capture names). If you are up for doing that backwards compatibility change, then we are still up for merging this.

**Comment by mikayla-maki** [comment]
As there hasn't been movement on this PR in 3 weeks, I'm going to close it for now. We're still interested in supporting these captures, it should just be backwards compatible with our existing captures :)

**Pull request closed without merging**
