### PR TITLE
Fix first/last item margin on scroll

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- Fixed first and last item margin when scroll view has padding.

## Before

https://github.com/zed-industries/zed/assets/5518/f7a4563a-504a-4a41-bfd4-21e9439cd02b

## After

https://github.com/zed-industries/zed/assets/5518/0ba41527-46fd-404f-8207-1b8c5cf37434

This change has modified the gpui basic element, so I don't know is there have side effect that out of my tests. By my tested cases, it is looks ok.

output

### CODE REVIEW

**Comment by huacnlee** [comment]
Look at the first item, there still have a 1px offset, I am trying to fix it.

**Review by SomeoneToIgnore — COMMENTED** [review]
Looks great, thank you.
I'm interested, is this hard to backport to the regular list case?
In https://github.com/zed-industries/zed/blob/7fe5f04d53126abba4568f489de66d61a2230085/crates/recent_projects/src/recent_projects.rs#L46
we enable it for recent project picker with paths, and that one obviously has no padding still:

image

**Comment by huacnlee** [comment]
The `list` element have fixed.

output

**Comment by huacnlee** [comment]
@SomeoneToIgnore Should I need to fix the 1px offset? That will change the list item vertical gap.

**Comment by huacnlee** [comment]
Last commit, I have adjusted the command Palette and File Finder item height to avoid the 1px offset on scroll top:

From 31px to 33px:

## Before
SCR-20240305-rcn
SCR-20240305-rj7


## After
SCR-20240305-rdh
SCR-20240305-rj0

**Review by SomeoneToIgnore — APPROVED** [review]
What I'm a bit concerned about is that `.py_px()` solution seems breakable with fonts of larger sizes?
But that does not seem like a big issue: it does not break for my `Monocraft` font that breaks a lot of other things already, and the main fix with edge paddings is good.

Thank you for fixing those style tings.

**Pull request merged**
