### PR TITLE
Add command to copy current file:line for working with external tools

### LINKED ISSUE #14787: Command to copy file:line of current line.
### Check for existing issues

- [X] Completed

### Describe the feature

Let's say you find the debuggers in other similar editors to be really basic, so you aren't too upset that Zed doesn't have one built-in. BUT You do find it handy to be able to just click to set breakpoints since that's one of the most common debugging tasks.

It occurred to me that an easy way to get half way there is to just provide a feature (a command I can bind to a key? or in the right click menu?) that copies the current filename:line". So if I'm using gdb for instance I just click, copy, then "b <paste>" to set a breakpoint. Not the same as an integrated debugger, but still a very convenient step forward.

### If applicable, add mockups / screenshots to help present your vision of the feature

zed-copy-file-line

### PR DESCRIPTION
**Pull request by slembcke**
Closes #14787.

I made a quick draft implementation of this feature request: https://github.com/zed-industries/zed/issues/14787

I know how to use use gdb well, so lacking a built-in debugger is OK. BUT... Speaking personally, setting breakpoints is 50% of what I want an IDE to do for me when debugging. Having a feature where I can click, copy, "b [paste]", is a huge step up from typing the whole thing in manually. I figure this must be useful for other external tools, or even just regular-human-communication too.

Open Questions:
* Does this belong in the right click menu? (I put it next to "Copy Permalink" which is similar.)
* Probably not useful enough to get a default keymap?
* Relative vs absolute path?
* Does this need tests?

Release Notes:

- Added `editor: copy file location` command to copy the current file location (FILE:LINE) to the clipboard ([#14787](https://github.com/zed-industries/zed/issues/14787)).

### CODE REVIEW

**Comment by maxdeviant** [comment]
We might want to come up with a more semantic name than `CopyFileLine`, as it sounds like it's going to copy a line from a file.

Maybe something like `CopyLineLocation`?

I'm not sure if we already have a name in the codebase for the `FILE:LINE` information.

**Comment by slembcke** [comment]
> Maybe something like `CopyLineLocation`?

Makes sense to me. I can make that change later tonight.

> I'm not sure if we already have a name in the codebase for the `FILE:LINE` information.

I tried a handful of search terms, but couldn't find anything. Any help figuring that out would be helpful.

Any opinions on if it should be an absolute or relative path? Absolute paths can get annoyingly long or machine specific, but I figured they might be a bit more universal. Personally I only need relative paths for my gdb use case, and someone wanting to paste it into a chat would probably prefer relative too...

**Comment by slembcke** [comment]
Ok!

1) Renamed to CopyFileLocation
1) after a lot of waffling, I changed it to use relative paths.

While there might be some use cases that don't work with relative paths, (I guess I can't think of any?) all the cases that benefit from the brevity of relative paths I can think of maybe outweigh the unknowns? Jeez, completely waffling here.

As a Rust novice (I wrote like 1000 lines 5 years ago), It's completely unclear where the CopyFileLocation struct is defined. It seems to work as long as all of the usages agree, but it's never actually defined??! I don't actually need an explanation, as long as someone is convinced I did it all right. Long time C programmer here. >_>

Also, "LineLocation" seems to mean the same thing within the Rust analyzer at least. I can't find other names for the same concept in the Zed code base, but it's big, and I'm new.

@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thank you!

I ended up removing the option from the right-click menu in the editor, so it will just be accessible from the command palette, for now.

We can revisit that decision if it seems that adding it to the right-click menu would be beneficial for a good portion of folks.

**Comment by slembcke** [comment]
Fair enough. It seemed similar to the "Copy Permalink" so I went for it. I've been using it with a key binding myself though.

Thanks!

**Comment by Moophic** [comment]
Can the column index be added as well, please?
Something like "LINE:ROW:COLUMN".

**Pull request merged**
