### PR TITLE
Fix keybindings on a Spanish ISO keyboard

### PR DESCRIPTION
**Pull request by ConradIrwin**
Co-Authored-By: Peter <peter@zed.dev>

Also reformatted the mappings to be easier to read/edit by hand.

Release Notes:

- Fixed keyboard shortcuts on Spanish ISO keyboards

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
This fix is quite critical for anybody using zed with a spanish keyboard. I had to revert back to an older version because of this.

**Comment by ConradIrwin** [comment]
@ConsoleTVs v0.162.4 is out with the fix.

**Comment by acstll** [comment]
I was suffering haha, thank you for the fix!

**Comment by aabedraba** [comment]
Thank you!

**Pull request merged**
