### PR TITLE
Fix composed inputs (dead keys) in vim emulation

### LINKED ISSUE #12522: Linux: Dead keys / US intl. does not work as expected in Vim mode
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi there, I've been experimenting with Zed and I must say I am extremely impressed at how quickly this project is growing. I'm a vim keybinds user on the US international keyboard layout and I often use the `ci"` input to change everything between double quotes. Unfortunately I cannot use this input in Zed's Vim mode, because when I type the double quotes, the whole input seems to just get ignored. The same issue exists with single quotes (`'`).

The issue exists on both X11 and Wayland.

I am not afraid to get my hands dirty so I will look around to see if I can make any improvements, but I can't promise anything.

### Environment

Zed: v1.0.0 (Zed Dev 819bb2663dbc5bb4f4f91f68fa73682e97be5b57)
OS: Linux 1.0.0
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

There don't seem to be any logs related to this issue, let me know if you need them anyway.

### PR DESCRIPTION
**Pull request by jorikvanveen**
This PR fixes actions in vim emulation such as `ci"` or `di'` on keyboard layouts where quotes require multiple keystrokes. The tests that were passing before this commit still pass, but it might be wise to do some additional testing since I jumped into this codebase an hour ago and I have no idea what I'm doing (feedback is very welcome).

Release Notes:

- Fixed #12522

### CODE REVIEW

**Comment by jorikvanveen** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@jorikvanveen I think we should probably try and fix the linux keyboard handling to more closely match the Mac behavior in this case (as this does work on macOS today - at least with a Brazilian layout - and I'm a bit concerned about special casing the accents).

Can you please let me know which keyboard layout you're using, and I'll try and test it on my local linux machine.

**Comment by jorikvanveen** [comment]
Yes, I must admit this solution is a bit hacky, though for my use case everything seems to work as far as I can tell.

I use GNOME wayland with this keyboard layout: `English (US, int., with dead keys)`

**Comment by ConradIrwin** [comment]
@jorikvanveen I think https://github.com/zed-industries/zed/pull/12871 is the right fix here. Does it work for you?

I was mistaken, as on macOS we were also triggering the find before composition had completed.

The main remaining downside is that it's not obvious that you're in composition mode in this case. I'm not sure what the best fix is, because we don't want to write the character to the buffer itself. Maybe we can use something like the Overlays from #12106 to render a fake IME input in this scenario.

**Comment by jorikvanveen** [comment]
Yes, that fixes it! Thank you!

**Comment by jorikvanveen** [comment]
Okay so I built the latest version of Zed on my desktop, and noticed the `ci"` combination didn't work. It turns out I still had my original patches active on my laptop when I made that last comment (oops). The `fi"` combination works fine, but I had to reapply the changes I made on line 192 to get `ci"` to work.

**Comment by ConradIrwin** [comment]
@jorikvanveen uh oh! 

To clarify: what exactly are the keys you're pressing, and what are you expecting to have to press?

It should be the case now that we wait until composition is over before running `f` or `t`. So if you're on a Brazilian keyboard layout where `"` puts you into compose mode, and `"a` types `ä` you can press the keys `f"a` (e.g. type `fä`) to jump to the next ä.

**Comment by jorikvanveen** [comment]
I press the following sequence: `c i ' space` on a US intl. keyboard layout. 
If I type this into a buffer in insert mode it results in `ci'`.
On my keyboard layout, when I press `'`, it puts me into compose mode and shows an underlined backtick to indicate it (<ins>\`</ins>), when I press space it inserts the actual apostrophe `'`

In standard vim, when my cursor is between two apostrophes in normal mode (i.e. in a string), this sequence removes everything between between the apostrophes and puts me into insert mode so I can easily change the contents of the string.

What happens in the latest zed without my patch is that the sequence gets cancelled when I press the `'` button

**Comment by ConradIrwin** [comment]
@jorikvanveen

**Comment by ConradIrwin** [comment]
Superseded by https://github.com/zed-industries/zed/pull/13185. I added an additional check to only run this in the case that it's likely part of an IME transaction, otherwise `c i down` no longer aborted the transaction.

**Comment by jorikvanveen** [comment]
Thank you so much! Everything is working perfectly now.

(and yes I made sure to have a clean git repo this time 😅)

**Comment by ConradIrwin** [comment]
Great. Sorry for the u-turns along the way!

**Pull request closed without merging**
