### PR TITLE
lsp:  Retrieve links to documentation for the given symbol

### LINKED ISSUE #18924: rust: add Open Documentation support
### Check for existing issues

- [X] Completed

### Describe the feature

in other editors i can select "Open Documentation" and it will open the docs.rs site for that item in the browser.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by wanlufun**
Closes #18924 

Release Notes:

- Added an `editor:OpenDocs` action to open links to documentation via rust-analyzer

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Sorry for taking this long.

I personally think it crosses the threshold of having too many custom proto messages, and we should rather use some generic proto message for anything related.

But recently I've learned that this particular one is very important for the enhanced hover messages, where we can include more docs thanks to r-a.

So, let's rebase and merge this in this form.

**Comment by wanlufun** [comment]
> Sorry for taking this long.
> 
> I personally think it crosses the threshold of having too many custom proto messages, and we should rather use some generic proto message for anything related.
> 
> But recently I've learned that this particular one is very important for the enhanced hover messages, where we can include more docs thanks to r-a.
> 
> So, let's rebase and merge this in this form.

Thank you for your feedback! I will handle the merge conflicts to facilitate the rebase and merge. I appreciate your understanding and support!
If there’s anything else, feel free to let me know.

**Comment by wanlufun** [comment]
> `cargo fmt --all` should solve this.

Alright, I have fixed the issue, and I believe it should pass the CI successfully this time. Could you please run the CI test again? Thank you!

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks!

**Pull request merged**
