### PR TITLE
Allow formatting selections via LSP

### PR DESCRIPTION
**Pull request by terziele**
Release Notes:

- Added a new `editor: format selections` action that allows formatting only the currently selected text via the primary language server.

### CODE REVIEW

**Comment by terziele** [comment]
Discussed with @ConradIrwin  here https://github.com/zed-industries/zed/pull/16823

**Comment by terziele** [comment]
It's also possible to make a range formatting with Prettier.

**Review by WeetHet — APPROVED** [review]

**Comment by mrnugget** [comment]
We landed some other changes in the meantime, can you rebase?

**Comment by terziele** [comment]
Wow, rebase made this messy. How can I fix that?

**Comment by WeetHet** [comment]
Reset onto the upstream main and cherry pick your commit

**Comment by terziele** [comment]
Thanks, it helped. :)

**Comment by mrnugget** [comment]
How do I test this out? With which language server? I tried it with rust-analyzer and it didn't work:

https://github.com/user-attachments/assets/666e2c22-1545-44e5-839d-cbf40ec5ae44

**Comment by terziele** [comment]
@mrnugget Yes, rust-analyzer supports range format only on nightly. I used C++ LSP for testing.

**Comment by WeetHet** [comment]
> @mrnugget Yes, rust-analyzer supports range format only on nightly. I used C++ LSP for testing.

Could we handle the error if range formatting is not supported and show something in the activity indicator or in a notification

**Comment by mrnugget** [comment]
> Could we handle the error if range formatting is not supported and show something in the activity indicator or in a notification

We have this, which could be used: https://github.com/zed-industries/zed/blob/fe1078ef685d4e34ea079f779c2ac0c87ca806c9/crates/activity_indicator/src/activity_indicator.rs#L344-L358

**Comment by terziele** [comment]
@WeetHet Maybe it would be better not to show the button in a mouse context menu if range formatting is not possible?

**Comment by terziele** [comment]
It seems that activity indicator was broken by `ResultExt::log_err()`, which consumes the error.

And also I can't open log from activity indicator, because log file doesn't exists. Is it possible that log file is missing because of debug build?
image

**Comment by mrnugget** [comment]
> It seems that activity indicator was broken by `ResultExt::log_err()`, which consumes the error.

Are you sure that you add the logging failure to the `last_format_failure` in the `LspStore`?

https://github.com/zed-industries/zed/blob/ec5d6e96bb304886f49680b54e58c9b0e7221cd6/crates/project/src/lsp_store.rs#L5106-L5113

**Comment by iautushka** [comment]
@mrnugget Correct me if I'm wrong, but as I understood, the provided piece of code is already processing the result of format operation.
I've removed the `log_err().flatten()` from the `LspStore`, because it `log_err()` consumes the `Result::Err` and returning the `Option<T>` instead. Because of this, the format operation never fails, and returns `Ok`, so `last_formatting_failure` is never replaced.

**Comment by mrnugget** [comment]
Alright! I tried it out locally, using `clangd` (which works), using `rust-analyzer`, using a custom formatter. I think everything works as expected.

Good stuff, thank you! I pushed some minor cosmetic changes and will merge once build is green.

**Comment by hferreiro** [comment]
It looks like https://github.com/zed-industries/zed/issues/5026 can be closed.

**Comment by iautushka** [comment]
@mrnugget Great! BTW, do we need the same formatting feature for Prettier?

**Comment by terziele** [comment]
@mrnugget Great! Do we need a prettier support here?

**Comment by mrnugget** [comment]
If it's possible, that would be neat, yep

**Comment by 4nur4g** [comment]
`editor: format selections` is formatting the whole file instead of formatting just the selection.

**Comment by mrnugget** [comment]
What language server are you using, @4nur4g?

**Comment by mrnugget** [comment]
Does that show an error message? Does it support formatting via ranges? See discussion, that includes information that not all language servers support the feature.

**Comment by 4nur4g** [comment]
@mrnugget , I don’t see any error on the UI. However, upon checking the logs, I found this:

```
2025-01-09T12:23:43.552048+05:30 [INFO] Language server with id 20 sent unhandled notification eslint/status:

{

  "uri": "file:///Users/anuragpradhan/Desktop/pb/posp_api_node/src/database/services/rmActivity/rmActivity.js",

  "state": 1,

  "validationTime": 38

}
```
  

Could you please share the reference to the discussion? I went through the current page and searched for similar issues but couldn’t find whether inline formatting is supported by the default JavaScript language server.

**Comment by mrnugget** [comment]
I meant these comments up here: https://github.com/zed-industries/zed/pull/18752#issuecomment-2404160498

I just tested this myself and seems like for TypeScript the default formatter is `prettier`. Change it to `vtsls` and it should work:

```json
{
    "languages": {
       "TypeScript": {
         "formatter": [{ "language_server": { "name": "vtsls" } }]
      }
    }
}
```

We don't have range-based formatting for Prettier.

**Comment by hferreiro** [comment]
@mrnugget there are comments related to this at https://github.com/zed-industries/zed/issues/22816#issuecomment-2579950071. I'm getting non-selected lines formatted with clangd.

https://github.com/user-attachments/assets/5161c4b6-1e37-4813-8b14-63fecfb61b53

**Comment by mrnugget** [comment]
@hferreiro are you using remoting? are you in a multi-buffer? do you use collab? I can't reproduce the issue with clang exactly like you have it. There is an issue where it would sometimes format block-wise, but that seems different.

**Comment by mrnugget** [comment]
Also, are you sure the LSP is configured as formatter?

**Comment by 4nur4g** [comment]
@mrnugget Changing formatter to `vtsls` worked.

**Comment by hferreiro** [comment]
> Also, are you sure the LSP is configured as formatter?

I had no setting. But, after adding `"formatter": "language_server"`, the result is the same.

**Comment by hferreiro** [comment]
@mrnugget I'm sorry, you're right. I had a project settings changing the formatter.

**Comment by mrnugget** [comment]
So it works correctly then when you use `clangd` as formatter?

**Comment by hferreiro** [comment]
> So it works correctly then when you use clangd as formatter?

Yes. Btw, it should be the default formatter for C++, since it's not supported by `prettier`, right?

**Comment by hferreiro** [comment]
Hey, I may have explained myself badly. What I meant is that with no config, `clangd` seemed to be used as the formatter for C++. I assumed that `"formatter: auto"` would automatically fallback to it, since `prettier` doesn't seem to support C-family languages.

**Comment by mrnugget** [comment]
> @mrnugget Hey, I may have explained myself badly. What I meant is that with no config, `clangd` seemed to be used as the formatter for C++.

Hmm, that's not what happened for me. With no config, `prettier` was used for me. So I changed the defaults so that `clangd` is used.

**Pull request merged**
