### PR TITLE
Fix desktop file

### PR DESCRIPTION
**Pull request by SpidFightFR**
Desktopfile entry 'Tryexec' breaks compatibility with the plasma desktop.

Release Notes:

- Fixed: Desktopfile, the "Tryexec" entry was set on `zed`. I also replaced `Exec=zed` by `Zed` since the actual binary generated after compilation is `/usr/bin/Zed`

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

### CODE REVIEW

**Comment by SpidFightFR** [comment]
@cla-bot check

**Comment by someone13574** [comment]
This breaks `script/bundle-linux` because the binary is renamed from `Zed` to `zed`. https://github.com/zed-industries/zed/blob/e15b902974a54bf60155a488c60ab48c25df04c8/script/bundle-linux#L61

**Comment by SpidFightFR** [comment]
> This breaks `script/bundle-linux` because the binary is renamed from `Zed` to `zed`.
> 
> https://github.com/zed-industries/zed/blob/e15b902974a54bf60155a488c60ab48c25df04c8/script/bundle-linux#L61



> This breaks `script/bundle-linux` because the binary is renamed from `Zed` to `zed`.
> 
> https://github.com/zed-industries/zed/blob/e15b902974a54bf60155a488c60ab48c25df04c8/script/bundle-linux#L61

I'm surprised to see something like that...

**Comment by someone13574** [comment]
@SpidFightFR https://github.com/void-linux/void-packages/blob/master/Manual.md#patches

**Pull request closed without merging**
