### PR TITLE
Add icon to the tabbar title 

### PR DESCRIPTION
**Pull request by fazibear**
There is a nice icon in terminal tab, but editor tab are without icons. Here is a PR to add them.

Just one question: 
A margin between an icon and text is a space character at the beginning of the label. Is this done on purpose? 

Beautiful codebase BTW ;)

Release Notes:
 - Added tabbar title icon

Screenshot 2024-07-13 at 17 08 56

### CODE REVIEW

**Comment by fazibear** [comment]
@cla-bot check

**Comment by MatinAniss** [comment]
This closed PR seems more complete, https://github.com/zed-industries/zed/pull/12443

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I'll take a closer look next week, but this approach isn't quite what we want.

**Comment by maxdeviant** [comment]
Thanks for opening this PR, but I'm going to close this in favor of https://github.com/zed-industries/zed/pull/14523.

**Pull request closed without merging**
