### PR TITLE
Add comment syntax highlighting support

### PR DESCRIPTION
**Pull request by d1y**
From zed-industries/extensions#523 & zed-industries/zed#6013

Before:

image

After:

image

~~AFAIK: The zed-industries/zed#7826 will it conflict with this?~~ Now. It only works with  JS single comment

> Refer to helix: https://github.com/helix-editor/helix/pull/2763 (See https://github.com/helix-editor/helix/pull/2650)

The label color need overridden it

> The syntax in the theme doesn't actually have these colors, is it missing here? @iamnbutler 

- hint
- info
- error
- warning

Sample configuration, add it to `settings.json` yourself:

```json
{
	"experimental.theme_overrides": {
	    "syntax": {
	      "hint": {
	        "color": "#576cdbff",
	        "font_style": "italic",
	        "font_weight": 700
	       },
	       "info": {
	         "color": "#36a165ff",
	         "font_style": "oblique",
	         "font_weight": 700
	       },
	       "error": {
	         "color": "#d73837ff",
	         "font_style": "oblique",
	         "font_weight": 700
	       },
	       "warning": {
	         "color": "#ae9414ff",
	         "font_style": "italic",
	         "font_weight": 700
	       }
	    }
	}
}
```

This PR injects some commonly used languages

- bash
- css
- dart
- go
- gomod
- gowork
- html
- javascript
- json
- lua
- python
- ruby
- rust
- toml
- typescript(tsx)
- vue
- yaml
- dockerfile

> Dockerfile extension not added: https://github.com/d1y/dockerfile.zed/blob/master/languages/dockerfile/injections.scm

Release Notes:

- Added comment syntax highlighting support

### CODE REVIEW

**Comment by d1y** [comment]
I don’t know how to fall back to the extension yet. I haven’t seen any examples of related inject syntax. I think at this time, it is more appropriate to build it into zed-core :)

**Comment by d1y** [comment]
There is a small problem, we can add a @link_uri || @link_text an underscore?

> I know that underline can now be displayed on "cmd" hover

The VScode:

image

**Comment by d1y** [comment]
I'm wondering, does this need to be injected into all languages ​​in some way, or is it injected one by one like this🤔?
@SomeoneToIgnore @maxbrunsfeld @maxdeviant 

image

**Comment by d1y** [comment]
Can we merge these two PRs first?
cc @rpfaeffle

- #7851
- #7826

**Comment by maxdeviant** [comment]
I think this is the sort of thing that should be provided by an extension.

Although I think we’ll have to work out how to have extensions provide injections for languages that aren’t in the same extension.

**Comment by maxdeviant** [comment]
Going to close this, for now. At some point we can implement it in an extension, as we build out the extension capabilities.

**Comment by inoas** [comment]
This would be lovely to have!

**Comment by Module32** [comment]
+1, would love to see this.

**Comment by g0t4** [comment]
@maxdeviant yeah extension makes sense... what features are missing in the extension APIs that are blocking doing that?

**Comment by anphir** [comment]
With [zed-industries/extensions#523](https://github.com/zed-industries/extensions/issues/523) and #11895 still being open and upvoted, I decided to put some time into this and created a comment highlighting extension ([repository](https://github.com/anphir/zed-comment)).

Meanwhile I found this PR to be closed on 2024-03-09 while #7826 was merged on 2024-03-15.
At least from my outsider's view they seem to be very similar.
I'm now a bit confused and uncertain if I should put more effort into this topic.

Even when using a language extension to provide comment highlighting, all languages with comments to be highlighted need a change to inject the comment language.
If these changes would not be made/pull request be rejected, the comment extension would become pointless.

@maxdeviant, @ConradIrwin please advise.
Many thanks!

**Comment by ConradIrwin** [comment]
I think we're still stuck with the same question as before of "how should we allow an extension to add injections to other languages".

Not sure there's an easy answer; though (maybe) we could just add it anyway, and it would do nothing if you didn't have the comment extension installed? Not sure what the downsides of that would be.

**Comment by anphir** [comment]
I created 'development extensions' of Scheme, RON, Rust and TOML to inject and test my comment highlighting extension.
After removing the comment highlighting extension, the language extensions all gracefully fell back to using their default highlighting for comments.

Based on what I have learned so far, spreading injections for one language over multiple extensions increases the risk of breakage as they might interfere with each other.

Perhaps users could be allowed to override injections?
That might be a bit more challenging than overriding settings using 'settings.json', but users could decide for themselves.

**Pull request closed without merging**
