### PR TITLE
Show branch information

### PR DESCRIPTION
**Pull request by Angelk90**
Show branch information such as, name of the user who committed last commit, date and time, and title of last commit.

Screenshot 2024-07-27 alle 16 32 13

### CODE REVIEW

**Comment by evrensen467** [comment]
could you make this an option

**Comment by maxdeviant** [comment]
Thanks for your work on this, but I think this makes the branch picker a bit too cluttered.

**Comment by evrensen467** [comment]
i'm just a bystander, sharing my opinion. i think these types of information can take place in a source control panel rather than a branch picker, or optionally show the last commit author and message as a tooltip when a certain branch has been hovered/selected for a given time, so it doesn't clog up the picker itself.

**Comment by evrensen467** [comment]
adding the commit sha next to the branch name seems like something useful

**Pull request closed without merging**
