### PR TITLE
Fix git commit popup message bracket

### LINKED ISSUE #16220: git commit popup messages strip newlines and brackets
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Raw commit messages is:
image

Get it from zed:
image

"\n", "<", ">" is gone.

### Environment

macbook

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by dovakin0007**
Closes #16220 

Coauthored @notpeter 

Release Notes:

- Fixed formatting of `<` and `>` in git commit message popup

### CODE REVIEW

**Comment by notpeter** [comment]
Tested and works as expected. Thanks @dovakin0007 and congrats on your first Zed PR!
Screenshot 2024-08-27 at 15 17 28
Screenshot 2024-08-27 at 15 18 13

**Comment by bestgopher** [comment]
image

Hi, is this case expected?

**Comment by notpeter** [comment]
> Hi, is this case expected?

Kind of? We render markdown in docstrings so `~word~` becomes ~word~. I haven't tested it (on mobile atm) but maybe use `\~` instead?

**Comment by bestgopher** [comment]
> Kind of? We render markdown in docstrings so `~word~` becomes ~word~. I haven't tested it (on mobile atm) but maybe use `\~` instead?

@notpeter I am not sure it okay. For some languages like Rust support Markdown-style comments, I don't know there are any side-effects if we replace `~` to `\~`. But for Golang, it maybe a good enhancement.

**Comment by dovakin0007** [comment]
> Tested and works as expected. Thanks @dovakin0007 and congrats on your first Zed PR!
> 
> Screenshot 2024-08-27 at 15 17 28
> 
> Screenshot 2024-08-27 at 15 18 13
> 
> 

Thank you😊

**Pull request merged**
