### PR TITLE
Add file icons for Dart, Swift, Kotlin, Java, Fonts

### PR DESCRIPTION
**Pull request by Imgkl**
Added icons for
- Dart - https://www.svgrepo.com/svg/473578/dart
- Swift - https://www.svgrepo.com/svg/512939/swift-146
- Kotlin - https://www.svgrepo.com/svg/473692/kotlin
- Java - https://www.svgrepo.com/svg/449119/java-filled
- Fonts - https://www.svgrepo.com/svg/532172/font

Extended support for
- .plist as template

Screenshot 2024-02-26 at 12 17 08 AM

Release Notes:

- Added icons for Dart, Swift, Kotlin, Java, and font files.
- Changed icon for `.plist` files.

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
These icon files are all way bigger than our other ones.

Can we size them down so they're more consistent?

**Comment by Imgkl** [comment]
@maxdeviant you mean file sizes?

**Comment by maxdeviant** [comment]
> @maxdeviant you mean file sizes?

The dimensions of the SVGs themselves are too large.

Most of our other file icons are in the neighborhood of 14x14, whereas I saw some here that are 800x800.

**Comment by Imgkl** [comment]
@maxdeviant ha. Understood. Fixing it.

**Comment by Imgkl** [comment]
@maxdeviant done.

Also added padding to the svg size to fit well with the existing icons

image

**Review by maxdeviant — APPROVED** [review]
Thanks, these look good!

**Pull request merged**
