### PR TITLE
project panel: Add indent guides

### LINKED ISSUE #12673: Indent guides for panels
### Check for existing issues

- [X] Completed

### Describe the feature

Now that we have indent guides in the editor, it makes sense that we also have them in other elements that have nested structures, such as:

- [X] project panel
- [x] outline panel
- [ ] collaboration panel
...

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by bennetbo**
See #12673

https://github.com/user-attachments/assets/94079afc-a851-4206-9c9b-4fad3542334e

TODO:
- [x] Make active indent guides work for autofolded directories
- [x] Figure out which theme colors to use
- [x] Fix horizontal scrolling
- [x] Make indent guides easier to click
- [x] Fix selected background flashing when hovering over entry/indent guide
- [x] Docs

Release Notes:

- Added indent guides to the project panel

### CODE REVIEW

**Comment by iamnbutler** [comment]
Looking great!

Here is one of the more recent project panel files:

CleanShot 2024-10-15 at 12 33 22@2x

[Figma link](https://www.figma.com/design/ZWrHLlGuUCLS7l3rsTcsoW/ZDS-%E2%80%93-Component-Working-File?node-id=1207-11781&node-type=frame&t=r82f9VRE54cbIH5H-11) (sorry non-employee folks, this may not work for you.)

Do we plan to have mouse interactions on the guides in this PR? (clicking to collapse an indent level) If so we'll need two guide colors: `indent_guide` and `indent_guide_active`.

**Comment by gabwill10** [comment]
How can I active this ?

**Comment by unnamedd** [comment]
@gabwill10 
> How can I active this ?

When released, this will be the way. Add `indent_guides` under the `project_panel` key on your `settings.json`
Just don't know when it would be landed on our computers yet.

```json
  "project_panel": {
    "git_status": true,
    "file_icons": true,
    "indent_size": 10,
    "indent_guides": true // <--------------
  },
```

**Comment by 0x2CA** [comment]
hi,thanks for your work, if the indentation guide is always displayed a bit cluttered affecting the visual, in vscode in the `onHover` option, just in the Hover time to display, if there is a corresponding option is better, I should open a new issue?

https://github.com/user-attachments/assets/2c18f3df-c545-4ff6-ab92-add952a1ae41

**Comment by tatwater** [comment]
Flagging that for those of us who have adjusted our `indent_size` the lines don't align themselves properly and collide with icons:
 
Screenshot 2024-10-30 at 4 33 40 PM

**Pull request merged**
