### PR TITLE
Improve IME input simulation

### PR DESCRIPTION
**Pull request by haruleekim**
Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@haruleekim thanks for sending this!
I'm trying to test this, and it seems like of the new comment you added, the only one that has changed behavior is 2-step Korean `g k s backspace backspace backspace`, which on current Zed leaves you with ㅎ in the buffer, but in the new world is empty. I think this is because we now reset the IME state before dispatching the backspace?

Are you expecting any other test cases to be passing now?

In #16278 we had talked about doing the entire IME simulation on keypress; but now I'm looking at the code, we also don't allow sending keystrokes during IME. Could you please remind me what bug(s) that this solves?

**Comment by ConradIrwin** [comment]
Makes sense. I'm trying to figure out how to balance all the various changes in flight re #17031.

I think if we make the change you originally proposed to send keystrokes before IME we can simplify this further.

* When a keystroke is received, we send it to the key system with the key code (and possibly also with the character it would generate without IME).
* If it is not handled by the keystroke system, then we pass it to the IME as we do today.
* On the gpui side, we then don't need `ime_events` per keystroke, but we do need the window to do IME simulation while there are pending keystrokes.

Does that make sense to you?

We should also figure out with @JunkuiZhang how we want to land all these changes. I think it would be ok to land either first and the other second; the ordering with respect to IME seems like the less risky change (it probably doesn't break very many people's shortcuts).

**Comment by ConradIrwin** [comment]
Those heuristics seem about right to me – before IME starts, all keystrokes are sent first; once you're in the middle of an IME transaction then we send keystrokes that have no modifiers to IME. That would mean that `jk` in vim mode in Korean wouldn't work in the middle of a character, but that seems like an understandable limitation?

**Comment by ConradIrwin** [comment]
Can you explain more about why we need to expose a choice to users here? I'd like to avoiding adding complexity if we can; so if we can make something work without the extra configuration it'd be better.

**Comment by ConradIrwin** [comment]
I guess it's to support `jk` mid-character during IME? 

If so, I wonder if we can change things (quite radically) so that we send events to IME *after* we queue them in the window.... Not sure if the IME relies on hidden properties of the keystrokes, but if not then we should be able to make this work (though will require some care).

**Comment by JunkuiZhang** [comment]
From the discussion above, I feel there are several things we need to address before we dive into the code. I'm somewhat confused about this PR and the `ime simulation` parts in the current `gpui` code, and I hope you can help clarify a few points:

1. Why do we need `ime simulation`? From the name, it seems related to IME handling. However, shouldn't IME-related processing be handled at the OS level? At least on Windows, IME-related inputs (like key presses) aren't even exposed to other windows. So, I believe IME handling on macOS should also be confined within `gpui/platform/macos`.
2. Why are we extracting the `IME simulation` part from the macOS implementation and moving it into gpui?

Say two examples to better explain my confusion:

**Example 1: Dead Keys**  
Consider the key sequence `= a`, using keys from a standard US keyboard layout: the key next to `backspace` and the `A` key. On a German keyboard, this sequence produces `á`. On Windows, a window receives the following events in sequence:
- `WM_KEYDOWN: VK_221`
- `WM_KEYDOWN: VK_65`
- `WM_CHAR: á`
In other words, Windows handles all dead key-related output for us.

**Example 2: IMM Input**  
Here, I'd like to first define what I mean by IMM (Input Method Manager). Please forgive my thoroughness—my background in mathematics makes me believe that clear definitions are essential for productive discussions. In this context, IMM refers to an input method that has a candidate window. For this example, I'll use Microsoft Pinyin.

Consider the key sequence `n i h a o space`, all on a standard US keyboard layout, which outputs `你好`. On Windows, this entire process is handled by the system (technically by the IMM, but for our purposes, we can consider it a system function since it's a black box to us). The window only receives the following events:
- `WM_KEYDOWN: VK_229` (repeated six times)

Yes, the window receives the same `VK_229` event six times. This means that, on Windows, key presses handled by the IMM aren't exposed to the window at all, and the only function of `VK_229` is to notify the window that the IMM is active. As a result, the idea of distributing IMM key presses, as this PR attempts, is nearly impossible on Windows. This is also why almost all software and games on Windows don't respond to key presses when an IMM is active.

Of course, not all keys are intercepted by the IMM—keys like `F1`, `ctrl-a`, and `ctrl-s` are still received by the window as usual.

**Video 1: Dead Keys**


https://github.com/user-attachments/assets/db3629aa-1279-4f97-820d-6926f821a137

**Video 2: IMM Input**


https://github.com/user-attachments/assets/5e76283f-a5e7-4e45-92f7-78616869fc96

**Comment by JunkuiZhang** [comment]
> I think the reason we have IME simulation code for macOS and Linux is to get something equivalent to Windows' virtual keys. Based on what you explained earlier, I found out that on macOS, `event.keyCode()` conceptually represents a virtual key code, but practically, it’s a scancode because the keyCode doesn’t change regardless of the input source. A bit of research shows that Linux works similarly. According to what I found, Windows is the only OS among the three that clearly distinguishes and uses scancodes and virtual keycodes separately. However, it seems that when the gpui's platform code was originally written, they wanted to support binding through logical keys like Windows' VKCodes. So, within the limited API, they implemented a way to intercept values inserted by the IME and resend them to achieve something similar to logical keys.

Thanks, that makes much sense.

**Comment by ConradIrwin** [comment]
@JunkuiZhang is there any way to get keybindings ahead of the IME? It'd be neat to support vim mode bindings while a Korean keyboard layout is active; which we can do on macOS as we can tell which key was pressed before IME gets involved. I'm also assuming if you have a modifier key down, then the key is not sent to IME?

I think we added the IME dependency on Mac as a way to get option-ç for $ working; but now I know we could solve that with charactersWithModifiers instead I think we should unwind that change and dispatch keystrokes before talking to the IME.

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang is there any way to get keybindings ahead of the IME? It'd be neat to support vim mode bindings while a Korean keyboard layout is active; which we can do on macOS as we can tell which key was pressed before IME gets involved. 

AFAIK, on Windows, no. On Windows, IMM (referring to IME with a candidate window, commonly used in East Asia) is a specialized software that intercepts keyboard input. As I mentioned earlier, when IMM is active, a typical window will only receive `VK_299` events. To support vim mode bindings, a common approach used in both `vim` and `VSCode` is the "IMM Switch." This involves actively turning off IMM when entering Vim's normal mode and turning it back on when entering edit mode.

> I'm also assuming if you have a modifier key down, then the key is not sent to IME?

`ctrl` and `alt`, true, that said, you can use shortcuts like `ctrl-q` or `alt-x` when IMM is active. `shift-[key]` is sent to IMM.

> I think we added the IME dependency on Mac as a way to get option-ç for $ working; but now I know we could solve that with charactersWithModifiers instead I think we should unwind that change and dispatch keystrokes before talking to the IME.

**Comment by ConradIrwin** [comment]
:+1: Thanks for confirming.

**Comment by ConradIrwin** [comment]
@haruleekim I'm going to close this for now, as our understanding of the problem has moved on and I want to land @JunkuiZhang's changes first so we no longer need IME to populate the KeyBinding struct.

Once those land, I'd like to explore moving to a world where we send keystrokes first (unless we have marked text and there are no modifiers)

**Pull request closed without merging**
