### PR TITLE
vim: Add smartcase search

### LINKED ISSUE #16878: Add a vim-style smart case option for search patterns
### Check for existing issues

- [X] Completed

### Describe the feature

Vim supports the 'smartcase' opton, which, when true and ignoring the casing, will temporarily go back to case sensitivity if the search pattern has upper case characters

It would be nice if this is supported in Zed as well

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by 0x2CA**
Closes #16878

Release Notes:

- Added a vim-style smart case option for search patterns

### CODE REVIEW

**Comment by 0x2CA** [comment]
@ConradIrwin 
Hi, I've implemented the intelligent smartcase function for command search and replace, as well as buffer search and submission.

However, I've now encountered a problem, which is that I need to listen to the input event of the search bar, so as to dynamically change the case options, but I don't know how to implement it, and there's also the issue of global search.

**Comment by ConradIrwin** [comment]
@0x2CA Is your idea that when you type an upper-case letter the case-sensitive option gets toggled in the search bar?

If so, it'll be tricky to do unless we build support for this feature into search itself. We could do that (apparently vs code also has a Smart Case search option). If you do that then you can listen for changes in the search bar component and toggle the mode indicator yourself.

It'll be a bit stateful because we still want to let people click on the toggle.

**Comment by 0x2CA** [comment]
> @0x2CA Is your idea that when you type an upper-case letter the case-sensitive option gets toggled in the search bar?
> 
> If so, it'll be tricky to do unless we build support for this feature into search itself. We could do that (apparently vs code also has a Smart Case search option). If you do that then you can listen for changes in the search bar component and toggle the mode indicator yourself.
> 
> It'll be a bit stateful because we still want to let people click on the toggle.

Yes, that's what I had in mind. Of course, I support the manual switching approach. I'm not a pure Vim user, so let me see if I can implement this feature in the editor itself.

**Comment by 0x2CA** [comment]
@ConradIrwin 

review

me achieved smart case in both buffer and project search, but I've found that `SearchQuery` is used extensively in many places, which may imply potential modules that should be implemented, although I think the current functionality is basically acceptable.

**Comment by ConradIrwin** [comment]
Thanks! This looks good, I changed the name of one function for clarity and merged main. Will merge when green.

**Comment by ConradIrwin** [comment]
It is merged into Zed Preview https://zed.dev/preview

**Pull request merged**
