### PR TITLE
linux: Fix backspace copying characters to primary clipboard

### LINKED ISSUE #14362: Linux delete and backspace keys copy characters to Primary clipboard
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running the nightly or normal build on Fedora 40 with X11 and when I use delete or backspace to remove characters Zed copies them to the clipboard. I use https://github.com/oae/gnome-shell-pano as my clipboard manager and I use Gpaste to sync my clipboard to the primary selection.

### Environment

```
Zed: v0.142.0 (Zed Nightly)
OS: Linux X11 fedora 40
Memory: 251.5 GiB
Architecture: x86_64
```

and

```
Zed: v0.143.6 (Zed)
OS: Linux X11 fedora 40
Memory: 251.5 GiB
Architecture: x86_64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here's a screen cap of the bug:

[Screencast_07_12_2024_02:38:16_PM.webm](https://github.com/user-attachments/assets/5b030a0b-851b-4eb2-a319-16c712b85b2d)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by apricotbucket28**
Closes https://github.com/zed-industries/zed/issues/14362

This PR moves the primary clipboard writing logic of the editor crate to mouse up, instead of `selections_did_change`. This prevents actions like `Backspace` from copying to the primary clipboard.

Selecting with the keyboard also no longer copies to the primary clipboard, but this seems to vary from program to program.

Release Notes:

- Linux: Fixed backspace copying characters to primary clipboard.

### CODE REVIEW

**Comment by joelselvaraj** [comment]
Backspace and Copying reminded me of the keybinding showing up weirdly in my linux system (fedora 40, wayland). I suppose this is a different issue. Is this a known issue or should I file a new issue. I think Cut, Copy and Paste should be Ctrl+X, Ctrl+C and Ctrl+V? 

image

**Comment by apricotbucket28** [comment]
> Backspace and Copying reminded me of the keybinding showing up weirdly in my linux system (fedora 40, wayland). I suppose this is a different issue. Is this a known issue or should I file a new issue. I think Cut, Copy and Paste should be Ctrl+X, Ctrl+C and Ctrl+V?

The keyboard shortcuts shown in the menu and the ones you mentioned are all valid for their respective actions. I agree that the shown keybindings should be Ctrl+X, Ctrl+C and Ctrl+V (since those are what all other programs show). IIRC this is because of how GPUI handles keybindings internally (insertion order is ignored). I haven't really looked at that code, so I might be wrong.

Nevertheless, that issue is different from what this PR is trying to address. You should file a new issue if one doesn't already exist.

**Comment by ConradIrwin** [comment]
@apricotbucket28 This seems like a reasonable change to me, is it still a draft for a reason?

**Comment by phisch** [comment]
@ConradIrwin The previous primary clipboard implementation was broken because deleting a character actually selects the character before the cursor, and replaces that selection with nothing. This would fix this issue, but introduces a new one where selecting text with the keyboard would not add it to the primary, only when selecting it with the mouse.

The real solution would most likely introduce some sort of intent given to the function that selects text, so that it can differentiate between something that happened due to some zed internal implementation details like deleting a character, or if it was a user action.

**Comment by ConradIrwin** [comment]
Makes sense.

I don't know if we have a way to say "user manually changed selection" yet. One idea would be to put it into the `Editor::select*` methods directly; but that won't catch edge cases like jump to definition / search result which create a selection (though maybe that's actually good?).

Another idea would be to register for the `SelectionsChanged` event from the editor - this will only be fired once per update so you won't see the intermediate selected characters in backspace - would that work?

**Comment by apricotbucket28** [comment]
Unfortunately it seems like the `SelectionsChanged` event is fired from the same that currently writes to the primary clipboard:
https://github.com/zed-industries/zed/blob/b1a581e81b6eaa951a7ca195cb0c46c335d0d5c7/crates/editor/src/editor.rs#L2288
https://github.com/zed-industries/zed/blob/b1a581e81b6eaa951a7ca195cb0c46c335d0d5c7/crates/editor/src/editor.rs#L2415

**Comment by ConradIrwin** [comment]
@apricotbucket28 Right, but it's not received by listener until after the current `cx.update` has completed (at which point backspace will have resolved).

**Comment by ConradIrwin** [comment]
@apricotbucket28 do you want to pair on this? https://calendly.com/conradirwin/pairing

**Comment by ConradIrwin** [comment]
Closing for now, but offer to pair still stands.

**Comment by apricotbucket28** [comment]
Sorry, I've been quite busy and missed your reply! I'd like to fix this but currently don't have the time. Feel free to use the code in this branch if it helps.

**Pull request closed without merging**
