### PR TITLE
WIP: Vulkan rendering backend

### PR DESCRIPTION
**Pull request by someone13574**
Status: *Very* early stage WIP, just working through the Vulkan boilerplate, but I have next week off so it should progress fairly quick. Currently there isn't much in the way of a structure, with everything just being thrown into a single function, but I will separate parts out once its up and running and a good structure becomes apparent.

This is a PR to add a Vulkan renderer to GPUI using [ash](https://github.com/ash-rs/ash), which are Vulkan bindings for Rust. This would be more similar to the Metal renderer in that it is directly using the unsafe bindings for the underlying library which allows more control over the tech stack.

Release Notes:

- Added Vulkan rendering backend to GPUI

### CODE REVIEW

**Comment by mikayla-maki** [comment]
Is there a specific problem you're having with the existing Blade renderer?

**Comment by theofficialgman** [comment]
@mikayla-maki blade requires `VK_KHR_timeline_semaphore` https://github.com/kvark/blade/issues/111#issuecomment-2065521583 while ash doesn't.

**Comment by theofficialgman** [comment]
It also requires `VK_KHR_DYNAMIC_RENDERING` which is a Vulkan 1.3 extension.

**Comment by kvark** [comment]
"VK_KHR_dynamic_rendering" is not a Vulkan 1.3 extension. It's an extension that was promoted to 1.3 core. You don't have to have Vulkan-1.3 support. Moreover, this is not even a GPU capability per se, it's just driver-level functionality. As far  I understand, it was designed with an idea in mind that all of the IHVs will update their drivers to support this (regardless of hardware). The only reason it's not supported on a machine is if it has an old driver.

"VK_KHR_timeline_semaphore" is similarly supported at the driver level - it's not a hard ware functionality. You can see all sorts of hardware in the [vulkandb](http://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_timeline_semaphore&platform=all). Just a matter of a driver update to get it.

**Comment by theofficialgman** [comment]
> "VK_KHR_dynamic_rendering" is not a Vulkan 1.3 extension. It's an extension that was promoted to 1.3 core. You don't have to have Vulkan-1.3 support. Moreover, this is not even a GPU capability per se, it's just driver-level functionality. As far I understand, it was designed with an idea in mind that all of the IHVs will update their drivers to support this (regardless of hardware). The only reason it's not supported on a machine is if it has an old driver.
> 
> "VK_KHR_timeline_semaphore" is similarly supported at the driver level - it's not a hard ware functionality. You can see all sorts of hardware in the [vulkandb](http://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_timeline_semaphore&platform=all). Just a matter of a driver update to get it.

@kvark neither the old (better driver because of less critical bugs) or the latest driver have `VK_KHR_dynamic_rendering` https://vulkan.gpuinfo.org/compare.php?reports=15757,18930#extensions

**Comment by kvark** [comment]
NVidia Tegra X1 looks like a very niche device. VulkanDB lists only 13 reports, of which 7 are on Android, 5 are on Ubuntu-18 (!!!), and one on Fedora-37. So it's not a technical limitation that NVidia didn't update the driver for them, it's probably just not in their interests to support.
For us, I'd say it's safe to put it in the bag of 2nd tier support and get OpenGL ES backend running for those.

**Comment by theofficialgman** [comment]
> NVidia Tegra X1 looks like a very niche device.

It isn't. All of [Nvidia's Jetson](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/) product (pre-Orin, so TX1, TX2, and Xavier) are subject to the same limitations. Hundreds of millions (likely billions) of such devices have sold. They run Nvidia Jetpack and are geared towards the development of embedded systems, particularly compute/AI/robotics. Having a Vulkan backend that supports for these most popular embedded systems would be beneficial. If that can be done by improving blade to not require these extensions that would be suitable.

**Comment by someone13574** [comment]
@theofficialgman Whats wrong with just using OpenGL though? I don't see why the Vulkan backend would need to be complicated when support can easily be done via OpenGL. We really just need a fallback to OpenGL built into blade.

**Comment by theofficialgman** [comment]
> @theofficialgman Whats wrong with just using OpenGL though?

nothing besides additional overhead

>We really just need a fallback to OpenGL built into blade.

once this gets added that is. right now it requires building from source in order to enable the GLES backend.

**Pull request closed without merging**
