### PR TITLE
zed: Add ability to restore last session w/ multiple windows

### PR DESCRIPTION
**Pull request by mrnugget**
This adds the ability for Zed to restore multiple windows after restarting. It's now the default behavior.

Release Notes:

- Added ability to restore all windows that were open when Zed was quit. Previously only the last used workspace was restored. This is now the default behavior. To get back the old behavior, add the following to your settings: `{"restore_on_startup": "last_workspace"}` (Part of [#4985](https://github.com/zed-industries/zed/issues/4985) and [#4683](https://github.com/zed-industries/zed/issues/4683))

Demo:

https://github.com/user-attachments/assets/57a375ec-0c6a-4724-97c4-3fea8f18bc2d

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
Hello, sorry to interrupt. These changes do not seem to work on Windows. Specifically, the position of the opened window is saved and restored, but the corresponding session is not opened.


https://github.com/user-attachments/assets/ea10b39a-a07c-46c9-9e6d-6301aeb5bcbe

And it seems that the session id is not saved.

Screenshot 2024-07-31 192816

**Comment by mrnugget** [comment]
> Hello, sorry to interrupt. These changes do not seem to work on Windows. Specifically, the position of the opened window is saved and restored, but the corresponding session is not opened.

Huh. Leaving multiple-windows aside: we've had last-workspace-restoration for quite a while now, did that never work on Windows?

If you run this in your DB on latest `main`, what do you get?

```sql
select * from kv_store where key in ('session_id', 'session_window_stack');
```

I'm also curious what this code does for you:

https://github.com/zed-industries/zed/blob/874fedd7174ce059552c8bec8221570451a0f207/crates/zed/src/main.rs#L706-L709

**Comment by JunkuiZhang** [comment]
> did that never work on Windows?

No, the video I recorded earlier was based on this commit.

> If you run this in your DB on latest `main`, what do you get?
> 
> ```sql
> select * from kv_store where key in ('session_id', 'session_window_stack');
> ```

The outputs (it says no error occured):

Screenshot 2024-08-01 031217


> I'm also curious what this code does for you:
> 
> https://github.com/zed-industries/zed/blob/874fedd7174ce059552c8bec8221570451a0f207/crates/zed/src/main.rs#L706-L709

My tests code:
```rust
let mut restore_behavior = cx
    .update(|cx| WorkspaceSettings::get(None, cx).restore_on_startup)
    .ok()?;
println!("-> Restore behavior: {:#?}", restore_behavior);
```

Output:
```rust
-> Restore behavior: LastSession
```

**Comment by JunkuiZhang** [comment]
After some testing, I discovered that the session restores correctly only when I exit Zed using `CTRL+Q`. However, when I close Zed by closing the last window, the session is not correctly restored, it reverts to `untitled`.

I suspect this difference may be due to the varying handling on macOS and Windows. On Windows, Zed automatically exits when all windows are closed. On macOS, the application only exits with `CMD+Q`. Linux follows a similar approach to Windows, so I guess the same behavior may also occur on Linux. Unfortunately, I don't have a Linux machine to verify this.

https://github.com/user-attachments/assets/3db749c0-77db-4c1b-a4f8-04beaa775989

**Comment by mrnugget** [comment]
> After some testing, I discovered that the session restores correctly only when I exit Zed using `CTRL+Q`. However, when I close Zed by closing the last window, the session is not correctly restored, it reverts to `untitled`.

Ah. That's intentional then. Yes. We only restore the session/files etc. on `cmd-q` when quitting the application.

Otherwise it would require a separate step to tell the application which windows to not restore on next start (if you manually closed it, why should we restore it?).

So sounds like it's working as intended.

**Comment by mrnugget** [comment]
> Linux follows a similar approach to Windows, so I guess the same behavior may also occur on Linux.

On Linux it works when quitting the application with `zed: quit` or `ctrl-q`.

**Comment by JunkuiZhang** [comment]
> So sounds like it's working as intended.

This behavior is quite unusual on Windows, as very few applications operate this way. On Windows, `CTRL+Q` is rarely used; almost all applications exit by closing the window ( well, they support `CTRL+Q` too. ). For example, consider how VSCode handles this:


https://github.com/user-attachments/assets/964800db-4eb0-45e6-abe7-3d60725f60f3

**Comment by mrnugget** [comment]
I guess we'll have to adjust the behavior for windows then, yeah. Right now a lot of behavior around restoration revolves around the `prepare_to_close` call on the Workspace and whether it's `quitting: true` or not.

Example: https://github.com/zed-industries/zed/blob/9b24e7d6de0455faf6eb857c89e1853faa8b47a7/crates/workspace/src/workspace.rs#L1669-L1680

On macOS, when you close a window, `quitting = false`. Same goes for Linux. And I guess same goes for Windows? Question is what happens on the last window.

But, leaving the multi-window/dirty-buffer stuff aside, I think then on Windows maybe the default should still be to restore the last workspace and not the session if we can't persist the session correctly? Or maybe last-lession (multiple windows) doesn't make a lot of sense on Windows to start with?

**Comment by JunkuiZhang** [comment]
>  Or maybe last-lession (multiple windows) doesn't make a lot of sense on Windows to start with?

The last-session feature makes sense on Windows, as VSCode also supports this and as its default behavior.

> But, leaving the multi-window/dirty-buffer stuff aside, I think then on Windows maybe the default should still be to restore the last workspace and not the session if we can't persist the session correctly?

I agree. VSCode handles it this way:
- Explicitly using `CTRL+Q` or clicking the `EXIT` button will restore the last session, which is the same as the current behavior of Zed.
- When exiting by closing the last window, VSCode will restore the last closed window and its content, as shown in the video I uploaded earlier.

**Comment by mrnugget** [comment]
> * When exiting by closing the last window, VSCode will restore the last closed window and its content, as shown in the video I uploaded earlier.

Got it. In that case, I think maybe we need to adjust the logic on Windows then. Something like this:

```diff
diff --git a/crates/workspace/src/workspace.rs b/crates/workspace/src/workspace.rs
index db12249871..3c9e7046de 100644
--- a/crates/workspace/src/workspace.rs
+++ b/crates/workspace/src/workspace.rs
@@ -1631,6 +1631,11 @@ impl Workspace {
         cx: &mut ViewContext<Self>,
     ) -> Task<Result<bool>> {
         let active_call = self.active_call().cloned();
+        let is_last_window = cx.windows().len() == 1;
+        // on windows: even if quitting is false, it's true if we're the last window to be closed
+        #[cfg(target_os = "windows")]
+        let quitting = quitting || is_last_window;
+
         let window = cx.window_handle();
 
         cx.spawn(|this, mut cx| async move {
```

But I'm VERY unsure whether that's the right fix or just a hack. Need to think about it some more.

**Comment by JunkuiZhang** [comment]
Thank you very much for taking the time to investigate this bug. I'm happy to help with testing.

**Comment by JunkuiZhang** [comment]
@mrnugget I think Linux should have the same implementation as Windows since I've seen others question this behavior as well. See #15642

**Comment by mrnugget** [comment]
@JunkuiZhang yeah, that makes sense! Also, one other thing: on Windows we'd also need to implement the `window_stack()` method on `Platform` for the whole session restoration including window-stack-order to work. Just wanted to mention it.

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang yeah, that makes sense! Also, one other thing: on Windows we'd also need to implement the `window_stack()` method on `Platform` for the whole session restoration including window-stack-order to work. Just wanted to mention it.

Understood. However, Windows does not have an API similar to `orderedWindows` on macOS, so we may need to manually sort the windows which could be quite messy.

By the way, the current builds for Windows and Linux are completely unusable; Zed panics immediately and doesn't open. I just want to confirm that Zed team is aware of this bug? See #15652

**Comment by maxdeviant** [comment]
> By the way, the current builds for Windows and Linux are completely unusable; Zed panics immediately and doesn't open. I just want to confirm that Zed team is aware of this bug? See #15652

Posting this on lots of PRs isn't going to help in getting the team's attention.

Let's keep it in the issue.

**Pull request merged**
