### PR TITLE
ruby: Add Podfile as Ruby extension language path suffix

### LINKED ISSUE #803: Syntax recognition ruby
### Check for existing issues

- [X] Completed

### Misc notes

Vscode:
Screenshot 2024-05-28 alle 20 38 47
Zed:
Screenshot 2024-05-28 alle 20 38 57

### PR DESCRIPTION
**Pull request by Moshyfawn**
Release Notes:

- N/A

Closes zed-industries/extensions#803

### CODE REVIEW

**Comment by maxdeviant** [comment]
@Moshyfawn Would you mind splitting this into two PRs: one with the change and one with the version bump?

It makes it easier to track which extensions have changed this way.

**Comment by Moshyfawn** [comment]
For sure!

**Comment by Moshyfawn** [comment]
@maxdeviant I'm going to leave this as the actual change and create a separate one for the version bump.

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
