### PR TITLE
vim: Support for q and @

### PR DESCRIPTION
**Pull request by ConradIrwin**
Fixes: #1504

Release Notes:

- vim: Support for macros (`q` and `@`) to record and replay (#1506, #4448)

### CODE REVIEW

**Comment by mrnugget** [comment]
Whoa, you did it.

**Comment by 0x2CA** [comment]
Thank you very much for your work.

If registers are not available the degrees of freedom are much less fault tolerant, if registers are used they can allow serialization of operations, modification of operations or saving of operations.

**Comment by sa1** [comment]
Can the macro feature be reused outside of vim mode?

**Comment by marcusandre** [comment]
Great. Another major step forward towards vim compatibility. Thanks, @ConradIrwin <3

**Pull request merged**
