### PR TITLE
docs: Improve documentation error for mac silicon

### PR DESCRIPTION
**Pull request by carlos-gn**
Improve documentation in case someone encounter the same issue as me when building the editor.

### CODE REVIEW

**Comment by carlos-gn** [comment]
@cla-bot check

**Comment by carlos-gn** [comment]
should i update the `.cargo/config.toml` and include it in this PR?

**Comment by maxdeviant** [comment]
> should i update the `.cargo/config.toml` and include it in this PR?

I don't think this change is necessary for the Cargo config, as most of Zed staff have been building Zed on Apple Silicon without it for a while now.

**Comment by maxdeviant** [comment]
Thank you for your PR, but I don't think we want to add this to the docs, as we are able to build Zed on Apple Silicon without the indicated change.

I suspect there might be something else that is causing that error to manifest.

**Pull request closed without merging**
