### PR TITLE
Make Vim movement to end of line configurable

### PR DESCRIPTION
**Pull request by lambdachad**
Release Notes:

- Add ability to configure Vim movement when moving to the right

### CODE REVIEW

**Comment by knarkzel** [comment]
@cla-bot check

**Comment by knarkzel** [comment]
I want to make it possible to configure normal mode and visual mode movement:

- "vim_normal_include_newline": boolean
- "vim_visual_include_newline": boolean

If it's true, it uses `clip_ignoring_line_ends`, otherwise `clip_point`. How can I do that?

**Comment by knarkzel** [comment]
Same with mouse

**Comment by SomeoneToIgnore** [comment]
There's been a need to do similar things for https://github.com/zed-industries/zed/pull/16848 and we ended up with defining fields in the actions to modify this behavior.

This is the 2nd case in out Vim support where line ends matter, so maybe we can still do a similar thing.
If there's an entire class of things to change, maybe we can consider adding it into global settings, but would be good to know first.

**Comment by knarkzel** [comment]
It's following I have noticed:
- Mouse clicking on end of line doesn't go to newline, annoying.
- Right doesn't go to newline in normal mode. In visual mode it does, so when deleting the newline is included (annoying).
- End of line doesn't go to newline in normal mode. In visual mode it does, so when deleting the newline is included (annoying)

**Comment by knarkzel** [comment]
Essentially it's something that should be configurable, like "include_newline" on per command basis. Then this can be modified for normal mode and visual mode.

**Comment by ConradIrwin** [comment]
@knarkzel I think if we want to do this we should just have a setting on the vim crate for `allow_cursor_beyond_line_end` which defaults to false. If that setting is set, we would always return `false` from https://github.com/zed-industries/zed/blob/f3b5894f3cfee74d77db893e107b7363f71a69cb/crates/vim/src/vim.rs#L573. 

That said, I am nervous about this because while I don't like the existing `clip_at_line_ends` stuff, it does replicate what vim does (and I don't want to test new features with this setting enabled, so it will likely have strange edge-cases).

Why do you want to be able to do this?

**Comment by ConradIrwin** [comment]
Closing this for now, but let me know if you're still interested in this.

**Pull request closed without merging**
