### PR TITLE
Add Prisma language support

### LINKED ISSUE #4832: Prisma support
### Check for existing issues

- [X] Completed

### Language

prisma

### Tree Sitter parser link

https://github.com/victorhqc/tree-sitter-prisma

### Language server link

https://github.com/prisma/language-tools/tree/main/packages/language-server

### Misc notes

_No response_

### PR DESCRIPTION
**Pull request by mgramigna**
Fixes #4832

Adds tree-sitter grammar and LSP adapter for Prisma

https://github.com/zed-industries/zed/assets/16297930/0f288ab1-ce5c-4e31-ad7f-6bb9655863c1

### CODE REVIEW

**Comment by mgramigna** [comment]
@cla-bot check

**Comment by mgramigna** [comment]
Update to include an LSP adapter as well

**Comment by SamHep0803** [comment]
Would you mind marking this as ready for review?

**Comment by taggon** [comment]
Love to see this in the next version! 👍

**Comment by ndneighbor** [comment]
Fantastic, would love to see this in the next version!

**Comment by maxbrunsfeld** [comment]
Nice work @mgramigna Thanks for the PR! 

Just a heads up - we are very soon going to be moving most of Zed's built-in languages into installable extensions (https://github.com/zed-industries/zed/issues/7096). Once the extension system lands, we will probably remove this code and put it into a new `prisma` repository under the new [zed-extensions](https://github.com/orgs/zed-extensions/repositories) GitHub org. We'll probably add you as a collaborator on that repo when we do it, if you're interested in helping maintain it.

**Comment by mgramigna** [comment]
> Nice work @mgramigna Thanks for the PR!
> 
> Just a heads up - we are very soon going to be moving most of Zed's built-in languages into installable extensions (#7096). Once the extension system lands, we will probably remove this code and put it into a new `prisma` repository under the new [zed-extensions](https://github.com/orgs/zed-extensions/repositories) GitHub org. We'll probably add you as a collaborator on that repo when we do it, if you're interested in helping maintain it.

@maxbrunsfeld Thanks! Feel free to add me as a collaborator. Happy to help when I can :)

**Pull request merged**
