### PR TITLE
linux: Fix word backspace/delete shortcuts

### PR DESCRIPTION
**Pull request by ComputerDruid**
Matching the changes in #9673, ctrl is the word-at-a-time modifier for backspace and delete, too. Alt-backspace and Alt-delete should do nothing based on some quick testing I did in firefox and kwrite.

Release Notes:

- N/A

### CODE REVIEW

**Comment by ComputerDruid** [comment]
'@cla-bot check

**Comment by jansol** [comment]
Does this overlap with #9829?

**Comment by ComputerDruid** [comment]
Yes, it looks like #9829 already contains all the changes I made here. That one's marked as a draft, so I'm not sure if it's worth merging this in the meantime or just waiting.

**Comment by mikayla-maki** [comment]
Thanks for the PR @ComputerDruid but mine should be merged today :)

**Pull request closed without merging**
