### PR TITLE
gpui: Fix window title special characters display on X11

### PR DESCRIPTION
**Pull request by maxime-forveille**
Before:
image

After:
image

Release Notes:

- Fixed window title special characters display on X11.

### CODE REVIEW

**Comment by maxime-forveille** [comment]
@cla-bot check

**Comment by mikayla-maki** [comment]
Thanks for fixing my botched merge :)

**Comment by maxime-forveille** [comment]
I cant run the app anymore because of a panic on fullscreen
In the new of the X11WindowState there is also a windows title set if there is a toolbar. I dont know if we should duplicate as well here.

**Comment by maxime-forveille** [comment]
In the `new` of `X11WindowState` there is also this piece of code:

``` rust
if let Some(titlebar) = params.titlebar {
            if let Some(title) = titlebar.title {
                xcb_connection
                    .change_property8(
                        xproto::PropMode::REPLACE,
                        x_window,
                        xproto::AtomEnum::WM_NAME,
                        xproto::AtomEnum::STRING,
                        title.as_bytes(),
                    )
                    .unwrap();
            }
        }
```

I don't know if we should duplicate also the code I added in `set_title` function.

**Pull request merged**
