### PR TITLE
windows: Fix the app frozen after window minimize and maximize

### LINKED ISSUE #21688: On windows, the app crashes when I minimize it
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

If I just switch to another application, then when I return to zed, it continues to function, but if I minimize it and expand it, it stops responding to any actions other than the window control buttons.
If I expand it to full screen (using the window control button at the top of the zed window), it will start functioning again.
If i collapse it again, everything will repeat itself.

### Environment

Windows 11 24H2   
AMD Ryzen 2700 Eight-Core (x64)
16gb ram
I have compiled zed from the source code   
I have not installed any plugins on it

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>
```
[Zed.log](https://github.com/user-attachments/files/18049222/Zed.log)
```
</details>

### PR DESCRIPTION
**Pull request by feeiyu**
Closes #21688

Release Notes:

- fix the app frozen after window minimize and maximize

freeze1208

### CODE REVIEW

**Comment by dovakin0007** [comment]
Can we use ```IsIconic()```?

**Comment by mgsloan** [comment]
Seems reasonable, thank you!

I will defer to someone else for merge - I'm curious if it's desired for the renderer to get resized to `(0, 0)`?  Perhaps @kvark knows?

If undesired then an alternative might be to wait for the next non-minimize resize, and then do `self.gpu.resize(...)` despite the size not differing [here](https://github.com/zed-industries/zed/blob/c5b6d78d5b01e0fcd243499bf3fb09cb1c758902/crates/gpui/src/platform/blade/blade_renderer.rs#L440-L444).

**Review by kvark — COMMENTED** [review]
From the renderer perspective, the ideal app behavior on minimize is: don't do anything with rendering. I.e. don't try to resize the swapchain to (0,0), don't try to render anything, nothing. Resume operation once the window size is meaningful again.

**Comment by mgsloan** [comment]
Thank you for working on this!  Merged alternative fix #21756

**Pull request closed without merging**
