### PR TITLE
Add Scala support via Metals (Scala LSP)

### PR DESCRIPTION
**Pull request by hmemcpy**
The Scala language support!
This uses the official [Metals](https://scalameta.org/metals/) LSP server.

(this is still WIP because I need to download the LSP binary, and make sure all the brackets are correctly highlighted/inserted)

image

### CODE REVIEW

**Comment by hmemcpy** [comment]
@cla-bot check

**Comment by hmemcpy** [comment]
Ah, looks like there's another PR coming soon with those features implemented. So I'm closing this!

**Comment by bishabosha** [comment]
On my side it really seems like Zed is not receiving LSP requests from the client, only notifications (doing a lot of print debugging)

**Comment by mprihoda** [comment]
@bishabosha I figured out the problem with the LSP communication - the code in lsp.rs expects int as request's id, but the spec allows int or string and Metals uses strings.

I made a quick and dirty effort to implement it, successfully, Metals seems to be correctly building and reporting errors now, but my Rust knowledge is basically none, so I'd need someone to take a look at it.

The code is in my fork, if anyone would be willing to take a look:

https://github.com/mprihoda/zed/tree/wip/zed-scala

Not ready for a pull request yet.

**Comment by bishabosha** [comment]
Nice, super glad you found that! perhaps we can all collab on one fork?

**Comment by mprihoda** [comment]
I just made https://github.com/zed-industries/zed/pull/7568 to gather feedback.

And sure, pooling our efforts into one fork might make things faster.

**Pull request closed without merging**
