### PR TITLE
Add rename to JetBrains keymaps

### LINKED ISSUE #7261: Missing rename keybinding in JetBrains binding
### Check for existing issues

- [X] Completed

### Describe the feature

I noticed that `rename` feature is missing when using `JetBrains` keybinding. Perhaps it's because it's missing from https://github.com/zed-industries/zed/blob/b35a722/assets/keymaps/jetbrains.json ?

It works fine after I added these lines:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "shift-f6": "editor::Rename"
    }
  },
  {
    "context": "ProjectPanel",
    "bindings": {
      "shift-f6": "project_panel::Rename"
    }
  }
]
```

If it's ok, I'd make a PR for this.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by litsynp**
Add rename to JetBrains keymaps.

Closes #7261.

Release Notes:

- Fixed ([#7261](https://github.com/zed-industries/zed/issues/7261)).

### CODE REVIEW

**Comment by litsynp** [comment]
@cla-bot check

**Comment by litsynp** [comment]
@cla-bot check

**Comment by JosephTLyons** [comment]
Hey @litsynp, did you sign the CLA? Just seeing if there is an issue on our end with it not going through.

**Review by SomeoneToIgnore — APPROVED** [review]
CLA reports as signed.

Thank you!

**Comment by litsynp** [comment]
@JosephTLyons Nope, I didn't read the instructions. Anyways, thanks for checking!

**Pull request merged**
