### PR TITLE
Pass temperature to Anthropic

### PR DESCRIPTION
**Pull request by maan2003**
Release Notes:

- N/A

### CODE REVIEW

**Comment by maan2003** [comment]
btw why is zed using temperature 0.5 for inline assistant and 1 for chat instead usually recommend 0 for programming related usecases?

**Comment by maan2003** [comment]
@maxdeviant 
https://github.com/zed-industries/zed/pull/17509/commits/56a5104a8b1c06f3812dfc0db931c1c9482007d4: is 1.0 empirically determined? or just to preserve old behavior (anthropic api defaults to 1.0 temperature)

**Comment by maxdeviant** [comment]
> @maxdeviant [56a5104](https://github.com/zed-industries/zed/commit/56a5104a8b1c06f3812dfc0db931c1c9482007d4): is 1.0 empirically determined? or just to preserve old behavior (anthropic api defaults to 1.0 temperature)

We've been using a temperature of 1.0 (since it's the default), so we want to stick with that since it seems okay.

We haven't really done any sort of evaluation of different temps, but may do so in the future and reevaluate. Right now we just want to keep things consistent.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
