### PR TITLE
gpui: Prefer integrated GPUs on Intel Mac

### LINKED ISSUE #5124: Discrete GPU activated on launch
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After launching Zed on an 16" Intel MacBook Pro the fans immediately started spinning up and the laptop became warm. Checking in Activity Monitor showed that this is because it activated the discrete AMD GPU:

Screenshot 2022-11-17 at 02 51 31

This won't be relevant for Apple Silicon systems, of course, but it has a major impact on thermals and battery life on Intel laptops, which I think is undesirable for a code editor. I understand that the discrete GPU might allow for better performance, but it shouldn't be required (and I can't imagine it makes enough of a difference in this use case to be worth the cost).

(Apologies if this has already been reported; I did a couple quick searches and couldn't find anything.)

### Expected behavior

Zed should not activate the discrete GPU, or at least it should be possible to disable that behaviour with a setting.

### Environment

Zed 0.64.0 – /Applications/Zed.app
macOS 13.0.1
architecture x86_64

(By the way, `echo "\n"` doesn't do what you might expect, on macOS at least (the behaviour of `echo` is [notoriously unportable](https://www.etalabs.net/sh_tricks.html)); I had to edit the output manually. I suggest using `printf '%s\nmacOS %s\narchitecture %s\n' "$(zed --version)" "$(sw_vers -productVersion)" "$(uname -m)"` in the template instead.)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

_No response_

### PR DESCRIPTION
**Pull request by emilazy**
On Intel, Metal will pick a discrete GPU by default when available, resulting in higher power consumption and heat output. Prefer non‐removable low‐power devices to correct this.

On Apple Silicon, there is only ever one GPU, so there is no functional change.

I didn’t do intensive benchmarking of this or anything, but Zed still seems responsive and it stops my MacBook Pro acting as a combination space heater–jet engine.

Thanks to @denlukia for showing that this is easy to fix; I’ve marked you as a co‐author, I hope that’s okay.

Closes: #5124

Release Notes:

- Improved power consumption on Intel Macs by preferring integrated GPUs over the discrete GPUs. ([#5124](https://github.com/zed-industries/zed/issues/5124)).

### CODE REVIEW

**Comment by emilazy** [comment]
@cla-bot check

Although I have marked @denlukia as a co‐author, my implementation is distinct from the one in https://github.com/zed-industries/zed/issues/5124#issuecomment-2041419944 in every way except for taking the inspiration to check the `.is_removable()` and `.is_low_power()` properties. I believe that is not copyrightable (indeed, I doubt my entire contribution here is copyrightable) and there should therefore be no need for @denlukia to sign the CLA, but if there are any concerns about my `Co-authored-by:` trailer in light of the CLA requirement I can remove it.

**Comment by mrnugget** [comment]
> On Intel, Metal will pick a discrete GPU by default when available, resulting in higher power consumption and heat output. Prefer non‐removable low‐power devices to correct this.

I'm wondering: what are the tradeoffs here? What are we missing by switching to the integrated GPUs?

> I didn’t do intensive benchmarking of this or anything, but Zed still seems responsive and it stops my MacBook Pro acting as a combination space heater–jet engine.

Can you run Zed with the [Metal HUD](https://developer.apple.com/documentation/xcode/monitoring-your-metal-apps-graphics-performance) enabled and also `ZED_MEASUREMENTS=1` to compare performance?

Ideally you record the output of `ZED_MEASUREMENTS=1` before and after. Good benchmarks to run:

1.  Open `editor.rs` in this repo and just scroll through it
2. Open multiple files and hold down the tab-switch key combination pressed (by default `cmd-{` on macOS) so Zed goes as fast as it can through the open tabs.

With before/after output stored in `before.txt` and `after.txt` you can run `./script/histogram before.txt after.txt`.

**Comment by Peiffap** [comment]
Wouldn't it be better to add the option for users to choose which GPU they want to use?

**Comment by emilazy** [comment]
An option would be a better compromise than the status quo, but I doubt it’s necessary or really desirable. The entire macOS desktop is accelerated just fine by your integrated GPU, and on Linux systems with multiple GPUs Zed will be rendering entirely on the integrated GPU unless users go out of their way to override that. It’s just a Metal default that is inappropriate for a code editor rather than a game or high‐end graphics software, and if the code to prefer the integrated GPU had been used from the get‐go I doubt anybody would be interested in adding an option for it today.

I’m still planning to do the measurements here to back my opinion up with concrete data, but I had my entire day taken up by dealing with the fallout of the OpenSSH CVE so it’ll hopefully be within the next few days instead.

**Comment by mrnugget** [comment]
@emilazy thanks! I agree with you, I just want to avoid us walking into a regression that we could've avoided. At the very least, I want to see what tradeoffs we're making before we make them (except for the "I can't hear anything anymore because the fans are on", which is understandable)

**Comment by emilazy** [comment]
Don’t get me wrong, I’m in favour of measurements! I got around to taking some. My workflow:

* `cargo build --release` before and after the change
* LSP support turned off to not interfere with measurements
* `MTL_HUD_ENABLED=1 ZED_MEASUREMENTS=1 …/zed crates/editor/src/editor.rs 2>…`
 and scroll around
* `MTL_HUD_ENABLED=1 ZED_MEASUREMENTS=1 …/zed (fd . -e rs | head -n 100) 2>…` and hold down <kbd>⌘</kbd> <kbd>}</kbd>
* Eyeball the HUD stats and run the histogram script on the measurements

I was on AC power for this and closed stuff before taking measurements but I wasn’t super rigorous; if you have any other suggestions for the methodology I can try them. I could also try `MTL_HUD_LOG_ENABLED=1` if the data would be useful.

Overall the results seemed very similar. The `editor.rs` test was an even 60 FPS on both, and both struggled with flipping rapidly through 100 tabs, stabilizing on FPSes around the 30–49 range. Both versions started out with a ridiculously high FPS on the HUD before coming down to 60-ish at idle, though this seemed kind of weirder on the tons of tabs test. I felt like the UI scrolling latency for the `editor.rs` test might have been a bit better on the discrete GPU, which the histograms seem like they might bear out (although the two segments are such similar shape and so completely disconnected that I wonder if there could be some weird timing measurement artefact going on here instead?), but I couldn’t tell if I was just imagining it or not. Let me know what you think and if there’s any other tests you’d like me to run.

Histogram for the editor.rs rest

Histogram for the tabs test

**Comment by mrnugget** [comment]
Thanks! Yeah, that seems weird, that they are this disconnected but then completely overlap in the other test. Can you maybe redo the scrolling test? You can also turn the metal HUD off, I think. It just feels like a weird testing artifact. It could also be the GPU working differently, but that wouldn't explain why they overlap in the second test.

**Comment by emilazy** [comment]
I got more normal results this time around with the HUD off; not sure what happened last time.

Histogram for the editor.rs test, again

So it does seem like there’s some degree of latency regression, although frame timings are more consistent now.

I double‐checked the raw measurements and they seem as expected; before:
```
…
frame duration: 7.011298ms
frame duration: 5.112829ms
frame duration: 5.304018ms
frame duration: 6.486004ms
frame duration: 8.252996ms
frame duration: 5.675147ms
frame duration: 5.130771ms
frame duration: 6.486652ms
frame duration: 5.860242ms
frame duration: 7.114259ms
frame duration: 5.638865ms
frame duration: 4.371119ms
frame duration: 5.188531ms
frame duration: 3.980462ms
frame duration: 4.334939ms
…
```

After:

```
…
frame duration: 8.41194ms
frame duration: 8.377034ms
frame duration: 9.406778ms
frame duration: 9.509476ms
frame duration: 8.308788ms
frame duration: 8.968947ms
frame duration: 8.522735ms
frame duration: 8.81079ms
frame duration: 9.418823ms
frame duration: 8.738202ms
frame duration: 9.741731ms
frame duration: 8.817128ms
frame duration: 9.00957ms
frame duration: 9.252705ms
frame duration: 8.869699ms
…
```

The greater consistency of the results after the change makes me wonder if this might be more to do with some frame pacing thing rather than raw GPU firepower. Does Zed do anything fancy to try and race VSync? Anyway, let me know what you think. The after numbers match the kind of thing Intel MacBook Air users (and possibly users of Intel integrated graphics on Linux) should be seeing currently anyway, so if there’s significant latency improvements to be made they’d benefit other users too.

**Comment by emilazy** [comment]
Yeah, it’s the internal 3072×1920 @ 60 Hz display of a MacBookPro16,1 with the Radeon Pro 5500M and 2.3 GHz i9-9880H (Intel UHD Graphics 630) options. Fancier displays only happened in the Apple Silicon era (though of course people can always plug in a monitor with a higher refresh rate).

**Comment by mrnugget** [comment]
Alright, then I'd say let's go with this and if something goes wrong, we can revert.

**Comment by emilazy** [comment]
Thank you! I’m glad to finally be able to give Zed a proper go.

**Pull request merged**
