### PR TITLE
tab_switcher: Add file and project search icons

### PR DESCRIPTION
**Pull request by Daste745**
I found tab switcher file icons to be missing. They were mentioned in the [initial tab switcher issue](https://github.com/zed-industries/zed/issues/7653), but left to be added later (mentioned in https://github.com/zed-industries/zed/pull/7987).

I also noticed that the project search icon went missing, but I'm not sure if that's intentional. These changes re-introduce it, as it's provided by the generic `tab_icon()` function.

There's a small difference between the terminal item and everything else, because terminal's `tab_content` returns a slightly different layout, which adds a little more space between the icon and text. I'll look into resolving this withouth changing too much stuff around in the terminal crate. If you have any ideas on how to do this well, please comment.

The new `tab_switcher` config section only has a single boolean option - `show_icons`. It toggles between icons and not icons, but doesn't disable the terminal icon. Implementing this would probably also require some refactoring in terminal's `tab_content` function.

Release Notes:

- Added file icons to the tab switcher

Screenshot:
image

### CODE REVIEW

**Comment by osiewicz** [comment]
> Maybe a green/gray check icon could be rendered in the place of the warning/error icon to keep the display consistent?

Yeah, that makes sense.

> The diagnostics panel and terminal view's icons are controlled internally. Is this a problem for us? It's inconsistent with the show_icons setting, but I'm not sure if that's not too big of a scope right now.

I guess it is problematic in that it introduces inconsistency; I'd honestly just not have any setting for it whatsoever and always show the result of `tab_content` in tab switcher.

**Comment by Daste745** [comment]
I added a green checkmark to the diagnostics tab when there are no problems:
image

> I'd honestly just not have any setting for it whatsoever and always show the result of tab_content in tab switcher.

Yeah, I aggree. It's such a small thing that it doesn't need to be a setting. I reverted the commit which introduced the setting.

**Comment by iamnbutler** [comment]
Hey @Daste745, this looks good to me. 🚢 it!

**Comment by Daste745** [comment]
Resolved all merge conflicts with `main`. This branch should be good to merge!

**Comment by osiewicz** [comment]
Thanks!

**Comment by EthanG45** [comment]
Does this work? I see it in the release notes for preview 0.154.0, but it doesn't show up in the tab switcher for me.

**Comment by Daste745** [comment]
@EthanG45 It's displaying icons for me 🤔. Testing on v0.154.0-pre on MacOS. I developed this on linux x86 and it also worked fine.
image

**Comment by notpeter** [comment]
This requires the following to be added to your settings:
```
  "tabs": {
    "file_icons": true
  }
```

I've updated the changelog to reflect this.

**Comment by nilskch** [comment]
Hey @Daste745, this is super nice, thank you a lot! With the following settings:
```json
"tabs": {
    "file_icons": true,
    "git_status": true
}
```
the new Icon is not in the same color as the label (Git modified or added). Should we change that?

**Comment by Daste745** [comment]
Hi @nilskch, thanks for pointing this out. I missed this case, because `tab_icon()` doesn't automatically add git-aware coloring, but `tab_content()` does.

I'll add a fix for this and open a new PR.

**Pull request merged**
