### PR TITLE
Add syntax highlighting and LSP for Dockerfiles(#6905)

### PR DESCRIPTION
**Pull request by d1y**
Release Notes:

- Added Dockerfile syntax highlighting and LSP support

### CODE REVIEW

**Comment by d1y** [comment]
In https://github.com/zed-industries/zed/pull/6905, I can't wait, I need this so much

**Comment by d1y** [comment]
I think when the plugin system is truly perfected, it can be downgraded to the plugin level, but before that, I need it 🤒

**Comment by SomeoneToIgnore** [comment]
I see that people actually submit extensions already, here's one for Java, for example: https://github.com/zed-industries/extensions/pull/57

Would it make sense to transfer it there?

**Comment by d1y** [comment]
> I see that people actually submit extensions already, here's one for Java, for example: [zed-industries/extensions#57](https://github.com/zed-industries/extensions/pull/57)
> 
> Would it make sense to transfer it there?

The current plug-in system is not perfect enough, lsp-server does not support it yet (I am not sure, at least I have not seen anything that does this, and embeds a binary (re-exec)

**Review by SomeoneToIgnore — APPROVED** [review]
Ok, re-checked on extensions (and noticed no LSP support yet) and this PR (seems good, and LSP actually doing navigation & formatting, so sort of useful).

Let's get that in, thank you for the pushing it over the last mile.

**Pull request merged**
