### PR TITLE
Add support for labelDetails in the completion popup

### PR DESCRIPTION
**Pull request by ryuukk**
Release Notes:

- Added support for LSP's labelDetails in the completion popup

Before:

image

After:

image

Questions:

- Is this the right way to layout the completion popup?
- What about themes? I'm not familiar with this code base, and I don't know rust, so i'll perhaps leave that task for someone else

### CODE REVIEW

**Comment by osiewicz** [comment]
We already make use of `labelDetails`; each language from `crates/languages` has it's own formatter in `fn label_for_completion` and at the very least VTSLS and RA use that field when formatting.

**Comment by maxdeviant** [comment]
> We already make use of `labelDetails`; each language from `crates/languages` has it's own formatter in `fn label_for_completion` and at the very least VTSLS and RA use that field when formatting. If there's a language that doesn't use this field yet, I'd suggest changing it directly (although admittedly you may have limited options when it comes to styling when compared to this PR)

This is correct, in Zed we use `label_for_completion` to synthesize the information from the language server into a completion label.

This allows us to perform syntax highlighting to make the completion look good.

We don’t want to show the details from the language server as-is.

**Comment by someone13574** [comment]
Could `labelDetails` be used as a fallback for when no `label_for_completion` is provided? It would be a shame if an lsp provided them but instead nothing was shown because the extension didn't implement the `label_for_completion` function.

**Comment by someone13574** [comment]
> Having to have a plugin already hinders the ability to use zed as a drop in replacement, wich is bad marketing wise IMO

Strongly disagree with this. I don't need, nor want, support for every language by default. That ultimately results in a larger and slower editor, the exact thing Zed markets itself contrary to. The plugin system allows Zed to stay smaller while still allowing support for things not everybody needs and IMO is the best solution to the problem. I fail to see how having a plugin system (which vscode also has) is a downside.

**Comment by someone13574** [comment]
> if you feel courageous, please submit a PR

I'd like to hear what @maxdeviant has to say to using the lsp's `labelDetails` as a fallback before I waste any time.

**Comment by maxdeviant** [comment]
> > if you feel courageous, please submit a PR
> 
> I'd like to hear what @maxdeviant has to say to using the lsp's `labelDetails` as a fallback before I waste any time.

The intent is for language extensions to define `label_for_completion` in order to process the labels coming back from the language server.

This allows for customizing the completion labels (e.g., with syntax highlighting) to provide a better UX.

So if a language server does have additional information and a language extension does not use `label_for_completion` to process it and build rich completions, I would consider that a deficiency in the extension that should be remedied by the extension author.

**Pull request closed without merging**
