### PR TITLE
Apply `terminal.foreground` and `terminal.background` from theme

### PR DESCRIPTION
**Pull request by zakj**
Release Notes:

- Fixed terminal colors not respecting the theme ([#11418](https://github.com/zed-industries/zed/discussions/11418)).

### CODE REVIEW

**Comment by zakj** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you.
Fo;llowing the same logic, can we also use 
`background_color: Some(theme.colors().terminal_background),` a few lines above?

**Comment by zakj** [comment]
@SomeoneToIgnore Good catch, thanks! I also noticed one another required change.

**Review by SomeoneToIgnore — APPROVED** [review]
Looks about right, thank you for spitting this!

**Pull request merged**
