### PR TITLE
assistant: Remove timeout in HttpClient to allow slow local LLMs

### LINKED ISSUE #9913: Assistant Timeout
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With the Zed Assistant, I like using a local LLM with a relatively large context size. This can sometimes make response times quite slow. Since updating to 0.128.3, I have been receiving a timeout message if it doesn't receive a response quickly enough: "Request or operations took longer than the configured timeout time." Is there a way to configure the timeout time to be longer?

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-03-28 at 12 19 30

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-03-28T12:12:11+00:00 [WARN] request completed with error: request or operation took longer than the configured timeout time

### PR DESCRIPTION
**Pull request by craigcomstock**
I am using ollama with mistral model.

my local settings.json:

```
{
  "theme": "One Dark",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "assistant": {
    "version": "1",
    "provider": {
      "name": "openai",
      "api_url": "http://localhost:11434/v1"
    }
  }
}
```

Release Notes:

- Fixed #9913

### CODE REVIEW

**Comment by craigcomstock** [comment]
This is a draft because I have just HACKED the timeout to not exist for all HttpClient requests. Obviously not the right answer but it does solve the assistant problem for me. I will work on refining the fix.

**Comment by craigcomstock** [comment]
I will read the CLA and work on a proper fix. Wanted to get this out to the issue mostly so that others could have the "fix" even if it is a hack. :)

**Comment by rgbkrk** [comment]
What might need to be done in the assistant completion provider is to invoke the builder for the HTTPClient directly and set the timeout at that point.

**Comment by maxdeviant** [comment]
> What might need to be done in the assistant completion provider is to invoke the builder for the HTTPClient directly and set the timeout at that point.

We should probably have a way of constructing an `HttpClient` with a given timeout without having to break out of our abstraction.

**Comment by craigcomstock** [comment]
closing this as I don't have time to finish and after digging through the code a bit I didn't see an "easy" fix as a new-comer to both rust and this code base. :)

Someone else has mentioned they can work on it: https://github.com/zed-industries/zed/issues/9913#issuecomment-2055042891

**Comment by rgbkrk** [comment]
Thanks for the contribution Craig. I'll keep it in mind as we build out more AI features. I really like the use of local models. The Zed team is focused on making sure the happy path involves external models (so it's easy for people to get going). I'd like to carve out space for open models as we find ways to introduce them though.

**Pull request closed without merging**
