### PR TITLE
gpui: Decouple X11 logic from LinuxPlatform

### PR DESCRIPTION
**Pull request by witelokk**
Release Notes:

- Separated Linux platform and X11-specific code, so that we can add Wayland support now.

### CODE REVIEW

**Comment by antaz** [comment]
This is very important. It would help to use crate feature flags such as `x11` and `wayland` to conditionally compile against the appropriate Linux platform and default to `wayland`

**Comment by gabydd** [comment]
This is great to see, in terms of compiling against Wayland or x11 we probably want to do something like winit where you compile against both and then check at runtime which one to use: https://github.com/rust-windowing/winit/blob/8936fe1acda1c4918ce57a23cbc12715a1bf05fa/src/platform_impl/linux/mod.rs#L750

**Comment by antaz** [comment]
> This is great to see, in terms of compiling against Wayland or x11 we probably want to do something like winit where you compile against both by default on Linux and then check at runtime which one to use: https://github.com/rust-windowing/winit/blob/8936fe1acda1c4918ce57a23cbc12715a1bf05fa/src/platform_impl/linux/mod.rs#L750

`winit` compiles platform specific code conditionally, saves some compile time.
It's also a good idea to default to wayland instead like winit does, since X11 can run inside wayland

**Comment by mikayla-maki** [comment]
I'd agree with @gabydd's comment, we want to compile both and then pick which one to use at runtime.

**Review by kvark — APPROVED** [review]
This isn't blocking us from doing run-time selection of windowing backend, does it? Looks reasonable.

**Review by mikayla-maki — APPROVED** [review]
Thank you!

**Pull request merged**
