### PR TITLE
gpui: Make SVGs render at the correct size

### PR DESCRIPTION
**Pull request by MatthiasGrandl**
in #9931 @mikayla-maki removed some code that already achieved this, but in a very memory-leaky fashion. This one now only keeps a single rasterized SVG size per element. To achieve this I made the asset_loading abortable and reintroduced the RasterOrVector Asset.

Before:
image

After:
image

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Passing by and wanted to thank you for the SVG rendering in Zed, now I can browse its icons from within!

Yet, this PR seem to break this capability away, when I use this branch to open e.g. `assets/icons/file_icons/quote.svg`, I get

`1Thread "<unnamed>" panicked with "called `Option::unwrap()` on a `None` value" at crates/gpui/src/svg_renderer.rs:69:10`

**Comment by MatthiasGrandl** [comment]
@SomeoneToIgnore that's interesting, thanks for reporting! This specific `unwrap` wasn't newly added in this PR, but I think I understand what causes it. I'll try to push an update soon, would appreciate if you could give it another test :)

**Comment by MatthiasGrandl** [comment]
@SomeoneToIgnore PS: can you share the SVG you are trying to display? That would help to confirm my theory.

**Comment by SomeoneToIgnore** [comment]
Sorry, did not indicate it clear enough: `assets/icons/file_icons/quote.svg` is a path inside this repository, Zed comes with a bunch of bundled SVGs: https://github.com/zed-industries/zed/tree/main/assets/icons

**Comment by MatthiasGrandl** [comment]
Ah ok, I got it. The image-viewers `img` element has no specified size as it wants to render images at their inherent size. Since this PR always tries to render the SVG at the size of the `img` element this turns out to be zero. So I need to add a fallback to render SVGs at their native size, if the element bounds are zero.

**Comment by MatthiasGrandl** [comment]
@SomeoneToIgnore you can try again, I think this should be fixed.

**Comment by SomeoneToIgnore** [comment]
@MatthiasGrandl did it work for you when you tested it on Zed assets?

For me, nothing is shown at all now:
image

compared to weirdly positioned, but working still in the current `main`:
image

**Comment by MatthiasGrandl** [comment]
> did it work for you when you tested it on Zed assets?

nope I did not build zed for testing. I have a minimal GPUI app for testing. I am not sure why it wouldn’t work with the changes. It should behave the same as before for `img` elements without a specified size.

**Comment by MatthiasGrandl** [comment]
Turns out this is a second issue, since we don’t have an image ready in the before_layout now. I think I know how to fix this though.

**Comment by MatthiasGrandl** [comment]
@SomeoneToIgnore now it should work.

**Comment by SomeoneToIgnore** [comment]
Thank you for looking into that.
I've started clicking through them and a few worked, but very soon (e.g. `ai.svg`), it started panicking with something else:
```
Thread "<unnamed>" panicked with "Zero size pixmap" at crates/gpui/src/svg_renderer.rs:61:10
```

**Comment by MatthiasGrandl** [comment]
pushed a change to remove this panic, but I am not sure why it happens. I can render this specific icon just fine, but I am now building Zed to test it directly in the image viewer.

**Comment by MatthiasGrandl** [comment]
image

now it seems to work.

**Comment by SomeoneToIgnore** [comment]
Beautiful! I was able to click through all icons without a crash this time, thank you.

I'll leave the code review to @mikayla-maki as the one with the deletion context mentioned in the PR's original message.

**Comment by furkanmustafa** [comment]
> So I need to add a fallback to render SVGs at their native size, if the element bounds are zero.

I hope a malicious SVG with 40000000x40000000 size wouldn't be a problem? Should there be a limit? scale down to viewport size by default and such, if no size given?
(Maybe not a concern of this PR though)

**Comment by MatthiasGrandl** [comment]
@furkanmustafa I think a malicious raster image would likewise already be a problem as GPUI indiscriminately tries to read it into memory.

but yeah it makes no sense to render an SVG with an insanely large viewbox at its intended size. We could definitely limit that.

**Comment by jansol** [comment]
For SVG I think it makes sense to simply cap the render size at the current view size * zoom level.

For raster images it would be cool to do something like read a mipmap with the closest larger-than-view size or progressively decode the image. Alas I don't know if the image crate supports either of these. As a fallback I guess there could always be a popup showing the desired/self-proclaimed size of the image and asking the user to confirm if they want to load it?

**Comment by rgbkrk** [comment]
Note: I took out SVG rendering in the image viewer on `main` since we don't have a way to toggle to editing an image at the moment.

**Comment by MatthiasGrandl** [comment]
> Note: I took out SVG rendering in the image viewer on `main` since we don't have a way to toggle to editing an image at the moment.

Jup I mentioned this on Discord. Doesn’t really affect this PR though. Was just one of the testing scenarios.

**Comment by DissolveDZ** [comment]
Hi!

I fixed all the conflicts so it can now merge with the main branch on the newest version, here's my fork: https://github.com/DissolveDZ/zed/tree/SVG-Fix.

This should help a lot in getting this finally merged here's the before and after.

before: 

image

after:

image

I believe this pull request combined with my own should already be a way better experience when using the image viewer!

https://github.com/zed-industries/zed/pull/11051

**Comment by rgbkrk** [comment]
Hey @MatthiasGrandl, could you rebase or handle merge conflicts directly so this can be more readily merged?

**Comment by MatthiasGrandl** [comment]
Uh yeah and a ton of stuff got rearranged in GPUI. @mikayla-maki can I get some rough estimate if the approach in this PR is at all something you want to merge? Otherwise I'd rather not put in the effort rebasing.

**Comment by rgbkrk** [comment]
I'm not planning to touch the image viewer anytime soon. If you figure out a way to have SVGs be previewable without affecting editing of SVGs, then I'd say go for it.

**Comment by jansol** [comment]
Something that could be very neat is rendering a preview in preview tabs and switching to the code editor when the tab is "materialized".

**Comment by MatthiasGrandl** [comment]
Can we keep the discussion on topic? This PR has nothing to do with the Zed image viewer 😅

**Comment by rgbkrk** [comment]
> Can we keep the discussion on topic? This PR has nothing to do with the Zed image viewer 😅

Apologies, I saw the screenshots and assumed you wanted it working there as well.

**Comment by mikayla-maki** [comment]
Thank you for this PR @MatthiasGrandl ! I have not had the spare bandwidth to focus and review this PR for too long, and I'd like to redo this off of a fresh main. It's entirely my issue for not getting to this when it was opened, and my apologies for that :)

I'm going to take a stab at another implementation of this features, and let's talk about it soon.

**Comment by MatthiasGrandl** [comment]
> Thank you for this PR @MatthiasGrandl ! I have not had the spare bandwidth to focus and review this PR for too long, and I'd like to redo this off of a fresh main. It's entirely my issue for not getting to this when it was opened, and my apologies for that :)
> 
> I'm going to take a stab at another implementation of this features, and let's talk about it soon.

Sounds good and no worries!

**Pull request closed without merging**
