### PR TITLE
Add ability to open files with system default application

### LINKED ISSUE #17094: Ability to open file using system default application.
### Check for existing issues

- [X] Completed

### Describe the feature

An ability to open the currently selected file with the default system application for that mime type would be great.

Adding a keybind for this in the project panel would be ideal such as `shift space` or `shift enter` 

On linux for example, `xdg-open` could be used to open the file and similar things on other desktop platforms.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by KorigamiK**
Closes #17094 

Release Notes:

- Uses platform specific ways to open a file/directory using system defaults
- Adds a keybind `s` to the vim defaults

### CODE REVIEW

**Comment by KorigamiK** [comment]
@cla-bot check

**Comment by KorigamiK** [comment]
Note that I haven't tested the windows and mac-os functions myself so some help is appreciated

**Comment by KorigamiK** [comment]
I hope this works now :+1:

**Comment by notpeter** [comment]
I tested this on MacOS and it seemed to work. Might try to test on Windows later today (note to self: test a filename with spaces to ensure quoting/escaping is correct).

Bikeshedding/Design: Visually I don't love that the text "Open With System Application" string is so long in this context menu.  Especially if you add a keyboard shortcut: `{"context": "ProjectPanel","bindings": {"ctrl-shift-r": "project_panel::OpenWithSystem"}},`

Before/After/With KB:
Screenshot 2024-09-03 at 10 32 57Screenshot 2024-09-03 at 10 33 27Screenshot 2024-09-03 at 10 35 29

VSCode has "Open With..." which spawns a modal that shows the default associated application but won't show any external application if file format that VSCode can handle.

JetBrains groups things together under a "Open-In" submenu (Finder, Open In Associated Application, Path Popup, Terminal, GitHub).

XCode uses "Open with External Editor" but that's no shorter.

**Comment by KorigamiK** [comment]
> Bikeshedding/Design: Visually I don't love that the text "Open With System Application" string is so long/wordy in this context menu
Thanks for the feedback. Do you prefer the text 'Open in App' better?
Screenshot_2024-09-04-01-16-29_19498

**Comment by notpeter** [comment]
Interesting. On Linux it's a much wider pop-up to start because `Ctrl + Alt + Shift + C` is always going to be wider than `⌃⌥⇧C`.  Maybe "Open with Default App"?
Screenshot 2024-09-03 at 15 56 38

Let me see if Design has any input.

**Review by danilo-leal — COMMENTED** [review]
Sorry for taking a little while here! I'm happy with "Open in Default App" and we should definitely add the keybinding to it, too.

**Comment by notpeter** [comment]
> Sorry for taking a little while here! I'm happy with "Open in Default App" and we should definitely add the keybinding to it, too.

Wonderful. Suggestions for a keybind? Maybe `ctrl-shift-enter`?

@KorigamiK Can you make the language change to "Open in Default App"?  In the future if you commit to a branch (instead of main) on your fork and click "Allow Maintainers to contribute changes" we can edit your branch directly.

**Comment by KorigamiK** [comment]
Yes, I'll remember to allow Maintainers to contribute changes. I've applied the requested changes for now

**Comment by notpeter** [comment]
Congrats on your first contribution to Zed, we really appreciate it.
It'll be in Preview in an hour or so and in Zed stable next Wednesday.
Thanks!

**Pull request merged**
