### PR TITLE
Windows: Add transparency effect

### PR DESCRIPTION
**Pull request by dovakin0007**
Release Notes:

- Added Transparency effect for Windows #19405 

image

image

### CODE REVIEW

**Comment by jansol** [comment]
As I understand it Acrylic and Mica materials have the same problem as NSVisualEffectView on macOS, i.e. they add a light/dark grey layer on top of the blurred content, depending on whether the system is in light or dark mode. This makes themes appear inconsistent when switching between light and dark mode. They will also looks different from other platforms.

Does this PR somehow skip this extra brightening/darkening layer?

**Comment by dovakin0007** [comment]
> As I understand it Acrylic and Mica materials have the same problem as NSVisualEffectView on macOS, i.e. they add a light/dark grey layer on top of the blurred content, depending on whether the system is in light or dark mode. This makes themes appear inconsistent when switching between light and dark mode. They will also looks different from other platforms.
> 
> Does this PR somehow skip this extra brightening/darkening layer?

as of my knowledge I haven't added anything for making it extra dark/bright not sure what's causing it though

**Comment by jansol** [comment]
What theme are you using here? It's easiest to verify by setting the window background AND editor background to `#00000000` (completely transparent black) and then switching windows back and forth between dark and light mode. If the appearance changes, that's a problem for Zed themes.

> as of my knowledge I haven't added anything for making it extra dark/bright not sure what's causing it though

AFAIK it's simply a feature of Mica and Acrylic - if you set your window to use them it happens automatically. But the method used here is different from what I remember seeing in Microsoft's documentation so I don't know if it applies the whole material. Can't tell from the screenshot either since I don't know what the theme is doing on top of the the window...

**Comment by dovakin0007** [comment]
> @dovakin0007 : What version of Zed are you using?

0.160

**Comment by dovakin0007** [comment]
> @dovakin0007 : I think you should try reporting it as a bug by posting screenshots and explaining the problem, then we'll see.

yeah but it can reported only when this feature is added else no feature no bug 😅

**Comment by dovakin0007** [comment]
> What theme are you using here? It's easiest to verify by setting the window background AND editor background to `#00000000` (completely transparent black) and then switching windows back and forth between dark and light mode. If the appearance changes, that's a problem for Zed themes. (Make sure Zed isn't configured to automatically switch to a different theme when dark/light mode is switched)
> 
> > as of my knowledge I haven't added anything for making it extra dark/bright not sure what's causing it though
> 
> AFAIK it's simply a feature of Mica and Acrylic - if you set your window to use them it happens automatically. But the method used here is different from what I remember seeing in Microsoft's documentation so I don't know if it applies the whole material. Can't tell from the screenshot either since I don't know what the theme is doing on top of the the window...

yeah the method is little different I tried how it was implemented in doc's didn't work had to set `DwmExtendFrameIntoClientArea` margins to -1 to make it work that's the only difference

**Comment by dovakin0007** [comment]
> The problem happens when the theme is run on this pr? I thought on the official v0.161.0 (Zed Preview).

image

**Comment by dovakin0007** [comment]
> > The problem happens when the theme is run on this pr? I thought on the official v0.161.0 (Zed Preview).
> 
> image

you can see the difference between these two!

**Comment by jansol** [comment]
> image this is light mode in the theme
> 
> image this is dark mode in the theme

That does not look like it's the same theme (the icon and text color is changed). Make sure you have
```
    "theme": {
        "dark": "Catpuccin Blur Mocha ",
        "light": "Catpuccin Blur Mocha",
        "mode": "system"
    },
```
to force zed to use the same theme regardless of what the system style is.

**Comment by dovakin0007** [comment]
> "theme": {
>         "dark": "Catpuccin Blur Mocha",
>         "light": "Catpuccin Blur Mocha",
>         "mode": "system"
>     },

image

image

**Comment by jansol** [comment]
Well that looks very wrong.

**Comment by dovakin0007** [comment]
maybe this causes these artifacts to form to not sure why
image

**Comment by dovakin0007** [comment]
> to force zed to use the same theme regardless of what the system style is.

ah sorry I am bad at setting themes

**Comment by dovakin0007** [comment]
> @dovakin0007 : To be clear you are not running your pr: `run ...` You know running official Zed, changing the theme right?

oh yeah let me do that to

> @dovakin0007 : To be clear you are not running your pr: `run ...` You know running official Zed, changing the theme right?

should I run my PR version or official version?
to test the theme

**Comment by dovakin0007** [comment]
> > Where this problem happens when running the official or your modified code?
> > image
> 
> modified code

no sir!

**Comment by dovakin0007** [comment]
@Angelk90 @jansol  how does it look now?
image

image

I am using acrylic effect

**Comment by jansol** [comment]
Assuming the first two images have the same theme, the problem with the background brightening/darkening is still there.

**Comment by dovakin0007** [comment]
> It looks like you got the weird line at the top of the window and the phantom window controls in the background fixed so it's an improvement. But assuming the first two images have the same theme, the problem with the background brightening/darkening is still there.

Yeah the first two images are same theme maybe it's better to use mica effect than acrylic

**Comment by dovakin0007** [comment]
> It looks like you got the weird line at the top of the window and the phantom window controls in the background fixed so it's an improvement. But assuming the first two images have the same theme, the problem with the background brightening/darkening is still there.

image
this one?

**Comment by jansol** [comment]
> Yeah the first two images are same theme maybe it's better to use mica effect than acrylic and any suggestions how we can handle that?

["Mica is an opaque dynamic material"](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) that is only tinted with the color of the wallpaper so it's a very different thing.

[The acrylic docs](https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic) explain how acrylic works and from the looks of it it would seem it's possible to create a custom brush that has the luminosity and tint/color blend layers set to zero opacity? That should eliminate the differences between light and dark mode. (Although they also say to not use Acrylic for large areas. Oops.)

**Comment by dovakin0007** [comment]
> > Yeah the first two images are same theme maybe it's better to use mica effect than acrylic and any suggestions how we can handle that?
> 
> ["Mica is an opaque dynamic material"](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) that is only tinted with the color of the wallpaper so it's a very different thing.
> 
> [The acrylic docs](https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic) explain how acrylic works and from the looks of it it would seem it's possible to create a custom brush that has the luminosity and tint/color blend layers set to zero opacity? That should eliminate the differences between light and dark mode. (Although they also say to not use Acrylic for large areas. Oops.)

so which one can we go with it let me share the screenshot's how they look like

**Comment by jansol** [comment]
Acrylic is much closer to how it looks on other platforms so I'd say that is the way to go. But the light/dark mode changes make authoring themes that look good on all configurations impossible, so I would still get rid of that. Seems like it is possible to make custom acrylic brushes in win32 apps, although it is a bit more complicated than it needs to: https://github.com/selastingeorge/Win32-Acrylic-Effect

**Comment by dovakin0007** [comment]
> Acrylic is much closer to how it looks on other platforms so I'd say that is the way to go. But the light/dark mode changes make authoring themes that look good on all configurations impossible, so I would still get rid of that. Seems like it is possible to make custom acrylic brushes in win32 apps, although it is a bit more complicated than it needs to: https://github.com/selastingeorge/Win32-Acrylic-Effect

yeah will try to incorporate those in acrylic effect then!

**Comment by dovakin0007** [comment]
**light mode** 
image

**dark mode**
image

**Comment by dovakin0007** [comment]
image
@jansol acrylic or transparency seems like linux uses transparency 
image
difference between both

**Comment by jansol** [comment]
> seems like linux uses transparency

They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and *additionally* supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)

**Comment by dovakin0007** [comment]
> > seems like linux uses transparency
> 
> They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and _additionally_ supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)

thanks for clarifying it!

**Comment by thedeveloper-sharath** [comment]
> > > seems like linux uses transparency
> > 
> > 
> > They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and _additionally_ supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)
> 
> thanks for clarifying it!
> 
> I have went through the implementation you have shared I did see few implementations in rust image @jansol how does it look?

@dovakin0007 May be a stupid question but can't we use the existing crate i mentioned in the original issue here?
https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html

Is there any issues with this.

**Comment by dovakin0007** [comment]
> > > > seems like linux uses transparency
> > > 
> > > 
> > > They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and _additionally_ supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)
> > 
> > 
> > thanks for clarifying it!
> > I have went through the implementation you have shared I did see few implementations in rust image @jansol how does it look?
> 
> @dovakin0007 May be a stupid question but can't we use the existing crate i mentioned in the original issue here? https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html
> 
> Is there any issues with this.

adding that crate will become an another micro micro dependency and it's specific for tauri, tao and winit crate cause it uses a trait  impl and even if I use it will default to the non customizable acrylic effect

**Comment by thedeveloper-sharath** [comment]
> > > > > seems like linux uses transparency
> > > > 
> > > > 
> > > > They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and _additionally_ supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)
> > > 
> > > 
> > > thanks for clarifying it!
> > > I have went through the implementation you have shared I did see few implementations in rust image @jansol how does it look?
> > 
> > 
> > @dovakin0007 May be a stupid question but can't we use the existing crate i mentioned in the original issue here? https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html
> > Is there any issues with this.
> 
> adding that crate will become an another micro micro dependency and it's specific for tauri, tao and winit crate cause it uses a trait impl and even if I use it will default to the non customizable acrylic effect

Got it. Acrylic seems to be troublesome to implement for certain types of apps and is generally worse when it comes to resource usage and all compared to mica since mica is just a material(no full redrawing and all) and acrylic is a proper brush which is much more expensive operations. Cant we just live with Mica for now. The mica alt is a pretty good balance between that grainy translucency look.

**Comment by thedeveloper-sharath** [comment]
> > > > > > seems like linux uses transparency
> > > > > 
> > > > > 
> > > > > They are separate options, macOS supports both "transparent" and "blurred" background appearances. Linux always supports "transparent" and _additionally_ supports "blurred" on some setups (currently only on KDE Plasma when using the Wayland session, should get more widespread once compositors agree on how exactly it should work)
> > > > 
> > > > 
> > > > thanks for clarifying it!
> > > > I have went through the implementation you have shared I did see few implementations in rust image @jansol how does it look?
> > > 
> > > 
> > > @dovakin0007 May be a stupid question but can't we use the existing crate i mentioned in the original issue here? https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html
> > > Is there any issues with this.
> > 
> > 
> > adding that crate will become an another micro micro dependency and it's specific for tauri, tao and winit crate cause it uses a trait impl and even if I use it will default to the non customizable acrylic effect
> 
> Got it. Acrylic seems to be troublesome to implement for certain types of apps and is generally worse when it comes to resource usage and all compared to mica since mica is just a material(no full redrawing and all) and acrylic is a proper brush which is much more expensive operations. Cant we just live with Mica for now. The mica alt is a pretty good balance between that grainy translucency look.

**Comment by dovakin0007** [comment]
there should be a screenshot of how mica and acrylic looks like. You wouldn't like mica effect and we have to match the effect in all platforms @thedeveloper-sharath 

> > > Yeah the first two images are same theme maybe it's better to use mica effect than acrylic and any suggestions how we can handle that?
> > 
> > 
> > ["Mica is an opaque dynamic material"](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) that is only tinted with the color of the wallpaper so it's a very different thing.
> > [The acrylic docs](https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic) explain how acrylic works and from the looks of it it would seem it's possible to create a custom brush that has the luminosity and tint/color blend layers set to zero opacity? That should eliminate the differences between light and dark mode. (Although they also say to not use Acrylic for large areas. Oops.)
> 
> so which one can we go with it let me share the screenshot's how they look like image **acrylic** image **mica**

**Comment by dovakin0007** [comment]
> > May be a stupid question but can't we use the existing crate i mentioned in the original issue here?
> 
> https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html
> 
> 
> 
> As mentioned above that still has the problem of changing the acrylic effect depending on light/dark mode. However that crate also has code for DWM_BLURBEHIND which AFAIK does not change with light/dark mode, making it ideal for Zed. The only thing I'm unclear about is whether it is still supported on modern Windows versions.

Let's try it out then?

**Comment by dovakin0007** [comment]
> As mentioned above that still has the problem of changing the acrylic effect depending on light/dark mode. However that crate also has code for DWM_BLURBEHIND which AFAIK does not change with light/dark mode, making it ideal for Zed. The only thing I'm unclear about is whether it is still supported on modern Windows versions.
light mode
image
dark mode 
image
do you mean this I don't see any change with light and dark mode

**Comment by jansol** [comment]
> do you mean this I don't see any change with light and dark mode

Yeah that looks quite promising.

**Comment by jansol** [comment]
Did you have transparency without blur working too?

**Comment by dovakin0007** [comment]
> Did you have transparency without blur working too?

Yeah I did but I removed it for now cause I am not sure where to add it any guidance will be appreciated on that

**Comment by jansol** [comment]
It should be in the same `set_background_appearance` function as opaque/blurred. It's indicated by the appearance argument being `WindowBackgroundAppearance::Transparent`. (You can check the wayland and macOS  implementations for references)

**Comment by dovakin0007** [comment]
> It should be in the same `set_background_appearance` function as opaque/blurred. It's indicated by the appearance argument being `WindowBackgroundAppearance::Transparent`. (You can check the wayland and macOS implementations for references)

any transparent themes you recommend for testing?

**Comment by dovakin0007** [comment]
> > It should be in the same `set_background_appearance` function as opaque/blurred. It's indicated by the appearance argument being `WindowBackgroundAppearance::Transparent`. (You can check the wayland and macOS implementations for references)
> 
> any transparent themes you recommend for testing?

image
let me know if the opacity has to be changed

**Comment by jansol** [comment]
Well, yes. With those settings it should be completely transparent except for the red highlights and the text.

**Comment by dovakin0007** [comment]
> Well, yes. With those settings it should be completely transparent except for the red highlights and the text.

image
now ? does it look any better

**Comment by jansol** [comment]
> should be completely transparent except for the red highlights and the text

**Comment by dovakin0007** [comment]
> > should be completely transparent except for the red highlights and the text



> should be completely transparent except for the red highlights and the text


> > should be completely transparent except for the red highlights and the text

**Comment by dovakin0007** [comment]
# # # #

**Comment by dovakin0007** [comment]
> > should be completely transparent except for the red highlights and the text


image
a comparison with linux when transparency is enabled and yes it seems like enabling transparency in windows does make the whole app transparent including the highlights it happens the same when I enable it in powershell / terminal
image
that's a limitation with windows how it handles transparency if any do find a better approach than this they can change the implementation

**Review by thedeveloper-sharath — COMMENTED** [review]
Please ignore. I read it wrong. I saw it as else if rather than the else of the appearance and then a nested if.

_@dovakin0007 Any reason build number if and else if using same condition or am I reading something wrong._

**Comment by dovakin0007** [comment]
> @dovakin0007 Any reason build number if and else if using same condition or am I reading something wrong. Please ignore. I read it wrong

it's alright one part is to set_effect  and another part is to remove the effect it can be written better I guess

**Comment by thedeveloper-sharath** [comment]
@dovakin0007 I just made the changes you made to window.rs on the latest code in zed. It works

image

transparent as well

image

**Comment by dovakin0007** [comment]
> @dovakin0007 I just made the changes you made to window.rs on the latest code in zed. It works
> 
> image
> 
> transparent as well
> 
> image

could you try opening and closing the app with those changes in hand?

**Comment by thedeveloper-sharath** [comment]
> > @dovakin0007 I just made the changes you made to window.rs on the latest code in zed. It works
> > image
> > transparent as well
> > image
> 
> could you try opening and closing the app with those changes in hand?

I did the changes are persisiting

image


but if i have set it to blurred, it is too faint and if i set it to transparent and has a white window in the back, it is unreadable, what can be a middle ground?

**Comment by dovakin0007** [comment]
> > > @dovakin0007 I just made the changes you made to window.rs on the latest code in zed. It works
> > > image
> > > transparent as well
> > > image
> > 
> > 
> > could you try opening and closing the app with those changes in hand?
> 
> I did the changes are persisiting
> 
> image
> 
> but if i have set it to blurred, it is too faint and if i set it to transparent and has a white window in the back, it is unreadable, what can be a middle ground?

yeah that's due to color and opacity see whether you can find a good middle ground my eyes are really bad at this

**Comment by dovakin0007** [comment]
> > > @dovakin0007 I just made the changes you made to window.rs on the latest code in zed. It works
> > > image
> > > transparent as well
> > > image
> > 
> > 
> > could you try opening and closing the app with those changes in hand?
> 
> I did the changes are persisiting
> 
> image
> 
> but if i have set it to blurred, it is too faint and if i set it to transparent and has a white window in the back, it is unreadable, what can be a middle ground?

image

image

**Comment by thedeveloper-sharath** [comment]
this is what i see

image


image

**Comment by thedeveloper-sharath** [comment]
Windows theme is dark.

**Comment by dovakin0007** [comment]
> Windows theme is dark.

App theme?

**Comment by thedeveloper-sharath** [comment]
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "assistant": {
    "default_model": {
      "provider": "google",
      "model": "gemini-1.5-flash"
    },
    "version": "2"
  },
  "lsp": {
    "bash-language-server": {
      "command": "wsl.exe",
      "args": ["bash", "-c", "bash-language-server start"]
    }
  },
  "features": {
    "inline_completion_provider": "supermaven"
  },
  "ui_font_size": 18,
  "buffer_font_size": 18,
  "buffer_font_family": "RobotoMono Nerd Font",
  "ui_font_family": "DroidSansM Nerd Font",
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Glazier | Deep Space"
  },
  "experimental.theme_overrides": {
    "background.appearance": "blurred",
    "background": "#00000000"
  },
  //
  //   "panel.background": "#00000090",
  //   "editor.background": "#00000090",
  //   "tab_bar.background": "#00000090",
  //   "terminal.background": "#00000090",
  //   "toolbar.background": "#00000090",
  //   "tab.inactive_background": "#00000000",
  //   // "tab.active_background": "#3f3f4650",
  //   "border": "#00000000",
  //   "status_bar.background": "#00000000",
  //   "title_bar.background": "#00000000",
  //   "border.variant": "#00000000",
  //   "scrollbar.track.background": "#52525b20",
  //   "scrollbar.track.border": "#00000000",
  //   "scrollbar.thumb.background": "#52525b30",
  //   "scrollbar.thumb.border": "#00000000",
  //   "elevated_surface.background": "#00000090",
  //   "surface.background": "#00000090",
  //   // "editor.active_line_number": "#ffffffcc",
  //   "editor.gutter.background": "#00000000",
  //   "editor.indent_guide": "#ffffff30",
  //   "editor.indent_guide_active": "#ffffff80",
  //   "editor.line_number": "#ffffff80",
  //   "editor.active_line.background": "#3f3f4640"
  // },
  "terminal": {
    "alternate_scroll": "off",
    "blinking": "terminal_controlled",
    "copy_on_select": false,
    "env": {},
    "font_family": "DroidSansM Nerd Font",
    "font_features": null,
    "font_size": 18,
    "option_as_meta": false,
    "button": false,
    "shell": {
      "program": "wsl.exe"
    },
    "toolbar": {
      "title": true
    },
    "working_directory": "current_project_directory"
  }
}

**Comment by thedeveloper-sharath** [comment]
> // Zed settings // // For information on how to configure Zed, see the Zed // documentation: https://zed.dev/docs/configuring-zed // // To see all of Zed's default settings without changing your // custom settings, run `zed: open default settings` from the // command palette (cmd-shift-p / ctrl-shift-p) { "assistant": { "default_model": { "provider": "google", "model": "gemini-1.5-flash" }, "version": "2" }, "lsp": { "bash-language-server": { "command": "wsl.exe", "args": ["bash", "-c", "bash-language-server start"] } }, "features": { "inline_completion_provider": "supermaven" }, "ui_font_size": 18, "buffer_font_size": 18, "buffer_font_family": "RobotoMono Nerd Font", "ui_font_family": "DroidSansM Nerd Font", "theme": { "mode": "system", "light": "One Light", "dark": "Glazier | Deep Space" }, "experimental.theme_overrides": { "background.appearance": "blurred", "background": "#00000000" }, // // "panel.background": "#90", // "editor.background": "#90", // "tab_bar.background": "#90", // "terminal.background": "#90", // "toolbar.background": "#90", // "tab.inactive_background": "#00000000", // // "tab.active_background": "#3f3f4650", // "border": "#00000000", // "status_bar.background": "#00000000", // "title_bar.background": "#00000000", // "border.variant": "#00000000", // "scrollbar.track.background": "#52525b20", // "scrollbar.track.border": "#00000000", // "scrollbar.thumb.background": "#52525b30", // "scrollbar.thumb.border": "#00000000", // "elevated_surface.background": "#90", // "surface.background": "#90", // // "editor.active_line_number": "#ffffffcc", // "editor.gutter.background": "#00000000", // "editor.indent_guide": "#ffffff30", // "editor.indent_guide_active": "#ffffff80", // "editor.line_number": "#ffffff80", // "editor.active_line.background": "#3f3f4640" // }, "terminal": { "alternate_scroll": "off", "blinking": "terminal_controlled", "copy_on_select": false, "env": {}, "font_family": "DroidSansM Nerd Font", "font_features": null, "font_size": 18, "option_as_meta": false, "button": false, "shell": { "program": "wsl.exe" }, "toolbar": { "title": true }, "working_directory": "current_project_directory" } }

currently doing my day job, so if they see me on call for something completely unrelated, they may get pissed.

**Comment by dovakin0007** [comment]
> // Zed settings
> //
> // For information on how to configure Zed, see the Zed
> // documentation: https://zed.dev/docs/configuring-zed
> //
> // To see all of Zed's default settings without changing your
> // custom settings, run `zed: open default settings` from the
> // command palette (cmd-shift-p / ctrl-shift-p)
> {
> "assistant": {
> "default_model": {
> "provider": "google",
> "model": "gemini-1.5-flash"
> },
> "version": "2"
> },
> "lsp": {
> "bash-language-server": {
> "command": "wsl.exe",
> "args": ["bash", "-c", "bash-language-server start"]
> }
> },
> "features": {
> "inline_completion_provider": "supermaven"
> },
> "ui_font_size": 18,
> "buffer_font_size": 18,
> "buffer_font_family": "RobotoMono Nerd Font",
> "ui_font_family": "DroidSansM Nerd Font",
> "theme": {
> "mode": "system",
> "light": "One Light",
> "dark": "Glazier | Deep Space"
> },
> "experimental.theme_overrides": {
> "background.appearance": "blurred",
> "background": "#00000000"
> },
> //
> // "panel.background": "#90",
> // "editor.background": "#90",
> // "tab_bar.background": "#90",
> // "terminal.background": "#90",
> // "toolbar.background": "#90",
> // "tab.inactive_background": "#00000000",
> // // "tab.active_background": "#3f3f4650",
> // "border": "#00000000",
> // "status_bar.background": "#00000000",
> // "title_bar.background": "#00000000",
> // "border.variant": "#00000000",
> // "scrollbar.track.background": "#52525b20",
> // "scrollbar.track.border": "#00000000",
> // "scrollbar.thumb.background": "#52525b30",
> // "scrollbar.thumb.border": "#00000000",
> // "elevated_surface.background": "#90",
> // "surface.background": "#90",
> // // "editor.active_line_number": "#ffffffcc",
> // "editor.gutter.background": "#00000000",
> // "editor.indent_guide": "#ffffff30",
> // "editor.indent_guide_active": "#ffffff80",
> // "editor.line_number": "#ffffff80",
> // "editor.active_line.background": "#3f3f4640"
> // },
> "terminal": {
> "alternate_scroll": "off",
> "blinking": "terminal_controlled",
> "copy_on_select": false,
> "env": {},
> "font_family": "DroidSansM Nerd Font",
> "font_features": null,
> "font_size": 18,
> "option_as_meta": false,
> "button": false,
> "shell": {
> "program": "wsl.exe"
> },
> "toolbar": {
> "title": true
> },
> "working_directory": "current_project_directory"
> }
> }

`{
  "theme": "Glazier | Deep Space",
  "assistant": {
    "default_model": {
      "provider": "ollama",
      "model": "llama3.2:latest"
    },
    "version": "2"
  },
  "ui_font_size": 12,
  "buffer_font_size": 12,
  "inlay_hints": {
    "enabled": true,
    "show_type_hints": true,
    "show_parameter_hints": true,
    "show_other_hints": true,
    "show_background": true,
    "edit_debounce_ms": 700,
    "scroll_debounce_ms": 50
  },
  "experimental.theme_overrides": {
    "background.appearance": "transparent",
    "background": "#0000000"
  }
}
try this

**Comment by thedeveloper-sharath** [comment]
Yes now with setting just theme and setting background to 0000070 it works

**Comment by thedeveloper-sharath** [comment]
> > Yes now with setting just theme and setting background to 0000070 it works
> 
> what do you say about transparency should we increase the effect or reduce it?

with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.

**Comment by dovakin0007** [comment]
> > > Yes now with setting just theme and setting background to 0000070 it works
> > 
> > 
> > what do you say about transparency should we increase the effect or reduce it?
> 
> with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.



> > > Yes now with setting just theme and setting background to 0000070 it works
> > 
> > 
> > what do you say about transparency should we increase the effect or reduce it?
> 
> with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.

https://github.com/dovakin0007/zed/blob/25d1032c2e605b720e04c4462ced7827111c3bf4/crates/gpui/src/platform/windows/window.rs#L676 you can change the value from `210` to higher from more transparent effect if you find a good enough spot do push those changes I am really bad at figuring out which looks good

**Comment by thedeveloper-sharath** [comment]
> > > > Yes now with setting just theme and setting background to 0000070 it works
> > > 
> > > 
> > > what do you say about transparency should we increase the effect or reduce it?
> > 
> > 
> > with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.
> 
> > > > Yes now with setting just theme and setting background to 0000070 it works
> > > 
> > > 
> > > what do you say about transparency should we increase the effect or reduce it?
> > 
> > 
> > with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.
> 
> https://github.com/dovakin0007/zed/blob/25d1032c2e605b720e04c4462ced7827111c3bf4/crates/gpui/src/platform/windows/window.rs#L676 you can change the value from `210` to higher from more transparent effect if you find a good enough spot do push those changes I am really bad at figuring out which looks good

@jansol What is you opinion on this, i mean us figuring out something or letting users control?

**Comment by dovakin0007** [comment]
> > > > > Yes now with setting just theme and setting background to 0000070 it works
> > > > 
> > > > 
> > > > what do you say about transparency should we increase the effect or reduce it?
> > > 
> > > 
> > > with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.
> > 
> > 
> > > > > Yes now with setting just theme and setting background to 0000070 it works
> > > > 
> > > > 
> > > > what do you say about transparency should we increase the effect or reduce it?
> > > 
> > > 
> > > with this being used by devs and will have a lot of text and all, i think it is better if we increase the tint even when in transparent mode, blurred is mostly devoid of this issue.
> > 
> > 
> > https://github.com/dovakin0007/zed/blob/25d1032c2e605b720e04c4462ced7827111c3bf4/crates/gpui/src/platform/windows/window.rs#L676 you can change the value from `210` to higher from more transparent effect if you find a good enough spot do push those changes I am really bad at figuring out which looks good
> 
> @jansol What is you opinion on this, i mean us figuring out something or letting users control?
letting users change is not an option as of now cause the effect doesn't pass any values the only thing we can do is find a good spot which looks good

**Comment by dovakin0007** [comment]
> oh, ok. let me see
> 
> 

Linux and MacOS handles transparency much better than how it's been done on windows or may be we haven't explored options yet

**Comment by thedeveloper-sharath** [comment]
> > oh, ok. let me see
> 
> Linux and MacOS handles transparency much better than how it's been done on windows or may be we haven't explored options yet

225/230 looks to be better since they give a balance of transparency and readability. 230 is better but loses significantly on transparency, 225 strikes the balance well at least for my eyes.

**Comment by dovakin0007** [comment]
> > > oh, ok. let me see
> 
> > 
> 
> > Linux and MacOS handles transparency much better than how it's been done on windows or may be we haven't explored options yet
> 
> 
> 
> 225/230 looks to be better since they give a balance of transparency and readability. 230 is better but loses significantly on transparency, 225 strikes the balance well at least for my eyes. 

You can change it and push it if you want to!

**Comment by thedeveloper-sharath** [comment]
> > > > oh, ok. let me see
> > 
> > 
> > > 
> > 
> > 
> > > Linux and MacOS handles transparency much better than how it's been done on windows or may be we haven't explored options yet
> > 
> > 
> > 225/230 looks to be better since they give a balance of transparency and readability. 230 is better but loses significantly on transparency, 225 strikes the balance well at least for my eyes.
> 
> You can change it and push it if you want to!

it asks me to fork it, so i didn't. If that is okay i can do and push

**Comment by thedeveloper-sharath** [comment]
can't we create a branch in zed and just put this window.rs(the one i have and raise an MR?

**Comment by dovakin0007** [comment]
> can't we create a branch in zed and just put this window.rs(the one i have and raise an MR?
> 
> 

I don't have the perms to create branch 🤣🤣🤣

**Comment by dovakin0007** [comment]
> > > > > oh, ok. let me see
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Linux and MacOS handles transparency much better than how it's been done on windows or may be we haven't explored options yet
> 
> > > 
> 
> > > 
> 
> > > 225/230 looks to be better since they give a balance of transparency and readability. 230 is better but loses significantly on transparency, 225 strikes the balance well at least for my eyes.
> 
> > 
> 
> > You can change it and push it if you want to!
> 
> 
> 
> it asks me to fork it, so i didn't. If that is okay i can do and push

Yeah you can

**Comment by thedeveloper-sharath** [comment]
@cla-bot check

**Comment by dovakin0007** [comment]
> @cla-bot check

Try to get a good match between linux and windows version for transparency if possible

**Comment by dovakin0007** [comment]
> https://github.com/dovakin0007/zed/pull/1 - here you go

If possible please do find the right balance with blur implementation to It's hard for me differentiate colors and differences

**Comment by thedeveloper-sharath** [comment]
> > [dovakin0007#1](https://github.com/dovakin0007/zed/pull/1) - here you go
> 
> If possible please do find the right balance with blur implementation to It's hard for me differentiate colors and differences

image

on linux

image

**Comment by dovakin0007** [comment]
> > > [dovakin0007#1](https://github.com/dovakin0007/zed/pull/1) - here you go
> 
> > 
> 
> > If possible please do find the right balance with blur implementation to It's hard for me differentiate colors and differences
> 
> 
> 
> image
> 
> 
> 
> on linux
> 
> 
> 
> image
> 
> 

Let's wait till what @jansol has to say

**Review by thedeveloper-sharath — APPROVED** [review]
LGTM.

**Review by SomeoneToIgnore — APPROVED** [review]
Given that everyone in the comments seem to be fine (or not against) with the change and this is Windows-only, let's merge this.

**Comment by SomeoneToIgnore** [comment]
One note from me, for the future PRs: this OS name is spelled as `Windows`, not `windows`.

**Comment by dovakin0007** [comment]
> Given that everyone in the comments seem to be fine (or not against) with the change and this is Windows-only, let's merge this.


Thank you!

**Pull request merged**
