### PR TITLE
Keep tab position when closing tabs

### LINKED ISSUE #18036: Keep tab position when closing tabs
### Check for existing issues

- [X] Completed

### Describe the feature

When closing tabs, I expect zed to keep the position of whatever tab I'm at when I close it with cmd+w, like how a browser would. i.e. if I have 5 tabs open, and I close the 3rd tab, I expect zed to keep the new 3rd tab focused. 
I often have a lot of tabs open as I'm working and go to cull them in bulk by holding cmd+w, but usually I want to keep my most recent tab open as I'm still working on it. What happens at that point is that the editor jumps to my most recent tab which might have changes and it's really annoying to have either close it out so I can just hold cmd+w or constantly click out of the tab so I can close out all my other tabs. 

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by patrickJramos**
- Closes #18036

Release Notes:

- N/A

### CODE REVIEW

**Comment by patrickJramos** [comment]
@cla-bot check

**Comment by patrickJramos** [comment]
I've changed the test to reflect the new behaviour

**Comment by osiewicz** [comment]
Thanks!

**Comment by SomeoneToIgnore** [comment]
To note, this is a very bad and ignorant PR.
It came and simply broke somebody's existing workflow: https://github.com/zed-industries/zed/issues/19036 including mine, and it wook a while for me to get back here.

Note for the future: do not blatantly remove some functionality (that's even coverred by tests!) as someone most probably need this.

I'm going to work on returning the old behavior back (enabled by default), and hidning this one under the settings.

**Comment by patrickJramos** [comment]
Really sorry about this, it's my first open source contribution and i guess i got too excited managing to "fix" an issue.

I'll be more careful and considerate in the future

**Comment by osiewicz** [comment]
@patrickJramos don't take it the hard way, it's not your fault - I am the one who merged your PR and thus it was my responsibility, not yours, to ensure that it's appropriate.

**Pull request merged**
