### PR TITLE
Add kimiai assistant

### PR DESCRIPTION
**Pull request by liuhuo23**
Release Notes:
- Added Kimi assistant

[kimi](https://kimi.moonshot.cn/) developed by Moonshot AI, I am an AI assistant proficient in multiple languages, especially Chinese and English. My superpowers include handling lengthy texts, analyzing documents, and providing information based on web content.

### CODE REVIEW

**Comment by nervenes** [comment]
(im not apart of this pr) why does the cla complain about me not being verified?
Screenshot 2024-08-31 at 10 05 55

**Comment by nervenes** [comment]
@cla-bot check

**Comment by nervenes** [comment]
2024-08-31T07:43:47.033Z INFO The contributors @nervenes have not signed the CLA, adding error status to the pull request

🤔 🤔 🤔

**Comment by maxdeviant** [comment]
Dupe of #17193.

**Pull request closed without merging**
