### PR TITLE
Fix alignment of status bar icons

### LINKED ISSUE #7374: status bar icons aren't properly aligned
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

screenshot

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by slymax**
closes #7374

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
Should the fix not be to make all the icons the same size? Instead of aligning the SVG's inside the files? Because they were aligned correctly before inside the files.

**Comment by slymax** [comment]
yeah for some reason `ai.svg` and `bell.svg` still look off when properly centered – not sure why

**Comment by RemcoSmitsDev** [comment]
> yeah for some reason `ai.svg` and `bell.svg` still look off when properly centered – not sure why

Do you have screenshots of the status bar when all the icons are the same size (height & width)? Maybe we can help you to make it not look off.

**Comment by slymax** [comment]
so this is the state of the PR – icons look aligned in zed but the icons in `ai.svg` and `bell.svg` are actually off center:

Bildschirmfoto 2024-02-19 um 22 58 18

this is what it looks like with the icons centered in the svgs:

Bildschirmfoto 2024-02-19 um 23 26 54

I'm not really sure if the issue comes across on the screenshots but the assistant and notification icons are skewed to the bottom right. If you hover over the icons in zed, you can see that they aren't properly centered inside the button. It's especially noticeable when you disable some of the other buttons:

Bildschirmfoto 2024-02-19 um 23 35 53

The two svgs in question:

ai

bell

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I don't think this is the right approach.

The way the bell icon is offset is incorrect, and it is now inconsistent with the other bell icons.

Screenshot 2024-02-21 at 11 58 18 AM

**Comment by slymax** [comment]
> The way the bell icon is offset is incorrect, and it is now inconsistent with the other bell icons.

yes, I haven't touched the other icons yet

> I don't think this is the right approach.

what would be the right approach then to get them aligned?

currently icon sizes, alignment within the svgs, stroke widths, etc are all over the place

**Comment by maxdeviant** [comment]
> > The way the bell icon is offset is incorrect, and it is now inconsistent with the other bell icons.
> 
> yes, I haven't touched the other icons yet
> 
> > I don't think this is the right approach.
> 
> what would be the right approach then to get them all aligned?
> 
> currently icon sizes, alignment within the svgs, stroke widths, etc are all over the place – and as mentioned above, I'm not really sure why some of the icons don't align in zed when they are centered within the svgs
> 
> should I go ahead with aligning the rest of the bell icons or do we abandon this?

I think there's going to be a larger effort involved to make our icons consistent and develop a pipeline to ensure they stay that way.

Our designer, Nate, is currently on paternity leave, and I suspect we won't be getting to it before he is back.

I'm going to close this for now, as I think we can live with the current state for a while longer.

**Comment by slymax** [comment]
agreed, I'd still have preferred a temporary solution until this happens though

**Pull request closed without merging**
