### PR TITLE
Styling option for separating terminal view background from background color

### LINKED ISSUE #17313: Create seperate setting for terminal background & terminal background ansi color
### Check for existing issues

- [X] Completed

### Describe the feature

When using a `transparent` or `blurred` theme, I wish to have a terminal that is transparent.

Unfortunately, text using the "background" color in my terminal gets turned invisible.

image

The correct behavior should look like this

image

However, our terminal is turned dark and we can no longer see the blurred background effect in the theme

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by AlbertMarashi**
Closes #17313

Release Notes:

- Added theme styling option to separate terminal background view from terminal background color, for transparent terminal backgrounds

### CODE REVIEW

**Comment by AlbertMarashi** [comment]
I'm not entirely sure here whether this is the best approach, but the core of the issue is that terminals with transparent backgrounds would display invisible text:

**Before**:
image


**After**:
image


> [!NOTE]
> This only applies in themes where `terminal.background` is set to a transparent value
> ```json
> "terminal.background": "#0000",
> ```

**Comment by iamnbutler** [comment]
I'm not totally sure I understand how this works/when this is a problem, but your implementation looks right. I have no issue merging if you think it is ready. Thanks!

**Comment by AlbertMarashi** [comment]
@iamnbutler this is specifically for themes that use transparent backgrounds `background.appearance` `blurred|transparent`

I did test this briefly with all of the default light/dark themes and did not find any visual differences in terminal coloring with what they currently are.

You can run the following bash script to get a sample of terminal colorings

```bash
#!/bin/bash

# Function to print colored text with reverse video
print_reverse_color() {
    local color=$1
    local color_name=$2
    echo -e "\033[7m\033[1m\033[${color}m ${color_name} \033[39m\033[22m\033[27m"
}

# Print header
echo "Reverse Video ANSI Color Test"
echo "-----------------------------"

# Standard colors
print_reverse_color "30" "Black"
print_reverse_color "31" "Red"
print_reverse_color "32" "Green"
print_reverse_color "33" "Yellow"
print_reverse_color "34" "Blue"
print_reverse_color "35" "Magenta"
print_reverse_color "36" "Cyan"
print_reverse_color "37" "White"

echo

# Bright colors
print_reverse_color "90" "Bright Black"
print_reverse_color "91" "Bright Red"
print_reverse_color "92" "Bright Green"
print_reverse_color "93" "Bright Yellow"
print_reverse_color "94" "Bright Blue"
print_reverse_color "95" "Bright Magenta"
print_reverse_color "96" "Bright Cyan"
print_reverse_color "97" "Bright White"

echo

# Default color
echo -e "\033[7m\033[1m Default Color \033[22m\033[27m"
```

For your convenience, I have tested the following examples

**Left** (this commit) - **Right** (before this commit)

## My custom transparent theme
- Uses `#0000` for `terminal.background` (making it fully transparent)
- Uses `#000` for `terminal.ansi.background` (making the text background color black, which during ANSI video reversal, becomes the foreground color)

image

## Atelier Savanna Dark
image

## Ayu Light

image


## Rose Pine Dawn

image

As you can see, there appears to be no discernible difference with existing themes, only that this fixes the themes that use a transparent `terminal.background`

**Comment by iamnbutler** [comment]
Great, thanks for the detailed answer! Merged!

**Pull request merged**
