### PR TITLE
vim: `f` and `t` multiline option

### PR DESCRIPTION
**Pull request by romgrk**
I'm not sure how compliant you're aiming to be with vim, but the `f` behavior is more useful when it can search on multiple lines instead of a single one, so I'd like to propose this change.

This change is quite frequent in vim/neovim as a plugin (e.g. [clever-f](https://github.com/VSCodeVim/Vim), [improved-ft](https://github.com/backdround/improved-ft.nvim), etc), and in other vim emulations (e.g. [vscode-vim](https://github.com/VSCodeVim/Vim)).

Release notes:

- vim: Add a setting for `{"vim": {"use_multiline_find":true}}` that lets `f,t,F,T` search across line boundaries.

### CODE REVIEW

**Comment by romgrk** [comment]
Good question, that's a difference with vim.

For visual block selection, it seems to act as if there was only one cursor, the last one, and all the other cursors follow the last one. This is not different than other motions right now, e.g. `w` does word motions on the last cursor and the other cursors follow the column position, regardless of the words on their own line.

For multiple cursors that end up on the same line, I haven't tested yet, depends what's the behavior right now when multiple cursors collide, but I haven't found a way to create multiple cursors in vim normal mode other than visual block selection.

**Comment by romgrk** [comment]
Sounds good, I think I have enough information to do it by myself.

**Comment by mrnugget** [comment]
> but I haven't found a way to create multiple cursors in vim normal mode other than visual block selection.

FWIW you can use `opt-click` (it would be neat if we find a Vim-y way to this):
screenshot-2024-02-27-09 59 29

**Comment by romgrk** [comment]
Gotcha, works on linux as `alt-click`. Played a bit with colliding selections/cursors and multiline find, it feels like the current behavior is good.

> it would be neat if we find a Vim-y way to this

I see two solutions to create multiple cursors in a keyboard-centric way:
 - Have a "create cursors" mode, where the user can move like in normal mode and mark locations for new cursors, and once complete all the marks turn to cursors.
 - Inspired by [atom-vim-mode-plus](https://www.youtube.com/watch?v=01yHgi59ASg&t=119s) and kakoune selections, we can add a command that adds cursors at either pre-defined patterns (e.g. word boundaries, other matches for current word, etc) or user-inputed patterns (regex). In conjunction with visual mode or operator-pending mode, it's a very efficient way to add cursors.

Once we get linux working I'd definitely be interested in spending some time on the vim implementation.

**Comment by romgrk** [comment]
This is ready for review.

**Comment by ConradIrwin** [comment]
Great, thanks so much for this!

I'd love to talk through the multi-cursor thing before you jump in and implement anything.

**Pull request merged**
