### PR TITLE
Add ability to scroll popovers with vim

### PR DESCRIPTION
**Pull request by ConradIrwin**
Co-Authored-By: ahmadraheel@gmail.com

Release Notes:

- vim: allow scrolling the currently open information overlay using `ctrl-{u,d,e,y}`etc. (#11883)

### CODE REVIEW

**Comment by natac13** [comment]
I was really hoping for this feature! However, I was hoping it would be closer to that of neovim of vscode where there is a keybinding to foucs the cursor onto the overlay menu itself and then have a 'context' for that which we could then apply our own key bindings for how to scroll the overlay menu. It seems I am forced to use the same keybindings as setup with "Vim:Srcoll*" or Vim:Line*" Any chance on having a focus overlay command which would lead to a context of "OverlayOpen"?

**Comment by ConradIrwin** [comment]
@natac13 Can you please file a separate issue for that. @0x2CA brought it up again in the context of #12918 too.

**Comment by KorigamiK** [comment]
> @natac13 Can you please file a separate issue for that. @0x2CA brought it up again in the context of #12918 too.

Was this issue created or fixed in any way? I'd like to propose this issue if not

**Comment by natac13** [comment]
> > @natac13 Can you please file a separate issue for that. @0x2CA brought it up again in the context of #12918 too.
> 
> Was this issue created or fixed in any way? I'd like to propose this issue if not

Sorry, I did not post the issue. I have not been using Zed for a few other reasons and did not want to create more work by filing this issue just after this featured was released. Sorry again

**Pull request merged**
