### PR TITLE
Add DeleteToPreviousWordEnd, DeleteToNextWordStart

### LINKED ISSUE #5285: A bit counterintuitive `delete word` behavior
**Is your feature request related to a problem? Please describe.**
`delete word` behavior is different to other code editors like sublime text and vs code when deleting non-word characters.

**Describe the solution you'd like**
Make it like in vs code.

**Describe alternatives you've considered**
No alternatives available.

**Screenshots (Videos)**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

This is vs code:

https://user-images.githubusercontent.com/24634903/179301934-fa882b9f-f54d-4e27-9210-866f4c250693.mov

This is sublime text 4:

https://user-images.githubusercontent.com/24634903/179300781-03a2920f-87a4-4027-bd0e-4ded90631d0e.mov

This is Zed:

https://user-images.githubusercontent.com/24634903/179301926-c289fa62-8079-478c-8968-abdec7057816.mov

### PR DESCRIPTION
**Pull request by thataboy**
Closes https://github.com/zed-industries/zed/issues/5285, https://github.com/zed-industries/zed/issues/14389, https://github.com/zed-industries/zed/issues/14389, https://github.com/zed-industries/zed/issues/16196

When there are whitespaces between the cursor and the word to delete, DeleteToPreviousWordEnd and DeleteToNextWordStart delete *only* the whitespaces rather than the whitespaces **and** the word in one go (zed's default behavior). This mode of operation is more familiar and arguably more intuitive to users of editors such as VSCode or SublimeText

Release Notes:

- Added editor::DeleteToPreviousWordEnd command
- Added editor::DeleteToNextWordStart command

### CODE REVIEW

**Comment by thataboy** [comment]
@cla-bot check

**Comment by mikayla-maki** [comment]
this PR also wants to fix this issue: https://github.com/zed-industries/zed/pull/16848

**Comment by thataboy** [comment]
> this PR also wants to fix this issue: #16848

I may be biased :) but IMHO, mine is a cleaner solution. It does not alter the behavior of the current command, which is not buggy per se. It does exactly what it says: delete to the previous word start, no more, no less. I'm guessing this is vim's behavior, and we should let vimmers vim! 

The other PR changes the original command's behavior, then reintroduces it with a different, long a__ name. I believe it's cleaner to just have a separate command which does exactly what it says -- delete to the previous word end.

I believe there's also a subtle difference in that DeleteToPreviousWordEnd not only stops at the `\n`,  when you hit it again, it does not delete the word yet but delete the `\n` and any whitespace and stops at the word's end, thus giving you no "oops, I did not expect that" surprise. I hope the video below explains it better. (Also, you get two commands for the price of one PR :)


https://github.com/user-attachments/assets/51c16f64-95c7-460c-861a-6ad3dcf707f4

**Comment by thataboy** [comment]
PR is no longer relevant. Issue fixed in main

**Pull request closed without merging**
