### PR TITLE
bookmark: Add bookmark support

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Currently bookmark can work, and had something not done.
Want to get some feedback and suggestion.

Release Notes:

- Add bookmark support

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this!

I think bookmarks should be based on Anchors, not on row/column, so that as the code is edited the bookmarks stay in the "same place". In order to make this work reliably, we'd either have to ensure that creating a bookmark keeps the file open, so the Bookmark might end up being `struct Bookmark{ buffer: Model<Buffer>, anchor: text::Anchor }`.

We also need to think about multi-buffers. If you create a book mark from a project search, and then go to that bookmark, should it take you to that position in the underlying buffer, or in the multibuffer?

**Comment by CharlesChen0823** [comment]
> I think bookmarks should be based on Anchors, not on row/column, so that as the code is edited the bookmarks stay in the "same place". 

I think there is an use case, we cannot easy toggle the bookmark remove, if we based on Anchors.

> In order to make this work reliably, we'd either have to ensure that creating a bookmark keeps the file open

I had check some other implementation, IMO, bookmarks should exist even if the current buffer is closed,  if using <Buffer> to represent bookmark, we should keep buffer always opened?

**Comment by ConradIrwin** [comment]
I think removing Anchors can still work, you just need to convert the anchor back to a point when checking?

If we retain the buffer in the bookmark store as a `Model<Buffer>` it will stay in memory even if the editor is closed. The alternative would be to convert between anchors and row/column when the buffer is closed - which you may want to do if you want bookmarks to persist when the workspace is closed and reopened.

**Comment by CharlesChen0823** [comment]
> I think removing Anchors can still work, you just need to convert the anchor back to a point when checking?

I don't thought can remove, I thought when user toggle remove a bookmark, he should first find the correct point, then can remove it. It's not better UX.


> If we retain the buffer in the bookmark store as a `Model<Buffer>` it will stay in memory even if the editor is closed. The alternative would be to convert between anchors and row/column when the buffer is closed - which you may want to do if you want bookmarks to persist when the workspace is closed and reopened.

Ahh，thanks，i'm misunderstood.

I will convert using Modal<Buffer>

**Comment by SomeoneToIgnore** [comment]
This looks quite stale, so I'll close this.

**Pull request closed without merging**
