### PR TITLE
Faster completion support for remotes 

### PR DESCRIPTION
**Pull request by maan2003**
Before this change we canceled every completion task on each keystroke.
This works fine when the latency to the LSP is low, but on a remote that
may be a few hundred ms away, this means you are always having to wait
until the completions show.

This also help if language server takes a while to respond to completion requests.

Release Notes:

 - Improved perceived latency of completions over the network

### CODE REVIEW

**Comment by maan2003** [comment]
supersedes https://github.com/zed-industries/zed/pull/17954, so I can also push changes

**Comment by maan2003** [comment]
latency saved is time taken to type the last word before completion.

**Comment by maan2003** [comment]
noticed that filtering completions can be really slow in some cases

from logs
[crates/editor/src/editor.rs:1360:9] start.elapsed() = 181.814619ms

**Comment by maan2003** [comment]
just dropping completions future doesn't cancel the request to remote server (tested in ssh case).

and rust analyzer sends huge completions response every time (~800KB) due to including docs.

this delays future responses because you have to wait for x * 800KB data to be received where x is number of keystrokes

**Comment by osiewicz** [comment]
just fyi @maan2003, @SomeoneToIgnore has recently landed a PR which significantly reduces the amount of data sent back by RA: https://github.com/rust-lang/rust-analyzer/pull/18167

**Comment by maan2003** [comment]
nice!

**Comment by SomeoneToIgnore** [comment]
This looks somewhat stale and outdates, so I'll close this to keep the PR queue cleaner.
Feel free to resubmit when ready.

**Pull request closed without merging**
