### PR TITLE
linux: Update `TryExec` value in desktop file

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
Release Notes:

- Fixed ([#15148](https://github.com/zed-industries/zed/issues/15148)).

### CODE REVIEW

**Comment by HarshNarayanJha** [comment]
@cla-bot check

**Comment by jansol** [comment]
The idea with having TryExec and Exec refer to different things was to make sure you have the GUI itself available too (via TryExec) and not just the CLI helper. I haven't followed the Linux CLI development too closely though, so not sure if that makes sense any more.

**Comment by HarshNarayanJha** [comment]
> The idea with having TryExec and Exec refer to different things was to make sure you have the GUI itself available too (via TryExec) and not just the CLI helper

Don't know about the distinction between CLI and GUI for the `zeditor` command, since invoking it will open GUI anyway. And in this case, the issue is that this [commit](https://github.com/zed-industries/zed/commit/0c6105992cc496976e3d27c0884e5b210074a3ca) was to allow `zed://` URL handlers to open, which changed MimeType in the desktop file
```diff
-  MimeType=text/plain;inode/directory;
+ MimeType=text/plain;inode/directory;x-scheme-handler/zed;
```

But also changed the TryExec
```diff
- TryExec=$APP_CLI
+ TryExec=$APP
```
I tried to find, but couldn't, any reference to from where the `$APP,` and `$APP_CLI` are being populated from.

The Freedesktop specification cleary states that

> TryExec:- Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example). 

If I reinstall zed right now on my machine, I can confirm that it removed Zed from Application List, and `TryExec` is empty. Right now, it seems correct for it's value to be `$APP_CLI`, since that is also the value for `Exec`.
It might be the case that @ConradIrwin is planning some changes related to App URLS, but this update is clearly broken for me, or atleast me.

Other Linux users may confirm the issue.

**Comment by HarshNarayanJha** [comment]
Also, I can fix it (and for the future updates too) by copying the file to `~/.local/share/applications` and overriding it, but it should be empty by default

**Comment by jansol** [comment]
> I tried to find, but couldn't, any reference to from where the $APP, and $APP_CLI are being populated from.

That would be `script/bundle-linux`

**Comment by HarshNarayanJha** [comment]
See, there is no `APP` defined [here](https://github.com/zed-industries/zed/blob/8ba392bba638325163acce2e458135b88d92afb8/script/bundle-linux#L86C1-L99C3)

```bash
# .desktop
export DO_STARTUP_NOTIFY="true"
export APP_CLI="zed"
export APP_ICON="zed"
export APP_ARGS="%U"
if [[ "$channel" == "preview" ]]; then
  export APP_NAME="Zed Preview"
elif [[ "$channel" == "nightly" ]]; then
  export APP_NAME="Zed Nightly"
elif [[ "$channel" == "dev" ]]; then
  export APP_NAME="Zed Devel"
else
  export APP_NAME="Zed"
fi
```

But `APP_CLI="`zed"`, then how do I end up getting `zeditor`, maybe the package manager

**Comment by jansol** [comment]
Yes, if you install zed from a 3rd party repo, the packagers can and quite possibly do completely rewrite the .desktop file and no amount of patching it here will help you.

**Comment by ConradIrwin** [comment]
The idea was to launch the app directly (instead of going via the CLI) from the desktop file (similar to how it's done on Mac). This didn't work (hence all the logic for supporting URLs now in the CLI), but I forgot to revert the change the manifest file.

Thanks!

/cherry-pick v0.146.x

**Comment by jansol** [comment]
> The idea was to launch the app directly (instead of going via the CLI) from the desktop file (similar to how it's done on Mac). This didn't work (hence all the logic for supporting URLs now in the CLI), but I forgot to revert the change the manifest file.

Thanks for adding the official explanation!

**Pull request merged**
