### PR TITLE
Remove lsp-less grammars

### PR DESCRIPTION
**Pull request by Entjic**
Removing lsp-less grammars as described in https://github.com/zed-industries/zed/issues/9072 to move them in seperate extensions, just a draft for now

Release Notes:

- Moved lsp-less grammars to seperate extensions ([#9072](https://github.com/zed-industries/zed/issues/9072)).

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Thank you for starting this.

Now the question is who will add and maintain more extensions into https://github.com/zed-industries/extensions because for now it appears that we remove 5 extensions from Zed code without providing an alternative?

**Comment by Entjic** [comment]
That was also what I was thinking of, I have no problem with going through the hassle to create all the required repos and add it to the extensions one, but I dont think I am the right person to maintain all these extensions..

**Comment by maxdeviant** [comment]
I think we'll want to hold off on doing this.

At least initially, the plan is to move languages to extensions that are still in the Zed repo.

**Comment by SomeoneToIgnore** [comment]
We sure can, should we do anything about the issue then? Closing it?

**Comment by maxdeviant** [comment]
> We sure can, should we do anything about the issue then? Closing it?

Yea, I don't think we need an issue for it, as this is likely something we'll want to handle ourselves.

**Comment by SomeoneToIgnore** [comment]
Sorry for the false lead @Entjic

**Pull request closed without merging**
