### PR TITLE
Add an input example to gpui

### PR DESCRIPTION
**Pull request by ConradIrwin**
Add a single-line text input example to gpui

(I'm hoping to be able to debug keyboard issues without rebuilding the whole
app every time)

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
image

**Comment by huacnlee** [comment]
@ConradIrwin Thank you for made this example.

It's saved a lot of time.

CleanShot 2024-06-27 at 15 34 23

**Comment by ConradIrwin** [comment]
Glad to be helpful! Now we just need to add mouse support to it :D

**Comment by jk-gan** [comment]
@ConradIrwin Hey, I just wanted to express my gratitude to you for the example. I've been struggling with creating text input for my app for about a week, and this has saved me a lot of time. Cheers!

**Pull request merged**
