### PR TITLE
Add Slint language and LSP

### PR DESCRIPTION
**Pull request by flukejones**
Release Notes:

- N/A

### CODE REVIEW

**Comment by flukejones** [comment]
@cla-bot check

**Comment by maxbrunsfeld** [comment]
Hey, thanks for the contribution @flukejones. We are actively working on allowing extensions to add LSP integrations, and we're going to ship an initial version soon. Because Slint is a more obscure language, I'd like to hold off on adding it into Zed core.

Subscribe to this issue for updates on our overall progress on our initial extension system: https://github.com/zed-industries/zed/issues/7096.

**Comment by flukejones** [comment]
@maxbrunsfeld I'll ask here to avoid cluttering up the linked tracking issue, can you tell me if there will be an ability for extensions to add commands to the command palette? For example a user might want to preview the slint UI they are building.

**Comment by maxbrunsfeld** [comment]
This initial implementation of extensions, which is underway right now, is going to be focused on adding support for new languages and language servers.

In the future, we'll keep expanding the extension API to let you do other types of things, but that won't ship as soon as the language stuff.

**Pull request closed without merging**
