### PR TITLE
vue: Opt in to HTML language server

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
ref: https://github.com/zed-industries/zed/pull/11761#issuecomment-2121102870

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxdeviant** [comment]
@osiewicz I'll let you take this one, as you've been handling most of the HTML language server work.

I did see that we rolled back a similar change in https://github.com/zed-industries/zed/pull/12083, so not sure if the same applies here.

**Comment by ThatOneCalculator** [comment]
I think #12083 is a bit different, since it applied to .js and .(j|t)sx files, which is a bit of a misguided choice imo. Vue has actual templates in it, so it'd be more appropriate for a plugin like this -- but I think it'd be better it could be scoped to everything inside `<template></template>`.

**Comment by ThatOneCalculator** [comment]
Drafting this as it doesn't work as expected, and I don't want to pretend like I seriously know what I'm doing when it comes to LSP extensions :woozy_face:

**Comment by osiewicz** [comment]
We've rolled it back for tsx/js as HTML language server was providing completions even outside of element context, which was kinda annoying.

**Comment by osiewicz** [comment]
> Drafting this as it doesn't work as expected, and I don't want to pretend like I seriously know what I'm doing when it comes to LSP extensions 🥴

I think you need to add HTML language server on this line as well: https://github.com/zed-industries/zed/pull/13244/files#diff-4897cd9fbe8cc8f3fc0616b061474b62776dd550c2e1a1f4ceacda4c3c4ba2abL17-R17

**Comment by maxdeviant** [comment]
Closing due to inactivity.

**Comment by cthulhua** [comment]
Does the html language server `extension.toml` need to have the language/language_id for vue too, for this to work? I tried adding the `scope_opt_in_language_servers` and `opt_into_language_servers` key for an extension I'm working on, but not dice. I noticed that the revert in #12083 removes the language/language_id's for the relevant languages.

**Pull request closed without merging**
