### PR TITLE
Filter LSP github releases that have no assets

### LINKED ISSUE #7183: Failed to download TOML LSP server
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
```console
Language server error: TOML

no asset found matching "taplo-full-darwin-aarch64.gz"
```

Related PR: #7034 

### Environment

Zed: v0.121.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by andrew-ares**
Release Notes:

- Filter lsp github releases that have no assets. Fixed #7183

### CODE REVIEW

**Comment by TENX-S** [comment]
This patch works for me:
image

The latest release of `taplo-cli` is 0.9.0:
image

Since it only contains source code assets, we fallback to downloading the older release that includes binaries.
image

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks for fixing, curious whether we should deal with name mismatches in releases, as you've noted in https://github.com/zed-industries/zed/issues/7183#issuecomment-1920665092 ?

**Comment by TENX-S** [comment]
I guess there's no simple way to deal with name mismatches. Should this patch be enough for most cases?

**Comment by SomeoneToIgnore** [comment]
The whole point that it's not enough when it breaks, and we would not know that easy.
Curious what seems so hard for this? Isn't `name` in that json supposed to end with a package name for the correct release?

But sure, let's be incremental and fix what's broken right now.

**Pull request merged**
