### PR TITLE
Fix alignment of traffic lights

### LINKED ISSUE #7339: Window Decoration Buttons Misalignment
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just a minor nitpick.
The window decoration buttons are misaligned. I compared it with other Mac apps that use the same tittle bar style. Zed to the left:
image
Zed's window buttons are a bit higher. 

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.2.0
Memory: 32 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by slymax**
closes #7339

### CODE REVIEW

**Comment by maxdeviant** [comment]
These don't seem aligned to me:

Screenshot 2024-02-21 at 11 46 33 AM

**Review by maxdeviant — CHANGES_REQUESTED** [review]
See my comment about the traffic lights being misaligned with other elements in the title bar.

**Comment by slymax** [comment]
idk looks fine on my end

Bildschirmfoto 2024-02-21 um 19 22 20

maybe this has to do with the `ui_font_size` setting

it is in the middle of the title bar, also on your screenshot

**Comment by slymax** [comment]
nvm I moved them up a bit so they look better with the default `ui_font_size` setting

Bildschirmfoto 2024-02-23 um 19 49 23

**Comment by probablykasper** [comment]
The traffic light position should just be in the middle of the title bar, don't consider the text. Though you gotta think of the window border *included* as part of the title bar. Illustration:
image

If the text looks misaligned, the text itself would need to be moved (and in that case, consider the alignment of uppercase characters and other alphabets)

**Review by maxdeviant — APPROVED** [review]
Looks better now!

**Pull request merged**
