### PR TITLE
task_ui: Move status indicator into tab bar of terminal panel

### PR DESCRIPTION
**Pull request by osiewicz**
I'm not a huge fan of this change (& I expect the placement to change). The plan is to have the button in a toolbar of terminal panel, but I'm not sure if occupying a whole line of vertical space for a single button is worth it; I suppose we might want to put more of tasks ui inside of that toolbar.
Release Notes:

- Removed task status indicator and added "Spawn task" action to terminal panel context menu.

### CODE REVIEW

**Comment by huacnlee** [comment]
Hi @osiewicz 

Do you forget to remove the `show_status_indicator` setting?

https://github.com/zed-industries/zed/blob/78f1482cd19af29dd1a1119ad562eedd73d01a34/assets/settings/default.json#L697
https://github.com/zed-industries/zed/blob/78f1482cd19af29dd1a1119ad562eedd73d01a34/crates/tasks_ui/src/settings.rs#L14

The `show_status_indicator` setting is looks like not used now.

**Comment by osiewicz** [comment]
Hey @huacnlee,
I plan to reuse the setting for a runnable file indicator; there'll be an icon just like one we had in status bar that shows tasks that apply to whole file (e.g. "run all tests in this file"). `show_status_indicator` will be thrown away, but it was still convenient for me to leave settings code in as I'm about to reuse it.

**Comment by huacnlee** [comment]
> Hey @huacnlee, I plan to reuse the setting for a runnable file indicator; there'll be an icon just like one we had in status bar that shows tasks that apply to whole file (e.g. "run all tests in this file"). `show_status_indicator` will be thrown away, but it was still convenient for me to leave settings code in as I'm about to reuse it.

Yes, we need the task icon on the status bar, that useful.

**Comment by osiewicz** [comment]
That's most likely not coming back to status bar; it's gonna be in the toolbar, next to file search toggle etc:
image

**Pull request merged**
