### PR TITLE
windows: Revert "Fix `hide`, `activate` method on Windows to hide/show application"

### PR DESCRIPTION
**Pull request by JunkuiZhang**
This PR reverts the changes introduced via #18164. As shown in the video below, once you `hide` the app, there is essentially no way to bring it back. I must emphasize that the window logic on Windows is entirely different from macOS. On macOS, when you `hide` an app, its icon always remains visible in the dock, and you can always bring the hidden app back by clicking that icon. However, on Windows, there is no such mechanism—the app is literally hidden. 

I think the `hide` feature should be macOS-only.

https://github.com/user-attachments/assets/65c8a007-eedb-4444-9499-787b50f2d1e9

Release Notes:

- N/A

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]

**Comment by huacnlee** [comment]
Both macOS and Windows have a stausBar or tray area, where there can be an App Icon, which can be restored with the help of a menu.

**Comment by JunkuiZhang** [comment]
> Both macOS and Windows have a stausBar or tray area, where there can be an App Icon, which can be restored with the help of a menu.

And `Zed` dose not support that yet, so I think let's keep it macOS-only.

**Comment by WeetHet** [comment]
> > Both macOS and Windows have a stausBar or tray area, where there can be an App Icon, which can be restored with the help of a menu.
> 
> And `Zed` dose not support that yet, so I think let's keep it macOS-only.

Yes, `Zed` does not support those, but some other app might

**Comment by huacnlee** [comment]
Yes, I am currently developing applications with GPUI and will need this feature soon. The previous `show: false` to ensure that the window does not appear was also added when it was discovered to be missing during actual development.

**Comment by JunkuiZhang** [comment]
> Yes, I am currently developing applications with GPUI and will need this feature soon. The previous `show: false` to ensure that the window does not appear was also added when it was discovered to be missing during actual development.
> 
> The case is like this:
> 
> The Shottr app was startup with hide mode, then we can use statusBar icon to restore it.
> 
>  CleanShot.2024-10-01.at.19.39.26.mp4

What I’m saying is that this reflects a fundamental difference between macOS and Windows. I know you're very familiar with macOS, and on Windows, some apps offer similar functionality to what you mentioned with `Shottr`, like Steam or Zoom. But on Windows, everything is window-based—hence the name "Windows". Apps like Steam typically don’t offer a “hide this app” command; instead, when you close all windows, the app stays running in the system tray, and that’s it.

On macOS, it absolutely makes sense for `gpui` to provide a "hide this app" feature because you can always bring hidden apps back easily. However, on Windows, as I showed in my video, if the app isn't registered in the system tray, it effectively "disappears." This behavior feels quite unintuitive from a Windows user’s perspective.

**Pull request merged**
