### PR TITLE
vim: Fix `g _` not having the expected behavior

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Release Notes:

- N/A

### CODE REVIEW

**Comment by CharlesChen0823** [comment]
Current CI failed in vim::surround `test_add_surronds` test case, but I think this case is might wrong? If this is expect behaviour ? so keep draft.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 It looks like the test matches the behavior of vim-surround, so we should probably keep the test passing.

Do you have a test-case for the `g_` fix?

**Comment by CharlesChen0823** [comment]
@ConradIrwin I checked vim-surround, the test case in [here](https://github.com/zed-industries/zed/blob/3cd6719b3003d9ae7642b6aba7fc8a845620fa06/crates/vim/src/surrounds.rs#L643) should be `{ The quick brown• }` current behaviour is wrong.

**Comment by ConradIrwin** [comment]
@CharlesChen0823 The • represents a trailing newline, not a literal • - sorry for not clarifying that.

Can you please add a test for the `g_` edge case you are trying to fix too.

**Comment by CharlesChen0823** [comment]
@ConradIrwin add test case, I though `test_add_surronnds` case failed is might other reason.

**Comment by ConradIrwin** [comment]
I think you ran into a long-standing nastiness with how vim mode is implemented:

* To ensure that in normal mode the [] block cursor never exceeds the end of the line, in normal mode we prevent the cursor landing on the true line end.
* This causes `end_of_line` on a line like "hello\n" to return either "hello|\n" or "hell|o\n" depending on implicit state

I've pushed a fix that should support both cases correctly; but I do want to refactor how that clipping is done to avoid having to think about it all the time in cases like this.

**Pull request merged**
