### PR TITLE
Fix file watching for symlinked workspace on Linux

### LINKED ISSUE #17161: Symlink as workspace root breaks file watching
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, if I make a new file or directory outside of the editor (like by downloading one with `curl`, or if my program makes a config file, etc), it does not appear in the editor's file view until I restart the program. Not sure whether this is a bug or would be a new feature.

If it's a bug, I'm having the issue on Linux, on past versions, and the current one in the Arch repos (0.150.4)

### Environment

Edit: I tried this on two machines, with two different versions of Zed, but I'm now up-to-date on both. The old version (0.149.5) was not the issue, I just hadn't updated on the machine I originally posted this from.

Zed: v0.150.4 (Zed)
OS: Linux Wayland arch 20240721.0.248532
Memory: 31 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6800 (RADV NAVI21) || radv || Mesa 24.2.1-arch1.1

### Zed Log

<details><summary>Zed.log</summary><pre>
with error: failed to connect to the server
2024-09-02T12:32:22.070436438+01:00 [ERROR] ignoring event "/home/user/Downloads/test/test" outside of root path "/home/user/test"
2024-09-02T12:32:25.165355705+01:00 [INFO] Using surface present mode MAILBOX
</pre></details>

### PR DESCRIPTION
**Pull request by tancop**
- Closes #17161

- #17609 only fixed file watching for symlinks inside the workspace, not if the folder itself or one of its parents is a symlink. This PR replaces uses of `read_link` with `canonicalize` that returns the right canonical path in these cases. 

Release Notes:

- Fixed file watching for symlinked workspaces on linux

### CODE REVIEW

**Comment by tancop** [comment]
@cla-bot check

**Comment by tancop** [comment]
@notpeter I rebased and fixed the failing tests, should check for rename events not just delete. Can you run CI again?

**Comment by tancop** [comment]
@ConradIrwin

**Comment by notpeter** [comment]
I actually was in this code this morning as part of this (adjacent, but unrelated):
- https://github.com/zed-industries/zed/issues/17831

**Comment by tancop** [comment]
All tests passed, do you think this is ready for merge?

**Comment by tancop** [comment]
@maxdeviant

**Comment by ConradIrwin** [comment]
@tancop sorry for the glacial response here!

The change to canonicalize before calling watch makes sense to me; do we also need to canonicalize on every filesystem event? It sounded like from your description on the issue that we were already getting canonical paths in that situation?

**Comment by tancop** [comment]
@ConradIrwin I rebased on the fs refactor and skipped canonicalize unless the root path is a symlink or the event path we got from notify doesn't match. Not exactly elegant but it works

**Comment by ConradIrwin** [comment]
@tancop Thanks!

Why is that needed? It sounded like from your earlier notes that we already got canonical paths from the notify events?

Can you also help me nail down the reproduction steps please: https://github.com/zed-industries/zed/issues/17161#issuecomment-2460956085

**Comment by tancop** [comment]
@ConradIrwin delete and rename events can return non canonical paths because the file doesn't exist anymore so notify can't canonicalize it internally. Same thing happens when the root directory is a descendant of a symlink for whatever reason, I tried to remove that check but it broke.

For the reproduction steps:
- Create a directory
- Create a symlink to that directory
- Open the symlink in Zed
- Create a file in the original directory outside of Zed (touch, vscode, file manager)
- Zed doesn't detect the file

**Comment by tancop** [comment]
@ConradIrwin do i also need to change repro steps on the issue?

**Comment by ConradIrwin** [comment]
@tancop I feel like I'm missing something obvious, but I cannot reproduce this problem as you describe....
[Screencast from 2024-11-19 08-46-42.webm](https://github.com/user-attachments/assets/cb6db9af-ed23-43b5-a990-6e710c108eb2)

Is there something different about our setups, or is there something else I need to do to get into the broken state?

**Comment by tancop** [comment]
@ConradIrwin I tested it with your commands and everything works that way. It breaks when I open the same folder with the *recents picker* inside zed so the real issue might be in there.

**Pull request closed without merging**
