### PR TITLE
Allow git blame tooltip emails to open mail client

### PR DESCRIPTION
**Pull request by JosephTLyons**
https://github.com/zed-industries/zed/assets/19867440/fe5025cd-6cbd-4c40-b8a0-8f548f3221a1

This matches what GitLense offers in VS Code.

Release Notes:

- Added clickable links to git blame tooltip to open system email client.

### CODE REVIEW

**Comment by JosephTLyons** [comment]
@mrnugget, this cool with you?

**Comment by maxdeviant** [comment]
Can this be a setting?

I _never_ want to open my email client.

**Comment by maxdeviant** [comment]
> Can this be a setting?
> 
> I _never_ want to open my email client.

Although I think I would argue that clicking on the email should copy it to the clipboard instead of opening anything.

Even on the web `mailto:` is considered to be bad practice for tools.

**Comment by JosephTLyons** [comment]
I've not heard that it is considered bad practice. I thought it was a cross-compatible protocol, so I felt it was safe. Looking into other editors:

- Xcode: Opens the default mail client.
- JetBrains IDEs: Opens the default email client. 
- VS Code: I don't think it ships with blame support, but with the most popular Git extension installed (GitLens), it opens up the default mail client.
- Sublime Text: Doesn't ship with blame support, the extensions I checked don't seem to offer either copy to clipboard or opening of default browser.
- Sublime Merge: has option to copy to clipboard, doesn't open the default mail client.

I'm not really against it simply copying to the clipboard, but at the same time, I'm not able to see how this is different from any of our other buttons that automatically open a link in a default browser - this behavior feels identical to that to me. Curious to hear what others think - is this bad / acceptable behavior?

**Comment by maxdeviant** [comment]
> I've not heard that it is considered bad practice. I thought it was a cross-compatible protocol, so I felt it was safe. Looking into other editors:
> 
> * Xcode: Opens the default mail client.
> * JetBrains IDEs: Opens the default email client.
> * VS Code: I don't think it ships with blame support, but with the most popular Git extension installed (GitLens), it opens up the default mail client.
> * Sublime Text: Doesn't ship with blame support, the extensions I checked don't seem to offer either copy to clipboard or opening of default browser.
> * Sublime Merge: has option to copy to clipboard, doesn't open the default mail client.
> 
> I'm not really against it simply copying to the clipboard, but at the same time, I'm not able to see how this is different from our other buttons that automatically open a link in a default browser - this behavior feels identical to that to me. Curious to hear what others think - is this bad / acceptable behavior?

In my case I don't use the built-in email client, so anytime I click a `mailto:` link—typically by accident—I'm immediately greeted by the built-in Mail app, which is never what I want.

When this happens, I get frustrated and immediately have a bone to pick with whatever site/app put me in that position.

I don't think I'm the only developer who would feel this way if Zed were to open an email client they don't use by accidentally clicking on an email address.

In fact, in Zed using a `mailto:` is even _worse_ than on the web because you can't hover over the link in advance to see that it's a `mailto:`.

So I feel pretty strongly that this either needs to be configurable (so I can turn it off) or that we copy to clipboard as a safe default.

**Comment by ConradIrwin** [comment]
I would tend to agree with @maxdeviant here, that the action of "I want to email this committer" is likely so rare that it'll happen more often than on purpose.

Copy to clipboard seems like a saner default, otherwise I'd suggest we link to their Github profile. (Or just do nothing, as in command-line git :D).

**Comment by mrnugget** [comment]
Agree with @maxdeviant too, as a very-long-time user of the Gmail web interface. I never want `mailto:` to open my email client on my OS. But I think copy-to-clipboard would be a good alternative. (Even though I never in my life have wanted to send an email to a committer)

**Comment by JosephTLyons** [comment]
> ... Even though I never in my life have wanted to send an email to a committer

Weirdly enough, I've never done this until recently (wanted to email an old college friend after looking at an old class project), which is what prompted me to look into this.

Let's close this for now - appreciate the opinions.

**Pull request closed without merging**
