### PR TITLE
rust: update rust-analyzer repo addr

### PR DESCRIPTION
**Pull request by bestgopher**
Release Notes:

- (Added|Fixed|Improved) ... ([#<public_issue_number_if_exists>](https://github.com/zed-industries/zed/issues/<public_issue_number_if_exists>)).

### CODE REVIEW

**Comment by bestgopher** [comment]
@cla-bot check

**Comment by mrnugget** [comment]
Hey @bestgopher — since `rust-analyzer/rust-analyzer` redirects to the new URL, was something broken? Or what's the reason for the change?

**Comment by matklad** [comment]
`rust-analyzer/rust-analyzer` probably will work forever, but `rust-lang/rust-analyzer` is the official new home, and one redirect (and a netwrok round-trip) less.

**Comment by mrnugget** [comment]
I was just wondering whether we don't follow redirects in Zed and whether something was broken, i.e. what the cause for this change was. Renaming it to the official new home makes sense.

@bestgopher CI complains that the formatting is off, can you fix that?

**Pull request closed without merging**
