### PR TITLE
Use frequency to sort entries in the command palette

### LINKED ISSUE #8107: command palette entries should be sorted by recency not usage
### Check for existing issues

- [X] Completed

### Describe the feature

This would match VSCode behavior, not sure about other editors. I understand there's no behavior that would satisfy everybody, but this would at least help with a common use case: running the same command repeatedly.

I guess one option would be to keep the usage count ordering only when filtering, if https://github.com/zed-industries/zed/issues/8106 is fixed.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by knyazer**
Closes #8107 #8106

Release Notes:

- Added consistent sorting of entries by frequency and recency in the command palette

---
Besides, fixed some minor issues with aliases (like delete) not participating in the command sorting.

### CODE REVIEW

**Comment by knyazer** [comment]
@cla-bot check

**Comment by knyazer** [comment]
Btw, I don't use the original frecency algo, because as noted [here](https://web.archive.org/web/20210412040826/https://wiki.mozilla.org/User:Mconnor/Past/PlacesFrecency), the reason not to use a continuous metric (like I did) is that recomputing it for every entry is too slow. In our case, the number of entries is like at most a few hundred, so there is no reason to not sort them on every request.

As soon as speed becomes an issue we can switch to the bucket-style algorithm with caching, but for now lets not do any premature optimizations :)

**Comment by knyazer** [comment]
Didn't notice there was a typos check... Now should be fine, I believe

**Comment by as-cii** [comment]
Thanks for this pull request, @knyazer!

Could you share some before/after examples that make it clear how the behavior is changing, and how the new behavior is better? 

Also, it seems like we wanted to match how VS Code works (which I think would be a valid reason for implementing this) so I'd appreciate comparing this approach to how they do it.

Thank you!

**Comment by knyazer** [comment]
Alright, so VSCode just uses MRU + a bunch of custom rules (most recently used, from [here](https://github.com/microsoft/vscode/blob/d9199ab0a6dddbcdcaf4381bf00288167ee4583b/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L140)). Also, in vscode the cache is persistent, while in my implementation the cache is not stored between different launches of zed.

My approach, is somewhat similar to vscode's one, but I also count command frequency, and weight it quite a bit: e.g. VSCode always places the last used command on the top, while my method would sometimes place old, but more frequently used command higher. For example, if one used command "A" three times an hour ago, and the command "B" just now, command "A" would rank higher, according to my decay function. I wrote the comments explaining hyperparameters, so if you feel like it is too much/too little, feel free to change them.

_The best way to figure the decay factor out is to look at user's data, and then just fit this factor to minimize the number of keystrokes a user would need to make, but I don't think this is that important_

In general, it's hard to make a comprehensive video as an illustration: since the video is short, any visualisation would look just like I'm using "most recently used" - there is just not enough time passing to see any difference

**Comment by knyazer** [comment]
Yeah, another weird decision that I make (actually, the most weird decision that I make, the main algorithm is just continuous-time equivalent of Mozilla frecency) is I multiply the final score for a completion by how well it matches the request. This adds one more degree of freedom (e.g. how much do we care about matching the suggested command well), but in general it gives a pretty low priority to matching well: I haven't actually tested it a ton, but I'm pretty sure this is only useful when there are two distinct but similar very commonly used commands, and only then this scaling would play a role

**Comment by as-cii** [comment]
Thanks for the thorough explanation, @knyazer! 🙇‍♂️  

I am somewhat worried about performance. Storing one `Vec<Hit>` per command in that `HashMap` seems inefficient for a couple of reasons:

1. It seems like that vector will keep growing as more actions get dispatched. Older entries will play a marginal role in the scoring.
2. When sorting results, any comparison between two command palette matches will incur the cost of scanning a vector of hits for each match, which feels expensive. 

Given that I am also somewhat unclear on how this will feel when using it, how would you feel about landing a pull request that replicates the exact behavior as VS Code? I'd be happy to merge that and it seems like it should lead to a more straightforward/faster implementation overall.

**Pull request closed without merging**
