### PR TITLE
tab_switcher: Use git-aware colors for file icons

### PR DESCRIPTION
**Pull request by Daste745**
Release Notes:

- Fixed tab switcher icons not respecting the `tabs.git_status` setting.

Fixes an issue mentioned in https://github.com/zed-industries/zed/pull/17115#issuecomment-2378966170 - file icons in the tab switcher weren't colored according to git status, even if  `tabs.git_status` was set to true.

|Before (icons have the default color)|After (icons use git status colors)|
|:--:|:--:|
|before|after|

I used a similar approach I saw in other places of the project to get the project entry and its git status, but maybe we could move the coloring logic entirely to `tab_icon()`? Wouldn't this break anything?

### CODE REVIEW

**Comment by maxdeviant** [comment]
> I used a similar approach I saw in other places of the project to get the project entry and its git status, but maybe we could move the coloring logic entirely to `tab_icon()`? Wouldn't this break anything?

I don't think that will be possible, as it means that `workspace` would need to depend on `project`.

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by iamnbutler** [comment]
Thanks for the contribution! 

If you get a chance in the future to contribute, it would be great if you can add a before/after screenshot so folks can reference it as needed 🙂

**Comment by Daste745** [comment]
> If you get a chance in the future to contribute, it would be great if you can add a before/after screenshot so folks can reference it as needed 🙂

For sure, I edited my original comment to include a before and after comparison. I forgot about them as this was a quick and small change. Thanks for the heads up!

**Pull request merged**
