### PR TITLE
Truncate line when accepting inline suggestions for Supermaven

### LINKED ISSUE #13039: Supermaven is unusable in zed
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in vscode supermaven suggest completions at the end of the line and when you hit tab **it replaces the whole line to the end**.

https://github.com/zed-industries/zed/assets/30318777/450b5cfd-dffa-44b5-a750-f163aacc90f9

but in zed suggestions is displayed in the middle of the line where the cursor at and when you hit tab **it only inserts in the middle**

https://github.com/zed-industries/zed/assets/30318777/15813669-5b8d-4626-8f8c-f9592974f3d1

**this ergonomic issue makes supermavan unusable in zed because supermaven suggestions are too fast and my code jumps all the time**

### Environment

Zed: v0.141.0 (Zed Nightly 124878878069a0aa52e97e531fef22fbef43e12f)
OS: macOS 14.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by kevmo314**
Configures inline completions to delete the remaining text on the given line. This doesn't affect the github copilot inline completion provider since it seems to only generate suggestions if the cursor is at the end of the line but fixes the usability issues related to Supermaven.

https://github.com/user-attachments/assets/1b8bc9a3-4666-4665-a436-96e4beee01bb

Release Notes:

- Fixed https://github.com/zed-industries/zed/issues/13039

### CODE REVIEW

**Comment by kevmo314** [comment]
@cla-bot check

**Comment by kynnyhsap** [comment]
@kevmo314 i think you put the wrong video in the description. it doesn't really show anything

**Comment by kevmo314** [comment]
> @kevmo314 i think you put the wrong video in the description. it doesn't really show anything

I've updated the screen recording, not sure what happened there.

**Comment by kevmo314** [comment]
> That would avoid this weird completion state:

I don't quite follow how that would work. In your screenshot, the completion text ends with `...newline(&completion_text);` but the active buffer is `(completion_text);`. This wouldn't match based on the code you've written?

We can't really guarantee the suffix matches at any regular cadence although @super-jacob can speak more to that probably. Returning an `Option<Range<Anchor>>` sounds good though if that works for you.

**Comment by kevmo314** [comment]
Ah, I suppose it would match `completion_text);` but I'm not completely sure it's the best idea to rely on the suffix being present...

**Comment by ConradIrwin** [comment]
🤦 How did I miss that :D.

Let's go with the range approach for now then.

**Comment by tomaswarynyca** [comment]
@kevmo314 can you please resolve conflicts?

**Comment by kevmo314** [comment]
@ConradIrwin I've been stuck on this for a bit, how do I get the end of the line in the `active_completion_text` function with only access to the `cursor_position: Anchor` and `buffer: &Model<Buffer>`? In the current verison I can do `display_map.next_line_boundary()` but going through the buffer code no such equivalent function seems to exist. I thought it might be something like what `next_line_boundary()` is doing but `Buffer::line_len()` takes a `row: u32` and `cursor_position: Anchor` doesn't seem to contain that information, only the byte offset in the buffer itself.

**Comment by ConradIrwin** [comment]
You should be able to do something like this:
```
        let snapshot = buffer.read(cx).snapshot();
        let mut point = cursor_position.to_point(&snapshot);
        point.column = snapshot.line_len(point.row);
        let range = cursor_position..snapshot.anchor_after(point);
```

If you want to pair on getting this over the line:  https://calendly.com/conradirwin/pairing

**Comment by WeetHet** [comment]
> Ah, I suppose it would match `completion_text);` but I'm not completely sure it's the best idea to rely on the suffix being present, wouldn't that edit end up with `...newline(&completion_text);(` if accepted?

What if instead we do not just a suffix comparison, but a full-on diff and show it instead?

**Comment by WeetHet** [comment]
Something like this:
result

**Comment by kevmo314** [comment]
> Something like this: result
> 
> cc @ConradIrwin

This seems like the right direction but orthogonal to this change? In particular, to apply this diff one would need to implement the line truncation/deletion range behavior still.

**Comment by WeetHet** [comment]
> > Something like this: result
> > cc @ConradIrwin
> 
> This seems like the right direction but orthogonal to this change? In particular, to apply this diff one would need to implement the line truncation/deletion range behavior still.
Can we implement them together? I think it would be best for everyone

**Comment by kevmo314** [comment]
> > > Something like this: result
> > > cc @ConradIrwin
> > 
> > 
> > This seems like the right direction but orthogonal to this change? In particular, to apply this diff one would need to implement the line truncation/deletion range behavior still.
> 
> Can we implement them together? I think it would be best for everyone

I'd like to figure out this PR first in its current scope because it's blocking the use of Supermaven in Zed all together. The rendering seems worthwhile but doesn't really block the use of Supermaven.

**Comment by kevmo314** [comment]
@ConradIrwin I got the build working with the anchors approach. Works now :)

https://github.com/user-attachments/assets/71375494-abd1-464e-ade9-272c8608de93

**Comment by ConradIrwin** [comment]
@kevmo314 awesome! I just pushed up some cleanup to reduce the change in the editor crate. Will merge when green.

**Comment by rgbkrk** [comment]
✅

**Pull request merged**
