### PR TITLE
Update Blade with acquire fixes, multisampling

### LINKED ISSUE #22406: SIGSEGV (Address boundary error) with dwm
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using a window manager (dwm) and this crash occurs when window is moved to another workspace and resized.
I think this may be somewhat hardware specific since I don't experience this on my other pc.

I've also created a backtrace for debugging, I'm unsure if this issue is even related to zed - it looks more like `blade` or `ash` crate issue.

```
~/work/builds/zed ❯❯❯ rust-gdb target/debug/zed
GNU gdb (GDB) 15.2
Reading symbols from target/debug/zed...
(gdb) run
Starting program: /home/sebba/work/builds/zed/target/debug/zed
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Thread 1 "zed" received signal SIGSEGV, Segmentation fault.
0x00007fffa6158323 in ?? () from /usr/lib/libnvidia-glcore.so.565.77
(gdb) backtrace
#0  0x00007fffa6158323 in ?? () from /usr/lib/libnvidia-glcore.so.565.77
#1  0x00007fffa6165a50 in ?? () from /usr/lib/libnvidia-glcore.so.565.77
#2  0x00007fffa622d6a8 in ?? () from /usr/lib/libnvidia-glcore.so.565.77
#3  0x0000555565caf2bf in ash::device::Device::cmd_pipeline_barrier () at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ash-0.38.0+1.3.281/src/device.rs:2380
#4  0x0000555565c73ce4 in blade_graphics::hal::command::{impl#18}::init_texture () at src/vulkan/command.rs:505
#5  0x0000555565c74046 in blade_graphics::hal::CommandEncoder::init_texture () at src/vulkan/command.rs:431
#6  0x0000555564ad6aaf in gpui::platform::blade::blade_renderer::BladeRenderer::draw () at crates/gpui/src/platform/blade/blade_renderer.rs:534
#7  0x0000555564f2117e in gpui::platform::linux::x11::window::{impl#12}::draw () at crates/gpui/src/platform/linux/x11/window.rs:1368
#8  0x00005555649c50b4 in gpui::window::WindowContext::present () at crates/gpui/src/window.rs:1497
#9  0x0000555564f2506e in gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure#0} () at crates/gpui/src/window.rs:707
#10 0x0000555564988b70 in gpui::app::{impl#5}::update_window::{closure#0}<(), gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure_env#0}> () at crates/gpui/src/app.rs:1504
#11 0x0000555564978b91 in gpui::app::AppContext::update<core::result::Result<(), anyhow::Error>, gpui::app::{impl#5}::update_window::{closure_env#0}<(), gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure_env#0}>> () at crates/gpui/src/app.rs:418
#12 0x000055556497df27 in gpui::app::{impl#5}::update_window<(), gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure_env#0}> () at crates/gpui/src/app.rs:1495
#13 0x000055556497111b in gpui::app::async_context::{impl#0}::update_window<(), gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure_env#0}> ()
    at crates/gpui/src/app/async_context.rs:91
#14 0x0000555564f4e966 in gpui::window::AnyWindowHandle::update<gpui::app::async_context::AsyncAppContext, (), gpui::window::{impl#19}::new::{closure#4}::{closure#1}::{closure_env#0}> ()
    at crates/gpui/src/window.rs:4838
#15 0x0000555564f2500b in gpui::window::{impl#19}::new::{closure#4}::{closure#1} () at crates/gpui/src/window.rs:704
#16 0x00005555649397dc in util::measure<(), gpui::window::{impl#19}::new::{closure#4}::{closure_env#1}> () at crates/util/src/util.rs:300
#17 0x0000555564f24d68 in gpui::window::{impl#19}::new::{closure#4} () at crates/gpui/src/window.rs:703
#18 0x0000555564f9d045 in alloc::boxed::{impl#49}::call_mut<(gpui::platform::RequestFrameOptions), dyn core::ops::function::FnMut<(gpui::platform::RequestFrameOptions), Output=()>, alloc::alloc::Global> () at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2077
#19 0x0000555564f1b4d7 in gpui::platform::linux::x11::window::X11WindowStatePtr::refresh () at crates/gpui/src/platform/linux/x11/window.rs:928
#20 0x0000555564ac501c in gpui::platform::linux::x11::client::X11Client::process_x11_events () at crates/gpui/src/platform/linux/x11/client.rs:549
#21 0x00005555649a4e46 in gpui::platform::linux::x11::client::{impl#8}::open_window::{closure#1} () at crates/gpui/src/platform/linux/x11/client.rs:1377
#22 0x0000555564fa7156 in calloop::sources::{impl#4}::process_events::{closure#0}<gpui::platform::linux::x11::client::X11Client, calloop::sources::timer::Timer, gpui::platform::linux::x11::client::{impl#8}::open_window::{closure_env#1}> () at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/sources/mod.rs:327
#23 0x0000555564fdc3c6 in calloop::sources::timer::{impl#1}::process_events<calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::x11::client::X11Client, calloop::sources::timer::Timer, gpui::platform::linux::x11::client::{impl#8}::open_window::{closure_env#1}>> ()
    at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/sources/timer.rs:122
#24 0x0000555564d6b8e4 in calloop::sources::{impl#4}::process_events<gpui::platform::linux::x11::client::X11Client, calloop::sources::timer::Timer, gpui::platform::linux::x11::client::{impl#8}::open_window::{closure_env#1}> () at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/sources/mod.rs:326
#25 0x0000555564946594 in calloop::loop_logic::EventLoop::dispatch_events<gpui::platform::linux::x11::client::X11Client> ()
    at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/loop_logic.rs:445
#26 0x0000555564952be1 in calloop::loop_logic::EventLoop::dispatch<gpui::platform::linux::x11::client::X11Client, core::option::Option<core::time::Duration>> ()
    at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/loop_logic.rs:559
#27 0x0000555564950e97 in calloop::loop_logic::EventLoop::run<gpui::platform::linux::x11::client::X11Client, gpui::platform::linux::x11::client::{impl#8}::run::{closure_env#0}, core::option::Option<core::time::Duration>> () at /home/sebba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/loop_logic.rs:596
#28 0x0000555564ad1adf in gpui::platform::linux::x11::client::{impl#8}::run () at crates/gpui/src/platform/linux/x11/client.rs:1527
#29 0x00005555649972f9 in gpui::platform::linux::platform::{impl#1}::run<gpui::platform::linux::x11::client::X11Client> () at crates/gpui/src/platform/linux/platform.rs:146
#30 0x000055555ac5c162 in gpui::app::App::run<zed::main::{closure_env#5}> () at crates/gpui/src/app.rs:166
#31 0x000055555ad8620e in zed::main () at crates/zed/src/main.rs:289
```

### Environment

Zed: v0.168.0 (Zed Dev 45c714110e5c5d966853d7cd04efc9068a926179)
OS: Linux X11 arch unknown
Memory: 31 GiB
Architecture: x86_64
GPU: Quadro P1000 || NVIDIA || 565.77

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by kvark**
Fixes #22406

Picks up:
- https://github.com/kvark/blade/pull/234 and https://github.com/kvark/blade/pull/237 (`OutOfDate` workaround)
- https://github.com/kvark/blade/pull/229 ("metal-rs" to "objc2" migration)

Release Notes:

- Improved handling of resizing and multiple monitors in Linux/Windows

### CODE REVIEW

**Comment by s3bba** [comment]
@kvark Thanks for a quick response on the issue, I tested this PR and SIGSEGV is gone but window never renders and this appears in the logs: `[2024-12-25T09:22:59+01:00 ERROR gpui::platform::blade::blade_renderer] GPU hung`

**Comment by kvark** [comment]
@s3bba this is very helpful, thank you! Would you be able to test with Vulkan validation enabled? If you have the relevant packages installed in the system, enabling validation can be done through this flag - https://github.com/zed-industries/zed/blob/1a9f0a647a70623392faf0ad8d7b1732481e1fb1/crates/gpui/src/platform/blade/blade_context.rs#L15

**Comment by s3bba** [comment]
Yeah, I'm around for few more hours today so we can try to debug this - here is the output with validation enabled, compiled with: `RUSTFLAGS="-Ctarget-cpu=native" cargo build --profile release-fast`

```
[2024-12-25T09:57:04+01:00 INFO  gpui::platform::linux::x11::client] Refreshing at 16666 micros
[2024-12-25T09:57:04+01:00 INFO  gpui::platform::linux::x11::window] x11: no compositor present, falling back to server-side window decorations
[2024-12-25T09:57:04+01:00 INFO  zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Quadro P1000", driver_name: "NVIDIA", driver_info: "565.77" }
[2024-12-25T09:57:04+01:00 INFO  blade_graphics::hal::resource] Creating texture 0x64eade8eb0a0 of size 1024x1024x1 and format R8Unorm, name 'atlas', handle 1
[2024-12-25T09:57:04+01:00 INFO  blade_graphics::hal::resource] Creating buffer 0x64eade8ec5d0 of size 65536, name 'chunk-0', handle 2
[2024-12-25T09:57:04+01:00 INFO  blade_graphics::hal::resource] Creating buffer 0x64eade8d4a70 of size 4096, name 'chunk-0', handle 3
[2024-12-25T09:57:04+01:00 INFO  blade_graphics::hal::resource] Creating buffer 0x64eade87d220 of size 6272, name 'chunk-1', handle 4
[2024-12-25T09:57:04+01:00 WARN  blade_graphics::hal::command] GPU frame is out of date
[2024-12-25T09:57:04+01:00 WARN  blade_graphics::hal::surface] Acquire failed because the surface is out of date
[2024-12-25T09:57:04+01:00 WARN  blade_graphics::hal::command] GPU frame is out of date
[2024-12-25T09:57:14+01:00 ERROR gpui::platform::blade::blade_renderer] GPU hung
```

**Comment by kvark** [comment]
@s3bba thank you! It doesn't look like Vulkan Validation was activated, or it just didn't detect anything wrong.
In any case, I figured another thing that could go wrong there and merged a fix in https://github.com/kvark/blade/pull/237
This PR is now picking it up as well. If you can check the latest of this PR, that would be great!

**Comment by s3bba** [comment]
@kvark Can confirm, the GPU hang error is gone and I haven't fond any new issues. Thank you!

**Comment by kvark** [comment]
@ConradIrwin let's get this in?

**Comment by ConradIrwin** [comment]
👍

**Pull request merged**
