### PR TITLE
Fix selection extend/shrink on JetBrains keymap

### PR DESCRIPTION
**Pull request by trin94**
JetBrains IDE's use `ctrl-w` and `ctrl-shift-w` on Win/Linux and `cmd-up` and `cmd-down` on mac to extend/shrink selections.

https://www.jetbrains.com/guide/java/tips/extend-selection/

Release Notes:

- Fixed extend/shrink selection on JetBrains keymap

### CODE REVIEW

**Comment by trin94** [comment]
@cla-bot check'

**Comment by notpeter** [comment]
Curious what keystrokes are used for closing a window if `ctrl-w` and `ctrl-shift-w` are unavailable. `ctrl-f4`?

**Comment by trin94** [comment]
Yes, `ctrl-f4` is correct.

**Comment by notpeter** [comment]
Thanks! And congrats on your first contribution!

**Comment by hedblad** [comment]
@notpeter I think there's been a mistake here. It should still be `alt-up` and `alt-down` for MacOS.

 As it says in [the link ](https://www.jetbrains.com/guide/java/tips/extend-selection/)you provided:
> Press ⌥↑ (macOS)

⌥ is the option key on mac, which is what alt is called on Mac. See the [Zed docs](https://zed.dev/docs/key-bindings#keybinding-syntax) for more info.

**Pull request merged**
