### PR TITLE
gpui: img element object-fit

### PR DESCRIPTION
**Pull request by MatthiasGrandl**
Release Notes:

- N/A

### CODE REVIEW

**Comment by MatthiasGrandl** [comment]
@cla-bot check

**Comment by MatthiasGrandl** [comment]
> Corner Radius doesn't work when the image is overflowing the bounds.


I guess the corner_radii not working seems more like an unrelated bug in GPUI and I would say it's probably out of the scope of this PR.

**Comment by MatthiasGrandl** [comment]
Ok I have an idea how to fix the corner_radii issue.

**Comment by MatthiasGrandl** [comment]
I adjusted both metal and blade shaders to fix the corner_radius not working on overflowing elements. I didn't observe any unintended side effects.

**Review by mikayla-maki — APPROVED** [review]
Nice!

**Pull request merged**
