### PR TITLE
docs: Fix default value for `relative_line_numbers` in vim

### PR DESCRIPTION
**Pull request by 5brian**
image

Changes:
`true` to `false`

Reasoning:
matches zed default settings as well as the settings changes portion of the vim docs

image

image

Release Notes:
- N/A

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Unfortunately, our CLA bot is broken, so I have to substitute for it for a while: 

> We require contributors to sign our Contributor License Agreement, and we don't have @yoleuh on file. You can sign our CLA at https://zed.dev/cla. Once you've signed, post a comment here that says '@cla-bot check'.

**Comment by yoleuh** [comment]
oh sorry, forgot about that

**Comment by yoleuh** [comment]
@cla-bot check

**Comment by yoleuh** [comment]
just added Release Notes

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!

**Pull request merged**
