### PR TITLE
WIP: Add swipe to navigate back/forward on macOS

### PR DESCRIPTION
**Pull request by seivan**
Release Notes:

- Fix: 
- [#4954 ](https://github.com/zed-industries/zed/issues/4954)

I need some help on the final part where I need access to `Workspace` to trigger `go_back` or `go_forward`

```rust
        let observer_for_gesture_swipe = cx.observe_gesture_swipe(|this, direction, cx| {
            this.update(cx, |workspace, mut cxx| async {
                workspace
                    .go_back(workspace.active_pane().downgrade(), cxx)
                    .await;
            })
            .unwrap();
            println!("direction: {:?}", direction);
        });
```

The error is 

```rust
the method `update` exists for mutable reference `&mut Workspace`, but its trait bounds were not satisfied
the following trait bounds were not satisfied:
`&mut Workspace: Iterator`
which is required by `&mut Workspace: Itertools`
`&&mut Workspace: Iterator`
which is required by `&&mut Workspace: Itertools`
`&mut &mut Workspace: Iterator`
which is required by `&mut &mut Workspace: Itertools`
`Workspace: Iterator`
which is required by `Workspace: Itertools`
`&Workspace: Iterator`
which is required by `&Workspace: Itertools`
items from traits can only be used if the trait is implemented and in scope.
```

I am not exactly sure how to go about it, my suspicion is that there's something messed up earlier before the observer being triggered, maybe I'm not passing the right types: 

```rust
    pub fn observe_gesture_swipe(
        &mut self,
        mut callback: impl FnMut(&mut V, &NavigationDirection, &mut ViewContext<V>) + 'static,
    ) -> Subscription {
        let view = self.view.downgrade();

        let (subscription, activate) = self.window.gesture_swipe_observer.insert(
            (),
            Box::new(move |direction, cx| {
                view.update(cx, |view, cx| callback(view, direction, cx))
                    .is_ok()
            }),
        );
        activate();
        subscription
    }
```

### CODE REVIEW

**Comment by seivan** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@seivan You should not need the workspace.update in that scenario as the listener does it for you.

If you want to pair on getting this over the line: https://calendly.com/conradirwin/pairing

**Comment by ConradIrwin** [comment]
I'm going to close this for now, but the offer of pairing on it still stands!

**Comment by seivan** [comment]
@ConradIrwin continuing in #36574 - this time it actually works, sorry for the delay.

**Comment by ConradIrwin** [comment]
Great! Looks like Mikayla's on it :D

**Pull request closed without merging**
