### PR TITLE
Add Mistral language model provider

### PR DESCRIPTION
**Pull request by seddonm1**
Mistral is basically the same as OpenAI so this code copies heavily from it. Currently Codestral is under a free developer period to allow integration to tools like Zed.

Currently requires definition like;

```json
  "language_models": {
    "mistral": {
      "api_url": "https://codestral.mistral.ai/v1",
      "available_models": ["codestral"]
    }
  },
```

Release Notes:

- Added Mistral Codestral support.

### CODE REVIEW

**Comment by seddonm1** [comment]
@cla-bot check

**Comment by mrnugget** [comment]
I'll defer to @nathansobo and @as-cii here, but I'd say that right now we're reworking a lot of things around our language model providers and models, and having yet another provider might make things harder. I'd personally would hold off adding another one until in ~3-4 weeks when the dust settles.

**Comment by seddonm1** [comment]
No worries. Feel free to close it and it can easily be redone. Perhaps a way to proxy through ollama is the answer?

**Comment by maxdeviant** [comment]
> I'll defer to @nathansobo and @as-cii here, but I'd say that right now we're reworking a lot of things around our language model providers and models, and having yet another provider might make things harder. I'd personally would hold off adding another one until in ~3-4 weeks when the dust settles.

Agreed with that.

Additionally, since this PR is adding it to zed.dev there needs to be an internal discussion about whether we want to provide access to Mistral the same way we will be doing for other model providers.

**Comment by shishkin** [comment]
> I'll defer to @nathansobo and @as-cii here, but I'd say that right now we're reworking a lot of things around our language model providers and models, and having yet another provider might make things harder. I'd personally would hold off adding another one until in ~3-4 weeks when the dust settles.

@mrnugget I'm curious if the dust has settled yet? I've looked at the AI 2025/Q1 roadmap in the zed channel, but I can't find anything related to completions (and the chat itself is basically just "test", "lol" and "/exit"). What are your plans regarding opening up AI completions in Zed for local models?

**Comment by wuemeli** [comment]
Any updates on this? @maxdeviant

**Pull request closed without merging**
