### PR TITLE
Add metal icon

### PR DESCRIPTION
**Pull request by ghost**
Release Notes:

- Added file icon for metal

### CODE REVIEW

**Comment by nervenes** [comment]
Skärmavbild 2024-12-08 kl  23 07 25

**Comment by danilo-leal** [comment]
Figma! I redrew the SVG completely to clean it up and ensure it abides to the guidelines we've been using for file icons 🙂

**Comment by nervenes** [comment]
Nice, thank you! Are the icon guidelines available somewhere I can read? I've had a few more icons in mind, namely Objective-C and C agnostic header file icons.

**Comment by mikayla-maki** [comment]
Thank you!

**Comment by mikayla-maki** [comment]
@nervenes 

> Are the icon guidelines available somewhere I can read?

Just checked in on this, they are not! We tend to prefer using either Lucide icons or making our own for specific projects. Feel free to open more PRs with placeholders!

**Pull request merged**
