### PR TITLE
Selectable information popover text

### LINKED ISSUE #5236: Selectable text in hover/inline-diagnositics
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

There are a lot of situations where it is useful to copy some text out of some hover popup or inline diagnostic message

### Describe the solution you'd like

The ability to select text in hover popups and inline diagnostics

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

### PR DESCRIPTION
**Pull request by effdotsh**
Release Notes:

- Fixed #5236
- Added the ability to select and copy text from information popovers

https://github.com/zed-industries/zed/assets/50590465/d5c86623-342b-474b-913e-d07cc3f76de4

### CODE REVIEW

**Comment by 0x2CA** [comment]
@ConradIrwin I would love this feature, but right now there is no way for keyboard access in vim

**Comment by ConradIrwin** [comment]
@0x2CA definitely hear you on wanting keyboard based navigation in this. I'd like to push that to a separate feature request though (as this will solve the 90% use-case).

The dismissal behavior is maybe a little more complicated. If we know we opened it with the keyboard (e.g. shift-k in vim mode) then it's frustrating to try and mouse-over right now, because your mouse is in the wrong place. @effdotsh I'm not sure if we can tell whether the popup was opened by keyboard or mouse? If it was opened by keyboard we should probably dismiss it on selection change / escape; not on mouse move - but we should keep the existing mouse move behavior if it was opened by a mouse move.

@effdotsh Could we set the style for rendering to match the existing code more closely. I think mostly that means fading the text color out more and using the monospace font consistently. (As a result I think we should put the styles in the hover code, and not in a default method).

Screenshot 2024-06-12 at 22 29 09
Screenshot 2024-06-12 at 22 29 15
Screenshot 2024-06-12 at 22 42 21
Screenshot 2024-06-12 at 22 41 58

It also looks like we lost syntax highlighting inside the pre block - not sure if the markdown returned by the language server contains the language; if not we could possibly default it to the file's language?

Instead of a `pad_block` boolean. I think we should change the style to take a `StyleRefinement` for code-blocks instead of a TextStyleRefinement. That way we should be able to specify the margins and paddings in the style as we want.

What situation causes a single info hover with multiple blocks? I'm worried that having multiple markdown views will mean that you can't select between the two; we should probably combine things into one document (assuming that makes sense given the context).

Is `trim_codeblocks` needed in general, or should we just trim leading/trailing newlines from the document. In testing it seems like we've lost some blank lines around code-blocks that should be there.

**Comment by 0x2CA** [comment]
> The dismissal behavior is maybe a little more complicated. If we know we opened it with the keyboard (e.g. shift-k in vim mode) then it's frustrating to try and mouse-over right now, because your mouse is in the wrong place. @effdotsh I'm not sure if we can tell whether the popup was opened by keyboard or mouse? If it was opened by keyboard we should probably dismiss it on selection change / escape; not on mouse move - but we should keep the existing mouse move behavior if it was opened by a mouse move.

The vim plugin in vscode can distinguish between keyboard and mouse hover behavior.
Of course these optimizations can be implemented in the next feature

https://github.com/zed-industries/zed/assets/19868292/9f1a84c7-e2cf-4b53-abaa-ecd873c065e1

**Comment by effdotsh** [comment]
@ConradIrwin 

Syntax highlighting was lost because the lsp is returning \`\`\`js, which the markdown crate is not using. Replacing for \`\`\`javascript makes the highlighting work.

image

The markdown crate also seems to be ignoring line breaks
image
renders to 
image.

The potential multiple markdown views have been combined. 

`trim_codeblocks` seems to not be necessary, I think I misread the intention being `test_line_ends_trimmed`? It is working fine without it.

I'll take a look at the rest of your comments tomorrow.

**Comment by ConradIrwin** [comment]
@effdotsh Is this ready for me to take another pass?

**Comment by effdotsh** [comment]
@ConradIrwin not quite. For the past couple of days I've been stuck on an issue where if a `TextRefinement` has a background color, the text is not visible when the user scrolls past the first line of the paragraph. 

https://github.com/zed-industries/zed/assets/50590465/968916c1-44fa-4d81-8d2f-2ef210c15438

I'm guessing this is the background being rendered on top of the text, rather than the text disappearing because changing just the text color works as expected. 

https://github.com/zed-industries/zed/assets/50590465/4445b12f-3370-41c9-a416-2993e14d65a8

I've been staring at this for a little while now, so any insight would be greatly appreciated! In the meantime, I just need to finish the dismissal behavior you mentioned, then it should be good.

**Comment by effdotsh** [comment]
The highlighting issue is present on the current markdown example on main (49dc63812ab1238b4df781ac342d0e3b107c0f7b) 

https://github.com/zed-industries/zed/assets/50590465/e8956080-cdf0-423b-83b1-b9fc4ce55a79

**Comment by effdotsh** [comment]
@ConradIrwin this should be ready for another pass!

**Review by soham-suki — APPROVED** [review]

**Comment by ConradIrwin** [comment]
@effdotsh Sorry for the slow turn-around here - this is looking really good! Also, I'm perplexed by the text rendering with backgrounds wrong when scrolled thing (cc @as-cii in case you have any idea). That said your fix fixes it, so it seems reasonable.

A few things to fix still:
* There's a bunch of commented-out code which we should delete
* The remoting dialogue has the wrong font color.
*  Screenshot 2024-07-03 at 15 45 14
* (To test this you need to set up for local development and run `foreman start` in one terminal tab, and then `./script/zed-local` in another. Then go to `cmd-shift-p remote`, then click new server, then "manual setup").
* It doesn't seem like the font selection is actually working for code blocks (e.g. if we set the font family to Zed Plex Sans, that is applied to code blocks instead of Zed Plex Mono:
Screenshot 2024-07-03 at 16 01 13
* (Super minor), but Rems(4_f32).into() can be spelled `rems(4.)` to be more like zed style.

**Comment by ConradIrwin** [comment]
Also, I think we can clean up the language selection logic by giving the markdown parser a default language to use if either none is specified or it can't parse the tag. Hopefully that lets us avoid pre-processing the markdown before passing it to the renderer.

**Comment by effdotsh** [comment]
@ConradIrwin ready for another pass

**Comment by soham-suki** [comment]
Can someone explain to me, from a technical POV, why is it to hard to implement selectable text? I was interested in this feature since a long time and I tried to follow the code in the PR, but unfortunately I couldn't, at least from a cursory glance.
Why is the hover tooltip so different from the normal text in the editor that makes it unselectable? And why is it such a hard problem to make it selectable?

**Comment by ConradIrwin** [comment]
@soham-suki how much detail do you want :D.

The short answer is GPUI doesn't really have any builtin support for selections yet. Zed implements selections, but only in two contexts so far: Editable inputs, and a new markdown renderer.

The tricky part of this PR is switching to the new markdown rendering and adding missing features to the new renderer.

The tricky part of selectable text (in general) is that there's a somewhat complicated stateful mapping to track between "position in the text" and "pixel coordinates" in a way that doesn't change as text in the UI is updated or we're scrolled around (or even off-screen).

**Comment by soham-suki** [comment]
> @soham-suki how much detail do you want :D.
> 
> The short answer is GPUI doesn't really have any builtin support for selections yet. Zed implements selections, but only in two contexts so far: Editable inputs, and a new markdown renderer.
> 
> The tricky part of this PR is switching to the new markdown rendering and adding missing features to the new renderer.
> 
> The tricky part of selectable text (in general) is that there's a somewhat complicated stateful mapping to track between "position in the text" and "pixel coordinates" in a way that doesn't change as text in the UI is updated or we're scrolled around (or even off-screen).

Very interesting! Why is editable text treated differently than non editable text? At the end of the day, if you're displaying text, selection of it should be an independent function of whether it's editable or not, no?

**Comment by ConradIrwin** [comment]
@soham-suki primarily performance. An editor maintains a *lot* of state that a label does not need.

@effdotsh Thanks again for this!

I've made some final tweaks to fix some more weird rendering artifacts in various popovers I tried, and it's looking pretty slick.

I also changed it so that if you have a selection in the popup, it will not dismiss the popup on mouse out (though it will on escape).

**Comment by JosephTLyons** [comment]
This is really nice - one minor thing I ran into is that you can only select text moving left to right, but not right to left.

**Comment by effdotsh** [comment]
@ConradIrwin thanks for working on this. 73d4b3cbc138ae0ea7b7eceabb167f816aaa4710 seems to have broken the copying behavior (with keyboard input dismissing the popover). I just submitted a fix #14368

**Pull request merged**
