### PR TITLE
Add a Project Search button to the Status Bar

### LINKED ISSUE #7836: Add "Find In Project" button and keyboard shortcut
### Check for existing issues

- [X] Completed

### Describe the feature

In VS Code we have a button represented by this magnifying glass that allows us to search for things in the entire project. In Zed we have a similar feature called Find In Project, but it's way too inaccessible (Menubar > Edit > Find In Project).

Screenshot 2024-02-15 at 11 43 43

I use this feature a lot and it really slows me down having to navigate on the menubar to find it, specially since I use my editor on full screen mode. I'd love if Zed had a find in project icon next to the project panel and added a keyboard shortcut similar to VS Code (Cmd + Shift + F).

### If applicable, add mockups / screenshots to help present your vision of the feature

The idea is that there's a magnifying glass icon right next to the Project Panel icon
Screenshot 2024-02-15 at 11 51 18
<br />

And a keyboard shortcut (maybe Cmd + Shift + F) for Find In Project.
Screenshot 2024-02-15 at 11 52 05

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
Closes #7836 

Release Notes:

- Added a little Project Search button to the status bar for anyone who wants quick access to it

image

Note: The `ProjectSeachIndicator` I created has a lot of potential as showing the project search stats for a global search, just like diagnostics `items.rs` (`DiagnosticsIndicator`) does.

EDIT: For Design issues, please let me know if search icon on the right side of status bar would be more pleasing

### CODE REVIEW

**Comment by maxdeviant** [comment]
cc @zed-industries/design

**Comment by HarshNarayanJha** [comment]
Any issues with the PR?

**Comment by baldwindavid** [comment]
If this is added we'll want to be able to hide for people that don't like seeing things they'll never use ✋. The convention for hiding these is a `button: bool` setting (e.g. collaboration_panel, chat_panel, notification_panel, assistant, terminal, outline_panel, project_panel).

**Comment by HarshNarayanJha** [comment]
Okay I added the setting

```jsonc
"project_search": {
	"button": false
}
```

will hide it (hopefully, compiling right now)

So where else do I need to document this setting? (schemas, docs etc)

(Btw I just noticed that project search doesn't render file icons, maybe we can add those too!)

**Comment by mrnugget** [comment]
Not against it and also not a designer, but throwing my hat in the ring by saying I think it should be hidden by default. (We do have a discoverability problem, but I think we should fix that in a way that's not adding buttons for features people don't know about.)

**Comment by HarshNarayanJha** [comment]
> should be hidden by default

Sure, that's just a matter of changing the default settings. Let me know if thats preferable

I have implemented the settings already, i will push by tonight

**Comment by baldwindavid** [comment]
@danilo-leal I share some of the same thoughts. Also, for posterity, I'd note that there is an existing way to get at project search via the tab bar quick actions (which is another button group I'd like to be able to hide)...

2024-10-16T122538@2x

**Comment by HarshNarayanJha** [comment]
Thanks for the commits. I haven't fully discovered the gpui's apis yet, and my poor laptop can't handle rust intellisense for this big codebase 😓. I just tried to match existing implementations for the project panel button and diagnostics button and built upon that.

> I do have one thought that I’d like to share, for the record, although I don’t yet have a clear solution/alternative: I feel like it’s a bit weird to have the search button in the status bar as it doesn’t behave the same way as the other buttons, all of which trigger panels.
> 
> Like, you click on it and open up the Project Search tab, but clicking on it back again doesn’t close it. It's not a toggle. And 

I completely agree with you, but again I just took the existing implementation for the diagnostics button and built upon that. The divider you added is honestly the best approach from my viewpoint. It does separate the left panels and the tabs 👍🏼. If agreed by others, you may push that divider too. **I would rather add a similar divider to the right side (separating cursor info, bottom panels and right panels)**. And the current padding does that already, if you carefully notice.

**Comment by HarshNarayanJha** [comment]
> @danilo-leal I share some of the same thoughts. Also, for posterity, I'd note that there is an existing way to get at project search via the tab bar quick actions (which is another button group I'd like to be able to hide)...

Yeah, I am aware of that option, and my initial plan was to add the search icon to the top bar, but then the bottom status bar seemed to be a better place for the diagnostics button, which is kind of similar.

**Comment by baldwindavid** [comment]
> If we ever expose a way for our Project Search to appear within a panel instead of a standalone tab, the button’s placement and behavior would feel more cohesive (which is also more similar to VS Code’s approach).

Might be nice though I tend to think some of this becomes moot if a telescope/helix-style live file and grep search/previewer is eventually introduced.

**Comment by HarshNarayanJha** [comment]
> Also pushed a small commit to use the existing Icon Button instead of `ButtonLike`.

Actually, this is causing me a small issue with implementing the hide the button setting. You are returning an IconButton, which has to have and visual representation, but I must not render it depending on the setting, which forces me to use a h_flex with and child of IconButton, which maybe None if setting instructs.

Also, I am removing the file_icons setting since there is no support for file icons in the project search tab

**Comment by HarshNarayanJha** [comment]
Okay, so the setting works now and defaults to false. 🎉 

The only problem is that after hiding the search button, the diagnostics button is offset by a small amount, even if I use
```rust
div().w(rems(0.0))
```
How to add an empty `div` right there?

image

**Comment by RemcoSmitsDev** [comment]
I think you can use the Empty element:

https://github.com/zed-industries/zed/blob/da28091b69345e323bf4cad64e3194e08e36fc06/crates/gpui/src/element.rs#L599

**Comment by HarshNarayanJha** [comment]
Did work with `Empty`, still having the spacing. Even tried to zero margin, padding and width of a div, but still has the space reserved.

Apart from that, I think is PR is ready for merging

**Comment by RemcoSmitsDev** [comment]
Yeah, I think GPUI doesn't take this into account yet.

**Comment by HarshNarayanJha** [comment]
For the space that is wasted by this button, moving the search button next to the diagonistics button helps since the diagonistics text doesn't always stays visible. So space is not wasted

**Comment by maxdeviant** [comment]
Thank you for your work on this PR. After some internal discussion we've decided we don't want to move forward with adding this button.

Given it's not something we want enabled by default, having it as a setting just means that it's something extra that we need to take into account when designing in this area.

We're trying to keep the status bar as lightweight as possible.

**Comment by HarshNarayanJha** [comment]
@maxdeviant It appears like we have the project search button into the latest release (ref https://github.com/zed-industries/zed/pull/28388), with no option to hide it.

**Pull request closed without merging**
