### PR TITLE
Add syntax highlighting for GraphQL

### PR DESCRIPTION
**Pull request by 11bit**
Adds basic support of GraphQL

Changes:
- [tree-sitter-graphql](https://github.com/bkegley/tree-sitter-graphql) grammar
- Oficial icon from https://graphql.org/brand/
- Embeddings configuration

Notes:
- I am using my fork of tree-sitter-graphql that [updates tree-sitter dependency to version 0.20.9](https://github.com/bkegley/tree-sitter-graphql/pull/14). I will replace it with bkegley's one whenever it is merged 
- I didn't find any documentation on `brackets` configuration in `config.toml`. What does `newline = true` mean in there? 
- This PR doesn't have LSP because implementation can be complicated since it requires schemas to work properly. I will try to address it in a separate PR

Screenshots:
Highlighting@2x

Icon@2x

### CODE REVIEW

**Comment by maxdeviant** [comment]
Since this is just syntax highlighting, could we add this in an extension instead?

You can refer to the docs [here](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md) for authoring an extension, and we're happy to answer any questions you have on the process.

**Comment by 11bit** [comment]
@maxdeviant 
1. I was planning to work LSP after that. Should I wait before extensions support it or continue here? 
2. Can I add an icon for GraphQL files via extensions? 

Thanks!

**Comment by 11bit** [comment]
@maxdeviant Looks like extensions are the way to go. So I made an extension from it https://github.com/zed-industries/extensions/pull/91. 

But can we merge an icon for graphql files from this PR? It would be great to have an icon

**Comment by maxdeviant** [comment]
> @maxdeviant Looks like extensions are the way to go. So I made an extension from it [zed-industries/extensions#91](https://github.com/zed-industries/extensions/pull/91).
> 
> But can we merge an icon for graphql files from this PR? It would be great to have an icon

Yea, could you open a separate PR for it?

So long as the icon looks good with the rest of our existing icons I think we'll be okay to accept it.

**Comment by 11bit** [comment]
> Yea, could you open a separate PR for it?
> 
> So long as the icon looks good with the rest of our existing icons I think we'll be okay to accept it.

Sure. Here is an icon. Let me know if it needs any changes to fit existing icons. https://github.com/zed-industries/zed/pull/8213

**Pull request closed without merging**
