### PR TITLE
Add doas support in script/linux

### PR DESCRIPTION
**Pull request by feelamee**
Release Notes:
- n/a

### CODE REVIEW

**Comment by feelamee** [comment]
@cla-bot check

**Comment by mikayla-maki** [comment]
Which libraries need this?

**Comment by feelamee** [comment]
This is no need for libraries also as sudo typically no need for it.
Doas is just an alternative to sudo, that's why this change will be useful for peoples who prefer it. For example me, but I'm not the only one

**Comment by mikayla-maki** [comment]
If we don't use this, I don't see a reason to add it yet.

**Comment by feelamee** [comment]
ok, then why you add `sudo`?

**Comment by mikayla-maki** [comment]
Oh, I'm sorry, I didn't check the PR when I should have. 

Could you add a typo exception for this? That way we can pass CI :)

**Pull request merged**
