### PR TITLE
[WIP] Add Docker file icon

### PR DESCRIPTION
**Pull request by Tom-Boscher**
Add Docker file icon.
_Source: https://www.docker.com/company/newsroom/media-resources/_

Release Notes:

- N/A

Capture d’écran 2024-02-25 à 18 06 06

### CODE REVIEW

**Comment by Tom-Boscher** [comment]
It seems that only `.dockerignore` is recognized as a Docker file.

**Comment by Hugoonreplit** [comment]
Hey @Tom-Boscher, I think most Zed file icons sizes are along the lines of 14x14 and 14x15, so maybe a good idea would be resizing the .svg file to any of those sizes, preferably 14x14!

**Comment by Tom-Boscher** [comment]
> Hey @Tom-Boscher, I think most Zed file icons sizes are along the lines of 14x14 and 14x15, so maybe a good idea would be resizing the .svg file to any of those sizes, preferably 14x14!

Indeed, I fixed that

**Comment by Tom-Boscher** [comment]
Capture d’écran 2024-02-28 à 02 21 46

**Comment by maxdeviant** [comment]
Thanks for opening this PR, @Tom-Boscher.

It looks like icons for `Dockerfile`s were added already in #8453.

**Pull request closed without merging**
