### PR TITLE
Add file icons for Zig, Julia, SCSS, HCL, Nix, and Roc

### PR DESCRIPTION
**Pull request by PixelJanitor**
Release Notes:

- Added file icons for Zig, Julia, SCSS, HCL, Nix, and Roc files.

image

### CODE REVIEW

**Comment by TanklesXL** [comment]
I just wanna say that I love that Zed is adding a gleam file icon 💜 

I have shared this with the gleam core team so they can give some feedback about how Lucy (gleam's mascot) looks here.

For transparency, i'll quote what I told @JosephTLyons when he first shared the PR in the gleam discord: 
> I just find it's giving more pentagon energy and less star energy 😆

**Comment by lpil** [comment]
Hey! This is cool!

The Gleam one looks cute but on my phone now it looks a bit pointy and seems to curves inwards rather than outwards.

Is it possible to see what it would looks like in the UI?

**Comment by JosephTLyons** [comment]
> Hey! This is cool!
> 
> 
> 
> The Gleam one looks cute but on my phone now it looks a bit pointy and seems to curves inwards rather than outwards.
> 
> 
> 
> Is it possible to see what it would looks like in the UI?

I can compile it and provide screenshots tonight.

**Comment by lpil** [comment]
Jen in the Gleam discord is working on an icon and I think he'll share it here soon for consideration

**Comment by george-grec** [comment]
@JosephTLyons no worries, I'm just an impatient guy, I appreciate the work!

**Comment by JosephTLyons** [comment]
> @JosephTLyons no worries, I'm just an impatient guy, I appreciate the work!

We want the Gleam icon in Zed too!

**Pull request merged**
