### PR TITLE
Add support for applying theme after extension is installed

### LINKED ISSUE #9228: Apply theme extensions on install
### Check for existing issues

- [X] Completed

### Describe the feature

It might be handy to be able to apply or even preview the theme extension after it's installed.

There are a few ways to do this, each with its own UX trade-offs:

- Automatically apply the installed theme.
- Show a toast/popup asking if you want to apply the theme.

Some editors even preview the theme on the current window when selected, but this isn't possible with the current extensions market layout.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- Added support for opening the theme selector with installed themes after installing an extension containing themes. ([#9228](https://github.com/zed-industries/zed/issues/9228)).

Screenshot 2024-03-20 at 11 00 35 AM

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I don't think we should be automatically picking a theme from the theme list, as it doesn't really make sense for extensions that provide multiple themes.

I think it would be better to pop up the theme selector, perhaps with the first theme pre-populated.

**Comment by huacnlee** [comment]
Ok, I will change later.

Marshall Bowers ***@***.***>于2024年3月19日 周二下午10:29写道：

**Comment by huacnlee** [comment]
New Update @maxdeviant 

There are some places changes I have to. But maybe I am not familiar with the Zed development, I don't know they are correct, if any incorrect modifications, please point them out for me, I will change it again.

output

**Comment by huacnlee** [comment]
There are still need to improve to only show themes of installed extension, not all theme. 

But I think we can check current implementation first, and then I do it later, this will have many changes the Theme Selector.

**Comment by huacnlee** [comment]
New update, now is better:

output

**Review by maxdeviant — APPROVED** [review]
Thanks, the new behavior is much better!

**Pull request merged**
