### PR TITLE
Improve runnable detection for JavaScript files

### LINKED ISSUE #21242: Search buffer symbols won't show `test.only` blocks for Javascript or Typescript test files
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open a test file that contains `describe`, `suite`, `test`, `it`, etc. blocks, the buffer symbols correctly show a list of these. However, if either one of those blocks is prefixed with `.only`, `.skip`, etc., these will disappear from the buffer symbols.

I'd definitely like to find them in the list, and OPTIONALLY perhaps using a different styling.

### Environment

Zed: v0.163.2 (Zed Preview)
OS: macOS 15.1.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by RemcoSmitsDev**
Closes #21242

Screenshot 2024-11-27 at 18 52 51
Screenshot 2024-11-27 at 18 53 08

Release Notes:

- Improved runnable detection for JavaScript/Typescript files.

### CODE REVIEW

**Comment by exalted** [comment]
@RemcoSmitsDev, along with `describe`, I think `suite` and `context` grouping functions should also be detected. Those are pretty common keywords in JS testing frameworks.

**Comment by RemcoSmitsDev** [comment]
Hey @exalted, Could you provide any docs for these methods? e.g. Jest does not seem to have them: https://jestjs.io/docs/api#methods.

**Comment by exalted** [comment]
@RemcoSmitsDev sure thing!

* https://mochajs.org/#tdd
* https://mochajs.org/#bdd

**Comment by RemcoSmitsDev** [comment]
Hey @exalted, thanks for the docs! Made a small PR to include these methods so they get recognized as a runnable.

**Comment by exalted** [comment]
> Hey @exalted, thanks for the docs! Made a small PR to include these methods so they get recognized as a runnable.

I appreciate you. Thanks!

**Pull request merged**
