### PR TITLE
Fix incorrect bright/dim terminal colors

### PR DESCRIPTION
**Pull request by clo4**
Some of the colors were messed up before, with the dim color being the bright one and the bright color being the dim one. This change swaps the colors where the dim color was darker. Not every pair was incorrect, so the process was automated using a script to (naively) check the luminance of each color, corrected for human vision, and swap them if they were wrong. This may lead to errors, but after checking through the themes manually I don't see any problems.

This only affects the dark themes -- it seems like the light themes are already correct?

## Before:
Gruvbox dark
Screenshot 2024-02-07 at 5 03 20 pm

## After:
Gruvbox dark
Screenshot 2024-02-07 at 5 04 20 pm

<details>
<summary>Conversion script</summary>

```javascript
async function main() {
  const promises = [];
  for (const file of Deno.args) {
    promises.push(fixThemeFile(file));
  }
  Promise.allSettled(promises);
}

async function fixThemeFile(path) {
  const textContent = await Deno.readTextFile(path);
  const json = JSON.parse(textContent);
  for (let i = 0; i < json.themes.length; i++) {
    const theme = json.themes[i];
    const isDark = theme.appearance === "dark";
    fixThemeStyle(json.themes[i].style, isDark);
  }
  await Deno.writeTextFile(path, JSON.stringify(json, null, 2) + "\n");
}

const pairs = [
  { bright: "terminal.bright_foreground", dim: "terminal.dim_foreground" },
  { bright: "terminal.ansi.bright_black", dim: "terminal.ansi.dim_black" },
  { bright: "terminal.ansi.bright_red", dim: "terminal.ansi.dim_red" },
  { bright: "terminal.ansi.bright_green", dim: "terminal.ansi.dim_green" },
  { bright: "terminal.ansi.bright_yellow", dim: "terminal.ansi.dim_yellow" },
  { bright: "terminal.ansi.bright_blue", dim: "terminal.ansi.dim_blue" },
  { bright: "terminal.ansi.bright_magenta", dim: "terminal.ansi.dim_magenta" },
  { bright: "terminal.ansi.bright_cyan", dim: "terminal.ansi.dim_cyan" },
  { bright: "terminal.ansi.bright_white", dim: "terminal.ansi.dim_white" },
];

function fixThemeStyle(style, isDark) {
  for (const { bright, dim } of pairs) {
    const brightColor = style[bright];
    const dimColor = style[dim];

    const brightBrightness = colorLuminance(brightColor);
    const dimBrightness = colorLuminance(dimColor);

    if (isDark) {
      if (dimBrightness > brightBrightness) {
        style[bright] = dimColor;
        style[dim] = brightColor;
      }
    }
    // This isn't correct:
    // else {
    //   if (dimBrightness < brightBrightness) {
    //     style[bright] = dimColor;
    //     style[dim] = brightColor;
    //   }
    // }
  }
}

function colorLuminance(colorString) {
  const c = colorString.substring(1);
  const rgb = parseInt(c, 16);
  const r = (rgb >> 16) & 0xff;
  const g = (rgb >> 8) & 0xff;
  const b = (rgb >> 0) & 0xff;

  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

main();
```

</details>

# Release Notes:

- Fixed incorrect bright/dim terminal colors

### CODE REVIEW

**Comment by maxdeviant** [comment]
I'll need to take a closer look at this.

In Andromeda, for instance, the current dim and bright colors look to be what I would expect:

#### Dim red

Screenshot 2024-02-07 at 10 10 23 AM

#### Bright red

Screenshot 2024-02-07 at 10 10 29 AM

**Comment by clo4** [comment]
Andromeda is a dark theme right? To me it makes more sense to make the dim color visibly darker and the bright color lighter. Maybe it's worth changing the terminal palette a little bit to account for this, so that it's consistently more vibrant instead of lighter? In most themes the current bright color is more saturated but very dark.

I think it's also worth considering removing the dim colors from the theme entirely and handling that in the terminal rendering by making the foreground more transparent, but that's a separate thing entirely

**Comment by maxdeviant** [comment]
> Andromeda is a dark theme right? To me it makes more sense to make the dim color visibly darker and the bright color lighter. Maybe it's worth changing the terminal palette a little bit to account for this, so that it's consistently more vibrant instead of lighter? In most themes the current bright color is more saturated but very dark.
> 
> I think it's also worth considering removing the dim colors from the theme entirely and handling that in the terminal rendering by making the foreground more transparent, but that's a separate thing entirely

I imagine there's a bit of subjectivity to this.

When I think of "bright" and "dim" colors in the theme, I think of bright colors being more vibrant and dim as being more washed-out, regardless of whether they're light or dark.

Also, would you mind sharing that `colors` script you're using above so that I can be looking at the same thing you are?

**Comment by clo4** [comment]
I totally agree that there's some subjectivity here - the main thing is that right now the bright colors make the terminal difficult to read because of their *lower* contrast. I personally don't care about whether or not the bright colors are lighter, more saturated, etc, just that we can increase the overall contrast with them.

This is Andromeda in VS Code:
Screenshot 2024-02-09 at 11 13 08 am

In Ghostty / iTerm (same themes)
Screenshot 2024-02-09 at 11 15 53 am

Currently in Zed:
Screenshot 2024-02-09 at 11 11 37 am

This contrast problem is the same in every theme - it's very hard to read in all of them. The "bright" color should be at least as bright as the normal color imo. The prompt I'm using is Tide, and if you select the 16-color mode in `tide configure` it uses bright colors to highlight the current directory, branch, git repository root, etc.

The colors script is just [this one](https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/) but I removed the last two lines so it only prints the first 16 colors. Having had a quick peek at your dotfiles seems like you're also a fish user, so I quickly made a nicer/shorter script that we can use for this :)
```fish
for color in black red green yellow blue magenta cyan white
    set_color --background $color
    printf " Normal "
    set_color --background br$color
    printf " Bright "
    set_color reset
    printf "\n"
end
```

If you think it's worth spending some time going through the themes and maybe picking some colors that work better manually I'm happy to do that!

**Comment by clo4** [comment]
Just noting that I pushed a commit where the script that flips the colors correctly accounts for the alpha value included in the strings, it probably didn't change anything of note.

**Comment by maxdeviant** [comment]
@clo4 Sorry for the radio silence here.

I think this is a bit more of an involved effort that I would like input from our designer, @/iamnbutler (who is currently on paternity leave), on before moving further.

Would you mind opening an issue for this so that we can discuss further?

I'm going to close this PR out, for now.

**Comment by clo4** [comment]
@maxdeviant im fully on board with that. Will open the issue later today :)

**Pull request closed without merging**
