### PR TITLE
Project Panel Sorting Options (dirs first)

### PR DESCRIPTION
**Pull request by crbellis**
Release Notes:

- Added a project panel sort setting, `sort_order`, with one additional sorting option `dirs_first` which sorts by directory first at each level of the directory. Default setting is the current production project panel setting. Issue: ([#4533](https://github.com/zed-industries/zed/issues/4533)).

Some examples of the `dirs_first` setting:
Screenshot 2024-03-08 at 8 40 41 PM
Screenshot 2024-03-08 at 8 40 21 PM

The project panel setting:
Screenshot 2024-03-08 at 8 41 51 PM

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Hey @crbellis.

I'm not sure if you'll run into any limitations with the fake file system, but assuming not, one thing that might be nice here is a test in `project_panel.rs` that includes a couple of files / directories, asserts they are in one order with the setting off, then in another order with the setting on.  There are some existing tests here that show how to simulate a file tree.

**Comment by crbellis** [comment]
No problem, I can put some tests together. 

Just a noticed this but I just pulled main and it seems like [PR#8486](https://github.com/zed-industries/zed/pull/8486) may have changed the way default sorting is done in the project panel. 

Regardless, think there may be some useful pieces here for extending to more sorts in the future.

Let me write some tests and add to the PR.

**Comment by JosephTLyons** [comment]
> @JosephTLyons No problem, I can put some tests together.
> 
> Just noticed this - I just pulled main and it seems like [PR#8486](https://github.com/zed-industries/zed/pull/8486) may have changed the way default sorting is done in the project panel.
> 
> Regardless, think there may be some useful pieces here for extending to more sorts in the future.
> 
> Let me write some tests and add to the PR.

Yeah, I think that other PR is about just treating number strings are numbers, so I dont think it negates what you are trying to do here.

**Comment by mrnugget** [comment]
@crbellis sorry for causing the merge-conflict! Do you need any help getting this PR back up?

@xpe is there a way we can work towards the composability here, say by using the right settings schema, without having to build the generic system up front? What'd you have in mind?

**Comment by mrnugget** [comment]
Good questions. I think the answer to most of these is: the extensions are very WIP at the moment and change from day to day. At the moment, I don't think they have any of the mechanisms nor capabilities you mentioned.

I think we'll have to wait until extensions are a bit further along until we can incorporate this here _and_ at the same time use these ideas to develop extensions. Meaning: I think we can continue with this PR, because I don't think it'll create blockers, and once we have a better grasp of extensions, we can extend the sorting system.

**Comment by mrnugget** [comment]
> LMW if there is a better place to share these thoughts.

I think the channel notes for our Product channel are actually a good place for that: https://zed.dev/channel/product-347

**Comment by mrnugget** [comment]
Hey @crbellis, I'm going to close this just to keep the number of open PRs manageable. If you want to pick this up again, let's reopen, no problem :)

**Pull request closed without merging**
