### PR TITLE
windows: implement mouse double click event

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
Seems like there's a bit of a conflict with this PR since I merged the others. 

That said, I'm not sure this is the approach we want to go down. On macOS and Linux we get a simple counter of how many clicks a user has made, which can go as high as the user wants. Is there a compelling reason to use the `NCBUTTONDBLCLICK` mechanism, over an approach like in this PR: https://github.com/zed-industries/zed/pull/9608?

**Comment by JunkuiZhang** [comment]
> Seems like there's a bit of a conflict with this PR since I merged the others.
> 
> That said, I'm not sure this is the approach we want to go down. On macOS and Linux we get a simple counter of how many clicks a user has made, which can go as high as the user wants. Is there a compelling reason to use the `NCBUTTONDBLCLICK` mechanism, over an approach like in this PR: #9608, except using `GetDoubleClickTime()` instead of hard coding it?

Oh, I didn't notice these double click changes in other playforms. If you wish, I can implement it for the Windows platform in a way similar to how other platforms handle the double-click mouse event.

**Comment by mikayla-maki** [comment]
I think it would be best to match the other platforms and do things simply, unless there's a good reason to use the `NCBUTTONDBLCLICK` approach, in which case we should augment it with the behavior of the other platforms :)

**Comment by JunkuiZhang** [comment]
Cargo clippy complains "recursion limit reached while expanding `#[test]`", should I move the tests to another file?

**Comment by mikayla-maki** [comment]
> "recursion limit reached while expanding #[test]"

That is caused by doing `use crate::*;`, which currently doesn't work inside GPUI.

**Comment by mikayla-maki** [comment]
Thank you!

**Pull request merged**
