### PR TITLE
Add Go file icon

### PR DESCRIPTION
**Pull request by MordFustang21**
IMG_4664

Release Notes:

- Added icon to `.go` files

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
There is already a pull request for adding the GO file icon. #7069

**Comment by maxdeviant** [comment]
> There is already a pull request for adding the GO file icon. #7069

I think the icon in this PR looks more in line with what I would expect.

**Comment by maxdeviant** [comment]
@MordFustang21 Thank you for the PR!

**Comment by d1y** [comment]
This icon has a different style from the other icons (it looks too small) and looks weird, I created PR #7069  thought this icon would fit in with the overall style.

image

**Comment by maxdeviant** [comment]
> This icon has a different style from the other icons (it looks too small) and looks weird, I created PR #7069 thought this icon would fit in with the overall style. @maxdeviant
> 
> image

I do agree that the Go wordmark doesn't _quite_ fit with the rest of the style.

We could potentially scale it up a bit and/or change the style to be a bit softer like the other icons (although I'm not sure exactly what sorts of changes are permissible under the Go branding guidelines).

I suspect this will be a common problem as we add more logos for icons, so we may just have to live with the differences at a certain point.

**Comment by MordFustang21** [comment]
I also agree it is a little small. I tried increasing the size a little but I think it looks small because the logo is wider than it is tall so it's staying within bounds.

This is the same icon that's used in the vscode-go plugin. 

I don't believe modifying the logo is allowed under the brand guidelines. See [Brand](https://go.dev/brand)
```
The Go Logo may not be used in the following manners without review and approval:

used as or incorporated in the logo for a commercial product;
modified in any form; or
used in close proximity to, within, or encompassing another logo, badge, or stylized trademark.
```

**Pull request merged**
