### PR TITLE
Add Go file type icon

### PR DESCRIPTION
**Pull request by d1y**
The SVG icon RAW link: https://www.svgrepo.com/svg/355038/golang
The Licensing https://www.svgrepo.com/page/licensing/#CC0

image

Release Notes:

- Added Go file type icon

### CODE REVIEW

**Comment by d1y** [comment]
I think

- go.mod
- go.work
- go.work.sum
- go.sum

should also use that icon🤔?

**Comment by maxdeviant** [comment]
Is this a commonly used icon for Go files?

it looks more like a logo/branding asset, to me.

What does VS Code do?

**Comment by maxdeviant** [comment]
I’m not a Go person, but I thought most editors used some variant of the wordmark:

image

**Comment by maxdeviant** [comment]
@d1y We ended up going with the version of the icon in #7110.

Appreciate you opening this PR!

**Pull request closed without merging**
