### PR TITLE
vim: Enable `%` to jump between tags

### LINKED ISSUE #12986: vim: Cannot use % to jump to matching tag
### Check for existing issues

- [X] Completed

### Describe the feature

When working with .jsx, .tsx, .html and etc files, the Shift + 5 keybinding does not jump between open and closing HTML/JSX tags although it works for brackets. This keybinding is expected to help navigate between matching pairs of tags but fails to do so.

> Steps to Reproduce:

1. Open any .jsx, .tsx, or .html file in Vim.
2. Place the cursor on an opening or closing HTML/JSX tag.
3. Press Shift + %.
4. Expected Behavior:
5. The cursor should jump to the matching closing or opening tag.

> Actual Behavior:
- No navigation occurs, or the cursor jumps incorrectly.

Additional Information:
I have attached a video as well for more info, and this video is of Neovim 0.9 with tsserver lsp.

Zed version: 0.139.3
OS: MacOS Sonoma 14.5

> If you guys fix, I am sold for Zed!

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/86684667/1378edb0-4a37-40e0-965f-77aa12687faa

### PR DESCRIPTION
**Pull request by hrou0003**
Closes #12986

Release Notes:

- Enable `%` to jump between pairs of tags

### CODE REVIEW

**Comment by hrou0003** [comment]
@ConradIrwin I've cleaned up the clippy errors from the most recent run

**Comment by ConradIrwin** [comment]
Thanks! 

I also know you have signed the CLA because we paired on this, but I wonder why @clabot can't figure it out

**Comment by hrou0003** [comment]
I think it's because I had git configured incorrectly on that first commit, I tried going back to update the author but that doesn't seem to have worked  😕

**Comment by ConradIrwin** [comment]
🤷

**Comment by sadiksaifi** [comment]
@hrou0003 Thanks a lot

**Comment by frontsideair** [comment]
I think this PR may have broken something.

When I'm inside the HTML tag like `<div id="button button-primary">` and while inside the quotes if I press `%` it jumps all the way down to the closing tag, and not move around the quotes. So I think HTML tags take precedence.

I think the innermost thing should take precedence when `%` is pressed. I was so used to this and it's been broken for a long time.

**Comment by hrou0003** [comment]
@frontsideair looks like neovim also behaves this way so I'm not sure if it's an issue for Zed's vim-mode, but I do feel like breaking behavior isn't great - I'd be happy to take a look at restoring the previous behavior if others think it makes sense - any thoughts @ConradIrwin?

**Comment by frontsideair** [comment]
I haven't compared behavior with other surround plugins (only comparing to the previous zed behavior) so you're most likely correct. But since it's not a core vim functionality, maybe there's no strong source of truth and room to discuss what's to be expected. 

Since I'm already used to the old behavior, I may be a bit biased, but my expectation to have it jump between the innermost surround context makes sense to me. Hope that also makes sense to you too.

**Pull request merged**
