### PR TITLE
Update Configuration docs

### PR DESCRIPTION
**Pull request by pointlessone**
Release Notes:

- N/A

---

I'd like to help improve Configuration documentation.

Currently I'm often confused by the configuration doc. It's incomplete: not all settings are documented. It's disorganized: some options are grouped together but overall there's not much structure or logic to it. It's inconsistent: some examples show only key and value, some—just the closes object, and others full nesting. It's confusing: individual keys are listed but it's hard to understand where in the config structure they belong.

I suggest the following changes:

- Always specify the full path of the setting
- Document all settings Zed recognises
- List settings in alphabetical order of their full path
- Always use full nesting in examples 

This is an example, of what it might look like. It's first draft, too. So I'm open to suggestions.

Please let me know if you're interested in this. The whole thing might need a bit of effort so I'd like to know if this is something you might want before doing all the work.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for taking a pass at this, we definitely need to improve that page!

I'd suggest we merge this in chunks rather than trying to do the whole thing in one shebang. What you have here seems sensible to me, but it looks like the linter is complaining about spelling. 

The other idea I had was to split things up a bit so we have a "common configuration" page that links out to a "reference configuration" page. We could potentially auto-generate the latter from the default settings (though we'd probably want to also improve the comments in that file).

**Comment by pointlessone** [comment]
Yeah, I saw the linter complaints. For whatever reason Zed didn't show any spelling mistakes. Maybe because I can't configure it quite right. ;) I'll fix that.

I agree that updating the documentation in chunks is easier to review. I will remove the AI configuration part from this PR and only leave the intro part. And then will submit individual chunks as they come.

On autogenerating docs from the default settings. I like the single source of truth approach but I have one major issue with that: default setting file does not have all the settings in it, not does it. It might be useful as an offline reference. But given the amount of settings the most sensible approach would be just putting the Configuration source into the settings file comments, and autogeneration would simply be taking all the comments and making a page from them. I have no idea whether it can be done with mdbook, I have little experience with it. In any case, this seem like it can be done later.

Thank you for the feedback.

**Comment by pointlessone** [comment]
I'd appreciate if some with the knowledge would comment on the factual accuracy of this section. Thank you.

**Comment by ConradIrwin** [comment]
@pointlessone Thanks for this! I spent a bit of time trying to make the intro flow better, and I think we're in a good place now. Please send more changes!

**Pull request merged**
