### PR TITLE
refactor: replace static with const for constants

### PR DESCRIPTION
**Pull request by Integral-Tech**

### CODE REVIEW

**Comment by Integral-Tech** [comment]
@cla-bot check

**Comment by osiewicz** [comment]
Is there any reason why you think we should prefer `const`s over statics in these particular cases?

**Comment by Integral-Tech** [comment]
> Is there any reason why you think we should prefer `const`s over statics in these particular cases?

As these variables can be evaluated during compilation and actually immutable, `const` provides better robustness and performance over `static`.

**Comment by osiewicz** [comment]
I'd respectfully disagree. :)
1. static initializers are evaluated at compile time, so there's no difference in the diff of this PR between the two when it comes to initialization performance([1](https://doc.rust-lang.org/reference/items/static-items.html#static-items))
2. Most compilers can notice when a value is immutable (and even in case of `pub static`s you have to mark it as mut, which makes it easier for compiler to infer).
3. None of these changes are in parts of the code that would benefit from (potentially) better constant propagation.

Respectfully, I don't think we should land this change unless it has a demonstrable performance benefit.

**Comment by Integral-Tech** [comment]
> I'd respectfully disagree. :)
> 
>     1. static initializers are evaluated at compile time, so there's no difference in the diff of this PR between the two when it comes to initialization performance([1](https://doc.rust-lang.org/reference/items/static-items.html#static-items))
> 
>     2. Most compilers can notice when a value is immutable (and even in case of `pub static`s you have to mark it as mut, which makes it easier for compiler to infer).
> 
>     3. None of these changes are in parts of the code that would benefit from (potentially) better constant propagation.
> 
>     4. Statics are immutable by default as well; you can just opt into making them mutable.
> 
> 
> Respectfully, I don't think we should land this change unless it has a demonstrable performance benefit. Feel free to reopen this PR when you have data to back it up.

> Constants should, in general, be preferred over statics unless one of the following are true:
    Large amounts of data are being stored
    The single-address property of statics is required.
    Interior mutability is required.

**Pull request closed without merging**
