### PR TITLE
Fix next/prev shortcuts handling in the File Finder

### PR DESCRIPTION
**Pull request by alygin**
This PR fixes the unexpected File Finder behaviour described in https://github.com/zed-industries/zed/pull/8782#issuecomment-2018551041

Any change of the modifier keys except for the release of the initial modifier keys now prevents opening the selected file.

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Great, this will work for me.

If I'm reading this correctly, I think it may be more conservative than what VS Code does. In VS Code, I believe you can do this:
* press `cmd-p` to open the file finder
* release all keys
* press `cmd` again
* press `p` again N times to move the selection down by N
* release `cmd` to confirm the selected file

Am I right that with this change, that behavior (confirming on release of `cmd` after it had already been released once) won't be implemented? I don't think it needs to block this PR, just curious.

**Comment by alygin** [comment]
> Am I right that with this change, that behavior (confirming on release of cmd after it had already been released once) won't be implemented? I don't think it needs to block this PR, just curious.

Yes, you're right, it won't work this way. Yet it's easy to support this scenario. It's just another one-liner and a test :) I can add it to this PR if you don't mind.

**Comment by alygin** [comment]
...but it'll take more time to also support `cmd-shift-p` in the similar scenario because it's now mapped as an equivalend of `ctrl-p`.

**Comment by alygin** [comment]
Here it is. Handles all the mentioned cases for both forward and backward navigation. With corresponding tests.

**Comment by maxbrunsfeld** [comment]
Awesome, thanks for all of the fixes @alygin .

**Pull request merged**
