### PR TITLE
task: Add re-run task button to terminal title

### LINKED ISSUE #12277: Re-run task with a mouse-click
### Check for existing issues

- [X] Completed

### Describe the feature

Great job on improvements to Tasks recently. I think it just lacks one thin - ability to easily rerun task by clicking icon in the task bar. Here is how it should work:

 - hover at the task Ⓧ icon, or a green tick ✓. 
 - on hover it should change into ↺
 - clicking it should re-run the task within same tab

Screenshot 2024-05-25 at 11 23 48

simple yet efficient

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- Added re-run task button to terminal title.

Close #12277

## Demo

https://github.com/zed-industries/zed/assets/5518/4cd05fa5-4255-412b-8583-68e22f86561e

### CODE REVIEW

**Comment by osiewicz** [comment]
Let's use the bundled `IconName::ArrowCircle` for now, we can massage it a bit later. @iamnbutler is a bit busy right now, but he'll take a look at it eventually.

**Comment by iamnbutler** [comment]
[rerun.svg.zip](https://github.com/zed-industries/zed/files/15476608/rerun.svg.zip)
@huacnlee Try this one! Found a bit of time to make one quickly.

CleanShot 2024-05-28 at 18 36 08@2x

**Comment by huacnlee** [comment]
Icon have updated

**Comment by osiewicz** [comment]
Thanks @huacnlee ! :)

**Pull request merged**
