### PR TITLE
Add Java language support

### PR DESCRIPTION
**Pull request by valentinegb**
This pull request aims to add complete Java language support. Currently, this is being achieved in this pull request with [tree-sitter-java](https://github.com/tree-sitter/tree-sitter-java) and [eclipse.jdt.ls](https://github.com/eclipse-jdtls/eclipse.jdt.ls).

It has been [expressed](https://github.com/zed-industries/zed/pull/6935#issuecomment-1913640078) that Java support cannot come until "collapsed directories" are implemented, so this pull request will remain in draft form until that happens. zed-industries/zed#7674 should resolve this.

Release Notes:

- Added Java language support ([#5301](https://github.com/zed-industries/extensions/issues/500)).

### CODE REVIEW

**Comment by ABckh** [comment]
Hi, I don't quite see the necessity of this pull request, as it duplicates functionality already present in my PR (#6935). However, I notice that in your case, the automatic downloading of jdt.ls and accessing it from cached binary features aren't functioning properly. Therefore, I would suggest avoiding redundant efforts. Once #7674 is merged, I'll reopen the PR with Java support. 
@SomeoneToIgnore what do you think is the best approach here?

**Comment by valentinegb** [comment]
Apologies @ABckh! After looking at your PR more closely, I think our pull requests both have certain things implemented better than the other, such as installing the language server in your PR and what I've got so far for completion highlighting in my PR. I would like to continue working on fully implementing complete Java support and I would be happy to do so with your help. I haven't worked on a pull request with another person before, does it sound good if I add you as a contributor on my fork?

**Comment by SomeoneToIgnore** [comment]
Oh, sorry for overlooking such event — I was deep down in the runnables world for the last week or so.
I would indeed prefer if @ABckh's PR would be used at least partially, just due to the humane considerations: I would be pissed if my PR got hijacked.
If it solaces you, we squash PRs into a single commit, and I think both usernames should be used there as co-authors.

And I do think that @ABckh does a right job by dealing with the project panel things first, thank you for that.

Yet, I do not want to make a claim that the original PR should be used in any case: Zed operates on a proof of work (if I may say so) and whatever PR has better functionality should be merged, not the one that got opened first.

Thank you @valentinegb for proposing to pair on that — it would be superb to have a real-time collaboration for it, but even if you could organize and at least cherry-pick commits into the same branch (as noted, there's a benefit from that anyway) it would be a great deal.


As you might have noticed, there is also https://github.com/zed-industries/extensions and we gradually work on hosting all languages there too.
So what if we close this PR too, just to be fair (I closed the original PR due to the reason that there's no proper project panel, so this reason applies here too), and, maybe, by the time the panel gets working, we'll have a way to submit PRs into that repo already?
If not, please talk to each other and propose a solution that is good for both of you.

I'm really sorry for overlooking it again — there's a lot happening in the repository right now. I hope we can agree on something that leaves both of you satisfied.

**Comment by valentinegb** [comment]
I accept that this PR should be closed in fairness. Even so, in the future when #7674 is merged, regardless of if it's in this repository or https://github.com/zed-industries/extensions, I think there's yet more work to be done for full Java support than what either of these Java support PRs have currently and I'd like to be a part of completing that work, along with @ABckh if you would be willing.

**Comment by ABckh** [comment]
> I accept that this PR should be closed in fairness. Even so, in the future when #7674 is merged, regardless of if it's in this repository or in a separate extension repository, I think there's yet more work to be done for full Java support than what either of these Java support PRs have currently and I'd like to be a part of completing that work, along with @ABckh if you would be willing.

Certainly, let's collaborate and ensure that neither your efforts nor mine are wasted

**Comment by SomeoneToIgnore** [comment]
Many thanks for doing this.
As agreed, closing the PR for now and will wait for the collaborated one 🙂

**Comment by SomeoneToIgnore** [comment]
Heads-up, another Java PR, now for extensions: https://github.com/zed-industries/extensions/pull/57
At this point, I do not know if I should close that one, since it's sort of standalone from the main Zed code, but feel free to join the comments.

**Comment by valentinegb** [comment]
Hey I just woke up and it looks like it's already been merged haha
Well, what's the consensus on alternate extensions in Zed? Could there be two Java language support extensions?

**Comment by SomeoneToIgnore** [comment]
Yeah, things are moving fast there. As a small solace, so far extensions do not seem to support LSP integrations but that will sure change in the future to.

> Could there be two Java language support extensions?

I did not participate in the extension discussions much so cannot say for sure — it seems that the list is curated by Zed so far, so there is a possibility for a "no" answer there.
But that extension has a repo and might benefit from collaborations and, in the worst case — proof of work with examples on how the 2nd extension is better might help.
One thing for sure — any project panel quirks are not relevant to whatever is in extensions: as it's not what Zed directly maintains, it can be much worse than we would expect from "official" integrations in this source tree.

**Comment by SomeoneToIgnore** [comment]
Thanks a lot for going that way, @ABckh !
https://github.com/zed-industries/zed/pull/7674 is merged and now Java has to be somehow supported.

Extensions are still in the early phase but looks like it gets formed as wasm extensions: https://github.com/zed-industries/zed/compare/wasm-extensions?expand=1
The plan is to eventually move all languages into https://github.com/zed-industries/extensions after the extension API matures, and make this repo to contain "zed core" that builds and links faster, and more flexible to ship.

It will might take a while to get there, so meanwhile Java LSP support might make sense to merge here.
Welcome to do so, if you wish to.

**Comment by valentinegb** [comment]
Sounds good, if no one objects I'll reopen this PR and add @ABckh as a collaborator to my fork, since this PR is more up-to-date with the main branch, and we can start working on reconciling our changes

**Comment by valentinegb** [comment]
Oh whoops, looks like I can’t reopen this myself actually 😅

**Pull request closed without merging**
