### PR TITLE
Fix markdown preview heading overflows no wrap

### PR DESCRIPTION
**Pull request by flappyBug**
Release Notes:

- Fixed ([#8047](https://github.com/zed-industries/zed/issues/8047)).

Kapture 2024-02-20 at 18 27 15

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]
Looks nice, thank you.
Let's deal with the CLA and merge it?

**Comment by flappyBug** [comment]
@cla-bot check

**Comment by SomeoneToIgnore** [comment]
I see that but nothing else.

```
2024-02-20T12:55:39.814Z INFO Some commits from the following contributors are not signed with a valid email address: haoran. 
```

I have no clue what happens, but see such issue for the first time, so assume something is odd on your side, as even in the PR I linked above it worked.

**Comment by flappyBug** [comment]
Sorry. I just ignored the bot message. I signed my commit with another email, just fixed it and force pushed.

**Comment by SomeoneToIgnore** [comment]
No worries, small PRs occasionally cause more hassle than their changes, but on the bright side, you do not have to do anything like that again as long as you stick to that email in the future PRs.

**Pull request merged**
