### PR TITLE
Don't show modified buffer indicator when autosave is set to delay

### PR DESCRIPTION
**Pull request by ghost**
VS Code, Xcode and CLion (i've not tried or observed how other editors behave) doesn't show an indicator in the tab of a modified buffer when autosave with a delay is enabled, thought we could bring this over to Zed as well.

https://github.com/user-attachments/assets/dc66cb2a-0f8f-4540-95ad-dadb4337c45b

Release Notes:

- N/A

### CODE REVIEW

**Comment by mrnugget** [comment]
Should this also be the case when the indicator would show that the file is conflicted?

**Comment by evrensen467** [comment]
sorry i don't know, i didn't even know the indicator was used to show conflicts, would this pr result in any problems with that?

**Comment by mrnugget** [comment]
I guess it would, yeah. What you'd need to do is to move your settings check inside here:

https://github.com/zed-industries/zed/blob/4347bdb55221639ad78c9153a658926eab8f7192/crates/workspace/src/pane.rs#L2660-L2670

Then you can remove the `.when_some` again.

But I'm wondering: should this be a setting? Or is this universally how it should work?

**Comment by evrensen467** [comment]
ah.. if its fine, i would propose not using this indicator for a conflict, but just for showing an indication of a modified buffer, and put this indicator and the close button in the same place, when the buffer is modified the indicator will take precedence over the close button, when the tab is hovered the close button will take precedence. as for showing the conflict/dirty, i just opened a pr to show git symbols in the project panel https://github.com/zed-industries/zed/pull/16671, we could do this for the tabs as well, not only to show conflicts but also whether if the file is modified, untracked, etc... this is also how vscode seems to do it.

https://github.com/user-attachments/assets/32a98747-0c0d-4e7a-a056-5a688f589da6

**Comment by evrensen467** [comment]
if this solutions is okay, i could try to implement it but i'd need a bit of help because i've actually tried to do this before but i couldnt figure out what code components were at play

**Comment by mrnugget** [comment]
Hmmm, paging @iamnbutler on this here. With a setting, I'm happy to merge the changes to hide the indicator, but I want to be careful about changing the indicators and/or removing them.

**Comment by evrensen467** [comment]
sounds good enough for me, ill open a separate issue/pr as a followup to my indicator proposal, and work on making this a setting 👍

**Comment by mrnugget** [comment]
Hey! Do you think you'll work on this soon? If not, I think it's fine to close the PR and pick things up later once there's time.

**Comment by nervenes** [comment]
hi, sorry i don't think i'll be able to pick up where i left off any time soon, i'll go ahead and close this PR for now, thanks

**Pull request closed without merging**
