### PR TITLE
Read HTTP proxy from env

### PR DESCRIPTION
**Pull request by dylankyc**
This PR will use http proxy from env for downloading files.

### CODE REVIEW

**Comment by lichuan6** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@lichuan6 Thanks for this!

I think we should configure the proxy on the HTTP client, instead of on get requests. This will ensure it is used for everything (including `post_json` automatically).

In the environment you're working in, do web sockets work correctly? I don't think we can try and establish the web socket connection through an http proxy, but I am curious if we need to do anything to make them work too.

**Comment by lichuan6** [comment]
@ConradIrwin 

I've configured the proxy on the HTTP client, instead of on `get` or `post_json` methods.

As for web sockets through http proxy, is there a way to verify if WebSocket communication works through an HTTP proxy?

Thanks

**Comment by mikayla-maki** [comment]
@lichuan6 in development builds, if you click on the sign in button on the top right, sign into our service via github or keychain, and then open the collab panel on the bottom right, you should be able to test it. If you're able to make new channels and such in that UI, then you're good. The collaboration features all use websockets.

**Comment by bestgopher** [comment]
Hi, call HttpClient::get or HttpClient::post_json directly won't set proxy.

**Comment by lichuan6** [comment]
Hi @mikayla-maki 
I tried to sign in on the top right, however, I failed with the following error.
Screenshot 2024-01-30 at 21 51 50

Any idea how to fix it?

**Comment by mikayla-maki** [comment]
Try rebasing your branch :) we recently updated our protocol pretty significantly, and we're only able to with the latest version of the protocol.

**Comment by ConradIrwin** [comment]
Thanks for this, and sorry for all the back and forth here!

**Pull request merged**
