### PR TITLE
gpui: Add mouse selection support to Input example

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- N/A

---

Continue rest of #13534, extract from https://github.com/huacnlee/gpui-component/pull/26

## Demo

```bash
cargo run -p gpui --example input    
```

https://github.com/user-attachments/assets/2a674023-af58-4a63-9677-5843e4f35281

> The video is looks like response slow, but it is actully fast.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@huacnlee oops! I had already done this, but failed to push.

Does https://github.com/zed-industries/zed/pull/14350 work for you, or are there missing edge cases?

I kind of prefer storing the bounds and the handlers on the div to reduce boilerplate around hitbox tracking

**Comment by huacnlee** [comment]
I can try your version tomorrow. We can close this PR if you are already done.

**Comment by ConradIrwin** [comment]
:+1:

**Comment by huacnlee** [comment]
If you have time, please give me a TextArea example, I don't know how to implement that.

**Comment by huacnlee** [comment]
And is add hitbox will have any side effects? If that true I will try to avoid use that.

**Pull request closed without merging**
