### PR TITLE
Support ESLint flat configs

### PR DESCRIPTION
**Pull request by koddsson**
Hey 👋🏻!

I'm not 100% sure I've done this right and am happy to receive pointers. 

This change sets the `experimental.useFlatConfig` attribute to `true` if a `eslint.config.js` file exists in the workspace root and `false` if not.

## Further reading

- https://eslint.org/docs/latest/use/configure/configuration-files-new
- https://github.com/microsoft/vscode-eslint?tab=readme-ov-file#settings-options

Release Notes:

- Added ESLint flat config support ([#7271](https://github.com/zed-industries/zed/issues/7271)).

### CODE REVIEW

**Comment by koddsson** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Overall, looks fine — I would replace `.exists()` with `.is_file()` but that is a minor thing.

What I failed to do entirely is to test this.
Do you have a project example that 
1. works with old eslint format and produces some eslint errors on certain change?
2. a patch on top that replaces one config with another?

**Comment by koddsson** [comment]
> Do you have a project example that
> 
> 1. works with old eslint format and produces some eslint errors on certain change?
> 2. a patch on top that replaces one config with another?

Yeah I had some issues trying to test this myself. Here's a minimal project using the normal eslint config on the `main` branch and the flat config on the `flat-config` branch.

https://github.com/koddsson/eslint-configs-demo

You can see that ESLint is working correctly by running `npm it`.

**Comment by SomeoneToIgnore** [comment]
Thank you for the example — I see zero diagnostics returned from eslint for that, which is concerning.
image

What also is odd for me, that `npm it` (and `npm run test`) are both erroring for me?

```
Last login: Wed Feb 21 14:46:42 on ttys000
npm ru%
~/Downloads/eslint-configs-demo main:origin/main ❯ npm run test

> eslint-configs-demo@1.0.0 test
> eslint index.js


Oops! Something went wrong! :(

ESLint: 8.56.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/someonetoignore/Downloads/eslint-configs-demo/.eslintrc.js from /Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
.eslintrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename .eslintrc.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/someonetoignore/Downloads/eslint-configs-demo/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at module.exports [as default] (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2583:47)
    at loadConfigFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2667:20)
    at ConfigArrayFactory.loadInDirectory (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2877:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3792:18)
    at FileEnumerator._iterateFilesWithFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/cli-engine.js:797:48)
    at ESLint.lintFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli.js:421:36)
    at async main (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/bin/eslint.js:152:22)

~/Downloads/eslint-configs-demo main:origin/main ❯ npm it

up to date, audited 100 packages in 442ms

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> eslint-configs-demo@1.0.0 test
> eslint index.js


Oops! Something went wrong! :(

ESLint: 8.56.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/someonetoignore/Downloads/eslint-configs-demo/.eslintrc.js from /Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
.eslintrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename .eslintrc.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/someonetoignore/Downloads/eslint-configs-demo/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at module.exports [as default] (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2583:47)
    at loadConfigFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2667:20)
    at ConfigArrayFactory.loadInDirectory (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2877:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3792:18)
    at FileEnumerator._iterateFilesWithFile (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli-engine/cli-engine.js:797:48)
    at ESLint.lintFiles (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/cli.js:421:36)
    at async main (/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/bin/eslint.js:152:22)
npm ERR! code 2
npm ERR! path /Users/someonetoignore/Downloads/eslint-configs-demo
npm ERR! command failed
npm ERR! command sh -c eslint index.js

npm ERR! A complete log of this run can be found in: /Users/someonetoignore/.npm/_logs/2024-02-21T12_55_23_599Z-debug-0.log

~/Downloads/eslint-configs-demo main:origin/main ❯
```

so I cannot really say that it works for me, same thing is in VSCode:
image

I have also tried running that `pnpm` and converting the config module to something else to no avail, and not sure how to proceed with my poor frontend knowledge.
It something off with my development set-up there?

I would love to get down to fixing eslint there in VSCode and Zed first, and then test this PR before merging it.

**Comment by koddsson** [comment]
> What also is odd for me, that `npm it` (and `npm run test`) are both erroring for me?

Ah, my bad. I've pushed a fix for this.

I made sure to double check this in VSCode which is a good shout.

Normal JSON eslint config:

image

Flat Config:

image

But yeah weirdly I'm not getting errors in zed with the normal ESLint config either

image

**Comment by SomeoneToIgnore** [comment]
Thank you, that helped and I think I'm onto something: there's a 
```
[2024-02-21T16:31:15+02:00 INFO  lsp] 2 unhandled notification eslint/confirmESLintExecution:
{
  "scope": "local",
  "uri": "file:///Users/someonetoignore/Downloads/eslint-configs-demo/index.js",
  "libraryPath": "/Users/someonetoignore/Downloads/eslint-configs-demo/node_modules/eslint/lib/api.js"
}
```
log entry and I see zero returned messages in the LSP trace. 
Presumably, https://github.com/microsoft/vscode-eslint/blob/release/2.1.10/server/src/eslintServer.ts#L780-L784 dies not allow it to return anything.

It might be a wrong lead though, the whole situation is quite odd, so it will take some time before I can understand what's goind on and get back here.

**Comment by koddsson** [comment]
> log entry and I see zero returned messages in the LSP trace.

I figure someone else might be quicker and better at fixing this but I think it would be cool for me to try my hand at debugging this. If it's alright can I ask how you get the LSP logs/trace? I've opened this LSP window but that's just empty and I can't see anything in my terminal where I've run `cargo run`.

image

**Comment by SomeoneToIgnore** [comment]
Afk right now, so no screenshots, sorry: but you have to open the server dropdown on that exact panel and select the RPC trace bullet for eslint.

I think it all related to zed not responding to the message I've posted above, and one can hardcode that for all servers during init (ugly but whatever at this point — we need to prove that it works).

Meanwhile, there's a bug that a portion of LSP logs before LSP init request is not shown, so both log views for prettier won't show much.

**Comment by SomeoneToIgnore** [comment]
Well this is really embarrassing, but I've got it fixed: https://github.com/zed-industries/zed/pull/8197
I will test your PR soon.

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
With both patches merged into a single branch, I've used your project and removed the old *.json file.
Then, created the `eslint.config.js` with
```
export default [
    {
        rules: {
            semi: "error",
            "prefer-const": "error"
        }
    }
];
```
as the docs state, but got zero errors in both VSCode and Zed.
I also see that `[crates/zed/src/languages/typescript.rs:241:38] workspace_root.join("eslint.config.js").is_file() = true` so we do detect that normally.

Seems like something else has to be done? I propose do deal with VSCode and make it work first, and then share the flat config example that works here.

**Comment by koddsson** [comment]
> I propose do deal with VSCode and make it work first, and then share the flat config example that works here.

I actually have it working with VSCode see: https://github.com/zed-industries/zed/pull/8109#issuecomment-1956671183.

It looks like this isn't working because Zed is downloading `vscode-eslint@2.2.0` and this option was added in `vscode-eslint@2.3.0`. That version isn't available in the GitHub releases UI or via the API which is where Zed is getting the binary from. I'm not 100% sure why the 2.3.0 wouldn't be in that list. Maybe they've changed where the publish the assets?

**Comment by SomeoneToIgnore** [comment]
Yes, you're right that it's an older version that's the culprit and there's a patch release ongoing right now for Zed to fix that.

What I've tried to say, is that the flat config approach does not work for me in VSCode, does it for you?

**Comment by SomeoneToIgnore** [comment]
Oh, what a day, apologies for spamming, it does work for you but not for me for some reason.
Will investigate it all again.

**Comment by SomeoneToIgnore** [comment]
This is the PR: https://github.com/zed-industries/zed/pull/8197 and it should be in `main` already. 

I've just rechecked that `head~1` from `main` does download the old version for me (`2.1.10` now but `2.2.0` was before and did not work either) , and `main` is able to update that to a newer, `2.2.20-Insider` one and actually shows the errors:
image

---------------

While we are at it, can you tell me what am I doing wrong with VSCode not showing me anything for the flat config?
Here's my patch on top of your example:
```diff
diff --git a/.eslintrc.json b/.eslintrc.json
deleted file mode 100644
index f26487c..0000000
--- a/.eslintrc.json
+++ /dev/null
@@ -1,5 +0,0 @@
-{
-    "rules": {
-      "semi": "error"
-    }
-}
diff --git a/eslint.config.js b/eslint.config.js
new file mode 100644
index 0000000..d1de234
--- /dev/null
+++ b/eslint.config.js
@@ -0,0 +1,7 @@
+export default [
+    {
+        rules: {
+            semi: "error"
+        }
+    }
+];


```

and I see nothing:
image

**Comment by koddsson** [comment]
> While we are at it, can you tell me what am I doing wrong with VSCode not showing me anything for the flat config?

Ah my bad. I should have mentioned. You need to enable the same config in the ESLint extension in VSCode:

Find `ESLint` in the installed extensions list. Click on the cog wheel and select "Extension Settings" and then set the experimental flatConfig setting there. 


image

**Comment by SomeoneToIgnore** [comment]
Thank you, that did the trick.
But Zed's `main` with this PR merged on top does not produce anything yet, so it has to be something else.
I see this in the logs:
```
[2024-02-22T18:08:38+02:00 INFO  lsp] Language server with id 2 sent unhandled notification eslint/noConfig:
{
  "message": "No ESLint configuration found in /Users/someonetoignore/Downloads/eslint-configs-demo.",
  "document": {
    "uri": "file:///Users/someonetoignore/Downloads/eslint-configs-demo/index.js"
  }
}
```

Sorry, after today's debugging I would prefer not to look at eslint LSP for the rest of the week, so I would leave you with this error for now and will return back to it on Monday, if you would not find the culprit.

**Comment by koddsson** [comment]
I couldn't leave it, ended up cloning `microsoft/vscode-eslint`, building it and then referencing directly instead of `server_path`. That's version `vscode-eslint@2.4.4` and with a slight change to the workspace configuration I got something up and running:

image

Here's the diff I've done but not pushed:

```diff
diff --git a/crates/zed/src/languages/typescript.rs b/crates/zed/src/languages/typescript.rs
index ed30e50ac..bd87ab087 100644
--- a/crates/zed/src/languages/typescript.rs
+++ b/crates/zed/src/languages/typescript.rs
@@ -27,7 +27,7 @@ fn typescript_server_binary_arguments(server_path: &Path) -> Vec<OsString> {
 }
 
 fn eslint_server_binary_arguments(server_path: &Path) -> Vec<OsString> {
-    vec![server_path.into(), "--stdio".into()]
+    vec!["/Users/koddsson/src/koddsson/vscode-eslint/server/out/eslintServer.js".into(), "--stdio".into()]
 }
 
 pub struct TypeScriptLspAdapter {
@@ -237,6 +237,7 @@ impl LspAdapter for EsLintLspAdapter {
                     "name": workspace_root.file_name()
                         .unwrap_or_else(|| workspace_root.as_os_str()),
                 },
+                "problems": {},
                 "experimental": {
                     "useFlatConfig": workspace_root.join("eslint.config.js").is_file(),
                 },
```

So I think there's only to wait for `vscode-eslint` to publish a newer version onto GitHub releases and then we can look at this again.

**Comment by SomeoneToIgnore** [comment]
Beautiful!
Can we ensure that `"problems": {},` does not break anything for the current prettier?
Then we can merge this and wait for the new release.

**Comment by koddsson** [comment]
> Can we ensure that `"problems": {},` does not break anything for the current prettier?

Looks good to me :)

image

**Review by SomeoneToIgnore — APPROVED** [review]
Nice.

Thank you for all the patience, help and debugging, those 4 lines required some blood to get written.

**Comment by koddsson** [comment]
> Thank you for all the patience, help and debugging, those 4 lines required some blood to get written.

Thank _you_! I really appreciate it, this allowed me to apply the little Rust knowledge I have and learn a ton about Rust and Zed. I think there might be more eslint/zed stuff I could contribute and maybe it won't be as painful now that I know my way around a bit <3

**Comment by ljukas** [comment]
This still needs some more work. eslint flat config by default loads when there is one the THREE following file

`eslint.config.js`
`eslint.config.mjs`
`eslint.config.cjs`

in that order, see https://eslint.org/docs/latest/use/configure/configuration-files-new

This only sets this flag when the first one is detected, not the second two. 

@koddsson @SomeoneToIgnore

**Comment by fazulk** [comment]
is there something I'm missing here to get this working in `0.126.2` ? Attempting with `"eslint": "^8.57.0"` and `8.56` with no errors showing up in the editor and no auto fixes. 
```  
 "format_on_save": "on",
 "languages": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
```

**Comment by mrnugget** [comment]
@fazulk does anything show up in the language server logs? `debug: open language server logs`

**Comment by fazulk** [comment]
@mrnugget No errors of any kind, 

`ESLint library loaded from: /Users/fazulk/webz/work/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/api.js`

and RPC messages on save
`{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///Users/fazulk/webz/work/.storybook/main.ts"}}}`

If anyone has a working repo, where flat config is working, would love to test.

**Comment by mrnugget** [comment]
@fazulk what's the name of your eslint config file?

**Comment by koddsson** [comment]
> If anyone has a working repo, where flat config is working, would love to test.

Ah sorry @fazulk; it's not clear in this PR but it's explained in https://github.com/zed-industries/zed/issues/7271#issuecomment-1971854615 that we've managed to add the actual support but it's impossible to download new versions of `vscode-eslint` as the team at Microsoft has changed how the publish the library. Flat config support was added in `vscode-eslint@2.3.0` and `zed` is stuck on `2.2.0` until we solve the issue. 

We're discussing solutions in the linked issue.

**Pull request merged**
