### PR TITLE
Hide mouse cursor when typing starts

### LINKED ISSUE #4461: Hide Mouse Cursor While Typing
### Check for existing issues

- [X] Completed

### Describe the feature

Sometimes the mouse cursor obscures the text I am editing. Some other IDEs will temporarily hide the mouse cursor when you begin typing & I think it would be nice to have in Zed!

### If applicable, add mockups / screenshots to help present your vision of the feature

Xcode is a good example of this feature

https://github.com/zed-industries/community/assets/17223924/938d7223-8c7a-4966-af26-c04e07828af4

### PR DESCRIPTION
**Pull request by komi1230**
Closes  #4461
Release Notes:

- Added feature to hide mouse cursor when start typing (only in macOS)

This PR is related to https://github.com/zed-industries/zed/issues/4461.

But this PR is not perfect.
I have only macOS device and this `setHiddenUntilMouseMoves` feature works only in macOS.
For Windows and Linux environment, I want someone to implement this.

https://github.com/user-attachments/assets/fd35f7a2-ed1f-435c-b1ec-46578166171b

### CODE REVIEW

**Comment by komi1230** [comment]
@cla-bot check

**Comment by mrnugget** [comment]
Hey! Thanks for this! Works perfectly fine on macOS and behaves exactly like Sublime/VSCode.

I hopped on the branch to get the code to compile on Linux. Seems like to get it to work, more work is required.

**Comment by mrnugget** [comment]
Ah, I can't push to your branch, since it's the `main` branch. Here's the diff:

```diff
diff --git a/crates/gpui/src/platform/linux/platform.rs b/crates/gpui/src/platform/linux/platform.rs
index 1185c783be..e77539e45c 100644
--- a/crates/gpui/src/platform/linux/platform.rs
+++ b/crates/gpui/src/platform/linux/platform.rs
@@ -628,6 +628,9 @@ impl CursorStyle {
             CursorStyle::DragLink => Shape::Alias,
             CursorStyle::DragCopy => Shape::Copy,
             CursorStyle::ContextualMenu => Shape::ContextMenu,
+            // TODO: Hiding the cursor is not yet supported on Wayland, so we fall back to
+            // the default style.
+            CursorStyle::None => Shape::Default,
         }
     }

@@ -657,6 +660,9 @@ impl CursorStyle {
             CursorStyle::DragLink => "alias",
             CursorStyle::DragCopy => "copy",
             CursorStyle::ContextualMenu => "context-menu",                                                                        +            // TODO: This doesn't have an effect and doesn't hide the cursor.
+            // We need to handle this differently in the `set_cursor_style` methods.
+            CursorStyle::None => "none",
         }
         .to_string()
     }
```

**Comment by mrnugget** [comment]
Friendly awareness-ping: @apricotbucket28, since you worked on the cursor stuff on Linux :) Not saying you have to do it and I also think it's fine to merge this PR as long as it compiles, but just wanted to let you know about this.

**Comment by apricotbucket28** [comment]
Thanks for the ping! I've got this working on Wayland. Though I'd say that this feature needs a bit more polish since right now:

- Pressing keys outside a text box will still hide the cursor.
- Pressing a modifier key (e.g. control) over a symbol to go to definition will cause the cursor to hide.

**Comment by mrnugget** [comment]
> It seems like this should only trigger when input text actually changes 🙂

Yeah, we can probably move the behavior to `Editor`, I think.

**Comment by osa1** [comment]
> It seems like this should only trigger when input text actually changes

I think any key press should hide the mouse, with the exception of modifiers. FWIW Alacritty works this way, ctrl, alt etc on their own do not hide it but ESC does.

**Comment by JunkuiZhang** [comment]
> > It seems like this should only trigger when input text actually changes
> 
> I think any key press should hide the mouse, with the exception of modifiers. FWIW Alacritty works this way, ctrl, alt etc on their own do not hide it but ESC does.

I agree with @mrnugget's point. Hiding the mouse cursor with any key press can easily lead to unexpected behaviors.

**Comment by komi1230** [comment]
@mrnugget 
Sorry for late response and thank you for checking my PR.

To move this further, I cherry-picked @apricotbucket28's [commit](https://github.com/apricotbucket28/zed/commit/a733d2bf17cc682ccfbc141a8c3caea86716270a) just now.
The rest part is Windows and Linux(x11).

We need some discussion on how mouse cursor should behave, but I want this PR to focus only on adding `CursorStyle::None`.
I think this topic should be discussed in another issue or PR.

**Comment by HarshNarayanJha** [comment]
No required, but shouldn't this "Hide mouse cursor…" be toggled via some setting (in config)?

**Comment by mrnugget** [comment]
> We need some discussion on how mouse cursor should behave, but I want this PR to focus only on adding `CursorStyle::None`.

So do you only want to add the capability to hide the cursor? Or also hide it on typing?

I think if we change it to only hide the cursor in the editor, i.e. when typing into a text box, it's a fairly uncontroversial change, since most macOS apps behave that way.

(I still think you need my code to get it to work on X11)

**Comment by apricotbucket28** [comment]
Using `CursorStyle::None` for this behavior can be a bit confusing since it only hides the cursor until the user moves it. Would it make sense to refactor this into a separate function, maybe something like `hide_cursor_until_input`?

**Comment by mrnugget** [comment]
Hey! Friendly ping on this :) @komi1230 do you think you can work on the discussed changes, or do you want someone else to take over?

**Comment by mrnugget** [comment]
In the interest of keeping the number of open PRs low, I'm going to go ahead and close this due to *inactivity*. I still think it's a good change we should make (ever since seeing this PR I notice it a lot.) So if someone wants to pick it up, we can alwas reopen the PR.

**Pull request closed without merging**
