### PR TITLE
Simplify logic & add UI affordances to show model cache status

### PR DESCRIPTION
**Pull request by rowillia**
Release Notes:

- Adds UI affordances to the assistant panel to show which messages have been cached
- Migrate cache invalidation to be based on `has_edits_since_in_range` to be smarter and more selective about when to invalidate the cache and when to fetch.

Screenshot 2024-08-16 at 11 19 23 PM

Screenshot 2024-08-18 at 10 05 16 PM

I had originally added the lightening bolt on every message and only added the tooltip warning about editing prior messages on the first anchor, but thought it looked too busy, so I settled on just annotating the last anchor.

### CODE REVIEW

**Comment by iamnbutler** [comment]
Hey @rowillia! Excited to get this in.

- I'd like to change the icon, let's chat about some options below.
- Does the icon/button have any interactivity, or is it just meant to serve as an indicator that the message has been cached?
- Can you help me understand a bit about _what_ is cached? Is it per message? You mention editing prior messages invalidating the cache, how does that work?

Let me know if it is easier to jump into a quick call!

**Comment by iamnbutler** [comment]
For icons:

| database-zap | hard-drive | database |
|----------|----------|----------|
| CleanShot 2024-08-19 at 10 42 13@2x | CleanShot 2024-08-19 at 10 42 31@2x | CleanShot 2024-08-19 at 10 43 37@2x |

Do any of these off the shelf options from Lucide feel like they would fit?

I'd like to avoid using just the lighting bolt since we associate that with the language server/lsp/code actions in the UI.

**Comment by rowillia** [comment]
@iamnbutler 

- Thanks so much for taking a look!  I think the database-zap is probably the best fit - is that already in as an option?
- The cache doesn't currently have any interactivity, but I'd love to have the ability to give the user control over the anchors (or we can call then breakpoints as we do in the [Anthropic documentation](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching) - but my feeling was "breakpoint" already has a specific meaning in IDEs and it would be confusing to reuse) manually in a future PR.  I'd also (somewhat related to caching) like to allow users to "fork" a context at a given point to take advantage of the cache.
- The anchors are the points that we can effectively "resume" a conversation from without paying a large penalty (cached input tokens are 90% cheaper & substantially faster) and 3.5 Sonnet & 3.0 Haiku allows users to have up to 4 of them.  For example, processing ~85k cached input tokens with 3.5 Sonnet is ~3x faster than processing those input tokens with Haiku.

**Comment by rowillia** [comment]
@iamnbutler how does this look?

Screenshot 2024-08-19 at 12 00 30 PM

**Comment by rowillia** [comment]
Before:
CleanShot 2024-08-19 at 14 37 41

After:
CleanShot 2024-08-19 at 14 42 20

**Comment by rgbkrk** [comment]
I'm going to readily assume since @iamnbutler and you looked it over that we can give this a go in nightly for now and iterate.

**Comment by iamnbutler** [comment]
Yeah sounds good 👍

**Pull request merged**
