### PR TITLE
Add D Support

### LINKED ISSUE #204: D
### Check for existing issues

- [X] Completed

### Language

Dlang

### Tree Sitter parser link

https://github.com/gdamore/tree-sitter-d

### Language server link

https://github.com/Pure-D/serve-d

### Additional tools that helps with workspace

* [Code formatter](https://code.dlang.org/packages/dfmt)
* [Package manager](https://code.dlang.org/packages/dub) primary used for building projects
* [Mardown Cells executor](https://code.dlang.org/packages/md)

### PR DESCRIPTION
**Pull request by kassane**
Release Notes:

- fixed https://github.com/zed-industries/extensions/issues/204

cc: @gdamore

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
@kassane Thanks for the PR! The language registry API has changed a bit on main. You now need to register the Tree-sitter grammar in a separate call, and then reference it by name in the language `config.toml`. So I think you may need to adjust your code slightly. Can you rebase or merge main, and test this again?

Also, could you include screenshots of the syntax highlighting and outline view?

Just a heads up - we are very soon going to be moving most of Zed's built-in languages into installable extensions (https://github.com/zed-industries/zed/issues/7096). D is a major enough language that I'm ok with merging this in the meantime. But once the extension system lands, we will probably remove this code and put it into a new `D` repository under the new [zed-extensions](https://github.com/orgs/zed-extensions/repositories) GitHub org. We'll probably add you as a collaborator on that repo when we do it, if you're interested in helping maintain it.

**Comment by kassane** [comment]
> @kassane Thanks for the PR! The language registry API has changed a bit on main. You now need to register the Tree-sitter grammar in a separate call, and then reference it by name in the language `config.toml`. So I think you may need to adjust your code slightly. Can you rebase or merge main, and test this again?

Hi, @maxbrunsfeld :wave: 

Rebased again.

**Note:** In `typos.toml` needed add `inout` keywords for D (D v2.x) [[inout - spec](https://dlang.org/spec/const3.html#inout)].

> Also, could you include screenshots of the syntax highlighting and outline view?

Sadly, I have not uploaded any screenshots because macOS is not available. For the moment all I have available is Linux ( Linux support still in progress #7015).

However, based on [tree-sitter-d](https://github.com/gdamore/tree-sitter-d) support in another editor, it could probably be something similar.
**Helix w/ tree-sitter-d**:
image


> Just a heads up - we are very soon going to be moving most of Zed's built-in languages into installable extensions (#7096). D is a major enough language that I'm ok with merging this in the meantime. But once the extension system lands, we will probably remove this code and put it into a new `D` repository under the new [zed-extensions](https://github.com/orgs/zed-extensions/repositories) GitHub org. We'll probably add you as a collaborator on that repo when we do it, if you're interested in helping maintain it.

Great!! This will help a lot in organizing the project.

**Comment by maxbrunsfeld** [comment]
Ok, I’d like some D user to actually test this before merging. Could someone who is awaiting this feature help out with this PR by just manually testing a bit, and adding screenshots of the syntax highlighting and outline view?

**Comment by gdamore** [comment]
I can take a look this week.  I only just started playing with Zed
(informed by this PR actually).

I am keen to see how it copes with the serve-d extension which can be
finicky on large D repos like we have at Weka.

(I am also the author of several language plugins for Nova which you might
be familiar with.)

**Comment by gdamore** [comment]
One thing I might be interested in is the ability to extend Zed with
actions to run our unique build process and parse the specific output from
D code.  Those are significant quality of life items for those of us at
Weka.

**Comment by gdamore** [comment]
It appears to test this, I need to actually build zed?  Or are there test binaries I can try somewhere?

**Comment by kassane** [comment]
> It appears to test this, I need to actually build zed?  Or are there test binaries I can try somewhere?

Currently just building zed.

**Comment by gdamore** [comment]
I did install, but was unable to test the LSP integration as the LSP release only includes artifacts for x86. 

```
[2024-02-16T09:01:03-08:00 ERROR util] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
[2024-02-16T09:01:49-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:49-08:00 ERROR project] failed to start language server "serve-d": no asset found matching "serve-d_v0.7.6-osx-aarch64.tar.gz"
[2024-02-16T09:01:49-08:00 ERROR project] server stderr: Some("")
[2024-02-16T09:01:49-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR project] failed to start language server "serve-d": no asset found matching "serve-d_v0.7.6-osx-aarch64.tar.gz"
[2024-02-16T09:01:50-08:00 ERROR project] server stderr: Some("")
[2024-02-16T09:01:50-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR project] failed to start language server "serve-d": no asset found matching "serve-d_v0.7.6-osx-aarch64.tar.gz"
[2024-02-16T09:01:50-08:00 ERROR project] server stderr: Some("")
[2024-02-16T09:01:50-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR util] crates/zed/src/languages/d.rs:125: no cached binary
[2024-02-16T09:01:50-08:00 ERROR project] failed to start language server "serve-d": no asset found matching "serve-d_v0.7.6-osx-aarch64.tar.gz"
[2024-02-16T09:01:50-08:00 ERROR project] server stderr: Some("")
```

(The beta releases of serve-d do include arm64 artifacts.)

The Tree-Sitter integration appears good -- I'll paste up some syntax highlighting.

**Comment by gdamore** [comment]
Screenshot 2024-02-16 at 9 13 45 AM

**Comment by gdamore** [comment]
I'm not familiar with the outline view.

**Comment by gdamore** [comment]
Okay found reference to it as cmd-shift-O.  I tried that in this buffer and it doesn't work -- does it depend on the LSP integration?  Because if so that won't work on this ARM based Mac.

I will talk with the developer of the serve-d extension to see if he can release an ARM binary for the latest "release", or possibly cut another new release.

**Comment by kassane** [comment]
@maxbrunsfeld, Zed no have xz unpack?
```bash
Caused by:
    Invalid gzip header
[2024-02-29T10:30:39-03:00 ERROR project] server stderr: Some("")
[2024-02-29T10:30:40-03:00 ERROR util] crates/languages/src/d.rs:128: no cached binary
[2024-02-29T10:30:41-03:00 ERROR util] crates/languages/src/d.rs:128: no cached binary
[2024-02-29T10:30:41-03:00 ERROR project] failed to start language server "serve-d": failed to iterate over archive
```
**Linux - Preview**
image

**Comment by ConradIrwin** [comment]
Closing this for now. Language server support for extensions will land soon, which should make this easier. Sorry for the slow response!

**Pull request closed without merging**
