### PR TITLE
Add `yield` keyword highlight for Rust

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- Added `yield` keyword highlight for Rust

Ref:

- https://github.com/rust-lang/rust-analyzer/pull/7209
- https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting/highlight.rs#L177
- https://doc.rust-lang.org/reference/keywords.html?highlight=yield#reserved-keywords

In VS Code:
 
SCR-20240403-hrb

docs.rs:
https://docs.rs/async-stream/latest/async_stream/macro.try_stream.html

SCR-20240403-gpk

## Before

image

## After update in Zed
SCR-20240403-hqk

### CODE REVIEW

**Comment by huacnlee** [comment]
The `yield` was in `std::ops::Generator`.

https://dev-doc.rust-lang.org/beta/std/ops/trait.Generator.html

And rust-analyzer also added to support this:

https://github.com/rust-lang/rust-analyzer/pull/7209

Maybe this is why the docs.rs was highlighted it.

**Comment by osiewicz** [comment]
I mean, Rust playground highlights all the keywords from a list of [reserved keywords](https://doc.rust-lang.org/reference/keywords.html?highlight=yield#reserved-keywords) you've linked, but I'm still not sold on adding highlighting for them. 
The generators are not yet stable (though there are plans to [stabilize them in 2024 edition](https://blog.rust-lang.org/inside-rust/2022/04/04/lang-roadmap-2024.html)) - they've explicitly stated that syntax is still a work in progress, so if they do end up using `yield` keyword for that feature, we should revisit that PR.

**Comment by huacnlee** [comment]
@osiewicz I see.

How about the `crate` keyword, I just discovered that this one doesn’t exist either.

**Comment by osiewicz** [comment]
Oh, we don't have that? Then yeah, that sounds like a good addition. Let's do that in a separate PR though

**Comment by huacnlee** [comment]
Hi @osiewicz

Just to discuss this one last time, tree-sitter-rust actually has this added.

I actually saw this before submitting the PR, but I just forgot about it when I posted the reference link.

https://github.com/tree-sitter/tree-sitter-rust/pull/110/files

**Comment by osiewicz** [comment]
Fair, let's reopen this then. I'm still not sold on having support for reserved keywords, but upstream tree-sitter parity is a good argument

**Comment by osiewicz** [comment]
There's now a conflict after landing #10110 fyi

**Comment by osiewicz** [comment]
Thanks!

**Pull request merged**
