### PR TITLE
windows: Allow horizontal scroll with shift + scroll

### PR DESCRIPTION
**Pull request by nathanielkatesimon**
Release Notes:

- Horizontally scroll when holding down the Shift key and using the scroll wheel

https://github.com/zed-industries/zed/assets/95680272/e6480f9c-0f6a-4f47-b700-a3657a75716f

### CODE REVIEW

**Comment by nathanielkatesimon** [comment]
@cla-bot check'

**Comment by mikayla-maki** [comment]
Interesting solution here, doing it at the platform layer instead of in the app.

**Comment by nathanielkatesimon** [comment]
I've updated my PR @mikayla-maki . And yeah, a very similar solution was used for Linux so I just copied it

**Comment by mikayla-maki** [comment]
Thank you!

**Pull request merged**
