### PR TITLE
docs: Document building with `RUST_FONTCONFIG_DLOPEN=on env` on Linux

### PR DESCRIPTION
**Pull request by curiousercreative**
Fixed Debian (and derivative) builds https://github.com/zed-industries/zed/issues/12778

Release Notes:

- N/A

### CODE REVIEW

**Comment by curiousercreative** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
This doesn't seem like it should be on the primary path, as plenty of people have been building on Linux without this specific environment variable set.

I think if we do add this to the docs at all it should just be a note at the bottom to address a particular scenario.

**Comment by curiousercreative** [comment]
These seems to be outdated already!

**Comment by curiousercreative** [comment]
I actually don't even have the issue on a second machine running the same arch, distro and version, so it's an isolated issue with my install and I agree there's nothing to do here

**Pull request closed without merging**
