### PR TITLE
void

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by abebeos** [comment]
@cla-bot check

**Review by williamdes — APPROVED** [review]

**Comment by d1y** [comment]
Haha, but I believe it will be supported by both linux/windows in the near future.👀

**Comment by abebeos** [comment]
> the near future

In software, this can be an eternity...

But it's anyways friendlier to inform visitors immediately.

**Comment by williamdes** [comment]
I believe @aminya and myself are trying to make it build on linux. There is nice PRs for this and some are already merged:
- #6854 
- #6855 
- #6859

**Comment by abebeos** [comment]
@williamdes , consider this here

- https://github.com/zed-industries/zed/issues/6868

I guess that many folks would contribute to get zen on their platform.

**Comment by maxdeviant** [comment]
Thank you for the PR, @abebeos, but we're closing in favor of https://github.com/zed-industries/zed/pull/6870.

**Comment by abebeos** [comment]
@maxdeviant , all good, informs even better.

**Pull request closed without merging**
