### PR TITLE
gpui: Add Global marker trait

### PR DESCRIPTION
**Pull request by osiewicz**
This should prevent a class of bugs where one queries the wrong type of global, which results in oddities at runtime.

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
I'm curious why the existing type stuff didn't work?

**Comment by osiewicz** [comment]
It is error prone when you're e.g. refactoring globals (or querying globals in general) - if you use wrong type as the argument of `cx.global`, you're only gonna notice that at runtime.

**Comment by osiewicz** [comment]
It is also easier to tell what is global in the codebase.

Call us to get a quote on better type safety. :P

**Comment by ConradIrwin** [comment]
Makes sense! I was imagining "oddities" to include type confusion and other odd things, but this makes sense to me

**Comment by maxdeviant** [comment]
> Makes sense! I was imagining "oddities" to include type confusion and other odd things, but this makes sense to me

Ah yea, the "oddities" is probably better read as "panics" 🤣

**Pull request merged**
