### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by ayshmnmm**
Release Notes:

- N/A

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
@ayshmnmm , in order to merge the PR, we need the CLA signed as the bot above says.

**Comment by ayshmnmm** [comment]
@cla-bot check

**Comment by SomeoneToIgnore** [comment]
https://s3.amazonaws.com/cla-bot-logs/zed-industries-a902fce5-7612-4ae5-80eb-dcae58650b2e says that 

> 2024-07-24T10:11:44.345Z INFO Some commits from the following contributors are not signed with a valid email address: Ayushman. 

Could be that your GitHub has a default e-mail, different from your local one, used to create the commits.

I can push this change myself and you can do the sign dance in the next PR — let me know if that works for you.

**Comment by ayshmnmm** [comment]
Thank you @SomeoneToIgnore that works for me, still trying to figure this out.

**Comment by SomeoneToIgnore** [comment]
I think you need to visit https://github.com/settings/emails and ensure you see the right e-mail there.
Then, ensure the local set-up has the same e-mail, so `git log` on your changes display that (bot had pasted relevant commands for updating it: https://github.com/zed-industries/zed/pull/15015#issuecomment-2247494297)

When all that has the same e-mail, future commits created with these settings should pass the CLA check.

Anyway, thanks for the spot, https://github.com/zed-industries/zed/pull/15078 will fix it.

**Pull request closed without merging**
