### PR TITLE
Add `-f` to curl commands

### PR DESCRIPTION
**Pull request by injust**
Release Notes:

- Updated curl commands with `-f` for improved error handling ([#14346](https://github.com/zed-industries/zed/issues/14346)).

### CODE REVIEW

**Comment by injust** [comment]
@cla-bot check

**Comment by injust** [comment]
cc @ConradIrwin

I don't think the source for https://zed.dev/download is in this repo? It'd be great if that page could be updated too.

**Comment by ConradIrwin** [comment]
@injust Thanks! I think we should probably *not* include -L as we don't expect this url to redirect. Adding `-f` makes sense. I could go either way on `sS` (mostly the progress bar is a bit of extra noise, but in the case of network problems, you'll be able to see what's up). Maybe in the interest of brevity we omit it, but happy to have it if you think it's useful?

**Comment by injust** [comment]
This doesn't affect me personally as I install via Homebrew, so I don't feel too strongly about these. But others may want to chime in here.

> I think we should probably _not_ include -L as we don't expect this url to redirect.

OTOH, if you ever _do_ decide to make the URL redirect, it'll be a bit painful. I believe a redirect will turn `curl URL | sh` into a no-op that does _not_ error.

I saw that the script is in this repo at https://github.com/zed-industries/zed/blob/main/script/install.sh. Maybe down the road you might redirect it to https://github.com/zed-industries/zed/raw/main/script/install.sh or https://raw.githubusercontent.com/zed-industries/zed/main/script/install.sh? Pretty reasonable scenario to account for.

> I could go either way on `sS` (mostly the progress bar is a bit of extra noise, but in the case of network problems, you'll be able to see what's up). Maybe in the interest of brevity we omit it, but happy to have it if you think it's useful?

`-s` _hides_ the progress bar and `-S` shows error messages. I think it does what you're thinking of?

**Comment by ConradIrwin** [comment]
I've gone ahead and updated zed.dev with `curl -f`.

`-S` is only needed if you specify `-s`, otherwise curl outputs errors normally.

We can always update things again if we need to add the `-L`. Currently we [upload the script](https://github.com/zed-industries/zed/blob/47ed69ecc740028825bfb3340e05d79d7c2b708f/.github/workflows/deploy_cloudflare.yml#L42) to Cloudflare so it can be served even if we break https://zed.dev or Github is having teething troubles.

**Comment by injust** [comment]
> `-S` is only needed if you specify `-s`, otherwise curl outputs errors normally.

Oh, maybe I misunderstood. I thought you wanted to get rid of the progress bar for brevity?

**Comment by ConradIrwin** [comment]
Sorry for being hard to understand :D `omit -sS` for brevity.

**Comment by injust** [comment]
Should be good to go now

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
