### PR TITLE
Remove workspace border, avoid the main window having double borders

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- Fixed main window border, avoid double borders.

## Diff (Left is Before, Right is After)

SCR-20240306-g2v
SCR-20240306-g0x

Reference to Safari:
SCR-20240306-ejo

## More Theme tests
SCR-20240306-g0d
SCR-20240306-g0j
SCR-20240306-g0q

SCR-20240306-fu9

### CODE REVIEW

**Comment by huacnlee** [comment]
## More Theme tests

SCR-20240306-g0d
SCR-20240306-g0j
SCR-20240306-g0q


SCR-20240306-g1u
SCR-20240306-g2c
SCR-20240306-g2p
SCR-20240306-g20

**Review by SomeoneToIgnore — APPROVED** [review]
LGTM, but is somewhat subtle to my eye, hence calling for @maxdeviant to verify it's what we want.

**Review by maxdeviant — APPROVED** [review]
Thanks, this looks good!

**Comment by dangh** [comment]
Zed has become handsome again. Thank you.

**Pull request merged**
