### PR TITLE
Stop using xtask for clippy

### PR DESCRIPTION
**Pull request by ConradIrwin**
This fixes an extra 10 second delay when needing to recompile xtask, and
allows passing arbitrary clippy args (like --allow-dirty)

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxdeviant** [comment]
@ConradIrwin Can we keep the `xtask clippy` and just not use it in CI?

I prefer using `cargo xtask` as my interface.

**Comment by ConradIrwin** [comment]
Sure.

I had been hoping to delete xtask completely, as it seems too heavy and slow to be useful, and I want to avoid incorporating it into the typical zed development workflow. That said, if you prefer it, I'm not going to stop you.

In particular I want to avoid using it for developer tasks and for CI runs where the expectation is that your rust cache is out of date.

For another comparison point, the rewritten licenses script takes 13ms to run. In the case that xtask doesn't need to be recompiled `cargo xtask licenses` takes 400ms to run (not a big deal, but it outputs a bunch of rustc output too), in the case that xtask does need to recompile it takes 9s (which is a calculable fraction of a PR run of a few minutes).

**Comment by maxdeviant** [comment]
> I had been hoping to delete xtask completely, as it seems too heavy and slow to be useful, and I want to avoid incorporating it into the typical zed development workflow. That said, if you prefer it, I'm not going to stop you.

I feel the opposite. I would prefer if more of our tooling—at least locally, doesn't have to be in CI—used `cargo xtask`.

Writing shell scripts or the occasional JS script just feels way worse than writing Rust when you need to do something more complex.

Granted, `cargo xtask clippy` wasn't that, but some of the other tooling I have in mind would be better off written in Rust, IMO.

> For another comparison point, the rewritten licenses script takes 13ms to run. In the case that xtask doesn't need to be recompiled `cargo xtask licenses` takes 400ms to run (not a big deal, but it outputs a bunch of rustc output too), in the case that xtask does need to recompile it takes 9s (which is a calculable fraction of a PR run of a few minutes).

Just for context, `cargo xtask licenses` is a _new_ workflow, not a rewrite of an existing one.

I wrote it to keep track of which crates were missing a license file.

**Comment by ConradIrwin** [comment]
Right; but if we want to run it on CI (which it seems like we should - I just added it), it should be fast. If we use xtask it will be slow some of the time, which is frustrating.

I do agree that hypothetically there are use-cases where running a tool in rust would be better (probably the closest is script/zed-local, but again I'd get pretty annoying if I had to wait extra time to compile that thing every time I changed branch).

I think a better approach for that use-case is how `./script/symbolicate` works where it installs the binary on first run, and re-uses the cached binary.

**Pull request merged**
