### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by drale2k**
Release Notes:

- N/A

### CODE REVIEW

**Comment by drale2k** [comment]
@cla-bot check

**Comment by osiewicz** [comment]
Hey, thanks for your PR! I don't think we need a release note for it, as it's not really a user facing change.

**Comment by drale2k** [comment]
> Hey, thanks for your PR! I don't think we need a release note for it, as it's not really a user facing change.

Sure thing. Actually i added a release note which went missing. I can re-add it if needed

**Comment by osiewicz** [comment]
Yeah, I've edited the original post

**Comment by osiewicz** [comment]
Thanks!

**Pull request merged**
