### PR TITLE
Add strikethrough to deprecated methods in CompletionsMenu

### PR DESCRIPTION
**Pull request by Adam-Alani**
Release Notes:

- Added ([#8390](https://github.com/zed-industries/zed/issues/8390)).
- Also Grays out deprecated methods

Before

image

After

image

### CODE REVIEW

**Comment by Adam-Alani** [comment]
@cla-bot check

**Comment by bbb651** [comment]
It would be nice to also derank them in the suggestions, the sorting works by separating the suggestions into weak and strong suggestions based on the fuzzy matcher, maybe weak suggestions should always put deprecated items last and strong suggestions keep them as is? I think that's strikes a fairly good balance

**Comment by evrsen** [comment]
I agree, the order is almost a must for me. I also think it would be nice to have their foreground colours dimmed, that would give me an instant feedback without actually looking at the text.

**Comment by Adam-Alani** [comment]
> I think it would be nice to have their foreground colours dimmed, that would give me an instant feedback without actually looking at the text.

Good Call, Ill set deprecated methods to text muted

image



> It would be nice to also derank them in the suggestions, the sorting works by separating the suggestions into weak and strong suggestions based on the fuzzy matcher, maybe weak suggestions should always put deprecated items last and strong suggestions keep them as is? I think that's strikes a fairly good balance

Ill read up and see if i can do this :)

**Comment by evrsen** [comment]
do we need the strikethrough? how does other editors do it?

**Comment by JosephTLyons** [comment]
> do we need the strikethrough? how does other editors do it?

VS Code uses strikethrough and muted colors:

SCR-20240308-saha

**Comment by mikayla-maki** [comment]
Since VSCode doesn't seem to de-rank deprecated completions, I think this is should be good to go.

**Comment by mikayla-maki** [comment]
If someone wants to add that in a follow up PR, feel free :)

**Pull request merged**
