### PR TITLE
 Add LSP support for Elm

### LINKED ISSUE #4595: LSP Support for Elm
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/elm-tooling/elm-language-server

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by w0rm**
Hi folks! This is a promised PR from @absynce and me to add LSP support for Elm (closes #4595).

There are a couple things that need to be improved in [elm-language-server](https://github.com/elm-tooling/elm-language-server), but this is already looking good.

One interesting bit that we've discovered: the progress percentage is not rounded in the [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node/issues/1412) package according to the LSP spec. Other language servers based on this package may be suffering from this too. 

Release Notes:

- Added LSP support for Elm ([#4595](https://github.com/zed-industries/zed/issues/4595)).

### CODE REVIEW

**Comment by w0rm** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Looks like the documentation and tree-sitter queries for code highlighting seems to be missing entirely, please check https://github.com/zed-industries/zed/pull/6748 and similar PRs for that part.

**Comment by w0rm** [comment]
@SomeoneToIgnore this only adds support for LSP, syntax highlighting has been implemented in https://github.com/zed-industries/zed/pull/2782. 

I've updated the documentation with a link to `elm-language-server`.

**Review by SomeoneToIgnore — COMMENTED** [review]
So many languages coming in, I have missed the previous PR apparently, sorry for the confusion.

One last question: does it work for you?
I've opened https://github.com/azimuttapp/azimutt saw errors and tried opening its `frontend` directory separately, just to be sure it breaks for me there too.

I have `elm` installed via homebrew, but nonetheless:

```
Reading elm.json from file:///Users/someonetoignore/Downloads/azimutt/frontend/elm.json
Elm version 0.19.1 detected.
{"shortMessage":"Command failed with exit code 1: elm make","command":"elm make","escapedCommand":"elm make","exitCode":1,"stdout":"\r                            \rDependencies ready!\n","stderr":"-- MISSING SOURCE DIRECTORIES ----------------------------------------- elm.json\n\nI need a valid elm.json file, but the \"source-directories\" field lists the\nfollowing directories:\n\n    .elm-spa/defaults\n    .elm-spa/generated\n\nI cannot find them though. Are they missing? Are there typos?\n\n","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
Error parsing files for file:///Users/someonetoignore/Downloads/azimutt/frontend/elm.json:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Program.<anonymous> (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/compiler/program.js:548:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/compiler/program.js:28:58)
Unhandled Rejection at: Promise [object Promise] reason:, Error: No Elm workspace contains /Users/someonetoignore/Downloads/azimutt/frontend/src/Main.elm
Unhandled Rejection at: Promise [object Promise] reason:, Error: No Elm workspace contains /Users/someonetoignore/Downloads/azimutt/frontend/src/Main.elm
Unhandled Rejection at: Promise [object Promise] reason:, Error: No Elm workspace contains /Users/someonetoignore/Downloads/azimutt/frontend/src/Main.elm
NoWorkspaceContainsError: No Elm workspace contains /Users/someonetoignore/Downloads/azimutt/frontend/src/Main.elm
    at ElmWorkspaceMatcher.getProgramFor (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/common/util/elmWorkspaceMatcher.js:48:19)
    at handleSaveOrOpen (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/common/providers/diagnostics/diagnosticsProvider.js:93:54)
    at CallbackList.invoke (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at /Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/common/util/textDocumentEvents.js:43:33
    at CallbackList.invoke (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at /Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/@elm-tooling/elm-language-server/out/common/util/documentEvents.js:32:29
    at handleNotification (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/someonetoignore/Library/Application Support/Zed/languages/elm-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
```

This is my first-ever interaction with Elm so I'm sure I could've forgotten something, but logs are quite odd: they state they parsed the https://github.com/azimuttapp/azimutt/blob/main/frontend/elm.json file and it's incorrect?

**Comment by w0rm** [comment]
@SomeoneToIgnore the project is using [elm-spa](https://www.elm-spa.dev), that needs some initialisation.

The error you're getting is because of the missing `.elm-spa` directory, that is referenced from `elm.json`:

```
"source-directories": [
        "src",
        ".elm-spa/defaults",
        ".elm-spa/generated"
    ]
```

I got it working by running `npm istall` && `npm run setup` from the frontend directory:

azimutt

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks for the crash course, indeed the server works now.

**Pull request merged**
