### PR TITLE
Add support for GitLab self-hosted instances

### LINKED ISSUE #18012: Add setting for custom Gitlab base URL
### Check for existing issues

- [X] Completed

### Describe the feature

Zed will automatically detect if the Git remote is a `github.com` or `gitlab.com` base URL and link commits to their appropriate location on the web. However, if the git repo remote is a custom Gitlab url such as `gitlab.mycompany.com` there is no way to utilize this feature. In theory as long as you specify it still follows Gitlab url conventions you could override the automatic detection and force it to use the base url of `gitlab.mycompany.com` and all the other url generation logic could stay the same. 

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by MichaelBitard**
Closes #18012

Release Notes:

- Added support for gitlab self hosted instances

[test.webm](https://github.com/user-attachments/assets/57f2028f-8161-445c-bc7b-e25c9d55da3a)

### CODE REVIEW

**Comment by MichaelBitard** [comment]
@cla-bot check

**Comment by MichaelBitard** [comment]
What I did:
- removed the base_url from the GitHostingProvider trait because now it is discovered from the URL
- added the base_url inside the ParsedGitRemote struct to be used later

What is missing to be ready:
- [ ] Support fot `git@` URLs

**Comment by WeetHet** [comment]
Could you also add support for blame avatars? It would be nice to see the way you're going to do that, so I can finally complete #11043

**Comment by MichaelBitard** [comment]
@WeetHet I looked into it this week-end and it seems like a lot of work ( It seems simpler for gitlab.com )

Anyway, maybe I'll try something this week for gitlab.com, on another PR

**Comment by maxdeviant** [comment]
Thanks for your work on this PR, but I don't think this is the approach we want to go with.

**Comment by MichaelBitard** [comment]
No problem, if you want to elaborate a little bit (or give me some hints?), I could try something more in the spirit of what you want to go with?

**Pull request closed without merging**
