### PR TITLE
project panel: Update file icon when editing filename

### PR DESCRIPTION
**Pull request by d1y**
Before:

before

After:

after

Release Notes:

- Added ProjectPanel editing show icon

### CODE REVIEW

**Comment by d1y** [comment]
Do we need unit testing for these modifications?

**Comment by SomeoneToIgnore** [comment]
I do not think it's possible to test the rendering in any way.

**Review by SomeoneToIgnore — COMMENTED** [review]
I think we should not do anything when renaming directories: those will stay directories even if granted a .txt suffix, as the video shows:

https://github.com/zed-industries/zed/assets/2690773/dcd44f37-8245-41e7-afb8-f3ecef4d4bc9

**Comment by SomeoneToIgnore** [comment]
Also wondering, whether we should guess anything for file renames, if those do not contain `.`? 
If one would type `rsuby_file.txt` there will be a bunch of flickering, esp. in the first three characters, while in reality, we cannot know a file type before `.` or exact match (e.g. `Dockerfile`) occurs.

**Comment by d1y** [comment]
> I think we should not do anything when renaming directories: those will stay directories even if granted a .txt suffix, as the video shows:
> 
>  Screen.Recording.2024-05-21.at.15.27.31.mov

Thank you for informing us
The folder will be ignored

**Comment by d1y** [comment]
> Not sure how feasible, but wortk considering whether we should guess anything for file renames, if those do not contain `.`
> 
> If one would type `rsuby_file.txt` there will be a bunch of flickering, esp. in the first three characters, while in reality, we cannot know a file type before `.` or exact match (e.g. `Dockerfile`) occurs.

I saw the flickering issue, so starting matching icons again when the length is greater than 2 can alleviate it 👀

```rs
            if !filename.is_empty() && filename.len() > 2 {
                icon = FileIcons::get_icon(Path::new(&filename), cx);
            }
```

**Comment by SomeoneToIgnore** [comment]
I would make it 3, unless you're aware of any widespread 2-letter files.

**Comment by SomeoneToIgnore** [comment]
Indeed, thanks.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks!

**Pull request merged**
