### PR TITLE
windows: Fix panicking on startup

### LINKED ISSUE #10954: [Windows] `ERROR_INITIALIZATION_FAILED` panic on startup
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On latest main branch the Windows build crashes on startup.

Debug mode logs:
```
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED" at C:\Users\jasoney\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:354:18
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_smart_subtransport_git
  10: git_smart_subtransport_git
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: DispatchMessageW
  18: DispatchMessageW
  19: CallNextHookEx
  20: KiUserCallbackDispatcher
  21: NtUserCreateWindowEx
  22: CreateWindowExW
  23: CreateWindowExW
  24: CreateWindowExW
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: git_smart_subtransport_git
  51: BaseThreadInitThunk
  52: RtlUserThreadStart
```

### Environment

Windows 11 (build 22631.3447)
32 GB RAM

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by JunkuiZhang**
### Connection:
Closes #10954 

Release Notes:

- N/A

### CODE REVIEW

**Comment by kvark** [comment]
So we need the HINSTANCE now? The old code only assigned HWND - https://github.com/zed-industries/zed/pull/10880/files#diff-b38258c3b6a51a8f791374836458afd4612ac04d28b558e53b9de1e073488282L85

**Review by kvark — APPROVED** [review]
Confirmed that `winit`'s implementation does obtain HINSTANCE for both RWH-0.5 and RWH-0.6. So it makes sense to do. Just unclear how did it work before...
ciu5v4qf1dg11

**Comment by kvark** [comment]
They are doing it slightly differently though, maybe we should do exactly the same?
https://github.com/rust-windowing/winit/blob/7006c7ceca948942914c42193fdd0b90e2dc50d5/src/platform_impl/windows/window.rs#L366

**Comment by JunkuiZhang** [comment]
> They are doing it slightly differently though, maybe we should do exactly the same? https://github.com/rust-windowing/winit/blob/7006c7ceca948942914c42193fdd0b90e2dc50d5/src/platform_impl/windows/window.rs#L366

This makes sense, the `hmodule` returned should be unique, but I believe using the same implementation as `winit` will help avoid potential bugs.

BTW, nice pic😂

**Comment by ognevny** [comment]
thanks, it works on `x86_64-pc-windows-gnu`

**Comment by integrajerome** [comment]
Works on x86_64... but github copilot can't be started (failed to iterate over).

**Comment by MatinAniss** [comment]
> Works on x86_64... but github copilot can't be started (failed to iterate over).

Unrelated problem

**Comment by integrajerome** [comment]
> > Works on x86_64... but github copilot can't be started (failed to iterate over).
> 
> Unrelated problem

Ok sorry.

**Comment by integrajerome** [comment]
Merge ?

**Comment by integrajerome** [comment]
@ConradIrwin please merge it

**Comment by mikayla-maki** [comment]
@integrajerome Don't spam PRs.

**Comment by integrajerome** [comment]
> @integrajerome Don't spam PRs.

Sorry. My builds are very usable on amd64 and osx but my company forces me to use Windows. That why I Realy want this branch to be merged.

**Comment by integrajerome** [comment]
> @integrajerome Don't spam PRs.

Sorry for spaming

**Comment by mikayla-maki** [comment]
Thank you @JunkuiZhang / @kvark !

**Pull request merged**
