### PR TITLE
Environment loading fixes

### LINKED ISSUE #19040: direnv direct mode prefers binaries outside of direnv PATH
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Now that direnv defaults to `direct` mode (as of #18536), I noticed that language servers in my system PATH get run instead of the ones in my direnv PATH. It looks like this is due to the shell sourcing my `~/.zshrc`, which effectively undoes some of the direnv settings (I believe [the relevant code is here](https://github.com/zed-industries/zed/blob/eea600ecc370bf548ea1801cf30545e5474d40cf/crates/project/src/environment.rs#L280-L288)).

For example:

1. Start with an empty `PATH`.
2. In my `~/.zshrc` I have `export PATH=$HOME/bin:$PATH` (`PATH=$HOME/bin`).
3. My .envrc sets `PATH=/other/dir:$PATH` (`PATH=/other/dir:$HOME/bin`).
4. Zed launches `zsh -l` which sources `~/.zshrc` again (`PATH=$HOME/bin:/other/dir:$HOME/bin`).

In contrast, `shell_hook` mode relies on the direnv hook in my `~/.zshrc` which gets run at the end, ensuring I get the desired direnv PATH as expected.

It would be nice if the `direct` mode behavior could be flipped so that the direnv PATH takes priority, similar to the `shell_hook` mode.

### Environment

Zed: v0.157.2 (Zed Preview)
OS: macOS 15.0.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by WeetHet**
Closes #19040
Addresses the problem with annoying error messages on windows (see comment from SomeoneToIgnore on #18567)

Release Notes:

- Fixed the bug where language servers from PATH would sometimes be prioritised over the ones from `direnv`
- Stopped running environment loading on windows as it didn't work anyways due to `SHELL` not being set

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Thanks for fixing the message bit too.

I think the windows conditional compilation clause has to be put as
https://github.com/zed-industries/zed/pull/19147/files

as on this branch currently I get
```
   Compiling notifications v0.1.0 (C:\work\zed\crates\notifications)
warning: function `load_direnv_environment` is never used
  --> crates\project\src\direnv.rs:34:14
   |
34 | pub async fn load_direnv_environment(
   |              ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

during `cargo run` on Windows.

**Comment by WeetHet** [comment]
> Thanks for fixing the message bit too.
> 
> I think the windows conditional compilation clause has to be put as [#19147 (files)](https://github.com/zed-industries/zed/pull/19147/files)
> 
> as on this branch currently I get
> 
> ```
>    Compiling notifications v0.1.0 (C:\work\zed\crates\notifications)
> warning: function `load_direnv_environment` is never used
>   --> crates\project\src\direnv.rs:34:14
>    |
> 34 | pub async fn load_direnv_environment(
>    |              ^^^^^^^^^^^^^^^^^^^^^^^
>    |
>    = note: `#[warn(dead_code)]` on by default
> ```
> 
> during `cargo run` on Windows.

Sure, I've hidden that behind a `cfg`-guard too. Could you ask @mrnugget to review this too, because I'm unsure if moving direnv loading to the end could break something

**Comment by mrnugget** [comment]
I think it's fine if the direnv env takes a higher precedence (which it does by overwriting the other env variables)

**Comment by WeetHet** [comment]
> I think it's fine if the direnv env takes a higher precedence (which it does by overwriting the other env variables)

Is there anything else I need to do before we merge this?

**Comment by mrnugget** [comment]
Nope! Thank you!

**Pull request merged**
