### PR TITLE
Correctly merge settings for vtsls

### PR DESCRIPTION
**Pull request by ConradIrwin**
Release Notes:

- Fixed vtsls initialization_options in project settings files

### CODE REVIEW

**Comment by m1guer** [comment]
bugs fixed?

**Comment by ConradIrwin** [comment]
Previously the overrides would not always apply.

**Comment by baptisteArno** [comment]
This should close https://github.com/zed-industries/zed/issues/17046 I think!

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
