### PR TITLE
.zed/settings.json: format markdown on save

### PR DESCRIPTION
**Pull request by ConradIrwin**
This should stop prettier yelling at me when I update documentation

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxdeviant** [comment]
@ConradIrwin Maybe this should go in your personal settings?

I think we specifically turned this off cause some folks on the team don't like it.

**Comment by ConradIrwin** [comment]
I think we should either enable this, or disable the prettier check on CI; it's otherwise super annoying to have to make PRs twice.

We could maybe just do it in the docs directory?

**Comment by maxdeviant** [comment]
> I think we should either enable this, or disable the prettier check on CI; it's otherwise super annoying to have to make PRs twice.

Well I don't think we should disable Prettier in CI. It's important that the docs are well-formatted for diffability, especially since we get a lot of external contributions.

But in your case I'm not sure why making a change to your personal settings doesn't do the trick, since I haven't heard anyone else having an issue with the behavior.

> We could maybe just do it in the docs directory?

I think that would be the least disruptive option, if we do intend to codify this in the project settings.

**Comment by ConradIrwin** [comment]
I don't want to fix this in my settings because I'm a small minority of zed contributors, it seems best that everyone has things set up right.

Looking at our 144 markdown files, currently 6 don't pass prettier.

Running it manually gives: https://github.com/zed-industries/zed/pull/21468/commits/db28a0ecdeca531a1b6cc76e038293d742cda24c, which
* Removing double space after `.` in legal/terms.md and extensions/EXTRACTING
* Replacing `~~~rust` with <code>```rust</code> in crates/gpui/docs
* Adding/removing a blank line in crates/vim/README.md and crates/terminal_veiew/README.md

I think those are relatively uncontroversial (with perhaps the exception of the double-space after . thing); so think it'd probably be better to merge this than to set up a new zed config file for just docs.

**Comment by ConradIrwin** [comment]
From talking with @maxdeviant the problem here is the project setting then overrides his user settings (which have been customized to disable format on save globally).

Going to close for now, but it'd be nice to find a way to either default format_on_save to on for markdown (which we can't do because prettier is too opinionated for many people's tastes) or have a mechanism to set "defaults" for a project that can be overridden by user settings.

**Pull request closed without merging**
