### PR TITLE
Add Prettier support for Vue, Markdown and PHP

### PR DESCRIPTION
**Pull request by claytonrcarter**
Current prettier support w/i Zed leaves out a few languages that are officially supported by prettier. In particular, Vue and Markdown are supported by the core prettier project, and PHP is supported via an official plugin. I didn't see any open issues for this, but I have been wondering for months why `"formatter": "prettier"` wasn't working on my PHP files. Now that Zed is open source, I was able to find out why, and fix it. :smile:

I have been using this with PHP files daily for a week+ now, and I have also used it successfully with Vue and Markdown files, though not as extensively. I looked around and did not see any tests for specific prettier language integrations, but if I missed them please let me know and I'll add some tests.

**Notes**
-  I did not add support for Ruby (which has an official prettier plugin) because it seems to require some external dependencies (notably, Rudy and some Gems). When those are present on the system and `$PATH`, prettier will will work just fine on Ruby files if the plugin is set up similar to how the PHP plugin is set up (I tried it), and I can add that in here, if desired. The PHP plugin is pure JS (as I recall) and doesn't have this issue.
- I did *not* add support for languages that have "community" plugins, though I do note that Zed already ships with prettier support for svelte enabled, which – if I understand correctly – is powered by a community plugin. If desired, I could look at adding support/configuration to enable prettier support for things like elm, erb, glsl, bash, toml. Bash, in particular, *I* would find useful. :smile:

Release Notes:

- Added prettier support for Vue, Markdown and PHP

### CODE REVIEW

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
Unfortunately, the whole prettier pipeline involves installing node packages for plugins and other interactions with external world, so there are no tests indeed.

I've given it a spin manually on a random PHP project from GitHub (https://github.com/harundogdu/PHPExamples) and found that it does fail for me with this error:

```
[2024-02-16T16:41:55+02:00 ERROR project::prettier_support] Failed to install default prettier: prettier & plugins install: fetching latest npm versions: fetching latest npm version for package @prettier/plugin-php/standalone.js: failed to execute npm info subcommand:
stdout: "{\n  \"error\": {\n    \"code\": \"ENOENT\",\n    \"summary\": \"ENOENT: no such file or directory, open '/Users/someonetoignore/work/zed/zed/@prettier/plugin-php/standalone.js/package.json'\",\n    \"detail\": \"This is related to npm not being able to find a file.\\n\"\n  }\n}\n"
stderr: "npm ERR! code ENOENT\nnpm ERR! syscall open\nnpm ERR! path /Users/someonetoignore/work/zed/zed/@prettier/plugin-php/standalone.js/package.json\nnpm ERR! errno -2\nnpm ERR! enoent ENOENT: no such file or directory, open '/Users/someonetoignore/work/zed/zed/@prettier/plugin-php/standalone.js/package.json'\nnpm ERR! enoent This is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/someonetoignore/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-02-16T14_41_55_862Z-debug-0.log\n"
```

it seems to break for me even if I wipe all `node`, `prettier` and `languages` directories in Zed's application support directory, so I'm very curious to know how does that work for you for a week+ 🙂 

I do not think it's a regression that came with this PR, but we have to fix it: existing web languages (vue, ts, js, etc.) usually install their own prettier and Zed reuses that, but PHP projects seem to do that less frequently and formatting for them will break.

Additionally, I'm not sure I find something reformatting my *.md files exciting.
It is not very intrusive now, as it seems, but it does reformat list items to something odd.
Consider https://github.com/rust-lang/rust-analyzer/blob/master/README.md#quick-links as an example

image

I find `* ` syntax more common around the repositories, so many people may get dissatisfied with this change.
Is there a way to configure prettier to avoid doing that? If not, let's omit the *.md part?

**Comment by maxdeviant** [comment]
> Additionally, I'm not sure I find something reformatting my *.md files exciting.
> It is not very intrusive now, as it seems, but it does reformat list items to something odd.
> Consider https://github.com/rust-lang/rust-analyzer/blob/master/README.md#quick-links as an example

Maybe we make it configurable?

Zed not formatting Markdown files with Prettier has been something that I've found myself missing over VS Code.

**Comment by SomeoneToIgnore** [comment]
It is configurable up to the point that Zed has a `prettier` settings section where anything can go, presumably, the *.md options too.
But the defaults is the question — would it be ok for you to have those list items reformatted? If so, let's ignore that entire paragraph of mine.

**Comment by maxdeviant** [comment]
> It is configurable up to the point that Zed has a `prettier` settings section where anything can go, presumably, the *.md options too. But the defaults is the question — would it be ok for you to have those list items reformatted? If so, let's ignore that entire paragraph of mine.

I personally have always used `-` for lists over `*`. But ever since Prettier started supporting Markdown formatting I have used it whenever I write Markdown, so I just take whatever formatting Prettier spits out.

**Comment by claytonrcarter** [comment]
> it seems to break for me even if I wipe all node, prettier and languages directories in Zed's application support directory, so I'm very curious to know how does that work for you for a week+ 🙂

OK, so this may be my misunderstanding: are the `prettier` plugins intended to be installed and shipped with Zed, or only within the user's project?

In my case, the projects that I've been working on have `@prettier/plugin-php` installed into `node_modules`, which I believe is where Zed has been loading it from for me. So, that error "makes sense" if the project that you tried didn't have `@prettier/plugin-php` installed. (Not that is should error like that, but it at least explains why it was.)

FWIW, I recall seeing similar errors in the logs (not `ENOENT` though) when I have used Zed in projects w/ prettier configured but *without* `prettier-plugin-tailwindcss` installed.  Those errors were a lot less gross looking though. 😄 

> existing web languages (vue, ts, js, etc.) usually install their own prettier and Zed reuses that, but PHP projects seem to do that less frequently and formatting for them will break.

Again, maybe this was my misunderstanding, but how does this differ from how the Astro and Svelte prettier config is working? (Sorry, I'm not familiar with those languages, but I can dig in more if need be.) 

I was thinking that prettier would only work (or at least only for these plugins) if the users project had it configured and setup, and part of that setup involves installing the plugins.

> Additionally, I'm not sure I find something reformatting my *.md files exciting.

Is it OK if I say this again: maybe this was my misunderstanding 😄, but my aim with this was to allow projects that have prettier configured to be able to use it for all applicable files. As noted in the PR description, I have been stumped why Zed had prettier support but it didn't seem to be working in projects/files where prettier was configured and otherwise working fine.

If Zed's prettier support is meant to be more of a "global" install of prettier, rather than a local install, then I have to rethink parts of this.

**Comment by SomeoneToIgnore** [comment]
> are the prettier plugins intended to be installed and shipped with Zed, or only within the user's project?

For whatever buffer applicable for prettier formatting, Zed's prettier support tries to find prettier for any buffer formatted, by looking for `package.json` and `node_modules` contents recursively up to `/` (we cache those lookups, but have to do the deep ones due to the possibility of monorepo set-ups).
If something's found, Zed tries to use that and then whatever configs and plugins are used is determined by the project configuration (e.g. same package.json or other prettier-specific files).
If such lookup fails, Zed tries to set-up a "default prettier" that gets those plugins installed along with prettier into the application support directory. This is what fails for me in the message above.

So, while Astro, Svelte & co are usually going down the package.json path, it's not that common for php, as it seems to me (I might be wrong, I have zero knowledge of PHP ecosystem).

I will try to look at the issue on Monday, but those `Failed to install default prettier: prettier & plugins install: fetching latest npm versions: fetching latest npm version for package` are `anyhow` error contexts and can be searched in our code to see where it breaks — feel free to poke at it if you're interested.

Please disregard my *.md-related comments, I think we should get that in after all, but that plugin issue is very sad and I would not want to make the error surface even more with PHP.

**Comment by claytonrcarter** [comment]
> That should work (I tried it with a PDF that's already on the site by hand)

Thank you! That's very helpful! 

> This is what fails for me in the message above

Ah, so now for some "speculation debugging": the bundle for the PHP plugin is in `./standalone.js` or `./src/index.mjs`, but neither of those paths are recognized by the searching code at https://github.com/zed-industries/zed/blob/main/crates/prettier/src/prettier.rs#L241-L249. Because of that, I listed the plugin name as `@prettier/plugin-php/standalone.js` to get this working. That works if `@prettier/plugin-php` is installed, but if Zed tries to install a package called `@prettier/plugin-php/standalone.js`, it obviously won't work.

I'll see if I can tinker with that for a fix, or at least a workaround. 😄

**Comment by claytonrcarter** [comment]
> neither of those paths are recognized by the searching code

OK, adding `src` to the search paths and removing `standalone.js` from the plugin name seems to have worked. I no longer get the error, and it seems to install the plugin and start formatting PHP correctly.

Question: is it better to add `src` to the search paths, or to just add `standalone.js`, or – because this seems to be an oddball – should there be a more specific workaround? For now, I'll push a change that adds `standalone.js` w/ a comment that it's for the PHP plugin, but I can change that to whatever you think is best.

Thanks all of the feedback on this!

**Comment by SomeoneToIgnore** [comment]
I think the reason I went on with the specific files were import errors that node 18 had when tried to import the directory — that might be as well my mistake, but let's be on the safe side and keep the fine-grained list of plugins for now, thank you for adjusting this.

**Review by SomeoneToIgnore — APPROVED** [review]
image


Yes, much better, now the plugin gets used during formatting.
Thank you for a deeper dive into all that, let's see how many people will get surprised with the new, default formatting capabilities 🙂

**Pull request merged**
