### PR TITLE
Set the default DPI awareness for Zed

### PR DESCRIPTION
**Pull request by JunkuiZhang**
### Description

This is a part of 
- #8809 

Release Notes:
- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
By default, windows apps (win32 apps mainly) are unable to automatically handle DPI scaling. Without such work, applications will appear blurry.

Using the `manifest` file is the Microsoft recommanded way, and any app developed using `gpui` should follow this method, maybe we should doc it somewhere?

**Comment by mikayla-maki** [comment]
I'm unsure if this is the way we should be handling this, cc: @kvark who has more expertise in graphics. Is this something the renderer needs to take into account? If not, happy to merge this PR.

**Comment by mikayla-maki** [comment]
Also, we should put this in the Zed crate, not GPUI, as GPUI has no access to bundling.

**Comment by mikayla-maki** [comment]
> Using the `manifest` file is the Microsoft recommanded way, and any app developed using `gpui` should follow this method, maybe we should doc it somewhere?

When GPUI is more developed, we should add these kinds of bundling requirements into `gpui.rs`, or our own bundling tool. But for now, this should be fine.

**Pull request merged**
