### PR TITLE
Astro LSP path leading slash in Windows

### PR DESCRIPTION
**Pull request by alvgaona**
This PR attempts to fix the issue of Astro LSP not spinning up due to a message like this one:

```
Language server error: astro-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'E:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro_1\node_modules\@astrojs\language-server\bin\nodeServer.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.5.0
```

The problem is related to the WASM runtime in which the extensions run. The `env::current_dir()` is abstracted away from the base platform in which Zed is running. You can check this with `env::constants::OS` which returns an empty string.

`env::current_dir()` returns this path: `"/C:\\Users\\alvga\\AppData\\Local\\Zed\\extensions\\work\\astro_1/node_modules/@astrojs/language-server/bin/nodeServer.js"`. You will see a leading forward slash which then is passed to the `zed::Command` and interprets it as some disk, and ultimately having the first presented log.

Release Notes:

- N/A

### CODE REVIEW

**Comment by alvgaona** [comment]
Until this commit, this is not yet fixed because `#[cfg(target_os = "windows")]` and `#[cfg(not(target_os = "windows"))]` do not work in extensions as far as I'm aware. 

How could we make this work? So we can trim the leading forward slash when we're running on Windows, still not sure if it's feasible as we're running within the WASM runtime.

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
> The problem is related to the WASM runtime in which the extensions run. The `env::current_dir()` is abstracted away from the base platform in which Zed is running. You can check this with `env::constants::OS` which returns an empty string.

> `env::current_dir()` returns this path: `"/C:\\Users\\alvga\\AppData\\Local\\Zed\\extensions\\work\\astro_1/node_modules/@astrojs/language-server/bin/nodeServer.js"`. You will see a leading forward slash which then is passed to the `zed::Command` and interprets it as some disk, and ultimately having the first presented log.

Thank you for the analysis, I think this is what we're supposed to be fixing, not a single LSP server with `split_off` hacks for it.

**Comment by SomeoneToIgnore** [comment]
> Until this commit, this is not yet fixed because `#[cfg(target_os = "windows")]` and `#[cfg(not(target_os = "windows"))]` do not work in extensions as far as I'm aware.

I think that works?
https://github.com/zed-industries/zed/blob/181c3724aa99e67ebc5f8147dce8d6ee2f77276d/crates/languages/src/typescript.rs#L297-L300

**Comment by alvgaona** [comment]
> > The problem is related to the WASM runtime in which the extensions run. The `env::current_dir()` is abstracted away from the base platform in which Zed is running. You can check this with `env::constants::OS` which returns an empty string.
> 
> > `env::current_dir()` returns this path: `"/C:\\Users\\alvga\\AppData\\Local\\Zed\\extensions\\work\\astro_1/node_modules/@astrojs/language-server/bin/nodeServer.js"`. You will see a leading forward slash which then is passed to the `zed::Command` and interprets it as some disk, and ultimately having the first presented log.
> 
> Thank you for the analysis, I think this is what we're supposed to be fixing, not a single LSP server with `split_off` hacks for it.

I think it makes much better sense. Not sure where to start though. I'll check if it's affecting Svelte LSP too.

**Comment by SomeoneToIgnore** [comment]
> I'll check if this affecting Svelte LSP too which will confirm that we need to fix this in a much more general approach.

If your analysis is right and `env::current_dir()` returns `\` (which is right), then this sentence is very odd.

It does affect every place where  `env::current_dir()`.
Example for emmet: https://github.com/zed-industries/zed/pull/20257

**Comment by alvgaona** [comment]
> > I'll check if this affecting Svelte LSP too which will confirm that we need to fix this in a much more general approach.
> 
> If your analysis is right (which is right) and `env::current_dir()` returns `\` , then this sentence is very odd.
> 
> It does affect every place where `env::current_dir()`. Example for emmet: #20257

Yes. I said that just to confirm but you just showed that other PR that's confirming it.

**Comment by alvgaona** [comment]
I'll create an issue off of this.

**Pull request closed without merging**
