### PR TITLE
Fix bug with keymaps flickering in mouse menu

### PR DESCRIPTION
**Pull request by babyccino**
Fixes a bug where Vim bindings would flash in the mouse context menu and then be replaced by the default keybindings. Also fixes those bindings not being usable while the mouse context menu was open.

Release Notes:

- Fixed bug where Vim bindings were not available when mouse context menu was open

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@babyccino thanks for figuring this out!

Unfortunately this doesn't account for the case when the inline assistant is open, as we still need to disable vim in that mode...

I've pushed up a more precise check which I think covers the case we need, and will merge when green.

**Comment by babyccino** [comment]
> @babyccino thanks for figuring this out!
> 
> Unfortunately this doesn't account for the case when the inline assistant is open, as we still need to disable vim in that mode...
> 
> I've pushed up a more precise check which I think covers the case we need, and will merge when green.

Ah good call, I never use the assistant so I didn't notice that 😂. I'm wondering if it wouldn't be simpler to just have a Vim context which is always on when vim mode is on

**Comment by ConradIrwin** [comment]
It’s a tricky interaction because we don’t want vim enabled in the rename editor - but it’s just an editor - and so the way keybinding works we can’t easily distinguish by context

**Comment by babyccino** [comment]
> It’s a tricky interaction because we don’t want vim enabled in the rename editor - but it’s just an editor - and so the way keybinding works we can’t easily distinguish by context

I'm thinking if you just had a Context just like `"Vim"` or something which was is separate from your `"vim_mode"` then you could have bindings in the project panel which are only active when vim mode is active because (I think?) at the moment there's no way to know if vim mode is on when you're outside the editor. ATM Zed just loads/unloads those vim default keybindings when it's turned on/off

**Pull request merged**
