### PR TITLE
Stop relying on binary location to be in `libexec` on Linux

### LINKED ISSUE #13360: Stop relying on binary location to be in `libexec` on Linux
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, the Linux CLI searches for the main binary at `<cli_binary_dir>/../libexec/zed-editor`. However, some distros like Arch [discourage the use of `libexec`](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) and recommend packagers to use `lib/<pkg_name>` instead.

You can see [here](https://aur.archlinux.org/cgit/aur.git/tree/use-lib-not-libexec.patch?h=zed-preview) that the `zed-preview` AUR package has to patch the zed source, to be able to put the main binary in the recommended directory. However, as the maintainer of the `zed-preview-bin` package, I don't have this option, as I'm using the binaries as they are distributed on the Zed website.

This situation could be improved if the CLI simply searched for the main binary in both the `libexec` and the `lib/zed` directories.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by Zollerboy1**
This fixes #13360 by adding fallback directories that are searched by the CLI if the main executable cannot be found in the `libexec` directory.

Release Notes:

- Added the fallback directories `lib/zed` and `lib/zed-editor` for the main executable search in the CLI ([#13360](https://github.com/zed-industries/zed/issues/13360)).

### CODE REVIEW

**Comment by Zollerboy1** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@Zollerboy1 Thanks for packaging zed for Arch!

It looks like the patch in #13360 only uses `../lib/zed/zed-editor`, but this change adds additionally `../lib/zed-editor/zed-editor`. Is it possible to just use one?

**Comment by Zollerboy1** [comment]
@ConradIrwin of course, that'd be possible for sure. I just thought that if we already add a fallback directory, why not add a few. On Arch, `lib/zed` is the correct directory to use, as the recommendation there is `lib/<package_name>`, but, considering that `zed` is quite a common executable name, I can definitely imagine that there are other distros, where someone would want to put the binary into `lib/zed-editor` instead. That's why I made both use-cases possible.

If you don't think that will be needed though, I can remove `lib/zed-editor` from the fallback directories again.

**Comment by ConradIrwin** [comment]
Let's only add the one we're actually going to use; and add it to the notes for package maintainers here: https://github.com/zed-industries/zed/blob/c477c12956f46cd41a23a3b896ee57ef4b672f86/docs/src/development/linux.md#L83

If we need yet another for a different distro's policy we can add it when we know what the policy requirements are.

**Comment by Zollerboy1** [comment]
All right, this should do it then.

**Comment by ConradIrwin** [comment]
Thanks! I pushed up a change to tidy up the code a little, and will merge when green.

**Pull request merged**
