### PR TITLE
editor: Fix DeleteToPreviousWordStart and DeleteToNextWordEnd interaction with newlines

### LINKED ISSUE #5285: A bit counterintuitive `delete word` behavior
**Is your feature request related to a problem? Please describe.**
`delete word` behavior is different to other code editors like sublime text and vs code when deleting non-word characters.

**Describe the solution you'd like**
Make it like in vs code.

**Describe alternatives you've considered**
No alternatives available.

**Screenshots (Videos)**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

This is vs code:

https://user-images.githubusercontent.com/24634903/179301934-fa882b9f-f54d-4e27-9210-866f4c250693.mov

This is sublime text 4:

https://user-images.githubusercontent.com/24634903/179300781-03a2920f-87a4-4027-bd0e-4ded90631d0e.mov

This is Zed:

https://user-images.githubusercontent.com/24634903/179301926-c289fa62-8079-478c-8968-abdec7057816.mov

### PR DESCRIPTION
**Pull request by kjzl**
Closes #5285, #14389

Changes:
- `DeleteToPreviousWordStart` now deletes '\n' separately from preceding words and whitespace.
- `DeleteToNextWordEnd` now deletes '\n' and any following whitespace separately from subsequent words.
- Added an `ignore_newlines` flag to both actions to optionally retain the old behavior.

These modifications align the behavior more closely with other popular editors like VSCode and Sublime:
- `DeleteToPreviousWordStart` now matches the default <Ctrl+Backspace> action in those editors.
- `DeleteToNextWordEnd` becomes more intuitive and closely resembles the default <Ctrl+Delete> behavior in those editors.

Release Notes:

- Improved `DeleteToPreviousWordStart` and `DeleteToNextWordEnd` interactions around newlines. You can opt-in into the previous behavior by adding {"ignore_newlines": true} to either action's binds in your keymap. ([#5285](https://github.com/zed-industries/zed/issues/5285), [#14389](https://github.com/zed-industries/zed/issues/14389))

### CODE REVIEW

**Comment by kjzl** [comment]
Feedback is welcome.
I am not sure if adding the old behavior through DeleteToPreviousWordStartIgnoringNewlines really is necessary - The way I see it this is a bug and I don't know of any editors which replicate this behavior or why this would be useful.

If this commit gets merged I would be open to also tackle a similar issue with DeleteToNextWordEnd to match the behavior of VSCode/Sublime. Issue #14389 contains a video showing the problem in that particular case.

**Comment by mikayla-maki** [comment]
> I am not sure if keeping the old behavior through DeleteToPreviousWordStartIgnoringNewlines really is necessary 

I don't really think it is personally, I'd prefer to just fix the bug and remove the old behavior entirely.

cc: @SomeoneToIgnore, lmk if you disagree :)

**Comment by mikayla-maki** [comment]
This PR also wants to fix this issue: ref: https://github.com/zed-industries/zed/pull/16963

**Review by SomeoneToIgnore — APPROVED** [review]
I would personally add this as a parameter into the `DeleteToPreviousWordStart`, there could be a 

```rs
struct DeleteToPreviousWordStart {
    include_newlines: bool,
}
```

definition, and its default `include_newlines = false` will keep the current behavior for everyone.

But if it already looks nice to everybody, why not merge it.
Any follow-ups to make it more ergonomic are good too.

I'll leave the decision to Mikayla, as the reviewer with most context here.

**Comment by kjzl** [comment]
If I understand correctly the author of the other PR is saying this behaviour comes from vim? In that case I'd be in favor of merging the other PR and closing mine.
But then I'd suggest to update the default keymaps of editors where the new commands are default behaviour.

If that's not correct and this is indeed a bug, I would rather merge my PR after I remove the extra command keeping the old behaviour.

**Comment by kjzl** [comment]
I believe this PR is now ready for merge with the implemented changes.

1. Compatibility for Vim users:
   - The default Vim behavior can be retained by setting `ignore_newlines` to true for these actions.

2. Consideration for default Vim keymap:
   - The only reference to these actions in the default Vim keymap is [here](https://github.com/zed-industries/zed/blob/c9b4c8c49894ce06f2bd60742fc8e1ea0df22a22/assets/keymaps/vim.json#L319).
   - We should review if the actual Vim default behavior is intended for that specific vim mode key bind, and if so, we may need to update it accordingly.

I would appreciate any feedback.

**Review by SomeoneToIgnore — APPROVED** [review]
Sorry for the delay, I hoped for @mikayla-maki to step in, but let's merge this: for me, this looks fine and all my feedback is incorporated.

Thank you for working on this!

**Pull request merged**
