### PR TITLE
Add docs and add `cargo-about` dependency for Flatpak bundling errors

### LINKED ISSUE #12745: Cargo cannot find licenses
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I build zed for flatpak, cp cannot find the licenses

```
sh '/home/rashadgasimli/Downloads/zed/script/flatpak/bundle-flatpak'
+ getopts h flag
+ export ZED_BUNDLE=true
+ ZED_BUNDLE=true
+ channel=dev
++ script/get-crate-version zed
+ version=0.140.0
+ export RELEASE_VERSION=0.140.0
+ RELEASE_VERSION=0.140.0
++ cut -c 1-7
++ git rev-parse HEAD
+ commit=0c7e745
++ rustc --version --verbose
+ version_info='rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2'
++ echo 'rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2'
++ grep host
+ host_line='host: x86_64-unknown-linux-gnu'
+ target_triple=x86_64-unknown-linux-gnu
+ export 'RUSTFLAGS=-C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib'
+ RUSTFLAGS='-C link-args=-Wl,--disable-new-dtags,-rpath,$ORIGIN/../lib'
+ cargo build --release --target x86_64-unknown-linux-gnu --package zed --package cli
warning: zed@0.140.0: Info: using '0c7e745be8ebb6c83d5b89ce5be6e197eefe45cc' hash for ZED_COMMIT_SHA env var
    Finished `release` profile [optimized + debuginfo] target(s) in 0.44s
+ strip target/x86_64-unknown-linux-gnu/release/zed
+ strip target/x86_64-unknown-linux-gnu/release/cli
+ suffix=
+ '[' dev '!=' stable ']'
+ suffix=-dev
++ mktemp -d
+ temp_dir=/tmp/tmp.qZWg5zUIa2
+ zed_dir=/tmp/tmp.qZWg5zUIa2/zed-dev.app
+ mkdir -p /tmp/tmp.qZWg5zUIa2/zed-dev.app/bin /tmp/tmp.qZWg5zUIa2/zed-dev.app/libexec
+ cp target/x86_64-unknown-linux-gnu/release/zed /tmp/tmp.qZWg5zUIa2/zed-dev.app/libexec/zed-editor
+ cp target/x86_64-unknown-linux-gnu/release/cli /tmp/tmp.qZWg5zUIa2/zed-dev.app/bin/zed
+ mkdir -p /tmp/tmp.qZWg5zUIa2/zed-dev.app/lib
+ rm -rf '/tmp/tmp.qZWg5zUIa2/zed-dev.app/lib/*'
++ find_libs
++ ldd target/x86_64-unknown-linux-gnu/release/zed
++ cut '-d ' -f3
++ grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\)'
+ cp /lib64/libasound.so.2 /lib64/libxkbcommon.so.0 /lib64/libxkbcommon-x11.so.0 /lib64/libxcb.so.1 /lib64/libz.so.1 /lib64/libxcb-xkb.so.1 /lib64/libXau.so.6 /tmp/tmp.qZWg5zUIa2/zed-dev.app/lib
+ mkdir -p /tmp/tmp.qZWg5zUIa2/zed-dev.app/share/icons/hicolor/512x512/apps
+ cp crates/zed/resources/app-icon-dev.png /tmp/tmp.qZWg5zUIa2/zed-dev.app/share/icons/hicolor/512x512/apps/zed.png
+ mkdir -p /tmp/tmp.qZWg5zUIa2/zed-dev.app/share/icons/hicolor/1024x1024/apps
+ cp crates/zed/resources/app-icon-dev@2x.png /tmp/tmp.qZWg5zUIa2/zed-dev.app/share/icons/hicolor/1024x1024/apps/zed.png
+ export DO_STARTUP_NOTIFY=true
+ DO_STARTUP_NOTIFY=true
+ export APP_ICON=zed
+ APP_ICON=zed
+ [[ dev == \p\r\e\v\i\e\w ]]
+ [[ dev == \n\i\g\h\t\l\y ]]
+ [[ dev == \d\e\v ]]
+ export 'APP_NAME=Zed Devel'
+ APP_NAME='Zed Devel'
+ mkdir -p /tmp/tmp.qZWg5zUIa2/zed-dev.app/share/applications
+ envsubst
+ cp assets/licenses.md /tmp/tmp.qZWg5zUIa2/zed-dev.app/licenses.md
cp: cannot stat 'assets/licenses.md': No such file or directory
```

### Environment

OS: Fedora Linux 40 (Workstation Edition) x86_64
Host: ASUS TUF Gaming F15 FX506HC_FX506HC (1.0)
Kernel: Linux 6.8.11-300.fc40.x86_64
Uptime: 3 hours, 5 mins
Packages: 2117 (rpm), 62 (flatpak-user)
Shell: zsh 5.9
Display (NCP004D): 1920x1080 @ 144Hz [Built-in]
DE: Gnome 46.2
WM: Mutter (Wayland)
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark [GTK2/3/4]
Icons: WhiteSur-dark [GTK2/3/4]
Font: Noto Sans (11pt) [GTK2/3/4]
Cursor: WhiteSur (24px)
Terminal: GNOME Terminal 3.50.1
Terminal Font: Source Code Pro (10pt)
CPU: 11th Gen Intel(R) Core(TM) i5-11400H (12) @ 4.50 GHz
GPU 1: Intel UHD Graphics @ 1.45 GHz [Integrated]
GPU 2: NVIDIA GeForce RTX 3050 Mobile [Discrete]
Memory: 5.26 GiB / 15.36 GiB (34%)
Swap: 1.17 GiB / 8.00 GiB (15%)
Disk (/): 140.21 GiB / 475.34 GiB (29%) - btrfs
Disk (/run/media/rashadgasimli/2B73-5B78): 8.00 KiB / 14.63 GiB (0%) - vfat [External]

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### LINKED ISSUE #12850: Flatpak build deps and documentation
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following the instructions for building/bundling a flatpak package on Linux, there are a series of errors encountered:
1. assets/licenses is missing
2. flatpak-builder is not found
3. something about appstream files not being valid

### Environment

```text
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by curiousercreative**
- Fixed https://github.com/zed-industries/zed/issues/12850
- Fixed https://github.com/zed-industries/zed/issues/12745

Release Notes:

- N/A

### CODE REVIEW

**Comment by someone13574** [comment]
Thanks!

**Comment by mikayla-maki** [comment]
Couldn't we just add the license generation to the flatpak bundling?

**Comment by someone13574** [comment]
> Couldn't we just add the license generation to the flatpak bundling script?

Or better, the `build-linux` script since that is the one which actually needs it.

**Comment by mikayla-maki** [comment]
true! It might be nice to change that script to only run if it doesn’t find one on your system, I know it takes a while.

**Comment by ConradIrwin** [comment]
I made the change to script/bundle-linux in #12870

**Pull request closed without merging**
