### PR TITLE
WGSL Tree-sitter

### PR DESCRIPTION
**Pull request by AlexanderEkdahl**
Basic WGSL syntax highlighting/understanding. 

image

### CODE REVIEW

**Comment by AlexanderEkdahl** [comment]
@cla-bot check

**Comment by AlexanderEkdahl** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Since it's only about tree-sitter, I would suggest making an extension out of it and submit it to https://github.com/zed-industries/extensions instead of here: this will help keeping Zed compile times "reasonable".

**Comment by bennetbo** [comment]
> Since it's only about tree-sitter, I would suggest making an extension out of it and submit it to https://github.com/zed-industries/extensions instead of here: this will help keeping Zed compile times "reasonable".

Looks like someone submitted a PR for a wgsl extension already <https://github.com/zed-industries/extensions/pull/62>

**Comment by SomeoneToIgnore** [comment]
Beautiful!
I would close this one then, and propose to improve things there, thank you for the PR nonetheless.

Our general plan is to move away all "external" language support to extensions, but currently there seems to be no LSP support there, so we're accepting some PRs into this repo meanwhile.

**Pull request closed without merging**
