### PR TITLE
Terminal panel: Add hide panel button

### PR DESCRIPTION
**Pull request by Terraciano**
Release Notes:

- Added a hide terminal button on the top right of the terminal panel

317248918-ddb42a37-550d-462a-ab64-80c51083ba16

### CODE REVIEW

**Comment by Otterpocket** [comment]
I'm not against this idea, but I do have some feedback.

- I would expect an "X" to close all the tabs also. Maybe a minimise or hide style icon would be more suitable if this simply hides the terminal and retains the tabs.

- Other features such as assistant, project panel etc, do not have a dedicated close button which makes this change alone a little inconsistent.

- Adding this feature means there are now 2  ui icons that can hide the terminal.

**Comment by maxdeviant** [comment]
> * I would expect an "X" to close all the tabs also. Maybe a minimise or hide style icon would be more suitable if this simply hides the terminal and retains the tabs.

Agreed on this. I think we need to use a different icon than the "X".

**Comment by baldwindavid** [comment]
To be fair, it appears the "X" is what VSCode uses to "hide" a terminal and tabs stay intact when clicking it.

That being said, I agree this is kind of surprising to me. Moreso, as @Otterpocket mentions we now have two icons to hide the terminal. My two cents is we should hold off on adding another button unless the other can at least be hidden. The design paradigm seems to have been set that the dock visibility is managed via the bottom toolbar and this would be a departure.

Beyond that, it's just pure personal preference from me. I'd just as soon have almost no buttons anywhere because I prefer keyboard-driven actions so buttons are just clutter to me.

**Comment by Terraciano** [comment]
Screenshot 2024-03-27 at 17 20 01

As @baldwindavid mentioned, we went for the close button precisely because it's what VSCode has, but we've changed it to the dash since its more intuitive in this case. 

To stick to both the personal preference and design paradigm, we could show or hide this button extending the settings, similar to how `show_call_status_icon` works. 

The main motivation behind this is not only we find ourselves used to this feature because VSC and JB have it, but also because this panel in particular already has the top toolbar with the 'add console' and 'expand' icons, which makes us look immediately for this minimise button, as opposite to the toggle approach that Zed already provides. 
The top toolbar is also the main reason why we are not implementing minimise buttons on other panels, because, for instance, the Assistant Panel is completely flat, and it would not make sense to add a top toolbar just for minimising

**Comment by baldwindavid** [comment]
@Terraciano That all seems reasonable. I think generally what I hope to see eventually is a keyboard-driven view; which is to say just about anything can be hidden. But that's way out of scope here :)

**Comment by Otterpocket** [comment]
Though I think the `-` does look way better, it creates another issue. `-` is synonymous with `+`, brains will assume they are somehow connected. Maybe a chevron down would be more appropriate 🤷🏻‍♂️

**Comment by baldwindavid** [comment]
Only thing with chevrons are they would probably need to account for whether `terminal.dock` is configured for left, right, or bottom.

**Comment by maxdeviant** [comment]
Given that this breaks the convention for how panel controls work, I think we'll want input from our designer, Nate, once he's back from paternity leave next month.

Going to close this out for now, but we can revisit in the future. If there isn't an issue for this yet, could you make one to track the request?

**Pull request closed without merging**
