### PR TITLE
Macos/keyboard event

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #ISSUE

Release Notes:

- Added/Fixed/Improved ...

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

### Or...

Closes #ISSUE

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks! I want to gather a bit more input from the community before we commit to this change: https://github.com/zed-industries/zed/discussions/17031, but having wrapped my head around it, I think it likely is the direction we want to go.

**Comment by ConradIrwin** [comment]
@JunkuiZhang Thanks for pushing ahead with this.

A few thoughts so far:
* We should not have to change the keymaps; for example, let's continue to parse cmd-{ as an alias for cmd-shift-[; otherwise we will break people's custom keymaps more than we should.
* It doesn't look like the macOS handling will work for non-Latin layouts. Is there a way to fix that?

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang Thanks for pushing ahead with this.
> 
> A few thoughts so far:
> 
> * We should not have to change the keymaps; for example, let's continue to parse cmd-{ as an alias for cmd-shift-[; otherwise we will break people's custom keymaps more than we should.

Makes sense. And BTW VSCode's default keymap use `cmd-shift-[`, they never use `{` or `>`.

> * It doesn't look like the macOS handling will work for non-Latin layouts. Is there a way to fix that?

On my mac I switch to Russian layout, it seems working good, I can use h j k l under vim mode. What's the issue you are facing?

**Comment by ConradIrwin** [comment]
Sorry I had just skimmed the code without testing it, it is working!

There are some strange things though. For example, on a German keyboard, the key in the position of qwerty-[ is labeled ü and has the virtual key code "[". Unfortunately the key next to it (qwerty-]) is labeled + and has the virtual key code "=". I cannot find a key that has the virtual key code "[".

I'm not sure what the right thing to do in this case is; but we might need to do some more testing with vscode and vim to see. (or if anyone reading this regularly uses a qwertz keyboard they could tell us :D).

It may also be the case that we need a way to bind to the actually typed character in addition to/instead of the virtual key code so that there is still a way for vim-users to type ] on a German keyboard (option-5 types it, but that has the virtual key code of 5).

**Comment by JunkuiZhang** [comment]
This

> Sorry I had just skimmed the code without testing it, it is working!
> 
> There are some strange things though. For example, on a German keyboard, the key in the position of qwerty-[ is labeled ü and has the virtual key code "[". Unfortunately the key next to it (qwerty-]) is labeled + and has the virtual key code "=". I cannot find a key that has the virtual key code "]".

`]}` on English layout is `VK_OEM_6`, from here http://kbdlayout.info/KBDGR/virtualkeys, it seems that the key next to `BACKSPACE` is `VK_OEM_6` on german keyboard.
 
> I'm not sure what the right thing to do in this case is; but we might need to do some more testing with vscode and vim to see. (or if anyone reading this regularly uses a qwertz keyboard they could tell us :D).

Based on your description, it seems that `VirtualKeyCode` is functioning correctly. When we talk about `VirtualKeyCode` (which I'll abbreviate as `VK`), it's worthy to note that keys starting with `VK_OEM` can represent different characters depending on the keyboard layout. For example, `VK_OEM4` is described by Microsoft as:

> Used for miscellaneous characters, it can vary by keyboard. For the US standard keyboard, it represents the `[{` key.

On a German or other keyboard layouts, it may correspond to different characters. This is likely why VSCode handles it in the way shown in [this image](https://code.visualstudio.com/assets/docs/getstarted/keybinding/keybindings-json.png), mapping it to different characters accordingly.

However, not all `VK_OEM***` keys change. According to Microsoft, `VK_OEM_PLUS` (which represents the =/+ key, and oddly enough, it's called PLUS but is = without shift), `VK_OEM_COMMA`, `VK_OEM_MINUS`, and `VK_OEM_PERIOD` do not change.

> It may also be the case that we need a way to bind to the actually typed character in addition to/instead of the virtual key code so that there is still a way for vim-users to type ] on a German keyboard (option-5 types it, but that has the virtual key code of 5).

As I mentioned earlier, `VK_OEM_6` seems to be located next to the `BACKSPACE` key. Could you please test binding that key as a shortcut?

**Comment by ConradIrwin** [comment]
Nice find! We'll need to figure out what changes we want to make to SendKeystrokes; because it seems like it should not require the `->` to work in this case.

**Comment by ConradIrwin** [comment]
@JunkuiZhang the key to the left of backspace is a dead key right now, so we may need to fix the IME ordering to make that work.

**Comment by ConradIrwin** [comment]
https://github.com/microsoft/vscode/issues/17521 Is worth reading - it has a good explanation of the difference between Mac and windows, and explains why they stopped using the approach in this PR.

Instead they inspect the users keyboard layout and re-interpret the shortcuts to work as best possible.

**Comment by JunkuiZhang** [comment]
I have an idea for providing cross-platform VKCode support by maintaining a mapping from scan codes of different keyboard layouts to VKCode. Here’s a feasibility analysis:

- We don’t need to maintain mappings for all keys, only those that can vary, primarily the following nine: `VK_OEM_1`, `VK_OEM_2`, `VK_OEM_3`, `VK_OEM_4`, `VK_OEM_5`, `VK_OEM_6`, `VK_OEM_7`, `VK_OEM_8`, and `VK_OEM_102`.
- We can detect the current keyboard layout when Zed starts up and then load the corresponding key mappings. This approach is somewhat similar to what was discussed in #16903.

**Comment by JunkuiZhang** [comment]
This draft PR adds the ability to load keyboard layout when window opening on macOS, and use the layout ti correctly maps VirtualKey. So far, the following layouts are supported:
- German layout
- Czech layout
- Russian layout

**Comment by JunkuiZhang** [comment]
If we continue down this path, I think we can gradually expand support for more keyboard layouts. We could implement an action like `zed:copy my keyboard layout into clipboard` to allow users to report their keyboard layout information, making it easier for us to add support for those layouts.

**Comment by JunkuiZhang** [comment]
BTW, I'll be returning to school on September 1st, so the progress of this draft might slow down.

**Comment by ConradIrwin** [comment]
@JunkuiZhang VSCode does this by reading the keyboard from the system, I think we could/should copy that: https://github.com/microsoft/node-native-keymap/blob/main/src/keyboard_mac.mm instead of hard coding.

The way they make this work on macOS is to identity where the key you're trying to type is on your layout, and adapting the shortcut to match. For example on a German keyboard typing `[` requires `option-5`, so the shortcut for outdent (`cmd-[`) becomes `cmd-option-ctrl-5`).  I am not sure yet why they add "ctrl", it seems like `cmd-option-5` would make more sense. Do you know @bennetbo ?

I am not yet sure if we have to do things that way or we can still wait until keydown. It seems like we could wait until key down, and do something similar to what we do today with `key` and `ime_key` but make each of those have modifiers; but it needs more thought....

**Comment by JunkuiZhang** [comment]
If I understand you correctly, you’re talking about how to handle or interpret keybindings. I feel that this might be taking things a bit further. The reason I hardcoded those mappings was to address the key mapping (from keypress to a VirtualKeyCode) issues on macOS, and naturally, the keybinding issues would be resolved as a result.

I initially thought that the `keyCode` returned by keyboard input events on macOS was equivalent to `VirtualKeyCode` since Apple [told me so](https://developer.apple.com/documentation/appkit/nsevent/1534513-keycode). However, it turns out that while `keyCode` does map to `VirtualKeyCode` for some keys like `F1` and `Enter`, for most other keys, it’s actually the scan code. The mapping logic from `keyCode` to `VirtualKeyCode` in this PR for macOS was inspired by Chrome's implementation. As you mentioned in the previous link to the VSCode issue (https://github.com/microsoft/vscode/issues/17521), VSCode also encountered some problem: for example, pressing `7` on a German keyboard maps to `VK_77`, and we expect the `7` within `shift-7` to map to the same key `shift+VK_77`, but it actually maps to `shift+VK_191`, which is incorrect.

To solve this problem, VSCode modified the mapping to `VirtualKeyCode`, which seems to be a mix of `VirtualKeyCode`, `char`, and `scan code`. I think the ultimate goal of these modifications was to simulate the mapping of `VirtualKeyCode` as it works on Windows.

For me, this approach adds complexity. I think the solution here is straightforward: following the Windows method, which is based on `VirtualKeyCode`. The challenge is that macOS and Linux are both based on scan codes. My approach in this draft PR is to simulate the Windows-style mapping on macOS, so that the same `VirtualKeyCode` is mapped across all three OSes for a given keyboard layout. For instance, on a German layout, both `7` and `shift-7` would always map to `VK_77`, solving the issue VSCode faced. This also allows for `scan code` based keybinding functionality that VSCode supports, and keeps all key-related code clear. The trade-off is the need to maintain some mapping tables, much like Windows does. As I mentioned earlier, the cost of maintaining these mappings might not be as high as it seems.

I apologize if my explanation is unclear; it’s currently 3:40 AM here in China, and I’m a bit groggy. If there’s anything you don’t understand or if I haven’t explained something well, please let me know.

**Comment by ConradIrwin** [comment]
@JunkuiZhang I think what you say is clear :D Thank you for working on this!

Before we write too much code, we have to understand how users expect this to work. I am not sure that we do yet, but we're getting closer.

I think based on talking to @bennetbo, and looking at VSCode's issue tracker, that it is likely on macOS that users expect keys to work based on what was typed. It also seems like users on Windows expect key-mappings to be based on virtual keys.

This is the heart of the problem we have to solve.

To summarize, I think the bugs we'd like to fix (on macOS) are:
* On non-Latin layouts, default keystrokes that use the Latin alphabet that don't involve command- cannot be typed. (e.g. no `ctrl-a` on a Russian keyboard).
* On non-English layouts, default keystrokes that require option to type cannot be typed (e.g. no `cmd-[` on German).

And the things we want to keep are:
* cmd-o on Dvorak is handled with the same key as typing an o 
* If you can type the character exactly, and you do so, it works. (e.g. option-č matches $ on Czech).

I am not sure that the virtual key solution fits these criteria. In particular I think the last one is problematic on macOS, and which is why VSCode moved away from this approach.

Are there a similar list of bugs for Windows shortcuts today?

**Comment by JunkuiZhang** [comment]
That the way Windows handles key input is quite different from macOS. The initial idea behind this draft PR was to unify key handling across platforms to match Windows' `VirtualKeyCode`-based system. In this system, keys and characters are clearly distinguished. For example, on an English keyboard layout, the shortcut `ctrl-$` would be interpreted as `ctrl-shift-4` and mapped to the corresponding `VK_CTRL + VK_SHIFT + VK_4`. I assume that’s why in VSCode, there isn't a shortcut like `ctrl-$`—because `$` is a character, not a key, and there’s no corresponding `VK_*` for it.

And, on a Czech keyboard layout, the shortcut `VK_CTRL + VK_SHIFT + VK_4` would correspond to `ctrl-shift-č`, and it's `ctrl-4` represented in chars.

To further illustrate how the `VirtualKeyCode` system handles things, say another shortcut: on a standard English layout, `ctrl-/` maps to `VK_CTRL + VK_OEM_2`. On a German layout, this shortcut corresponds to `ctrl-#`. You can see how this system clearly distinguishes between keys and characters.

Similarly, the shortcut `ctrl-\` on an English layout (`VK_CTRL + VK_OEM_5`) corresponds to `ctrl-[the key above TAB]` on a German layout. In this case, `VK_OEM_5` is a dead key on the German layout. The `VirtualKeyCode`-based system’s clear separation of keys and characters makes it natural and straightforward to bind dead keys as shortcuts.

In my testing on Windows, non-Latin keyboards, such as Russian keyboards, allow all shortcuts that use the Latin alphabet. However, I’m not sure if we should bring this behavior to macOS.

Initially, my draft PR aimed to bring this system to all three OSes. However, you’re right that we need to consider how users expect shortcuts to work. Personally, I think the Windows `VirtualKeyCode` system is better, given Windows's widespread use and high compatibility. `VirtualKeyCode` might be the result of careful consideration of all scenarios by Windows developers.

Therefore, in this system, the behavior you described—"If you can type the character exactly, and you do so, it works. (e.g., option-č matches $ on Czech)"—does not work. If we wanted the `VirtualKeyCode` system to support this “what you see is what you get” behavior for shortcuts, one approach could be to map the shortcuts in `default_keymap.json` to the keys on the current layout and then display their corresponding characters. For example, when using a German layout, the shortcut `ctrl-/` would be displayed as `ctrl-#`.

**Comment by JunkuiZhang** [comment]
> To summarize, I think the bugs we'd like to fix (on macOS) are:
> 
> * On non-Latin layouts, default keystrokes that use the Latin alphabet that don't involve command- cannot be typed. (e.g. no `ctrl-a` on a Russian keyboard).

This can be fixed using the `VirtualKeyCode`-based system.

> * On non-English layouts, default keystrokes that require option to type cannot be typed (e.g. no `cmd-[` on German).

Under this system, a shortcut `cmd-[` on English layout is mapped to `VK_CMD + VK_OEM_4`, then is mapped to `cmd-ß` in chars on German layout.

> And the things we want to keep are:
> 
> * cmd-o on Dvorak is handled with the same key as typing an o

The default behavior of the `VirtualKeyCode`-based system.
> * If you can type the character exactly, and you do so, it works. (e.g. option-č matches $ on Czech).

Requires more works using `VirtualKeyCode`. On Windows, shortcut `$` is mapped to `shift-4` -> `VK_SHIFT + VK_4` -> `shift-č`.

> I am not sure that the virtual key solution fits these criteria. In particular I think the last one is problematic on macOS, and which is why VSCode moved away from this approach.
> 
> Are there a similar list of bugs for Windows shortcuts today?

I don't know if there are any bugs on Windows at the moment. As I mentioned earlier, the Windows system, which is based on `VirtualKeyCode`, clearly distinguishes between keys and characters. The only issue is that it’s not “what you see is what you get.” For example, `ctrl-shift-4` on a Czech layout is actually `ctrl-shift-č`.

However, I don’t think this is a flaw in the system itself. As I mentioned in #16903, all our current shortcuts are designed based on a standard English keyboard layout, and users see the keys and corresponding characters from that layout. So, why should we expect these shortcuts to work correctly without any issues on other layouts?

I believe the solution lies in displaying shortcuts to users based on their specific keyboard layout. That is, the `keymap.json` presented to users should show `ctrl-shift-č` instead of `ctrl-shift-4`, as the latter is a shortcut for the English layout. Dose it really make sense for users with a Czech layout to see English-layout-based shortcuts?

I think showing `cmd-ß` instead of `cmd-[` is better for a German-layout user.

**Comment by ConradIrwin** [comment]
I've asked as few people who use other non-English Latin keyboards regularly how they think this should behave at #17031. I hope they can help to clarify what the requirements should be.

I think for Russian other non-qwerty

**Comment by JunkuiZhang** [comment]
> I've asked as few people who use other non-English Latin keyboards regularly how they think this should behave at #17031. I hope they can help to clarify what the requirements should be.

I've been following that discussion, and it seems that users tend to view keybindings more from a "character matching" perspective. My idea is that our current keybindings are based on keys (or characters) from the standard English layout, and we're essentially forcing users with other layouts to match the characters from the English layout. My suggestion would be to convert the key (or character) from the English layout to the user's layout. For example, the shortcut `ctrl-[` should be `ctrl-ß` on a German layout.

> I also reached out to @alexdima who seems to be VSCode's expert in this system to see if he would change anything if he didn't have the constraint of being based on Electron.

So, you mean that @alexdima will be taking over this part of the work? Should I close this PR?

**Comment by ConradIrwin** [comment]
I think regardless of which approach we take we'll want to update the display of shortcuts to match the current keyboard.

I reached out to see if we could learn from his experience, I don't expect him to work on it.

Safari uses cmd-ö and cmd-ä to go to forward/back (equivalent to cmd-[/] on a US keyboard); but I don't see the logic behind that yet (it may just be they have per-language bindings).

**Comment by notpeter** [comment]
> Safari uses cmd-ö and cmd-ä to go to forward/back (equivalent to cmd-[/] on a US keyboard); but I don't see the logic behind that yet (it may just be they have per-language bindings).

I assume this is because it's a similar hand placement (just one row lower) to `cmd-[` / `cmd-]` where there two available keys.
german keyboard layout

**Comment by JunkuiZhang** [comment]
Recent changes:

1. Since neither macOS nor Linux support `VirtualKeyCode`, and using `VirtualKeyCode` for keybinding matching does not align with the char-based matching intuition for macOS users, I revises the `Keystroke` struct to the following, which is inspired by the current web standards:
    ```rust
    struct Keystroke {
        label: String, // Used for displaying the key in the UI
        text: Option<String>, // Used for char-based matching, e.g., `:` and `$` in vim mode
        code: KeyCodes, // On Windows, this is `VirtualKeycode`, while on macOS and Linux, it's `ScanCode`
        ime_key: ...
    }
    ```

2. When parsing shortcuts from the `keymap.json` file, `cmd-[` will first be interpreted according to the English keyboard layout. Based on the user's current layout, certain keys are remapped as needed (not implemented yet). For keys like `*`, `$`, and `:`, which require `shift` to trigger, the matching will first attempt char-based matching, followed by keycode-based matching if necessary.

**Comment by SomeoneToIgnore** [comment]
image

I feel like we'd better close it for now, as it's sitting in the queue for 2 months or so without the changes and needs quite a rebase.

**Comment by JunkuiZhang** [comment]
> I feel like we'd better close it for now, as it's sitting in the queue for 2 months or so without the changes and needs quite a rebase.

Makes sense.

Sorry! My Hackintosh is currently broken, so I can not program on macOS at this moment, and so I haven't been able to continue with this PR. I'm now considering whether to purchase a Mac Mini or a MacBook.

**Comment by SomeoneToIgnore** [comment]
No worries at all, and thank you for all the attempts, those are sometimes very nice 🙂

**Pull request closed without merging**
