### PR TITLE
php: Add Phpactor support

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR extends the PHP extension with [Phpactor](https://github.com/phpactor/phpactor) support.

Phpactor seems to provide a better feature set out-of-the-box for free, so it has been made the default PHP language server.

Thank you to @xtrasmal for informing us of Phpactor's existence!

Release Notes:

- N/A

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
I'm not sure if other people have the same issue with starting the phpactor LSP. Tried the following PHP versions, 7.4, 8.0, 8.1, 8.2, 8.3 but got the same error on every version.


```log
[2024-07-17T09:01:08+02:00 ERROR project] failed to start language server "phpactor": failed to deserialize response
[2024-07-17T09:01:08+02:00 ERROR project] server stderr: Some("PHP Deprecated:  Return type of Phpactor\\ConfigLoader\\Core\\PathCandidates::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/config-loader/lib/Core/PathCandidates.php on line 24\nDeprecated: Return type of Phpactor\\ConfigLoader\\Core\\PathCandidates::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/config-loader/lib/Core/PathCandidates.php on line 24\nStarting language server, use -vvv for verbose output\nPHP Deprecated:  Return type of Phpactor\\FilePathResolver\\Expanders::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/file-path-resolver/lib/Expanders.php on line 45\nDeprecated: Return type of Phpactor\\FilePathResolver\\Expanders::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/file-path-resolver/lib/Expanders.php on line 45\nPHP Deprecated:  Return type of Phpactor\\CodeBuilder\\Domain\\TemplatePathResolver\\FilterPhpVersionDirectoryIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/code-builder/lib/Domain/TemplatePathResolver/FilterPhpVersionDirectoryIterator.php on line 28\nDeprecated: Return type of Phpactor\\CodeBuilder\\Domain\\TemplatePathResolver\\FilterPhpVersionDirectoryIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/code-builder/lib/Domain/TemplatePathResolver/FilterPhpVersionDirectoryIterator.php on line 28\nPHP Deprecated:  Return type of Phpactor\\CodeTransform\\Domain\\AbstractCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/code-transform/lib/Domain/AbstractCollection.php on line 47\nDeprecated: Return type of Phpactor\\CodeTransform\\Domain\\AbstractCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/remcosmits/.composer/vendor/phpactor/code-transform/lib/Domain/AbstractCollection.php on line 47\nPHP Deprecated:  Optional parameter $offsetEnd declared before required parameter $variableName is implicitly treated as a required parameter in /Users/remcosmits/.composer/vendor/phpactor/code-transform/lib/Adapter/TolerantParser/Refactor/TolerantExtractExpression.php on line 36\nDeprecated: Optional parameter $offsetEnd declared before required parameter $variableName is implicitly treated as a required parameter in /Users/remcosmits/.composer/vendor/phpactor/code-transform/lib/Adapter/TolerantParser/Refactor/TolerantExtractExpression.php on line 36\n")
[2024-07-17T09:01:08+02:00 ERROR project] Hit 4 reinstallation attempts for "phpactor"
[2024-07-17T09:01:09+02:00 ERROR language] server container removal
```

**Comment by pjv** [comment]
@maxdeviant example of phpactor configuration in zed please?

**Comment by maxdeviant** [comment]
> @maxdeviant example of phpactor configuration in zed please?

Phpactor will become the default language server in today’s Preview release, but if you want to try it out now you can add the following to your settings:

```json
{
  "languages": {
    "PHP": {
      "language_servers": ["!intelephense", "phpactor", "..."]
    }
  }
}
```

**Comment by pjv** [comment]
@maxdeviant Sorry, I should have been more clear. I’m running zed preview and already seeing phpactor. Is there a way to configure phpactor’s defaults in my zed settings and if so, can you show an example of a basic minimum default config?

**Comment by xtrasmal** [comment]
https://github.com/xtrasmal/zed-lsp-phpactor [GitHub - xtrasmal/zed-lsp-phpactor: Phpactor LSP Zed Extension] I've still got to remove this package, cause it is not needed anymore. 
BUT... I did add a reader with a .phpactor.json file you can use as reference.
Also if you load phpactor from the command line, you will have a lot of options.

**Pull request merged**
