### PR TITLE
Reduce the frequency writing window size and position information to the database

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Release Notes:

- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
```rust
/// Close this window.
pub fn remove_window(&mut self) {
    self.window.removed = true;
}
```
Should I place the implementation in this function? This function involves some handling related to remote projects, and I'm not sure if the implementation should be placed in this function.

**Comment by ConradIrwin** [comment]
@JunkuiZhang what is the problem you're trying to solve with this?

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang what is the problem you're trying to solve with this?

I just feel that writing data to the database every time the window is moved or resized is a bit redundant （on windows 10-30 messgaes emitted which means 10-30 writing to database）, especially since we also have to continuously call system functions to determine the window's state (whether it is minimized or fullscreen). I am completely fine with the current implementation, but I think it would be more intuitive to save the window's state only when it is closed, which could also slightly reduce the number of system calls. I also have implemented the feature to remember the window's restored size for Zed in another pull request that has not been published yet. In that pull request, multiple functions need to be called to obtain the window's state, so I think it might be better to save the data only when the window is closed. I am not sure if this pull request is appropriate or if such optimization is necessary.

**Comment by ConradIrwin** [comment]
That makes sense.

Waiting for close can be unreliable (apps do crash/computers shut down, etc.), so if you want to reduce the frequency we can debounce this instead.

The easiest way to debounce in gpui is to assign a task to an instance member, and have that task sleep for a time before doing anything.

```
if self.save_bounds.is_some() { 
  return
}
self.save_bounds = Some(cx.spawn(|this, cx| {
    cx.background_executor().timer(Duration::from_millis(100)).await
    this.update(&mut cx, |this, cx| {
      // existing save code

      this.save_bounds.take();
    }).ok();
}));
```

* t

**Comment by JunkuiZhang** [comment]
> That makes sense. 这是有道理的。
> 
> Waiting for close can be unreliable (apps do crash/computers shut down, etc.), so if you want to reduce the frequency we can debounce this instead.等待关闭可能不可靠（应用程序崩溃/计算机关闭等），因此如果您想降低频率，我们可以将其去抖动。
> 
> The easiest way to debounce in gpui is to assign a task to an instance member, and have that task sleep for a time before doing anything.在 gpui 中去抖动的最简单方法是将任务分配给实例成员，并在执行任何操作之前让该任务休眠一段时间。
> 
> ```
> if self.save_bounds.is_some() { 
>   return
> }
> self.save_bounds = Some(cx.spawn(|this, cx| {
>     cx.background_executor().timer(Duration::from_millis(100)).await
>     this.update(&mut cx, |this, cx| {
>       // existing save code
> 
>       this.save_bounds.take();
>     }).ok();
> }));
> ```
> 
> * t

Awesome idea, thanks!

**Comment by JunkuiZhang** [comment]
@ConradIrwin ready for review.

**Pull request merged**
