### PR TITLE
Let Ubuntu Dock show app icon

### PR DESCRIPTION
**Pull request by hongquan**
Closes #16503, #16694

Release Notes:

- Properly show app icon in Ubuntu dock

### CODE REVIEW

**Comment by hongquan** [comment]
@cla-bot check

**Comment by SomeoneToIgnore** [comment]
@jansol , traditionally invite you for the related PRs if you do not mind still.

**Comment by jansol** [comment]
Same comment applies as in the previous PR that did this exact thing :D

Maybe zed should check if it can find a **correctly named** desktop file when running on linux and yell at the user if not.

**Comment by mrnugget** [comment]
@jansol can you link to the previous PR here too? I think then we can close it.

**Comment by jansol** [comment]
It's already closed: #15763

**Comment by mrnugget** [comment]
Hehe, no, I meant we can close this one.

@hongquan see @jansol's comment here: https://github.com/zed-industries/zed/pull/15763#issuecomment-2270698795 Short version: the `.desktop` file should be renamed, setting this attribute here instead is more a hack.

**Comment by hongquan** [comment]
Thanks. Agree that renaming desktop file is a correct solution.

**Pull request closed without merging**
