### PR TITLE
Fix VIM cw on last character of a word doesn't work as expected:

### LINKED ISSUE #10945: VIM `cw` on last character of a word doesn't work as expected
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm sorry if this has already been reported. I couldn't find an issue which describes the exact problem I'm facing though.

If my cursor is on the last (or only) character of a word and I hit `cw` it not only replaces the text starting from the cursor to the end of the current word but also the next word. This feels a bit weird and I believe it's wrong. That behaviour I'd expect from a `ce`.

I hope the screen recordings may help in understanding what I mean exactly.

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screencast of bare neovim (run via `nvim --clean`):

https://github.com/zed-industries/zed/assets/9202899/8e639c53-140b-4c7c-93d3-1a85af500bf8

Screencast of zed using vim mode:

https://github.com/zed-industries/zed/assets/9202899/34cb2cb6-441d-46a2-8d1c-a3c8ff9dafb4

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by Kalmaegi**
At the moment, using the default expand_selection seems to do the job well, without the need for some additional logic, which may also make the code a little clearer, Fix #10945

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
I'd love to delete all the code if we can :D. What happened?

**Comment by weartist** [comment]
> I'd love to delete all the code if we can :D. What happened?

After removing the extra logic, the logic of change is basically similar to delete, for selection, but there are some boundary cases that require them to be different, and I need to confirm XD a little further

**Comment by weartist** [comment]
Teˇst test after cw should be: Te test, If no additional processing is done, it will become at the moment: Tetest, Since our range logic includes spaces, there may still be some additional details to be processed

**Comment by weartist** [comment]
It seems that we can only add a judgment at the end of an object to deal with the edge case, use a tactical patch, and tidy up the previous code, remove some unnecessary branches, and not modify the original execution logic

**Comment by ConradIrwin** [comment]
Makes sense, thanks. Could you please add a test too so we can avoid regressing this when we want to refactor it.

**Comment by weartist** [comment]
> Makes sense, thanks. Could you please add a test too so we can avoid regressing this when we want to refactor it.有道理，谢谢。您能否也添加一个测试，以便我们在想要重构它时可以避免回归它。



> Makes sense, thanks. Could you please add a test too so we can avoid regressing this when we want to refactor it.

I forgot, thanks for the reminder

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
