### PR TITLE
Add Prisma file icon

### PR DESCRIPTION
**Pull request by gariasf**
Add Prisma icon from https://github.com/file-icons/icons

CleanShot 2024-02-06 at 13 17 01@2x

Release Notes:

- Added Prisma icon.

### CODE REVIEW

**Comment by gariasf** [comment]
check

**Comment by gariasf** [comment]
@cla-bot check

**Comment by gariasf** [comment]
@cla-bot check

**Comment by mrnugget** [comment]
Hey! Can you add a screenshot to show what it looks like in the project panel?

**Comment by gariasf** [comment]
Come to look at it, it needs a bit of adjustment:
CleanShot 2024-02-02 at 12 58 13@2x

**Comment by gariasf** [comment]
CleanShot 2024-02-06 at 13 12 01@2x

**Comment by mrnugget** [comment]
Looks great, thanks!

**Pull request merged**
