### PR TITLE
docs: Fix Decrease buffer font size key binding

### PR DESCRIPTION
**Pull request by pointlessone**
What it say on the tin.

Release Notes:

- N/A

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks.

**Comment by SomeoneToIgnore** [comment]
Oh, you seem to have not signed the CLA, so I cannot merge it yet.

**Comment by pointlessone** [comment]
Something's broken. I've signed the CLA. When I got to the page there's no button there any more.
image

**Comment by SomeoneToIgnore** [comment]
Great, now, one last step from the bot's message above, and it all should work:

> Once you've signed, post a comment here that says '@cla-bot check'.

**Comment by pointlessone** [comment]
@SomeoneToIgnore Ah, sorry. Totally missed that bit. 🤦‍♂️

**Comment by SomeoneToIgnore** [comment]
This was the last time it was needed though, so thank you.

**Pull request merged**
