### PR TITLE
Fix incorrect checkbox placement in Markdown preview

### LINKED ISSUE #12515: Incorrect checkbox placement in Markdown preview.
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add a checkbox, and a bullet point underneath it. For example:
```
- [ ] Try to implement basic SSAO
  * Note, SSAO is pretty slow, maybe I shouldn't do it for the web version
```

The result will be  the checkbox being swapped with the bullet point underneath:

image

### Environment

Zed: v0.139.0 (Zed Dev dc141d0f6182773b1281b019c28bcd97413102f0)
OS: Windows 10.0.19045
Memory: 15.9 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by zfz7**
- Closes #12515

Before fix:
Screenshot 2024-10-17 at 09 50 19

After fix:
Screenshot 2024-10-17 at 09 52 36

Testing:
- Manual testing 
- Added unit test

Test results, these tests fail on the main branch for my setup as well, I have docker running but still had some failures:
```
failures:
    tests::integration_tests::test_context_collaboration_with_reconnect
    tests::integration_tests::test_formatting_buffer
    tests::integration_tests::test_fs_operations
    tests::integration_tests::test_git_branch_name
    tests::integration_tests::test_git_diff_base_change
    tests::integration_tests::test_git_status_sync
    tests::integration_tests::test_join_after_restart
    tests::integration_tests::test_join_call_after_screen_was_shared
    tests::integration_tests::test_joining_channels_and_calling_multiple_users_simultaneously
    tests::integration_tests::test_leaving_project
    tests::integration_tests::test_leaving_worktree_while_opening_buffer
    tests::integration_tests::test_local_settings
    tests::integration_tests::test_lsp_hover
    tests::integration_tests::test_mute_deafen
    tests::integration_tests::test_open_buffer_while_getting_definition_pointing_to_it
    tests::integration_tests::test_pane_split_left
    tests::integration_tests::test_prettier_formatting_buffer
    tests::integration_tests::test_preview_tabs
    tests::integration_tests::test_project_reconnect
    tests::integration_tests::test_project_search
    tests::integration_tests::test_project_symbols
    tests::integration_tests::test_propagate_saves_and_fs_changes
    tests::integration_tests::test_references
    tests::integration_tests::test_reloading_buffer_manually
    tests::integration_tests::test_right_click_menu_behind_collab_panel
    tests::integration_tests::test_room_location
    tests::integration_tests::test_room_uniqueness
    tests::integration_tests::test_server_restarts
    tests::integration_tests::test_unshare_project
    tests::notification_tests::test_notifications
    tests::random_project_collaboration_tests::test_random_project_collaboration
    tests::remote_editing_collaboration_tests::test_sharing_an_ssh_remote_project

test result: FAILED. 156 passed; 32 failed; 0 ignored; 0 measured; 0 filtered out; finished in 100.98s
```
Comments:
I do not have a ton of rust knowledge, so very open to feedback. TYSM

Release Notes:

- Fix Incorrect checkbox placement in Markdown preview

### CODE REVIEW

**Comment by zfz7** [comment]
@cla-bot check

**Comment by zfz7** [comment]
@cla-bot check

**Comment by zfz7** [comment]
I ran the following commands and they now pass 
```
cargo fmt --all -- --check
cargo clippy --workspace --release --all-targets --all-features -- --deny warnings
```

**Comment by bennetbo** [comment]
Thanks for fixing this! 
FYI: I changed a bit of the code to make it more "rusty"

**Pull request merged**
