### PR TITLE
vim: Add ability to spawn multicursors at beginning/end of line

### LINKED ISSUE #17842: Vim Mode - Multicursor Spawn at Beginning/End of Line
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has a nice feature to spawn multiple cursors in Vim mode (this is not a native Vim behavior).

You can select lines using the Vim visual line selection mode (`Shift+V`), and press `Shift+I` or `Shift+A` to add cursors to the beginning/end of each line.

### Desired Behavior (VSCode as a reference)

https://github.com/user-attachments/assets/3a5969ce-5153-49bf-9672-c94c6db74f9d

https://github.com/user-attachments/assets/99203650-6c75-4a10-b3df-9dcdde0253d4

### Current Zed Behavior

Here are the current behaviors in zed for the same key inputs in Vim mode.

Visual line selection `Shift+V`, then `J` `J` `J` `J` to select following lines, then `Shift+I` to add a cursor at the beginning of lines:

https://github.com/user-attachments/assets/94aaa53f-842c-4cb6-94aa-77d8184dd9a8

Visual line selection `Shift+V`, then `J` `J` `J` `J` to select following lines, then `Shift+A` to add a cursor at the end of lines:

https://github.com/user-attachments/assets/fcf8b636-7bdf-48a7-84c7-e0efb052d2fc

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by sergioengineer**
Closes #17842

Release Notes:

- Added the ability to spawn multiple cursors through the g-A and g-I motions while in visual select mode.

### CODE REVIEW

**Comment by sergioengineer** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
Thanks for this! As with all vim extensions we should not alter the default behavior but we should document how to do this.

Maybe we could bind to gA and gI by default?

**Comment by sergioengineer** [comment]
Since ga already spawns multi cursors for every match, it does make more sense to allocate another multicursor functionality in gA instead of using shift-a like I did previously.

**Comment by titouandk** [comment]
I don't find using gA and gI very intuitive, since gA and gI does not leave the visual mode currently.

Shift+A and Shift+I, by opposition, go back into the insert mode.

**Comment by sergioengineer** [comment]
In the long run, I believe we are better off having all cursor related actions using the same prefix.
Vim follows an action-object-esque pattern(g is weird though) so having a common prefix is kinda intuitive.

Zed has, currently, 4 multi cursors actions: gl, gL, g<, g>, ga
Adding gI and gA follows the already established pattern.

I do understand your point though. The current shift-i/a behavior for the visual line select mode is very counter intuitive. It doesn't move the cursor to the beginning/end of the line. It just toggles the mode. 
I thought it was a placeholder and that's why, at first, I decided to replace it entirely, but I ended up breaking some compatibility tests at the end of the day and hence the reason why mr Conrad suggested the use of another keybind which, in hindsight, is a better option overall in my opinion.

But I've started using zed just a two weeks or so ago. So I might be missing something here. That's why I'll let you guys decide which keybind suits zed better.
If need be, I can go revert and fix the previously broken test.

**Comment by ConradIrwin** [comment]
yeah, `I` and `A` already do something in real vim (albeit a bit weird), and any time I've changed what vim does (no matter now weird) it's caused someone muscle memory issues.

**Pull request merged**
