### PR TITLE
Add more options to zed.desktop file  

### PR DESCRIPTION
**Pull request by ZorinFoss**
Release Notes:

Add options to :
- open directory using context menu (Right click -> open with -> zed).
- open new zed window using actions menu (Right click on zed desktop  file -> New Window)

### CODE REVIEW

**Comment by ZorinFoss** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@ZorinFoss Thanks for this! Unfortunately I don't think linux yet supports `--new` so more work is needed before we do this!

Out of interest, what system are you on? I'm working on a shell-based installer for zed on linux, and I wonder if you'd be open to testing it?

**Comment by ZorinFoss** [comment]
I'm on Arch Linux. yes i can it.

**Comment by ConradIrwin** [comment]
@ZorinFoss If you do `curl https://zed.dev/install.sh | bash` do you end up with a working `~/.local/bin/zed`?

**Comment by ZorinFoss** [comment]
> @ZorinFoss If you do `curl https://zed.dev/install.sh | bash` do you end up with a working `~/.local/bin/zed`?

yes, it's working fine.

**Comment by ConradIrwin** [comment]
Great, thanks for confirming!

**Pull request closed without merging**
