### PR TITLE
vim: Add square bracket commands

### LINKED ISSUE #17177: Support vim count sections `[m` and `[[`
### Check for existing issues

- [X] Completed

### Describe the feature

If you run `:help [m` and `:help [[`  in vim you can get more details on how it works. 

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by saahityaedams**
Closes https://github.com/zed-industries/zed/issues/17177 https://github.com/zed-industries/zed/issues/4316

Release Notes:

N/A

### CODE REVIEW

**Comment by saahityaedams** [comment]
@ConradIrwin I took a stab at implementing the square bracket vim commands and had a query.

Does ]] mean moving to the next { at the zeroth column for ALL file extension ? Can it be configured ? The documentation [here](https://vimhelp.org/motion.txt.html#:~:text=A%20section%20begins,see%20%3C%3E%5D) isn't very clear.

**Comment by ConradIrwin** [comment]
In vim I believe that is how it works. I would like to do better than that, but it's not (yet) clear to me how to map tree-sitter node names to methods in a reliable cross-language way.

**Comment by feltcute** [comment]
> In vim I believe that is how it works. I would like to do better than that, but it's not (yet) clear to me how to map tree-sitter node names to methods in a reliable cross-language way.

These keybinds for treesitter nodes are done in Helix ([Vim Unimpaired inspired](https://docs.helix-editor.com/keymap.html#unimpaired)) and Ki Editor to more advanced extents, the latter of which is also in Rust and uses treesitter as its fundamental technology for its modal structure, may serve as useful reference. I try to broadly cover the topic of the state of treesitter based bindings in-depth [in a Discussions comment.](https://github.com/zed-industries/zed/discussions/6447#discussioncomment-10713526)

**Comment by ConradIrwin** [comment]
Superseded by https://github.com/zed-industries/zed/pull/20924

**Pull request closed without merging**
