### PR TITLE
vim: Revert 'Y' to yank to end of line

### LINKED ISSUE #17549: All the vim enabled IDEs I've used and I think nvim to, have shift y mapped to line yank. Can we reopen and fix?
All the vim enabled IDEs I've used and I think nvim to, have shift y mapped to line yank. Can we reopen and fix?

_Originally posted by @hortovanyi in https://github.com/zed-industries/zed/issues/14771#issuecomment-2336475728_

### PR DESCRIPTION
**Pull request by vbhavsar**
Closes https://github.com/zed-industries/zed/issues/17549

Release Notes:
- vim: Reverted `Y` to vim behavior. If you want the neovim version (as a built in mapping to `y$`) you must configure it in your [settings](https://zed.dev/docs/vim).

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks! 

Was worth a try 🤷. I'll add something to the docs.

**Comment by vbhavsar** [comment]
Can't please them all 😄

**Comment by verhovsky** [comment]
Disappointing

**Comment by schpet** [comment]
how do i restore previous _yank to end of line_ behaviour in my settings? i'm assuming something in my keymap.json needs to be tweaked but i don't know what:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "shift-y": "<what goes here?>"
    }
  }
]
```

in my .vimrc i have this:

```vimrc
map Y y$
```

**Pull request merged**
