### PR TITLE
Fix cursor shape flickering and dead-zone on 1px border around list items in project and outline panels

### LINKED ISSUE #15614: Project Panel Mouse hover
### Check for existing issues

- [X] Completed

### Describe the feature

When the mouse hovers over it, the cursor style will change.
Maybe keep one style is better?

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/d366e2fd-7977-47b2-af73-2ed6816a7cc4

### PR DESCRIPTION
**Pull request by stippi**
Move click listener to outer div
- Avoids dead area when clicking the 1px border around a list item
- Avoids flickering cursor shape when moving the cursor above the list, and especially when scrolling the list with a stationary cursor.

Closes #15614

Release Notes:

- Fixed mouse cursor shape flickering in project and outline panels when crossing items ([#15614](https://github.com/zed-industries/zed/issues/15614))

### CODE REVIEW

**Comment by stippi** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Nice!
Can we do the same for the outline panel too, please?

**Comment by stippi** [comment]
> Can we do the same for the outline panel too, please?

Of course. I asked this myself, no idea why I didn't follow up on this.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks!

**Pull request merged**
