### PR TITLE
Add Deno LSP support

### PR DESCRIPTION
**Pull request by lino-levan**
This PR adds support for the deno LSP. Should be reviewable now.

Release Notes:

- Added support for the Deno LSP ([#5361](https://github.com/zed-industries/zed/issues/5361)).

### CODE REVIEW

**Comment by lino-levan** [comment]
@cla-bot check

**Comment by lino-levan** [comment]
Ok this is a little tricky, I need to somehow (enable the deno lsp + disable the typescript lsp) when a "deno.json" or "deno.jsonc" file appears in the top level. I'm not really sure how to approach this. I currently have just disabled the eslint and typescript lsps manually to test. Open to guidance.

**Comment by lino-levan** [comment]
I'm not sure what the best way of approaching this is. This should fully work but it's unclear to me how to pick between different LSPs dynamically. Would love to hear your feedback @JosephTLyons.

**Comment by mikayla-maki** [comment]
We currently don't have a system for picking between LSPs dynamically, but you can look at the implementation of NextLs and ElixirLs just above this diff in `language.rs` for a way to switch LSPs at startup.

**Comment by lino-levan** [comment]
@mikayla-maki could you review? added a deno enable config option

**Comment by maxbrunsfeld** [comment]
@lino-levan I'm going to add some logic to Zed so that language servers adapters can declare "required project files". With this, the Deno LSP adapter will be able to list `deno.json` and `deno.jsonc` as required files. This way, we won't need a setting for it.

**Comment by lino-levan** [comment]
@maxbrunsfeld If you want to do this, we definitely can. I think the config is necessary anyways, since there's some more configuration that I'd like to do on a follow up PR.

I'd also like to note that deno projects don't need a `deno.json` or `deno.jsonc`, so removing the option to enable it would... make projects that don't have either uneditable in Zed. Ideally I'd like to avoid that.

**Comment by maxbrunsfeld** [comment]
I see, thanks for clarifying @lino-levan. A setting is fine then.

**Comment by lino-levan** [comment]
Let me fix this PR to work on top of the changes landed in https://github.com/zed-industries/zed/pull/6449.

**Comment by lino-levan** [comment]
Should be ready for review!

**Comment by sigmaSd** [comment]
Can zed handle lsp extensions? Deno virtual text extension is needed for go to definition to work on remote modules

**Comment by lino-levan** [comment]
Haven't had the time to investigate. I haven't seen anything that might allow for this, so I think "no" is the answer right now.

**Comment by lino-levan** [comment]
Investigated, looks like the answer is safely "not right now". Could be wrong!

**Comment by maxbrunsfeld** [comment]
Thanks @lino-levan!

Good point, @sigmaSd - Zed does not yet handle virtual text from language servers. We'll need to tackle that at a later time.

**Comment by pnbv** [comment]
How can I disable the typescript LSP?

**Comment by Gioppix** [comment]
@lino-levan do you happen to know why the lsp is returning only null results?

examples:
// Send:
{"jsonrpc":"2.0","id":76,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/giovanni/Downloads/url/supa/supabase/functions/manage/index.ts"},"position":{"line":8,"character":16}}}
// Receive:
{"jsonrpc":"2.0","result":null,"id":76}
// Send:
{"jsonrpc":"2.0","id":77,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/giovanni/Downloads/url/supa/supabase/functions/manage/index.ts"},"position":{"line":0,"character":8}}}
// Receive:
{"jsonrpc":"2.0","result":null,"id":77}
// Send:
{"jsonrpc":"2.0","id":78,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/giovanni/Downloads/url/supa/supabase/functions/manage/index.ts"},"range":{"start":{"line":0,"character":8},"end":{"line":10,"character":8}},"context":{"diagnostics":[],"only":["quickfix","refactor","refactor.extract","source"]}}}
// Receive:
{"jsonrpc":"2.0","result":null,"id":78}


latest version of zed.

**Pull request merged**
