### PR TITLE
[WIP] Easy motion

### PR DESCRIPTION
**Pull request by babyccino**
Requested at #4930

Release Notes:

- WIP: add easy motion #4930

Current state:

- By word (word(w) and full word(W) are working)
- Row mode is working

### CODE REVIEW

**Comment by 0x2CA** [comment]
Hi, I'm looking forward to this feature, although I'm a vim user, I understand that there is a partial audience of non-vim users, can these features be made public?
https://github.com/zed-industries/zed/issues/5289

**Comment by ConradIrwin** [comment]
@babyccino Thanks for sending this!

I'm curious about the overlay approach vs the updates to the `HighlightStyle` we explored on the call? (I haven't measured it, but I'm worried that if you have 100 of these on the screen, it'll be quite time-consuming to recompute the position of each one on every frame).

What other feedback would be helpful at this point?

**Comment by babyccino** [comment]
> @babyccino Thanks for sending this!
> 
> I'm curious about the overlay approach vs the updates to the `HighlightStyle` we explored on the call? (I haven't measured it, but I'm worried that if you have 100 of these on the screen, it'll be quite time-consuming to recompute the position of each one on every frame).
> 
> What other feedback would be helpful at this point?

I realised that the highlight style approach just wasn't going to work. Trying to take away the copy on the highlight objects was proving to be a real pain. At the moment the copy is fine because that struct is pretty small so adding a field which is not copyable is totally changing the API. You'd also have to add some way of dealing with the style going over the boundary of two chunks. I just think that api is incompatible with what I'm trying to do

I didn't really think about the performance to be honest because I just assumed adding a bunch of elements would be fine like it is in the browser 😅.

The least hacky way I could see it being done is adding another layer of chunks into the `display_map` (`overlay_map` I guess?), but it didn't seem worth it if the api isn't going to be used elsewhere. But if the performance really sucks I'd be happy to do that

Other than that I don't think any feedback will be all that helpful, you can see how rough it is at the moment and by the next time I push it'll be completely different. I'll try get it sort of usuable and then we can talk about it

**Comment by babyccino** [comment]
https://github.com/zed-industries/zed/assets/29778301/4f6ea7f3-8acb-461b-8181-dd9144d8f368

It's not pretty but it is sort of working!

**Comment by babyccino** [comment]
https://github.com/zed-industries/zed/assets/29778301/9492635a-10c5-4dbb-900b-e271aff4a1a6

Coming along 🙂

**Comment by ConradIrwin** [comment]
Nice! From talking to some other people here, it seems like my concern was probably unfounded, so if the overlay approach works better let's go with that.

The other idea we had in that conversation was that, because we're not limited by terminal columns/rows, we could do something that doesn't interfere with the actual text on screen, e.g. excuse my poor design skills:
Screenshot 2024-05-23 at 21 37 36

That might avoid the need to do the contrast reduction stuff in your second screenshot, which I think would make the tool smoother to use overall.

**Comment by ConradIrwin** [comment]
(cc @iamnbutler who may have more informed opinions on how this should look)

**Comment by 0x2CA** [comment]
> Nice! From talking to some other people here, it seems like my concern was probably unfounded, so if the overlay approach works better let's go with that.
> 
> The other idea we had in that conversation was that, because we're not limited by terminal columns/rows, we could do something that doesn't interfere with the actual text on screen, e.g. excuse my poor design skills: Screenshot 2024-05-23 at 21 37 36
> 
> That might avoid the need to do the contrast reduction stuff in your second screenshot, which I think would make the tool smoother to use overall.

This is an interesting idea, but this one has serious line-height requirements, otherwise it's inevitably obscured and the display is even more misaligned

**Comment by ConradIrwin** [comment]
Yeah. That said, we managed to make it work for multiplayer, so there is "just" enough space if we do it right :D.

image

**Comment by babyccino** [comment]
Screenshot 2024-05-24 at 5 12 17 PM
Screenshot 2024-05-24 at 5 14 38 PM

@ConradIrwin @iamnbutler when you mentioned it I thought it would be great but I'm not so sure now. It looks a little jank

**Comment by baldwindavid** [comment]
@babyccino Guess I was thinking there would be a background color with white text similar to the player stuff and without dimming the code.

**Comment by 0x2CA** [comment]
Generally speaking, the location of the target in mind is certain, and it does not make much sense to display a cue above it to prevent occlusion, and color interference should be avoided, and the background should be decolorized.

in vscode
image
image
in zed
image
image

**Comment by ConradIrwin** [comment]
@babyccino Can we talk this through at some point please https://calendly.com/conradirwin/pairing? I took a look at this and it has become way too much code to consider merging, sorry for not looking sooner!

At a high level:
* We need to avoid changing every context in the vim.json by re-using the existing VimWaiting.
* We should re-use the existing mode indicator to display the characters in progress instead of building our own.
* Avoid rebuilding the editor focus/blur tracking from the vim crate.

I would like to figure out how to significantly reduce scope here and build the 20% that gives us the 80% return. My guess is that this is:

* Single-pane only
* Support word + line only (and only bi-directionally).
* Re-use existing zed code where possible (e.g. window_bottom, etc. all exist in the vim crate already; the cursor_position can be read from pixel_position_of_current_cursor).

Once we have the basics merged, we can iterate from there – in particular there are a lot of non-easymotion plugins that support various kinds of jumps. Once we have the infrastructure in place I suggest we play around and pick the next best one to explore.

**Comment by babyccino** [comment]
> @babyccino Can we talk this through at some point please https://calendly.com/conradirwin/pairing? I took a look at this and it has become way too much code to consider merging, sorry for not looking sooner!
> 
> At a high level:
> 
> * We need to avoid changing every context in the vim.json by re-using the existing VimWaiting.
> * We should re-use the existing mode indicator to display the characters in progress instead of building our own.
> * Avoid rebuilding the editor focus/blur tracking from the vim crate.
> 
> I would like to figure out how to significantly reduce scope here and build the 20% that gives us the 80% return. My guess is that this is:
> 
> * Single-pane only
> * Support word + line only (and only bi-directionally).
> * Re-use existing zed code where possible (e.g. window_bottom, etc. all exist in the vim crate already; the cursor_position can be read from pixel_position_of_current_cursor).
> 
> Once we have the basics merged, we can iterate from there – in particular there are a lot of non-easymotion plugins that support various kinds of jumps. Once we have the infrastructure in place I suggest we play around and pick the next best one to explore.

😅 fair enough. I've just been really enjoying building this so I went a little crazy. Re the indicator: yeah I figured that was just kind of a temporary thing. The context hack was also just a temporary thing. If it's using the vim indicator and the vim context maybe it makes sense to move it back into the Vim crate?

I didn't realise that cursor position function existed but iirc the window top and bottom even with the scroll margin set to 0 were not giving the actual top and bottom of the window but I'll try and adapt the code.

**Comment by ConradIrwin** [comment]
Thanks for this, looks like it's getting simpler!

I'd still like to remove some of the logic around editor focus tracking. I think there are two approaches:
* Move this to the vim crate so it doesn't have to track itself
* Register actions on the Editor instead of the workspace so we don't have to track this at all (this is a change I'd like to make to vim too, but it keeps getting bumped down the priority list :D)

Is there anything else on your todo list still?

**Comment by babyccino** [comment]
> Thanks for this, looks like it's getting simpler!
> 
> I'd still like to remove some of the logic around editor focus tracking. I think there are two approaches:
> * Move this to the vim crate so it doesn't have to track itself
> * Register actions on the Editor instead of the workspace so we don't have to track this at all (this is a change I'd like to make to vim too, but it keeps getting bumped down the priority list :D)
> 
> Is there anything else on your todo list still?

Yep I've got everything we talked about on my to-do list including what you've mentioned above. I haven't had as much time to work on his but I'm trying to get it working properly with folds at the moment and then I'll handle moving everything back into the vim crate.

**Comment by ConradIrwin** [comment]
@babyccino How's things going? If you're planning on working on this soon, I'll leave this open; otherwise will close out to keep the PR list tidy.

**Comment by ConradIrwin** [comment]
@babyccino I'm going to close for now, but please re-open when you get time to work on it!

**Comment by babyccino** [comment]
@ConradIrwin is the way I've done the editor events what you were expecting? The only obvious issue I can see at this point is the occlusion thing, i.e. if you scroll the overlays will occlude other parts of the UI but I don't really know how to fix that while using `defer_draw`.

**Comment by babyccino** [comment]
@ConradIrwin is the way I've done the editor events what you were expecting? The only obvious issue I can see at this point is the occlusion thing, i.e. if you scroll the overlays will occlude other parts of the UI but I don't really know how to fix that while using `defer_draw`.

**Comment by ConradIrwin** [comment]
The editor events stuff seems reasonable, but I think we can simplify it by removing the easy motion enabled setting (you can only start easy motion if you trigger its key binding so I think that's fine).

For occlusion we should be able to filter out the overlays that are scrolled outside the bounds (or set the clipping mask), but I may be misunderstanding the problem.

**Comment by babyccino** [comment]
> The editor events stuff seems reasonable, but I think we can simplify it by removing the easy motion enabled setting (you can only start easy motion if you trigger its key binding so I think that's fine).
> 
> For occlusion we should be able to filter out the overlays that are scrolled outside the bounds (or set the clipping mask), but I may be misunderstanding the problem.

image

Here's the occlusion problem I have. It's just when a row is partly occluded by the boundary of the editor. The plugin will only give you matches which are entirely in the editor but if you scroll you can get into the state in the picture

**Comment by ConradIrwin** [comment]
We (probably) just need a cx.with_content_mask (or to re-use one of the ones that already exists in editor element rendering)

**Comment by babyccino** [comment]
Okay seems to be fixed now. I'll try and get some actual real world use with it next week

**Comment by machin3io** [comment]
Spectactular work by the looks of it. Thank you so much for putting in the effort.

**Comment by babyccino** [comment]
@ConradIrwin sorry haven't had much time to work on this. It's now back up to date with main. I haven't really got much real world use but it at least *seems* to work. Are you still interested in merging this? If so what else what we need to get done to make that happen

**Comment by ConradIrwin** [comment]
TBH I am on the fence about merging it. On the one hand it's highly requested, on the other it's a large change that I'll probably end up having to maintain.

Let me chat with some people internally and try and figure out what we want to do.

If we do merge it, the code needs a bit of polish - deleting comments and unused functions, making the diff look good; etc.

**Comment by ConradIrwin** [comment]
Ok, so I talked about this a bit internally, and I've decided that we're *not* going to merge this right now. 

This is very contextual, but it really boils down to two things for me:
* Adding a bunch of extra features to the editor is quite an onus to take on. Although I think the overlays stuff is good, it adds a maintenance burden to everything else we add there.
* This really should be a Zed extension (though obviously that's impossible right now)
* There is a lot of code that powers this feature that is otherwise not necessary, and I don't currently have the time to make sure that it's all good. 

I realize this is probably not the outcome you hoped for, and I'd like to be clear that this is just a "no right now", not a "no never".

**Comment by machin3io** [comment]
Pretty saddened by this, but I totally respect understand your reasoning.

Can you elaborate on why it's *obviously not possible as an extension right now*? And if and when that may change? Thanks!

**Comment by styx** [comment]
@ConradIrwin totally agree it should be a plugin but it is so pity we won't have this functionality anytime soon.
Is there any roadmap or even a rough idea when general plugins support development going to start?

**Comment by baldwindavid** [comment]
@machin3io Zed extensions can currently only add languages, themes, and slash commands (https://zed.dev/docs/extensions/developing-extensions)

I wonder if more elaborate extensions could start their lives as extensions within the Zed codebase and eventually be extracted out when the infrastructure is in place to support them. And, if so, perhaps easymotion-ish functionality might be a good early candidate for that sort of thing. Or maybe there are some existing smaller features (that I can't think of :)) that are better suited as early candidates.

**Comment by machin3io** [comment]
@baldwindavid Thanks, wasn't aware they are so limited still

**Comment by babyccino** [comment]
> @machin3io Zed extensions can currently only add languages, themes, and slash commands (https://zed.dev/docs/extensions/developing-extensions)
> 
> I wonder if more elaborate extensions could start their lives as extensions within the Zed codebase and eventually be extracted out when the infrastructure is in place to support them. And, if so, perhaps easymotion-ish functionality might be a good early candidate for that sort of thing. Or maybe there are some existing smaller features (that I can't think of :)) that are better suited as early candidates.

I did notice the new `addons` field in the editor when I was fixing the merge conflicts on this branch so hopefully it's soon. I would be happy to pitch in to help get a vim plugins api going. I've already put so much work into this PR so I'd be happy to put in more work so it can all actually get used, esp when so many are keen on the feature.

**Comment by babyccino** [comment]
Obviously won't matter now but I've trimmed all the nonsense out of the diff, so it's now 21 files instead of 28

**Comment by machin3io** [comment]
> > @machin3io Zed extensions can currently only add languages, themes, and slash commands (https://zed.dev/docs/extensions/developing-extensions)
> > I wonder if more elaborate extensions could start their lives as extensions within the Zed codebase and eventually be extracted out when the infrastructure is in place to support them. And, if so, perhaps easymotion-ish functionality might be a good early candidate for that sort of thing. Or maybe there are some existing smaller features (that I can't think of :)) that are better suited as early candidates.
> 
> I did notice the new `addons` field in editor.rs when I was fixing the merge conflicts on this branch so I have hope it won't be too much longer. I would be happy to pitch in to help get a vim plugins api going. I've already put so much work into this PR so I'd be happy to put in more work so it can all actually get used, esp when so many are keen on the feature. Vim motion plugins (without edits) seem like a good candidate to expand the extensions.

Once again, thank you so much for all your work. I hope it will see the light of the day. IMO, this feature alone would push zed to another level.

**Comment by julyfun** [comment]
I migrated to vscode because there is easymotion in vscode.

**Comment by DavidBChristensen** [comment]
> I migrated to vscode because there is easymotion in vscode.

Not a constructive comment.

They already know a portion of people are not going to use zed fully until extensions and some features are implemented.

**Pull request closed without merging**
