### PR TITLE
linux: Use filesystem based unix socket instead of abstract namespace

### PR DESCRIPTION
**Pull request by maan2003**
Release Notes:

- N/A

fixes: unable to launch multiple zed instances even if the support dirs are different(example: bwrap based sandboxing)

### CODE REVIEW

**Comment by maan2003** [comment]
@cla-bot check

**Comment by maan2003** [comment]
:thinking: actually not sure what will happen if the sock already exists (but not being listened to)

**Comment by ConradIrwin** [comment]
@maan2003 that's why I went with the abstract namespace approach. It seems most apps using the fs based approach do something like "put the pid in the filename, and see if that pid is still running (and hope you don't get a false positive)".

If Zed is already running, it seems likely that we do want to re-use the running instance – what's the use-case for having two different installations of zed running the same release channel on one machine and wanting to run both side by side? If it's just for developing zed I think we can live with it being not great.

One thing I've been considering for longer term is allowing something like "profiles" (like Chrome) you could then run zed in a different profile, and it would not share any of the config/data/sockets. I think that would solve this, but I don't want to rush into building that.

**Comment by maan2003** [comment]
> what's the use-case for having two different installations of zed running the same release channel on one machine and wanting to run both side by side?

I have linux namespaces based sandbox (bubblewrap). I want to run one zed outside the sandbox and one zed inside the sandbox. Both zed have different directories (mount namespace) but the abstract sockets (network namespace) are shared.

**Comment by maan2003** [comment]
@ConradIrwin I updated the PR, now it correctly handles the socket already existing and removing it if no process is listening on it.

**Comment by ConradIrwin** [comment]
@maan2003 Looks like the linter is unhappy, but will merge when that's resolved

**Comment by maan2003** [comment]
@ConradIrwin could you please restart the CI, looks like it timed out.

**Comment by ConradIrwin** [comment]
Thanks for this!

**Pull request merged**
