### PR TITLE
Fix caret movement issue for some special characters

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Currently in Zed, certain characters require pressing the key twice to move the caret through that character. For example: "❤️" and "y̆".

The reason for this is as follows:

Currently, Zed uses `chars` to distinguish different characters, and calling `chars` on `y̆` will yield two `char` values: `y` and `\u{306}`, and calling `chars` on `❤️` will yield two `char` values: `❤` and `\u{fe0f}`.

Therefore, consider the following scenario (where ^ represents the caret):

- what we see: ❤️ ^
- the actual buffer: ❤ \u{fe0f} ^

After pressing the left arrow key once:

- what we see: ❤️ ^
- the actual buffer: ❤ ^ \u{fe0f}

After pressing the left arrow key again:
- what we see: ^ ❤️
- the actual buffer: ^ ❤ \u{fe0f}

Thus, two left arrow key presses are needed to move the caret, and this PR fixes this bug (or this is actually a feature?).

I have tried to keep the scope of code modifications as minimal as possible. In this PR, Zed handles such characters as follows:

- what we see: ❤️ ^
- the actual buffer: ❤ \u{fe0f} ^

After pressing the left arrow key once:

- what we see: ^ ❤️
- the actual buffer: ^ ❤ \u{fe0f}

Or after pressing the delete key:

- what we see: ^
- the actual buffer: ^

Please note that currently, different platforms and software handle these special characters differently, and even the same software may handle these characters differently in different situations. For example, in my testing on Chrome on macOS, GitHub treats `y̆` as a single character, just like in this PR; however, in Rust Playground, `y̆` is treated as two characters, and pressing the delete key does not delete the entire `y̆` character, but instead deletes `\u{306}` to yield the character `y`. And they both treat `❤️` as a single character, pressing the delete key will delete the entire `❤️` character.

This PR is based on the principle of making changes with the smallest impact on the code, and I think that deleting the entire character with the delete key is more intuitive.

Release Notes:

- Fix caret movement issue for some special characters

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this!

I will do some benchmarking soon, but assuming that it is not noticeably slower I think this is a great improvement

**Comment by ConradIrwin** [comment]
@JunkuiZhang Thanks for this.

From benchmarking, this is too slow to ship in its current form. The primary problem is the change to line wrapping, which makes rendering a frame in zed take twice as long (I tested this by resizing the width of the window with a single file open).

screenshot_2024-04-10_at_08 47 39_720

The change to clip_point is less of a problem because it's called less, but we can use the fact that zed is mostly used to edit programs (which are largely ascii) to reduce the slowdown by half. I'll push that up to your branch.

If you're ok to merge just the clip point stuff, and come back to line wrapping later, I think that would be a good approach. That said, we can also likely special case the ascii code-paths for line wrapping and only seek for grapheme indexes inside non-ascii characters; but I'm not sure how fast we can make it.

**Comment by JunkuiZhang** [comment]
@ConradIrwin I'm sorry, I didn't realize that the changes related to `line_wrapper` had such a significant impact. I have reverted these changes. The main issue in this part was that it not only calculated the length of `❤️`, but also calculated the length of `\u{fe0f}`, which is meaningless. Therefore, I modified this part of the code. However, considering that the current implementation did not have any functional issues and the changes would lead to a performance decline, I agree with your perspective and have removed these modifications.

**Comment by ConradIrwin** [comment]
Thanks for the update.

It is still broken for line-wrapping, but I guess only in the case of multi-code-point graphemes that each have individual width. For example the 👨‍👩‍👧‍👦 character is made up of a number of composed emojis, and so depending on the width of the editor, it may be line broken like:
Screenshot 2024-04-10 at 12 59 10

or:
Screenshot 2024-04-10 at 12 59 05

I don't think this is worth a 2x slowdown to fix, but it would be nice if we could figure out a faster fix in the future.

**Pull request merged**
