### PR TITLE
Multiple styles of line numbers

### PR DESCRIPTION
**Pull request by francesco-gaglione**
Release Notes:

- Added/Fixed/Improved ... ([#13692 ](https://github.com/zed-industries/zed/issues/13692)).

Release Notes:
- Roman line numbers implemented
- Some issues with settings.json change

### CODE REVIEW

**Comment by mikayla-maki** [comment]
Can we see a screenshot with this working? FWIW we'll probably not merge it but it's a very fun idea :)

**Comment by francesco-gaglione** [comment]
@mikayla-maki  sure, I tested the settings.json too and it work.

image

**Comment by mikayla-maki** [comment]
I think you'd also need to adjust the gutter width calculation in `max_line_number_width` to take into account the roman numerals

**Comment by francesco-gaglione** [comment]
@mikayla-maki I agree with that. Lines with icons look very bad with roman numerals. I'll work on it just for fun and then if merged a new feature will be available

**Comment by mikayla-maki** [comment]
@francesco-gaglione Yeah! You should be able to fix the icon problem by updating `max_line_number_width` :)

**Comment by RustoMCSpit** [comment]
you could have it only show every fifth roman numeral. im not sure if you can put the number line on the left or make it smaller in width though

**Comment by versecafe** [comment]
This makes me so tempted to add line numbers as tally marks but macOS doesn't even render them

```
����
```

> U+1D372

**Comment by versecafe** [comment]
@francesco-gaglione Love the idea, decided to go for something a millennia or two older, turns out Aegean numerals work on MacOS even if tallymarks don't (they're both in the unicode spec)

image

**Comment by RustoMCSpit** [comment]
> @francesco-gaglione Love the idea, decided to go for something a millennia or two older, turns out Aegean numerals work on MacOS even if tallymarks don't (they're both in the unicode spec)
> image

i feel like this warrants the issue to be renamed to "Different line number implementations"

**Comment by francesco-gaglione** [comment]
@Angelk90 I am reading the documentation you provided, I had not seen the notification. In the meantime I have changed the implemetation of the conversion in the Roman system and now it should be able to go over 3999. Also, the editor now adjusts the width of the number bar correctly based on the length of the longest Roman numeral.

Here a demo, check it:

https://github.com/zed-industries/zed/assets/94604837/882be5af-2893-433c-bab2-e9108efdc5c2

**Comment by versecafe** [comment]
@francesco-gaglione I used an enum to control it to make it easier to expand in the future as it feels weird to use a pile of booleans when only one can be true

```rs
#[derive(Copy, Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum NumeralStyle {
    /// Use Arabic Numerals, for normal people who like their base 10 counting.
    Arabic,
    /// Use Roman Numerals, for the strange people who hate based number systems.
    Roman,
    /// Use Aegean Numerals, for all the Linear A fans coding since 1500 BCE.
    Aegean,
}

#[derive(Copy, Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
pub struct Gutter {
    pub line_numbers: bool,
    pub code_actions: bool,
    pub runnables: bool,
    pub folds: bool,
    pub line_numbers_style: NumeralStyle,
}
```

```rs
let numeral_style = EditorSettings::get_global(cx).gutter.line_numbers_style;

let relative_rows = self.calculate_relative_line_numbers(snapshot, &rows, relative_to);
let mut line_number = String::new();
buffer_rows
    .into_iter()
    .enumerate()
    .map(|(ix, multibuffer_row)| {
        let multibuffer_row = multibuffer_row?;
        let display_row = DisplayRow(rows.start.0 + ix as u32);
        let color = if active_rows.contains_key(&display_row) {
            cx.theme().colors().editor_active_line_number
        } else {
            cx.theme().colors().editor_line_number
        };
        line_number.clear();
        let default_number = multibuffer_row.0 + 1;
        let raw_number = relative_rows
            .get(&DisplayRow(ix as u32 + rows.start.0))
            .unwrap_or(&default_number);
        let number = match numeral_style {
            NumeralStyle::Arabic => raw_number.to_string(),
            NumeralStyle::Roman => self.calculate_roman_numeral(raw_number),
            NumeralStyle::Aegean => self.calculate_aegean_numeral(raw_number),
        };
        write!(&mut line_number, "{number}").unwrap();
```

**Comment by versecafe** [comment]
@francesco-gaglione You can shrink the gutter usage a bit by using the dedicated unicode characters for roman numerals

image

> https://en.wikipedia.org/wiki/Numerals_in_Unicode#Roman_numerals

**Comment by RustoMCSpit** [comment]
> you could have it only show every fifth roman numeral. im not sure if you can put the number line on the right rather than the left or make it smaller in width though


roman numerals emphasise multiples of five and i think having this as an option would make it a lot cleaner, or at least shading the multiples of five a bit darker than the other numbers.

image

**Comment by francesco-gaglione** [comment]
> @francesco-gaglione I used an enum to control it to make it easier to expand in the future as it feels weird to use a pile of booleans when only one can be true
> 
> ```rust
> #[derive(Copy, Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
> #[serde(rename_all = "snake_case")]
> pub enum NumeralStyle {
>     /// Use Arabic Numerals, for normal people who like their base 10 counting.
>     Arabic,
>     /// Use Roman Numerals, for the strange people who hate based number systems.
>     Roman,
>     /// Use Aegean Numerals, for all the Linear A fans coding since 1500 BCE.
>     Aegean,
> }
> 
> #[derive(Copy, Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
> pub struct Gutter {
>     pub line_numbers: bool,
>     pub code_actions: bool,
>     pub runnables: bool,
>     pub folds: bool,
>     pub line_numbers_style: NumeralStyle,
> }
> ```
> 
> ```rust
> let numeral_style = EditorSettings::get_global(cx).gutter.line_numbers_style;
> 
> let relative_rows = self.calculate_relative_line_numbers(snapshot, &rows, relative_to);
> let mut line_number = String::new();
> buffer_rows
>     .into_iter()
>     .enumerate()
>     .map(|(ix, multibuffer_row)| {
>         let multibuffer_row = multibuffer_row?;
>         let display_row = DisplayRow(rows.start.0 + ix as u32);
>         let color = if active_rows.contains_key(&display_row) {
>             cx.theme().colors().editor_active_line_number
>         } else {
>             cx.theme().colors().editor_line_number
>         };
>         line_number.clear();
>         let default_number = multibuffer_row.0 + 1;
>         let raw_number = relative_rows
>             .get(&DisplayRow(ix as u32 + rows.start.0))
>             .unwrap_or(&default_number);
>         let number = match numeral_style {
>             NumeralStyle::Arabic => raw_number.to_string(),
>             NumeralStyle::Roman => self.calculate_roman_numeral(raw_number),
>             NumeralStyle::Aegean => self.calculate_aegean_numeral(raw_number),
>         };
>         write!(&mut line_number, "{number}").unwrap();
> ```

I like it and as you said it can be used in future to implement other formats. I'm working on it. My only doubt is how to reflect the settings into the Gutter struct. I'm new here, I'm trying to figure it out. I'll update you.

**Comment by francesco-gaglione** [comment]
> > you could have it only show every fifth roman numeral. im not sure if you can put the number line on the right rather than the left or make it smaller in width though
> 
> roman numerals emphasise multiples of five and i think having this as an option would make it a lot cleaner, or at least shading the multiples of five a bit darker than the other numbers (but if so, should other important multiples be given an even more important shading distinction)
> 
> image

I investigate the possibility of obtaining this functionality

**Comment by RustoMCSpit** [comment]
https://github.com/zed-industries/zed/issues/13747

the above issue is somewhat related to this then

**Comment by francesco-gaglione** [comment]
I am not familiar with Aegean, can anyone help finish the implementation?

**Comment by RustoMCSpit** [comment]
> Can we see a screenshot with this working? FWIW we'll probably not merge it but it's a fun idea :)

looks like we are merging now lol

**Comment by francesco-gaglione** [comment]
@mikayla-maki  I implemented the feature in the screenshot as requested from @RustoMCSpit. But decisions have to be made here. Do we want to make this feature enableable from settings or do we make it always on for all styles that are not arabic? Or do we even enable it by default

image

**Comment by versecafe** [comment]
@francesco-gaglione 

```rs
fn calculate_roman_numeral(&self, number: &DisplayRowDelta) -> String {
    let values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
    let symbols = [
        "M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I",
    ];

    let mut num = *number;
    let mut roman = String::with_capacity(15);
    for i in 0..values.len() {
        while num >= values[i] {
            num -= values[i];
            roman.push_str(symbols[i]);
        }
    }

    roman
}

fn calculate_aegean_numeral(&self, number: &DisplayRowDelta) -> String {
    let values = [
        9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 1000, 900, 800, 700, 600, 500, 400,
        300, 200, 100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,
    ];
    let symbols = [
        "𐄪", "𐄩", "𐄨", "𐄧", "𐄦", "𐄥", "𐄤", "𐄣", "𐄢", "𐄡", "𐄠", "𐄟", "𐄞", "𐄝", "𐄜", "𐄛", "𐄚",
        "𐄙", "𐄘", "𐄗", "𐄖", "𐄕", "𐄔", "𐄓", "𐄒", "𐄑", "𐄐", "𐄏", "𐄎", "𐄍", "𐄌", "𐄋", "𐄊", "𐄉",
        "𐄈", "𐄇",
    ];

    let mut num = *number;
    let mut aegean = String::with_capacity(5);
    for i in 0..values.len() {
        while num >= values[i] {
            num -= values[i];
            aegean.push_str(symbols[i]);
        }
    }

    aegean
}
```

**Comment by versecafe** [comment]
I could expand aegean for the 10,000 to 90,000 but I don't know if that is necessary

**Comment by RustoMCSpit** [comment]
> @mikayla-maki I implemented the feature in the screenshot as requested from @RustoMCSpit. But decisions have to be made here. Do we want to make this feature enableable from settings or do we make it always on for all styles that are not arabic? Or do we even enable it by default
> 
> image

id have it shaded the other way, the multiples of five should be more prominent

**Comment by RustoMCSpit** [comment]
> I could expand aegean for the 10,000 to 90,000 but I don't know if that is necessary

do it

**Comment by RustoMCSpit** [comment]
image
image
i know this is silly and all but if we wanted to, we could...

**Comment by versecafe** [comment]
@francesco-gaglione https://github.com/versecafe/zed/tree/custom-gutter-numerals, you can merge this into your branch if you want it should have all the setup, and is a more expandable system so adding new numeral systems is just adding an enum value and a corresponding calculate function

**Comment by francesco-gaglione** [comment]
> @francesco-gaglione : I don't understand how number ordering works, the first shouldn't be `I` but from the video it seems like `XIII` i.e. 13. Screenshot 2024-07-03 alle 12 45 39
> 
> Wouldn't it be better to do this, to avoid having problems with the subtraction?
> 
> The main problem in the original code is that the number parameter passed to the calculate_roman_numeral function is of type &DisplayRowDelta, but is used directly without being dereferenced. This can cause errors when subtracting and updating the variable num within the loop, since num should be an integer and not an object reference.
> 
> When manipulating num values ​​inside the loop, you must properly dereference num to get the actual value contained by DisplayRowDelta, otherwise your code will not work as expected and may generate type errors during execution.
> 
> ```
> while *num >= values[i] {
>             *num -= values[i];
> ...
> }
> ```
> 
> Then it would be better to ask someone who is more experienced.

The reason is I use vim mode, so I use relative row numbers. If disabled the first row is I

**Comment by francesco-gaglione** [comment]
> @francesco-gaglione https://github.com/versecafe/zed/tree/custom-gutter-numerals, you can merge this into your branch if you want it should have all the setup, and is a more expandable system so adding new numeral systems is just adding an enum value and a corresponding calculate function, also includes aegean 10k to 90k

already did it, but I will copy the aegean numerals. Did you test it? I have some issue because the symbols are not displayed, it seems to be a unicode issue. I will check but let me know

**Comment by versecafe** [comment]
> @versecafe : However, the maximum number you can represent is 9999, using Aegean notation.

@Angelk90 I updated it goes to 99999

**Comment by francesco-gaglione** [comment]
> ```rust
> fn calculate_aegean_numeral(&self, number: &DisplayRowDelta) -> String {
>     let values = [
>         9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 1000, 900, 800, 700, 600, 500, 400,
>         300, 200, 100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,
>     ];
>     let symbols = [
>         "𐄪", "𐄩", "𐄨", "𐄧", "𐄦", "𐄥", "𐄤", "𐄣", "𐄢", "𐄡", "𐄠", "𐄟", "𐄞", "𐄝", "𐄜", "𐄛", "𐄚",
>         "𐄙", "𐄘", "𐄗", "𐄖", "𐄕", "𐄔", "𐄓", "𐄒", "𐄑", "𐄐", "𐄏", "𐄎", "𐄍", "𐄌", "𐄋", "𐄊", "𐄉",
>         "𐄈", "𐄇",
>     ];
> 
>     let mut num = *number;
>     let mut aegean = String::with_capacity(5);
>     for i in 0..values.len() {
>         while num >= values[i] {
>             num -= values[i];
>             aegean.push_str(symbols[i]);
>         }
>     }
> 
>     aegean
> }
> ```

Using your code I have this result:
image
have you tested it and/or found a solution?

**Comment by versecafe** [comment]
@francesco-gaglione It may just be macOS Sequoia and up since Aegean numerals were added to the unicode standard in 2013, I'm running on the 15 beta works fine

**Comment by francesco-gaglione** [comment]
> @francesco-gaglione It may just be macOS Sequoia and up since Aegean numerals were added to the unicode standard in 2023, I'm running on the 15 beta works fine

Oh well, I'm on linux so it is an issue only on linux, so I'll try to solve this before to push

**Comment by versecafe** [comment]
It'll likely just be dependent on the OS specific unicode support, and if the characters don't render it shouldn't be an issue since it's purely optional and honestly a bit of a hidden joke feature.

**Comment by francesco-gaglione** [comment]
> It'll likely just be dependent on the OS specific unicode support, and if the characters don't render it shouldn't be an issue since it's purely optional and honestly a bit of a hidden joke feature.

Agree with that.... so in this case if maintainers want to merge this I think it is ready for this reasons: the pr is linked to a roman numerals issue (feature request) so here we decided to start the implementation of different numerals and the code is now ready to easily implement different numerals type. 
At this moment 3 numeral types are enough, so then a more specific issue can be created with all the numerals that we want to implement (after maintainers discussion on what to implement).

@mikayla-maki  what do you think? Can I put this pr ready for review?

**Comment by RustoMCSpit** [comment]
> > @mikayla-maki I implemented the feature in the screenshot as requested from @RustoMCSpit. But decisions have to be made here. Do we want to make this feature enableable from settings or do we make it always on for all styles that are not arabic? Or do we even enable it by default
> > image
> 
> id have it shaded the other way, the multiples of five should be more prominent, maybe even show them exclusively (or should that be another setting applied to all modes of styles that the fifth multiple line is the only one labelled? it's the same issue you mentioned). in my opinion, i believe users should be able to select to show multiples of fifths to be prominent (as in shaded more brightly or be the only visible numbers) in all counting systems but as an opt-in option. something like "highlight_multiples: 5" and "only_show_multiples: 5"
> 
> also, should the numbers be aligned to the left rather than the right (or have even more options)?

should i then make new feature requests for all the above? @francesco-gaglione

**Comment by francesco-gaglione** [comment]
> > > @mikayla-maki I implemented the feature in the screenshot as requested from @RustoMCSpit. But decisions have to be made here. Do we want to make this feature enableable from settings or do we make it always on for all styles that are not arabic? Or do we even enable it by default
> > > image
> > 
> > 
> > id have it shaded the other way, the multiples of five should be more prominent, maybe even show them exclusively (or should that be another setting applied to all modes of styles that the fifth multiple line is the only one labelled? it's the same issue you mentioned). in my opinion, i believe users should be able to select to show multiples of fifths to be prominent (as in shaded more brightly or be the only visible numbers) in all counting systems but as an opt-in option. something like "highlight_multiples: 5" and "only_show_multiples: 5"
> > also, should the numbers be aligned to the left rather than the right (or have even more options)?
> 
> should i then make new feature requests for all the above? @francesco-gaglione

I think so, but let wait for the maintainers suggestions. I'm new here, second contribution here, so they can say more on how to proceed.

**Comment by RustoMCSpit** [comment]
okay sure, for the maintainers then a quick tl;dr -
 "highlight_multiples: 5" would have zed highlight multiples of any number placed after it, in this case multiples of 5

 "only_show_multiples: 5" would have zed only show multiples of any number placed after it, in this case multiples of 5

an example of highlight mulitples is below but note that the primary and secondary colors have been swapped, the multiples of 5 should be highlighted

image

**Comment by versecafe** [comment]
> And Hindi and Arabic!

@mikayla-maki Added them in here https://github.com/versecafe/zed/tree/custom-gutter-numerals

**Comment by francesco-gaglione** [comment]
@versecafe to avoid the code to be merged being scattered in various sources, can you merge your branch on this branch of the pull request?

**Comment by versecafe** [comment]
@francesco-gaglione 
image
Can't seem to open a PR to your branch, but I can open one to merge yours into mine. can you see if you can do open and merge it

**Comment by francesco-gaglione** [comment]
> @francesco-gaglione 
> image
> Can't seem to open a PR to your branch, but I can open one to merge yours into mine. can you see if you can do open and merge it

You can clone my repo and than merge localy or copy paste code. You only need to copy the convertion the rest of the code is the same

**Comment by francesco-gaglione** [comment]
Added your changes manually. This should be now ready, ready for review.

**Comment by RustoMCSpit** [comment]
> okay sure, for the maintainers then a quick tl;dr - "highlight_multiples: 5" would have zed highlight multiples of any number placed after it, in this case multiples of 5
> 
> "only_show_multiples: 5" would have zed only show multiples of any number placed after it, in this case multiples of 5
> 
> the reason this was brought up is because roman numerals are heavily oriented around multiples of 5, however we thought it would be best to allow this to work for any number system and any numbers multiples (hence the above two customisable parameters)
> 
> the idea of highlighting the number line is somewhat related to #13747
> 
> an example of highlight mulitples is below but note that the primary and secondary colors have been swapped, the multiples of 5 should be highlighted
> 
> image

what about this?

**Pull request closed without merging**
