### PR TITLE
windows: Make "Reveal in Finder" always open the file explorer

### PR DESCRIPTION
**Pull request by SomeRanDev**
At the current moment, the "Reveal in Finder" behavior on Windows "opens" the file using direct execution. This causes files to be opened with whatever software they are associated with (i.e. will open Sublime Text instead of the file explorer).

Release Notes:

- Fixed "Reveal in Finder" on Windows to open with the File Explorer. The new behavior always opens the file explorer with the target folder/file pre-selected.

https://github.com/zed-industries/zed/assets/28355157/b8ba471d-2f5b-4529-90c3-4dc59f308b99

### CODE REVIEW

**Comment by SomeRanDev** [comment]
@cla-bot check

**Comment by SomeRanDev** [comment]
This is outside the scope of this PR, but wanted to ask if a PR to change the "Reveal in Finder" text to "Reveal in Explorer" on Windows builds would be accepted if I made it?

**Comment by mikayla-maki** [comment]
yes!

**Comment by mikayla-maki** [comment]
Thank you!

**Comment by SomeRanDev** [comment]
Thanks for the pull! Glad this is how I spent my Thursday May 23, 2024.

**Pull request merged**
