### PR TITLE
Snippets: Move snippets into the core of editor

### PR DESCRIPTION
**Pull request by osiewicz**
Release Notes:

- Move snippet support into core editor experience, marking the official extension as deprecated. Snippets now show up in any buffer (including plain text buffers).

### CODE REVIEW

**Comment by didier** [comment]
Is it just me or is there no documentation anywhere on how these actually work?

**Comment by piechologist** [comment]
@osiewicz: thank you for baking snippet support into core Zed! Am I right that some features — notably word and path completions — are not available anymore?

My `settings.json` includes:
```json
"lsp": {
    "snippet-completion-server": {
      "settings": {
        "max_completion_items": 20, 
        "snippets_first": true,
        "feature_words": true,
        "feature_snippets": true,
        "feature_paths": true,
        "feature_unicode_input": false
      }
    }
  }
```
Do I need to adjust these settings?

**Comment by danremollino** [comment]
> Is it just me or is there no documentation anywhere on how these actually work?

Yeah, definitely needs a section added to the Docs page on the website.

I should be able to remove the extension now, correct? I can't get my old snippets working without the extension.

**Comment by stalexsm** [comment]
Can you tell me how to make snippets for Python now?

**Comment by ruanfdev** [comment]
Here is the only documentation i found that shows how to implement snippets, but would also like to know if this is still the correct method after being baked into the core - https://zed.dev/docs/snippets?highlight=snip#snippets

**Comment by danremollino** [comment]
> Here is the only documentation i found that shows how to implement snippets, but would also like to know if this is still the correct method after being baked into the core - https://zed.dev/docs/snippets?highlight=snip#snippets

This was recently added so should be up to date.

**Comment by didier** [comment]
It's very incomplete.

I'm unable to make snippets that contain some special characters such as "$", and JS specific snippsts don't show up in TS and vice versa

**Pull request merged**
