### PR TITLE
Add open vim keymap command

### PR DESCRIPTION
**Pull request by mmtftr**
Release Notes:

- Added a `vim: open default keymap` command to show the default Vim keymap ([#8593](https://github.com/zed-industries/zed/issues/8593)).

### CODE REVIEW

**Comment by maxdeviant** [comment]
I don’t think this PR is addressing the linked issue.

That issue seems to be about showing the Vim keybindings themselves next to the corresponding action in the command palette.

**Comment by mmtftr** [comment]
Sorry, then should it refer to #8593 instead?

**Comment by mmtftr** [comment]
can you give me an example of this signaling logic in the codebase?

**Comment by maxdeviant** [comment]
> can you give me an example of this signaling logic in the codebase?

We have an `emit` method on a `ViewContext` that can be used to emit events: https://github.com/zed-industries/zed/blob/a4b55b9924f9d45fd9012d0f2d408cd7c6e8addd/crates/gpui/src/window.rs#L2423-L2435

So you define an event type and register it with an `EventEmitter` on some type: https://github.com/zed-industries/zed/blob/a4b55b9924f9d45fd9012d0f2d408cd7c6e8addd/crates/extension/src/extension_store.rs#L114-L122

Then you can emit events:

https://github.com/zed-industries/zed/blob/a4b55b9924f9d45fd9012d0f2d408cd7c6e8addd/crates/extension/src/extension_store.rs#L598-L601

And subscribe to them:

https://github.com/zed-industries/zed/blob/a4b55b9924f9d45fd9012d0f2d408cd7c6e8addd/crates/extensions_ui/src/extensions_ui.rs#L131-L137

**Comment by mmtftr** [comment]
Added an event to the workspace to fix the caveat.

**Comment by maxdeviant** [comment]
@mmtftr Thanks!

**Pull request merged**
