### PR TITLE
Improve support for OpenAI-compatible services

### PR DESCRIPTION
**Pull request by amtoaer**
Currently, OpenAI supports custom API endpoints, but the inability to customize the model remains a limitation. For example, when using Ollama, the model name needs to be manually renamed to gpt-4-turbo-preview, and some third-party OpenAI-compatible services that use different model names cannot be used(e.g., https://platform.deepseek.com/api-docs/). This PR implements custom model names and max token count, aiming to provide greater flexibility.

I am unsure if it is necessary to implement proper `id` and `from_id` methods for custom models, because in the only use case for `from_id`, the called API endpoint is fixed as OPEN_AI_API_URL, which would not succeed in general use cases for custom models. Additionally, implementing a proper `id` method would require changing the return type from &str to String, which would have a broader impact. Hope someone can give me some advice.

Release Notes:

- Improved support for OpenAI-compatible services

### CODE REVIEW

**Comment by amtoaer** [comment]
@cla-bot check

**Comment by christ-offer** [comment]
Just tested this with openrouter and it's working great so far, tested gemini, openai, claude and llama3.

**Comment by rgbkrk** [comment]
I added Ollama directly in #12902. It'll pick up all the models you have available (and you can still set a default). Try it out and let me know how it's going.

**Comment by amtoaer** [comment]
> I added Ollama directly in #12902. It'll pick up all the models you have available (and you can still set a default). Try it out and let me know how it's going.

Thanks for your reply, I just tried it. It appears that the PR works fine for ollama but not for third-party OpenAI-compatible services. I used [deepseek api](https://platform.deepseek.com/api-docs/) mentioned above for testing and configured it as follows:
```json
  "assistant": {
    "version": "1",
    "provider": {
      "name": "ollama",
      "api_url": "https://api.deepseek.com/v1",
      "default_model": {
        "name": "deepseek-coder",
        "max_tokens": 16000,
        "parameter_size": ""
      }
    }
  }
```

However, I got a 404 error because ollama needs to `fetch_models` in order to `authenticate`.

image

```rust
[2024-06-12T11:31:21+08:00 ERROR util] crates/assistant/src/assistant_panel.rs:968: Failed to connect to Ollama API: 404 Not Found
```
Thus, that PR partially solved the problem. Further work is needed to fully support this use case. Regardless, the workaround of this PR is not suitable for now. I'll close it and consider a better solution.
Thanks again for your work.

**Comment by christ-offer** [comment]
Isnt this a bit hasty, it only fails because you said ollama instead of openai as provider (openai compatible apis has to use openai as provider name right?)

This works perfectly fine for me:

```
"assistant": {
    "version": "1",
    "provider": {
      "api_url": "https://openrouter.ai/api/v1",
      "name": "openai",
      "default_model": {
        "custom": {
          "name": "google/gemini-pro-1.5",
          "max_token_count": 2000000
        }
      }
    }
  },

```

**Comment by amtoaer** [comment]
@christ-offer @rgbkrk Sorry for the delay, I just opened a PR based on this one, introducing multiple custom models support: #13276.

**Comment by sahadev0079** [comment]
image
why don't i see the model? i am doing anything wrong ? @christ-offer

**Comment by bennetbo** [comment]
@sahadev0079 You can only provide custom models under the language_models settings, see https://zed.dev/docs/assistant/configuration#openai-custom-models

**Pull request closed without merging**
