### PR TITLE
Extract Elixir extension

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR extracts Elixir support into an extension and removes the built-in Elixir support from Zed.

As part of this, [Lexical](https://github.com/lexical-lsp/lexical) has been added as an available language server for Elixir.

Since the Elixir extension provides three different language servers, you'll need to use the `language_servers` setting to select the one you want to use:

#### Elixir LS

```json
{
  "languages": {
    "Elixir": {
      "language_servers": [ "elixir-ls", "!next-ls", "!lexical", "..."]
    }
  }
}
```

#### Next LS

```json
{
  "languages": {
    "Elixir": {
      "language_servers": [ "next-ls", "!elixir-ls", "!lexical", "..."]
    }
  }
}
```

#### Lexical

```json
{
  "languages": {
    "Elixir": {
      "language_servers": [ "lexical", "!elixir-ls", "!next-ls", "..."]
    }
  }
}
```

These can either go in your user settings or your project settings.

Release Notes:

- Removed built-in support for Elixir, in favor of making it available as an extension.

### CODE REVIEW

**Comment by baldwindavid** [comment]
Apologies if this is user error and/or something that won't work until the Preview release. I tried out `main` and got the "Do you want to install the recommended 'elixir' extensions for 'ex' files?" and no way to get it. This appears to be an extension within this main repo rather than https://github.com/zed-industries/extensions so perhaps there is a different workflow there. Anyway, all good if it works for the Preview release and I'll see it at that time.

**Comment by maxdeviant** [comment]
> Apologies if this is user error and/or something that won't work until the Preview release. I tried out `main` and got the "Do you want to install the recommended 'elixir' extensions for 'ex' files?" and no way to get it. This appears to be an extension within this main repo rather than https://github.com/zed-industries/extensions so perhaps there is a different workflow there. Anyway, all good if it works for the Preview release and I'll see it at that time.

I hadn't gotten around to publishing the Elixir extension yet. Will do so today!

Here's the PR to publish it: https://github.com/zed-industries/extensions/pull/644

Note that there are some settings that need to be adjusted in order to select which language server should be used, as the extension provides three.

If you try out the extension, do let me know if there is anything you want to see improved about it. I want to make sure we're not regressing in terms of the experience of using Elixir in Zed.

**Comment by scottming** [comment]
@maxdeviant 

Hello, thank you for your PR. I am one of the main contributors to Lexical. I haven't used Zed for a while. As the bugs in nvim increase, I'm considering switching to Zed. However, I noticed that this configuration is no longer valid. 

```json
   "elixir": {
    "lsp": {
      "local": {
        "path": "/Users/scottming/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
        "arguments": [""]
      }
    }

```

Could you please let me know how I can override the existing Lexical configuration to customize the run path? I need to use a custom version to test some new features.

**Comment by maxdeviant** [comment]
> @maxdeviant
> 
> Hello, thank you for your PR. I am one of the main contributors to Lexical. I haven't used Zed for a while. As the bugs in nvim increase, I'm considering switching to Zed. However, I noticed that this configuration is no longer valid.
> 
> ```json
>    "elixir": {
>     "lsp": {
>       "local": {
>         "path": "/Users/scottming/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
>         "arguments": [""]
>       }
>     }
> ```
> 
> Could you please let me know how I can override the existing Lexical configuration to customize the run path? I need to use a custom version to test some new features.

Would it work to put `lexical` on your PATH? We check for that first:

https://github.com/zed-industries/zed/blob/6cf6614c482376901d7b6d90b97163730af9d82d/extensions/elixir/src/language_servers/lexical.rs#L25-L27

If that doesn't work we can look into allowing configuring the binary path for the extension.

**Comment by scottming** [comment]
@maxdeviant 

I use this configuration, but it doesn't work. Zed will automatically download ElixirLS, which is not what I want.

```json
{
  "theme": "Dracula Pro (Buffy)",
  "buffer_font_size": 12,
  "buffer_font_family": "MonoLisa Nerd Font",
  "vim_mode": true,
  // Other settings fields
  "elixir": {
    "lsp": {
      "local": {
        "path": "/Users/scottming/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
        "arguments": [""]
      }
    }
  }
}
```

CleanShot 2024-07-17 at 21 13 11@2x

**Comment by maxdeviant** [comment]
> @maxdeviant
> 
> I use this configuration, but it doesn't work. Zed will automatically download ElixirLS, which is not what I want.
> 
> ```json
> {
>   "theme": "Dracula Pro (Buffy)",
>   "buffer_font_size": 12,
>   "buffer_font_family": "MonoLisa Nerd Font",
>   "vim_mode": true,
>   // Other settings fields
>   "elixir": {
>     "lsp": {
>       "local": {
>         "path": "/Users/scottming/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
>         "arguments": [""]
>       }
>     }
>   }
> }
> ```
> 
> CleanShot 2024-07-17 at 21 13 11@2x

Support for respecting the LSP settings has been added (https://github.com/zed-industries/zed/pull/14655) and is available in v0.0.6 of the Elixir extension.

Could you download v0.0.6 and try it with these settings?

```json
{
  "languages": {
    "Elixir": {
      "language_servers": ["lexical", "!elixir-ls", "!next-ls", "..."]
    }
  },
  "lsp": {
    "lexical": {
      "binary": {
        "path": "/Users/scottming/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
        "arguments": [""]
      }
    }
  }
}
```

**Pull request merged**
