### PR TITLE
vim: Add 'gf' command, make files cmd-clickable

### PR DESCRIPTION
**Pull request by mrnugget**
Release Notes:

- vim: Added `gf` command to open files under the cursor.
- Filenames can now be `cmd`/`ctrl`-clicked, which opens them.

TODOs:

- [x] `main_test.go` <-- works
- [x] `./my-pkg/my_pkg.go` <-- works
- [x] `../go.mod` <-- works
- [x] `my-pkg/my_pkg.go` <-- works
- [x] `my-pkg/subpkg/subpkg_test.go` <-- works
- [x] `file\ with\ space\ in\ it.txt` <-- works
- [x] `"file\ with\ space\ in\ it.txt"` <-- works
- [x] `"main_test.go"` <-- works
- [x] `/Users/thorstenball/.vimrc` <-- works, but only locally
- [x] `~/.vimrc` <--works, but only locally
- [x] Get it working over collab
- [x] Get hover links working

Demo:

https://github.com/user-attachments/assets/26af7f3b-c392-4aaf-849a-95d6c3b00067

Collab demo:

https://github.com/user-attachments/assets/272598bd-0e82-4556-8f9c-ba53d3a95682

### CODE REVIEW

**Comment by 0x2CA** [comment]
@mrnugget 

in vim use `g f` invalid, use command invalid.

use cmd+click work.

```
Zed: v0.151.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64
```

**Comment by mrnugget** [comment]
Where do you place the cursor? It works for me:


https://github.com/user-attachments/assets/b66cf7dd-3f4d-405e-9f91-f61f7e4149bd

Do you maybe have any conflicting bindings?

**Comment by 0x2CA** [comment]
> Where do you place the cursor? It works for me:
> 
>  screenshot-2024-08-29-15.16.33.mp4 
> 
> Do you maybe have any conflicting bindings?

Keystroke conflicts are unlikely because the annotations actually work!

https://github.com/user-attachments/assets/618f7154-b711-435b-8acc-bada08687813

**Comment by mrnugget** [comment]
> Keystroke conflicts are unlikely because the annotations actually work!

Have you tried opening Zed with default settings and seeing if it works then?

I also don't follow the reasoning: if the clicking works, but the keystrokes don't — the problem must be somewhere with the keystrokes, no?

**Comment by 0x2CA** [comment]
> > Keystroke conflicts are unlikely because the annotations actually work!
> 
> Have you tried opening Zed with default settings and seeing if it works then?
> 
> I also don't follow the reasoning: if the clicking works, but the keystrokes don't — the problem must be somewhere with the keystrokes, no?

I've already tried clearing all settings and keymaps, but it's still like this, which is frustrating.

**Comment by mrnugget** [comment]
But it works if you cmd-click on it? That's the confusing bit to me

**Comment by mrnugget** [comment]
Ahhh! I see what the problem is. Your file is named `assets/Scripts/Blade/Decorators/View.ts` (`.ts`!) but your import statement says `Blade/Decorators/View`.  Yeah, we don't add the file suffixes automatically yet, like Vim does. So, yes, that's to be expected.

And I guess when you click, then it's actually the language server that resolves the file path. So you will get the same result if you use `gd` instead of `gf`.

**Comment by mrnugget** [comment]
@0x2CA take a look at: https://github.com/zed-industries/zed/pull/17805 -- That should fix going to types of the same filetype even if the extension is missing.

**Comment by 0x2CA** [comment]
> @0x2CA take a look at: #17805 -- That should fix going to types of the same filetype even if the extension is missing.

hi,I tried it and felt pretty good, but there are some issues, such as the unavoidable use of js in ts projects, which cannot be jump, and maybe `suffixesadd` can make it more usable.
Of course, it can also include the search path.

**Pull request merged**
