### PR TITLE
Add metal lang

### PR DESCRIPTION
**Pull request by ghost**
Release Notes:

- Added support for metal language

### CODE REVIEW

**Comment by nervenes** [comment]
Skärmavbild 2024-12-08 kl  23 25 08

**Comment by maxdeviant** [comment]
Thanks for the PR, but this should go into an extension.

**Comment by nervenes** [comment]
could we reconsider @maxdeviant ? metal is essentially cpp, all it needs is the cpp grammar which is already shipped in zed otb, all this pr does is using that grammar and copies the other cpp schemes into its own "metal" subset.

**Comment by mikayla-maki** [comment]
I think it's acceptable for this to duplicate the tree sitter C++ for the extension. Eventually, we'd like to not have any native extensions, and perhaps have language's association with metal provided by a C++ wasm extension.

**Pull request closed without merging**
