### PR TITLE
Fix JavaScript and TypeScript HTML injections

### LINKED ISSUE #16199: JavaScript injection (Template Strings):  HTML syntax highlight may fail for closing tags
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A PR has recently been merged to allow for syntax highlighting within template strings in JavaScript files: #15984

This PR is really great, this is a feature I really needed since I work with [`Lit`](https://lit.dev/docs/components/rendering/) everyday. 

It seems the injection does not completely work for `lit-html` templates because any time there is an interpolation (`${// some js content}`) within an element, its closing tag is not highlighted properly:
image

### Environment

Zed: v0.147.2 (Zed)
OS: Linux Wayland cachyos unknown
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4070 Ti || NVIDIA || 560.31.02

### Possible solution

I don't know much about treesitter, I merely reuse stuff I find and tweak them but it seems that removing the `string_fragment` part from the injection fixes my issue but I'm not good enough with treesitter to be sure it won't break other cases.

```scm
(call_expression
  function: (identifier) @_name (#eq? @_name "html")
  arguments: (template_string) @content
                              (#set! "language" "html")
)
```

This solution is also a little bit closer to what nvim-treesitter does: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ecma/injections.scm#L8

image

I could create a PR for that but since I'm a treesitter noob I preferred raising the issue and discussing it before creating a PR nobody asked for :roll_eyes: 

@RobinMalfait I'd love to have your opinion about this (thanks again for your PR, I hope me pinging you here is not rude, sorry if it is)

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by florian-sanders**
Fixes #16199

## Description

Recently added template string injections do not completely work for because any time there is an interpolation (`${// some js content}`) within an element, its closing tag is not highlighted properly:
image

This PR fixes the issue:
image

Release Notes:

- Fixed incomplete syntax highlighting for HTML injections inside JavaScript template tags.

## Note

I'm a beginner with treesitter so I only modified the part for HTML usecase. 
Should the same solution be applied to other injections (`css`, `js`, etc.)?

### CODE REVIEW

**Comment by mrnugget** [comment]
Thank you! Paging @RobinMalfait here for a quick look. But looks fine from my side.

**Comment by florian-sanders** [comment]
Thanks, I took the liberty of adding the same change to the TypeScript injection if it's alright with you and Robin :+1: 

It's in a separate commit.

**Comment by mrnugget** [comment]
@florian-sanders I assume you tested this with all different filetypes and it works, right?

**Comment by mrnugget** [comment]
Tested it locally, works fine! Merging.

**Comment by MichaPau** [comment]
I still have a small problem when using a `:host` selector inside a template string. (and only with :host selector; :root, .some-class, #some-id ...  all formatting correctly)..

wrong formatting:
Zed_01_Screenshot_2025-01-05_19-36-19
good formatting:
Zed_02_Screenshot_2025-01-05_19-36-19

**Comment by notpeter** [comment]
@MichaPau Please do not comment on a stale PR from 5 months ago.

**Pull request merged**
