### PR TITLE
Simplify livekit config so that cargo check Just Works

### PR DESCRIPTION
**Pull request by mikayla-maki**
Supersedes https://github.com/zed-industries/zed/pull/21653

This enables us to use `cargo test -p workspace` on macOS and Linux.

Note that the line diffs in `shared_screen.rs` are spurious, I just re-ordered the `macos` and `cross-platform` modules to match the order in the call crate.

Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
@WeetHet 

It's a bit more of a cut, but this patch file should allow you to build with the livekit rust sdk for macOS
[use-cross-platform-livekit.patch](https://github.com/user-attachments/files/18043344/use-cross-platform-livekit.patch)

**Comment by mikayla-maki** [comment]
@WeetHet As I mentioned in the other PR, using rust features to conditionally enable and disable the livekit rust SDK didn't seem very viable

So in this PR I've included a patch file you can use in your nix build: https://github.com/zed-industries/zed/blob/8b5c039b08c977bb03aac0eb9aa4b6d3e780efe3/script/patches/use-cross-platform-livekit.patch

And since we want to move to the livekit Rust SDK on all platforms, I've added a step to our CI that checks if that patch still compiles.

**Comment by WeetHet** [comment]
> @WeetHet As I mentioned in the other PR, using rust features to conditionally enable and disable the livekit rust SDK didn't seem very viable
> 
> So in this PR I've included a patch file you can use in your nix build: [`8b5c039`/script/patches/use-cross-platform-livekit.patch](https://github.com/zed-industries/zed/blob/8b5c039b08c977bb03aac0eb9aa4b6d3e780efe3/script/patches/use-cross-platform-livekit.patch)
> 
> And since we want to move to the livekit Rust SDK on all platforms, I've added a step to our CI that checks if that patch still compiles.

Thank you, this also works

**Comment by WeetHet** [comment]
Are you sure there're supposed to be `+#[cfg(not(all()))]` and not `+#[cfg(any())]` in the patch?

**Pull request merged**
