### PR TITLE
remote_server: Fix lost `load-grammars` for remote server

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
We don't want to load the tree sitter grammars on the remote server

**Comment by CharlesChen0823** [comment]
current in remote server, crashed.

**Comment by mikayla-maki** [comment]
What's the crash and does this PR fix it?

**Comment by CharlesChen0823** [comment]
this is easy reproduce, you cannot using lsp in remote server,etc. go_to_definition

**Comment by mrnugget** [comment]
@bennetbo and I are investigating. Current suspect: https://github.com/zed-industries/zed/commit/43258190751251b4fa03ce721d74acd1d414a241#diff-d29f6dd9e43c17ea0d810c5ab6c24009716901a9b871934bf95f525d1e43dd33

**Comment by mrnugget** [comment]
Yep, that was it: https://github.com/zed-industries/zed/pull/19821

**Pull request closed without merging**
