### PR TITLE
Revert accidental change to Rust outline files

### PR DESCRIPTION
**Pull request by ConradIrwin**
Release Notes:

- Preview only: Fixed impl blocks in the rust outline view

### CODE REVIEW

**Comment by marcospb19** [comment]
Hi @ConradIrwin, was this bug also expected to only happen in Preview?

FYI, Rust outline is now broken in v0.165.4 now, it's the non-preview version (I'm not sure how you guys work, shouldn't this fix go to v0.165 too? anyways just letting you know).

**Comment by ConradIrwin** [comment]
@marcospb19 hmm, I thought I broke it in 75c9dc179b, which is in 0.166+, and the fix is 44264ffedcfe1a87606e7d6a9a52aaadf88061f5 which is also in 0.166+

What are you seeing on 0.165?

**Comment by marcospb19** [comment]
@ConradIrwin 2 days ago I tested in 0.164 and 0.165.

In 0.165 the trait definitions don't appear in the outline panel.

**Comment by marcospb19** [comment]
Alright, let me stop being lazy :rofl: (Zed takes long to compile when I change its versions).

I went back and compiled versions again to take screenshots and show you.

## Main branch (9daa426e936c5d0b2f3a24e1cffde434c38a13de): 

[Example of simple impl block](https://github.com/zed-industries/zed/blob/9daa426e936c5d0b2f3a24e1cffde434c38a13de/crates/editor/src/element.rs#L6453
):

image

Outline panel:
image

missing the `impl HighlightRange` line!

[Now a trait impl](https://github.com/zed-industries/zed/blob/9daa426e936c5d0b2f3a24e1cffde434c38a13de/crates/editor/src/element.rs#L5137-L5144):

image

Again, no impl block, and no nesting.

## 0.164.x branch, when it was working:

Same two examples:

image

image

All properly nested and showing up when I search 'em.

image

---

I assumed it was a problem with this PR due to the title and diff, but, as we can see now, it's still a problem in the latest `main`.

**Comment by ConradIrwin** [comment]
cc @SomeoneToIgnore any idea why the nesting would be messed up in the outline panel?

**Comment by SomeoneToIgnore** [comment]
Seems like a bug in the item depth calculation to me.

**Pull request merged**
