### PR TITLE
zig: Bump to v0.1.4

### PR DESCRIPTION
**Pull request by mrnugget**
This PR bumps the Zig extension to v0.1.4.

Changes:

- #14379

Release Notes:

- N/A

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@mrnugget We can't publish the Zig extension right now since it depends on an unpublished version of the Zed extension API.

**Comment by mrnugget** [comment]
Oh, no, that sucks. What's the plan?

**Comment by maxdeviant** [comment]
> Oh, no, that sucks. What's the plan?

It depends on how pressing the new features in the extension are.

I was hoping to hold the new extension API release until we've firmed up the Assistant-related functionality it contains (so we don't have to have another breaking change soon).

So we can either:

1. Hold off on publishing the Zig extension until ~later this month
2. Publish the extension API now so we can publish the Zig extension
3. Roll back the changes to the Zig extension that are dependent on the new extension API and publish the extension

**Comment by maxdeviant** [comment]
> > Oh, no, that sucks. What's the plan?
> 
> It depends on how pressing the new features in the extension are.
> 
> I was hoping to hold the new extension API release until we've firmed up the Assistant-related functionality it contains (so we don't have to have another breaking change soon).
> 
> So we can either:
> 
> 1. Hold off on publishing the Zig extension until ~later this month
> 2. Publish the extension API now so we can publish the Zig extension
> 3. Roll back the changes to the Zig extension that are dependent on the new extension API and publish the extension

I'll just proceed with option 3: https://github.com/zed-industries/zed/pull/14652

**Comment by mrnugget** [comment]
> I'll just proceed with option 3: #14652

Good call! Since _this_ PR here would include the feature that allows users to specify their own `zls`, which can help with the "we use latest version" issue.

**Review by maxdeviant — APPROVED** [review]

**Comment by mrnugget** [comment]
Thanks @maxdeviant! Appreciate it a lot :)

**Pull request merged**
