### PR TITLE
Add ability to split terminals

### PR DESCRIPTION
**Pull request by dangdennis**
Closes #ISSUE

Release Notes:

- N/A *or* Added/Fixed/Improved ...

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Hey, small update on the terminal tab: you seem to have missed that I've got assigned to https://github.com/zed-industries/zed/issues/4351 issue.
I've started my work in https://github.com/zed-industries/zed/tree/kb/split-terminal and have a prototype that can split tabs.

It has no actions for that, as started with the most complex case: drag and dropping tabs, similar to what central pane allows doing with the regular ones.

In my opinion, this PR picked some odd direction by introducing custom actions and split directions and whatever else: instead, we seem to benefit more by reusing the same approach as the central pane does, getting all key combinations and functionality reused automagically.

So, I'm going to close this PR, sorry.
There's a lot of work and polishing needed on top of that other branch still, so if you really want to, let's consolidate there — at least, some testing is very needed.

**Comment by dangdennis** [comment]
Yeaup certainly missed it. I also accidentally linked a stale PR to the issue, didn’t want to broadcast that I was exploring.

I’m interested in testing your branch.

Fwiw I haven’t made much progress either on my own working PR: https://github.com/dangdennis/zed/pull/1

**Comment by SomeoneToIgnore** [comment]
Heads-up, I have a branch that seems to work: https://github.com/zed-industries/zed/tree/kb/split-terminal
The only notable issue is the absence of DB persistence, so all splits are gone on Zed restart.
This is quite a large issue and might take some time to fix, but otherwise the functionality seems to be complete and ready to be tested, if you want to.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/21238

**Pull request closed without merging**
