### PR TITLE
Use square buttons for code action and run indicators in the gutter

### PR DESCRIPTION
**Pull request by versecafe**
### Before

Screenshot 2024-06-14 at 1 34 54 PM

Screenshot 2024-06-14 at 1 35 04 PM

### After

Screenshot 2024-06-14 at 1 34 27 PM

Screenshot 2024-06-14 at 1 34 33 PM

Release Notes:

- Improved the look of code action and run indicators in the gutter ([#12803](https://github.com/zed-industries/zed/issues/12803)).

### CODE REVIEW

**Comment by versecafe** [comment]
> Note the icon size between the bolt and the play icon are intentionally different as using the two different sizes actually leads to the appearing roughly the same height in the UI

**Comment by maxdeviant** [comment]
> > Note the icon size between the bolt and the play icon are intentionally different as using the two different sizes actually leads to the appearing roughly the same height in the UI

We want to use consistent icon sizes. If they look off that is something that needs to be fixed at the icon level.

**Comment by versecafe** [comment]
@maxdeviant Fixed it, and left a note in the commit description that the play button SVG should probably be resized a little.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
