### PR TITLE
Fix: Copilot Chat is logged out  

### LINKED ISSUE #21255: Copilot chat logged out while autocomplete is logged in
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am signed in but still see the login prompt. Autocompletion is working.
Got copilot through our company profile, has Github enterprise.

If there is any useful debug info I can provide you, I would be happy to help.

Screenshot 2024-11-27 at 23 33 02

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

I could not find any relevant log entries.

### PR DESCRIPTION
**Pull request by fred-sch**
Closes #21255

Release Notes:

- Fixed Copilot Chat OAuth Token parsing

### CODE REVIEW

**Comment by fred-sch** [comment]
@cla-bot check

**Comment by fred-sch** [comment]
I summarized the details of this fix in https://github.com/zed-industries/zed/issues/21255#issuecomment-2508940898.

**Comment by bennetbo** [comment]
Hey, thanks for investigating! This PR breaks copilot chat for me, because (for whatever reason) the oauth token is still stored in `hosts.json` on my machine.
However, looking at other repositories on GitHub, it seems like that it's actually pretty common, to check for both `hosts.json` and `apps.json` ([search query](https://github.com/search?q=github-copilot%2Fapps.json&type=code)).
I changed the implementation to handle both cases, can you check if this still works for you?

**Comment by fred-sch** [comment]
Thanks for your feedback. Your fix is still working fine for me! 

I was expecting that users would need to sign-out and sign-in again into github copilot (because they have the `hosts.json` file but not the `apps.json`), but I totally agree that checking both files is the better solution.

**Comment by bennetbo** [comment]
Thanks for verifying! After logging out and in again, I can indeed see the `hosts.json` file appearing, not sure why I did not make that connection.
Anyways, thanks for fixing this!

**Comment by erenergul** [comment]
Its not working in my case. Still can not login for chat.

**Comment by bennetbo** [comment]
> Its not working in my case. Still can not login for chat.

The fix has not been released (although it will be part of today's preview release). Are you running into this building from main?

**Pull request merged**
