### PR TITLE
windows: Fix `tailwind-language-server`

### LINKED ISSUE #17741: windows: Sometimes `tailwind-launguage-server` refuses to work
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For some unclear reasons, the `tailwind-language-server` sometimes fails to run properly, as discussed in #13891 and #13786. When this issue occurs, the error message typically indicates that the executable file `.bin/tailwindcss-language-server.ps1` is missing from the installation directory.

Strangely, I am unable to reproduce this bug on my machine, so additional information would be helpful.

### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #17741

I'm not sure why, but ever since `tailwind` was upgraded to `0.24`, there have been occasional errors indicating that the `.ps1` file could not be found. After reviewing the `.ps1` script, it appears that it simply starts the server using `node`. This PR directly using the method from the script to start the server with `node`.

Co-authored-by: Anay <me@anayparaswani.dev>

Release Notes:

- N/A

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Nice! It's always good to fix bugs by deleting code.

Is this still a draft for a reason? Otherwise happy to merge.

**Comment by JunkuiZhang** [comment]
> Nice! It's always good to fix bugs by deleting code.
> 
> Is this still a draft for a reason? Otherwise happy to merge.

I'll update co-author info, then I think this PR is good to be merged.

**Comment by JunkuiZhang** [comment]
@ConradIrwin Sorry for disturbing you, this PR is ready for review.

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
