### PR TITLE
Add ability to separately set background color for highlighted brackets

### LINKED ISSUE #16380: [Accessibility] Alternative display style for editor.document_highlight.read_background
### Check for existing issues

- [X] Completed

### Describe the feature

AFAIK, the only way to change appearance of dynamic bracket highlighting is with `editor.document_highlight.read_background`. This value is very dim by default in most themes, but regardless, changing the background color of a single character does not make it stand out very much. You don't want to go overboard since making it too bright only reduce contrast. Plus this color is also used to highlight words matching the one under the cursor and it would get too distracting. 

 
Screenshot 2024-08-14 at 9 12 32 AM

I request another option to using the background color for this purpose, such as combination of different foreground color, style, and/or drawing a line beneath. Sublimetext does all of that as shown here

Screenshot 2024-08-14 at 9 13 17 AM

This is very clear and also looks nice (IMO). Obviously people with better eyes than mine will choose less bright colors, but I think this is an accessibility feature that will benefit everyone

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by thataboy**
Closes https://github.com/zed-industries/zed/issues/16380

Currently brackets are highlighted with `editor.document_highlight.read_background`. This commit adds a separate `editor.document_highlight.bracket_background` theme setting so bracket highlights can be made more prominent without doing the same to other highlights, making the display too busy.

(My own theme)

https://github.com/user-attachments/assets/29a8c05e-2f1a-4c16-9be8-a4b4cb143548

I set defaults for light and dark theme that I hope are sensible and not too obnoxious, but   noticeable so people can change it if they don't like it.

Release Notes:

- Added `editor.document_highlight.bracket_background` field to the theme to set background color of highlighted brackets.
  - This will fall back to `editor.document_highlight.read_background`, if not set.

Screenshot 2024-09-08 at 8 46 57 AM
Screenshot 2024-09-08 at 9 03 27 AM

### CODE REVIEW

**Comment by AlbertMarashi** [comment]
Nice, I like this

**Comment by juliangarnier** [comment]
I like this too!
I think the readability could be improved even further by also allowing setting a foreground color (see https://github.com/zed-industries/zed/issues/17890)

**Comment by thataboy** [comment]
> I like this too! I think the readability could be improved even further by also allowing setting a foreground color (see #17890)

I agree, but it's more work than I wanted to do :) I think you can work around this by selecting the appropriate `punctuation.bracket` color in your theme to match with `editor.document_highlight.bracket_background`

In general, from an accessibility point of view, I don't like relying on background color to highlight things because you can't guarantee good contrast while keeping the foreground color the same (which you probably want to do for the sake of syntax highlighting). Some alternative or additional mean to highlight is needed, like underlining or drawing a box around the selection, but that requires deeper knowledge of the code and maybe the gpui library than I have now. Would love if someone chose to tackle this!

**Comment by juliangarnier** [comment]
> In general, from an accessibility point of view, I don't like relying on background color to highlight things because you can't guarantee good contrast while keeping the foreground color the same (which you probably want to do for the sake of syntax highlighting). 

In some cases it's preferred to prioritise contrast over syntax, for example search results: 
highlights

> Some alternative or additional mean to highlight is needed, like underlining or drawing a box around the selection, but that requires deeper knowledge of the code and maybe the gpui library than I have now. Would love if someone chose to tackle this!

It doesn't necessary means losing syntax highlighting, SublimeText allows to set an optional `selection_foreground` color to individual syntax color properties at the syntax level:

```json
{
    "scope": "comment",
    "foreground": "color(var(grey))",
    "selection_foreground": "color(var(bg2))",
},
```

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
