### PR TITLE
Add vulkan linux dependency

### PR DESCRIPTION
**Pull request by pigletfly**
Release Notes:

- Fixed ([#8934](https://github.com/zed-industries/zed/issues/8934)).

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

**or**

- N/A

### CODE REVIEW

**Comment by skullcrushercmd** [comment]
i was just compiling it today and was getting that issue, thanks for the fix

**Comment by pigletfly** [comment]
after this patch ```cargo run --release``` passed, but still some errors exist
```
[2024-03-06T14:40:54+08:00 ERROR fs] watch path does not exist: /home/wangbing/.config/zed/keymap.json
[2024-03-06T14:40:54+08:00 ERROR fs] watch path does not exist: /home/wangbing/.config/zed/settings.json
[2024-03-06T14:40:54+08:00 ERROR util] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-03-06T14:40:54+08:00 ERROR util] crates/zed/src/zed.rs:619: EOF while parsing a value at line 1 column 0
[2024-03-06T14:40:54+08:00 ERROR fs] watch path does not exist: /home/wangbing/.config/zed/tasks.json
```

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
#8168 appears to be a collection of different things.
For instance, https://github.com/zed-industries/zed/issues/8168#issuecomment-1974913411 is unlikely going to be resolved by this PR, since the person says they already installed this package.

**Comment by pigletfly** [comment]
> #8168 appears to be a collection of different things. For instance, [#8168 (comment)](https://github.com/zed-industries/zed/issues/8168#issuecomment-1974913411) is unlikely going to be resolved by this PR, since the person says they already installed this package.

so I will create a new issue instead

**Comment by jansol** [comment]
Does this really need the -devel package? AFAIK most Rust vulkan bindings don't need that - they only need libvulkan1.

**Comment by someone13574** [comment]
> Does this really need the -devel package? AFAIK most Rust vulkan bindings don't need that - they only need libvulkan1.

No, it doesn’t need it. It is a runtime error, not a build error.

**Pull request merged**
