### PR TITLE
Recognize Cuda files as C++

### LINKED ISSUE #16070: C++ LSP should recognize .cu and .cuh
### Check for existing issues

- [X] Completed

### Describe the feature

CUDA files (using the .cu and .cuh extensions) are supported out-of-the-box by clangd; it would make sense for zed to map these extensions by default to the C++ LSP.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by Athishpranav2003**
Closes #16070 

Release Notes:

- Added support for recognizing Cude files as C++.

### CODE REVIEW

**Comment by Athishpranav2003** [comment]
@cla-bot check

**Comment by Athishpranav2003** [comment]
@cla-bot check

**Comment by Athishpranav2003** [comment]
Hi @maxdeviant . Seems like the CI tests are passing(not sure of the skipped ones). Is the PR fine?

**Comment by notpeter** [comment]
Thanks for your contribution @Athishpranav2003!

**Pull request merged**
