### PR TITLE
Fix Supermaven crash when handling non-ASCII text

### LINKED ISSUE #18027: Regional indicator symbols (emoji flags) broken on Windows
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The symbols of the regional indicators are not displayed in zed. In other IDEs, characters like "🇩🇪" turn into emoji or are displayed simply as text. But in zed there is just an invisible string. Changing fonts didn't help.

### Environment

WindowsBuildLabEx                                       : 22621.1.amd64fre.ni_release.220506-1250
WindowsProductName                                      : Windows 10 Home Single Language
CsProcessors                                            : {AMD Ryzen 9 7950X 16-Core Processor            }
PowerPlatformRole                                       : Desktop

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/d92af7e7-993f-46bf-86b4-3fb0d1834108

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0868679+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0869971+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0871325+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0872584+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0873769+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0874821+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0875572+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0876533+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
2024-09-18T21:42:45.0877576+03:00 [ERROR] The font or sequence of glyphs does not contain colored glyphs. (0x8898500C)
</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #18027

Fixed the issue where Supermaven would crash when handling non-ASCII text.

In #17578, the problem was as follows:
- There was no distinction between `char_index` and `utf8_index`. In fact, they are only equal when dealing with ASCII strings. For non-ASCII strings, they are often different, leading to crashes. For example:
```rust
let text = "你好";
text.len(); // Outputs 6
text.chars().count(); // Outputs 2
```
- When updating the `Anchor` of `BufferSnapshot`, it would simply add 1, without considering the non-ASCII character problem.

This PR introduces `StringIndexConverter` to address these issues. Additionally, I'm unsure whether other inline completion providers have similar issues. I currently can't test with Copilot since my GitHub student pack hasn't been approved yet.

Release Notes:

- Fixed the issue where Supermaven would crash when handling non-ASCII text ([#18027](https://github.com/zed-industries/zed/issues/18027)).

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
https://github.com/user-attachments/assets/401a9720-b00f-4176-94e8-9755ea3c29c7

**Comment by ConradIrwin** [comment]
Thanks for taking a pass at this!

Can we fix it by adding the char.len_utf8 in the loop instead of adding the index tracker struct?

**Comment by JunkuiZhang** [comment]
I'm not entirely sure because we would need to track both `utf_ix` and `char_ix`, which would give us four variables: `completion_text_utf8_ix`, `buffer_text_utf8_ix`, `completion_text_char_ix`, and `buffer_text_char_ix`. This would make the code extremely hard to read. That's why I refactored the code and introduced `StringIndexConverter`. You can refer to commit e020fe9 to compare the code before and after the refactor.

**Comment by ConradIrwin** [comment]
@JunkuiZhang I think https://github.com/zed-industries/zed/pull/18235 works to fix this without introducing the extra tracking classes?

**Comment by ConradIrwin** [comment]
I've merged #18279 - which seems to fix the language.txt problem

**Comment by JunkuiZhang** [comment]
I had also considered using graphemes, similar to what was discussed in #10198. However, I'm unsure about the performance implications, so I actually lean more toward the char-based solution.

**Pull request closed without merging**
