### PR TITLE
windows: Update crate `Windows` from `0.53` to `0.56`

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Version 0.56 has fixed many of the previous bugs, and one of the bugs prevent me implementing some functions.

Release Notes:

- N/A

### CODE REVIEW

**Comment by ognevny** [comment]
cool, that adds `i686_gnullvm` support for windows

**Comment by JunkuiZhang** [comment]
> cool, that adds `i686_gnullvm` support for windows

I noticed that you closed your PR. My PR serves as a good complement to yours, as mine simply updates the `windows` crate from `0.53` to `0.56`, and there are updates to many crates in your PR that are not included in this one, such as updates to `chrono`.

**Comment by ognevny** [comment]
> > cool, that adds `i686_gnullvm` support for windows
> 
> I noticed that you closed your PR. I think this PR can be a good complement to yours, as mine simply updates the `windows` crate from `0.53` to `0.56`, and there are updates to many crates in your PR that are not included in this one, such as updates to `chrono`.

yours should be enough

**Comment by mikayla-maki** [comment]
Thank you!

**Pull request merged**
