### PR TITLE
vim: smartcase find option

### PR DESCRIPTION
**Pull request by romgrk**
Release Notes:

- Added option `use_smartcase_find` to the vim-mode

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this!

Is there a plugin/setting in vim you're coping here? I want to make sure if people are trying to find this setting we can direct them there.

**Comment by romgrk** [comment]
The "smartcase" terminology comes from [vim](https://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase') but that applies to the `/` search, not `f`.

Extending the behavior of `f` with smartcase, also including [multiline find](https://github.com/zed-industries/zed/pull/8448), usually comes from plugins such as [clever-f](https://github.com/rhysd/clever-f.vim) (vim) and [improved-ft](https://github.com/backdround/improved-ft.nvim) (neovim).

But this is also handled by the more advanced jump plugins which have the infrastructure to improve both `f` as well as their special jumps, the likes of [vim-sneak](https://github.com/justinmk/vim-sneak?tab=readme-ov-file#usage) or [leap.nvim](https://github.com/ggandor/leap.nvim?tab=readme-ov-file#leapnvim). Leap is imho the most efficient jump plugin because of its UX, I'm hoping to implement it here also, as switching away from neovim without that plugin considerably slows down my efficiency.

Demo: extended `f` (`fi` followed by `;` repeats) and leap jump (`;nvj`: `;` start jump + 2 search letters + target).

[Kooha-2024-03-08-05-55-47.webm](https://github.com/zed-industries/zed/assets/1423607/be49f307-422a-4ed3-a7a7-40c718bf57d5)

**Comment by hferreiro** [comment]
Are there any plans to implement this for buffer search?

**Comment by romgrk** [comment]
Wdym by buffer search? Like [barbar's magic jump mode](https://github.com/romgrk/barbar.nvim?tab=readme-ov-file#jump-to-buffer-mode)?

**Comment by hferreiro** [comment]
I'm sorry, maybe I misunderstood, but from the comment above I thought this would only apply to `f` and not to `/`?

**Comment by romgrk** [comment]
Not planned afaict from the open issues, but I was hoping to do some work on the search integration to have it behave more like a vim user would expect, including the smartcase beahvior. I'll get around to it unless someone else is interested in implementing it. Wink wink.

**Comment by ConradIrwin** [comment]
:+1: Happy to work together on that if you'd like: https://calendly.com/conradirwin/pairing

**Pull request merged**
