### PR TITLE
Fix node LSPs on Windows

### PR DESCRIPTION
**Pull request by LoganDark**
I noticed #11156 after I was already mostly done with this, but it looks like that one is not going to be merged anyway.

Everything now works for me on Windows, but I'll need someone on macOS to verify it still works there too. (It should)

Release Notes:

- Fixed Node.js-based language servers on Windows

### CODE REVIEW

**Comment by LoganDark** [comment]
oops, looks like command prompts are popping up for each npm command. let me fix that real quick

image

**Comment by LoganDark** [comment]
looks like the JSON and Python language servers are still broken on my machine, investigating

**Comment by LoganDark** [comment]
it looks like #11156 was merged, but I'm going to ignore that for now since it was already on the path to merging when I started this. Assuming my PR ends up better, I've already rebased it on top of a revert.

**Comment by LoganDark** [comment]
I keep getting these:

```
0 verbose cli C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\node.exe C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 5ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\LoganDark\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\blank_user_npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\blank_global_npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 5ms
16 timing config:load Completed in 17ms
17 timing npm:load:configload Completed in 17ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm info vscode-json-languageserver
21 verbose argv "--cache" "C:\\Users\\LoganDark\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache" "--userconfig" "C:\\Users\\LoganDark\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\blank_user_npmrc" "--globalconfig" "C:\\Users\\LoganDark\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\blank_global_npmrc" "info" "vscode-json-languageserver" "--json" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 6ms
24 timing npm:load:display Completed in 7ms
25 verbose logfile logs-max:10 dir:C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-09T13_46_43_878Z-
26 verbose logfile C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-09T13_46_43_878Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 42ms
31 silly logfile start cleaning logs, removing 4 files
32 silly logfile done cleaning log files
33 timing command:info Completed in 7175ms
34 verbose type system
35 verbose stack FetchError: request to https://registry.npmjs.org/vscode-json-languageserver failed, reason: getaddrinfo EAI_FAIL registry.npmjs.org
35 verbose stack     at ClientRequest.<anonymous> (C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
35 verbose stack     at ClientRequest.emit (node:events:513:28)
35 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
35 verbose stack     at TLSSocket.emit (node:events:525:35)
35 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
35 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
35 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
36 verbose cwd C:\Users\LoganDark\zed
37 verbose Windows_NT 10.0.25931
38 verbose node v18.15.0
39 verbose npm  v9.5.0
40 error code EAI_FAIL
41 error syscall getaddrinfo
42 error errno EAI_FAIL
43 error network request to https://registry.npmjs.org/vscode-json-languageserver failed, reason: getaddrinfo EAI_FAIL registry.npmjs.org
44 error network This is a problem related to network connectivity.
44 error network In most cases you are behind a proxy or have bad network settings.
44 error network
44 error network If you are behind a proxy, please make sure that the
44 error network 'proxy' config is set properly.  See: 'npm help config'
45 verbose exit 1
46 timing npm Completed in 7245ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     C:\Users\LoganDark\AppData\Local\Zed\node\node-v18.15.0-win-x64\cache\_logs\2024-05-09T13_46_43_878Z-debug-0.log
```

This should be entirely impossible, as I am connected to the internet, and I cannot reproduce this outside of Zed, so I have no idea what could be happening. Even executing the exact same command line somewhere else does not reproduce the issue. It seems like commands only intermittently work and otherwise fail with this nonsensical DNS error.

**Comment by LoganDark** [comment]
Oh well, marking as non-draft for now as I believe that NPM issue is a separate issue. With these changes I'm able to use all the language servers that will actually install correctly, maybe eventually someone will have to figure out why npm is failing for no reason but it eventually works and that's what matters. I don't believe it's anything wrong with my code, just npm being dumb.

**Comment by LoganDark** [comment]
I've been daily driving this for a few days and it works relatively ok. Open to feedback, I'd consider this relatively merge-ready unless the DNS thing is an issue with my code instead of my computer.

**Comment by LoganDark** [comment]
seems like there is an issue where paths from wasm are not normalized properly, 
image

because the wasm binary itself is not windows-aware.

need to fix this

**Comment by LoganDark** [comment]
alright now all kinds of language servers work:
- rust-analyzer obviously works
- built-in node language servers work (typescript, tailwind, css, python)
- extension language servers work (html, svelte)

I don't know if I should mass-apply the changes that made the html and svelte extensions work, that pattern is repeated basically everywhere else even though version directories don't and probably never have(?) existed - I have no idea what the rationale was for these or if they're still necessary on macOS which is why I didn't already. Can someone from Zed weigh in on this?

**Comment by AcoXQ** [comment]
I have this error i dont know why i am getting this error
`stdout: "{\n  \"error\": {\n    \"code\": \"EAI_FAIL\",\n    \"summary\": \"request to https://registry.npmjs.org/@prettier%2fplugin-php failed, reason: getaddrinfo EAI_FAIL registry.npmjs.org\",\n    \"detail\": \"This is a problem related to network connectivity.\\nIn most cases you are behind a proxy or have bad network settings.\\n\\nIf you are behind a proxy, please make sure that the\\n'proxy' config is set properly.  See: 'npm help config'\"\n  }\n}\n"
stderr: "npm ERR! code EAI_FAIL\nnpm ERR! syscall getaddrinfo\nnpm ERR! errno EAI_FAIL\nnpm ERR! network request to https://registry.npmjs.org/@prettier%2fplugin-php failed, reason: getaddrinfo EAI_FAIL registry.npmjs.org\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network 'proxy' config is set properly.  See: 'npm help config'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\acox\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\cache\\_logs\\2024-05-13T21_27_15_499Z-debug-0.log\n"`

**Comment by LoganDark** [comment]
okay, apparently it's not just my machine then. thanks for the report. I have absolutely no fucking clue what is going wrong, so if anyone knows why zed's mere existence causes npm to suddenly fail to use the internet please let me know

**Comment by mikayla-maki** [comment]
Thank you for the contribution @LoganDark, unfortunately this PR changes too much for us to review / merge properly. Let's try making a plan of attack for 'Node LSPs on windows' via a tracking issue, and see if we can split this up into digestible chunks :)

**Comment by LoganDark** [comment]
I could clean up the series of commits, a lot of them are self-contained (i.e. support zip extraction on windows, then fix the commands, then fix WASM paths etc.). this is the only way Zed works for me so I want to find a way to get this merged somehow.

**Comment by mikayla-maki** [comment]
Putting up the commits in a series of shorter PRs for us to review and comment on, with a wider plan of attack as context (e.g. the tracking issue I mentioned), would help us review and merge this.

**Comment by LoganDark** [comment]
I suppose so, it might take me a while to find time for that level of organization, but I'm open to try.

**Pull request closed without merging**
