### PR TITLE
feat: add dracula theme

### PR DESCRIPTION
**Pull request by xhwhis**
Release Notes:

- Added dracula theme.

### CODE REVIEW

**Comment by maxdeviant** [comment]
Thank you for the contribution @xhwhis!

We're not accepting theme contributions into Zed at the moment, but we are working on making the theme system more extensible (a first version is in-progress in #6791).

Would be happy to work with you to get the work you've done with Dracula ported over.

**Comment by xhwhis** [comment]
Alright, I hope to enjoy the Dracula theme soon. All of my IDE themes are Dracula, and I believe many others also like this theme. @maxdeviant

**Comment by maxdeviant** [comment]
Closing in favor of theme extensibility in userland.

**Comment by maxdeviant** [comment]
@xhwhis I converted the Dracula themes you made to the new JSON format: https://gist.github.com/maxdeviant/eeacdce91fb8af851f8d579c70c1abc8

(No font weights or styles yet, as those aren't supported in the theme overrides just yet).

Once we release a new version of Zed that has https://github.com/zed-industries/zed/pull/6791 included, you'll be able to apply those themes in your `settings.json` to use them:

```jsonc
{
  "experimental.theme_overrides": {
    "border": "#bf9eeeff",
    "border.variant": "#bf9eeeff",
    "border.focused": "#7b7f8bff",
    "border.selected": "#bf9eeeff",
    "border.transparent": "#bf9eeeff",
    "border.disabled": "#bf9eeeff",
    "elevated_surface.background": "#343746ff",
    "surface.background": "#282a36ff",
    "background": "#282a36ff",
    "element.background": "#44475aff",
    "element.hover": "#44475a75",
    "element.selected": "#44475aff",
    "drop_target.background": "#44475aff",
    "ghost_element.hover": "#44475a75",
    "ghost_element.selected": "#44475aff",
    "text": "#f6f6f4ff",
    // ...
  }
}
```

**Comment by xhwhis** [comment]
LGTM! I will try it.

**Pull request closed without merging**
