### PR TITLE
Linux: Disable PureScript grammar to avoid linking error

### PR DESCRIPTION
**Pull request by h3mosphere**
Release Notes:

- N/A

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
We only want to disable it on Linux.

AFAIK this isn't a problem on macOS, so we don't want to disable it there.

**Comment by maxdeviant** [comment]
@h3mosphere Could you try changing the `tree-sitter-purescript` dependency in Zed from:

```
tree-sitter-purescript = { git = "https://github.com/ivanmoreau/tree-sitter-purescript", rev = "a37140f0c7034977b90faa73c94fcb8a5e45ed08" }
```

to this:

```
tree-sitter-purescript = { git = "https://github.com/deviant-forks/tree-sitter-purescript", rev = "ad3a8ebbf8d29039374050637c7e2c3995626baa" }
```

Does that fix the linking error when the PureScript grammar is not commented-out?

**Comment by h3mosphere** [comment]
woops

**Comment by h3mosphere** [comment]
Barring me making a mistake, It didnt work alas:

```
diff --git a/Cargo.lock b/Cargo.lock
index 9da269ce5..530d6054a 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -9237,7 +9237,7 @@ dependencies = [
 [[package]]
 name = "tree-sitter-purescript"
 version = "1.0.0"
-source = "git+https://github.com/ivanmoreau/tree-sitter-purescript?rev=a37140f0c7034977b90faa73c94fcb8a5e45ed08#a37140f0c7034977b90faa73c94fcb8a5e45ed08"
+source = "git+https://github.com/deviant-forks/tree-sitter-purescript?rev=ad3a8ebbf8d29039374050637c7e2c3995626baa#ad3a8ebbf8d29039374050637c7e2c3995626baa"
 dependencies = [
  "cc",
  "tree-sitter",
diff --git a/Cargo.toml b/Cargo.toml
index 2746b5d87..79e95006b 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -251,7 +251,8 @@ tree-sitter-nu = { git = "https://github.com/nushell/tree-sitter-nu", rev = "26b
 tree-sitter-ocaml = { git = "https://github.com/tree-sitter/tree-sitter-ocaml", rev = "4abfdc1c7af2c6c77a370aee974627be1c285b3b" }
 tree-sitter-php = "0.21.1"
 tree-sitter-proto = { git = "https://github.com/rewinfrey/tree-sitter-proto", rev = "36d54f288aee112f13a67b550ad32634d0c2cb52" }
-tree-sitter-purescript = { git = "https://github.com/ivanmoreau/tree-sitter-purescript", rev = "a37140f0c7034977b90faa73c94fcb8a5e45ed08" }
+# tree-sitter-purescript = { git = "https://github.com/ivanmoreau/tree-sitter-purescript", rev = "a37140f0c7034977b90faa73c94fcb8a5e45ed08" }
+tree-sitter-purescript = { git = "https://github.com/deviant-forks/tree-sitter-purescript", rev = "ad3a8ebbf8d29039374050637c7e2c3995626baa" }
 tree-sitter-python = "0.20.2"
 tree-sitter-racket = { git = "https://github.com/zed-industries/tree-sitter-racket", rev = "eb010cf2c674c6fd9a6316a84e28ef90190fe51a" }
 tree-sitter-ruby = "0.20.0"
diff --git a/crates/zed/src/languages.rs b/crates/zed/src/languages.rs
index 43e92fb0a..01a9e2c4e 100644
--- a/crates/zed/src/languages.rs
+++ b/crates/zed/src/languages.rs
@@ -266,7 +266,7 @@ pub fn init(
 
     // Produces a link error on linux due to duplicated `state_new` symbol
     // todo!(linux): Restore purescript
-    #[cfg(not(target_os = "linux"))]
+    // #[cfg(not(target_os = "linux"))]
     language(
         "purescript",
         vec![Arc::new(purescript::PurescriptLspAdapter::new(
```


```

inux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-321b82c30dffdf5f.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3dd8a6810a0bdfef.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-eb39a61c0c879984.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-aa769569f91c3548.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-510a192a50a983ed.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0577018320f99037.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-193cf992125ccd4c.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-8e138eaf26ebb4a8.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lasound" "-lfontconfig" "-lfreetype" "-ldl" "-lfreetype" "-lxcb" "-ldl" "-lssl" "-lcrypto" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/Zed-529538631754ab2e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/libtree_sitter_haskell-8da48a83a0b5f337.rlib(scanner.o): in function `state_new':
          /home/hemosphere/.cargo/git/checkouts/tree-sitter-haskell-74c278e7a2ef8d7d/cf98de2/src/scanner.c:218: multiple definition of `state_new'; /home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/libtree_sitter_purescript-c5ade00a1193717a.rlib(scanner.o):/home/hemosphere/.cargo/git/checkouts/tree-sitter-purescript-eded29d2e8e62f6a/ad3a8eb/src/scanner.c:218: first defined here
          collect2: error: ld returned 1 exit status


```

**Comment by h3mosphere** [comment]
Ok, _that_ should be good

**Review by maxdeviant — APPROVED** [review]

**Comment by maxdeviant** [comment]
> Barring me making a mistake, It didnt work alas:
> 
> ```
> diff --git a/Cargo.lock b/Cargo.lock
> index 9da269ce5..530d6054a 100644
> --- a/Cargo.lock
> +++ b/Cargo.lock
> @@ -9237,7 +9237,7 @@ dependencies = [
>  [[package]]
>  name = "tree-sitter-purescript"
>  version = "1.0.0"
> -source = "git+https://github.com/ivanmoreau/tree-sitter-purescript?rev=a37140f0c7034977b90faa73c94fcb8a5e45ed08#a37140f0c7034977b90faa73c94fcb8a5e45ed08"
> +source = "git+https://github.com/deviant-forks/tree-sitter-purescript?rev=ad3a8ebbf8d29039374050637c7e2c3995626baa#ad3a8ebbf8d29039374050637c7e2c3995626baa"
>  dependencies = [
>   "cc",
>   "tree-sitter",
> diff --git a/Cargo.toml b/Cargo.toml
> index 2746b5d87..79e95006b 100644
> --- a/Cargo.toml
> +++ b/Cargo.toml
> @@ -251,7 +251,8 @@ tree-sitter-nu = { git = "https://github.com/nushell/tree-sitter-nu", rev = "26b
>  tree-sitter-ocaml = { git = "https://github.com/tree-sitter/tree-sitter-ocaml", rev = "4abfdc1c7af2c6c77a370aee974627be1c285b3b" }
>  tree-sitter-php = "0.21.1"
>  tree-sitter-proto = { git = "https://github.com/rewinfrey/tree-sitter-proto", rev = "36d54f288aee112f13a67b550ad32634d0c2cb52" }
> -tree-sitter-purescript = { git = "https://github.com/ivanmoreau/tree-sitter-purescript", rev = "a37140f0c7034977b90faa73c94fcb8a5e45ed08" }
> +# tree-sitter-purescript = { git = "https://github.com/ivanmoreau/tree-sitter-purescript", rev = "a37140f0c7034977b90faa73c94fcb8a5e45ed08" }
> +tree-sitter-purescript = { git = "https://github.com/deviant-forks/tree-sitter-purescript", rev = "ad3a8ebbf8d29039374050637c7e2c3995626baa" }
>  tree-sitter-python = "0.20.2"
>  tree-sitter-racket = { git = "https://github.com/zed-industries/tree-sitter-racket", rev = "eb010cf2c674c6fd9a6316a84e28ef90190fe51a" }
>  tree-sitter-ruby = "0.20.0"
> diff --git a/crates/zed/src/languages.rs b/crates/zed/src/languages.rs
> index 43e92fb0a..01a9e2c4e 100644
> --- a/crates/zed/src/languages.rs
> +++ b/crates/zed/src/languages.rs
> @@ -266,7 +266,7 @@ pub fn init(
>  
>      // Produces a link error on linux due to duplicated `state_new` symbol
>      // todo!(linux): Restore purescript
> -    #[cfg(not(target_os = "linux"))]
> +    // #[cfg(not(target_os = "linux"))]
>      language(
>          "purescript",
>          vec![Arc::new(purescript::PurescriptLspAdapter::new(
> ```
> 
> ```
> 
> inux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-321b82c30dffdf5f.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3dd8a6810a0bdfef.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-eb39a61c0c879984.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-aa769569f91c3548.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-510a192a50a983ed.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0577018320f99037.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-193cf992125ccd4c.rlib" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-8e138eaf26ebb4a8.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lstdc++" "-lasound" "-lfontconfig" "-lfreetype" "-ldl" "-lfreetype" "-lxcb" "-ldl" "-lssl" "-lcrypto" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/hemosphere/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/Zed-529538631754ab2e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
>   = note: /usr/bin/ld: /home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/libtree_sitter_haskell-8da48a83a0b5f337.rlib(scanner.o): in function `state_new':
>           /home/hemosphere/.cargo/git/checkouts/tree-sitter-haskell-74c278e7a2ef8d7d/cf98de2/src/scanner.c:218: multiple definition of `state_new'; /home/hemosphere/repos/ides/zed/hemosphere/target/debug/deps/libtree_sitter_purescript-c5ade00a1193717a.rlib(scanner.o):/home/hemosphere/.cargo/git/checkouts/tree-sitter-purescript-eded29d2e8e62f6a/ad3a8eb/src/scanner.c:218: first defined here
>           collect2: error: ld returned 1 exit status
> ```

Darn. Although the error message does provide some additional clues.

**Pull request merged**
