### PR TITLE
linux: Get the color scheme through xdg-desktop-portal

### PR DESCRIPTION
**Pull request by citorva**
The method has been tested on:
- Gnome 46 (Working)
- Gnome 40 (Not supported)

Tasks

- [x] Implements a draft which get and provides the user theme to components which needs it
- [x] Implements a way to call the callback function when the theme is updated
- [X] Cleans the code

Release notes:
- N/A

### CODE REVIEW

**Comment by citorva** [comment]
I have fix my email address

**Comment by citorva** [comment]
I have fixed my email configuration @cla-bot check

**Comment by citorva** [comment]
Theme update is now supported by the application:
example-auto-theme

**Comment by citorva** [comment]
Supporting Gnome < 42 requires the use of alternate way such as listening the gtk theme through GSettings

**Comment by mikayla-maki** [comment]
This looks great! I'm a bit nervous about the blocking call on startup to get the right variables, as we don't want to delay initialization time anymore than absolutely necessary. That said, it might be fine! So let's try it and see how it feels :)

**Comment by citorva** [comment]
> This looks great! I'm a bit nervous about the blocking call on startup to get the right variables, as we don't want to delay initialization time anymore than absolutely necessary. That said, it might be fine! So let's try it and see how it feels :)

I have worked without the blocking initialization at the beginning, however, when using calloop, the theme given at the initialization was not the system's theme but the default value in the code. I think that the issue is due to the fact that the first event occurs before the end of the UI initialization and is drop. As I didn't want to change the behavior of this feature, I have used the blocking method to get the initial color scheme.

**Pull request merged**
