### PR TITLE
Windows: prevent blocking by GetMessage

### PR DESCRIPTION
**Pull request by kazatsuyu**
It is possible that `PeekMessage` or `GetMessage` may not return a message even if a message exists in the message queue. In that case, the message is processed inside the call to these functions, with `PeekMessage` returning `FALSE` and `GetMessage` blocking the thread until another message arrives.

If a window was visible, this was unlikely to be a problem because other messages would occur soon, but after all windows were closed, this would block the thread and the application would not terminate.

Therefore, I changed it to use `PeekMessage` instead of `GetMessage`.

Release Notes:

- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
That's interesting. I saw `winit` uses `PeekMessage` too, but dont know why, is there any doc or webpage that I can go into this deeper? Thx

**Comment by kazatsuyu** [comment]
> That's interesting. I saw `winit` uses `PeekMessage` too, but dont know why, is there any doc or webpage that I can go into this deeper? Thx

You will find this explanation in [`GetQueueSttatus`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getqueuestatus) 
> The presence of a QS_ flag in the return value does not guarantee that a subsequent call to the [GetMessage](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getmessage) or [PeekMessage](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-peekmessagea) function will return a message. GetMessage and PeekMessage perform some internal filtering that may cause the message to be processed internally.

**Comment by zaucy** [comment]
I did how the loop works here: https://github.com/zed-industries/zed/pull/8921 take a look. Went back to peek message for other reasons.

Regardless I was quite certain that Get message would not block with the multi object wait. Surprised by that.

**Comment by kazatsuyu** [comment]
So this PR may be closable. I'll check #8921

**Comment by mikayla-maki** [comment]
Already done in #8921

**Pull request closed without merging**
