### PR TITLE
Add autosave with delay

### LINKED ISSUE #9787: After python autosave, cursor moves to beginning of line
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When autosave is enabled, saving a Python file with an empty method definition results in the cursor moving from an indented position to the beginning of the line, resulting in a frustrating dev experience.

Autosave setting:

```json
  "autosave": {
    "after_delay": {
      "milliseconds": 1000
    }
  }
```

To reproduce:
1. Create a new python file
2. Start to populate with some Python class
```python
class TestClass:
    def some_method(self):
        
```
3. Wait for autosave
4. Observe the cursor moving to the beginning of the line

Note that this happens even if the method definition is in the middle of a file. It appears to be related to the `remove_trailing_whitespace_on_save` setting - if I disable that, then the cursor remains in the same/correct position.

Similar to #7570 and #392 

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.3.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by Dageus**
Implemented autosave functionality with a delay, which now refrains from formatting the code upon triggering unless the user manually saves it. Additionally, enhanced documentation for the `format_on_save` setting has been added. This resolves the issue where autosave with delay would inadvertently format the code, disrupting the user experience, as reported in the corresponding issue.

Release Notes:

- Fixed a bug where autosave after_delay would auto-format the buffer ([#9787](https://github.com/zed-industries/zed/issues/9787)).

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@Dageus Thanks for this!

I think we need to only ignore the `format_on_save` parameter if this was triggered by auto-save, so we need to put the if statement in `pub fn autosave_item(` instead.

**Comment by Dageus** [comment]
Thank you! I was unsure whether I was checking the auto save parameter in the correct place, so I will fix this asap and correct the PR.

**Comment by Dageus** [comment]
Thank you! I was unsure whether I was checking the auto save parameter in the correct place, so I will fix this asap and correct the PR.

**Comment by Linyuqiz** [comment]
Is this going to be merged soon?

**Pull request merged**
