### PR TITLE
JavaScript: Add runnable tests

### PR DESCRIPTION
**Pull request by RemcoSmitsDev**
https://github.com/zed-industries/zed/assets/62463826/2912c940-bd00-483d-9ce7-df1a2539560a

Release Notes:

- Added runnable tests for JavaScript & Typescript files.
- Added task to run selected javascript code.

### CODE REVIEW

**Comment by sigmaSd** [comment]
What if the user uses another framework instead of jest
What about another runtime like deno 

Does the task/runnable in zed take this in consideration currently?

**Comment by RemcoSmitsDev** [comment]
@sigmaSd We could also add support for Deno tests, but I never used Deno. We could pair on it to make it work if you want to?

**Comment by coratgerl** [comment]
Thanks for this PR, it will be very usefull !

There is also Bun tests (bun:test) and Node tests (node:test). This will be supported in the future ?

**Comment by sigmaSd** [comment]
Thanks but I can't currently hack on zed , but here is what I tried https://github.com/zed-industries/zed/discussions/11586

What I'm really wondering is can this in the future be offloaded to extensions as in I can author a deno extension that can provide deno tests without clashing with the default runnable that this pr adds

**Comment by sigmaSd** [comment]
Otherwise we can put all the combinationd possible inside this default runnable

**Comment by RemcoSmitsDev** [comment]
Ahh Deno has their own lsp and stuff, so I think the Deno extension just should contain these runnables instead of adding support for them inside the JavaScript/Typescript extensions.

**Comment by RemcoSmitsDev** [comment]
Renamed `jest-test` to `js-test` and `ts-test` so people can define tasks for them independently. And if you want to use one task for both tags, you can just update your task to contain both of them.
```json
{
   "tags":  ["js-test", "ts-test"],
   ...
}
 ```

**Comment by osiewicz** [comment]
@RemcoSmitsDev something that came up in other PRs/issues (https://github.com/zed-industries/zed/pull/12003#issuecomment-2127235201 https://github.com/zed-industries/zed/issues/12215) is that we might want to allow users themselves to fill in some environmental variables used by tasks. Imagine that user could have the following in their settings (in pseudocode):
```
tasks:
  javascript:
    TEST_RUNNER: jest
```
which you could then inspect when creating a task context on extension side.

**Review by osiewicz — APPROVED** [review]
LGTM, let's give it some time on nightly and merge it after todays Preview is out.

**Comment by quintstoffers** [comment]
It appears this PR did not enable runnable tests for "tsx" files. Is that intentionally left out of this scope, or could I create a new issue for this?

**Comment by RemcoSmitsDev** [comment]
Yeah didn't left it out on purpose, I thought this was included inside the Typescript language. So totally misted the JSX language.

**Comment by quintstoffers** [comment]
Thanks @RemcoSmitsDev! I created https://github.com/zed-industries/zed/issues/12884 to track implementation for TSX.

**Comment by exalted** [comment]
FYI; this won't detect an outline item if the first argument (i.e., the "name") for `describe`, `test`, or `it` is a template literal (a.k.a. template string) delimited with backtick (<code>`</code>) characters.

**Pull request merged**
