### PR TITLE
Delete /workflow

### PR DESCRIPTION
**Pull request by rtfeldman**
This a separate PR from https://github.com/zed-industries/zed/pull/19705 so we can revert it more easily if we want it back later.

Release Notes:

- Added "Suggest Edit" button to the assistant panel if `"enable_experimental_live_diffs": true` is set in the `"assistant"` section of `settings.json`. This button takes the place of the previous `/workflow` command, but it is experimental and may change!

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
> No release notes because `/workflow` is not currently on stable.

To note, seems that this had been leaked to people too, after all, as threads like https://github.com/zed-industries/zed/discussions/19841 appear.
So maybe it is good to explain in the release notes what it gets replaced with.

**Comment by SomeoneToIgnore** [comment]
Also https://github.com/zed-industries/zed/issues/19671

**Comment by Supremesource** [comment]
image
what is this ? no context added, and already token count consumed. is the workflow now "baked in" the model context window so user can not adjust it ? that would go completely against the vibe of the assistant pannel

**Comment by rtfeldman** [comment]
@Supremesource https://github.com/zed-industries/zed/pull/20180 addresses this!

**Comment by EDLLT** [comment]
I have read this, but I still don't understand. What's the reasoning behind removing ``/workflow``?

> This a separate PR from #19705 so we can revert it more easily if we want it back later.
> 
> Release Notes:
> 
> * Added "Suggest Edit" button to the assistant panel if `"enable_experimental_live_diffs": true` is set in the `"assistant"` section of `settings.json`. This button takes the place of the previous `/workflow` command, but it is experimental and may change!

**Comment by monotykamary** [comment]
@rtfeldman is there a way that whenever "Suggest Edits" are used, the prompt used to call it appears on the assistant editor? This way, it's a bit more explicit and easier to calculate tokens.

**Pull request merged**
