### PR TITLE
Add minimum column option to git inline blame

### PR DESCRIPTION
**Pull request by hshreekar**
Release Notes:

- Added a setting to determine the minimum column where the inline blame information is shown. Example: `{{"git": {"inline_blame": {"min_column": 80}}}` ([#10555](https://github.com/zed-industries/zed/issues/10555)).

Demo Video:

https://github.com/zed-industries/zed/assets/1185253/61343dbe-9002-4bd1-b0d4-403f8da79050

### CODE REVIEW

**Comment by hshreekar** [comment]
``` 
error: failed to run custom build command for live_kit_server v0.1.0 (~/zed-contribution/zed/crates/live_kit_server)

Caused by:
  process didn't exit successfully: ~/zed/target/debug/build/live_kit_server-827ec39843723782/build-script-build (exit status: 101)
  --- stderr
  thread 'main' panicked at crates/live_kit_server/build.rs:4:10:
  called Result::unwrap() on an `Err` value: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/livekit_room.proto: No such file or directory\n" }
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```
i get this when i run cargo test --workspace, i havent set up postgres or any other feature for collab. What is this error related to ?

**Comment by mrnugget** [comment]
I'll hop on the branch and try to fix it.

**Comment by hshreekar** [comment]
So , i reran the test, only these failed (i havent set up postgres so should have failed)
```
    auth::test::test_verify_access_token
    db::tests::buffer_tests::test_channel_buffers_last_operations_postgres
    db::tests::buffer_tests::test_channel_buffers_postgres
    db::tests::channel_tests::test_channel_invites_postgres
    db::tests::channel_tests::test_channel_renames_postgres
    db::tests::channel_tests::test_channels_moving_postgres
    db::tests::channel_tests::test_channels_postgres
    db::tests::channel_tests::test_db_channel_moving_bugs_postgres
    db::tests::channel_tests::test_guest_access_postgres
    db::tests::channel_tests::test_joining_channels_postgres
    db::tests::channel_tests::test_user_is_channel_participant_postgres
    db::tests::contributor_tests::test_contributors_postgres
    db::tests::db_tests::test_add_contacts_postgres
    db::tests::db_tests::test_create_access_tokens_postgres
    db::tests::db_tests::test_fuzzy_search_users
    db::tests::db_tests::test_get_or_create_user_by_github_account_postgres
    db::tests::db_tests::test_get_users_by_ids_postgres
    db::tests::db_tests::test_metrics_id_postgres
    db::tests::db_tests::test_project_count_postgres
    db::tests::embedding_tests::test_get_embeddings_postgres
    db::tests::embedding_tests::test_purge_old_embeddings
    db::tests::extension_tests::test_extensions_by_id_postgres
    db::tests::extension_tests::test_extensions_postgres
    db::tests::feature_flag_tests::test_get_user_flags_postgres
    db::tests::message_tests::test_channel_message_mentions_postgres
    db::tests::message_tests::test_channel_message_nonces_postgres
    db::tests::message_tests::test_channel_message_retrieval_postgres
    db::tests::message_tests::test_unseen_channel_messages_postgres
    ```
    Everything else seems fine . Had forgotten to update git submodule before (☠️). 
    Thank you for helping me out and do let me know if there are changes to be made in this.

**Comment by mrnugget** [comment]
I changed the release notes to conform to the format, added a demo video, and fixed the calculation. It actually didn't display the information at the right column. Turns out that we need to use `self.column_pixels` in order to get the exact offset for a given column.

**Comment by hshreekar** [comment]
Ahh ok, Sorry for the oversight. Thanks again for helping me out. I will delete the branch now

**Pull request merged**
