### PR TITLE
Add a way to use splits when opening in file finder

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Follow-up of https://github.com/zed-industries/zed/pull/18187

image

image

Release Notes:

- Added a way to use splits when opening in file finder

### CODE REVIEW

**Review by danilo-leal — COMMENTED** [review]
Can we trigger the ellipsis icon button open with a keybinding, too? Raycast's a great benchmark for this:

Screenshot 2024-11-12 at 19 08 12

**Comment by SomeoneToIgnore** [comment]
Thank you, adjusted it according to the feedback:

not_open
single_open
multi_open


I have tried experimenting with the offset to make the menu more detached from the button, similar to Raycast, but not sure I liked it.

Will merge this with the default offset for now.

**Comment by marcospb19-cw** [comment]
@SomeoneToIgnore 
in version 0.162.5 the non-vim keybindings for splitting don't work for me
is it fixed in the beta or should this be an issue? 🤔

**Comment by SomeoneToIgnore** [comment]
Without extra details provided (what would non-vim keybindings even mean, given that those are vim-like only after https://github.com/zed-industries/zed/pull/20680?), I have no clue what may cause this, as there'd been quite a release storm recently, changing the way bindings work.

Seems to work for me:

https://github.com/user-attachments/assets/b1b3760e-80a2-4817-89bc-78dee83b1ea1

**Comment by marcospb19-cw** [comment]
@SomeoneToIgnore I'm sorry for the confusion.

I re-tested it and created a proper issue with steps to reproduce.

**Comment by notpeter** [comment]
- Link: https://github.com/zed-industries/zed/issues/21077

**Pull request merged**
