### PR TITLE
Initial Notebook UI structure

### PR DESCRIPTION
**Pull request by rgbkrk**
This is the start of a notebook UI for Zed. 

`🔔 Note: This won't be useable yet when it is merged! Read below. 🔔`

This is going to be behind a feature flag so that we can merge this initial PR and then make follow up PRs. Release notes will be produced in a future PR.

Minimum checklist for merging this:

* [x] All functionality behind the `notebooks` feature flag (with env var opt out)
* [x] Open notebook files in the workspace
* [x] Remove the "Open Notebook" button from title bar
* [x] Incorporate text style refinements for cell editors
* [x] Rely on `nbformat` crate for parsing the notebook into our in-memory format
* [x] Move notebook to a `gpui::List`
* [x] Hook up output rendering

Release Notes:

- N/A

### CODE REVIEW

**Comment by rgbkrk** [comment]
https://github.com/user-attachments/assets/d74de1a8-db29-4b2c-b7f1-94035f01309e

**Comment by cs2018ncsa** [comment]
this looks phenomenal! can't wait for this to be available in stable release.

**Comment by gabrielalexandrelopes** [comment]
How can we test this? I tried the flag but nothing changes
```
"features": {
    "notebooks": true
}
```

**Comment by pantheraleo-7** [comment]
Set the env var `LOCAL_NOTEBOOK_DEV` to `1`. And then open a workspace (directory).

**Comment by gabrielalexandrelopes** [comment]
Thanks so much! Testing!!!

> Set the env var `LOCAL_NOTEBOOK_DEV` to `1`. And then open a workspace (directory).

**Comment by FelixHT** [comment]
This looks great! Is there already a way to create a new .ipynb file? Opening an empty file seems to throw a JSON error.

**Comment by duytuej1210** [comment]
> Set the env var `LOCAL_NOTEBOOK_DEV` to `1`. And then open a workspace (directory).

I am new with it. Could someone show me how to enable this feature step by step. I work with ipynb files almost everyday and still use VS to work with

**Comment by baiguoname** [comment]
Thanks for sharing. Could you please add an option to remove the rectangular button in the front of each cell? It is quit annoying at times.

**Comment by FelixHT** [comment]
@duytuej1210 
You can set the environment variable before starting zed via cli
https://zed.dev/docs/environment

**Comment by lhutyra** [comment]
I was able to open Notebook, however nothing reacts - I cannot execute any cells. I tried on windows, linux and mac.... I guess - I should set something more

**Comment by pantheraleo-7** [comment]
This PR only added initial support for viewing notebooks. That's it. Might see further notebook support early next year [#5273 (comment)](https://github.com/zed-industries/zed/issues/5273#issuecomment-2486935753)

PS. It's not a GH etiquette to discuss in a PR AFAIK, especially a closed (merged) one.

**Comment by baiguoname** [comment]
The UI seems really nice and clean, but currentlly, it seems doesn't support code folding, `evcxr` image output. Looking forward to more seetings in the future!

**Comment by Obsidianage** [comment]
> Set the env var `LOCAL_NOTEBOOK_DEV` to `1`. And then open a workspace (directory).

where is that

**Comment by lhutyra** [comment]
> > Set the env var `LOCAL_NOTEBOOK_DEV` to `1`. And then open a workspace (directory).
> 
> where is that

You need to set enviornment variable on your windows or linux/mac,
Something like this on windows:
`setx LOCAL_NOTEBOOK_DEV 1`
Anyway you can only preview notebook - it's not executable at this point as far I know and saw

**Comment by gjmveloso** [comment]
I just tried to use this in conjunction with `mise` and `uv`, [following uv's instructions for VSCode](https://docs.astral.sh/uv/guides/integration/jupyter/#using-jupyter-from-vs-code) and it didn't worked. 

Apparently Zed currently does not support `ipykernel` coming from `uv` managed `venv`, is that right?

```
 bat mise.toml
───────┬────────────────────────────────────────────────────────────────────────────────
       │ File: mise.toml
───────┼────────────────────────────────────────────────────────────────────────────────
   1   │ [tools]
   2   │ python = "latest"
   3   │
   4   │ [env]
   5   │ LOCAL_NOTEBOOK_DEV = 1
```

```
 uv pip list
Package           Version
----------------- -----------
appnope           0.1.4
asttokens         3.0.0
comm              0.2.2
debugpy           1.8.12
decorator         5.1.1
executing         2.2.0
ipykernel         6.29.5
ipython           8.32.0
jedi              0.19.2
jupyter-client    8.6.3
jupyter-core      5.7.2
matplotlib-inline 0.1.7
nest-asyncio      1.6.0
packaging         24.2
parso             0.8.4
pexpect           4.9.0
platformdirs      4.3.6
prompt-toolkit    3.0.50
psutil            6.1.1
ptyprocess        0.7.0
pure-eval         0.2.3
pygments          2.19.1
python-dateutil   2.9.0.post0
pyzmq             26.2.1
six               1.17.0
stack-data        0.6.3
tornado           6.4.2
traitlets         5.14.3
wcwidth           0.2.13
```
`zed .` 
`repl: sessions`

Screenshot 2025-02-12 at 8 04 53 AM

**Comment by tcwalther** [comment]
Just came here to say that I really like the notebooks UI, and previewing notebooks is often enough for me because notebooks often come as part of documentation of other packages. Could be worth considering enabling this by default and making it clear that notebooks are read-only (may with a banner or sth?).

**Comment by rgbkrk** [comment]
> Just came here to say that I really like the notebooks UI, and previewing notebooks is often enough for me because notebooks often come as part of documentation of other packages. Could be worth considering enabling this by default and making it clear that notebooks are read-only (may with a banner or sth?).

That's a good suggestion, especially since a full working notebook has been back burnered. Would you be able to make a new issue for it?

**Pull request merged**
