### PR TITLE
Revert: "a" for "vim::AngleBrackets"

### LINKED ISSUE #20912: vim motions `dia` and `cia` no longer work as expected
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Updated Zed recently, so unsure when it broke, but vim motions `dia` `daa` `cia` `caa` perform differently than before. Language is typescript

For example

```typescript
function my_func(a: number, b: number): boolean { //place cursor anywhere on `b:number` and do motion: daa
    return false;
}

function my_generic_func<T>(a: T) {
    
}
```
Place cursor anywhere on `b:number` and do motion: `daa`

In previous versions, this would remove `, b: number` entirely

Currently, this removes `<T>` in the next function

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 14.7.0
Memory: 32 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by ConradIrwin**
The replacement "g" didn't seem to work for everyone.

Closes #20912
Updates #20104

Release Notes:

- vim: Restores `dia` to mean "delete in argument" instead of "delete within angle brackets". To keep this in your own keymap use:
    ```
    {
        "context": "vim_operator == a || vim_operator == i || vim_operator == cs",
        "use_layout_keys": true,
        "bindings": {
            "a": "vim::AngleBrackets"
        }
    }
    ```

### CODE REVIEW

**Comment by kylejreed** [comment]
Appreciate the quick PR, I will also mention that it looks like `b` is just parens, but I believe in other vim implementations it is just the nearest bracket `()` `[]` `{}` `<>`

**Comment by ConradIrwin** [comment]
@kylejreed do you have a link to back that up? As far as I'm aware, vim itself treats b as a synonym for (.

**Comment by kylejreed** [comment]
I think you are be right. Some of the Neovim pre-configured setups like LazyVim include a text-objects plugin that extends `b` to all brackets. It also allows `q` for nearest \` ' or ".  Nice QoL things, but not available in the base vim/neovim

**Comment by xzbdmw** [comment]
>  Some of the Neovim pre-configured setups like LazyVim include a text-objects plugin that extends b to all brackets. It also allows q for nearest ` ' or "

It's from https://github.com/echasnovski/mini.ai

**Pull request merged**
