### PR TITLE
windows: Fix renderer state sync during window minimize/restore

### PR DESCRIPTION
**Pull request by Cupnfish**
## Description
This PR fixes a Windows-specific issue where restoring the window from a minimized state would cause the application to crash with surface out of date errors. The root cause was improper handling of Windows `SIZE_MINIMIZED` messages and subsequent renderer state updates.

### What's Changed
- Improved handling of Windows `SIZE_MINIMIZED` window messages
- Ensured proper renderer state updates during Windows window state transitions
- Added correct handling of resize events during minimize/restore on Windows
- Restructured the Windows window state management code for better clarity

### Previous Behavior
On Windows platform, when minimizing the window, the application would crash upon restore with:
```
[WARN] GPU frame is out of date
[WARN] Acquire failed because the surface is out of date
```

### New Behavior
- Windows window can be minimized and restored without errors
- Renderer state remains properly synchronized with Windows window state
- No crashes or surface out of date errors on window restore

### Platform Specific
- This fix is specific to the Windows platform
- Issue and fix are related to Windows window message handling (`SIZE_MINIMIZED`)
- Other platforms are unaffected by this change

### Testing
- [x] Tested window minimize/restore multiple times on Windows
- [x] Verified no crashes on window restore on Windows
- [x] Checked renderer state consistency across state changes
- [x] Verified no regression on other platforms

### Related Issues
Closes #21703

Release Notes:

- Fixed window renderer crash on Windows when restoring from minimized state

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
In PR #21756, @mgsloan chose that approach to prevent the swapchain from being resized to (1,1) when the window is minimized. However, it seems to cause the issue of `Acquire failed because the surface is out of date`.

To be honest, I am more inclined towards the approach in PR #21703.

**Comment by Cupnfish** [comment]
I also referred to the method in https://github.com/zed-industries/zed/pull/21703, but the issue on my computer was not fixed in PR https://github.com/zed-industries/zed/pull/21756.

**Comment by vipexv** [comment]
I'll go ahead and test this a little bit later, as i was having the same exact issue, although it could vary on Window's versions maybe? since not everyone seems to be having this, for me i'm on 24H2

**Comment by SomeoneToIgnore** [comment]
Thank you, this fixes things on my Win11, but I would prefer to merge https://github.com/zed-industries/zed/pull/22414 instead, as it looks simpler and also fixes the issue.

**Pull request closed without merging**
