### PR TITLE
Fix keybinding issues for CJK and non-Latin input sources on macOS

### PR DESCRIPTION
**Pull request by haruleekim**
Related #15258

# Issues and Changes:

1. Previously, when using input sources like Korean or Russian, none of the keybindings in vim’s normal mode could be used. This was because the IME of these input sources returns Korean or Cyrillic characters as the value of the keystroke’s `key` field instead of Latin alphabets based on the physical layout. (these two input sources only return Latin alphabets in the QWERTY keyboard layout when combined with the command key.) To resolve this, the native macOS platform keycodes have been mapped to the corresponding Latin alphabet on the QWERTY keyboard layout, and this mapped value is now used in the keystroke's `key` field. The mapping table was sourced from the `winit` crate's code.

2. When replaying a keystroke that doesn't match any keybinding, previously the `ime_key` field’s string was sent to the input handler to be inserted. However, this behavior isn't suitable for input sources with IME composition like CJK. The correct behavior is to replay the composition command as instructed by the actual IME rather than simply inserting the string. To implement this, an `ime_inputs` field was added to the Keystroke struct, which contains the composition commands (conforming to the InputHandler trait) dictated by the IME. When replaying a keystroke, the commands contained in this field are executed as they are.

3. To accurately and correctly extract the IME’s composition commands, the existing method of buffering IME commands has been improved: AppKit's TextInputContext sometimes issues multiple text manipulation commands in response to a single event. Additionally, it may determine the next command to issue after checking the current composition state via methods like `selectedRange` or `markedRange` immediately after a command is dispatched. However, in the current implementation, the IME commands were buffered in such a way that only text change commands were buffered. If the TextInputContext called methods like `markedTextRange` or `selectedTextRange` of the TextInputClient protocol during this buffering process, it would return a result as if the TextInputClient ignored the TextInputContext’s commands (which is true), leading to many IME-related bugs. To resolve this, all methods of the TextInputClient protocol are now wrapped in a simple simulation when buffering IME commands, effectively deceiving the TextInputContext. This method seems to cover even the edge cases that occurred in the previous implementation.

4. Since the detailed information for replaying the keystroke is now stored in the `ime_inputs` field, the role of the `ime_key` field has been reduced to being used solely for matching keybindings. Therefore, instead of using commands from the IME, the `characters` method of the key event is used to set the value of the `ime_key` field. Although this implementation still has issues with Korean and Russian IMEs (the correct implementation would be to explicitly map all keycodes and shift key combinations to uppercase Latin alphabets or special characters, but this has been left unimplemented for now), it is expected to work well with keyboard layouts that use Latin alphabets.

5. Just before executing an action bound to a keybinding, if there is any marked (composed) text, it is unmarked to finalize it, and immediately after, the `discardMarkedText` method of TextInputContext is called to reset the internal state.

# Limitations

- All these implementations are currently configured to work only on macOS using the `#[cfg(target_os = "macos")]` macro. However, with some modifications and trait method implementations, it could likely work on other platforms as well.

- Some heuristics are used to handle CJK input methods appropriately. Nevertheless, with the Chinese IME, the candidate list keeps appearing, making vim’s insert mode multistroke keybindings inconvenient. To completely resolve this, it is necessary to pre-check whether the keystroke will match a keybinding before sending it to the event handling callback. Based on the result, the key event should be sent directly to TextInputContext without simulation, but this prevents creating the `ImeInput` required for replay, so the keycode and modifiers should be stored in the keystroke and then an NSEvent should be synthesized and sent to TextInputContext during replay. I attempted this implementation, but kept encountering panics due to violating `AppCell`’s borrow rule, so I gave up for now.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@huacnlee Thank you for taking a pass at this! Better keyboard support has been on my wishlist for a while.

I am sure we want to fix the edge cases you talk about in 2 and 3 - thank you for adding more “test cases” to the comment! 5. also seems sensible.

With 1. I think we can’t use the key scan directly, as for a Dvorak layout that means that “r” can be interpreted as “o”. I notice that on macOS most (all?) keyboard layouts revert to ASCII when command is held down, so could we use event.charactersWithModifiers(.command) instead of the key code?

I don’t fully follow your concern in 4. Do the issues with Korean and Russian IMEs persist even if we set `key: event.charactersWithModifiers(.command)` and `ime_key: event.characters`?.  I guess (for Russian), we miss some information, if you type option-ф you get `key: “a”, ime_key: “ƒ"` and we don’t know about it being `option-ф` so if you are doing custom bindings you have to choose either `option-a` or `ƒ` . That seems ok though, but I worry I’m missing something. (we also need to unwind the changes to apply/unapply_modifiers as I don't think we can sanely do these in our code).

For the issues with opening the menu in some IMEs there is definitely a conflict here. Mostly I think you’re right we should not invoke the IME if the keystroke is handled; but there is one known edge-case that requires this today. On a Brazilian layout to match the Vim object `"`(as in `di"` to delete everything in quotes). In that case the `"`is a dead key, and typing a quote requires two key-presses:  `" space` . Maybe we can solve that separately; or implement sometime like vim’s `langmap` instead. I think your heuristics are probably fine until then.

I’d be happy to pair with you on this if that’d be helpful! https://calendly.com/conradirwin/pairing

**Comment by ConradIrwin** [comment]
Also, it would be good to ship the same fixes to Linux too. Is it possible to do the IME simulation outside of the platform code? (we may have to change the InputHandler trait a little).

**Comment by huacnlee** [comment]
😂 You are mentioned wrong man.

**Comment by ConradIrwin** [comment]
Sorry!

**Comment by ConradIrwin** [comment]
I think the assumptions are not what most people would expect. When I need to figure out what we should do I usually look at neovim and VS Code as the apps most people coming to Zed will be familiar with.

They both agree that:
1. In Dvorak the keyboard shortcuts match the typed keys
2. In Brazilian you need to `d i " space`
3. In Czech end of line is `option-4`

So I think that means we should not do the key code stuff, nor send keystrokes before IME.  The things I agree we should do are:
1. Improve IME simulation on macOS
2. Move IME simulation out of macOS if possible

That still leaves us with the original problems you were trying to solve though. To restate them:
1. (In non vim mode) In Russian (and other non-Latin layouts) you cannot type keyboard shortcuts that don’t require command
2. (In non vim mode) In Czech there’s no way to type `cmd-{, cmd-}`
3. (In vim mode) In Russian (and other non-Latin layouts) you cannot type vim normal commands
4. (In vim mode) In Japanese (and other menu-based IME) you cannot type vim normal commands.

I’m not sure how to solve all of these, but possibly:
1. Use `key: .charactersWithModifiers(.command), ime_key: <output of ime>`
2. We should ignore (though it’s unfortunate that the keyboard doesn’t seem to have a way to type this combination, we have similar issues with other shortcuts on other specific keyboards already)
3. I think we have three options:
   1. Use `key: .charactersWithModifiers(.command), ime_key: <output of ime>` 
   2. Automatically change keyboard layout on mode switch: `{"vim": {"normal_layout": "US", "insert_layout": "Russian"}}`. 
   3. We could implement vim’s `langmap`.
4. I think we have two options:
   1. Automatically change keyboard layout on mode switch: `{"vim": {"normal_layout": "US", "insert_layout": "Japanese"}}`
   2. Use your heuristics to detect this kind of IME, and have vim mode set/unset a flag that we don’t want to use normal mode so we dispatch the keystrokes immediately

With automatically changing the keyboard layout, I'm not sure if we should ask users to specify the insert mode one, or just restore it to whatever it was before we switched to normal mode.

What keyboard layouts do you use on a daily basis, and do any of these feel like they might work, or do we need more ideas?

**Comment by ConradIrwin** [comment]
Doing a little more digging here. If we do want to change the keyboard layout (though I'm not yet sure we do), it seems like we can:
```
                let _: id = msg_send![input_context, setSelectedKeyboardInputSource: NSString::alloc(nil).init_str("com.apple.keylayout.US")];
```

It also seems like macOS has two Dvorak layouts, one with command mapped to qwerty and one without - maybe that was part of the cause of our different assumptions, and I think makes blindly setting the key to the .command modifiers not super ideal.

It also seems like we might be able to detect the difference in Japanese etc. vs Brazilian by looking at [kTISPropertyInputSourceType](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/TextInputSources.h#L192C26-L192C53), but I haven't figured out how to do that yet.

**Comment by ConradIrwin** [comment]
That all makes sense to me. Thanks for taking the time to talk this through.

If you create a PR with your work in progress, you can "allow maintainers to edit", and I can try and make similar changes for the Linux side.

We should probably do the vim-mode keyboard switcher setting in a separate PR.

**Comment by ConradIrwin** [comment]
Also, re cmd-shift-[, you are correct that should be spelled cmd-{.

**Comment by JunkuiZhang** [comment]
For non-English layouts in Vim and other programming tools, I think the common solution is to install an English layout, as mentioned [here](https://stackoverflow.com/questions/22416877/can-i-set-vim-up-to-detect-non-english-input) and [here](https://www.reddit.com/r/vim/comments/ftlnhp/vim_with_a_foreign_keyboard/). As someone who uses Chinese input, the first step I take when setting up a computer is to install an English layout. In fact, I use the English layout 99% of the time, switching to the IME only when inserting text.

Or is this PR addressing a different issue?

**Comment by JunkuiZhang** [comment]
> Currently, no keyboard layout can match the key binding written as `cmd-shift-]`

> Also, re cmd-shift-[, you are correct that should be spelled cmd-{.

I think `cmd-shift-[` is the correct notation when talking about key binding when using standard English kbd layout. The `cmd-shift-[` refers to the physical keypress, say `cmd-shift-p` is a physical keypress, `cmd-P` is not, as there is no `P` key on keyboard. `cmd-shift-[` and  `cmd-{` is something similar.

The video below shows `cmd-shift-[` is actually working on English layout:


https://github.com/user-attachments/assets/65ffdc58-c1d1-4779-a542-dd74cc39da8a

**Comment by JunkuiZhang** [comment]
> The discussion above is about providing a feature that automatically changes the keyboard layout in modes other than insert mode. (This is a different direction from the original PR code I wrote, but on reflection, it seems more practical.)

Could you please clarify what is meant by “automatically changes the keyboard layout”? What happens if the user has only one layout? For example, on Windows, there will be only a Chinese keyboard layout comes out of box.

> In fact, this default behavior is written as `cmd-}`

I understand that macOS handles this differently, this is some long left issue on macOS implemtation, I dont know if it's intentional or not. But as I mentioned earlier, `cmd-shift-[` is somehow the "correct" notation. Additionally, in the Windows implementation, `ctrl-shift-[` works, while `ctrl-{` does not, since the `{` key is not a physical key on the keyboard. While, in theory, `ctrl-shift-[` and `ctrl-{` are identical.

> ```json
> [
>     {
>         "bindings": {
>             "cmd-{": ["workspace::SendKeystrokes", "left"],
>             "cmd-shift-]": ["workspace::SendKeystrokes", "right"],
>         }
>     }
> ]
> ```
> 
> Then, try pressing `cmd-shift-[` and `cmd-shift-]` in any empty editor window. The former will match the user keymap and output the text "left", while the latter will not match and will execute zed's default behavior of `pane::ActivateNextItem`. 

I think the issue here is that one can not set and treat `cmd-shift-[` and `cmd-shift-]` as key bindings on macOS, there is no such issue on windows:


https://github.com/user-attachments/assets/f154c2b2-33db-41b2-8f8d-21bd43b44ad3


I noticed that you’re in Korea, and it’s quite late here in China, and I believe so Korea is. Let’s continue the discussion tomorrow.

**Comment by JunkuiZhang** [comment]
> @JunkuiZhang Sorry for the late reply! The concept of "automatically changing the keyboard layout" is as follows: https://github.com/keaising/im-select.nvim. Each keyboard layout has a unique identifier specific to the operating system (for example, the identifier for the English layout on macOS is `"com.apple.inputmethod.ABC"`). If the user explicitly specifies this identifier in the configuration file, the layout will automatically switch whenever Vim exits insert mode (or more generally, whenever the `input_handler` assigned to `WindowState` is taken). When switching back to insert mode, it will return to the previous layout. If the user has not set a keyboard layout, this feature should not be activated. Additionally, if the specified layout identifier is incorrect or not installed on the operating system, an error message should be displayed.

That's why I believe this functionality should be provided by a plugin or extension rather than being built into GPUI. I believe this would help avoid more bugs in GPUI while also reducing its complexity, as you can look into the implementation on macOS, a lot of workarounds have already been done to accommodate different keyboard layouts. Of course, this is just my opinion, and ultimately, it’s up to the Zed team to decide.


> As I mentioned earlier, I believe the core of the issue lies in the confusion caused by the varying meanings of the _**key**_ in different contexts within the GPUI code. You will understand what I mean by looking at the [winit's keyboard module](https://docs.rs/winit/latest/winit/keyboard/index.html). I think eventually we need to change the type of the `Keystroke::key` field in GPUI to something similar to `winit::keyboard::Key`. And the reason I split the Keystroke structure in my code into `Keystroke` and `VirtualKeystroke` based on the context in which they're used is a reflection of this thought.

Previously, in my comment on #9479, I also suggested that we should use some form of Keycode. However, after some time and practice, I’ve come to realize that using a `String` might also be a reasonable approach. In a way, `Key: "a"` and `Keycode: 65` are not fundamentally different, they both are some kind of mapping, one map to `String`, one to `u32`. Additionally, the approach in your PR of directly mapping scancodes to keycodes is definitely problematic, as the mapping between scancodes and keycodes varies across different keyboard layouts.

**Comment by JunkuiZhang** [comment]
> I agree with your opinion that the feature to automatically change the input method should not be included in the gpui. However, I hope this functionality will be implemented within the vim crate rather than as a third-party extension.
> 
> > Previously, in my comment on #9479, I also suggested that we should use some form of Keycode. However, after some time and practice, I’ve come to realize that using a String might also be a reasonable approach. In a way, Key: "a" and Keycode: 65 are not fundamentally different, they both are some kind of mapping, one map to String, one to u32.
> 
> That's correct. They are both just different types of mapping. However, I didn't mean to focus on the mapping method itself. What I wanted to highlight is that the concept of a keystroke is used for different purposes. In gpui, the keystroke concept is applied in at least three different ways:
> 
> 1. The actual key press made by the user.
> 2. The virtual input dispatched through the `workspace::sendKeystroke` command.
> 3. The keystroke template needed when defining each keybinding, which might correspond to more than one user input.
> 
> Currently, in gpui, the `Keystroke` struct is used in all these scenarios. While this approach has certain advantages, in situations where the contexts of these different usages overlap (for example, matching a keybinding with an actual keystroke or sending a text-based `sendKeystroke` command to the input handler), the keystroke needs to be interpreted differently according to each scenario's semantics. This is where various heuristics come into play, and I believe this leads to issues, such as bugs with the Czech layout.
> 
> Perhaps this is why, in [winit](https://docs.rs/winit/latest/winit/keyboard/enum.Key.html), these different usages are separated into enum variants. If we adopt this approach, with some adjustments to the syntax for parsing keystrokes, it should be possible to resolve issues with the Czech layout and also allow vim's normal mode commands to be executed in a multilingual IME state without the need for automatic input method switching.

Sorry, I didn't quite follow you. Could you explain how this would fix the bug related to the Czech keyboard layout?

Anyway, my point about the keyboard layout things is that, say, currently, non-English keyboard layouts can generally be categorized into two groups:

1. Layouts that don't involve an Input Method Manager (IMM), such as Russian and Czech.
2. Layouts primarily used in East Asia that do involve an IMM.

For typing vim commands, there are two solutions for the first type of keyboard layout:

1. Install an English keyboard layout. This is the most commonly recommended solution, as it’s the one you'll find suggested across the internet.
2. Use key mappings, similar to what `nvim` offers.

For the second type of keyboard layout, there are also two solutions:

1. Install an English keyboard layout. On Windows, this is often referred to as installing an English input method; on macOS, it's common to install the ABC input method.
2. Provide automatic input method switching between insert and normal modes, as you mentioned with nvim.

In my opinion, neither vim, nvim, VSCode, nor any other software (including games or professional software like Autodesk's) typically provides a solution at the software level itself. I believe that Zed, especially GPUI, should focus on reliably translating platform keystrokes or char inputs into GPUI Keystrokes or Keycodes (if you prefer). Any additional processing, such as key mapping, should be handled above the GPUI layer.

**Comment by JunkuiZhang** [comment]
> The method I mentioned above enables key mappings like this: https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layout-independent-bindings. Of course, with the current method, one can use `cmd-/` on the Czech layout to mimic the `cmd-{` behavior on the US layout. However, that would prevent using `cmd-/` to toggle comments on the US layout.

I think I somehow understand your point. From my perspective, there’s a significant issue with your PR:

It doesn't distinguish between `scan code` and `virtual keycode`. In fact, both Windows and macOS use `virtual keycodes` as the basis for their input systems, and `winit` is also built on `virtual keycodes`. A particular concern is with the line `let scancode = native_event.keyCode();`, which is problematic because it returns a `CGKeyCode`, which is actually a `virtual keycode`. The key difference between the two is that `scan code` represents the physical position of a key. For example, on a standard English layout, the `[` key has a `scan code` of `0x1a` and a `VKCode` of `VK_OEM_4 (0xDB)`. However, on a Czech layout, the key in the same `scan code` position is `/`, with a `VKCode` of `VK_OEM_2 (0xBF)`.

That said, if `gpui` needs to be modified, it should be based on `VKCode`, not `scan code`. If there's a need to support using `scan code` as shortcuts, similar to how VSCode does, then there should be a function that converts between `scan code` and `virtual keycode` in the standard English layout, as seen here: [VSCode KeyCodes](https://github.com/microsoft/vscode/blob/a628b923ec0abdd3bbd289288b2339c2bf1a2809/src/vs/base/common/keyCodes.ts#L494).

Overall, as I mentioned earlier, the current issue with `gpui`'s `KeyStroke` isn't that it uses `String` rather than `VKCode` or `Scan Code`, like I said, they are just different mapping method, but the issue is that it relies on key mappings based on the English layout. Here’s the situation:

Consider the shortcut `cmd-shift-[`. Since `gpui` is based on the standard English layout (which is fine, AFAIK, VSCode and Vim do the same), the `[` key here is translated to `VK_OEM_4 (0xDB)`. However, in a Czech layout, there is no corresponding `VKCode` for this key. What we should do instead is:

1. Obtain the `VKCode` for `[` based on the standard English layout, which is `VK_OEM_4 (0xDB)`.
2. Use the conversion function I mentioned earlier to map `VK_OEM_4 (0xDB)` to its `Scan Code` in the standard English layout, which is `0x1a`.
3. Convert this `Scan Code` to the corresponding `VKCode` in the user's keyboard layout (Czech in this case), which would be `VK_OEM_2 (0xBF)`. In the Czech layout, this key is actually `/`, occupying the same physical position as `[` in the standard English layout.

A similar example is the `cmd+/` shortcut, which would eventually be translated to `cmd+-` in the Czech layout following the above steps.

> Are you suggesting that the key mapping features currently provided by the gpui crate should be moved outside of gpui? Or, if you're referring to the specific logic in my code for arrow keys and text manipulation keys, I also agree that this logic is quite crude, and I don't want it to be merged in its current state.

I need to clarify what I mean by "key mapping" first. I'm referring to functionality similar to the key mapping feature provided by nvim. In my view, if we want to address issues related to different keyboard layouts in Vim, the solution should be implemented on top of `gpui`, rather than within it.

I should also mention that I dont know how keyboard inputs are handled on macOS, but at least on Windows, there is no key mapping logic described above.

**Comment by JunkuiZhang** [comment]
A quick demo to illustrate my idea. #16903

**Comment by ConradIrwin** [comment]
I've started a public discussion here: https://github.com/zed-industries/zed/discussions/17031.

After having seen the discussion and wrapped my head around it a bit more, I think that you were probably more correct about your assumptions than I thought. I'd like to gather input for a few days from a wider set of brains before committing to anything; but likely we do want to make things work more like this PR does (but using virtual key codes instead of scan codes).

It would mean that `d i "` on a Brazilian layout does not require a `space`; but that seems worth the trade-off to have vim mode "just work" on Russian/Korean layouts (which we'd have to do by sending keystrokes ahead of IME).

Thanks again for kicking this off, and look forward to working with you on this.

**Comment by JunkuiZhang** [comment]
I have replace all the String with `VKCode` in #17015, we can discuss there, and I'd like to cherry-pick your commits. You can give #17015 a try, it's usable on Windows and macOS.

**Comment by ConradIrwin** [comment]
Closing this as superseded by other discussions.

**Pull request closed without merging**
