### PR TITLE
Highlight selections on vim yank

### LINKED ISSUE #7311: vim mode: it's good to flashing yanked selections once, so users can know which lines they yanked.
### Check for existing issues

- [X] Completed

### Describe the feature

I think it's good to highlight on yanked, it's useful if user yank through `Y`, e.g: `3Y`, `5Y`.

Then user knows if he made a corrent yank.

It can be powered by the following config in neovim:
https://github.com/nvim-lua/kickstart.nvim/blob/7af594fd319fbae6b2aaa06337f3df8acbbb7f18/init.lua#L347-L354

### If applicable, add mockups / screenshots to help present your vision of the feature

This is how it works in neovim:
[asciicast](https://asciinema.org/a/cS5MmG3ymJApkk6KHMxT3vRDk)

### PR DESCRIPTION
**Pull request by ConradIrwin**
Fixes: #7311

Co-Authored-By: WindSoilder <WindSoilder@outlook.com>

Release Notes:

- Added a highlight on yanked text in vim normal mode

**or**

- N/A

### CODE REVIEW

**Comment by mrnugget** [comment]
Neat!

**Comment by RustyDev69** [comment]
Is there a way to change the highlight timings, or disable the highlighting alltogether ?

**Comment by ConradIrwin** [comment]
Not yet, but PR's welcome! We could add a setting to the existing vim settings.

What do you want to change about it?

**Comment by RustyDev69** [comment]
I was thinking of adding a change where we can configure both the highlight timings 
so like ppl may want it to flash for only 50ms or smth
and also be able to disable the flashing if they don't want it 
also the cursor shape thing doesn't work in insert mode ?

**Comment by RustyDev69** [comment]
> Not yet, but PR's welcome! We could add a setting to the existing vim settings.
> 
> What do you want to change about it?

https://github.com/zed-industries/zed/pull/21479
I made a smol PR

**Pull request merged**
