### PR TITLE
vim: Add "unmatched" motions `]}`, `])`, `[{` and `[(`

### PR DESCRIPTION
**Pull request by helgemahrt**
Closes #20791

Release Notes:

- Added vim ["unmatched" motions](https://github.com/vim/vim/blob/1d87e11a1ef201b26ed87585fba70182ad0c468a/runtime/doc/motion.txt#L1238-L1255) `]}`, `])`, `[{` and `[(`

### CODE REVIEW

**Comment by helgemahrt** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
Thanks for this!

**Comment by helgemahrt** [comment]
Thanks for the fix, and for showing me how times work! 😊

**Comment by bfulop** [comment]
Thank you so much for this addition! ❤️ 
So useful for navigating in Javascript test blocks!

**Pull request merged**
