### PR TITLE
Fix prettier plugins does not seem to be picked up

### PR DESCRIPTION
**Pull request by RemcoSmitsDev**
This fixed the issue that prettier plugins were not picked up. The old code would always send an empty array to the prettier plugin that happens inside the `prettier_server.js`.

**Before**
The `options.plugins` key is an empty array, which is not correct.
```log
stderr: Resolved config: {"singleQuote":true,"trailingComma":"all","plugins":["prettier-plugin-organize-imports"]}, will format file '/Users/remcosmits/Documents/code/prettier-test/src/app/page.tsx' with options: {"singleQuote":true,"trailingComma":"all","plugins":[],"parser":"typescript","path":"/Users/remcosmits/Documents/code/prettier-test/src/app/page.tsx"}
```

https://github.com/zed-industries/zed/assets/62463826/52f2aad0-2f96-43a9-81ec-9d4630c495b2

**After**
The `options.plugins` contains the `prettier-plugin-organize-imports` plugin as expected.
```log
stderr: Resolved config: {"singleQuote":true,"trailingComma":"all","plugins":["prettier-plugin-organize-imports"]}, will format file '/Users/remcosmits/Documents/code/prettier-test/src/app/page.tsx' with options: {"singleQuote":true,"trailingComma":"all","plugins":["prettier-plugin-organize-imports"],"parser":"typescript","path":"/Users/remcosmits/Documents/code/prettier-test/src/app/page.tsx"}
```

https://github.com/zed-industries/zed/assets/62463826/9045028d-aeca-4df1-819c-01905d83216c

Release Notes:
- Fixed send plugins correctly to the prettier plugin ([#8841](https://github.com/zed-industries/zed/issues/8841)).

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
@mrnugget Would be nice if you could check this, because I know you have hacked on it a couple of times.

**Comment by mrnugget** [comment]
Whoa, how did I get plugins to work before then? Doesn't this mean that plugins were never sent along?

**Comment by RemcoSmitsDev** [comment]
> Whoa, how did I get plugins to work before then? Doesn't this mean that plugins were never sent along?

Uhm, don't want to say they have never worked. Because I was there when you were hacking on it. But It almost seems so.

**Comment by mrnugget** [comment]
What if we do send along plugins in the params? Here:

https://github.com/zed-industries/zed/blob/1634a33b9cda91955aadcf8802db2526da4f706d/crates/prettier/src/prettier.rs#L320-L342

I think there's two things that can happen:

1. Zed finds prettier plugins and sends them along (like in the code I linked to)
2. prettier_server.js resolves the config and finds plugins.

Right? 

If so, I think both should work. So maybe instead of removing the line, we should have a separate line that checks whether `plugins` is empty and if so, fallback to resolved plugins.

**Comment by RemcoSmitsDev** [comment]
Yeah, that are the 2 cases that can happen. 

So you mean that if on project level the plugins are empty, we fall back to the zed configured prettier plugins? If so, that would make sense. Because we do this for the normal `prettierOptions` as well.

**Comment by mrnugget** [comment]
When I made the other changed I used this repository for testing: https://github.com/LukeberryPi/phived

`.prettierrc.json`:
```json
{
  "printWidth": 80,
  "semi": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "endOfLine": "auto",
  "plugins": ["prettier-plugin-tailwindcss"]
}
```

I created `src/components/Testing.tsx`:

```tsx
export function Testing() {
  return <span className={`items-center flex`}>This is testing</span>;
}
```

The `className` ordering is wrong.

When I use Zed Nightly and save I get the following in the logs:

```
stderr: Resolved config: {"printWidth":80,
"semi":true,
"tabWidth":2,
"trailingComma":"es5",
"useTabs":false,
"endOfLine":"auto",
"plugins":["prettier-plugin-tailwindcss"]
},
will format file '/Users/thorstenball/code/clones/phived/src/components/Testing.tsx' with options: {"printWidth":80,
"semi":true,
"tabWidth":2,
"trailingComma":"es5",
"useTabs":false,
"endOfLine":"auto",
"plugins":["/Users/thorstenball/code/clones/phived/node_modules/prettier-plugin-tailwindcss/dist/index.js"],
"parser":"typescript",
"path":"/Users/thorstenball/code/clones/phived/src/components/Testing.tsx"}
```

Note the `plugins` here.

That works for me. I'm going to investigate this later (see you in Zed?), but first I want to fix ESLint, which seems to have been broken.

**Comment by mrnugget** [comment]
Okay, I just checked out your branch locally and tried it. It works with the test case repo that I have. I'm going to merge this now.

For the record: logic now is that we first try to locate plugins that we think should go along with a given language (i.e. tailwind plugin), but if `prettier` can resolve the config, then we use that instead.

**Pull request merged**
