### PR TITLE
Add C++ file icon

### PR DESCRIPTION
**Pull request by Kalmaegi**
add cpp file icon, source file from: https://github.com/file-icons/icons/blob/master/svg/C%2B%2B.svg
I've tweaked the Bring You format a bit to make it more suitable for display in ZED

### CODE REVIEW

**Comment by maxdeviant** [comment]
Can we size the icon down a bit? It looks way too large in comparison with our other icons.

**Comment by jansol** [comment]
`cc`, `cxx`,and `C` are also common C++ file suffixes, the icon should apply to those as well.

**Comment by weartist** [comment]
> Can we size the icon down a bit? It looks way too large in comparison with our other icons.



> Can we size the icon down a bit? It looks way too large in comparison with our other icons.

sure, this before:
image

this now:
image

**Comment by maxdeviant** [comment]
The icon still seems too large when compared to our existing icons.

The C++ icon is at 512x512, while most of our other icons are 14x14.

**Comment by weartist** [comment]
> The icon still seems too large when compared to our existing icons.
> 
> The C++ icon is at 512x512, while most of our other icons are 14x14.

sorry  not get your mean before, resized it

**Comment by maxdeviant** [comment]
The icon doesn't look quite right:

Screenshot 2024-02-26 at 10 18 39 PM

You can barely make out the `++` in the icon. I think we need a different icon that is clearer at small sizes.

**Comment by weartist** [comment]
> The icon(图标) doesn't look quite right:
> 
> Screenshot 2024-02-26 at 10 18 39 PM
> You can barely(勉强) make out the `++` in the icon(图标). I think we need a different icon(图标) that is clearer at small sizes.

I think 

> The icon doesn't look quite right:
> 
> Screenshot 2024-02-26 at 10 18 39 PM
> You can barely make out the `++` in the icon. I think we need a different icon that is clearer at small sizes.

I think so, although the icon is broad, but `++` is too small, I extracted the internal symbols and removed the borders, but even then, the `++` was small and illegible, so I found another icon, it has the same line width as other languages icon, how do you feel about this one?
And I found that the icons of file are not perfectly aligned, and the icons of some languages will be smaller e.g. haskell

also too small:
image



newest:
image

**Comment by weartist** [comment]
> The icon doesn't look quite right:
> 
> Screenshot 2024-02-26 at 10 18 39 PM
> You can barely make out the `++` in the icon. I think we need a different icon that is clearer at small sizes.

I think so, although the icon is broad, but `++` is too small, I extracted the internal symbols and removed the borders, but even then, the `++` was small and illegible, so I found another icon, it has the same line width as other languages icon, how do you feel about this one?
And I found that the icons of file are not perfectly aligned, and the icons of some languages will be smaller e.g. haskell

also too small:
image



newest:
image

**Pull request closed without merging**
