### PR TITLE
Immediate edit step resolution

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
## Todo

* [x] Parse and present new XML output
* [x] Resolve new edits to buffers and anchor ranges
* [x] Surface resolution errors
* [x] Steps fail to resolve because language hasn't loaded yet
* [x] Treat empty `<symbol>` tag as None
* [x] duplicate assists when editing steps
* [x] step footer blocks can appear *below* the following message header block

## Release Notes:

- N/A

### CODE REVIEW

**Comment by sagarspatil** [comment]
@maxbrunsfeld Sorry to disturb/bother you. Just wanted to enquire if this fixes 
https://github.com/zed-industries/zed/issues/16894#issuecomment-2318462683

Im enjoying fast edit mode but /workflow just fails with step resolution failed.

Thanks again, you are brilliant.

**Comment by maxbrunsfeld** [comment]
We still have some work to do on /workflow, but this eliminated one common way that step resolution could fail. It’ll go out in the preview release on Wednesday.

**Comment by sagarspatil** [comment]
Thank you so much. I really appreciate it. I was going crazy trying to make /workflow work.

**Comment by sagarspatil** [comment]
@maxbrunsfeld 
Currently, we have to manually apply all the transformations. What do you think about providing a Transform All button which applies the transformations automatically? (cursor provides this as an option in composer)

**Comment by sagarspatil** [comment]
> We still have some work to do on /workflow, but this eliminated one common way that step resolution could fail. It’ll go out in the preview release on Wednesday.

Just wanted to say that I've been using /workflow and I don't see any errors now. You are brilliant! Thank you so much!

**Pull request merged**
