### PR TITLE
Note installation step via Homebrew

### PR DESCRIPTION
**Pull request by Goooler**
https://formulae.brew.sh/cask/zed

### CODE REVIEW

**Comment by Goooler** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
Can we add this in a separate subsection under Installation?

The Homebrew install is not an official release channel, so it should not be listed on the same level as a download from the Zed website.

**Comment by Goooler** [comment]
Done.

**Comment by maxdeviant** [comment]
@Goooler Thank you!

**Pull request merged**
