### PR TITLE
git: Support git repos with .git folder above project root

### LINKED ISSUE #4419: Project cannot switch branches from local git repository subdirectory
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a Zed project of a local git repository, Zed provides the ability to checkout available git branches. This capability is not there when a Zed project is loaded from a subdirectory of a git repository. This can be a problem for a mono repo, where you would not want to load the entire mono repo into a Zed project at once.

For example:
- A git repo exists at `~/src/mono`, with subdirectory `~/src/mono/foo`.
- When Zed opens `~/src/mono`, it can switch branches via the dropdown menu on the top left of the window.
- However when a project is loaded at `~/src/mono/foo`, the ability to switch branches is no longer available.

### Environment

Zed: v0.107.6 (stable)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### LINKED ISSUE #4672: Git support when opening monorepo subfolder
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you open a subfolder of a monorepo in zed (a folder that does not have a `.git` directory at it's root) you lose all source control support inside zed (file navigator highlighting etc). Currently, zed expects the .git folder to be in the root. It's often nice to not have to open the entire monorepo folder.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### LINKED ISSUE #5161: Changes aren't tracked if folder opened is inside git repository
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a folder somewhere inside a git repository but not the root
2. Make changes to a file
3. Git gutter is not visible

### Expected behavior

Git gutter should be visible

### Environment

```
Zed 0.61.1 – /Applications/Zed.app 
macOS 13.0 
architecture arm64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

_No response_

### LINKED ISSUE #6762: impl VScode `git.openRepositoryInParentFolders` = 'always'
### Check for existing issues

- [X] Completed

### Describe the feature

When you open a subdirectory of a git repository, you will not be able to see git diff. Of course, prev-chunk doesn't work either

https://github.com/zed-industries/zed/issues/4672
https://github.com/zed-industries/zed/issues/5161

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #7816: Git: Open repository in parent folders
### Check for existing issues

- [X] Completed

### Describe the feature

Control whether a git repository in workspace parent folders or open files should be opened.
You can choose between "never", "always", and "ask if possible".

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #8275: Zed Not Recognizing Git Extension in Subfolders
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Zed editor in a mono repository, I’ve noticed that it doesn’t consistently recognize Git extensions when working within subfolders. Specifically:

When I open the main folder, Git integration works as expected.
However, when I open a subfolder, Zed fails to recognize the Git status.
This behavior makes it challenging to work efficiently in mono repos where subfolders are common. I’d appreciate any insights or solutions to address this issue.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### LINKED ISSUE #8418: Lacking git indicators on the project panel when opening a specific package in a monorepo
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My monorepo is structured like the following:
```
my-monorepo/
└── packages/
    ├── package-1
    ├── package-2
    ├── ...
    └── package-n
```

When I `zed my-monorepo`,
image

When I `zed my-monorepo/packages/package-2`:
image

I often only need to be editing a package or two in my monorepo, so I just add the relevant folders to my editor, but the lack of indicators is jarring.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### LINKED ISSUE #10154: Zed does not show git status and git diff when launched from a subfolder
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you launch zed from a subfolder inside a git repo, then all the git markings do not appear.

Thus, you can no longer see the `git diff`s or any of the other things such as what file has been modified (in the project panel), or the name of the branch (in the top bar) and so on.

These things are visible only if you launch zed from the root of the repo where `.git` resides basically. But I think it would make sense for this to not be the case 

### Environment

Zed: v0.129.1 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-04-04 at 10 39 01 AM
Screenshot 2024-04-04 at 10 39 18 AM

The same file, if I launch from the root of the repo, it works.

Screenshot 2024-04-04 at 10 40 37 AM

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by mrnugget**
TODOs:

- [x] Add assertions to the test to ensure that the git status is propagated
- [x] Get collaboration working
- [x] Test opening a git repository inside another git repository
- [x] Test opening the sub-folder of a repository that itself contains another git repository in a subfolder

Fixes:
- Fixes https://github.com/zed-industries/zed/issues/10154
- Fixes https://github.com/zed-industries/zed/issues/8418
- Fixes https://github.com/zed-industries/zed/issues/8275
- Fixes https://github.com/zed-industries/zed/issues/7816
- Fixes https://github.com/zed-industries/zed/issues/6762
- Fixes https://github.com/zed-industries/zed/issues/4419
- Fixes https://github.com/zed-industries/zed/issues/4672
- Fixes https://github.com/zed-industries/zed/issues/5161

Release Notes:

- Added support for opening subfolders of git repositories and treating them as part of a repository (show git status in project panel, show git diff in gutter, git blame works, ...) ([#4672](https://github.com/zed-industries/zed/issues/4672)).

Demo video:

https://github.com/zed-industries/zed/assets/1185253/afc1cdc3-372c-404e-99ea-15708589251c

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Oh, yes, please! Most of my work is in subfolders of a monorepo, and I've been missing the git integrations. This will be great!

FYI, if I understand correctly, I think that this would close (or at least address) #10154, #8418, #8275, #7816, #6762, #4419, #4672, and #5161. Phew!

**Comment by mrnugget** [comment]
Thanks for that listen @claytonrcarter!

**Comment by claytonrcarter** [comment]
Just wanted to say **thank you** for this! I updated and rebuilt, and git integration is working great in my monorepo projects. Thank you! 🙏 🎉

**Comment by mrnugget** [comment]
Great to hear, @claytonrcarter! Let me know if you bump into any issues :)

**Pull request merged**
