### PR TITLE
Fix Flashing Hover Popover

### PR DESCRIPTION
**Pull request by cyypherus**
Release Notes:

- Use an inclusive range for local range containment check to match LSP behavior & fix popover flashing while the cursor moves over the last character of a symbol.

https://github.com/zed-industries/zed/assets/17223924/6c3ddc9c-04fb-4414-812f-025ede5ecaf7

### CODE REVIEW

**Comment by ejjonny** [comment]
@cla-bot check

**Comment by ejjonny** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@ejjonny Thank you! This has been driving me crazy, but I didn't take the time to dig in.

I'm not sure I understand the comment you added here: https://github.com/zed-industries/zed/pull/8238/commits/1a13b3bba5f21886f9ac792523d0a934d3161fef#diff-2c4beb0f3febb4181a2f3bcf1d1008cd789d2f072b34b57c3de3249d88ffe48fR890-R892, so we should remove that (or clarify it) but the code change seems good to me!

You'll need to run `cargo fit` to fix the lint error.

**Comment by ejjonny** [comment]
Lol, it was driving me nuts too

Regarding the comment - I realized that all the glyph hit testing is offset by the padding that's added right there & significant functionality depends on it.

The cursor 'snapping' behavior I mentioned is where you click just to the right of the center of a glyph and the cursor goes to the index that is on the right. It's not actually implemented the way you'd assume - the rendering has just been nudged about a half-character's width to make it happen, leaving the hit-testing behind the scenes at the `text_bounds` leading edge with no padding.

I'm happy to remove or update the comment regardless. lmk what you think

**Comment by ConradIrwin** [comment]
Oh I see, `gutter.margin` is a very strange way to spell padding, which was confusing me :D.

Let's update the comment to call that out, how about:

```
// Offset the content_bounds from the text_bounds by the gutter margin (which is roughly half a character wide) to make hit testing work more like how we want.
``` 

I also just merged another outstanding PR that will conflict with this. If you're able to update the comment and rebase I can hit merge (otherwise I'll do this tomorrow).

**Pull request merged**
