### PR TITLE
vim: Convert from visual mode to normal mode with a single click

### LINKED ISSUE #4319: Vi mode: when in `visual` mode, single click inside buffer should go back to `normal` mode
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. press `v` to go to visual vode
2. click inside an buffer
3. it still remains in visual mode

But I'd expect it to go back to `normal` mode, that's how neovim does

### Environment

Zed: v0.114.1 (preview)
OS: macOS 13.3.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/22256154/c4b56a99-99d6-43cc-8e2e-733d1ac438c0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by WindSoilder**
Release Notes:

- Fixed #4319

Here is a demo after the fix:
https://github.com/zed-industries/zed/assets/22256154/a690f146-73c9-4b0e-8527-e4faf690cca2

Actually I'm not really sure should I submit my idea to discussion, since it's not a large change, and it's something like a bug fix.  So I directly create a pr here.

### CODE REVIEW

**Comment by WindSoilder** [comment]
@cla-bot check

**Comment by mrnugget** [comment]
Hey! Thanks for this! With this change, does `opt+click` still work, to create multiple cursors?

**Comment by WindSoilder** [comment]
Thank you for a good question, I haven't thought about it.

After some testing, if I'm in visual mode, `opt+click` will go back to normal mode and create multiple cursors.
If I'm in normal mode, `opt+click` will create multiple cursors as normal.

**Comment by ConradIrwin** [comment]
@WindSoilder Thanks for the fix here!

I think we need to do this more carefully, as the current version breaks the visual block mode tests and opt-click in visual mode. If you want to pair with me on fixing this: https://calendly.com/conradirwin/pairing.

I think we should try only entering normal mode if there is exactly one selection and it is empty. 

Some behaviors I'd like to work:
* visual block mode onto an empty line (this is the test that's failing)
* opt-click-and-drag to add another visual selection to an existing visual selection (currently this gets interrupted, I think because the local_selections_change fires on the click with an empty selection and stops my drag).
* opt-click on another line in visual line mode to create a new visual line selection.

**Comment by ConradIrwin** [comment]
@WindSoilder and I have a pairing session on Friday to get this over the line! Looking forward to it :D

**Comment by WindSoilder** [comment]
Hi, I've tried to reproduce the CI failure, but I got no luck :-( not really sure is it been handled on latest main?

**Comment by diocletiann** [comment]
@ConradIrwin I tried the latest preview where this was merged and when some text is selected, clicking elsewhere doesn't activate normal mode like Vim would.

**Comment by diocletiann** [comment]
> @diocletiann strange, it seems to work for me... Are you clicking on the editor, or another part of the UI?

Never mind, it's working now. Maybe I tried it before updating Zed Preview.

**Pull request merged**
