### PR TITLE
python: Add pylsp as the secondary language server

### PR DESCRIPTION
**Pull request by osiewicz**
Closes #ISSUE

Release Notes:

- Added python-lsp-server as a secondary built-in language server.

### CODE REVIEW

**Comment by albas99** [comment]
Great! Now how do I remove this or at least disable pycodestyle, mypy and flake8 because now I'm getting too many unnecessary warning since this update.

**Comment by metallerok** [comment]
Need documentation on setting up individual modules pyslp. I want to use pycodestyle, but the whole pylsp breaks the autocomplete from Pyright and extremely slows down the whole editor a lot, Seems like several instances of different LSPs start at the same time

**Comment by dhbrojas** [comment]
Would it be possible to reflect this change on the documentation web page dedicated to configuring Python for Zed? And explain how to enable/disable both language servers for Python? Ever since this update I get mypy cache folders in my root and unwanted warnings on my screen. Thanks in advance!

**Comment by someone13574** [comment]
> Great! Now how do I remove this or at least disable pycodestyle, mypy and flake8 because now I'm getting too many unnecessary warnings since this update.

I was having this issue as well. Adding `"language_servers": ["!pylsp", "..."]` to your settings file disables them while keeping pyright.

**Comment by albas99** [comment]
An update has been pushed earlier today disabling mypy and pycodestyle but that's still not enough, I don't know why there's a need to add pylsp to the editor when there's already a pylsp extension that people can install if they wanted. If it's not gonna be removed at least give us a way to remove it ourselves entirely through the settings because as @metallerok pointed out, adding pylsp has significantly slowed down the editor and now it's no more than VSCode in terms of speed.

**Comment by ptolemy-tk** [comment]
@albas99 you can disable it with the following in settings:

```
{
  "languages": {
    "Python": {
      "language_servers": ["!pylsp", "..."]
    }
 }
 ```

**Pull request merged**
