### PR TITLE
windows: Fix title bar appearing when set to None

### PR DESCRIPTION
**Pull request by MatinAniss**
When the `titlebar` option is set to `None` in the `WindowOptions` it currently still displays the title bar of the window on Windows. This PR fixes this issue.

Release Notes:

- N/A

### CODE REVIEW

**Comment by MatinAniss** [comment]
I decided to move the small fix to a new PR which is accompanied by another fix/simplification of how the title bar padding is handled. https://github.com/zed-industries/zed/pull/13420

**Comment by mikayla-maki** [comment]
Superseded by other PRs

**Comment by mikayla-maki** [comment]
Actually, I'm unsure if this is superseded by https://github.com/zed-industries/zed/pull/13420 and https://github.com/zed-industries/zed/pull/13975, what do you think @MatinAniss ?

**Comment by MatinAniss** [comment]
https://github.com/zed-industries/zed/pull/13975, does fix this issue but it keeps the transparent title bar which does conform more with the current macOS implementation. I think the implementation of the window options on both Windows and macOS should be discussed a later time and reworked. Closing this as that PR does fix the main issue.

**Comment by mikayla-maki** [comment]
Yeah, I think we could follow the linux client side / server side setting and get rid of the titlebar field. But that opens another can of worms…

Anyway, thank you!

**Pull request closed without merging**
