### PR TITLE
vim: Fix increment/decrement command

### LINKED ISSUE #16672: "vim: increment" is inconsistent with vim
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've stumbled to the following limitations/inconsistencies with the `^A` ("vim: increment") command:

1. The range is limited to `i32` range. I.e. incrementing `2147483647` results in `-2147483648`, and not `2147483648` as expected. By comparison, the original vim support values from `-18446744073709551615` to `18446744073709551615`, aka 2⁻⁶⁴ to 2⁶⁴. Given that most modern languages support 53-bit or 64-bit integer literals, it's a not rare situation to have such huge values in the code.
2. It drops leading zeroes. E.g. incrementing `0x0001` results in `0x2` and not in `0x0002` as in the original vim.
3. Incrementing `0x39u32` twice (`^A ^A`) results in `0x3au33`, and not in `0x3bu32` as in the original vim.

### Environment

zed 0.149.3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by hekmasani**
Improving vim increment and decrement command.

Closes: #16672

## Release Notes:

- vim: Improved edge-case handling for ctrl-a/ctrl-x

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this!

Let's simplify the code a bit:

* For hex and binary strings it looks like the vim behavior is equivalent to a `wrapping_add_signed` on a u64. 
* For decimal strings, it looks like the vim behavior is like a `wrapping_add_signed` on an `i65` (though obviously that type doesn't exist). I think you can get the same behavior using `wrapping_add_signed` on a `u64` and toggling the sign bit if overflow has occurred (which you can either detect using a checked add, or by seeing if an addition made the number smaller, or a subtraction made it bigger).
* Let's not shrink the count to an i32, but keep it as an i64.

Finally could you please add some more tests that cover the edge-cases that you've fixed.

**Comment by hekmyr** [comment]
Thanks, for your feedback. Indeed, this is so much simpler this way. I also extended the list of defects I found and fixed! Most of them are demonstrated in the tests I wrote.

**Comment by ConradIrwin** [comment]
Thanks for this! I spent a bit of time updating the code to use rusts builtin `wrapping_add_signed`. If this code seems to do the right thing for you, I'll merge.

**Comment by hekmyr** [comment]
Yes, this is better and does the right thing.

**Pull request merged**
