### PR TITLE
Adjust the yss surrounds operator

### PR DESCRIPTION
**Pull request by Kalmaegi**
For #11084 In the case of an indentation in front of the current line, it may also be necessary to deal with the start point of the selected range

Release Notes:

- N/A

### CODE REVIEW

**Comment by weartist** [comment]
Maybe we also need to deal with the case where the end of the line is a space, and if so, the logic at the end of the line needs to be modified somewhat

**Comment by ConradIrwin** [comment]
:+1: looks like that's what nvim does.

**Comment by weartist** [comment]
It seems that there should be no difference between using `movement::right` directly and using `offset+ch.len_utf8()`, so I chose a more intuitive way

**Comment by ConradIrwin** [comment]
@weartist Instead of re-doing the buffer iteration, I thought it would be better to reuse the existing logic. Then I noticed that we didn't have a "go to last non-whitespace" yet...

So, pushed up some fixes to `g _` so we can re-use that.

Along the way I noticed that counts weren't working, so I fixed that too.

**Comment by weartist** [comment]
> @weartist Instead of re-doing the buffer iteration, I thought it would be better to reuse the existing logic. Then I noticed that we didn't have a "go to last non-whitespace" yet...
> 
> So, pushed up some fixes to `g _` so we can re-use that.
> 
> Along the way I noticed that counts weren't working, so I fixed that too.

@ConradIrwin  It's more suitable, thank you very much!

**Pull request merged**
