### PR TITLE
Add ability to expand/collapse directories using the `project_panel::Open` action

### PR DESCRIPTION
**Pull request by d1y**
#6910

I changed the `open_file` symbol to `open`, because this is more consistent with the original intention

Release Notes:

- Added the ability to expand/collapse directories using the `project_panel::Open` action.

### CODE REVIEW

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
Would you mind also adding a test demonstrating this behavior?

**Comment by d1y** [comment]
@mikayla-maki Can you help me take a look? I really need this feature. I am one step closer to deleting vscode looool

**Comment by d1y** [comment]
> Would you mind also adding a test demonstrating this behavior?

I'm sorry, I'm not familiar with rust and can't write unit tests, the behavior is the same as I demonstrated in the video :(

https://github.com/zed-industries/zed/assets/45585937/62b6a18d-62bf-433b-b470-b99282b0c2b7

**Comment by mikayla-maki** [comment]
You can see how to write our unit tests at the bottom of the file you where editing, in the tests module :) 

We'd also be glad to work with you at one of our fireside hacks or in discord!

**Comment by d1y** [comment]
> You can see how to write our unit tests at the bottom of the file you where editing, in the tests module :)
> 
> We'd also be glad to work with you at one of our fireside hacks or in discord!

I added the test, can you help me take a look now? 👀

**Comment by juninhopo** [comment]
very good, I was writing these same changes when I found your PR 🚀

**Comment by juninhopo** [comment]
Did you remove the shortcuts from keymap.json?

I tested your changes and they are not working. I believe that what is working there is the keymaps.

Could you please check if you removed the keymaps?

**Comment by d1y** [comment]
> @d1y
> 
> Did you remove the shortcuts from keymap.json?
> 
> I tested your changes and they are not working. I believe that what is working there is the keymaps.
> 
> Could you please check if you removed the keymaps?

I didn't delete anything else, are you sure you applied my patch but it didn't take effect? 🤔

```json
{
    "context": "ProjectPanel && not_editing",
    "bindings": {
      "enter": "project_panel::Open",
      "space": "project_panel::Open",
    }
}
```

**Comment by juninhopo** [comment]
@d1y

yes, I cloned your PR.

Did you build Rust again?

If you want, we can join discord to check about it. I'm very interested in your pr.

my discord: juninhopo

**Comment by juninhopo** [comment]
@d1y @mikayla-maki it's working... 🚀

**Comment by d1y** [comment]
Are there any issues with this PR? I urgently need this feature 😵‍💫

**Review by mikayla-maki — APPROVED** [review]

**Pull request merged**
