### PR TITLE
chore: Bump Rust to 1.82

### PR DESCRIPTION
**Pull request by osiewicz**
Closes #ISSUE

Release Notes:

- N/A

### CODE REVIEW

**Comment by osiewicz** [comment]
It seems that we're hitting an infinite loop on this line https://github.com/zed-industries/zed/blob/main/extensions/test-extension/src/test_extension.rs#L77 when we're trying to restart the language server at https://github.com/zed-industries/zed/blob/5506669b0654add16dca8447332f4804a4cea0d8/crates/extension/src/extension_store_test.rs#L754, which results in stalled await on https://github.com/zed-industries/zed/blob/5506669b0654add16dca8447332f4804a4cea0d8/crates/extension/src/extension_store_test.rs#L758

**Comment by osiewicz** [comment]
The test passes when the test extension is compiled with 1.81 and the rest uses 1.82.

**Comment by osiewicz** [comment]
I've bisected it to nightly-2024-08-24 and I'm pretty sure it's https://github.com/rust-lang/rust/commit/736f773844e7ebf05ccb827c17b7ad9eb28aa295 that's the culprit.

**Comment by SomeoneToIgnore** [comment]
Given that we pivoted into fixing stdlib for this (https://github.com/rust-lang/rust/pull/133184), this PR seems obsolete.

**Comment by osiewicz** [comment]
Eh, I'd say this PR is still relevant, but we can reopen it in a few months.

**Pull request closed without merging**
