### PR TITLE
Add icon to title bar branch switcher

### LINKED ISSUE #14945: Add icon to title bar branch switcher
### Check for existing issues

- [X] Completed

### Describe the feature

It'd be neat to have an icon next to the branch switcher so we know what that text actually means.

### If applicable, add mockups / screenshots to help present your vision of the feature

image

### PR DESCRIPTION
**Pull request by jackTabsCode**
Closes #14945.

Icon from https://lucide.dev, which someone said is the source of Zed's icons.

Release Notes:

- Added icon to title bar branch switcher ([#14945](https://github.com/zed-industries/zed/issues/14945)).
image

### CODE REVIEW

**Comment by huacnlee** [comment]
You can find icons from https://lucide.dev/icons/git-pull-request

Zed's icons are from lucide.dev

**Comment by jackTabsCode** [comment]
> Maybe can find icons from https://lucide.dev/icons/git-pull-request
> 
> Zed's icons are some from lucide.dev

Alrighty then-I've updated it with their icon, and I've also made it smaller.

**Comment by jansol** [comment]
There is already a "version control" icon being shipped, it's used in the inline git blame:
image

**Comment by jackTabsCode** [comment]
> There is already a "version control" icon being shipped, it's used in the inline git blame:
> 
> image
> 
> 
> 
> EDIT: looks to be `assets/icons/file_icons/git.svg`. Additionally there is a variant at `assets/icons/pull_request.svg`.

I don't think a generic icon that doesn't communicate it's a branch helps to convey the meaning of the text! It could be a remote, or a tag!

**Comment by jansol** [comment]
> I don't think a generic icon that doesn't communicate it's a branch helps to convey the meaning of the text! It could be a remote, or a tag!

Remotes hardly make sense in that context. Unless you mean that it'd be an indicator that you are editing a project remotely?

It could be a tag, sure. That would make as much sense as a branch, though, since branches are basically tags that move with every commit. Heck, I'd go as far as suggest showing the shortened commit hash if it does not match a branch or tag - this is what my neovim is doing too:
image

**Comment by jackTabsCode** [comment]
I'll also note that both Sublime and VSCode have icons representing the branch but not for project name.

image
image

**Comment by jackTabsCode** [comment]
I don't understand why my PR branch was edited to use the Pull Request icon. As I said, I don't think that icon represents a branch, compared to what I had originally submitted, which is also analagous with the other editors' icons I posted above.

 I'm a little confused what the argument is to not shipping a specific icon for a specific purpose, rather than using an existing one which exhibits something else.

**Comment by maxdeviant** [comment]
> Hey! I'm not against this in theory...
> 
> However I'd want to make sure that if we add this we:
> 
> 1. make sure all the project-related buttons have icons
> 2. we don't default it on (being minimal is one of our core tenants, even if it's slipped a bit recently.)
> 
> So we could either close this now and get back to it when we have time to make those changes, or if you wanted to take a stab at it here is what would need to be done:
> 
> * Add icons for each project-related menu (remote project status, project, branch)
> * Add a setting to enable it (likely `title_bar: { show_icons: true }` or something similar`
> * Add the above setting as false in the default config.
> 
> If you do decide to pick this up it'd be really nice if you could add screenshots or before/after to make it easier to review.
> 
> Thanks!
> 
> Edit: I added myself, @danilo-leal and @maxdeviant as reviewers, but just getting an ok from one of us would be sufficient!

Closing this for now. Feel free to reopen following the approach described above.

**Comment by jackTabsCode** [comment]
As I previously noted, I'm not interested picking up more work to add icons and settings that I find noisy. Thanks.

**Pull request closed without merging**
