### PR TITLE
Rename scrollbar_thumb to be consistent with other style properties

### PR DESCRIPTION
**Pull request by phisch**
This small inconsistency was mentioned on the discord. This fixes it.

Release Notes:

- Themes: Renamed `scrollbar_thumb.background` to `scrollbar.thumb.background` to be consistent with other style properties.

### CODE REVIEW

**Comment by phisch** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
This is the first breaking change we’ve made to the themes since we launched them, so we’ll have to think about how we want to do it.

**Comment by phisch** [comment]
@maxdeviant I didn't think it's that critical this early on.

But in this case, it would probably the best and cleanest to use a [serde alias](https://serde.rs/field-attrs.html#alias) as well. So that the json schema shows and suggests the new, corrected name, but a theme using the old json value would still deserialize the field into the correct property.

Let me know if you think this is a good idea, or have a better one, and I'll update the PR!

**Comment by maxdeviant** [comment]
> @maxdeviant I didn't think it's that critical this early on.
> 
> But in this case, it would probably the best and cleanest to use a [serde alias](https://serde.rs/field-attrs.html#alias) as well. So that the json schema shows and suggests the new, corrected name, but a theme using the old json property would still deserialize into the correct property of the struct.
> 
> Let me know if you think this is a good idea, or have a better one. I updated the PR with the alias in the meantime.

Using an alias sounds good 👍🏻

**Pull request merged**
