### PR TITLE
Scale X11 mouse events by the window scale factor

### PR DESCRIPTION
**Pull request by wezm**
When the window scale factor was other than 1.0 mouse events were reported to the UI in the wrong place causing hover effects and mouse clicks to not be reported where the mouse cursor was. This PR applies the scaling factor to mouse events to remedy this.

Is have a HiDPI display that I run with 2x scaling. To avoid Zed looking tiny I built it with [scale_factor](https://github.com/wezm/zed/blob/6ebe599c980508aa8c7e87fad3e59e5a43892368/crates/gpui/src/platform/linux/x11/window.rs#L249) set to 2.0. This fixed the tiny window problem but now mouse events were off from the cursor position. This PR is my attempt to address this.

Release Notes:

- Fixed reporting of mouse events on X11 when scale_factor was not 1.0

### CODE REVIEW

**Comment by wezm** [comment]
'@cla-bot check

**Comment by mikayla-maki** [comment]
Looks like this needs a `cargo fmt` :)

**Comment by wezm** [comment]
> Looks like this needs a `cargo fmt` :)

That's weird. I already formatted it before opening the PR and `cargo fmt` doesn't make any changes. What version of Rust is the CI using?

**Comment by mikayla-maki** [comment]
I am unsure, but this PR is also now conflicting!

**Comment by mikayla-maki** [comment]
Since it's been about week with no movement here, I'm going to close this one for now! I'll probably use it for reference though :)

**Comment by wezm** [comment]
Oh looks like I missed the comment from 5 days ago (including the Easter break). I hope you're able to incorporate a similar fix soon.

**Pull request closed without merging**
