### PR TITLE
git: Append (You) to git blame author

### LINKED ISSUE #10557: Inline git blame author (you logic)
### Check for existing issues

- [X] Completed

### Describe the feature

Would be neat if the newly merged inline git blame could show "You" instead of your username if it is in fact you that is to blame. Just easier/faster to recognise at glance.

### If applicable, add mockups / screenshots to help present your vision of the feature

CleanShot 2024-04-15 at 16 00 07@2x

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
This commit suffixes (You) to the git blame author if `git config user.name` is same as author name `get_git_user_name` fetches user.name, behaviour is controlled by the setting `git.inline_blame.author_display`

`for_path` method is modified to replace author name with the appropriate string.

Closes #10557 

Release Notes:

- Improved git blame author display to show (You) on author's machine controlled via the setting `git.inline_blame.author_display`

My Commit shows as `... (You)`

image

...Rest doesn't

image

### CODE REVIEW

**Comment by maxdeviant** [comment]
Could you please include a screenshot of this change?

**Comment by HarshNarayanJha** [comment]
Ah, right! I clicked but forgot to post 😝

**Comment by HarshNarayanJha** [comment]
> Okay so what about adding a config option to show
> 1. Author
> 2. Author with You
> 3. just You

_Originally posted by @HarshNarayanJha in https://github.com/zed-industries/zed/issues/10557#issuecomment-2495843272_

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I’m personally not a fan of this. I think having the “You” is unnecessary and adds extra noise.

If we do want to add this, it will need to be behind a setting that is disabled by default.

**Comment by HarshNarayanJha** [comment]
> If we do want to add this, it will need to be behind a setting that is disabled by default.

That is what I suggested in the issue thread. I will add a config option under `git.inline_blame`  named `author_format` with values
- `author`
- `you`
- `author (you)`

with

```json
{
	"git": {
		"inline_blame": {
			"author_format": "author"
		}
	}
}
```

Being the default.
Suggestions for better config names are open. Also, is it better to put it under `inline_blame`, since it won't show up only in inline blame, but everywhere in the blame.

I will suggest changing the format a little bit to better clarify things up.

```json
{
	"git": {
		"blame": {
			"inline": {
				"enabled": true,
				"delay_ms": 500,
				"show_commit_summary": true
			}
			"author_format": "author (you)"
		}
	}
}
```

**Comment by HarshNarayanJha** [comment]
So it seems like I can't read setting from the `git` crate.

I had to go up to `crates/git/src/repository.rs` and modify the `blame` fn on `GitRepository` to accept an `author_display_replace: Option<&str>` and pass to the `crate::blame::Blame::for_path(` call, and `for_path` now uses this replacement option &str to handle replacements.

The repository receives that str from `crates/project/src/buffer_store.rs`'s `repo.blame` call.

Now, here is the problem with the current implementation. The settings work as intended, default being the only author display. But changing the setting in the file doesn't update the blames immediately, but only after I toggle inline blame.

I think this is because of how I read the setting.

https://github.com/HarshNarayanJha/zed/blob/4d4aec2420fe03a3e8daf575f160adc04c872e78/crates/project/src/buffer_store.rs#L1129-L1149

Please check @maxdeviant

**Comment by HarshNarayanJha** [comment]
I understand

**Pull request closed without merging**
