### PR TITLE
Do not format or fully save non-dirty buffers

### LINKED ISSUE #9475: Saving multi buffer should only touch modified files
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if this is a 'bug'.

Now saving a multi buffer will save all the related buffers / files. 

This will cause some unexpected behaviors. Supposed there are 10 buffers there (created by project search), and only 2 are modified, the other 7 buffers will also be saved. If "format on save" option is on, those 7 buffer will also be formatted even if they are not modified.

Moreover, even one do nothing on the any of the search results and simply press "save" shortcut, the buffers will still be touched and saved.

### Environment

Zed: v0.127.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Fixes https://github.com/zed-industries/zed/issues/9475

Release Notes:

- Start skipping formatting and actual FS saving for non-dirty buffers ([9475](https://github.com/zed-industries/zed/issues/9475))

### CODE REVIEW

**Comment by porsager** [comment]
Is this live in the current preview version? I think it is what is causing issues with some of my development tools that relies on a file being saved (fs change watching) even though the content is the same.

I can see the idea in not doing work that seems unnecessary, but this is a difference from how other editors behave and will clash with expectations made by other tools.

Could it maybe be implemented as a setting that can be enabled for for those who want it?

This comment is only related to FS saving, not formatting.

**Comment by SomeoneToIgnore** [comment]
Oof, sorry for breaking your workflow.

I am still not certain if adding such setting is a good middle ground: e.g. when some search multibuffer with 5_000 entries will get a save, should we really even try to save anything beyond the dirty excerpts?

> this is a difference from how other editors behave

Could you give an example of any other editor that's allowing to save the search results and does that even for unchanged excerpts? 
I have always thought that Zed's multibuffer is somewhat unique so no real expectations are there yet — but seeing real life examples of editors re-saving non-dirty entities is interesting to see.

**Comment by porsager** [comment]
Oh - is this only for search buffers? I am experiencing it with open files.

For search buffers I indeed would think it only saved dirty ones.

**Comment by SomeoneToIgnore** [comment]
Oh, I see: you would want to save the singleton buffers too and that does not work now?

My main goal was to avoid re-saving extra things in the multi buffers, but I have no strong preference over the singleton ones, let me come back to you tomorrow with the fix.

**Comment by porsager** [comment]
Right. I'm referring to the simple case of pressing cmd+s while editing a single file (which is what I assume you refer to as a single buffer?)

The specific case is for tools watching files to trigger various actions (refresh browser, rebuild, retest etc) which you want to trigger by saving the file, even if there are no changes to it. This is really useful for quickly triggering actions in external tools directly during editing in zed.

**Comment by SomeoneToIgnore** [comment]
Thank you now I've realized the context better, and definitely it should be the way it used to be: crated the https://github.com/zed-industries/zed/pull/10174 and will cherry-pick it into the Preview to deliver with the next patch release (if happens).

**Pull request merged**
