### PR TITLE
Adjust erf estimation function

### PR DESCRIPTION
**Pull request by phungleson**
Release Notes:

- Fixed a (potential) small error in erf estimation. Technically, the error is negligible.

I am not sure where the current calculation for erf come from and if it is intended or a simple mistake. However it looks slightly different from the official calculation, notably [this](https://en.wikipedia.org/wiki/Error_function#Approximation_with_elementary_functions) from Wikipedia.

I will add a comment if it is intended.

### CODE REVIEW

**Comment by phungleson** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Looks like it was introduced in: https://github.com/zed-industries/zed/commit/666b134d2067d4f1bb153908230e3e8e69d86535

I think this is the original source (CC0):
https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/

**Comment by mrnugget** [comment]
Did you test this manually? Are there any visible changes?

**Comment by mrnugget** [comment]
Is the positioning different then or is that due to the screenshots?

**Comment by mrnugget** [comment]
Okay, thanks! Then let's go with that

**Pull request merged**
