### PR TITLE
file_finder: Display file icons

### PR DESCRIPTION
**Pull request by Daste745**
This PR adds file icons (like in tabs, the project panel and tab switcher) to the file finder popup.

It's similar to [tab_switcher icons](https://github.com/zed-industries/zed/pull/17115), but simpler, because we're only dealing with actual files.

Release Notes:

- Added icons to the file finder.

Screenshot:
image

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Thanks for the PR!

We'll need a setting for this, the way we do for our other icons.

**Comment by Daste745** [comment]
> We'll need a setting for this, the way we do for our other icons.

For sure, I'll add a new `file_finder` settings object and a `file_icons` boolean. Should we default it to `true` or `false`?

**Comment by maxdeviant** [comment]
> > We'll need a setting for this, the way we do for our other icons.
> 
> For sure, I'll add a new `file_finder` settings object and a `file_icons` boolean. Should we default it to `true` or `false`?

Let's make it default to `true`, as that's what our other icon settings do.

**Review by maxdeviant — APPROVED** [review]
This is great, thank you!

**Pull request merged**
