### PR TITLE
Replace `CADisplayLink` with `CVDisplayLink`

### PR DESCRIPTION
**Pull request by as-cii**
Release Notes:

- Fixed a bug that caused Zed to render at 60fps even on ProMotion displays.
- Fixed a bug that could saturate the main thread event loop in certain circumstances.

### CODE REVIEW

**Comment by mrnugget** [comment]
@RemcoSmitsDev it could be! Try the latest release, we put the fix in `Zed 0.121.7`: https://zed.dev/releases/stable

cc @bennetbo 😄 we did it!

**Comment by RemcoSmitsDev** [comment]
> @RemcoSmitsDev it could be! Try the latest release, we put the fix in `Zed 0.121.7`: https://zed.dev/releases/stable
> 
> 
> 
> cc @bennetbo 😄 we did it!

I just updated to the latest preview version and it still happens.

**Comment by as-cii** [comment]
It actually makes sense that the frame rate drops when no input occurs, we're not producing any new frames because nothing changed on screen and we wanna save battery.

**Comment by mrnugget** [comment]
Oh, yes, that. I misunderstood. @RemcoSmitsDev take a look at this video: you can see that if there is something to do, things are rendered, blue line moves. But at the end, I'm just not doing anything, and rendering stops.

https://github.com/zed-industries/zed/assets/1185253/a47d4b7f-6d64-4e9a-8b45-34156322e69c


If I do that on a 60hz display it looks exactly like in your video.

**Comment by RemcoSmitsDev** [comment]
> Oh, yes, that. I misunderstood. @RemcoSmitsDev take a look at this video: you can see that if there is something to do, things are rendered, blue line moves. But at the end, I'm just not doing anything, and rendering stops.
> 
>  screenshot-2024-02-09-10.55.13.mp4 
> If I do that on a 60hz display it looks exactly like in your video.

Okay, makes sense, thanks! But I'm not sure if it's clear on my video, but when I hover over an identifier the popup keeps open until I click somewhere or hover over a new identifier. This happens only on the preview build.

https://github.com/zed-industries/zed/assets/62463826/5efcc449-60b5-4e92-a855-93c2ab500356

**Comment by as-cii** [comment]
That seems like a regression unrelated to these changes, as this pull request was hotfixed to stable. I know we recently changed our handling of mouse events on the editor to support clicking on links, maybe @ConradIrwin knows more about this?

Either way, would you mind opening a new issue and tagging it as “regression”? Thanks!

**Comment by RemcoSmitsDev** [comment]
> That seems like a regression unrelated to these changes, as this pull request was hotfixed to stable. I know we recently changed our handling of mouse events on the editor to support clicking on links, maybe @ConradIrwin knows more about this?
> 
> Either way, would you mind opening a new issue and tagging it as “regression”? Thanks!

Sure, made the issue: #7670

**Pull request merged**
