### PR TITLE
extensions: Add Ruff extension

### PR DESCRIPTION
**Pull request by osiewicz**
To install Ruff extension, open command palette (`cmd-shift-p` on mac), search for `zed: extensions` and then in the search bar of the extensions view type in `Ruff`.
Release Notes:

- Added extension for [Ruff](https://docs.astral.sh/ruff/), an extremely fast Python linter and code formatter, written in Rust.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Extension is working like a champ for me, once I disabled `pyright` in my config:

```jsonc
{
  "languages": {
    "Python": {
      "language_servers": ["!pyright", "ruff"]
    }
}
```

**Comment by code-yeongyu** [comment]
Hi. I don't think the formatting is not working properly. Is there anything that I need to set more?

**Comment by osiewicz** [comment]
That's still in progress. Right now there's no way to use a non-primary language server for formatting. It should be possible by our next update on Wednesday.

**Comment by code-yeongyu** [comment]
> That's still in progress. Right now there's no way to use a non-primary language server for formatting. It should be possible by our next update on Wednesday.
> 
> This however did not block releasing the extension itself, as setting up Ruff is independent from how Zed chooses a language server to format your code.

I didn't know there were such limitations. I currently have my zed config set up as follows to use the ruff format.

```json
{
  "languages": {
    ..., // other languages
    "Python": {
      "format_on_save": {
        "external": {
          "command": "python",
          "arguments": [
            "-m",
            "ruff",
            "format",
            "-"
          ]
        }
      }
    }
  }
}
```

I think it can be introduced in the Python guide documents along with the extension. I made a PR for it: https://github.com/zed-industries/zed/pull/14896

**Comment by osiewicz** [comment]
Thank you so much!

**Comment by failable** [comment]
Can I use `ruff` with the default LSP? I can't get completions if I enable the `ruff` extension.

**Comment by osiewicz** [comment]
Yes, you can; `Ruff` doesn't provide completions, so by disabling `pyright` and using just `ruff` you won't get them.
You shouldn't have to put anything in your Python config, or you can do:
```
{
  "languages": {
    "Python": {
      "language_servers": ["pyright", "ruff"]
    }
}
```
But that's the default.

**Comment by failable** [comment]
@osiewicz Ah, thanks. After some restarting it seems to work now.

**Comment by rgbkrk** [comment]
Updated my comment from earlier so that people don't disable `pyright`.

**Comment by Fingel** [comment]
I'm a little confused as to what this extension actually does. The docs still say we need to add the external formatter config to our settings. Does this just install ruff if it isn't present?

**Comment by rgbkrk** [comment]
It was showing up with Code Actions before:

image

There are some fixes coming to `ruff` that we need for the extension, which should be part of their release next week. We'll post updates next week.

**Comment by rgbkrk** [comment]
@Fingel -- I just realized, you probably need to upgrade your version of `ruff` if you have it installed globally `pip install --upgrade ruff` (or however you originally installed it). Previous versions of `ruff` required a `--preview` flag that we no longer supply with the newer versions.

**Comment by Fingel** [comment]
> @Fingel -- I just realized, you probably need to upgrade your version of `ruff` if you have it installed globally `pip install --upgrade ruff` (or however you originally installed it). Previous versions of `ruff` required a `--preview` flag that we no longer supply with the newer versions.

That makes sense!
What is the recommended way to install ruff for use with Zed? Install system wide, in the project's virtualenv, or do we let the zed extension install it? Thanks!

**Comment by jansol** [comment]
> What is the recommended way to install ruff for use with Zed? Install system wide, in the project's virtualenv, or do we let the zed extension install it?

Whichever suits you best. System-wide is often the easiest and safest option, but if you want to keep your system environment clean a per-project virtualenv should be a great option as well. (Or a Nix flake, if you are familiar with them.)

Letting the zed extension download it is fine if the upstream project publishes prebuilt binaries for your platform on github (and you trust both them and the extension enough to just let the extension blindly download it). Personally I'm not a fan of this approach, but many people greatly appreciate the effortlessness of it, so as long as they understand the risks involved more power to them.

**Comment by Fingel** [comment]
> > What is the recommended way to install ruff for use with Zed? Install system wide, in the project's virtualenv, or do we let the zed extension install it?
> 
> Whichever suits you best. System-wide is often the second easiest and safest option, but if you want to keep your system environment clean a per-project virtualenv should be a great option as well. (Or a Nix flake, if you are familiar with them.) The version available in your system package manager may not be as up to date as the other options, though.
> 
> Letting the zed extension download it is fine if the upstream project publishes prebuilt binaries for your platform on github (and you trust both them and the extension enough to just let the extension blindly download it). Personally I'm not a fan of this approach, but many people greatly appreciate the effortlessness of it, so as long as they understand the risks involved more power to them.

I'd be fine with the Zed extension handling it all. But to get formatting to work (at least for now) you need to specify an executable. I'm not sure how smart Zed's Python handling is, but ideally it could run binaries from the project's Virtualenv. That doesn't seem to be the case (yet) so it's looking like global installation is the way.

**Pull request merged**
