### PR TITLE
Restore crates/zed dependency on libc

### PR DESCRIPTION
**Pull request by cole-miller**
This somehow got lost during or after merge of #22202.

Release Notes:

- N/A

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Why is this needed?

This was changed in https://github.com/zed-industries/zed/pull/22335/files#diff-315ed179e69e42c0a098166a7faa7899838376c2649c84fa8cb66643f3813a45

**Comment by cole-miller** [comment]
It's used here: https://github.com/zed-industries/zed/blob/a0e4464a3399f93d498e39b1941dcf39f2514891/crates/zed/src/reliability.rs#L143

**Comment by cole-miller** [comment]
Yeah, indeed! I didn't notice until CI for #22350 unexpectedly failed.

**Comment by Rusydy** [comment]
I got an issue of dependency on `libc` in my local

**Comment by cole-miller** [comment]
@Rusydy can you give a bit more detail?

**Pull request merged**
