### PR TITLE
Enhanced support for the Claude Sonnet model in the Copilot Chat feature

### PR DESCRIPTION
**Pull request by arshadbarves**
This pull request introduces new roles and models to the `copilot_chat` module and updates the `LanguageModel` implementation to support these additions. The most important changes include adding a new role, several new models, and updating the `Model` enum and its associated methods to handle these new models.

### New Roles and Models:

* Added a new role `Tool` to the `Role` enum in `crates/copilot/src/copilot_chat.rs`.

* Added new models `O1Preview`, `O1Mini`, and `Claude3_5Sonnet` to the `Model` enum in `crates/copilot/src/copilot_chat.rs`.

### Updates to Model Enum:

* Updated the `impl Model` block to include the new models in the `from_str` method.
* Updated the `impl Model` block to include the new models in the `to_string` method.
* Updated the `impl Model` block to include the new models in the `display_name` method.
* Updated the `impl Model` block to include the new models in the `max_tokens` method.

### Language Model Implementation:

* Updated the `impl LanguageModel for CopilotChatLanguageModel` block to map the new models to their corresponding `open_ai::Model` variants in `crates/language_model/src/provider/copilot_chat.rs`.

### CODE REVIEW

**Comment by arshadbarves** [comment]
The O1 models do not currently support streaming functionality, as I plan to incorporate this feature later.

**Comment by arshadbarves** [comment]
@cla-bot check

**Comment by SirSilver** [comment]
There is existing [#19968](https://github.com/zed-industries/zed/pull/19968)

**Comment by arshadbarves** [comment]
Closing #19968

**Pull request closed without merging**
