### PR TITLE
Allow overriding all language server command through env vars

### PR DESCRIPTION
**Pull request by maan2003**
Example: ZED_GOPLS_PATH=/path/to/gopls, this can even override extension language server binary

Release Notes:

- Language server path can now be overridden using environment variables.

### CODE REVIEW

**Comment by maan2003** [comment]
thoughts @jcdickinson

**Comment by mrnugget** [comment]
Why not use the settings.json? Or why not modify `PATH` so that the desired `gopls` is first in `PATH`? The latter seems more elegant than introducing an env var for every language server.

**Comment by maan2003** [comment]
from previous PRs like https://github.com/zed-industries/zed/pull/17494 looks that has to be added per language/extension. this is like a big hammer.

**Comment by mrnugget** [comment]
Sure, but I think we can still fix this in a better way than one env var per language server, if there is an env var that's specifically made for this — `PATH` :)

**Comment by maan2003** [comment]
I don't know of a good way of mapping lsp adapter to binary name.

**Comment by maan2003** [comment]
This will likely be solved properly with disable downloads issue.
This works well enough, and I can use this patch locally till then.

**Pull request closed without merging**
