### PR TITLE
Fix fifo files hanging the project wide search

### PR DESCRIPTION
**Pull request by SultanTanirkul**
Release Notes:

- Fixed the issue related to the project wide search being stuck when project contains .fifo files
- Might potentially solve the following issue https://github.com/zed-industries/zed/issues/7360

### CODE REVIEW

**Comment by SultanTanirkul** [comment]
@cla-bot check

**Comment by ConradIrwin** [comment]
@SultanTanirkul Thanks for this!

I am worried that stat'ing each file during search will make the common case where there are no fifo's slower. Can we update the worktree Entry to have the `is_fifo` status instead so we can skip without hitting the filesystem in that case?

**Comment by SultanTanirkul** [comment]
@ConradIrwin Thanks for reviewing the code.  I agree with you. I have added `is_fifo` flag to `Entry` and removed stat'ing of each file during search.

**Comment by ConradIrwin** [comment]
Thanks! Looks like we need to skip the check on windows, but otherwise this looks good to me.

**Comment by SultanTanirkul** [comment]
@ConradIrwin added a conditional compilation to resolve the issue. Tested locally on both windows and linux. Should be passing now

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
