### PR TITLE
Scroll project search results to the top

### LINKED ISSUE #8237: Search result may need to scroll to the top after they are searched
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm not sure if it's a bug, but when I'm using it, I'll find that if there are fewer results per search, and the screen scrolls in the previous search, then I can only see blank space after each search, and I need to manually scroll to see the results, and if this does need to scroll to the top, I can submit a PR for it

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/17105034/543f5aae-c475-44fd-adbd-223dbed2d2ff

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by alygin**
Scroll project search results to the top after every new search.

Related issues:

- Fixes #8237

Release Notes:

- Fixed autoscrolling of the project search results.

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you, works like a charm.

I do not insist on that, but would appreciate the attempt to make a test: 
* we have a way to query all editor text https://github.com/zed-industries/zed/blob/cf3b875922600d97d539e6a1c3f2db2bf5af474b/crates/search/src/project_search.rs#L2679-L2685
* we can(?) access the scroll manager as in https://github.com/zed-industries/zed/blob/cf3b875922600d97d539e6a1c3f2db2bf5af474b/crates/editor/src/editor.rs#L3101 and try to see what's actually visible

Maybe it's even simpler, given that all we need to check is that we've scrolled back to the very beginning.

**Comment by alygin** [comment]
> would appreciate the attempt to make a test

Sure, I'll give it a try. In such a test, I expect difficulties with reproducing the bug first, because it depends on the previous user behaviour. At least I had to do some preliminary steps manually for the bug to manifest itself. But I think it should be doable.

**Comment by SomeoneToIgnore** [comment]
For me that was reatively simple: fire a project search, scroll down to the lowest point (can be emulated with SelectPrev action, presumably?) and fire another search in the same window (tests do that already?).

But I agree it might be hard to write such test, so let's merge this PR after you fail to do so and come back with the details of the failure 🙂

**Comment by alygin** [comment]
> For me that was reatively simple: fire a project search, scroll down to the lowest point (can be emulated with SelectPrev action, presumably?) and fire another search in the same window (tests do that already?).

I don't know why, but sometimes it's not enough to just scroll down, it reproduces very inconsistently. Sometimes it's not happening at all for a long period, and I have to restart Zed to "break" it again.

> But I agree it might be hard to write such test, so let's merge this PR after you fail to do so and come back with the details of the failure 🙂

Sounds like a good plan :)  I'll be back.

**Comment by alygin** [comment]
@SomeoneToIgnore , I have this test. It passes. But it also passes if I remove that `editor.scroll(...)` in the main code. The problem is that I can hardly reproduce the problem on my computer (it's 1 in several dozens attempts), and I don't understand if the test is incorrect, or the erroneous behaviour depends on something else that the test doesn't do.

I also don't understand what window size I have in the test, and if it can affect the test.

**Comment by SomeoneToIgnore** [comment]
Thank you for coming up with the test nonetheless!
It does look good logically (as the change is too) and seems to work for me on the branch, at least.

Now, retesting the latest Preview, the bug also appears quite randomly — so it might be more than the screen size.
I would blame the multibuffer events, but do not have a good proof.
If you want to look at the screen size more, here's the place: https://github.com/zed-industries/zed/blob/48aba8eb4c147d8644a1fe3c13c39adaffc32773/crates/gpui/src/platform/test/display.rs#L19

But we have everything what we need here thanks to you, so let's merge.

**Pull request merged**
