### PR TITLE
windows: Fix runtime `BorrowMutError`

### LINKED ISSUE #10884: [GPUI] [Windows] Panic when opening more than one window
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening more than one window using `cx.open_window` when there is already a open window causes a panic in GPUI.

Panic:
`
thread 'main' panicked at C:\Users\Matin\.cargo\git\checkouts\zed-23861290b5d2093f\ae3c641\crates\gpui\src\platform\windows\window.rs:956:44:
already borrowed: BorrowMutError
`

### Environment

Environment details aren't really important since this is a issue in GPUI.

Zed: v0.133.0 (Zed Dev ae3c641bbee2029fb4588d008e45ddb783593622)
OS: Windows 10.0.22631
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### LINKED ISSUE #11192: Zed Crashes After a minute or two on Windows 11
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Once compiled for Windows 11, Zed crashes after a minute or two. I could be writing for example the settings file and it would randomly crash on me. Happened on both Release and Debug builds.

### Environment

Zed 0.134.0.0
Windows 11 22H2 22621.3447

Type: Laptop
Manufacturer: ASUS
Mode: TUF FX506HF
CPU: Intel Core i5-11400H
GPU1: Intel UHD Graphics
GPU2: NVIDIA GeForce RTX 2050
RAM: 32 GB
Storage: Intel 670P Series 512GB + Crucial P3 1TB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15155539/Zed.log)

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #10884 #11094 

Possibly closes #11192 

https://github.com/zed-industries/zed/assets/14981363/91b1af73-8896-4988-8205-2950ecbf77e1

Release Notes:

- N/A

### CODE REVIEW

**Comment by 1982FenceHopper** [comment]
#11192 Not resolved. Crash continues even after fix by @JunkuiZhang 

Log: 
[zed.log](https://github.com/zed-industries/zed/files/15205971/zed.log)

**Comment by JunkuiZhang** [comment]
> #11192 Not resolved. Crash continues in same manner even after fix by @JunkuiZhang
> 
> Log: [zed.log](https://github.com/zed-industries/zed/files/15205971/zed.log)
> 
> EDIT: Wording mistake.

The log file #11192 attached indicates that crash was caused by `BorrowMutError`, which should be fixed by this PR. The new log file you attached indicates that the crash reason is `ERROR_OUT_OF_POOL_MEMORY`, which is an issue on the blade side. And I have no idea what causes the crash, there is an open issue #10018 here.

**Comment by mikayla-maki** [comment]
I seem to have botched the merge, I'll fix it and merge this later today :)

**Comment by mikayla-maki** [comment]
That said, I'm wondering if this PR can be superseded by https://github.com/zed-industries/zed/pull/11393, as both seem to be related to state management improvements. Spawning the task is ok if that's what we need to do, but in principle I'd prefer closer state management.

**Comment by JunkuiZhang** [comment]
> That said, I'm wondering if this PR can be superseded by #11393

Oh yes. I have merged the changes from this PR into #11393 , so this PR can be closed.

> Spawning the task is ok if that's what we need to do, but in principle I'd prefer closer state management.

I'm not exactly sure what happened behind the scenes, but the implementation on macOS is also achieved through spawning tasks, and removing it would result in the same `BorrowMutError`. Therefore, I suspect it might be an issue with Zed's deeper-level implementation.

**Comment by mikayla-maki** [comment]
ahhh, I see. Thank you!

**Pull request closed without merging**
