### PR TITLE
Windows: IME support

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Waiting for #9180 to be merged.

The behavior of IME windows is consistent with VS Code.

https://github.com/zed-industries/zed/assets/14981363/14913219-7345-4fec-9cc5-623d0c60acc9

Release Notes:
- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
@kazatsuyu Can you try this PR? I noticed that your IME window is some vertical form, I wonder if this PR fits your IME inputs.

**Comment by kazatsuyu** [comment]
@JunkuiZhang My IME popup went to bottom-left of display
image

**Comment by JunkuiZhang** [comment]
@kazatsuyu That's the default position, which means `ImmSetCompositionWindow` dose not work for your IME inputs.

Where can I download your input method? I wanna try to test it and make it working.

**Comment by kazatsuyu** [comment]
@JunkuiZhang My input method is Microsoft IME. So you can install it in system settings.

**Comment by JunkuiZhang** [comment]
@kazatsuyu I guess we are ok now.


https://github.com/zed-industries/zed/assets/14981363/e75a289d-7938-41da-9d38-f70c91a0ba84

**Comment by JunkuiZhang** [comment]
@mikayla-maki Is there a way that I can change the position of the caret?

Please note in the video, as I press the left and right keys, the caret moves left and right within the composing string.


https://github.com/zed-industries/zed/assets/14981363/e5660201-6eef-46f6-b060-38cb293b09f5

**Review by mikayla-maki — APPROVED** [review]

**Pull request merged**
