### PR TITLE
windows: [WIP] A DirectX 11 backend prototype

### PR DESCRIPTION
**Pull request by JunkuiZhang**
I've recently been working on migrating `Zed`'s implementation on Windows to `DirectX 11` and I need your suggestions and advices to decide whether to continue.

### Why Migrate to `DirectX`?
We already have a `Vulkan` backend implementation, so why go through the effort of migrating to `DirectX`? Migrating to `DirectX` brings several benefits, such as:
- Support for transparent backgrounds
- Minimal memory usage
- Using DirectX can help fix issues like `NoSupportedDeviceFound` encountered with Vulkan. I think DirectX has better compatibility. Even if you don't have a hardware GPU driver, you can still use the software driver provided by Windows.

### Why Use `DirectX 11` Instead of `DirectX 12`?
`DirectX 12` is complex and challenging. Many things require manual management, including switching the backbuffer after presenting the buffer and handling both resource and hardware synchronization yourself. Furthermore, `DirectX 11`'s performance is not that bad, as demonstrated by games like CS:GO and Dota 2 which use DirectX 11. I think the effort required for `DirectX 12` does not justify the marginal performance gains.

### Memory Usage
Before this PR, `Zed` uses about 150MB memory, under this PR, `Zed` uses around 50MB.
Screenshot 2024-06-30 221900

### Transparent Background
To implement a transparent background, we need to create a swapchain using `CreateSwapchainForComposition`. I believe this is quite challenging to achieve with Vulkan.
Screenshot 2024-06-30 220318

Release Notes:

- N/A

### CODE REVIEW

**Comment by apricotbucket28** [comment]
This is really cool! I'm not from the Zed team and I mainly use Linux, but I wanted to give some thoughts.

- Using Vulkan exclusively is probably a bad idea, there are lots of issues like https://github.com/zed-industries/zed/issues/8168 that are caused because a lot of setups don't support Vulkan.
- OpenGL ES is supported by Blade, but it can't be dynamically selected (https://github.com/kvark/blade/issues/130) and I get it's still not ideal on Windows.
- From what I get, Kvark has talked with the Zed team and they've got a shared understanding and vision on the Blade renderer.
- The Zed team probably doesn't want to maintain a third renderer (there's already Metal and Blade), and a [similar PR](https://github.com/zed-industries/zed/pull/9118) has been closed in the past.

> Before this PR, Zed uses about 150MB memory, under this PR, Zed uses around 50MB.

Wow, that's a huge difference. It seems like there's room for optimization inside Blade.

<hr />
IMO there are probably better paths to take here for the sake of maintainability:

1. Add the DirectX 11 renderer directly into Blade
2. Code a OpenGL ES renderer using e.g. the [glow](https://crates.io/crates/glow) crate and then use [ANGLE](https://github.com/google/angle/blob/main/doc/DevSetup.md#to-use-angle-in-your-application) to emulate the GLES calls with the platform native API (i.e. DirectX 11, Metal, OpenGL or Vulkan)

**Comment by mikayla-maki** [comment]
Unfortunately, I don't think this is something we're interested in merging as we don't have the capacity to support Windows developers yet. I'd suggest seeing if blade / @kvark is interested in having this as a backend :)

**Comment by mikayla-maki** [comment]
Also, I'd like to also say that it's super cool to see you diving in on this!

**Comment by kvark** [comment]
I'd like to see only a few backends supported. Previously in the GPU abstractions I worked on, such as [gfx](https://github.com/gfx-rs/gfx/) we tried to get every single graphics API. It comes with a big maintenance cost and driver headaches. For Blade, the idea is that the primary path is being optimized for: Vulkan on Linux/Windows, and Metal on Apple. And then there is a secondary path for compatibility only - this is OpenGL ES. This compatibility path is ultra portable, since, in addition to targeting Linux and Web, it can be run with Google's ANGLE (e.g. to translate to DX11).
I believe this distinction (between primary vs compatibility path) is working well, and I think we shall keep it.

@JunkuiZhang this is very big and impressive work btw!
I'd like to comment on some of the points
> Support for transparent backgrounds

We do support it in Vulkan as of #10973  

> Minimal memory usage

I love small and quick apps, and I appreciate the drive to perfection here!
There is a room for improvement with Blade on this to reduce the 150mb mark. We can tune the memory allocator, for instance, if anyone is interested. I'm more inclined to get the visual issues and latency right as I get time to contribute (e.g. #13203).

> Using DirectX can help fix issues like NoSupportedDeviceFound encountered with Vulkan

That's definitely true. Echoing @apricotbucket28, I think we should make the GLES backend work well, and we can run it on top of ANGLE on Windows.

**Comment by JunkuiZhang** [comment]
@kvark Thanks for your kind word and reply!

> > Support for transparent backgrounds
> 
> We do support it in Vulkan as of #10973

Implementing a transparent background on Windows is more complex than it seems. On Windows, achieving a transparent background involves three steps:

1. **Remove the window's default buffer**: This is easily done by specifying the `NOREDIRECTIONBITMAP` parameter when creating the window.
2. **Create a special swap chain**: Normally, we use `CreateSwapchain` to create a swap chain associated with a window, and I guess Vulkan uses a similar API. However, to create a transparent window, we need to use `CreateSwapchainForComposition`, which is currently only supported by DirectX.
3. **Associate the swap chain to the window using `DirectComposition` or `VisualLayer`**: This is another feature exclusive to DirectX.

Therefore, I think that if we want to support transparent or blurred backgrounds on Windows in the future, migrating to DirectX will eventually be necessary.

**Comment by JunkuiZhang** [comment]
> Also, I'd like to also say that it's super cool to see you diving in on this!

@mikayla-maki Thank you for your response, really happy to hear from Zed team. The HLSL files in this PR are almost copied and pasted from the Metal shaders and Vulkan's WGSL, which are amazing works implmented by the Zed team and @kvark  , I just modified some codes to fit HLSL syntax. I appreciate all your hard work. I will continue to try implement a blurred background.

**Comment by JunkuiZhang** [comment]
I just implemented blurred background on Windows with `DirectX` and `Visual Layer`:


https://github.com/zed-industries/zed/assets/14981363/1991b2bf-0779-4597-bc80-49268cbe298e

**Comment by ZeppLu** [comment]
> I just implemented blurred background on Windows with `DirectX` and `Visual Layer`:
> 
>  Recording.2024-07-04.013322.mp4

The blur looks amazing! How is it implemented, your own shader/code or Windows 11 Mica effect?

**Comment by JunkuiZhang** [comment]
> The blur looks amazing! How is it implemented, your own shader/code or Windows 11 Mica effect?

The Mica effect and Acrylic effect are XAML only features. So I use the visual layer [here](https://learn.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createhostbackdropbrush?view=winrt-26100), this is some traditional blur effect I guess, the only difference compared with Acrylic seems to be just saturaion.

**Comment by getpool** [comment]
Looking forward to updates to support low-end devices, as older devices do not support vulkan.

**Pull request closed without merging**
