### PR TITLE
Allow formatting of unsaved buffers with prettier

### LINKED ISSUE #4529: Can not format unsaved file/buffer with custom formatter
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Set an arbitrary formatter for some language in `"language_overrides"`.
2. Call the new file command to create a new file without saving it.
3. Input some unformatted content into the buffer.
4. Call the format command.

Observation: The buffer is not formatted.

### Environment

Zed: v0.100.0 (preview)
OS: macOS 13.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #4529 by allowing unsaved buffers to be formatted with prettier.

Steps to do that:

1. Create a new buffer
2. Set language for the buffer (e.g.: `language selector: toggle` and JSON)
3. In settings, set prettier parser for language (can't be inferred, since we don't have filename) and allow formatting with prettier:

   ```json
   {
     "languages": {
       "JSON": {
         "prettier": {
           "allowed": true,
           "parser": "json"
         }
       }
     }
   }
   ```

4. Use `editor: format`

Release Notes:

- Added ability to format unsaved buffers with Prettier. Requirement is to set a Prettier parser in the user settings. Example for JSON:  `{ "languages": { "JSON": { "prettier": { "allowed": true, "parser": "json" } } } }` ([#4529](https://github.com/zed-industries/zed/issues/4529)).

Demo:

https://github.com/zed-industries/zed/assets/1185253/d24e490b-2e2c-4a5d-95a8-fc8675523780

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Does this mean we should return back some form of a "default prettier parser" field in the language config to make it all ergonomic?

**Comment by mrnugget** [comment]
> Does this mean we should return back some form of a "default prettier parser" field in the language config to make it all ergonomic?

That would definitely be more ergonomic, yeah. Because it's also not enough to set the `parser`, the `enabled` is also required.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/12273

**Comment by enkr1** [comment]
how about other languages? I tried the code below but doesn't seem like working:
```json
{ 
  "languages": {
    "JSON": {
      "prettier": {
        "allowed": true,
        "parser": "json"
      }
    },
    "bash": {
      "prettier": {
        "allowed": true,
        "parser": "json"
      }
    }
  }
}
```

**Comment by mrnugget** [comment]
works for me with your config. Are you sure that you change the language of the buffer to be JSON?

https://github.com/user-attachments/assets/17372313-612d-484a-8c38-5db2b66399be

**Comment by enkr1** [comment]
i see, thanks for the video!

im curious how do we do "shift + option + F" which is a quick format shortcut (in VSC)?
image

i have tried this but doesn't seem to work

**Comment by enkr1** [comment]
https://github.com/user-attachments/assets/c8048f7b-98d7-40b0-ba22-52607035b46a

**Comment by mrnugget** [comment]
> im curious how do we do "shift + option + F" which is a quick format shortcut (in VSC)?

It's command-shift-f.

**Pull request merged**
