### PR TITLE
Add Gleam icon

### PR DESCRIPTION
**Pull request by okkdev**
I took a shot at creating an icon version of the Gleam logo in response to https://github.com/zed-industries/zed/pull/19529

Release Notes:

- Added an icon for Gleam files.

image

Screenshot 2024-10-29 at 9 46 33 AM

### CODE REVIEW

**Comment by okkdev** [comment]
@cla-bot check

**Review by lpil — APPROVED** [review]
Fantastic!!

Would be great to get this on the Gleam website too https://gleam.run/branding/

**Review by maxdeviant — APPROVED** [review]
Thank you! This should do nicely 😄

**Comment by maxdeviant** [comment]
@notpeter Since you're our active Release Tsar, could we get this cherry-picked to Preview?

**Pull request merged**
