### PR TITLE
vim: Support gn command and remap gn to gl

### LINKED ISSUE #4273: Vim: support `gn` command
### Check for existing issues

- [X] Completed

### Describe the feature

I'm enjoying Zed and the vim mode has really come a long way since the last I tried it. I've attempted switching to this as my full-time editor and finding that apparently my muscle-memory leverages vim's `gn` command extensively.

I am happy to elaborate, but VimCasts can do it more justice than I... http://vimcasts.org/episodes/operating-on-search-matches-using-gn/

Perhaps this is supported _somehow_ in Zed of which I'm not aware. Regardless, as of now it appears the default vim keymap in Zed assigns `g n` already as documented at https://docs.zed.dev/general/vim#zed-specific-features...

```
g n   Add a visual selection for the next copy of the current word
```

If the intent is to eventually, as noted in the documentation, "do what you expect", the `gn` command is one I'd expect to be present.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by Neptune650**
Release Notes:

-  Adds the `gn` command for the Vim keymap and remaps the current `gn` to `gl` ([#4273](https://github.com/zed-industries/zed/issues/4273)).

@algora-pbc /claim #4273
@algora-pbc /fixes #4273

### CODE REVIEW

**Comment by Neptune650** [comment]
@cla-bot check

**Comment by baldwindavid** [comment]
Thanks for taking a look at supporting the command. Perhaps I have something misconfigured, but I pulled down this branch and it did not seem to support much of the behavior of the command. It is posted in the original issue, but the video and show notes at http://vimcasts.org/episodes/operating-on-search-matches-using-gn/ provides the best summation of how it works.

Upon first looking it appears it only visually selects the next whole word of a search match. It should select only the "match" rather than the entire word surrounding a match as word selections are already available. It should also select the current match if already on a match or the next if not. It should support operators as the typical usage scenario is a partial word search followed by `cgn` then followed by any number of  `n`'s to select the next match and  `.`'s to perform the last operation throughout a file. I think support would also include the backwards direction as well (`gN`). Again, I'd suggest the video as it will explain much better than I can.

**Comment by Neptune650** [comment]
Thanks for reviewing the PR, in that case I'm turning this PR into a draft and working in your requests.

**Comment by ConradIrwin** [comment]
Closing this in favor of #9982

**Comment by baldwindavid** [comment]
@Neptune650 I appreciate you putting some time into this one. That bounty was awarded on the accepted PR #9982. My perception is that the bulk of the work was performed on that PR. At the same time, not trying to cause problems here so if you feel like you have a strong claim I will honor it. Let me know. Thank you.

**Pull request closed without merging**
