### PR TITLE
Change `PathWithPosition::parse_str` to support files that contain colons in filenames

### LINKED ISSUE #14100: Wrong behaviour opening file that contains colon : in filename
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a file has `:` in its filename, zed opens a new buffer instead of the file.
For example, when opening a file named `a:b.txt` it opens a new buffer named `a`.
This hapens on lastest stable v0.143.6 and master, self compiled or relaese binary.

### Environment

OS: Gentoo Linux 2.15 x86_64
CPU: AMD Ryzen 7 3700X
GPU: AMD Radeon RX 6500 XT
DE: KDE Plasma 6.1.2
WM: KWin (Wayland)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

relaese binary https://github.com/zed-industries/zed/releases/tag/v0.143.6
image

compile from master
image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-11T04:29:56+08:00 [INFO] ========== starting zed ==========
2024-07-11T04:29:56+08:00 [INFO] Opening main db
2024-07-11T04:29:56+08:00 [INFO] perform;
2024-07-11T04:29:56+08:00 [INFO] read_command;
2024-07-11T04:29:56+08:00 [INFO] read_command;
2024-07-11T04:29:56+08:00 [INFO] socket reader;
2024-07-11T04:29:56+08:00 [INFO] new;
2024-07-11T04:29:56+08:00 [INFO] keep_updated;
2024-07-11T04:29:56+08:00 [INFO] Using git binary path: None
2024-07-11T04:29:57+08:00 [INFO] extensions updated. loading 2, reloading 0, unloading 0
2024-07-11T04:29:57+08:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-11T04:29:57+08:00 [INFO] perform;
2024-07-11T04:29:57+08:00 [INFO] read_command;
2024-07-11T04:29:57+08:00 [INFO] Opening main db
2024-07-11T04:29:57+08:00 [INFO] read_command;
2024-07-11T04:29:57+08:00 [INFO] socket reader;
2024-07-11T04:29:57+08:00 [INFO] new;
2024-07-11T04:29:57+08:00 [INFO] keep_updated;
2024-07-11T04:29:57+08:00 [INFO] Enabling Vulkan Portability
2024-07-11T04:29:57+08:00 [INFO] Enabling color space support
2024-07-11T04:29:57+08:00 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/18/bin:/etc/eselect/wine/bin
2024-07-11T04:29:57+08:00 [INFO] Adapter "AMD Radeon RX 6500 XT (RADV NAVI24)"
2024-07-11T04:29:57+08:00 [INFO] Ray tracing is supported
2024-07-11T04:29:57+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:29:57+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:29:57+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-11T04:29:57+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-11T04:29:57+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-11T04:29:57+08:00 [INFO] set status on client 0: Authenticating
2024-07-11T04:29:57+08:00 [INFO] Opening main db
2024-07-11T04:29:57+08:00 [INFO] perform;
2024-07-11T04:29:57+08:00 [INFO] read_command;
2024-07-11T04:29:57+08:00 [INFO] read_command;
2024-07-11T04:29:57+08:00 [INFO] socket reader;
2024-07-11T04:29:57+08:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-07-11T04:29:57+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:29:57+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:29:57+08:00 [INFO] new;
2024-07-11T04:29:57+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-11T04:29:57+08:00 [INFO] keep_updated;
2024-07-11T04:29:57+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:29:57+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:29:57+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-11T04:29:57+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:29:57+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:29:57+08:00 [INFO] set status on client 177024: Connecting
2024-07-11T04:29:57+08:00 [INFO] Opening main db
2024-07-11T04:29:57+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:29:57+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:29:58+08:00 [INFO] Node runtime install_if_needed
2024-07-11T04:29:58+08:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-11T04:29:59+08:00 [INFO] starting language server. binary path: "/home/skye/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/skye/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-11T04:29:59+08:00 [INFO] add connection to peer
2024-07-11T04:29:59+08:00 [INFO] add_connection;
2024-07-11T04:29:59+08:00 [INFO] waiting for server hello
2024-07-11T04:29:59+08:00 [INFO] got server hello
2024-07-11T04:29:59+08:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 451, id: 5449048 })
2024-07-11T04:29:59+08:00 [INFO] set status on client 177024: Connected { peer_id: PeerId { owner_id: 451, id: 5449048 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-11T04:29:59+08:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-10T20:29:59.754Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-10T20:29:59.754Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-11T04:29:59+08:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "6d232666-e706-4ad6-a15b-0f6856d51ad6",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-11T04:29:59+08:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-10T20:29:59.773Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-10T20:29:59.773Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-07-11T04:31:56+08:00 [ERROR] window not found
2024-07-11T04:31:56+08:00 [ERROR] window not found
2024-07-11T04:32:08+08:00 [INFO] ========== starting zed ==========
2024-07-11T04:32:08+08:00 [INFO] Opening main db
2024-07-11T04:32:08+08:00 [INFO] perform;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] socket reader;
2024-07-11T04:32:08+08:00 [INFO] new;
2024-07-11T04:32:08+08:00 [INFO] Using git binary path: None
2024-07-11T04:32:08+08:00 [INFO] keep_updated;
2024-07-11T04:32:08+08:00 [INFO] extensions updated. loading 2, reloading 0, unloading 0
2024-07-11T04:32:08+08:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-11T04:32:08+08:00 [INFO] perform;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] socket reader;
2024-07-11T04:32:08+08:00 [INFO] new;
2024-07-11T04:32:08+08:00 [INFO] keep_updated;
2024-07-11T04:32:08+08:00 [INFO] set status on client 0: Authenticating
2024-07-11T04:32:08+08:00 [INFO] Opening main db
2024-07-11T04:32:08+08:00 [INFO] perform;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] read_command;
2024-07-11T04:32:08+08:00 [INFO] socket reader;
2024-07-11T04:32:08+08:00 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/18/bin:/etc/eselect/wine/bin
2024-07-11T04:32:08+08:00 [INFO] Enabling Vulkan Portability
2024-07-11T04:32:08+08:00 [INFO] Enabling color space support
2024-07-11T04:32:08+08:00 [INFO] new;
2024-07-11T04:32:08+08:00 [INFO] keep_updated;
2024-07-11T04:32:08+08:00 [INFO] Adapter "AMD Radeon RX 6500 XT (RADV NAVI24)"
2024-07-11T04:32:08+08:00 [INFO] Ray tracing is supported
2024-07-11T04:32:08+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:32:08+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:32:08+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-11T04:32:08+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-11T04:32:08+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-11T04:32:08+08:00 [INFO] set status on client 177024: Connecting
2024-07-11T04:32:08+08:00 [INFO] Opening main db
2024-07-11T04:32:08+08:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-07-11T04:32:08+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:32:08+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:32:08+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-11T04:32:08+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:32:08+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:32:08+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-11T04:32:08+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:32:08+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:32:08+08:00 [INFO] Opening main db
2024-07-11T04:32:08+08:00 [INFO] Using surface present mode MAILBOX
2024-07-11T04:32:08+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-11T04:32:09+08:00 [INFO] Node runtime install_if_needed
2024-07-11T04:32:10+08:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-11T04:32:10+08:00 [INFO] starting language server. binary path: "/home/skye/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/skye/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-11T04:32:11+08:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-10T20:32:11.636Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-10T20:32:11.636Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-11T04:32:11+08:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "6d4f1ca8-614d-432f-b11e-fcec43908aba",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-11T04:32:11+08:00 [INFO] add connection to peer
2024-07-11T04:32:11+08:00 [INFO] add_connection;
2024-07-11T04:32:11+08:00 [INFO] waiting for server hello
2024-07-11T04:32:11+08:00 [INFO] got server hello
2024-07-11T04:32:11+08:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 451, id: 5450237 })
2024-07-11T04:32:11+08:00 [INFO] set status on client 177024: Connected { peer_id: PeerId { owner_id: 451, id: 5450237 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-11T04:32:11+08:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-10T20:32:11.674Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-10T20:32:11.674Z]",
  "extra": [
    "Telemetry initialized"
  ]
}

</pre></details>

### PR DESCRIPTION
**Pull request by terziele**
Fixes #14100

Split parsing in two: 
1. Parse extension 
2. Parse filename if there is no extension

To not breaking the API on parsing an extension first two values between the colons are parsed: `test.rs:1:2:3:4` => `[test.rs, 1, 2]. Trailing values are skipped.
But for parsing filename the last  two values are used for parsing row and column, assuming that rest are the part of file's name. And in case the row value cann'ot be parsed, the column value becomes a row. This is may be tricky with , so I'll be glad to hear your feedback.

Release Notes:

- Fixed ([#14100](https://github.com/zed-industries/zed/issues/14100)).

### CODE REVIEW

**Comment by terziele** [comment]
@cla-bot check

**Comment by terziele** [comment]
@cla-bot check

**Review by osiewicz — APPROVED** [review]
LGTM (sans clippy violations)

**Comment by terziele** [comment]
Weel, it seems that with the commit here https://github.com/terziele/zed/commit/06833d7360b2c198cb43fdc7772ab2168297e6ec
 this PR may be irrelevant.

**Comment by osiewicz** [comment]
Yeah, it looks like it. We can always reopen this PR if needed though.

**Pull request closed without merging**
