### PR TITLE
Add injections for tagged template literals

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR adds syntax highlighting support for `css`, `html`, `js`, `json`, `sql`, `ts`, `yaml` and `yml` in `javascript`, `typescript` and `tsx` languages where the contents of tagged template literals are now highlighted.

This does not actually enable language features (like LSP support), it only does syntax highlighting.

Before this change:
image

After this change:
image

/cc @mrnugget 

Release Notes:

- Added syntax highlighting for tagged template literals in `javascript`, `typescript` and `tsx` languages for `css`, `html`, `js`, `json`, `sql`, `ts`, `yaml` and `yml`. ([#15984](https://github.com/zed-industries/zed/issues/15984))

### CODE REVIEW

**Comment by RobinMalfait** [comment]
This is currently a very manual and hardcoded way of the problem. I think some improvements that could be cool but not sure if that's even possible or wanted:

1. If let's say you type `ts` we have to set the language to `typescript`. If there is an alias from `ts` to `typescript` we could make it dynamic where every `name` just sets the language to that name.
   1. If the language is not found, we can always fallback to plain text which results in the same behavior as before.
3. If you add an extension, for let's say `language-foo-bar`, that you automatically get syntax highlighting support for it.

**Comment by mrnugget** [comment]
> 1. If let's say you type `ts` we have to set the language to `typescript`. If there is an alias from `ts` to `typescript` we could make it dynamic where every `name` just sets the language to that name.

Not sure, but can't you `(#set! "language" @_name)`?

**Comment by RobinMalfait** [comment]
@mrnugget aha you are right that when capturing `js` you can just set the language to `js` instead of `javascript`.

I tried doing this part: `(#set! "language" @_name)` but it won't let me highlight anything anymore, so I think it's not meant to be referenced that way.

**Comment by mrnugget** [comment]
Ah, yeah. Maybe that part is evaluated differently. I honestly think the code is fine as it is right now.

**Comment by mrnugget** [comment]
Thank you!

**Comment by affanshahid** [comment]
I suppose this still wouldn't allow a 3rd-party extension from providing their own injections, right? For example the GraphQL extension (not built in) wouldn't be able to add GraphQL syntax highlighting to TS files.

**Comment by lougreenwood** [comment]
Also would love to see `hbs` template literal support. This is the `handlebars/glimmer` template language and embedding it in template literals is used extensively in tests `Ember JS`.

Does the architecture need to hard code these, or can't it just use the appropriate syntax highlighting for the language defined for the template literal (assuming the syntax highlighting is available??

**Comment by Atom-c** [comment]
> I suppose this still wouldn't allow a 3rd-party extension from providing their own injections, right? For example the GraphQL extension (not built in) wouldn't be able to add GraphQL syntax highlighting to TS files.

I actually was going to see if I could get the `gql` included. Did you already determine this wasn't possible at current architecture, for other extension literals @RobinMalfait ?

**Comment by XiNiHa** [comment]
Do we have any reason performing manual matches here, instead of assuming the tagged template function name as a language code? That's [what tree-sitter-javascript is doing](https://github.com/tree-sitter/tree-sitter-javascript/blob/15887341e5b57ffdb423aff840aef142b8f53d6d/queries/injections.scm#L4-L12) and I guess the same could be applied as a fallback while having some exact matches in front of it.

**Comment by visnup** [comment]
For anyone wanting a no-op version of any of these tags in order to get the sweet-sweet highlighting, you can `const css = String.raw;` for whichever function you want to highlight.

Of course, there may be other packages you could use that do more, but if you just want the default template literal behavior, [String.raw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) is what you're looking for.

**Pull request merged**
