### PR TITLE
make syntax nicer - wikipedia.rs

### PR DESCRIPTION
**Pull request by Bleachfuel**
I think this makes more sense when u read from top to bottom? 

Release Notes:

- N/A

### CODE REVIEW

**Comment by Bleachfuel** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
We generally don't merge stylistic refactoring PRs like this, see our contributing guidelines for more information: https://github.com/zed-industries/zed/blob/0511768b226094a25fddb99fc6e7ef53ad220197/CONTRIBUTING.md#tips-to-improve-the-chances-of-your-pr-getting-reviewed-and-merged

**Comment by Bleachfuel** [comment]
But is it not better to have more readable code?

**Comment by maxdeviant** [comment]
> But is it not better to have more readable code?

This is subjective. I think the current code is more readable.

**Pull request closed without merging**
