### PR TITLE
Update One Light modified color

### PR DESCRIPTION
**Pull request by effdotsh**
Release Notes:

- Changed the `modified` color on the one-light color theme to a more readable value

The current color in the file tree for modified files is basically unreadable in the default light mode
image

This change just changes the color to match that of the one-light theme present in vscode
~~old proposal: https://github.com/zed-industries/zed/assets/50590465/b4dc4030-bcd8-429a-84b8-2744e213e492~~
new proposal:
image

This does have a side-effect of changing the modified color on the side in the editor, but personally I think this change is negligable.

### CODE REVIEW

**Comment by maxdeviant** [comment]
The new color looks way too dark, to me.

**Comment by effdotsh** [comment]
For reference, this is how it appears in vscode
image

but I agree it seems a bit on the dark side. Maybe taking something between the two?
image

**Comment by evrsen** [comment]
as a light mode user, this change is almost a must. but i agree the first one is a bit too dark, i like the one in-between 👍

**Comment by iamnbutler** [comment]
Apologies, I meant to get to this earlier – while I somewhat agree the color isn't great, I also recognize the current situation is worse than not great. Let's merge this change for now and I'll take another look when I get to One Light cleanup.

Thanks for the contribution! Apologies it took me this long to get to.

**Pull request merged**
