### PR TITLE
Fix index out of bounds

### LINKED ISSUE #15254: index out of bounds
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure at what action it really crashes. But it seems it happens while navigating around the code with they keyboard

### Environment

Zed: v0.147.0 (Zed Dev b7c6f3e98eb53eb516cba9bb1724ebbbf780cfd4)
OS: Linux Wayland ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.0.5-1ubuntu1

Zed: v0.147.0 (Zed Dev 745d2e4d3b4cd977de8895a18729c3e96fc190b5)
OS: Linux Wayland ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.0.5-1ubuntu1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
Thread "<unnamed>" panicked with "index out of bounds: the len is 66 but the index is 18446744073709551610" at crates/rope/src/rope.rs:678:16

### PR DESCRIPTION
**Pull request by cemoktra**
Release Notes:

- Fixed [#15254](https://github.com/zed-industries/zed/issues/15254)

### CODE REVIEW

**Comment by cemoktra** [comment]
@cla-bot check

**Comment by cemoktra** [comment]
I noticed that there might be other cases like this. But could not reproduce yet. @as-cii

**Review by SomeoneToIgnore — COMMENTED** [review]
I do not have enough context, but based on my observations of such issues before, this looks more like a masking of the problem, and the bug is somewhere below.

I might be as well wrong, but here's one solid thing: it's good to test this to avoid future regressions.
It seems that the bug occurs when a caret is placed inside a particular, whitespace-surrounded block, with the indent guides turned on.
editor_tests.rs has a bunch of tests with the caret (ˇ) and with the indent guides: https://github.com/zed-industries/zed/blob/43f407acf59d0cc13bd0d87bebe4522f6d1dbdc4/crates/editor/src/editor_tests.rs#L12506
that can serve as examples.

**Comment by cemoktra** [comment]
> I do not have enough context, but based on my observations of such issues before, this looks more like a masking of the problem, and the bug is somewhere below.
> 
> I might be as well wrong, but here's one solid thing: it's good to test this to avoid future regressions. It seems that the bug occurs when a caret is placed inside a particular, whitespace-surrounded block, with the indent guides turned on. editor_tests.rs has a bunch of tests with the caret (ˇ) and with the indent guides:
> 
> https://github.com/zed-industries/zed/blob/43f407acf59d0cc13bd0d87bebe4522f6d1dbdc4/crates/editor/src/editor_tests.rs#L12506
> 
> 
> that can serve as examples.

i agree. but due to a lack of knowledge of the full code i'm trying to fix the symptom for me here.

**Comment by SomeoneToIgnore** [comment]
This part is tough, I agree, and that's why we most probably will close the PR and let @as-cii to make a proper fix.
That's why having a test would be so useful — then we could reuse something out of the PR.

**Comment by cemoktra** [comment]
i can give you the exat code that cause problems for me:
```
pub trait Encoder {
    fn encode_u32(&mut self, data: u32);
}

impl Encoder for bytes::BufMut {
    fn encode_u32(&mut self, data: u32) {
        
    }
}
```

initially the auto generated code was ending with an empty implementation `{}`, when i pressed enter between the brackets and then moved the curser down one row it crashed

**Comment by cemoktra** [comment]
image

typing any key here also crashes

**Comment by bilelmoussaoui** [comment]
I have been getting crashes very often recently here on linux

backtrace:
```
[2024-07-26T21:14:31+02:00 ERROR theme] theme not found: Github Light
Thread "<unnamed>" panicked with "attempt to subtract with overflow" at crates/rope/src/rope.rs:677:30
   0: zed::reliability::init_panic_hook::{{closure}}
             at crates/zed/src/reliability.rs:58:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
      std::panicking::rust_panic_with_hook
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:799:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:656:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   5: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:179:21
   7: rope::Chunks::prev_line
             at crates/rope/src/rope.rs:677:30
   8: text::BufferSnapshot::reversed_line_indents_in_row_range::{{closure}}
             at crates/text/src/text.rs:2065:21
   9: <core::iter::sources::from_fn::FromFn<F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/iter/sources/from_fn.rs:69:9
  10: language::buffer::BufferSnapshot::enclosing_indent::{{closure}}
             at crates/language/src/buffer.rs:3394:30
  11: editor::indent_guides::resolve_indented_range::{{closure}}
             at crates/editor/src/indent_guides.rs:198:10
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/future/future.rs:123:9
  13: async_task::raw::RawTask<F,T,S,M>::run
             at /home/bilalelmoussaoui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:557:17
  14: async_task::runnable::Runnable<M>::run
             at /home/bilalelmoussaoui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781:18
  15: gpui::platform::linux::dispatcher::LinuxDispatcher::new::{{closure}}::{{closure}}
             at crates/gpui/src/platform/linux/dispatcher.rs:44:25
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18
  17: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:542:17
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9
  19: std::panicking::try::do_call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
  20: __rust_try
  21: std::panicking::try
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
  22: std::panic::catch_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:541:30
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
  24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys/pal/unix/thread.rs:108:17
  25: start_thread
  26: __GI___clone3
```

**Comment by SomeoneToIgnore** [comment]
The original issue had been reverted and I could not reproduce the panics for my cases: https://github.com/zed-industries/zed/pull/15282

This PR conflicts now, and is sort of obsolete, so I'll close this, thank you for the attempt.

**Comment by bilelmoussaoui** [comment]
> The original issue had been reverted and I could not reproduce the panics for my cases: #15282
> 
> This PR conflicts now, and is sort of obsolete, so I'll close this, thank you for the attempt.

Thanks a lot! I forgot to pull again & try before commenting.

**Pull request closed without merging**
