### PR TITLE
Improve editor tabs and project panel items

### PR DESCRIPTION
**Pull request by ghost**
Continuation of https://github.com/zed-industries/zed/pull/16615 and https://github.com/zed-industries/zed/pull/16671
---

#### Notes
previously, the ``git_status`` option in both ``project_panel`` and ``tabs`` settings was used to toggle git coloring, this option name is a bit misleading now with git symbols in place which are the actual statuses, so i've changed ``git_status`` to toggle the git symbols on and off instead (to avoid a breaking change). for git coloring, i've added a new option called ``git_colors`` that can be toggled.

- both ``git_status`` and ``git_colors`` default to ``true`` in both ``project_panel`` and ``tabs``.
- i've also defaulted ``file_icons`` in ``tabs`` to true for a more consistent relation with the ``project_panel``.

## Screenshot
Skärmavbild 2024-11-04 kl  19 23 43

Release Notes:

- Added git symbols to the project panel and editor tabs, the ``git_status`` option now refers to git symbols, with an added ``git_colors`` option for coloring, both are set to ``true`` by default. ([#20134](https://github.com/zed-industries/zed/pull/20134))
- Added symlink symbol to editor tabs. ([#20134](https://github.com/zed-industries/zed/pull/20134))
- Disable the dirty buffer indicators in tabs when autosave is enabled. ([#20134](https://github.com/zed-industries/zed/pull/20134))
- Improved the editor tabs layout. ([#20134](https://github.com/zed-industries/zed/pull/20134))
- Changed ``file_icons`` in ``tabs`` to default to ``true``. ([#20134](https://github.com/zed-industries/zed/pull/20134))

### CODE REVIEW

**Comment by nervenes** [comment]
cc @mrnugget @iamnbutler

**Comment by mrnugget** [comment]
Before I dive in too deep: have you seen the discussion in https://github.com/zed-industries/zed/pull/18182 on icons in the project panel?

**Comment by nervenes** [comment]
Yep, even left a comment: https://github.com/zed-industries/zed/pull/18182#issuecomment-2453602794

Though, I'm unsure what the defaults should be here?

a) VSCode-like defaults:
Skärmavbild 2024-11-04 kl  09 57 37

b) Xcode-like defaults:
Skärmavbild 2024-11-04 kl  09 56 53

The colors can be changed in the settings with:
```json
{
    "project_panel": {
        "git_status": true
    },
    "tabs": {
        "git_status": true
     }
}
```

**Review by danilo-leal — CHANGES_REQUESTED** [review]
Hey @nervenes, thanks so much for the PR! Generally speaking, though, I feel like this PR could be divided into multiple pieces for ease of discussion, review, and traceability. Also, I want to make sure https://github.com/zed-industries/zed/pull/18182 gets over the finish line before any other project panel icon-display-related PR is merged, so maybe some of the changes you're proposing here are not sequential but parallel to that. Would you mind breaking this PR up?

**Comment by nervenes** [comment]
Oh sure thing, would you like this pr to remain the project panel changes for git symbols?

**Comment by nervenes** [comment]
Now that https://github.com/zed-industries/zed/pull/18182 has been merged 🎉 i'll go ahead and close this one, i'll open a new pr for the editor tabs, i'll have to see if i can find the time to revisit git symbols in the project panel :)

**Pull request closed without merging**
