### PR TITLE
Add support for Odin

### PR DESCRIPTION
**Pull request by laytan**
Adds support for the Odin programming language, some links:

- https://odin-lang.org/
- https://github.com/amaanq/tree-sitter-odin
- https://github.com/DanielGavin/ols

Screenshot 2024-01-30 at 17 40 58

Release Notes:

- Added support for Odin.

### CODE REVIEW

**Comment by laytan** [comment]
@cla-bot check

**Comment by laytan** [comment]
@cla-bot check

**Comment by maxbrunsfeld** [comment]
Hey @laytan, this PR looks good. For right now, I would like to limit how many languages we bundle into Zed, because each one contributes to the compile time of the app on our CI servers. Because Odin is a bit more obscure of a language, I'd like to hold off on bundling it.

We are actively working on the ability for Zed to load arbitrary Tree-sitter parsers via Wasm files. It is one of my top priorities at the moment. Once that happens, we'll be able to have a Nickel plugin, and we plan to automatically surface available plugins when users are editing unsupported file extensions. You'll be able to package all of the same queries, in the same structure you've set up here.

Here is a tracking issue for our support of language extensions: https://github.com/zed-industries/zed/issues/7096. Subscribe there for updates on this. Sorry to turn away this good code.

**Comment by laytan** [comment]
@maxbrunsfeld Alright, no worries, I get it, I will use my fork in the meantime ;)

I did like the idea of the editor not requiring any config or installation which is the way it was currently, but with a good system like the one you are describing that will probably still be a smooth experience.

**Pull request closed without merging**
