### PR TITLE
Impl `prompts` and `savefile dialog` on Windows

### PR DESCRIPTION
**Pull request by JunkuiZhang**
### Description
This is a part of #8809 , and this PR dose not include `open file dialog`, as I already saw two PRs impl this.

https://github.com/zed-industries/zed/assets/14981363/3223490a-de77-4892-986f-97cf85aec3ae

Release Notes:

- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
### Potential BUG

The `directory` here:
```rust
fn prompt_for_new_path(&self, directory: &Path) -> Receiver<Option<PathBuf>>
``` 
can be empty string `""`, which is pretty similar with #8933 (as I described in #8825 ):
```rust
let cwd = TERMINAL_DB
                .get_working_directory(item_id, workspace_id)
```
here the `cwd` get empty string. 

Is this intended? or something buggy behind the scene?

**Comment by mikayla-maki** [comment]
Once this branch is up to date with main, I'd be happy to merge it.

That said, I noticed the styling on the alert window is very different from the styling used in https://github.com/zed-industries/zed/pull/8919, is there a different API we could be using that's similar to 8919?

**Comment by a-usr** [comment]
> I noticed the styling on the alert window is very different from the styling used in https://github.com/zed-industries/zed/pull/8919, is there a different API we could be using that looks similar to #8919?

Those are actuall as far as I can tell the default windows dialogs for opening a file/folder and for saving a file respectively. The drop-down Textbox below the Textbox where the name of the file goes in the "Save as" dialog is supposed to be used to pick the file extension for the file. 

Also, is there a reason as for why you are using the `FileSaveDialog` directly instead of [this function in the windows API](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getsavefilenamew)?

**Comment by JunkuiZhang** [comment]
> Also, is there a reason as for why you are using the `FileSaveDialog` directly instead of [this function in the windows API](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getsavefilenamew)?

By microsoft:
> Starting with Windows Vista, the Open and Save As common dialog boxes have been superseded by the [Common Item Dialog](https://learn.microsoft.com/en-us/windows/win32/shell/common-file-dialog).
And there are many answers in stackoverflow suggest doing so.

**Comment by JunkuiZhang** [comment]
> That said, I noticed the styling on the alert window is very different from the styling used in #8919, is there a different API we could be using that looks similar to #8919?

If you are saying the visual style diiference, it should be the difference that I use light Windows theme, tthat PR uses dark Windows theme.

**Comment by mikayla-maki** [comment]
Ahh, I see. Thanks for telling me about the platform norms @JunkuiZhang and @a-usr

**Pull request merged**
