### PR TITLE
dart: Add support for documentation comments

### LINKED ISSUE #19590: Rewrap cannot handle Dart documentation comments
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Rewrap comand correctly handles normal comments:

```dart
// blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
void main() {}
```

Converts this to:

```dart
// blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah
// blah blah blah
void main() {}
```

But if I make the comment a documentation comment, rewrap transforms it into:

```
/// blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah
blah blah blah
void main() {}
```

Without the `///` prefix.

### Environment

Zed: v0.157.5 (Zed)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by osa1**
Closes #19590

Release Notes:

- N/A
---

I'm unable to test this because rebuilding Zed with the changes does not seem to use the changes. If maintainers could let me know how to test these changes I'd like to verify that this really fixes #19590.

### CODE REVIEW

**Comment by notpeter** [comment]
Yeah, it's a little confusing, but luckily you can testing extension changes without having to rebuild Zed. 

Just opening the extensions panel (cmd-shift-x) in your normal Zed (Stable, Preview, etc) and click "Install Dev Extension", and select the `extensions/dart` folder in your Zed repo with these changes.

**Comment by osa1** [comment]
@notpeter thanks -- when I followed these steps I see a .wasm file being generated in extensions/dart, but is there a way to verify that it's being used? Either it's not being used, or this doesn't fix the bug.

**Comment by notpeter** [comment]
> @notpeter thanks -- when I followed these steps I see a .wasm file being generated in extensions/dart, but is there a way to verify that it's being used? Either it's not being used, or this doesn't fix the bug.

You could make sure by uninstalling the existing Dart Extension and temporarily modifying the version number in your branch and that version number shows up in the Extensions panel after you click "rebuild extension"

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by osa1** [comment]
Thanks for merging this. However the addition of `//` and `///` were intentional as currently Zed cannot rewrap comments like `//blah blah...` (e.g. no space between the comment start and the comment).

I guess we fix it later.

**Pull request merged**
