### PR TITLE
zig: Switch to official Zig grammar

### LINKED ISSUE #20001: investigate using a different zig treesitter grammar
### Check for existing issues

- [X] Completed

### Describe the feature

the [current zig grammar](https://github.com/maxxnino/tree-sitter-zig) only just recently started merging prs after >1 year and is effectively abandoned by the owner (see the readme). theres a new one https://github.com/tree-sitter-grammars/tree-sitter-zig which claims to be faster and generally better, though i havent really tested how true that is. im not very familiar with treesitter so its not easy for me to tell whats actually different. nvim-treesitter switched not too long ago as well https://github.com/nvim-treesitter/nvim-treesitter/pull/7097

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by xdBronch**
Closes #20001

the old outline was *weird* for many reasons so ill just show it with a hodgepodge of zig declarations
before:
image
after:
image

why were values shown? why werent `var`s or modifiers like pub, const, export? it was very odd to me and inconsistent with other languages. i chose to leave out unnamed tests, it just seemed like noise to me since they werent distinct but i can easily revert that
unfortunately there seems to be a bug upstream which causes those `t`/`f` decls to show 2 things https://github.com/tree-sitter-grammars/tree-sitter-zig/issues/3

im very new to treesitter and queries so i really havent looked over the rest of the stuff here, other than outline theyre unmodified please lmk if theres anything wrong

Release Notes:

- Changed upstream treesitter grammar for zig

### CODE REVIEW

**Comment by mrnugget** [comment]
Hey! Happy to merge this, but can you also make sure that the highlights etc. are still correct?

**Comment by xdBronch** [comment]
hmm im noticing it doesnt seem to correctly identify types if theyre behind field access e.g. `std.SomeType` but im struggling to get it working without normal field access just ending up with identifier highlighting

**Comment by xdBronch** [comment]
ive realized the way i made the outline is flawed, it makes sense for general variables imo but since types are values in zig youll just see things like `const S` or `const U` without any indicator that they're e.g. structs or unions. gonna think on it more

**Comment by xdBronch** [comment]
does `lua-match` not work in zed? i changed all of those to just `match` and it solved multiple problems i was having with highlighting

**Comment by mrnugget** [comment]
> does `lua-match` not work in zed? i changed all of those to just `match` and it solved multiple problems i was having with highlighting

No, it doesn't, we don't have Lua in Zed. `match` is built-in though.

Let me know once you're done testing/revising.

**Comment by xdBronch** [comment]
alright ive changed some stuff, im pretty happy with the highlighting. i decided to make the outline a bit more like it was before, i dont love how it looks but what i was doing before just wasnt the most helpful i dont think.

**Comment by mrnugget** [comment]
Tested it locally and it seems fine. I'm not sure whether the outline is improved though — do you think that's the case? If so, I'll merge it.

**Comment by xdBronch** [comment]
i think its a slight improvement, its about the same in most cases but it includes things like `pub` and fields which is nice imo

**Comment by mrnugget** [comment]
Alright, let's try this then! @notpeter do you handle the release of the Zig extension now or do I do that?

**Pull request merged**
