### PR TITLE
context_servers: Support tools

### PR DESCRIPTION
**Pull request by dsp-ant**
This PR depends on #19547 

This PR adds support for tools from context servers. Context servers are free to expose tools that Zed can pass to models. When called by the model, Zed forwards the request to context servers. This allows for some interesting techniques. Context servers can easily expose tools such as querying local databases, reading or writing local files, reading resources over authenticated APIs (e.g. kubernetes, asana, etc).

This is currently experimental. 

Things to discuss
* I want to still add a confirm dialog asking people if a server is allows to use the tool. Should do this or just use the tool and assume trustworthyness of context servers?
* Can we add tool use behind a local setting flag?

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxdeviant** [comment]
> * Can we add tool use behind a local setting flag?

Tool use isn't at a point where we're ready to expose it via a setting. It's just a prototype, at the moment.

**Comment by dsp-ant** [comment]
BTW I noticed that repeated tool use in the assistant panel doesn't work. I want to dig more into this, but it feels like it's a problem in context handling. I can repro it with the now tool as well.

**Comment by maxdeviant** [comment]
> * I want to still add a confirm dialog asking people if a server is allows to use the tool. Should do this or just use the tool and assume trustworthyness of context servers?

I think, for now, it's fine to assume the trustworthiness of the context server.

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
