### PR TITLE
Improve window decorations: check for compositor support

### PR DESCRIPTION
**Pull request by s3bba**
Adds the `compositor_support` to the `X11WindowState` struct so that correct window decorations are selected

Release notes:

- N/A

### CODE REVIEW

**Comment by s3bba** [comment]
@cla-bot check

**Comment by apricotbucket28** [comment]
Wouldn't it be better to copy [Chromium's logic](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_desktop_window_tree_host_linux.cc;l=195-198;drc=67d0441446c6264c2921cf5c41098e6b4db467d3)? Mainly, it also checks for support of the `_GTK_FRAME_EXTENTS` atom on the root window, which is what Zed uses to support CSD on X11.

**Comment by mrnugget** [comment]
I don't think we can do it like this.

When I run this locally, I get the following:

```
[2024-07-05T09:25:41+02:00 INFO  gpui::platform::linux::x11::window] Compositor support: false
```

but I also don't get server-side decorations:

image

I can dig into this.

But: client-side decorations worked fine for me.

Which problem for you is this check solving?

**Comment by s3bba** [comment]
@mrnugget Yeah I agree, I'm not super familiar with X11, I just run my desktop on it.

Why is this needed? If system does not have a compositor and client-side decorations are sent window gets black borders, rounded corners and window management buttons, like so:
image

**Comment by mrnugget** [comment]
> Why is this needed? If system does not have a compositor and client-side decorations are sent window gets black borders, rounded corners and window management buttons, like so:

So what does it look like with your PR here? What's the ideal outcome?

(I'm asking because I think we also want to make it configurable whether you have window decorations on/off — via an env variable for example — and I'm wondering whether that also won't fix your problem)

**Comment by s3bba** [comment]
> So what does it look like with your PR here? What's the ideal outcome?

It looks identical to zed before https://github.com/zed-industries/zed/pull/13611 PR was merged:
image
Also I think I should point out, I didn't mess with any decoration logic. So if server decorations are not working for you my PR *shouldn't* be the reason (then again X11 is a magic black box)

> (I'm asking because I think we also want to make it configurable whether you have window decorations on/off — via an env variable for example — and I'm wondering whether that also won't fix your problem)
Yeah, I'm with you on this one, I would still add the check if compositor is supported because it makes the whole experience way more polished. 

But, this applies only if we can detect this reliably - which is currently clearly not, I need to look into chromium internals to see how they check it.

**Comment by mrnugget** [comment]
> So if server decorations are not working for you my PR _shouldn't_ be the reason (then again X11 is a magic black box)

No, I think it's more that we need to tell the framework, gpui, when client-side decorations aren't working.

**Comment by s3bba** [comment]
> No, I think it's more that we need to tell the framework, gpui, when client-side decorations aren't working.

Ah okay, I assumed this is done with the return value of `window_decorations` function https://github.com/zed-industries/zed/pull/13822/files#diff-5ddf506fd5f49b8cdc4c75cb73aec925240e33d87c197ec0a0d6bf5aefdf5898R1200

**Comment by mrnugget** [comment]
@s3bba I pushed a commit that moves the code to the client (so we only check once) and also internally stores the actual decorations that are used.

Most importantly: I extended the checks for the compositor. I have barely any clue what I'm doing there though, so: what do you get in the logs when you run this? Ideally we'd only have a single check for the compositor, but I'm not sure which of the three is the most reliable.

On my machine, method 3 returns `true`, so client-side decorations work for me.

**Comment by mrnugget** [comment]
Relevant: https://github.com/zed-industries/zed/pull/13866

**Comment by mrnugget** [comment]
Okay, I tried this in i3 and the checks return `false, false, true` and it looks bad. I think what @apricotbucket28 suggested, to check whether one can set insets, seems like a good idea.

**Comment by mrnugget** [comment]
@s3bba can you check with the newest commit? In my i3 it now correctly detects that it won't work and uses server-side decorations.

**Comment by s3bba** [comment]
Just checked on your last commit and server decorations are correctly chosen for my system:
`[2024-07-05T17:27:50+02:00 INFO  gpui::platform::linux::x11::window] x11: no compositor present, falling back to server-side window decorations`

I'll install a compositor on my system and test if it will act diffrently

**Comment by s3bba** [comment]
@mrnugget I installed `picom` compositor, but logs still report `x11: no compositor present, falling back to server-side window decorations`, compositor is active and working correctly.

**Comment by mikayla-maki** [comment]
Ref to chromium implementation: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_desktop_window_tree_host_linux.cc;l=195-198;drc=67d0441446c6264c2921cf5c41098e6b4db467d3

**Comment by mrnugget** [comment]
> Ref to chromium implementation: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_desktop_window_tree_host_linux.cc;l=195-198;drc=67d0441446c6264c2921cf5c41098e6b4db467d3

@mikayla-maki that's kinda the approach I was taking here. Do you see a specific difference?

**Comment by mrnugget** [comment]
> @mrnugget I installed `picom` compositor, but logs still report `x11: no compositor present, falling back to server-side window decorations`, compositor is active and working correctly.

What does Chrome do in that scenario?

**Comment by mikayla-maki** [comment]
> > Ref to chromium implementation: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_desktop_window_tree_host_linux.cc;l=195-198;drc=67d0441446c6264c2921cf5c41098e6b4db467d3
> 
> @mikayla-maki that's kinda the approach I was taking here. Do you see a specific difference?

No sorry, I thought no one had linked it yet and was just making sure there was context on this PR. But it turns out I missed a link earlier!

**Pull request merged**
