### PR TITLE
Allow Node paths to be overridden

### PR DESCRIPTION
**Pull request by jcdickinson**
This adds the `node_runtime` settings, which allows the user to override the location of `node`, `npm` and the npm cache. This is primarily for supporting NixOS.

This changes behavior slightly: the blank npmrc files are stored in the cache directory, not the node bin directory (as that is immutable on NixOS).

A sync+async mutex crate is not currently a dependency in the workspace, so a mpsc is used to smuggle new configuration into the singleton - using `futures::executor::block_on` on the mutex seems to deadlock the GUI thread.

With this change (and language_servers config) I am able to use 95%-100% (TBD) of Zed functionality on NixOS.

Alternative approach: #15749

Release Notes:

- Added Node Runtime Override

Allows the Node runtime to be provided to Zed, instead of being automatically downloaded. This is useful for using Zed on exotic systems such as NixOS. For example:

```nix
xdg.configFile.zed-editor = {
  target = "zed/settings.json";
  text = builtins.toJSON {
    node_runtime = with pkgs; {
      node = "${nodejs_22}/bin/node";
      npm = "${nodejs_22}/bin/npm";
    };
  };
};
```

### CODE REVIEW

**Comment by WeetHet** [comment]
You should also probably try getting node from the PATH, as it is done for most language servers

**Comment by jcdickinson** [comment]
> You should also probably try getting node from the PATH, as it is done for most language servers

This is not for the language servers. It is the runtime used by GitHub copilot, prettier, and other tools.

**Comment by WeetHet** [comment]
> > You should also probably try getting node from the PATH, as it is done for most language servers
> 
> This is not for the language servers. It is the runtime used by GitHub copilot, prettier, and other tools.

Yeah, but I'd still appreciate it automatically detecting node binary from PATH

**Comment by jcdickinson** [comment]
My main concern is that Zed is expecting Node 22; what if you have Node 18 on the path? Either way I think a maintainer would need to chime in about that.

**Comment by WeetHet** [comment]
> My main concern is that Zed is expecting Node 22; what if you have Node 18 on the path? Either way I think a maintainer would need to chime in about that.

We can check if the version is correct by running 
```sh
nodejs -- -v | grep -Eo '[0-9]+[.][0-9]+[.][0-9]+'
```

**Comment by atleast0iq** [comment]
Is there any progress?

**Comment by linuxmobile** [comment]
Waiting this. I really need to override that paths.

**Comment by linuxmobile** [comment]
> Seconding this. Zed is fairly unusable on NixOS right now without being able to run the JS code it depends on.

I've been using it on nixos for quite some time now, and I haven't had any issues. I've completely removed vscode, and I don't see any need to use Helix anymore, for performance reasons.

**Comment by maan2003** [comment]
IMO this should be configured through environment variables instead of config file

**Comment by WeetHet** [comment]
> IMO this should be configured through environment variables instead of config file

I think it should be both. I'd prefer to have it in the config, so I can save it in git

**Comment by ConradIrwin** [comment]
@jcdickinson Sorry for the glacial response here.

We're making some changes to how this works for language servers and I think we should probably reuse some aspects of that approach here.

In particular:
* I like that we can provide the path to the node binary in the settings. I think we should probably flip things around so that the app converts from the settings format to a struct this crate exposes rather than adding a dependency on settings.
* We should probably also copy the settings structure we use for language servers: `{"path":, "arguments":, "env":}` - in case we run into more complicated cases later
* If the setting is not set, we should attempt to use the version of node in your path (after checking it is recent enough).
* We should not use environment variables for this; nothing else in Zed is configured that way.
* I think we could get away without letting you configure the cache directory, we'd continue to manage that like all our other cache directories.
* I am worried about requiring users to configure the `npm` path separately from node. Can we assume it'll be `node/../npm` (and have an option if that assumption is false). Or is there a better way?

**Comment by jansol** [comment]
> I am worried about requiring users to configure [...]

Does zed support having a "system"/"vendor" config? That would allow offloading cases like this to distro packagers. NixOS for example could generate the system config with a node path that is chosen in the package definition. Such a config would live in `$PREFIX/share/zed/config.json` where `$PREFIX` is `/usr` on e.g. Ubuntu and `/nix/store/blarghargahrgahrg-zed-x.yyy.z` on Nix. There is the default config but AFAIK that is defined in the code rather than a file?

Pipewire for example ships its default config in `/usr/share/pipewire/*.conf` and then has system-wide overrides in `/etc/pipewire/*.conf` and per-user customizations in `~/.config/pipewire/*.conf`.

This kind of approach would go a long way towards making things work out of the box on NixOS since the package could specify sensible default paths for a lot of things.

**Comment by ConradIrwin** [comment]
A few packagers just overwrite the default config. It seems reasonable to have another settings file, but (given this is linux distros) we'd need to let them configure the path to it, so not sure if it's actually any less effort than changing the defaults.

**Comment by ConradIrwin** [comment]
This shipped in #18172.

We will now use your system node by default (though you can disable this with `{"node":{"disable_path_lookup":true}}`) or you can hard-code the paths with `{"node"{"path":"/usr/bin/node", "npm_path": "/usr/bin/npm"}}`

**Pull request closed without merging**
