### PR TITLE
windows: Move manifest file to `gpui`

### PR DESCRIPTION
**Pull request by JunkuiZhang**
This is a follow up of #10810 , `embed-resource` crate uses a different method to link the manifest file, so this makes moving manifest file to `gpui` possible.

Now, examples can run as expected:
Screenshot 2024-04-26 111559

TODO:
- [ ] check if it builds with gnu toolchain

Release Notes:

- N/A

### CODE REVIEW

**Comment by JunkuiZhang** [comment]
@ognevny Could you test this PR, on my machine it always complains could not find gcc even it is installed

**Comment by ognevny** [comment]
I can't run on `x86_64-pc-windows-gnu`

<details>

```
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED" at C:\Users\maksa\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:354:18
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98:5
      backtrace::backtrace::trace_unsynchronized
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:66:5
   1: backtrace::backtrace::trace
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:140:22
   4: Zed::init_panic_hook::{{closure}}
             at crates\zed\src\main.rs:747:29
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_handler::{{closure}}
   7: std::sys_common::backtrace::__rust_end_short_backtrace
   8: rust_begin_unwind
   9: core::panicking::panic_fmt
  10: core::result::unwrap_failed
  11: core::result::Result<T,E>::unwrap
             at C:\M\B\src\rustc-1.77.2-src\library\core\src\result.rs:1073:23
      blade_graphics::hal::init::<impl blade_graphics::hal::Context>::init_impl::{{closure}}
             at C:\Users\maksa\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:353:13
  12: core::option::Option<T>::map
             at C:\M\B\src\rustc-1.77.2-src\library\core\src\option.rs:1072:29
  13: blade_graphics::hal::init::<impl blade_graphics::hal::Context>::init_impl
             at C:\Users\maksa\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:352:26
  14: blade_graphics::hal::init::<impl blade_graphics::hal::Context>::init_windowed
             at C:\Users\maksa\.cargo\git\checkouts\blade-b2bcd1de1cf7ab6a\e82eec9\blade-graphics\src\vulkan\init.rs:652:9
  15: gpui::platform::windows::window::WindowsWindowInner::new
             at crates\gpui\src\platform\windows\window.rs:100:17
  16: gpui::platform::windows::window::wnd_proc
             at crates\gpui\src\platform\windows\window.rs:1789:29
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: windows::Win32::UI::WindowsAndMessaging::CreateWindowExW
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.53.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:540:5
  26: gpui::platform::windows::window::WindowsWindow::new
             at crates\gpui\src\platform\windows\window.rs:1284:13
  27: <gpui::platform::windows::platform::WindowsPlatform as gpui::platform::Platform>::open_window
             at crates\gpui\src\platform\windows\platform.rs:373:18
  28: gpui::window::Window::new
             at crates\gpui\src\window.rs:605:31
  29: gpui::app::AppContext::open_window::{{closure}}
             at crates\gpui\src\app.rs:498:30
  30: gpui::app::AppContext::update
             at crates\gpui\src\app.rs:363:22
  31: gpui::app::AppContext::open_window
             at crates\gpui\src\app.rs:495:9
  32: gpui::app::async_context::AsyncAppContext::open_window
             at crates\gpui\src\app\async_context.rs:157:12
  33: workspace::Workspace::new_local::{{closure}}::{{closure}}
             at crates\workspace\src\workspace.rs:970:17
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
             at C:\M\B\src\rustc-1.77.2-src\library\core\src\future\future.rs:124:9
  35: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:455:26
  36: async_task::raw::RawTask<F,T,S,M>::run
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\raw.rs:557:17
  37: async_task::runnable::Runnable<M>::run
             at C:\Users\maksa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:781:18
  38: gpui::platform::windows::platform::WindowsPlatformInner::run_foreground_tasks
             at crates\gpui\src\platform\windows\platform.rs:85:13
  39: gpui::platform::windows::platform::WindowsPlatform::run_foreground_tasks
             at crates\gpui\src\platform\windows\platform.rs:194:9
  40: <gpui::platform::windows::platform::WindowsPlatform as gpui::platform::Platform>::run
             at crates\gpui\src\platform\windows\platform.rs:248:21
  41: gpui::app::App::run
             at crates\gpui\src\app.rs:142:9
  42: Zed::init_ui
             at crates\zed\src\main.rs:237:5
  43: Zed::main
             at crates\zed\src\main.rs:446:9
  44: core::ops::function::FnOnce::call_once
             at C:\M\B\src\rustc-1.77.2-src\library\core\src\ops\function.rs:250:5
  45: std::sys_common::backtrace::__rust_begin_short_backtrace
             at C:\M\B\src\rustc-1.77.2-src\library\std\src\sys_common\backtrace.rs:155:18
  46: std::rt::lang_start::{{closure}}
             at C:\M\B\src\rustc-1.77.2-src\library\std\src\rt.rs:166:18
  47: std::rt::lang_start_internal
  48: std::rt::lang_start
             at C:\M\B\src\rustc-1.77.2-src\library\std\src\rt.rs:165:17
  49: main
  50: __tmainCRTStartup
             at C:\M\B\src\build-UCRT64\C:/M/B/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:267:15
  51: mainCRTStartup
             at C:\M\B\src\build-UCRT64\C:/M/B/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:188:9
  52: <unknown>
  53: <unknown>

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)
```

</details>

looks like it's a regression from https://github.com/zed-industries/zed/commit/53f67a82414fa0429fe8f8bdc2098700f65aa4b6

**Comment by ognevny** [comment]
I applied #11028 and now everything works, thanks

**Comment by mikayla-maki** [comment]
Woo hoo!

**Pull request merged**
