### PR TITLE
Windows: Fix canonicalize return UNC path

### PR DESCRIPTION
**Pull request by CharlesChen0823**
In Windows platform, using notify to watch file events. 
1. in [notify windows implement](https://github.com/notify-rs/notify/blob/3df0f65152c8585cfb29d231c880b86b9164dcfd/notify/src/windows.rs#L344), we get the full file path, just with `path.join(file_path)`.  
2. In [zed worktree start_backgroud_scan_tasks](https://github.com/zed-industries/zed/blob/d2569afe662be93c926eed1aeb2b17d050ba90b0/crates/worktree/src/worktree.rs#L679), `abs_path` is not unc path, so we get all file events with not unc path. 
3. but in [zed worktree process_event](https://github.com/zed-industries/zed/blob/d2569afe662be93c926eed1aeb2b17d050ba90b0/crates/worktree/src/worktree.rs#L3619), we `strip_prefix` unc path all times, it will always print annoy error.

@mikayla-maki I can't reopen pre closed pr #10501 .

Release Notes:

- N/A

### CODE REVIEW

**Comment by CharlesChen0823** [comment]
[`gpui::platform::windows::prompt_for_paths`](https://github.com/zed-industries/zed/blob/32e642454329ac4ad469e032ff439afd465b771b/crates/gpui/src/platform/windows/platform.rs#L452) return not unc path, but i don't think here return unc path is better choice.

**Comment by mikayla-maki** [comment]
@CharlesChen0823 is this PR ready to go? The current fix looks a lot better :)

**Comment by CharlesChen0823** [comment]
@mikayla-maki yes, it's ready for review.

**Comment by mikayla-maki** [comment]
thank you!

**Pull request merged**
