### PR TITLE
Add an easy way to create a branch if it doesn't exist in the branch picker

### PR DESCRIPTION
**Pull request by DAlperin**
If the branch doesn't exist show a "Create Branch: '{}'" menu item. 
Aditionally, branch names are normalized to remove spaces before creating.

I know this is kinda bad code, happy to fix up however.

Release Notes:

- Added a quick way to create branches from the branch picker
Screenshot 2024-10-02 at 4 28 30 PM

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
We already have existing functionality to create a branch if it does not exist:

Screenshot 2024-10-02 at 4 46 15 PM

Seems like we should just make that keyboard navigable?

**Comment by tomaswarynyca** [comment]
What do you think about removing the button and having the menu item?

**Comment by maxdeviant** [comment]
> What do you think about removing the button and having the menu item?

I'll defer to @iamnbutler and @danilo-leal on that one 🙂

**Comment by DAlperin** [comment]
Personally, I think avoiding the extra step a button introduces is worth it. Plus, this introduces visual feedback, but I am not a designer :)

**Comment by iamnbutler** [comment]
Yeah, if everything works the same, having it is an item in the list feels nicer than the button IMO. Easier to use from the keyboard.

**Comment by maxdeviant** [comment]
> Yeah, if everything works the same, having it is an item in the list feels nicer than the button IMO. Easier to use from the keyboard.

I opened https://github.com/zed-industries/zed/pull/18712, as the implementation needed to go in a different direction.

Going to close this PR out in favor of that one. Thanks for taking a swing at this, @DAlperin!

**Comment by DAlperin** [comment]
@maxdeviant aha! matches can be an arbitrary struct, that makes more sense. Thanks for taking my suggestion!

**Pull request closed without merging**
