### PR TITLE
Add support for Typst

### PR DESCRIPTION
**Pull request by bbb651**
Release Notes:

- Added support for [Typst](https://github.com/typst/typst).

I would love some help with the `*.scm` and `config.toml` files, I don't understand them too well and I'm quite certain they have some mistakes and I'm missing some.
The lsp works but for some reason it's missing documentation snippets for methods.

### CODE REVIEW

**Comment by jansol** [comment]
This should probably be an extension? Especially with the recent work towards letting extensions use preinstalled language servers.

**Comment by bbb651** [comment]
I went with builtin approach to get the LSP working, I didn't know what the status of LSP in extensions was. It's very unlikely people will have typst-lsp installed, so this will probably have to wait for bundled LSPs to be an extension.

**Comment by jansol** [comment]
See #9085

As for bundling LSPs, that will never work e.g. for NixOS users (unless you compile the whole LSP to WASM and some extra glue is added to Zed I guess).

**Comment by maxdeviant** [comment]
> This should probably be an extension? Especially with the recent work towards letting extensions use preinstalled language servers.

I agree, this should be an extension.

> I went with builtin approach to get the LSP working, I didn't know what the status of LSP in extensions was. It's very unlikely people will have typst-lsp installed, so this will probably have to wait for bundled LSPs to be an extension.

We already have some languages in Zed that require the language server to be installed separately, so there is prior art for this.

**Comment by maxdeviant** [comment]
As mentioned above, this should ultimately be provided by an extension.

We have an initial version of providing language servers via extensions that is ready for use, so I think that Typst support can move to an extension.

We have a couple extensions in the repo that can serve as a reference: https://github.com/zed-industries/zed/tree/eaa803298ee078c38af4e2ccf753ed98b43a9859/extensions

I'm also happy to answer any questions for someone who wants to work on a Typst extension.

**Pull request closed without merging**
