### PR TITLE
Scala extension

### PR DESCRIPTION
**Pull request by hmemcpy**
Release Notes:

- Added an extension for the Scala language via Metals (Scala LSP) ([#7933](https://github.com/zed-industries/zed/issues/7933)).

This consolidates the wonderful efforts of @mprihoda, @bishabosha and others who made suggestion improvements.
Note: this extension assumes Metals is available in the system (using the equivalent of `which metals`), otherwise prompts to download and install it with coursier.

We could further improve the experience by automatically downloading the latest release of Metals from github (as supported by other extensions, such as Gleam)

image

### CODE REVIEW

**Comment by jansol** [comment]
Pretty sure this should go to [zed-industries/extensions](https://github.com/zed-industries/extensions).

**Comment by hmemcpy** [comment]
Oh dammit, didn't see that repo! Thanks, I'll send the PR again.

**Comment by maxdeviant** [comment]
> Hmm, unless I'm reading it wrong - there are two ways to add extensions: a private repo holding the implementation that is registered in extensions.toml, or an implementation inside zed itself, with the submodule pointing to the implementation inside zed (like e.g. Prisma support [zed-industries/extensions#385](https://github.com/zed-industries/extensions/pull/385))
> 
> I'm fine either way, though if this lives in an external repo, I'd prefer this to be hosted by the scalameta org, who are responsible for the Metals language server.

Correct, right now the only extensions that live in the Zed repo itself are for languages that were previously built-in to Zed. We’re primarily doing this just for ease of management in the short-term. Long-term they will most likely make their way into separate repos.

So for the Scala extension we should have it live in a separate repo.

**Comment by maxdeviant** [comment]
I’m going to close this in favor of having it live in its own repo.

As for getting it hosted by the scalametal org, you’ll have to get in touch with someone over there to facilitate it.

It’s also not a problem from the Zed side if it starts out in a personal repo and then later gets transferred to a different owner.

**Comment by maxdeviant** [comment]
> Thanks for the response, I've already talked to the scalameta folks and we'll set it up there.
> 
> One last question: should I still send a PR to Zed adding it to the extension suggest file, so it could be advertised?

Yep! Once the extension is published we can add it as a suggested extension for Scala files.

**Comment by hmemcpy** [comment]
To anyone coming here from search: the extension now lives under the Scalameta org! https://github.com/scalameta/metals-zed

**Pull request closed without merging**
