### PR TITLE
Add git awareness to file tab icons

### PR DESCRIPTION
**Pull request by ghost**
Before:
Screenshot 2024-08-22 at 15 58 22

After:
Screenshot 2024-08-22 at 15 58 32

Release Notes:

- N/A

### CODE REVIEW

**Review by WeetHet — APPROVED** [review]
This is so cool, love it

**Review by SomeoneToIgnore — APPROVED** [review]
LGTM code-wise, let's wait for the design notes.

As a potential follow-up, we might consider the same approach for file_finder items.
There are no icons and no git statuses there yet, maybe it's a good time to consider adding those too if @iamnbutler has an opinion?

**Comment by SomeoneToIgnore** [comment]
(also, the `Before` image seems to be wrong)

**Comment by SomeoneToIgnore** [comment]
Ok, after the recent release, we have a week to get the feedback based on nightly builds and consider leaving or reverting this.

**Comment by nervenes** [comment]
> LGTM code-wise, let's wait for the design notes.
> 
> As a potential follow-up, we might consider the same approach for file_finder items. There are no icons and no git statuses there yet, maybe it's a good time to consider adding those too if @iamnbutler has an opinion?

i could work on this too and open a separate pr, if it's something that's wanted

**Comment by SomeoneToIgnore** [comment]
I cannot be sure as no feedback on the design was given, but personally interested in looking at how it looks, so can review the new PR.

I could swear there was an issue for this, but failed to find it now.

**Pull request merged**
