### PR TITLE
repl: Scroll down after running code

### PR DESCRIPTION
**Pull request by rgbkrk**
Go to the next line after running code. Allows for fluid coding and running.

https://github.com/user-attachments/assets/d11ac05d-7801-4191-b275-3b20302e54c5

Release Notes:

- N/A

### CODE REVIEW

**Comment by pantheraleo-7** [comment]
Is this binded to cmd+enter? If yes, wouldn't it be better to bind it to shift+enter to match the behaviour of notebooks? One argument could be given is that this isn't a notebook.

**Comment by rgbkrk** [comment]
Since `shift-enter` is used to create a newline unconditionally in text editors I opted not to override that. It's tempting to make that binding show up though when you have an active kernel. 🤔

**Comment by rgbkrk** [comment]
They're currently established keybindings (check out `default-macos.json` and `default-linux.json` in `assets/keymaps`:

https://github.com/zed-industries/zed/blob/49c38a522978f3f569d0531e0552251f77f1fa1d/assets/keymaps/default-macos.json#L135-L138

We also made sure to maintain the `cmd-enter` key binding when jupyter is not enabled:

https://github.com/zed-industries/zed/blob/49c38a522978f3f569d0531e0552251f77f1fa1d/assets/keymaps/default-macos.json#L149-L154

I'm just hesitant for changing default behavior for the moment.

**Comment by pantheraleo-7** [comment]
> We also made sure to maintain the cmd-enter key binding when jupyter is not enabled

And this is the right way IMO.


> They're currently established keybindings

This is the only thing that can stop this change because it will change default behaviour. But apart from that, there's absolutely no reason to:
1. have `shift-enter` for `editor::Newline` when just `enter` does the job
2. have two different bindings for the same job in the same context

**Pull request merged**
