### PR TITLE
Sticky multibuffer headers

### PR DESCRIPTION
**Pull request by agu-z**
https://github.com/user-attachments/assets/92cc5ff7-d8be-4e4b-ac6e-68eb310fffce

Release Notes:

- Multibuffer headers will now stick to the top of the viewport as you scroll
- Added support for expanding diagnostic excerpts

### CODE REVIEW

**Comment by exalted** [comment]
HECK YEA! 🙇

**Comment by exalted** [comment]
I do not love the tiny gap above the topmost header that reveals a few pixels of text scrolling by, but I'll take it!! ❤️ Tyvm @agu-z

**Comment by agu-z** [comment]
@exalted Great point! We decided to hide the lines above the headers and add a transparent gradient on the sides so that other elements smoothly fade out. I updated the video in the description!

**Comment by exalted** [comment]
G-O-R-G-E-O-U-S! 😍

**Pull request merged**
