### PR TITLE
Scrollbar markers for cursors

### PR DESCRIPTION
**Pull request by alygin**
This PR adds cursor markers to the scrollbar. They work similar to VSCode:

1. A cursor marker takes the whole scrollbar width.
2. It's always 2px high.
3. It uses the player's `cursor` color, so it may be helpful in the collaboration mode.

There's a setting to switch cursor markers on/off:

```json
{
  "scrollbar": {
    "cursors": true
  }
}
```

Implementation details:

- Unlike other markers, cursor markers are displayed synchronously. Otherwise they don't feel smooth and sometimes freez on prolonged up/down navigation.
- Cursor markers are automatically switched off when it's more than 100 of them.
- The minimum (non-cursor) marker height is now 5px. It allows the user to see other markers under the cursor marker.
- The way the minimum height is imposed on markers has changed a bit to keep consistency between markers of different types.
- Selected symbol markers use less vibrant color (`info` faded out a little).

Release Notes:

- Added displaying of cursor markers in the scrollbar. They can be switched on/off by the `scrollbar.cursors` setting.

How it looks:

https://github.com/zed-industries/zed/assets/2101250/f564111c-1019-4442-b8a6-de338e12b12e

### CODE REVIEW

**Comment by JosephTLyons** [comment]
One thing this is a bit tricky is the `auto` setting of the scrollbar.

```json
"scrollbar": {
  "show": "auto"
}
```

In `auto` mode, the scrollbar is hidden, unless you are either scrolling, or unless there are markers in the gutter, then, the scrollbar appears. I'm not sure if this setting has been considered in any of the other updates and changes to markers in the scrollbar, but back in the day, git markers were one of the markers that would cause the scrollbar to appear.

Omitting the cursor markers from this setting seems to make the most sense, sense there is always at least one cursor, which would cause the scrollbar to always be visible. It looks like that's how this is currently working - but curious if others have any different ideas for it? Should we dynamically include the cursor markers into this setting? If one cursor, don't allow it to be the thing that forces the scrollbar to be visible in `auto` mode, but if there are more than one cursor, for it to be visible?

**Comment by alygin** [comment]
@JosephTLyons, as an idea &mdash; show the scrollbar when there's at least one cursor that is not in the visible area at the moment. Because a relatively frequent use case (at least for me) is to quickly find out where I am relatively to the cursor without jumping to it.

**Comment by SomeoneToIgnore** [comment]
I like the idea and ready to review when it lands + the conflict gets fixed.

**Comment by alygin** [comment]
@SomeoneToIgnore, implemented, fixed.

This "+1" in change `prepaint()` is valid because adding `height_in_lines` in combination with `.ceil()` already gives us an extra line.

**Review by mikayla-maki — APPROVED** [review]
Looks great!

**Review by SomeoneToIgnore — APPROVED** [review]
Great, thanks!

**Comment by JosephTLyons** [comment]
> @JosephTLyons, as an idea — show the scrollbar when there's at least one cursor that is not in the visible area at the moment. Because a relatively frequent use case (at least for me) is to quickly find out where I am relatively to the cursor without jumping to it.

Yeah this could work. I'm really liking having the cursor locations in the scrollbar, but I am wishing it would *somehow* trigger the scrollbar reveal in auto mode.

**Comment by alygin** [comment]
@JosephTLyons, the implementeation of the cited idea is in Zed Preview. Does it work for you?

**Comment by alygin** [comment]
I found that it's broken. Here's the fix: #11244

**Comment by JosephTLyons** [comment]
@alygin

I think I ran into an issue - likely too many cursors. I'm in `element.rs` and I highlighted `cx` and did a `cmd-shift-l` to select all occurrences and many markers seem to be missing from the scrollbar. Bringing it up here, and not in an issue, in case this is some sort of intentional bail-out.

Notice that there are cursors visible in the buffer, but no associated markers in the scrollbar:

SCR-20240508-mese

**Comment by JosephTLyons** [comment]
That makes sense! Thanks for pointing it out!

**Pull request merged**
