### PR TITLE
Use user-defined font weight, where appropriate

### PR DESCRIPTION
**Pull request by Peiffap**
Release Notes:

- N/A

### CODE REVIEW

**Comment by hron** [comment]
I think the terminal completely ignores `terminal.font_weight` setting as well. Unfortunately, I have no idea how to fix this yet, even though I tried :)

**Comment by Peiffap** [comment]
I think you're right. I only added them in a few obvious places, but the font weight settings aren't always getting applied properly.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Comment by Peiffap** [comment]
Sorry about the messed up title and commit message :(.

**Pull request merged**
