### PR TITLE
Fix proxy settings retrieval on startup

### LINKED ISSUE #18155: Can not connection network through my proxy after #15446
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am using latest Zed in an internal network environment and must connect to a specific server via an HTTP proxy to log in to my Zed account. In the most recent commit, configuring `"proxy": "http://example.com:12345"` in settings.json does not work. I am unable to log in to the account, and the AI cannot be used. No connection records to zed.dev are observed in the proxy logs either.

The relevant code is located in [http_client.rs](https://github.com/zed-industries/zed/blob/main/crates/http_client/src/http_client.rs), and the issue has occurred after commit 2c8a6ee7cc18cb8b3e29fa4c7efa74dde8458f4f. I reverted to commit 9016de5d6350e0a9bbf6a51076c04acd9b7fba96, manually built it, and run; the traffic successfully passed through the proxy and connected to the network.

P.S.: the commit 2c8a6ee7cc18cb8b3e29fa4c7efa74dde8458f4f related #15446

### Environment

Windows11 23H2 22631.4169
(Ubuntu24.04 also Tested.)
rustc 1.81.0 (eeb90cda1 2024-09-04)
Zed between 9016de5d6350e0a9bbf6a51076c04acd9b7fba96 to 2c8a6ee7cc18cb8b3e29fa4c7efa74dde8458f4f.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Runner Terminal output</summary><pre>

[2024-09-21T01:32:11+08:00 ERROR client::telemetry] Failed to send events: HTTP 500
[2024-09-21T01:35:40+08:00 ERROR client] connection error: delay between messages too long
</pre></details>

### PR DESCRIPTION
**Pull request by ClanEver**
Closes https://github.com/zed-industries/zed/issues/18155

Release Notes:

- N/A

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
@JunkuiZhang , would you want to have a peek at this?

**Comment by SomeoneToIgnore** [comment]
Sorry, I was unaware of this, it's totally ok to ignore my message entirely if needed.
Thank you for a quick review.

**Comment by ClanEver** [comment]
I apologize for not explaining this PR, which wasted some of your time.

I've reviewed https://github.com/zed-industries/zed/pull/15446.

It appears that all HTTP requests use the HTTP client created here: `let http = IsahcHttpClient::new(proxy_url, Some(user_agent));`.

Before:

1. `let proxy_str = ProxySettings::get_global(cx).proxy.to_owned();` reads the proxy settings from the global SettingsStore.
2. `handle_settings_file_changes(user_settings_file_rx, cx, handle_settings_changed);` reads settings from the file into the global SettingsStore, including the proxy.

So before the modification, the proxy settings from the settings file were ignored, causing proxy_str to always be None.

After:
By reading the settings from the file first, then `let proxy_str = ProxySettings::get_global(cx).proxy.to_owned();` becomes correct.

<br/>

I just tested that simply placing `handle_settings_file_changes(user_settings_file_rx, cx, handle_settings_changed);` before `let proxy_str = ProxySettings::get_global(cx).proxy.to_owned();` works. When submitting the PR, I referred to the order before the changes in https://github.com/zed-industries/zed/pull/15446, thinking it needed to be placed before `client::init_settings(cx);` to work.

**Comment by JunkuiZhang** [comment]
> Sorry, I was unaware of this, it's totally ok to ignore my message entirely if needed. Thank you for a quick review.

@SomeoneToIgnore There's no need to be sorry, my friend. I can still read and reply emails and github notifications everyday.

**Comment by ConradIrwin** [comment]
Thanks for this!

**Pull request merged**
