### PR TITLE
project panel: select autofolded entries

### LINKED ISSUE #17252: Support selecting intermediate directories in project panel with auto_fold_dirs true
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am experiencing a problem when creating files and folders in the Zed editor. Here's the issue I'm encountering:

I create a folder (let's call it "folder1").
Inside "folder1", I create another folder ("subfolder2").
Inside "subfolder2", I create yet another folder ("subfolder3").
After these steps, the editor displays everything in a path format like folder1/subfolder2/subfolder3. However, I am unable to click on or select any folder other than "subfolder3". It seems like the editor is not allowing me to interact with the parent folders once a subfolder is created.

This behavior is making it difficult to manage my files and folders effectively. Could you please look into this issue?

image

If you see the image, I can't select subfolder1 or folder1. I can't return to nodes.

### Environment

I'm running Zed 0.150.4
macOS 14.16.1 - Apple M1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by osiewicz**
Closes #17252

Release Notes:

- Intermediate auto-folded project entries can now be selected and acted upon (removed, renamed, cut, pasted).

### CODE REVIEW

**Comment by notpeter** [comment]
@osiewicz Did this ever work as expected?  

I built from the commit for this PR https://github.com/zed-industries/zed/commit/66ef31882341852229c74996867916fbd4a2fe2a and could not rename/copy/delete intermediate directories nor create new subdirs or new files in them.

**Comment by osiewicz** [comment]
Yeah, they do work for me (sans creating new files, that seems broken) on latest Nightly.

**Comment by osiewicz** [comment]
I did land a follow-up PR that might affect what you're seeing: https://github.com/zed-industries/zed/pull/17594/files

**Comment by notpeter** [comment]
I can't get the behavior to work anywhere (nightly, dd257b8412c3c8005c710185dc8fc2eed3cc67ba, 66ef318). Maybe I'm completely misunderstanding this functionality.

**Pull request merged**
