### PR TITLE
blade: Switch to linear color space

### LINKED ISSUE #7684: Rendering is done in sRGB color space instead of linear
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following up on #7666.
The surface format used in Zed is currently `BGRA8Unorm`, and we aren't explicitly requesting a color space from `CALayer`. Default color space is always "srgb non-linear". You can see this in [VkColorSpace](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkColorSpaceKHR.html): `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` is zero. On Metal, a similar setting called [colorspace](https://developer.apple.com/documentation/coregraphics/cgcolorspace) exists, but the documentation is less explicit:
> The default value is nil, indicating that the rendered content isn’t color-matched.

What this means is - Metal wouldn't be trying to configure the monitor in any way. And the convention for the monitors since CRT days is that they assume the surface data is in "sRGB" space. See https://bottosson.github.io/posts/colorwrong/#non-linear-transfer-function.
In practice, your colors are going to be put to the power of "2.2" (roughly) before being emitted by the display, which makes colors darker.

This isn't easily evident in general because most of the colors come from constants (the visual "theme"), and theme authors make sure that these constants are specified in a way that makes a particular end result visually. So, as long as you only ever display a constant color from some table - it's OK. Problem shows up in the interpolation of colors: gradients and blending, as you can see in the blog post by Björn Ottosson. Zed isn't a full-featured browser, but technically it does blending on all primitives, so it's affected by using the wrong color space.

Here is how we could fix this. Proposal:
1. Switch the `CALayer` format to be `BGRA8Unorm_srgb`.
2. For any image that is taken from the outside, it should be assumed that the contents are in sRGB format, so the associated texture should also be in `BGRA8Unorm_srgb`.
3. All the intermediate data, such as the sprite atlas, would still use `BGRA8Unorm`. It means - to assume linear color space at this step in the pipeline.
4. In the shader code for `hsla_to_rgba`, we'd also do the "srgb -> linear" conversion, since all of the theme data today is assumed to be in sRGB color space. Can also do it earlier in the pipeline, e.g. when a theme is loaded.

### Environment

macOS

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I don't know how to create a gradient in Zed/GPUI.

### LINKED ISSUE #11462: Transparency behaves inconsistently across platforms
### Check for existing issues

- [X] Completed

### macOS / Metal
Zed with transparent background using the native Metal render backend

### macOS / blade
Zed with transparent background using the Blade render backend

### Linux / blade
Zed with transparent background using the Blade render backend, but on Linux (KDE Plasma)

### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by kvark**
Release Notes:

- N/A

## What

Addresses a long-standing issue of doing the blending operations in sRGB space. Currently, the input HSL colors are provided in sRGB space and converted to linear in the vertex shader. Conversion back to sRGB, which is required on most platforms today, happens at the very end of the pipeline when writing into sRGB render target.

Note-1: in the future we may consider doing HSL -> sRGB -> Linear transform on CPU before feeding into shaders. However, I don't expect any significant difference here given that we are likely bound by fill rate and pixel shaders, anyway.

Note-2: the graphics stack is programmed to detect if the platform supports presenting in linear color space and avoids converting to sRGB at the end in this case. However, on my Z13 laptop this isn't supported by the RADV driver.

Closes #7684 
Closes #11462
@jansol please confirm if you can!

## Comparison

Screenshot of the Glazier theme before the change:
glazier-old
Same theme after the change:
glazier-new

### CODE REVIEW

**Review by jansol — CHANGES_REQUESTED** [review]
Hm, looks like Neither RADV nor ANV (Mesa Vulkan driver for Intel GPUs) support linear sRGB. So the end result will have to be converted back to sRGB and the surface marked as sRGB nonlinear after all. [Looks like I misremembered, and only nonlinear sRGB support is guaranteed by the vulkan spec anyway.](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkColorSpaceKHR.html). It's still worth doing these conversions though, since linear interpolation should be done in linear space to ensure the result actually looks linear (see e.g. shadows).

Color texture reads also need to be converted from sRGB to linear (now they are washed out), but if the texture format for the relevant textures is specified as VK_FORMAT_*_SRGB (rather than *_UNORM) this is done automagically in hardware. I'm not sure if antialiased text glyphs are rasterized with or without gamma, that needs some further investigation.

**Comment by kvark** [comment]
@jansol good point about the textures! I added a commit to switch the atlas Polychrome kind to sRGB.

**Comment by mikayla-maki** [comment]
@kvark @jansol Does further work need to be done on this PR to cover the lack of guaranteed linear sRGB? If not, happy to merge this :)

**Comment by jansol** [comment]
@mikayla-maki yes, when linear framebuffers are not available the shaders need to convert the result back to nonlinear sRGB.

**Comment by kvark** [comment]
@jansol no, we aren't missing this bit. Blade will automatically select the sRGB render target here, and conversion to be done by the pixel export in the HW. I think the PR is ready, unless your testing proves otherwise.

**Comment by mikayla-maki** [comment]
@kvark Good enough for me

@jansol I'm going to merge this, feel free to open up issues or PRs so we can fix forward with the issues you've potentially identified

**Pull request merged**
