### PR TITLE
gpui: Export raw_window_handle for wry to render WebView, and with a WebView example

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- N/A

Ref #10533 #5310 and by #9778 @vultix idea.

This PR just to export the `raw_window_handle` method.

Because wry or others can use this to render to the window.

https://docs.rs/wry/latest/wry/struct.WebViewBuilder.html#method.new_as_child

https://github.com/zed-industries/zed/assets/5518/f6759762-5d60-4751-a6a9-32c41068584b

---

Run example:

```bash
cargo run -p gpui --example webview
```

### CODE REVIEW

**Comment by huacnlee** [comment]
The Linux CI fail, the CI server needs to install `libwebkit2gtk`:

```
sudo apt install libwebkit2gtk-4.1-dev
```

**Comment by huacnlee** [comment]
With this, we can to make a markdown preview with WebView.

I have do a quick test:
CleanShot 2024-07-02 at 15 33 12@2x

**Comment by huacnlee** [comment]
I am going to close. It still have a lot of issues, the wry not work with the GPUI.

**Comment by isaacmclellan** [comment]
hey, this looks pretty cool.

**Comment by mocenigo** [comment]
This looks wonderful. Is this being integrated into the mainline source code of zed?

**Pull request closed without merging**
