### PR TITLE
Fix AI Context menu text wrapping causing overlap

### LINKED ISSUE #20678: Assistant slash command menu: descriptions can overflow
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The bug is in rendering i think. When I click on the context button of Assist panel I see this bug. I am on linux.\

image

### Environment
```
Zed: v0.161.2 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 15 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV RENOIR) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2
```
Did I installed the wrong version or something?
### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by huacnlee**
Closes https://github.com/zed-industries/zed/issues/20678 #21394

| Before | After |
| --- | --- |
| SCR-20241203-jreb | SCR-20241203-jwhe |

Release Notes:

- Fixed AI Context menu text wrapping causing overlap.

Also cc #21409 @WeetHet @osiewicz to use `Label`, this PR has been fixed `Label` to ensure `whitespace_nowrap` when use `single_line`.

### CODE REVIEW

**Comment by huacnlee** [comment]
image

**Comment by huacnlee** [comment]
Ok, I have remove the tooltip change.

**Comment by danilo-leal** [comment]
The tooltip's great! It's a good solution to see the whole description if it's been cut by the overflow. I was referring to the need ot having the `single_line` property on the Label. That might be useful, I think, but not necessarily for this scenario. And maybe we could separate its addition on a separate PR. I might've not communicated super well, apologies.

**Comment by huacnlee** [comment]
In this case if we not enable `whitespace_nowrap` for `single_line`, the issue will not to be fix

**Comment by danilo-leal** [comment]
I pushed a little commit there adding `text_ellipsis`. That fixes the overflowing! And then, the tooltip helps have access to the description even if the text's overflown.

**Review by danilo-leal — APPROVED** [review]
Thank you! 🙌

**Pull request merged**
