### PR TITLE
[WIP] Improve completions for TypeScript

### PR DESCRIPTION
**Pull request by babyccino**
Related to #5287 

This is a WIP but I just wanted to check if this is something Zed would be interested in before I put more time into it. Basically what I've done is changed the LSP functionality so labels as well as documentation is updated from the LSP `completionItem/resolve` response.

Before:
Screenshot 2024-04-19 at 7 19 07 PM

After:
Screenshot 2024-04-19 at 7 18 51 PM

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
The new labels look great. Could you explain a bit more about why the separate `labels_for_resolved_completion` method is needed?

**Comment by babyccino** [comment]
> The new labels look great. Could you explain a bit more about why the separate `labels_for_resolved_completion` method is needed?

It's not _completely_ necessary. You could definitely determine in the label function which kind of completion you're dealing with, but for the TS LSP (and maybe for others) the format is completely different depending on whether they are regular completions or resolved completions. I figured it was easier to do it this way and maybe there are some other LSPs where it's not so easy to differentiate.

**Comment by mrnugget** [comment]
Without having looked too closely at the code: @babyccino it might be worth checking against `main` and what has changed there, since I also changed the how we do completion item resolution: https://github.com/zed-industries/zed/pull/11157

**Comment by jackTabsCode** [comment]
Hi @mikayla-maki, I'm curious what the status of this is? Is it ready to be merged?

**Comment by babyccino** [comment]
> Hi @mikayla-maki, I'm curious what the status of this is? Is it ready to be merged?

I got distracted by #12106 so I haven't worked on this in a while. It's still in a very rough state and definitely not ready to be merged. If Zed is still interested in this I can work on it after #12106 is merged

**Comment by ConradIrwin** [comment]
@babyccino I'm going to close for now, but please re-open when you get time to work on it!

**Pull request closed without merging**
