### PR TITLE
Helix keybindings take 2

### PR DESCRIPTION
**Pull request by maan2003**
currently has no helix bindings just supporting code. 

went with helix in a different crate, editor addons made simpler so it was much less code.

this PR is meant to be merged early so I don't build a big branch that is impossible to merge.

Release Notes:

- N/A

### CODE REVIEW

**Comment by noaccOS** [comment]
@maan2003 I've sent you a PR to try to fix the CI and move this forward. Let me know if I can help you somehow!

**Comment by noaccOS** [comment]
@cla-bot check

**Comment by noahfraiture** [comment]
It's pretty surprising to have a single failing test. Is it possible that the test if incorrect ?

**Comment by noaccOS** [comment]
> It's pretty surprising to have a single failing test. Is it possible that the test if incorrect ?

This PR doesn't really modify the vim crate at all. Also, the tests pass just fine on the macos ci.
I'm not really familiar with the zed ci, but it's possible this is (was? the branch is based on a 2 months old main branch) a flaky test.

Personally I'm more interested in what's missing from this pr to mark it ready for review

**Comment by ConradIrwin** [comment]
I am going to close this in favor of #19175.

I know we've been back on forth on this  a bunch, sorry for not being clearer about the direction here sooner.

**Pull request closed without merging**
