### PR TITLE
vim: indentation object

### PR DESCRIPTION
**Pull request by romgrk**
Text-object for current indentation level.

[Kooha-2024-03-07-18-11-02.webm](https://github.com/zed-industries/zed/assets/1423607/1e33364c-b5f5-41a6-bf42-a4f95d7af20f)

Release Notes:

- Added vim `indentation` object

### CODE REVIEW

**Comment by romgrk** [comment]
This is the most popular vim plugin for this text-object: https://github.com/michaeljsmith/vim-indent-object, and the one I use. I'll update the docs once the PR is ready to make it discoverable.

> Looks like the tests are failing

Yeah I just made a quick draft yesterday.

**Comment by ConradIrwin** [comment]
@romgrk Are you still working on this one, or should I close and let you re-open when it's ready?

**Comment by romgrk** [comment]
Let's close for now, too busy at work.

For the record, there is an issue with text-objects in general, they don't implement the characterwise/linewise distinction that vim has. The paragraph text-object right now is not working properly because it will yank text it operates on characterwise, while it's linewise in vim. That needs to be fixed, which is why I didn't complete this PR. Most of the work for the indentation object is done except for that. For anyone interested, feel free to pick up the PR.

**Comment by ConradIrwin** [comment]
Thanks!

When I was first implementing yank, I think the difference is whether or not to include the trailing newline, so that may not be too hard to fix. (But also, it's vim, so there may be more subtleties :D).

**Comment by romgrk** [comment]
Yeah I saw that trailing newline meant a linewise clipboard, but despite that there was something I couldn't resolve, Details are fuzzy in my brain. To reproduce, `yip`, then `p` will paste character-wise. Indentation are paragraph are the only linewise text-objects I could see. `vipy` works, but that's not in text-object mode, it's a motion followed by a visual mode yank.

**Pull request closed without merging**
