### PR TITLE
SSH Remoting: Improve unsupported error messages

### PR DESCRIPTION
**Pull request by ConradIrwin**
Updates #19697

Release Notes:

- SSH Remoting: Improved error message on unsupported OS/Arch.

### CODE REVIEW

**Comment by alessio-locatelli** [comment]
@ConradIrwin Is there any open issue/PR to improve the `Permission denied` confusing message as well? I attached the screenshot in https://github.com/zed-industries/zed/discussions/19992#discussioncomment-11108565

**Comment by ConradIrwin** [comment]
@alessio-locatelli there is not, sorry I had missed that.

It looks like for some reason we are unable to execute that script for you, is it possible that you're mounting /tmp with `noexec`? if so, I think we need a different place to stash this file.

**Comment by alessio-locatelli** [comment]
> @alessio-locatelli there is not, sorry I had missed that.
> 
> It looks like for some reason we are unable to execute that script for you, is it possible that you're mounting /tmp with `noexec`? if so, I think we need a different place to stash this file.

The problem is very easy to reproduce via:

1. Start a Fedora container.

```bash
docker run --rm -it --name fedora-ssh -p 0.0.0.0:2200:22 -e SSH_USERPASS=secret fedora/ssh
```

2. Verify that SSH is working.

```bash
ssh -p 2200 user@localhost
```

3. Now try to connect with Zed:

```bash
zed ssh://user@localhost:2200
```

---

Note that the mentioned image is a bit outdated, but I guarantee the same error on `fedora:40`.

Again, I am not saying that I expect that Fedora is supported. I am saying that the error does not provide enough details about what is wrong.

**Comment by ConradIrwin** [comment]
I think the problem is on your local machine (I can ssh into that docker container just fine).

Can you run `mount` and show me the output?

Or try this:
```
cd /tmp
echo 'echo 1' > a.sh
chmod +x a.sh
./a.sh
```

My current hypothesis is that you'll see permission denied when trying to execute a.sh because you have noexec on your tmp directory.

**Comment by alessio-locatelli** [comment]
> I can ssh into that docker container just fine

I assume you say "I can ssh **with Zed** into that docker container just fine" because I can `ssh` too, but not with Zed. 

Well, since you assume that a `Permission denied` problem can be due to my local machine (my primary OS is Fedora 41), I decided to test Zed on my another machine with Lubuntu 22.04. So, on Lubuntu:
```bash
curl -f https://zed.dev/install.sh | sh
zed ssh://user@localhost:2200
```
fails with the same error (see the screenshot above).

```bash
curl -f https://zed.dev/install.sh | ZED_CHANNEL=preview sh
zed ssh://user@localhost:2200
```
A "preview" version fails too.

I am not sure that this is somehow can be related to the `/tmp` directory, but here it is:

<details>
<summary>Click to expand: exec permission</summary>

```bash
❯ cd /tmp
❯ echo 'echo 1' > a.sh
❯ chmod +x a.sh
❯ ./a.sh
1
```
</details>


<details>
<summary>Click to expand: `mount` output</summary>

```bash
/dev/nvme0n1p3 on / type btrfs (rw,relatime,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/root)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4096k,nr_inodes=4062781,mode=755,inode64)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=6509276k,nr_inodes=819200,mode=755,inode64)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=6835)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,nosuid,nodev,relatime,pagesize=2M)
tmpfs on /run/credentials/systemd-journald.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-network-generator.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-udev-load-credentials.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev-early.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-sysctl.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-vconsole-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
/dev/nvme0n1p3 on /home type btrfs (rw,relatime,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home)
/dev/nvme0n1p2 on /boot type ext4 (rw,relatime)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro)
tmpfs on /run/credentials/systemd-tmpfiles-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-resolved.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3254636k,nr_inodes=813659,mode=700,uid=1000,gid=1000,inode64)
net_cls on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sdc1 on /run/media/sam/clover type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
tmpfs on /run/firejail/dbus type tmpfs (rw,nosuid,nodev,noexec,size=6509276k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/firejail/firejail.ro.dir type tmpfs (ro,nosuid,nodev,size=6509276k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/firejail/firejail.ro.file type tmpfs (ro,nosuid,nodev,size=6509276k,nr_inodes=819200,mode=755,inode64)
```

</details>

In the Docker container's `/tmp` executing is allowed too.

I highly appreciate your support.  

I am happy to wait for new Zed releases to try it again, or to provide more details if I can.

**Comment by alessio-locatelli** [comment]
Sorry, I forgot to attach the log: 

<details>
<summary>Click to expand</summary>

```
v/bin:/home/sam/.pyenv/bin:/home/sam/.local/kitty.app/bin:/home/sam/.pyenv/bin:/home/sam/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/sam/.local/bin:/home/sam/.local/bin:/home/sam/.local/bin:/home/sam/.local/bin:/home/sam/.local/bin
2024-11-22T18:39:50.113174376+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-11-22T16:39:50.104Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-11-22T16:39:50.104Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-11-22T18:39:50.117295574+02:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "a3d3350c-7768-493b-9f69-91a7864fdc35",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-11-22T18:39:50.157958555+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-11-22T16:39:50.127Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-11-22T16:39:50.127Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
(END)
```

</details>

**Comment by ConradIrwin** [comment]
Weird!

I think it makes sense that it works for some machines, and not for others is that `ssh` will only attempt to invoke askpass if it needs to ask you for a password.

What I don't understand is why when ssh tries to run that executable, it gets permission denied for you, but not for me.

**Pull request merged**
