### PR TITLE
Bump rustls and async-tungstenite to remove child dep ring 0.16.20

### LINKED ISSUE #18891: Bump dependencies for RISC-V support
### Check for existing issues

- [X] Completed

### Describe the feature

The manual currently states:

> You will need to build from source for:
>
>  - architectures other than 64-bit Intel or 64-bit ARM (for example a 32-bit or RISC-V machine)

However, zed currently fails to build on RISC-V because of an (indirect) dependency on ring 0.16, which does not support RISC-V. Version 0.17 of the crate does, but updating that dependency is not straightforward to me (not being a Rust developer). The compatibility seems restricted by rustls and async-tungstenite, but bumping those dependencies to resp. 0.21.8 and 0.25 (which are the minimum versions that are compatible with ring 0.17) results in the introduction of http 1.1.0, which is incompatible with version 0.2.12 of the http crate that's used by other dependencies.

Would it be possible to upgrade dependencies in order to unblock RISC-V support? ring 0.16.20 is 3 years old, rustls 0.20.3 is over 2 years old, so it seems that upgrading these dependencies is a good idea anyway.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by ifsheldon**
Closes #18891 

Tests:
- I have cargo checked and built `remote-server` on my riscv64 dev board.
- I have cargo checked and tested on my M1 Mac
    - Almost all test passed. Some (LLM tests, Postgres tests)failed due to, IMO, irrelevant reasons

Release Notes:

- Improved support of Zed remote server compilation for riscv64

cc @ConradIrwin 

PS: I didn't include the changes of `Cargo.lock`, which may look messy. Probably I should include these? Or, should a reviewer do this? The expected Cargo.lock should have only one version of `ring` with version > 0.17.0

### CODE REVIEW

**Comment by ifsheldon** [comment]
@cla-bot check

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
Passing by and leaving a note: this had not bumped anything yet, as the lockfile is unaffected.
You could trigger `cargo check` or anything else that will re-resolve the dependencies and update the lockfile (which you need to commit and push here afterwards)

**Comment by ifsheldon** [comment]
yea, I know. I just thought maybe regenerating Cargo.lock should be done by someone who has write privilege of the main branch to avoid unnecessary merge conflicts. But anyway, I am committing changes on Cargo.lock.

**Comment by ifsheldon** [comment]
I saw Cargo.lock was changed by other commits since my last one, so I rebased my commits and then ran a `cargo check` to update Cargo.lock. This brings irrelevant commits into the history.

**Comment by SomeoneToIgnore** [comment]
Then the rebase went wrong, as this PR now clearly does something beyond altering the dependencies:
image

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks, now we're prepared for @ConradIrwin 's final say.
The code looks good to me, but I guess he might have more context and may check for more things.

**Comment by ConradIrwin** [comment]
Thanks!

**Pull request merged**
