### PR TITLE
Update C++ Tree-sitter queries

### LINKED ISSUE #16443: Syntax Tag for elements after two or more scope resolution operators in c++ is wrongly set to "variable" instead of "function"
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When there are more than one scope resolution operator ( "::" ) , if there is a function call at the end of the expression, it will be wrongly categorized as a variable for the syntax tag system used by themes for highlighting the text.

in "std::move()", the word "move" will properly be highlighted as a function.

in "std::chrono::high_resolution_clock::now()", the word "now" will be highlighted by the color set to the tag "variable" 

in "std::this_thread::sleep_for(std::chrono::milliseconds(500))", "sleep_for" and "millisecond" will also take the color of the variable tag. 

here is a screenshot showcasing this. In the case it is important, the theme used is catppuccin mocha no italic.  

image

### Environment

Zed: v0.148.1 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4070 || NVIDIA || 535.183.01

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Elements ending with parenthesis in an expression with more than one scope resolution operator should have the tag "function" instead of "variable". 

I'm not knowledgeable enough in C++ to be certain it would be sufficient to avoid every edge cases, but multiple scope resolution is widely used in the standard library, so qualifying those cases with the tag "function" could be a reasonably better heuristic than the actual tag as "variable".

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by VacheDesNeiges**
Closes #16443 

Release Notes:

- Fixed C++ functions being wrongly tagged as variables when called after two or more scope resolution operators.
- Added a "namespace" tag for highlighting purposes

Before : 
image
After : 
image

### CODE REVIEW

**Comment by VacheDesNeiges** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Changes looks nice to me.
There's another tree-sitter-cpp upgrade happening in https://github.com/zed-industries/zed/pull/17734 , so let's wait with this PR before that one is merged.

Seems to be close, so maybe rebasing on top of it and checking that things work is a good thing to do.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/17734 is merged, feel free to ping me when you have rebased and rechecked th queries.

**Comment by VacheDesNeiges** [comment]
@SomeoneToIgnore I think I correctly rebased on main, the queries are still working when I compile and run Zed. 

This was my first time rebasing with changes on other branches than mine in between, so I would appreciate if you could verify that I have not broken anything.

**Review by SomeoneToIgnore — APPROVED** [review]
Seemed to work for me on a cpp repo I've checked.

Thank you!

**Pull request merged**
