### PR TITLE
Show Icons for Completion Kind

### LINKED ISSUE #4943: Code completion icons
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode shows icons for code completions, depending on what kind of suggestion it is. There's an icon for functions, one for snippets, etc. I'd love to see this in Zed because it helps me more quickly get a sense of what I'm looking at.

### If applicable, add mockups / screenshots to help present your vision of the feature

image
image

### PR DESCRIPTION
**Pull request by Feel-ix-343**
Takes influence from the icons [here](https://github.com/onsails/lspkind.nvim) and adds completion kind icons to zed completions. (It looks beautiful!) 

- Resolves #4943 ([link](https://github.com/zed-industries/zed/issues/4943)). 

Preview with Rust-Analyzer on the Zed codebase:

zed_completion_kind

### CODE REVIEW

**Comment by Feel-ix-343** [comment]
And a future step could be to make this configurable by Zed themes

**Comment by Feel-ix-343** [comment]
I will make the icons the same color as the text!

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I think it's unlikely we'll merge in this current state, as we would need to design all of these icons to match our current icon set.

**Comment by Feel-ix-343** [comment]
Okay. Are there plans for themes to configure icons?

**Comment by maxdeviant** [comment]
> Okay. Are there plans for themes to configure icons?

We are planning on adding the ability for extensions to provide icons, but no timeline on it yet. Right now our primary focus with extensions is making sure all of our current language servers can be expressed using the extension API.

Here's the tracking issue for icons in extensions: https://github.com/zed-industries/zed/issues/8843

**Comment by filipwiech** [comment]
Maybe this PR could be repurposed and show text with a styled font (muted + colored depending on the completion type) instead of the icons for now? :thinking: Icons could then always be added later and made configurable (maybe the text should be configurable by the user/theme too). :slightly_smiling_face:

**Comment by maxdeviant** [comment]
> Maybe this PR could be repurposed and show text with a styled font (muted + colored depending on the completion type) instead of the icons for now? 🤔 Icons could then always be added later and made configurable (maybe the text should be configurable by the user/theme too). 🙂

I think we’re a little pressed for real estate here to be showing words of variable lengths.

**Comment by filipwiech** [comment]
> > Maybe this PR could be repurposed and show text with a styled font (muted + colored depending on the completion type) instead of the icons for now? 🤔 Icons could then always be added later and made configurable (maybe the text should be configurable by the user/theme too). 🙂
> 
> I think we’re a little pressed for real estate here to be showing words of variable lengths.

That's understandable. :slightly_smiling_face:  To be honest I wasn't really thinking about whole words, but more like letters, kind of similar to what for example IntelliJ does (m - method, f - field, v - variable, etc.), but perhaps it would be not clear enough. :+1:

**Comment by jezikk** [comment]
XCode examples:
XCode

XCode2

**Comment by Feel-ix-343** [comment]
> XCode examples: XCode
> XCode2

I like this to - it is technically another icon style though and I think either way the Zed team would want to redesign the icons; It could be quite simple if they are just characters, however.

**Comment by maxdeviant** [comment]
I'm going to close this for now, as I think we'll want to involve our designer, @/iamnbutler, when he's back from paternity leave to make sure we settle on an approach that aligns with our design direction for Zed.

**Comment by Feel-ix-343** [comment]
Hey!

@iamnbutler bump (no pressure)

**Comment by d1y** [comment]
@iamnbutler If you have time, can you take a look at this? ^:)

**Comment by retort00** [comment]
@iamnbutler bump 🙏

**Comment by XZCendence** [comment]
@iamnbutler bumpppp this is a much needed feature

**Pull request closed without merging**
