### PR TITLE
Reduce memory usage to represent buffers by up to 50%

### PR DESCRIPTION
**Pull request by mrnugget**
This should help with some of the memory problems reported in https://github.com/zed-industries/zed/issues/8436, especially the ones related to large files (see: https://github.com/zed-industries/zed/issues/8436#issuecomment2037442695), by **reducing the memory required to represent a buffer in Zed by ~50%.**

### How?

Zed's memory consumption is dominated by the in-memory representation of buffer contents.

On the lowest level, the buffer is represented as a [Rope](https://en.wikipedia.org/wiki/Rope_(data_structure)) and that's where the most memory is used. The layers above — buffer, syntax map, fold map, display map, ... — basically use "no memory" compared to the Rope.

Zed's `Rope` data structure is itself implemented as [a `SumTree` of `Chunks`](https://github.com/zed-industries/zed/blob/8205c52d2bc204b8234f9306562d9000b1691857/crates/rope/src/rope.rs#L35-L38).

An important constant at play here is `CHUNK_BASE`:

`CHUNK_BASE` is the maximum length of a single text `Chunk` in the `SumTree` underlying the `Rope`. In other words: It determines into how many pieces a given buffer is split up.

By changing `CHUNK_BASE` we can adjust the level of granularity withwhich we index a given piece of text. Theoretical maximum is the length of the text, theoretical minimum is 1. Sweet spot is somewhere inbetween, where memory use and performance of write & read access are optimal.

We started with `16` as the `CHUNK_BASE`, but that wasn't the result of extensive benchmarks, more the first reasonable number that came to mind.

### What

This changes `CHUNK_BASE` from `16` to `64`. That reduces the memory usage, trading it in for slight reduction in performance in certain benchmarks.

### Benchmarks

I added a benchmark suite for `Rope` to determine whether we'd regress in performance as `CHUNK_BASE` goes up. I went from `16` to `32` and then to `64`. While `32` increased performance and reduced memory usage, `64` had one slight drop in performance, increases in other benchmarks and substantial memory savings.

| `CHUNK_BASE` from `16` to `32` | `CHUNK_BASE` from `16` to `64` |
|-------------------|--------------------|
| chunk_base_16_to_32 | chunk_base_16_to_64 |

### Real World Results

We tested this by loading a 138 MB `*.tex` file (parsed as plain text) into Zed and measuring in `Instruments.app` the allocation.

#### standard allocator
Before, with `CHUNK_BASE: 16`, the memory usage was ~827MB after loading the buffer.

| `CHUNK_BASE: 16` |
|---------------------|
| memory_consumption_chunk_base_16_std_alloc |

After, with `CHUNK_BASE: 64`, the memory usage was ~396MB after loading the buffer.

| `CHUNK_BASE: 64` |
|---------------------|
| memory_consumption_chunk_base_64_std_alloc |

#### `mimalloc`

`MiMalloc` by default and that seems to be pretty aggressive when it comes to growing memory. Whereas the std allocator would go up to ~800mb, MiMalloc would jump straight to 1024MB.

I also can't get `MiMalloc` to work properly with `Instruments.app` (it always shows 15MB of memory usage) so I had to use these `Activity Monitor` screenshots:

| `CHUNK_BASE: 16` |
|---------------------|
|  memory_consumption_chunk_base_16_mimalloc |

| `CHUNK_BASE: 64` |
|---------------------|
| memory_consumption_chunk_base_64_mimalloc |

### Release Notes

Release Notes:

- Reduced memory usage for files by up to 50%.

### CODE REVIEW

**Comment by mocenigo** [comment]
I can confirm that the application now behaves MUCH better when handling large tasks. It still does not release memory promptly, and earlier I thought it may have been some memory leak. Now I see that this may be because of the large chunks of memory allocated by MiMalloc — if a large chunk is allocated and then other parts of the application keep in it some of their data, then the large chunk may not be released back to the system. 

I am not sure this is the ideal model for an editor. Could you try with some other allocator? Performance is important but I feel that for an editor MiMalloc may be overkill (for a MILP solver, or a game, it would be ideal).

**Comment by mocenigo** [comment]
By the way, what happens with a CHUNK_BASE of 128?

**Comment by mocenigo** [comment]
Update. I tried with a CHUNK_BASE of 128. No significant memory usage improvement by looking at Activity Monitor, so it seems that that with 64 you hit the sweet spot.

**Comment by mrnugget** [comment]
> I am not sure this is the ideal model for an editor. Could you try with some other allocator? Performance is important but I feel that for an editor MiMalloc may be overkill by(for a MILP solver, or a game, it would be ideal).

You can try this yourself by just commenting out these two lines:

https://github.com/zed-industries/zed/blob/b181a42471a3dae5542353e613a5fe5c91053c92/crates/zed/src/main.rs#L70-L71

**Comment by mocenigo** [comment]
> > I am not sure this is the ideal model for an editor. Could you try with some other allocator? Performance is important but I feel that for an editor MiMalloc may be overkill by(for a MILP solver, or a game, it would be ideal).
> 
> You can try this yourself by just commenting out these two lines:
> 
> https://github.com/zed-industries/zed/blob/b181a42471a3dae5542353e613a5fe5c91053c92/crates/zed/src/main.rs#L70-L71

Wonderful. Love you, man. I did not trust myself to comment those lines myself because I feared it left some functions undefined (I am a bit of a coward).

Is there a benchmarking suite in some of the crates, so that I can, say, start zed via the cli and with a testing option?

**Comment by mrnugget** [comment]
> Is there a benchmarking suite in some of the crates, so that I can, say, start zed via the cli and with a testing option?

I've added a few benchmarks to the `ropes` create (take a look in the `benches` folder). You could take some of that code and modify it to give you really large buffers, then create a test that initializes only a rope with a certain size and see its memory usage.

**Pull request merged**
