### PR TITLE
lsp: Do not notify all language servers on file save

### PR DESCRIPTION
**Pull request by osiewicz**
This is not an ideal solution to https://github.com/fasterthanlime/zed-diags-readme, but current status quo is not great either; we were just going through all of the language servers and notifying them, whereas we should ideally do it based on a glob.
/cc @fasterthanlime

Release Notes:

- N/A

### CODE REVIEW

**Comment by fasterthanlime** [comment]
I do not fully understand this change nor exactly how the integration works, but I want to emphasize that rust analyzer should absolutely know about the change in the markdown file in this instance.

The markdown file does contain rust code blocks that rust analyzer needs to know about I’m assuming.

**Comment by osiewicz** [comment]
It's a bit more subtle; I don't think we spawn a separate language server instance in this case (for . md file) and the existing Rust instance does not care about Markdown files, as it does not register for watching of .md files.

This is a can of worms. ૮꒰꩜ ᯅ ꩜;꒱ა

**Comment by fasterthanlime** [comment]
Mhhh, I see.

for the record the original error I saw in the logs was something like “got diagnostics for path/to/README.md but this path isn’t in VFS” or something.

when making the repro I got a different error (the r-a panic)

**Comment by Veykril** [comment]
The panic in r-a happens because it receives an invalid path for the on save handler, it only registers rust and toml files for it but zed incorrectly gives it other files, violating the LSP (see https://github.com/zed-industries/zed/issues/17376). We fixed panic behavior in r-a (it now logs an error) but this still needs fixing in zed.

**Comment by fasterthanlime** [comment]
> but zed incorrectly gives it other files

Okay but there is Rust code in the markdown file.

The markdown file is included as the “doc” attribute of the .rs file, and there’s runnable doc tests in there, hence the diagnostics etc.

Shouldn’t r-a care about this markdown file?

**Comment by osiewicz** [comment]
Yeah, we're not spec-compliant, but I'd expect RA to register for file watching of all files pulled in via macros like `include_str` or `include_bytes`.

Supporting completions in .md files is out of RA scope IMHO; we should implement it on Zed side by e.g. treating a language snippet in .md file as an untitled buffer that's registered with a language server (though AFAIK RA doesn't support unnamed buffers?)

**Comment by Veykril** [comment]
> > but zed incorrectly gives it other files
> 
> Okay but there is Rust code in the markdown file.
> 
> The markdown file is included as the “doc” attribute of the .rs file, and there’s runnable doc tests in there, hence the diagnostics etc.
> 
> Shouldn’t r-a care about this markdown file?

Two things:
1) r-a is not able to expand macro invocations in builtin attributes right now -> https://github.com/rust-lang/rust-analyzer/issues/8092
2) r-a's VFS does not currently handle files other than `.rs` and `.toml` files, so even if 1) worked it would still not include the readme -> https://github.com/rust-lang/rust-analyzer/issues/10178


> Shouldn’t r-a care about this markdown file?

So to answer, yes, r-a should kind of care (in that it should track the content of the file changing), but it won't ever care about markdown files being saved. (there is a different notification for file updates that would be relevant).

**Comment by filipwiech** [comment]
@osiewicz While the topic of Rust snippets in Markdown files seems more complex and would require further design and work, the changes in this PR still appear to make sense and be generally better than the current state if things. Would it make sense to go ahead and merge it, to avoid the most obvious issues and to improve the situation for all language servers (fix LSP violation)? :slightly_smiling_face:

**Comment by osiewicz** [comment]
@filipwiech yeah agree, we should not creep the scope; I think the solution in this PR might actually undernotify in certain cases (e.g. I'm pretty sure it won't notify RA about changes to .toml files), so I'll hack on it some more on the plane today.

**Comment by filipwiech** [comment]
@osiewicz Sorry to bother you, but it appears that this PR has broken support for Scala projects (with Scala extension, https://github.com/scalameta/metals-zed). After saving files with the Scala source code in the properly imported project LSP server doesn't get notified about the changes. AFAIK Metals (the LSP provider) does support the `didChangeWatchedFiles` client capability, so not sure what's going on here, maybe the watchers are not being correctly registered. :slightly_frowning_face:

**Pull request merged**
