### PR TITLE
Add a setting for custom associations between languages and files

### LINKED ISSUE #5178: A settings to allow mapping file types to known languages in Zed
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I want to see Cargo.lock content with highlights syntax’s.

### Describe the solution you'd like

Add a setting to settings.json

### If applicable, add mockups / screenshots to help present your vision of the feature

settings.json

```json
{
    "files": {
        "associations": {
            "*.avsc": "json",
            "Cargo.lock": "toml"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Closes #5178

Release Notes:

- Added a `file_types` setting that can be used to associate languages with file names and file extensions. For example, to interpret all `.c` files as C++, and files called `MyLockFile` as TOML, add the following to `settings.json`:

    ```json
    {
      "file_types": {
        "C++": ["c"],
        "TOML": ["MyLockFile"]
      }
    }
    ```

    As with most zed settings, this can be configured on a per-directory basis by including a local `.zed/settings.json` file in that directory.

### CODE REVIEW

**Comment by etmartinkazoo** [comment]
I am using Adonisjs and their Edge templatinig engine. The following should work but does not unless I am missing something:
```
"file_types": {
    "html": ["edge"]
 }
```

**Comment by maxbrunsfeld** [comment]
Right now, I believe the given string must either be the extension or the filename. We could change it to be a general string suffix check if people think that would be more useful.

**Comment by eyayaw** [comment]
Hi there, 
How can I associate [quarto](https://quarto.org) (.qmd) files to markdown? Thanks.
```yml
 {
"file_types": {
    "markdown": ["qmd"]
 }
 }
```

**Comment by John-Colvin** [comment]
> Right now, I believe the given string must either be the extension or the filename. We could change it to be a general string suffix check if people think that would be more useful.

Personally I would like a glob/regex, but whatever it is, it would be helpful for people like me if it was documented for a bunch of common cases - partly just to make sure it actually covers them!

**Comment by mloskot** [comment]
This is an awesome feature. It allows me to treat `log20240911.txt` files as `.log` file for https://github.com/nervenes/zed-log highligher :)

```json
  "file_types": {
    "LOG": ["log*.txt"]
  }
```

**Pull request merged**
