### PR TITLE
vim: Implement named registers

### PR DESCRIPTION
**Pull request by p-A-uLo**
Release Notes:

- vim: Add support for register selection `"a`-`"z`, `"0`-`"9`, `"-`. `"_` and `"%` ([#11511](https://github.com/zed-industries/zed/issues/11511))

### CODE REVIEW

**Comment by ConradIrwin** [comment]
:partying_face: Awesome!

@p-A-uLo I think it would be best to do this in the way we do marks where we just wait for input after the `"` instead of hardcoding the ascii range. Was there a reason you chose to do it this way?


Happy to talk this through if you want: https://calendly.com/conradirwin/pairing

**Comment by p-A-uLo** [comment]
@ConradIrwin Ok, I'll look into it.

**Comment by p-A-uLo** [comment]
@ConradIrwin I implemented the changes you proposed. I may have done something wrong though : to avoid conflicts I rebased and force pushed. Now CI fails. Could you have a look ?

**Comment by ConradIrwin** [comment]
re-running....

**Comment by ConradIrwin** [comment]
@p-A-uLo I read though this more, and looked at the vim docs, and came to a few conclusions:

* I think we should identify registers by `char` and store them in a hash map so we can support the various special vim registers as well as any characters people want to use, and we don't need to pre-allocate a mostly empty array.
* `"0` (used for yanks) is actually different from `"1-"9` (used for multi-line deletes) and they are both different again from `"-` (who knew!)
* `"+` and `"*` always talk directly to the system clipboard
* I think we can ship this without supporting all the special registers. For now I've added `"%`. I think `"/`, `"#`, `":`, `".` would be pretty easy to add, but `"=` is probably a won't fix for now.

I ended up refactoring as part of exploring how should work, so I've updated this branch with that.

Anything else you think we should do? Otherwise I think this is good to merge.

**Comment by 0x2CA** [comment]
hi ,[vim Command display #4447](#4447) The function is broken.

**Comment by ConradIrwin** [comment]
Thanks @0x2CA - added that!

**Comment by baldwindavid** [comment]
Amazing work, @p-A-uLo and @ConradIrwin ! This is a really big deal.

**Comment by p-A-uLo** [comment]
Thanks @ConradIrwin, this is making zed a quite good vim now !

**Comment by ConradIrwin** [comment]
thank you too! Keep the PRs coming :D.

**Comment by quarkw** [comment]
The implementation of this seems buggy, especially around visual selections.
Something like `"ayy` seems to work fine, but visually selecting a region, and then `"_y` (which is essentially a no-op) paves over the existing vim clipboard

**Comment by ConradIrwin** [comment]
Thanks for the heads up. Fix is here: https://github.com/zed-industries/zed/pull/18418

**Pull request merged**
