### PR TITLE
editor: Open file when double clicking line number in gutter

### PR DESCRIPTION
**Pull request by nbw**
Double clicking the line number in the gutter of a multibuffer (i.e.: in search results) opens the file at that line. Single click continues to act as a select. 

Kapture 2024-09-11 at 21 12 37

This is an ergonomic change that I think it makes it easier for the user to get to the file (and the line) they want from the multibuffer search results. I'm pretty sure vscode has this behavior so I had a habit of clicking the line number. 

cocredit shoutout to @osiewicz for the help. 

Release Notes:

- Added the ability to double click the line number in a multi-buffer (i.e.: in search results) and open the file at that line

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Passing by and noticing that this PR seems odd: 
* there's an alt-enter binding to open any line of the file
* there's a https://github.com/zed-industries/zed/blob/6841f7b9d792f6f89ca1b1bcbfca9dc763b66531/assets/settings/default.json#L232-L240

and overall, we seem to miss a good way to discover alt-enter.
Adding a 3rd way to open the location instead of fixing that seems quite redundant.

**Comment by nbw** [comment]
> there's an alt-enter binding to open any line of the file

> Adding a 3rd way to open the location instead of fixing that seems quite redundant.

We considered this setting. Though you'd be overriding the behaviour for any multibuffer. You could change `double_click_in_multibuffer ` to "open" and then clicking the highlighted text would open that file. So that would work if you're willing to lose "select" abilities.  

The intention here was to add a sensible default (which is subjective) to double clicking the line number in the gutter, not behind a config. it currently does nothing if you double click it (because any click on the gutter is registered as 3 clicks in the code). 

> we seem to miss a good way to discover alt-enter.

I just tried this. So you'd have to click a line then press alt + enter. That's cool! Good to know.  Not sure what I would've done to discover that (plus remember the hotkey)

You can also click the horizontal line that separates results (one of the Zed folks mentioned this, but it's not obvious:

Screenshot 2024-09-12 at 12 55 40

---

@SomeoneToIgnore would your suggestion then be to simply close this PR or what would be a good way to open the file from the search results at a specific line? Ideally something that doesn't involve learning a specific hotkey.

**Comment by SomeoneToIgnore** [comment]
I do not insist on closing the PR (I will not review or merge this since disagree with that but it's subjective), but yeah, I'd rather solve the

> Not sure what I would've done to discover that (plus remember the hotkey)

and keep this as the main way of doing things, as this is Zed's "correct" way of doing things instead of introducing another way to open the editor.


Unfortunately, this seems quite hard as we've tried a bunch of things by this point and they did non raise the awareness that much.

At this point, I wonder if we should do some cursor-like tutorial GIFs shown near the welcome page or some hover popover 🙂

**Comment by notpeter** [comment]
> Not sure what I would've done to discover that (plus remember the hotkey)

Currently we're not showing the `alt-enter` hotkey in the `Jump to File` tooltip which seems like a bug.  `Tooltip::for_action` should pick it up from the keymap.

Screenshot 2024-09-15 at 20 01 45

**Comment by maxdeviant** [comment]
Thank you for putting together this PR.

I agree with @SomeoneToIgnore in that I don't think we should be adding more ways of navigating when we already have two ways that folks have a hard time understanding.

I don't think that adding a third way of doing that same thing that is also not very discoverable—I don't know that I would try double-clicking on the line number—is beneficial.

Going to close this, for now, but we may revisit in the future.

**Pull request closed without merging**
