### PR TITLE
Rosé Pine: Change `#f5c177` to `#f6c177`

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
As discussed in #themes-and-ui

Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
Can we see a side by side screenshot of this change?

**Comment by ThatOneCalculator** [comment]
gold_sidebyside

**Comment by mikayla-maki** [comment]
Perfect, thank you!

**Comment by ThatOneCalculator** [comment]
Ty!

**Pull request merged**
