### PR TITLE
Add limit to minimum window size

### PR DESCRIPTION
**Pull request by Aaron-212**
Release Notes:

- Add a limit to the minimum window size on macOS.

Here's the minimum window before change:
image

After change:
image

### CODE REVIEW

**Review by diaslui — APPROVED** [review]

**Comment by JunkuiZhang** [comment]
Is this PR trying to fix #11920 ?

**Comment by Aaron-212** [comment]
> Is this PR trying to fix #11920 ?

Might be related, but I don't think this PR will fix it. Adding a limit to the window is just for good practice.

**Comment by MatinAniss** [comment]
This should definitely not be hard coded and should be set when creating the window with `WindowOptions`. I can see other GPUI applications wanting different minimum sizes.

**Comment by Aaron-212** [comment]
Just refactored the code to expose the window_min_size options, but I don't know if it's the right way.

**Comment by ConradIrwin** [comment]
Thanks for this!

**Pull request merged**
