### PR TITLE
Polish multibuffer UI

### PR DESCRIPTION
**Pull request by alejandrovrojas**
This branch is mostly intended for polishing small UI details in the multi-buffer view. Specifically, the jump-to-file subheaders are very large and jarring compared to the rest of the UI in the current version. There's also other UI quirks like the fact that the "expand excerpt" (upwards) area is actually clickable and jumps to the file matched – which I find to be an anti-pattern considering the hitbox is completely invisible to the user.

Notes:
- I'd like some feedback on how to keep the subheader text size to match and scale with the rest of the UI, respecting the `ui_font_` settings.

Release Notes:
- N/A

Screenshot 2024-10-25 at 13 26 56

### CODE REVIEW

**Comment by alejandrovrojas** [comment]
@cla-bot check

**Comment by danilo-leal** [comment]
Heya @alejandrovrojas, thanks for putting the PR up! I'd probably hold off on these changes, though, as we have ongoing designs for multibuffers that will change some of these things, and elements of your suggestion go in a different direction. The changes we're exploring are motivated by the fact that one of the gems (if not _the_ gem) of multibuffers is that all of the displayed excerpts are editable, allowing you to do things such as find and replace across multiple files simultaneously. We're seeing that this is not immediately clear to some people, and dividers that span the tab container's whole width are possibly contributing to giving a sense of rigid separation between the files, among other things. We might also go with a significantly different header design, one that is lighter and more integrated into the multibuffer editor.

In any case, I'm super curious about this point, though:
> ...which I find to be an anti-pattern considering the hitbox is completely invisible to the user.

What do you mean by being completely invisible here? You can click anywhere on the header (not just close to the arrow icon), and it will take you to the displayed file.

**Comment by alejandrovrojas** [comment]
@danilo-leal Agreed! I also noticed while testing that the editor could use more UI affordances like dashed lines to better visualize the split between excerpts and so on. Design-wise the multibuffer currently works as _one editor split into multiple excerpts_ whereas a better solution is _one view containing multiple editors_.

The multibuffer is definitely a gem. There's a [discussion from last year](https://github.com/zed-industries/zed/discussions/6615) with many great suggestions that I hope gain some traction.

As for the invisible hitbox I meant the area inbetween excerpts of the same file!

Screenshot 2024-10-25 at 14 35 23

**Comment by danilo-leal** [comment]
Thanks for understanding! 🙏  We'll keep the feedback in mind as we get closer to pushing design changes to the multibuffer UI.

**Pull request closed without merging**
