### PR TITLE
Add design tweaks to the AI configuration panel

### PR DESCRIPTION
**Pull request by danilo-leal**
This PR polishes elements around setting up LLM providers on the Assistant panel, including:

- [x] Adding banners for promoting Zed AI and to deal with the "No provider set up" scenario
- [x] Tweaking the error popover whenever there's no API key added
- [ ] Making configuration panel scrollable

--- 

Release Notes:

- N/A

### CODE REVIEW

**Comment by mrnugget** [comment]
@bennetbo and I just decided to merge this, so we can build on top of it on `main`.

**Comment by ukd1** [comment]
What's the workaround for this in the release version?

**Comment by bennetbo** [comment]
@ukd1 Sorry about the bad experience, we're going to release a patch to stable today that will fix this.
If you really can't wait you could try to set the `ui_font_size` setting to something very small, like `"ui_font_size": 10`, then you should be able to see the whole view even if you're display is small.

**Comment by ukd1** [comment]
@bennetbo no problems - hahaha I could have done that, but I just make the ux scale on my display smaller to get to the Ollama settings. Working great, outside the scrolling - thanks for the work! 🙇‍♂️

**Pull request merged**
