### PR TITLE
wip: Add Helix keybindings

### PR DESCRIPTION
**Pull request by maan2003**
Release Notes:

- N/A

---
very wip, will cleanup _eventually_

to activate helix mode:
- add `"helix_mode": true` in settings 
- open zed
- press `i<esc>` (insert mode -> escape) to enter helix mode

you will see -- HELIX -- in status bar

### CODE REVIEW

**Comment by noahfraiture** [comment]
Hello,
If there is any way to help I think a lot of person would be glad to. Currently there's a keymap to match the binding but this very far from the actual helix motion. https://github.com/zed-industries/zed/issues/4642#issuecomment-2227421718

**Comment by maan2003** [comment]
I am still working on this, but only over weekends. 

latest round of improvements include a correctly working `xd` and `xc` :)

(which are the really tricky)

@ConradIrwin: should I try to get it merged in extermely broken state under a feature flag? (most of bindings have a stroke on seeing EOF or soft warp)

**Comment by ConradIrwin** [comment]
@maan2003 I think that makes sense, yes; then people can help more easily by sending PRs to main instead of your branch.

When you think this is ready for me to take a pass, let me know.

**Comment by 1925381584** [comment]
I am waiting this feature every day

**Comment by fazibear** [comment]
Hey! Just was thinking about start to implement helix/kakoune mode for zed and found this one. 
I'm just curious why this mode is implemented as part of vim_mode crate instead of separate one?

Idea is to start changing vim_mode = true to modal_mode = "vim|helix", copy vim_mode crate as separate helix_mode and make changes there. Eventually extract common stuff to modal_mode. 

What do you think?

**Comment by maan2003** [comment]
> I'm just curious why this mode is implemented as part of vim_mode crate instead of separate one?

because spliting crates is just an optimization to save compile time :)

Yes it should be a separate crate in future when it is ready, but I didn't want to think about circular deps.

**Comment by Suyashtnt** [comment]
> > I'm just curious why this mode is implemented as part of vim_mode crate instead of separate one?
> 
> because spliting crates is just an optimization to save compile time :)
> 
> Yes it should be a separate crate in future when it is ready, but I didn't want to think about circular deps.
> 
> > I am waiting this feature every day
> 
> me too

An Idea would be to split it into 3 crates:
- `modal`
- `vim`
- `helix`

`modal` contains code thats shared by both (and potentially future) vim and helix modal modes. This should also fix circular deps.

**Comment by linuxmobile** [comment]
> I am waiting this feature every day

me too.

**Comment by noahfraiture** [comment]
It would maybe good to stop pushing the author since he said he can only works weekend, give him time to cook

**Comment by maan2003** [comment]
I am going to close this for now because I am used to vim keybindings.

**Comment by nvkomata** [comment]
> I am going to close this for now because I am used to vim keybindings.

your reason sucks

**Comment by Guekka** [comment]
> > I am going to close this for now because I am used to vim keybindings.
> 
> your reason sucks

Please be respectful. Developers can choose what they want to work on

**Comment by maan2003** [comment]
> your reason sucks

agreed that reason sucks for lot of people. 

You are free to continue working on helix keybindings from where I stopped.

I would love to use helix bindings in future. But implementing helix bindings is lot of work.

**Comment by Swoorup** [comment]
> > I am going to close this for now because I am used to vim keybindings.
> 
> your reason sucks

Great we have a new committed person who is ready to put in the work. Thanks in advance. Looking forward to helix bindings.

**Comment by neel04** [comment]
This is unproductive, and frankly a waste of everyone's time and energy - especially for the watchers who get pinged everytime. Please refrain from commenting unless you have something of substance to add.

OP has made it clear that it's a lot of work that they can't commit to. At this point, I think a better solution would be to urge `helix` core devs to either a) invest more effort in this PR or b) Perhaps setup a bounty for this feature.

I know this is disappointing - I myself have been waiting for this feature for quite a while - but harassing the OP gets us nowhere.  Please be civil.

**Comment by noahfraiture** [comment]
@maan2003 Hello, is it possible to know where you were and what is left to do ? It would be easier to continue this PR if we knew what we could do. Also I think that it would be great to have a merge quickly to open to contributions

**Comment by ConradIrwin** [comment]
👋 Thanks for all your work on this @maan2003!

I've talked with a few people about building Helix support into Zed. Realistically I don't have the time to do this myself, but I am happy for anyone to work on this.

We've tried two different approaches so far:
* A new helix crate that probably depends on the vim crate, but adds more stuff, and maintains the mode separately.
* Updating the vim crate to support helix too depending on a config flag.

It's not yet clear which one is better (I lean towards including it in the vim crate because it seems like much of the state management is the same as vim, BUT, most of the actions/motions are different); so happy for whoever picks this up next to choose.

In terms of first steps, I'd love to get to the point that we have a basic set of helix features (maybe just a setting and the ability to toggle between normal/insert mode) merged and disabled behind a compile time flag. That will let people who want to use it and improve it do so. Once we reach a point where we have middling-to-good helix support (i.e. most motions working kind of right) we can remove the flag. I think this is too big of a feature to try and land in one PR.

Once Zed's extension APIs are good enough to implement helix, it would make more sense to be an extension, but that is likely very very far away, so I think if we want this in the next year or two, we should build it in.

I'm happy to pair with anyone who's interested in making progress on this: https://calendly.com/conradirwin/pairing.

**Comment by maan2003** [comment]
superseded by https://github.com/zed-industries/zed/pull/17575

**Pull request closed without merging**
