### PR TITLE
Move from Zed fonts to IBM Plex

### PR DESCRIPTION
**Pull request by ConradIrwin**
Release Notes:

- Changed the default fonts to IBM Plex Sans and IBM Plex Mono. If you'd like to go back to using Zed Sans/Zed mono you need to [download](https://github.com/zed-industries/zed-fonts/releases/tag/1.2.0) them and install them.

### CODE REVIEW

**Comment by shinebayar-g** [comment]
Ugh, is zed font dead? This new font looks wildly different the previous one.

**Comment by kelvinpraises** [comment]
This could have been an opt-in option, no one likes a jarring visual change in product updates.

**Comment by RustoMCSpit** [comment]
> This could have been an opt-in option, no one likes a jarring visual change in product updates.

agreed

**Comment by sebastiansandqvist** [comment]
Installing Zed Sans locally and having it set as the `ui_font_family` in my settings still led to a somewhat jarring font change on upgrade. It appears that a condensed version of the font is now the default. Is there a way to tell Zed to use a specific font variant? And if so, which variant was the default before?

**Comment by kelvinpraises** [comment]
Let me share what did it for me:

1. Install `zed-app-fonts-1.2.0` from [here](https://github.com/zed-industries/zed-fonts/releases/tag/1.2.0) as linked above
2. On Zed press the key binding `⌘,` to open the settings
3. In the JSON file add the following fields
```
  {
    ...
    
    "buffer_font_family": "Zed Mono",
    "ui_font_family": ".SystemUIFont"
  }
```


Also, do check out the [settings file change](https://github.com/zed-industries/zed/pull/13596/files#diff-42e01d7aacb60673842554e30970b4ddbbaee7a2ec2c6f2be1c0b08b0dd89631) to roll back commits as you may

**Comment by kelvinpraises** [comment]
>  Is there a way to tell Zed to use a specific font variant?

Zed auto-infers _most_ of your system fonts, it auto-suggests, as you type in the font you want, as long as you've installed the fonts locally and are editing the right settings field.

**Comment by sebastiansandqvist** [comment]
> Zed auto-infers _most_ of your system fonts, it auto-suggests, as you type in the font you want, as long as you've installed the fonts locally and are editing the right settings field.

What I mean by variant is that within the `Zed Sans` font family, there are light/extended/oblique/italic variants. In my case it appears that I am getting a condensed variant of Zed Sans. I'd like to figure out how to get the ui to have the same font and variant I had before.

**Before installing the preview update:**
post-update

**After installing the preview update:**
pre-update

**After update with no font specified:**
post-update-no-font

**Comment by kelvinpraises** [comment]
Oh okay, check out [Issue 5028](https://github.com/zed-industries/zed/issues/5028) on how to switch between variants and edit the `buffer_font_family` to see the effect on your main editor pane while `ui_font_family` affects the UI

**Comment by sebastiansandqvist** [comment]
> Oh okay, check out [Issue 5028](https://github.com/zed-industries/zed/issues/5028) on how to switch between variants and edit the `buffer_font_family` to see the effect on your main editor pane while `ui_font_family` affects the UI

Ah, perfect, thank you! `"ui_font_family": "Zed Sans Extended"` did the trick for me, although there is a warning that it's an invalid value.

**Comment by RustoMCSpit** [comment]
> > Oh okay, check out [Issue 5028](https://github.com/zed-industries/zed/issues/5028) on how to switch between variants and edit the `buffer_font_family` to see the effect on your main editor pane while `ui_font_family` affects the UI
> 
> Ah, perfect, thank you! `"ui_font_family": "Zed Sans Extended"` did the trick for me, although there is a warning that it's an invalid value.

sounds like there is an error there, make an issue about it?

**Comment by huypham50** [comment]
Is there a reason for this change? I genuinely prefer `Zed` fonts. Have to do this now 😭 
```
"ui_font_family": "Zed Sans Extended",
"buffer_font_family": "Zed Mono Extended",
```

**Comment by medzernik** [comment]
such a shame, the zed font is the reason i fell in love with the clean code. Gotta install it manually now

**Comment by ConradIrwin** [comment]
TBH that was my initial reaction for the mono too. After a bit of use though I've come round. I particularly like the fun  italics and the `{}` braces:
Screenshot 2024-07-10 at 11 14 51

Plex Sans is a lot better for a UI font than Zed Sans was (to the point where we can actually enable it by default) which distinguishes Zed nicely.

It also saves us about 8Mb of space, and fixes some font fallback issues on Linux. The Zed fonts were gigantic and configured a bit wrong (it turns out in hindsight :D).

Obviously fonts are a personal thing, so we've left the old ones available, but we think this is a better default for everyone.

**Comment by RustoMCSpit** [comment]
> Plex Sans is a lot better for a UI font than Zed Sans was (to the point where we can actually enable it by default) which distinguishes Zed nicely.

why?

> The Zed fonts were gigantic and configured a bit wrong (it turns out in hindsight :D).

will that be fixed

**Comment by richardhenry** [comment]
Plex Mono seems to have a bunch of issues where characters overlap. It's generally pretty subtle, but here's an obvious example:

Screenshot 2024-07-10 at 12 11 14 PM
Screenshot 2024-07-10 at 12 11 20 PM

Compared to Zed Mono:

Screenshot 2024-07-10 at 12 12 35 PM
Screenshot 2024-07-10 at 12 12 42 PM

Is this an issue with the Zed rendering engine, or does the font suck?

**Comment by joaokamun** [comment]
> Plex Mono seems to have a bunch of issues where characters overlap. It's generally pretty subtle, but here's an obvious example:
> 
> Screenshot 2024-07-10 at 12 11 14 PM Screenshot 2024-07-10 at 12 11 20 PM
> Compared to Zed Mono:
> 
> Screenshot 2024-07-10 at 12 12 35 PM Screenshot 2024-07-10 at 12 12 42 PM
> Is this an issue with the Zed rendering engine, or the font? Or is it intentional? It looks confusing to me.

This seems font ligature feature, you can disable with the following settings:

```
  "buffer_font_features": {
    "calt": false
  }
```

**Comment by richardhenry** [comment]
Thanks @joaokamun — these character pairs seem like strange choices for ligatures, IMO

**Comment by icoigo** [comment]
> TBH that was my initial reaction for the mono too. After a bit of use though I've come round. I particularly like the fun italics and the `{}` braces: 

Just wonder how to make the "comments" part to be italics font sytle.

**Comment by icoigo** [comment]
> > TBH that was my initial reaction for the mono too. After a bit of use though I've come round. I particularly like the fun italics and the `{}` braces:
> 
> Just wonder how to make the "comments" part to be italics font sytle.

I just figured out, this setting works.
```
"experimental.theme_overrides": {
    "syntax": {
      "comment": {
        "font_style": "italic"
      }
    }
  },
```

**Comment by RustoMCSpit** [comment]
can someone compose a full settings copy and paste text that includes all features of the previous font setup

> > > TBH that was my initial reaction for the mono too. After a bit of use though I've come round. I particularly like the fun italics and the `{}` braces:
> > 
> > 
> > Just wonder how to make the "comments" part to be italics font sytle.
> 
> I just figured out, this setting works.
> 
> ```
> "experimental.theme_overrides": {
>     "syntax": {
>       "comment": {
>         "font_style": "italic"
>       }
>     }
>   },
> ```

**Comment by arbales** [comment]
Hey! Came here to figure out how to get back to Zed Sans (Extended), and have to say I'm surprised and bummed by this change. I say this as both a developer and a professional designer — Zed Sans was and is great, and it was a strikingly positive first impression when I started using Zed. 

I'm curious what motivated the change?

**Comment by federicoangelli** [comment]
Another option for going back to Zed Mono would be to install the ZedMono Nerd Font from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/ZedMono.zip
(I'm using the "extended regular" one from that zip).

Then, configure it as follows in **settings.json**:
`"buffer_font_family": "ZedMono Nerd Font",`

That should be it 😄

**Comment by heiskr** [comment]
I'm curious, given it sounds like file size was the main concern of the change... I would think to use the built-in UI and monospace fonts for the operating system as the default and let folks overwrite it in their settings; I'm sure it's often the first setting most folks will change after installing Zed.

**Comment by sebastiansandqvist** [comment]
> Hey! Came here to figure out how to get back to Zed Sans (Extended), and have to say I'm surprised and bummed by this change. I say this as both a developer and a professional designer — Zed Sans was and is great, and it was a strikingly positive first impression when I started using Zed.

Totally agree! I love Zed Sans. If file size is the primary concern, could the font's (optional) installation be part of the onboarding flow instead? Post-install when selecting default keybindings and choosing whether to have vim mode enabled, "Install and apply Zed fonts" could be one of those options.

**Comment by arbales** [comment]
Was size the major factor? The Zed fonts are ~16x larger but also contain ~28x more glyphs. If size were the driver, you could build the fonts with a reduced glyph set. 

In any case, I'd be curious to get @iamnbutler's take.

**Comment by RustoMCSpit** [comment]
> > Hey! Came here to figure out how to get back to Zed Sans (Extended), and have to say I'm surprised and bummed by this change. I say this as both a developer and a professional designer — Zed Sans was and is great, and it was a strikingly positive first impression when I started using Zed.
> 
> Totally agree! I love Zed Sans. If file size is the primary concern, could the font's (optional) installation be part of the onboarding flow instead? Post-install when selecting default keybindings and choosing whether to have vim mode enabled, "Install and apply Zed fonts" could be one of those options.

this seems like a great idea! i can make it an issue if wanted or we can continue to discuss it here?

**Comment by barrelltech** [comment]
Don't know where to leave this issue, but the ligatures don't match the curly braces, which looks pretty awful:

CleanShot 2024-07-15 at 12 40 51@2x

Also I mentioned elsewhere, but at least with Elixir code, you end up with mostly italic code:

GSM5cl7WwAAEfYP

Any while I agree that fonts are a personal preference... the new IBM Plex is one of the _worst_ fonts I've ever seen. I've spent over a week with it now and I can honestly say I hated it with a burning passion. I'm not being hyperbolic when I say I've developed a physical revolution to it.

YMMV but I know Zed is all about FTUX and UI. I would have to imagine this font will negatively impact the FTUX for most people.

(I've reinstalled the old Zed font which I genuinely enjoyed, so I'm happy, only leaving as feedback)

**Comment by baldwindavid** [comment]
> Also I mentioned elsewhere, but at least with Elixir code, you end up with mostly italic code:

@barrelltech I don't see anything italicized in the Elixir files I'm looking at. 🤷 

---

fwiw, I expected to hate this font since that seems to be the sentiment here. I've been using FiraCode Nerd Font Mono for a couple years and this doesn't seem like much a departure

I'd probably switch to it, but running into what appears to be a rendering issue with the buffer font size at 16 for the letter "f". You can see in the screenshots that the top portion of the letter is fine at 15 and 17, but partially cut off at 16. Sadly, this is the font size I use. 😿 

15
Screenshot 2024-07-15 at 5 39 18 PM

16
Screenshot 2024-07-15 at 5 40 00 PM

17
Screenshot 2024-07-15 at 5 40 31 PM

**Comment by TheRedXD** [comment]
Not gonna lie, the IBM fonts suck for code editing. I've tried them on many different editors, and I've never been happy with them.

The Zed fonts are THE BEST THAT I'VE SEEN for code editing, they're ridiculously easy on my eyes, and for someone who sits at his computer for the bigger part of the day - it's a big benefit to not over-stress your eyes with hard to read fonts.

It would be amazing if the zed fonts were brought back into zed as the default fonts, I don't see much of a downside to them being included. I'm surprised this even got merged, as this doesn't really make too much sense.

**Comment by shinebayar-g** [comment]
For those who don't like the new font, https://www.jetbrains.com/lp/mono/ is the closest one to the old one, which seems a much better option.

**Comment by RustoMCSpit** [comment]
> The Zed fonts are THE BEST THAT I'VE SEEN for code editing, they're ridiculously easy on my eyes, and for someone who sits at his computer for the bigger part of the day - it's a big benefit to not over-stress your eyes with hard to read fonts.

i agree, it was easily the best code editor font ive ever seen as well in all my programming years. it's sad to see it so unceremoniously removed. ive made a new issue request asking it to have a new install

**Comment by RustoMCSpit** [comment]
for all who are curious: "The WidthClass is set to 400 instead of 300, which breaks cosmic texts fallback stack on Linux. (Also they're really big, for some reason I don't know yet)" https://github.com/zed-industries/zed/issues/15053#issuecomment-2250921434

if anyone knows how to fix that, thatd be great.

**Comment by icoigo** [comment]
> TBH that was my initial reaction for the mono too. After a bit of use though I've come round. I particularly like the fun italics and the `{}` braces: Screenshot 2024-07-10 at 11 14 51
> 
> Plex Sans is a lot better for a UI font than Zed Sans was (to the point where we can actually enable it by default) which distinguishes Zed nicely.
> 
> It also saves us about 8Mb of space, and fixes some font fallback issues on Linux. The Zed fonts were gigantic and configured a bit wrong (it turns out in hindsight :D).
> 
> Obviously fonts are a personal thing, so we've left the old ones available, but we think this is a better default for everyone.

The `doc comments` is not italics any more. Does anyone knows how to fix it?

**Comment by RustoMCSpit** [comment]
> for all who are curious: "The WidthClass is set to 400 instead of 300, which breaks cosmic texts fallback stack on Linux. (Also they're really big, for some reason I don't know yet)" [#15053 (comment)](https://github.com/zed-industries/zed/issues/15053#issuecomment-2250921434) https://github.com/zed-industries/zed/pull/13596#issuecomment-2221061672
> 
> if anyone knows how to fix that, thatd be great.

all of you asked why this was done, the above comment cites the reason in a different discussion (as well as another dev saying virtually the same thing)

@huypham50 
@arbales 
@TheRedXD

**Comment by notpeter** [comment]
> The `doc comments` is not italics any more. Does anyone knows how to fix it?

There is an example in the docs of how to make comments use italics:
https://zed.dev/docs/themes#theme-overrides

**Comment by icoigo** [comment]
> > The `doc comments` is not italics any more. Does anyone knows how to fix it?
> 
> There is an example in the docs of how to make comments use italics: https://zed.dev/docs/themes#theme-overrides

This is only for `comments ( starts with //)`, but for the `doc comments (starts with ///)` is not italics.

**Comment by notpeter** [comment]
I updated the docs for this in https://github.com/zed-industries/zed/pull/19694.

Use this instead:
```json
{
  "experimental.theme_overrides": {
    "syntax": {
      "comment": {
        "font_style": "italic"
      },
      "comment.doc": {
        "font_style": "italic"
      }
    }
  }
}
```

**Comment by icoigo** [comment]
> @icoigo I've updated the docs to cover doc strings too in #19694.
> 
> Use this instead:
> 
> ```json
> {
>   "experimental.theme_overrides": {
>     "syntax": {
>       "comment": {
>         "font_style": "italic"
>       },
>       "comment.doc": {
>         "font_style": "italic"
>       }
>     }
>   }
> }
> ```

cool, thanks

**Pull request merged**
