### PR TITLE
Add a badge to the bell icon on new notifications

### PR DESCRIPTION
**Pull request by realharley91**
It changes the icon if a new notification event is consumed and changes it back to normal upon toggling NotificationPanel.

Added a new field to NotificationPanel:
	- have_unseen_notifications: bool

Added a new icon asset
	- IconName::BellBadged => "assets/icons/bell_badged.svg"

Release Notes:

- Added a badge to bell icon for new notifications ([#6721](https://github.com/zed-industries/zed/issues/6721)).

### CODE REVIEW

**Comment by dammerung2718** [comment]
I sat down and wrote something quick, unfortunately IconName svg's do not support color so right now it looks like this:

Screenshot 2024-01-26 at 10 40 09

It is small but clear enough that I know I have unseen notifications. The way it works is totally client side and I may be uninformed about the backend capabilities. Pending review from the zed team.

**Comment by SomeoneToIgnore** [comment]
Looks interesting, a few notes from me:

* image

As you can see, our copilot icon has some round element on it already, which is in kind of disarray with the new icon's circle.
I would at least make the new circle larger and maybe also place similarly to copilot's?

* I like the absence of color on the icons, so the whole app does not look like a rainbow, so let's make it colorless for now, as other icons?

* `have_unseen_notifications` -> `has_unseen_notifications`

* if I have a chat open and get a @mention which I instantly see, I still get the unseen notification in the panel, that is not very useful


I would strongly insist on the last bullet to be fixed, and would appreciate the others to get fixed too.

Not sure if you are aware yet (and whether it will work for you, but that we should fix if it doesn't), but there's a way to test collab things locally: https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__local_collaboration.md

**Comment by dammerung2718** [comment]
Right now it looks like this and I updated the logic to take into account whether we are showing the corresponding notification on screen at the moment.

Screenshot 2024-01-26 at 13 24 44

I couldn't align the two dots perfectly together, several attempts I tried:

- Changing the viewport so I can squeeze the badge a bit more to the bottom caused the whole svg to shrink so I scrapped that idea.
- I tried moving the pixels down more than the viewport allowed but then the pixels got cut around the borders.

Because they are different in resolution I eyeballed the badge icon, it blends seemlessly from afar but is flawed in pixels.

**Comment by SomeoneToIgnore** [comment]
Thanks for the update, looks really nice to me.

Agree that the aligning could be better, but have no good design skills myself hence linking @maxdeviant to help.
Maybe, it's enough for the merge and we can deal with the alignment some time later.

**Comment by maxdeviant** [comment]
Sorry for the delay in reviewing this.

I think the icon is serviceable for now.

Thank you for the PR, @dammerung2718!

**Pull request merged**
