### PR TITLE
gpui: Fix window display on Windows

### LINKED ISSUE #18610: Zed Cannot Display a Window on Windows OS after Being Built
### Check for existing issues

- [X] Completed

### Descriptions
I cloned the source code, built and tried running it, but it cannot display an window, and threw errors instead.

Here are the errors:

```text
[2024-10-02T14:04:52+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:52+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:53+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:53+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:53+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-02T14:04:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-02T14:04:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-02T14:04:55+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:55+08:00 ERROR] Error { code: HRESULT(0x80070057), message: "参数错误。" }
[2024-10-02T14:04:55+08:00 ERROR] Error { code: HRESULT(0x80070057), message: "参数错误。" }
[2024-10-02T14:04:55+08:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-02T14:04:55+08:00 ERROR] no worktrees when constructing LocalLspAdapterDelegate
```
### How to Reproduce
1. Clone this repo on a Windows computer.
2. Just build it!
3. Double-click `zed.exe` and wait for errors.

### Environment

As what the bug described, I cannot run the command and have to provide the environment manually:
Zed: v0.156.0 (Zed Dev https://github.com/zed-industries/zed/commit/563a1dcbab67b58a6c9cf10fe4dea35d862376d1)
OS: Windows 10.0.22631
Memory: 15.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU || Nvidia Corporation || 32.0.15.6094

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
- Closes #18610

This PR addresses the same issue as PR #18578. After a full day of research and testing, I believe I’ve found the best solution to resolve this issue. With this PR, the window creation behavior on Windows becomes more consistent with macOS:

- When `params.show` is `true`: The window is created and immediately displayed.
- When `params.show` is `false`: The window is created but remains hidden until the first call to `activate_window`.

As I mentioned in #18578, `winit` creates hidden windows by setting the window's `exstyle` to `WS_EX_NOACTIVATE | WS_EX_TRANSPARENT | WS_EX_LAYERED | WS_EX_TOOLWINDOW`, which is different from the method used in this PR. Here, the window is created with normal parameters, but we do not call `ShowWindow` so the window is not shown.

I'm not sure why `winit` doesn't use a smilliar approach like this PR to create hidden windows. My guess is that `winit` is creating this hidden window to function as a "DispatchWindow" — serving a purpose similar to `WindowsPlatform` in `zed`. To ensure the window stays hidden even if `ShowWindow` is called, they use the `exstyle` approach.

With the method used in this PR, my initial tests haven't revealed any issues.

Release Notes:

- N/A

### CODE REVIEW

**Comment by shenjackyuanjie** [comment]
last commit tested, works

**Comment by Long0x0** [comment]
winit does create windows using the `WS_EX_APPWINDOW` flag ([code here](https://github.com/rust-windowing/winit/blob/32cd1ad9a741728ca6ccf4f8b3e63e6324a51392/src/platform_impl/windows/window.rs#L1314)). The window you mentioned is an extra one created for the event loop that is never visible.

**Comment by evaneaston** [comment]
I've verified that this fixes the reported problem.  I have no idea if it's the correct way to solved it.

**Comment by co-bby** [comment]
> last commit tested, works
> 
> for anyone who wants to tested out, check out https://github.com/shenjackyuanjie/zed-win-build/releases/tag/0.156.0%2B85eceb7194-1.2.1 for prebuilt binary

Thank you

**Comment by co-bby** [comment]
Tested is working

**Comment by MarvinMynx** [comment]
I had the same issue, can confirm that this fix works too.

**Comment by zhouxs1023** [comment]
still turn on error as below:
Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }

**Comment by shenjackyuanjie** [comment]
> still turn on error as below: Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }

this error is not related to this issue

**Comment by AFellowSpeedrunner** [comment]
Any timeframe for when this gets merged?

**Review by SomeoneToIgnore — APPROVED** [review]
I have no clue about these changes, but given the previous change got merged and this is tested by others and reported to be fixing the issue, let's merge this and @mikayla-maki  can post-review if needed.

Odd that I have never experienced that in my Windows builds.

**Comment by getpool** [comment]
最近更新编译，怎么不能记录保存窗口最大化了呢，每次都需要再点最大化。

**Comment by JunkuiZhang** [comment]
> 最近更新编译，在windows下，没办法保存正确的窗口大小，没办法最大化，删除db，也是一样。 我只能手动修改db.sqlite,把window_with和window_height改成我的显示尺寸大小。

I will open a PR to address this tomorrow.

> 大佬能不能增加个兼容一下，老旧设备不支持vulkan的问题呢。

The only possible solution is porting the backend from blade to directX, but zed team rejected my PR of porting to directX. So, I can’t, sorry.

**Pull request merged**
