### PR TITLE
Handle first click on Zed window

### LINKED ISSUE #4336: Focus editor component under cursor instead of last active component
### Check for existing issues

- [X] Completed

### Describe the feature

Please propagate the initial click that brings focus to the editor so that the clicked element inside the editor gets focus. Tried vscode, it focuses on click. Also in chrome browser, clicking on a different tab will switch to it immediately.

### If applicable, add mockups / screenshots to help present your vision of the feature

Problem:

Since switching from vs code to zed I have been sometimes typing into the wrong panel in the zed editor. It happens when you want to swith to Zed from another application by clicking (e.g. I click on the terminal panel), but Zed does not switch focus to it, opting to keep the focus the same as when you left the editor. 

Current process: 
1) Zed main panel active
2) switch to another application, keeping Zed visible
3) click on Zed terminal panel
4) start typing -> source code in the main panel is being changed (or whichever panel was focused when leaving zed)

Changed flow:
1) Zed main panel active
2) swith to another application, keeping Zed visible
3) click on Zed terminal panel
4) (CHANGE) start typing -> terminal has become focused as the user clicked on it. User is successfully typing commands in the terminal.

### PR DESCRIPTION
**Pull request by xyzqm**
Fixes #4336 

Release Notes:
- Zed now responds to the first, focusing, click on the application window.

### CODE REVIEW

**Comment by danielzsh** [comment]
@mikayla-maki I refactored the `first_mouse` handling into ClickEvent, what do you think?

**Comment by mikayla-maki** [comment]
This came out pretty nice! Let me test drive this a bit tomorrow and see how it feels.

**Comment by mikayla-maki** [comment]
Gave this a test drive, it seems like this has caused a pretty nasty bug where first clicks are treated like a drag event. In this example video, I only click on the terminal-editor border, and I only click on the assets folder, but both cause dragging behavior.



https://github.com/zed-industries/zed/assets/2280405/46b9a4e2-5a66-451d-8bbc-b84e213e0ef6

**Comment by danielzsh** [comment]
Oh yikes, I only tested double clicking the files; thanks for the catch!

**Comment by mikayla-maki** [comment]
This works great, thank you!

**Comment by mikayla-maki** [comment]
A good follow up for this PR might be making non-focused hovers work. I noticed that firefox does do a little styling of non-focused tabs you hover over, and I think that would be good behavior for things like the status bar buttons.

**Pull request merged**
