### PR TITLE
gpui: Fix `cx.bounds`, `cx.open_window` position on macOS

### PR DESCRIPTION
**Pull request by huacnlee**
Release Notes:

- gpui: Fixed `cx.bounds` method to get correct `y` position on macOS.
- gpui: Fixed `cx.open_window` position when macOS Dock is existed.
- Fixed call notification and reopen window position.

## Before

image

https://github.com/zed-industries/zed/assets/5518/ab925779-4253-4b27-9084-01023888087f

## After

image

https://github.com/zed-industries/zed/assets/5518/8793824a-8b74-4913-8204-7b39649aeeed

---

The case is I have made a Popover by use child window, the coordinate of the window is always can't placement a right position.

So, I make this example to test the `cx.bounds` and set bounds to window.

---

By this test, is the `cx.bounds` have a bug?

For example the **Top Left** window, we give it origin (150,150), but it `cx.bounds()` returns (150,262)

> On the window label, middle line is the `bounds` that we set to the window, last line is `cx.bounds()` result.

Display 1:

CleanShot 2024-07-10 at 14 52 26@2x

---

Or is there something I missed. Is it correct to use `cx.bounds` method to get the bounds of the current window?

At the same time, I also found that when there are multiple screens, the information obtained by cx.bounds is very different on different screens, and it seems that the origin is not relative to the screen.

Display 2:

SCR-20240710-nkmq

### CODE REVIEW

**Comment by huacnlee** [comment]
https://github.com/zed-industries/zed/pull/14044/commits/dedaa51f4484b7d9c5b34fc19d6cc84ef1aa21c0

This commit has fixed the macOS position, now `cx.bounds()` return is correct.

image

**Comment by huacnlee** [comment]
This commit: https://github.com/zed-industries/zed/commit/c558a9e7f662426744c24ea3eacd135af07ac8f1 has fixed `cx.open_window` position on macOS primary screen.

image

**Comment by huacnlee** [comment]
And then, I wrote child window Popover can place with correct position now.

image

**Comment by ConradIrwin** [comment]
@huacnlee nice! Thank you very much for figuring this out

**Pull request merged**
