### PR TITLE
Update linux deps to include opensuse

### PR DESCRIPTION
**Pull request by eyecreate**
Release Notes:

- Added support for openSuse to Linux dependency installer script.

### CODE REVIEW

**Comment by eyecreate** [comment]
@cla-bot check

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
Hello! Thank you for adding this distro. Could you add the OpenSSL dependency that I just merged: https://github.com/zed-industries/zed/pull/8136?

**Comment by mikayla-maki** [comment]
I think we'd prefer if you did a rebase on main :)

**Comment by eyecreate** [comment]
Huh, I thought I did click rebase in github. Guess I'll need to do some manual fixing.

**Comment by mikayla-maki** [comment]
Thank you!

**Review by mikayla-maki — APPROVED** [review]

**Pull request merged**
