### PR TITLE
Add ability to display backgrounds for inlay hints

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR adds the ability to display backgrounds for inlay hints within the editor.

This is controlled by the new `inlay_hints.show_background` setting. This setting defaults to `false`.

To enable the setting, add the following to your `settings.json`:

```json
{
  "inlay_hints": {
    "enabled": true,
    "show_background": true
  }
}
```

When enabled, the inlay hint backgrounds will use the `hint.background` color from the theme.

| Disabled                                                                                                                                           | Enabled                                                                                                                                            |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| Screenshot 2024-09-17 at 4 21 53 PM | Screenshot 2024-09-17 at 4 21 43 PM |

Related issues:

- #12485
- #17392

Release Notes:

- Added an `inlay_hints.show_background` setting to allow displaying backgrounds for inlay hints in the editor.
  - This setting defaults to `false`.
  - If enabled, the inlay hint backgrounds will use the `hint.background` color from the theme.

### CODE REVIEW

**Comment by AlbertMarashi** [comment]
would love to see this for predictive texts as well, because it helps me distinguish the generated code vs my actual code

**Comment by maxdeviant** [comment]
> would love to see this for predictive texts as well, because it helps me distinguish the generated code vs my actual code

We can handle predictive text separately. I just wanted to focus on inlay hints, for now.

**Comment by AlbertMarashi** [comment]
@maxdeviant did you have an issue by any chance where inlay hint backgrounds were laid over the user selections, making the selection background invisible?

**Comment by HamzaFarhan** [comment]
> @maxdeviant did you have an issue by any chance where inlay hint backgrounds were laid over the user selections, making the selection background invisible?

Yes. I kind of solved it using this but I would love a better solution:
```json
"experimental.theme_overrides": {
    "editor.document_highlight.read_background": "#000000"
}
```

**Pull request merged**
