### PR TITLE
Fix scroll thumb

### PR DESCRIPTION
**Pull request by alygin**
Editor scrollbar has several issues that show up on large files:

- The thumb scrolls beyond the window.
- When dragged, the thumb goes out of sync with the mouse pointer.
- When the scrollbar trunk is clicked, the thumb jumps incorrectly.

https://github.com/zed-industries/zed/assets/2101250/320dba59-a526-4e68-99b3-1186271ba839

The reason is that the scrollbar now has two modes:
1. The "basic mode" for small files, when the thumb height correctly represents the visible area, i.e. the top of the thumb matches the top visible row (let's call it top-to-top sync), and the bottom of the thumb matches the bottom visible row.
2. The "extended mode" for large files, when thumb becomes too small and we have to impose minimal height to it. In this mode we have a vertical offset of the first row position inside the scrollbar, we try to position the thumb center-to-center with the editor.

...and the second mode is not implemented correctly. Also, mouse event handlers ignore it. It is possible to fix this implementation, but I'm not sure if it worth doing because it a) leads to some confusing cases (for instance, in the extended mode the first row marker is not at the top of the scrollbar), and b) differs from what all other editors do.

Here's a previous mentioning of this problem: https://github.com/zed-industries/zed/pull/9080#pullrequestreview-1927465293

This PR changes the "extended mode", making it synchronize the thumb top-to-top with the editor. It solves all the mentioned problems and makes the scroll thumb work the same whay as in other editors.

But if you want to stick to the idea of the center-to-center sync for large files, I can do that too.

Release Notes:

- Fixed scroll thumb behaviour.

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

- N/A

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you for coming back to this!

I've followed the aforementioned `option in project.rs` test from https://github.com/zed-industries/zed/pull/9080#pullrequestreview-1927465293 and found clicking improved generally (the consistency and precision of the current "top of the thumb to clicked place" approach is much better than before).

But still, there's something that makes the caret to jump around drastically in the `option` search case: seems that the jumps usually happen when I click on more blank spaces on the scrollbar and worsen if I start to click above-below-above-below-etc. the thumb.
When the project loads, it seems to be better and I can even click the entire project.rs scrollbar through without issues, but when it stops (and all error markers are off the scrollbar), I was never able to click top-to-bottom without the jumps.

Here's an example video, but it could get worse after some clicking:

https://github.com/zed-industries/zed/assets/2690773/4d6a7429-6321-4b35-a083-f17ecfde2ee6

**Comment by alygin** [comment]
> the consistency and precision of the current "top of the thumb to clicked place" approach is much better than before

Actually, when the user clicks the scrollbar, the approach is to scroll the "clicked row" to the center of the editor, which means the top of the thumb may be above the clicked place. But in large files, like `project.rs`, where one scrollbar pixel represents many editor rows, it's hard to notice. On relatively small files this centering is easily visible.

> I was never able to click top-to-bottom without the jumps.

Hm, that's interesting. I cannot reproduce it. Hundreds of clicks and not a single case of incorrect thumb positioning.

Do I understand correctly that if ther're no search results, everything works?

**Comment by alygin** [comment]
I found how to reproduce it. It has nothing to do with search results or any markers at all. It's also present in the stable version.

The problem occurs when the clicks also involve little draging. It makes MouseMoveEvent fire, and the calculation of the diff between mouse positions uses the wrong starting point.

I guess I'll add the fix of this problem to this PR.

**Comment by alygin** [comment]
Fixed

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you for the find, that was the thing!
So, apparently my clicking pattern becomes more abrupt with more items in the scroll panel, interesting 🙂 
I have tested the scrollbar clicks and those work very consistently for me now.

One last issue I'd like to discuss, since the PR is named so broadly:
in the same project.rs, around the line 4851, there's a place with 4 `option` query matches:

image

On the screenshot, those 4 results are almost at the very bottom of the screen, but the thumb shows that the matches are at the top of my screen.
IIRC, this is caused by the minimum thumb height requirements we put, which makes sense, but curious if we could do something else about it, to make it look more natural?
The only thought (bad) I have is to shift the thumb a bit more during the scrolling only.
Curious if you have any thoughts, but not insisting on any fix right now.

My issue with this thing is the fact that Rust files tend to get long, and the drift starts to be visible quite early on, by Rust standards: if I take `crates/editor/LICENSE-GPL` and append its contents to itself a few times to bloat the file up to ~2k lines, it already starts to drift for `show` query:

image

Here, I have on the very bottom the last match before large zero-matches area, and the thumb shows it's in the middle of my screen.

**Comment by alygin** [comment]
I see the problem, but I don't know a good soluton either. It looks like all the editors use the same approach (the one implemented in this PR).

> to shift the thumb a bit more during the scrolling only.

What kind of shifting do you mean?

I was thinking of highlighting the part of the thumb that really represents the visible area while scrolling (and maybe muting the other part of the thumb a bit), so the user could aim better:

изображение

But it has its limitations too. In `project.rs` the highlighted part will be only two or three pixels high on my laptop.

**Review by SomeoneToIgnore — APPROVED** [review]
Well, that idea looks much better than any of mine, so maybe it is the way out, after all.

Thank you for checking on the scrollbar!

**Pull request merged**
