### PR TITLE
Add default terminal binding for buffer search on Linux

### PR DESCRIPTION
**Pull request by VitorRamos**
Release Notes:

- Fixed find in Terminal: `ctrl-shift-f` (Linux)

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@VitorRamos On linux this should be `ctrl-shift-f` (like it is in gnome terminal). to avoid conflicting with terminal tools that use ctrl-f.

**Comment by ConradIrwin** [comment]
Thanks!

**Comment by SomeoneToIgnore** [comment]
Before, project search was invoked with cmd-shift-f, and now there's no keybinding for that at all - I would rather keep the project search binding.

**Comment by apricotbucket28** [comment]
> @VitorRamos On linux this should be `ctrl-shift-f` (like it is in gnome terminal). to avoid conflicting with terminal tools that use ctrl-f.

Hmm, you're right that both Gnome Terminal and Konsole have Ctrl+Shift+F as the shortcut, but I found that VSCode actually has it for Ctrl+F (possibly to not conflict with Ctrl+Shift+F and allow opening project search from inside the terminal).

I know I could change it myself, but given that this is called the "VSCode" keymap in the welcome screen maybe it makes more sense to match that behaviour?

**Comment by SomeoneToIgnore** [comment]
Honestly, I'm quite lost in the keymaps, Linux especially, so trusted @notpeter for knowing what's better.
I can only state the obvious that project search has to be accessible via some shortcut.
I agree that keeping closer to VSCode in that keymap seems reasonable, and it keeps ctrl-shift-f for project search as I've just rechecked.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/16845 fixed this particular issue, as this PR was utterly wrong: it added a terminal-related binding into `"context": "!Terminal",` context...

**Pull request merged**
