### PR TITLE
c: Fix incorrect indentation after `if` statements

### LINKED ISSUE #13924: Editor auto-indents curly braces when typed under an if statement in C
### Check for existing issues

- [X] Completed

### **The issue:**
Whenever I try to type in curly braces under an if statement in C, the Zed editor automatically adds an indent before them. I have turned code formatting off.

### **Steps to reproduce:**
1. Start typing an if statement
2. Press enter / return to go to the next line
3. Type the left curly bracket
4. The editor should automatically add the right bracket and shift the entire thing one tab towards right

Screen recording of the issue and a screenshot of my config file are attached with this bug report

https://github.com/zed-industries/zed/assets/145113/4156d580-9f53-4d30-9455-0209f093a72f

Screenshot 2024-07-08 at 12 52 19 PM

### Environment

Zed: v0.142.6 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

N/A

### PR DESCRIPTION
**Pull request by Louis-Ladd**
- Closes #13924 

Release Notes:

- curly braces won't indent after If, else if, else

### CODE REVIEW

**Comment by Louis-Ladd** [comment]
@cla-bot check

**Comment by Louis-Ladd** [comment]
This PR fails the test_c_autoindent
`
if ()
{
}
`
`
if () {
}
`
Running the build myself and testing both styles correctly indents for me so I'm not sure why it's failing that test.

**Comment by MrSubidubi** [comment]
The issue is that whilst your described cases now work properly, the case originally causing this behavior stopped working with your changes. 

This is the case
```
if ()
    single_statement_to_be_executed
```
which is an if-statement with just a single statement and without brackets. 

The removal of this auto-indentation is also what [fails the tests](https://github.com/zed-industries/zed/blob/0a7468c89f6dc72eeb27c0ea1113c95ee100ae2c/crates/languages/src/c.rs#L323). The issue you referenced also stated that the indentation should only be removed once brackets are inserted.

**Comment by SomeoneToIgnore** [comment]
Looks quite stale, so will close this.

**Pull request closed without merging**
